PF Firewall: Net_SSH2 Class Reference
Net_SSH2 Class Reference
Public Member Functions
__construct ($host, $port=22, $timeout=10)
Default Constructor.
Net_SSH2 ($host, $port=22, $timeout=10)
PHP4 compatible Default Constructor.
setCryptoEngine ($engine)
Set Crypto Engine Mode.
sendIdentificationStringFirst ()
Send Identification String First.
sendIdentificationStringLast ()
Send Identification String Last.
sendKEXINITFirst ()
Send SSH_MSG_KEXINIT First.
sendKEXINITLast ()
Send SSH_MSG_KEXINIT Last.
_connect ()
Connect to an SSHv2 server.
_generate_identifier ()
Generates the SSH identifier.
_key_exchange ($kexinit_payload_server=false)
Key Exchange.
_encryption_algorithm_to_key_size ($algorithm)
Maps an encryption algorithm name to the number of key bytes.
_encryption_algorithm_to_crypt_instance ($algorithm)
Maps an encryption algorithm name to an instance of a subclass of \phpseclib\Crypt\Base.
_bad_algorithm_candidate ($algorithm)
Tests whether or not proposed algorithm has a potential for issues.
login ($username)
Login.
_login ($username)
Login Helper.
_login_helper ($username, $password=null)
Login Helper.
_keyboard_interactive_login ($username, $password)
Login via keyboard-interactive authentication.
_keyboard_interactive_process ()
Handle the keyboard-interactive requests / responses.
_ssh_agent_login ($username, $agent)
Login with an ssh-agent provided key.
_privatekey_login ($username, $privatekey)
Login with an RSA private key.
setTimeout ($timeout)
Set Timeout.
setKeepAlive ($interval)
Set Keep Alive.
getStdError ()
Get the output from stdError.
exec ($command, $callback=null)
Execute Command.
_initShell ()
Creates an interactive shell.
_get_interactive_channel ()
Return the channel to be used with read() / write()
_get_open_channel ()
Return an available open channel.
read ($expect='', $mode=NET_SSH2_READ_SIMPLE)
Returns the output of an interactive shell.
write ($cmd)
Inputs a command into an interactive shell.
startSubsystem ($subsystem)
Start a subsystem.
stopSubsystem ()
Stops a subsystem.
reset ()
Closes a channel.
isTimeout ()
Is timeout?
disconnect ()
Disconnect.
__destruct ()
Destructor.
isConnected ()
Is the connection still active?
isAuthenticated ()
Have you successfully been logged in?
ping ()
Pings a server connection, or tries to reconnect if the connection has gone down.
_reconnect ()
In situ reconnect method.
_reset_connection ($reason)
Resets a connection for re-use.
_get_binary_packet ($skip_channel_filter=false)
Gets Binary Packets.
_filter ($payload, $skip_channel_filter)
Filter Binary Packets.
enableQuietMode ()
Enable Quiet Mode.
disableQuietMode ()
Disable Quiet Mode.
isQuietModeEnabled ()
Returns whether Quiet Mode is enabled or not.
enablePTY ()
Enable request-pty when using exec()
disablePTY ()
Disable request-pty when using exec()
isPTYEnabled ()
Returns whether request-pty is enabled or not.
_get_channel_packet ($client_channel, $skip_extended=false)
Gets channel data.
_send_binary_packet ($data, $logged=null)
Sends Binary Packets.
_append_log ($message_number, $message)
Logs data packets.
_send_channel_packet ($client_channel, $data)
Sends channel data.
_close_channel ($client_channel, $want_reply=false)
Closes and flushes a channel.
_disconnect ($reason)
Disconnect.
_string_shift (&$string, $index=1)
String Shift.
_define_array ()
Define Array.
getLog ()
Returns a log of the packets that have been sent and received.
_format_log ($message_log, $message_number_log)
Formats a log for printing.
_format_log_helper ($matches)
Helper function for _format_log.
_on_channel_open ()
Helper function for agent->_on_channel_open()
_array_intersect_first ($array1, $array2)
Returns the first value of the intersection of two arrays or false if the intersection is empty.
getErrors ()
Returns all errors.
getLastError ()
Returns the last error.
getServerIdentification ()
Return the server identification.
getKexAlgorithms ()
Return a list of the key exchange algorithms the server supports.
getServerHostKeyAlgorithms ()
Return a list of the host key (public key) algorithms the server supports.
getEncryptionAlgorithmsClient2Server ()
Return a list of the (symmetric key) encryption algorithms the server supports, when receiving stuff from the client.
getEncryptionAlgorithmsServer2Client ()
Return a list of the (symmetric key) encryption algorithms the server supports, when sending stuff to the client.
getMACAlgorithmsClient2Server ()
Return a list of the MAC algorithms the server supports, when receiving stuff from the client.
getMACAlgorithmsServer2Client ()
Return a list of the MAC algorithms the server supports, when sending stuff to the client.
getCompressionAlgorithmsClient2Server ()
Return a list of the compression algorithms the server supports, when receiving stuff from the client.
getCompressionAlgorithmsServer2Client ()
Return a list of the compression algorithms the server supports, when sending stuff to the client.
getLanguagesServer2Client ()
Return a list of the languages the server supports, when sending stuff to the client.
getLanguagesClient2Server ()
Return a list of the languages the server supports, when receiving stuff from the client.
getServerAlgorithms ()
Returns a list of algorithms the server supports.
getSupportedKEXAlgorithms ()
Returns a list of KEX algorithms that phpseclib supports.
getSupportedHostKeyAlgorithms ()
Returns a list of host key algorithms that phpseclib supports.
getSupportedEncryptionAlgorithms ()
Returns a list of symmetric key algorithms that phpseclib supports.
getSupportedMACAlgorithms ()
Returns a list of MAC algorithms that phpseclib supports.
getSupportedCompressionAlgorithms ()
Returns a list of compression algorithms that phpseclib supports.
getAlgorithmsNegotiated ()
Return list of negotiated algorithms.
setPreferredAlgorithms ($methods)
Accepts an associative array with up to four parameters as described at https://www.php.net/manual/en/function.ssh2-connect.php
getBannerMessage ()
Returns the banner message.
getServerPublicHostKey ()
Returns the server public host key.
getExitStatus ()
Returns the exit status of an SSH command or false.
getWindowColumns ()
Returns the number of columns for the terminal window size.
getWindowRows ()
Returns the number of rows for the terminal window size.
setWindowColumns ($value)
Sets the number of columns for the terminal window size.
setWindowRows ($value)
Sets the number of rows for the terminal window size.
setWindowSize ($columns=80, $rows=24)
Sets the number of columns and rows for the terminal window size.
_updateLogHistory ($old, $new)
Update packet types in log history.
getAuthMethodsToContinue ()
Return the list of authentication methods that may productively continue authentication.
enableSmartMFA ()
Enables "smart" multi-factor authentication (MFA)
disableSmartMFA ()
Disables "smart" multi-factor authentication (MFA)
Data Fields
$identifier
$fsock
$bitmap = 0
$errors = array()
$server_identifier = false
$kex_algorithms = false
$kex_algorithm = false
$kex_dh_group_size_min = 1536
$kex_dh_group_size_preferred = 2048
$kex_dh_group_size_max = 4096
$server_host_key_algorithms = false
$encryption_algorithms_client_to_server = false
$encryption_algorithms_server_to_client = false
$mac_algorithms_client_to_server = false
$mac_algorithms_server_to_client = false
$compression_algorithms_client_to_server = false
$compression_algorithms_server_to_client = false
$languages_server_to_client = false
$languages_client_to_server = false
$preferred = array()
$encrypt_block_size = 8
$decrypt_block_size = 8
$decrypt = false
$encrypt = false
$hmac_create = false
$hmac_check = false
$hmac_size = false
$server_public_host_key
$session_id = false
$exchange_hash = false
$message_numbers = array()
$disconnect_reasons = array()
$channel_open_failure_reasons = array()
$terminal_modes = array()
$channel_extended_data_type_codes = array()
$send_seq_no = 0
$get_seq_no = 0
$server_channels = array()
$channel_buffers = array()
$channel_status = array()
$packet_size_client_to_server = array()
$message_number_log = array()
$message_log = array()
$window_size = 0x7FFFFFFF
$window_resize = 0x40000000
$window_size_server_to_client = array()
$window_size_client_to_server = array()
$signature = ''
$signature_format = ''
$interactiveBuffer = ''
$log_size
$timeout
Timeout.
$curTimeout
Current Timeout.
$keepAlive
Keep Alive Interval.
$realtime_log_file
$realtime_log_size
$signature_validated = false
$realtime_log_wrap
Real-time log file wrap boolean.
$quiet_mode = false
Flag to suppress stderr from output.
$last_packet
$exit_status
$request_pty = false
$in_request_pty_exec = false
$in_subsystem
$stdErrorLog
$last_interactive_response = ''
$keyboard_requests_responses = array()
$banner_message = ''
$is_timeout = false
$log_boundary = ':'
$log_long_width = 65
$log_short_width = 16
$host
$port
$windowColumns = 80
$windowRows = 24
$crypto_engine = false
$agent
$send_id_string_first = true
$send_kex_first = true
$bad_key_size_fix = false
$retry_connect = false
$binary_packet_buffer = false
$preferred_signature_format = false
$auth = array()
$auth_methods_to_continue = null
$compress = NET_SSH2_COMPRESSION_NONE
$decompress = NET_SSH2_COMPRESSION_NONE
$compress_context
$decompress_context
$regenerate_compression_context = false
$regenerate_decompression_context = false
$smartMFA = true
Detailed Description
Definition at line 177 of file SSH2.php.
Constructor & Destructor Documentation
__construct()
__construct ($host, $port = 22, $timeout = 10)
Default Constructor.
$host can either be a string, representing the host, or a stream resource.
Parameters
mixed $host
int $port
int $timeout
See also
self::login()
Returns
Net_SSH2 @access public
Definition at line 1072 of file SSH2.php.
    {
        global $VIEW_PATH;
        // Include Math_BigInteger
        // Used to do Diffie-Hellman key exchange and DSA/RSA signature verification.
        if (!class_exists('Math_BigInteger')) {
            include_once $VIEW_PATH.'/lib/phpseclib/Math/BigInteger.php';
        }
        if (!function_exists('crypt_random_string')) {
            include_once $VIEW_PATH.'/lib/phpseclib/Crypt/Random.php';
        }
        if (!class_exists('Crypt_Hash')) {
            include_once $VIEW_PATH.'/lib/phpseclib/Crypt/Hash.php';
        }
        // include Crypt_Base so constants can be defined for setCryptoEngine()
        if (!class_exists('Crypt_Base')) {
            include_once $VIEW_PATH.'/lib/phpseclib/Crypt/Base.php';
        }
        $this->message_numbers = array(
            1 => 'NET_SSH2_MSG_DISCONNECT',
            2 => 'NET_SSH2_MSG_IGNORE',
            3 => 'NET_SSH2_MSG_UNIMPLEMENTED',
            4 => 'NET_SSH2_MSG_DEBUG',
            5 => 'NET_SSH2_MSG_SERVICE_REQUEST',
            6 => 'NET_SSH2_MSG_SERVICE_ACCEPT',
            20 => 'NET_SSH2_MSG_KEXINIT',
            21 => 'NET_SSH2_MSG_NEWKEYS',
            30 => 'NET_SSH2_MSG_KEXDH_INIT',
            31 => 'NET_SSH2_MSG_KEXDH_REPLY',
            50 => 'NET_SSH2_MSG_USERAUTH_REQUEST',
            51 => 'NET_SSH2_MSG_USERAUTH_FAILURE',
            52 => 'NET_SSH2_MSG_USERAUTH_SUCCESS',
            53 => 'NET_SSH2_MSG_USERAUTH_BANNER',
            80 => 'NET_SSH2_MSG_GLOBAL_REQUEST',
            81 => 'NET_SSH2_MSG_REQUEST_SUCCESS',
            82 => 'NET_SSH2_MSG_REQUEST_FAILURE',
            90 => 'NET_SSH2_MSG_CHANNEL_OPEN',
            91 => 'NET_SSH2_MSG_CHANNEL_OPEN_CONFIRMATION',
            92 => 'NET_SSH2_MSG_CHANNEL_OPEN_FAILURE',
            93 => 'NET_SSH2_MSG_CHANNEL_WINDOW_ADJUST',
            94 => 'NET_SSH2_MSG_CHANNEL_DATA',
            95 => 'NET_SSH2_MSG_CHANNEL_EXTENDED_DATA',
            96 => 'NET_SSH2_MSG_CHANNEL_EOF',
            97 => 'NET_SSH2_MSG_CHANNEL_CLOSE',
            98 => 'NET_SSH2_MSG_CHANNEL_REQUEST',
            99 => 'NET_SSH2_MSG_CHANNEL_SUCCESS',
            100 => 'NET_SSH2_MSG_CHANNEL_FAILURE'
        );
        $this->disconnect_reasons = array(
            1 => 'NET_SSH2_DISCONNECT_HOST_NOT_ALLOWED_TO_CONNECT',
            2 => 'NET_SSH2_DISCONNECT_PROTOCOL_ERROR',
            3 => 'NET_SSH2_DISCONNECT_KEY_EXCHANGE_FAILED',
            4 => 'NET_SSH2_DISCONNECT_RESERVED',
            5 => 'NET_SSH2_DISCONNECT_MAC_ERROR',
            6 => 'NET_SSH2_DISCONNECT_COMPRESSION_ERROR',
            7 => 'NET_SSH2_DISCONNECT_SERVICE_NOT_AVAILABLE',
            8 => 'NET_SSH2_DISCONNECT_PROTOCOL_VERSION_NOT_SUPPORTED',
            9 => 'NET_SSH2_DISCONNECT_HOST_KEY_NOT_VERIFIABLE',
            10 => 'NET_SSH2_DISCONNECT_CONNECTION_LOST',
            11 => 'NET_SSH2_DISCONNECT_BY_APPLICATION',
            12 => 'NET_SSH2_DISCONNECT_TOO_MANY_CONNECTIONS',
            13 => 'NET_SSH2_DISCONNECT_AUTH_CANCELLED_BY_USER',
            14 => 'NET_SSH2_DISCONNECT_NO_MORE_AUTH_METHODS_AVAILABLE',
            15 => 'NET_SSH2_DISCONNECT_ILLEGAL_USER_NAME'
        );
        $this->channel_open_failure_reasons = array(
            1 => 'NET_SSH2_OPEN_ADMINISTRATIVELY_PROHIBITED'
        );
        $this->terminal_modes = array(
            0 => 'NET_SSH2_TTY_OP_END'
        );
        $this->channel_extended_data_type_codes = array(
            1 => 'NET_SSH2_EXTENDED_DATA_STDERR'
        );
        $this->_define_array(
            $this->message_numbers,
            $this->disconnect_reasons,
            $this->channel_open_failure_reasons,
            $this->terminal_modes,
            $this->channel_extended_data_type_codes,
            array(60 => 'NET_SSH2_MSG_USERAUTH_PASSWD_CHANGEREQ'),
            array(60 => 'NET_SSH2_MSG_USERAUTH_PK_OK'),
            array(60 => 'NET_SSH2_MSG_USERAUTH_INFO_REQUEST',
                  61 => 'NET_SSH2_MSG_USERAUTH_INFO_RESPONSE'),
            // RFC 4419 - diffie-hellman-group-exchange-sha{1,256}
            array(30 => 'NET_SSH2_MSG_KEXDH_GEX_REQUEST_OLD',
                  31 => 'NET_SSH2_MSG_KEXDH_GEX_GROUP',
                  32 => 'NET_SSH2_MSG_KEXDH_GEX_INIT',
                  33 => 'NET_SSH2_MSG_KEXDH_GEX_REPLY',
                  34 => 'NET_SSH2_MSG_KEXDH_GEX_REQUEST')
        );
        if (is_resource($host)) {
            $this->fsock = $host;
            return;
        }
        if (is_string($host)) {
            $this->host = $host;
            $this->port = $port;
            $this->timeout = $timeout;
        }
    }
References $VIEW_PATH, and _define_array().
Referenced by Net_SSH2().
__destruct()
__destruct ()
Destructor.
Will be called, automatically, if you're supporting just PHP5. If you're supporting PHP4, you'll need to call disconnect().
@access public
Definition at line 3371 of file SSH2.php.
    {
        $this->disconnect();
    }
References disconnect().
Member Function Documentation
_append_log()
_append_log ($message_number, $message)
Logs data packets.
Makes sure that only the last 1MB worth of packets will be logged
Parameters
string $message_number
string $message @access private
Definition at line 4269 of file SSH2.php.
    {
        // remove the byte identifying the message type from all but the first two messages (ie. the identification strings)
        if (strlen($message_number) > 2) {
            $this->_string_shift($message);
        }
        switch (NET_SSH2_LOGGING) {
            // useful for benchmarks
            case NET_SSH2_LOG_SIMPLE:
                $this->message_number_log[] = $message_number;
                break;
            // the most useful log for SSH2
            case NET_SSH2_LOG_COMPLEX:
                $this->message_number_log[] = $message_number;
                $this->log_size+= strlen($message);
                $this->message_log[] = $message;
                while ($this->log_size > NET_SSH2_LOG_MAX_SIZE) {
                    $this->log_size-= strlen(array_shift($this->message_log));
                    array_shift($this->message_number_log);
                }
                break;
            // dump the output out realtime; packets may be interspersed with non packets,
            // passwords won't be filtered out and select other packets may not be correctly
            // identified
            case NET_SSH2_LOG_REALTIME:
                switch (PHP_SAPI) {
                    case 'cli':
                        $start = $stop = "\r\n";
                        break;
                    default:
                        $start = '<pre>';
                        $stop = '</pre>';
                }
                echo $start . $this->_format_log(array($message), array($message_number)) . $stop;
                @flush();
                @ob_flush();
                break;
            // basically the same thing as NET_SSH2_LOG_REALTIME with the caveat that NET_SSH2_LOG_REALTIME_FILE
            // needs to be defined and that the resultant log file will be capped out at NET_SSH2_LOG_MAX_SIZE.
            // the earliest part of the log file is denoted by the first <<< START >>> and is not going to necessarily
            // at the beginning of the file
            case NET_SSH2_LOG_REALTIME_FILE:
                if (!isset($this->realtime_log_file)) {
                    // PHP doesn't seem to like using constants in fopen()
                    $filename = NET_SSH2_LOG_REALTIME_FILENAME;
                    $fp = fopen($filename, 'w');
                    $this->realtime_log_file = $fp;
                }
                if (!is_resource($this->realtime_log_file)) {
                    break;
                }
                $entry = $this->_format_log(array($message), array($message_number));
                if ($this->realtime_log_wrap) {
                    $temp = "<<< START >>>\r\n";
                    $entry.= $temp;
                    fseek($this->realtime_log_file, ftell($this->realtime_log_file) - strlen($temp));
                }
                $this->realtime_log_size+= strlen($entry);
                if ($this->realtime_log_size > NET_SSH2_LOG_MAX_SIZE) {
                    fseek($this->realtime_log_file, 0);
                    $this->realtime_log_size = strlen($entry);
                    $this->realtime_log_wrap = true;
                }
                fputs($this->realtime_log_file, $entry);
        }
    }
References _format_log(), _string_shift(), NET_SSH2_LOG_COMPLEX, NET_SSH2_LOG_MAX_SIZE, NET_SSH2_LOG_REALTIME, NET_SSH2_LOG_REALTIME_FILE, and NET_SSH2_LOG_SIMPLE.
Referenced by _connect(), _get_binary_packet(), and _send_binary_packet().
_array_intersect_first()
_array_intersect_first ($array1, $array2)
Returns the first value of the intersection of two arrays or false if the intersection is empty.
The order is defined by the first parameter.
Parameters
array $array1
array $array2
Returns
mixed False if intersection is empty, else intersected value. @access private
Definition at line 4585 of file SSH2.php.
    {
        foreach ($array1 as $value) {
            if (in_array($value, $array2)) {
                return $value;
            }
        }
        return false;
    }
Referenced by _key_exchange().
_bad_algorithm_candidate()
_bad_algorithm_candidate ($algorithm)
Tests whether or not proposed algorithm has a potential for issues.
https://bugzilla.mindrot.org/show_bug.cgi?id=1291 string $algorithm Name of the encryption algorithm bool private
Definition at line 2213 of file SSH2.php.
    {
        switch ($algorithm) {
            case 'arcfour256':
            case 'aes192-ctr':
            case 'aes256-ctr':
                return true;
        }
        return false;
    }
Referenced by _encryption_algorithm_to_key_size(), and _get_binary_packet().
_close_channel()
_close_channel ($client_channel, $want_reply = false)
Closes and flushes a channel.
Net_SSH2 doesn't properly close most channels. For exec() channels are normally closed by the server and for SFTP channels are presumably closed when the client disconnects. This functions is intended for SCP more than anything.
Parameters
int $client_channel
bool $want_reply
Returns
bool @access private
Definition at line 4395 of file SSH2.php.
    {
        // see http://tools.ietf.org/html/rfc4254#section-5.3
        $this->_send_binary_packet(pack('CN', NET_SSH2_MSG_CHANNEL_EOF, $this->server_channels[$client_channel]));
        if (!$want_reply) {
            $this->_send_binary_packet(pack('CN', NET_SSH2_MSG_CHANNEL_CLOSE, $this->server_channels[$client_channel]));
        }
        $this->channel_status[$client_channel] = NET_SSH2_MSG_CHANNEL_CLOSE;
        $this->curTimeout = 5;
        while (!is_bool($this->_get_channel_packet($client_channel))) {
        }
        if ($this->is_timeout) {
            $this->disconnect();
        }
        if ($want_reply) {
            $this->_send_binary_packet(pack('CN', NET_SSH2_MSG_CHANNEL_CLOSE, $this->server_channels[$client_channel]));
        }
        if ($this->bitmap & NET_SSH2_MASK_SHELL) {
            $this->bitmap&= ~NET_SSH2_MASK_SHELL;
        }
    }
References _get_channel_packet(), _send_binary_packet(), disconnect(), and NET_SSH2_MASK_SHELL.
Referenced by _get_channel_packet(), disablePTY(), exec(), ping(), reset(), and stopSubsystem().
_connect()
_connect ()
Connect to an SSHv2 server.
Returns
bool @access private
Definition at line 1273 of file SSH2.php.
    {
        if ($this->bitmap & NET_SSH2_MASK_CONSTRUCTOR) {
            return false;
        }
        $this->bitmap |= NET_SSH2_MASK_CONSTRUCTOR;
        $this->curTimeout = $this->timeout;
        $this->last_packet = strtok(microtime(), ' ') + strtok(''); // == microtime(true) in PHP5
        if (!is_resource($this->fsock)) {
            $start = strtok(microtime(), ' ') + strtok(''); // http://php.net/microtime#61838
            // with stream_select a timeout of 0 means that no timeout takes place;
            // with fsockopen a timeout of 0 means that you instantly timeout
            // to resolve this incompatibility a timeout of 100,000 will be used for fsockopen if timeout is 0
            $this->fsock = @fsockopen($this->host, $this->port, $errno, $errstr, $this->curTimeout == 0 ? 100000 : $this->curTimeout);
            if (!$this->fsock) {
                $host = $this->host . ':' . $this->port;
                user_error(rtrim("Cannot connect to $host. Error $errno. $errstr"));
                return false;
            }
            $elapsed = strtok(microtime(), ' ') + strtok('') - $start;
            if ($this->curTimeout) {
                $this->curTimeout-= $elapsed;
                if ($this->curTimeout < 0) {
                    $this->is_timeout = true;
                    return false;
                }
            }
        }
        $this->identifier = $this->_generate_identifier();
        if ($this->send_id_string_first) {
            fputs($this->fsock, $this->identifier . "\r\n");
        }
        /* According to the SSH2 specs,
          "The server MAY send other lines of data before sending the version
           string.  Each line SHOULD be terminated by a Carriage Return and Line
           Feed.  Such lines MUST NOT begin with "SSH-", and SHOULD be encoded
           in ISO-10646 UTF-8 [RFC3629] (language is not specified).  Clients
           MUST be able to process such lines." */
        $temp = '';
        $extra = '';
        while (!feof($this->fsock) && !preg_match('#^SSH-(\d\.\d+)#', $temp, $matches)) {
            if (substr($temp, -2) == "\r\n") {
                $extra.= $temp;
                $temp = '';
            }
            if ($this->curTimeout) {
                if ($this->curTimeout < 0) {
                    $this->is_timeout = true;
                    return false;
                }
                $read = array($this->fsock);
                $write = $except = null;
                $start = strtok(microtime(), ' ') + strtok('');
                $sec = floor($this->curTimeout);
                $usec = 1000000 * ($this->curTimeout - $sec);
                // on windows this returns a "Warning: Invalid CRT parameters detected" error
                // the !count() is done as a workaround for <https://bugs.php.net/42682>
                if (!@stream_select($read, $write, $except, $sec, $usec) && !count($read)) {
                    $this->is_timeout = true;
                    return false;
                }
                $elapsed = strtok(microtime(), ' ') + strtok('') - $start;
                $this->curTimeout-= $elapsed;
            }
            $subtemp = fgets($this->fsock, 255);
            if ($subtemp === '' || $subtemp === false) {
                return false;
            }
            $temp.= $subtemp;
        }
        if (feof($this->fsock)) {
            $this->bitmap = 0;
            user_error('Connection closed by server');
            return false;
        }
        if (defined('NET_SSH2_LOGGING')) {
            $this->_append_log('<-', $extra . $temp);
            $this->_append_log('->', $this->identifier . "\r\n");
        }
        $this->server_identifier = trim($temp, "\r\n");
        if (strlen($extra)) {
            $this->errors[] = $extra;
        }
        if (version_compare($matches[1], '1.99', '<')) {
            user_error("Cannot connect to SSH $matches[1] servers");
            return false;
        }
        if (!$this->send_id_string_first) {
            fputs($this->fsock, $this->identifier . "\r\n");
        }
        if (!$this->send_kex_first) {
            $response = $this->_get_binary_packet();
            if ($response === false) {
                $this->bitmap = 0;
                user_error('Connection closed by server');
                return false;
            }
            if (!strlen($response) || ord($response[0]) != NET_SSH2_MSG_KEXINIT) {
                user_error('Expected SSH_MSG_KEXINIT');
                return false;
            }
            if (!$this->_key_exchange($response)) {
                return false;
            }
        }
        if ($this->send_kex_first && !$this->_key_exchange()) {
            return false;
        }
        $this->bitmap|= NET_SSH2_MASK_CONNECTED;
        return true;
    }
References _append_log(), _generate_identifier(), _get_binary_packet(), _key_exchange(), NET_SSH2_MASK_CONNECTED, and NET_SSH2_MASK_CONSTRUCTOR.
Referenced by _login(), _login_helper(), _reconnect(), getAlgorithmsNegotiated(), getCompressionAlgorithmsClient2Server(), getCompressionAlgorithmsServer2Client(), getEncryptionAlgorithmsClient2Server(), getEncryptionAlgorithmsServer2Client(), getKexAlgorithms(), getLanguagesClient2Server(), getLanguagesServer2Client(), getMACAlgorithmsClient2Server(), getMACAlgorithmsServer2Client(), getServerAlgorithms(), getServerHostKeyAlgorithms(), getServerIdentification(), and getServerPublicHostKey().
_define_array()
_define_array ()
Define Array.
Takes any number of arrays whose indices are integers and whose values are strings and defines a bunch of named constants from it, using the value as the name of the constant and the index as the value of the constant. If any of the constants that would be defined already exists, none of the constants will be defined.
@access private
Definition at line 4473 of file SSH2.php.
    {
        $args = func_get_args();
        foreach ($args as $arg) {
            foreach ($arg as $key => $value) {
                if (!defined($value)) {
                    define($value, $key);
                } else {
                    break 2;
                }
            }
        }
    }
References $args.
Referenced by __construct().
_disconnect()
_disconnect ($reason)
Disconnect.
Parameters
int $reason
Returns
bool @access private
Definition at line 4432 of file SSH2.php.
    {
        if ($this->bitmap & NET_SSH2_MASK_CONNECTED) {
            $data = pack('CNNa*Na*', NET_SSH2_MSG_DISCONNECT, $reason, 0, '', 0, '');
            $this->_send_binary_packet($data);
        }
        $this->bitmap = 0;
        if (is_resource($this->fsock) && get_resource_type($this->fsock) == 'stream') {
            fclose($this->fsock);
        }
        return false;
    }
References _send_binary_packet(), and NET_SSH2_MASK_CONNECTED.
Referenced by _filter(), _get_channel_packet(), _initShell(), _key_exchange(), _login_helper(), _privatekey_login(), _reset_connection(), disconnect(), exec(), and getServerPublicHostKey().
_encryption_algorithm_to_crypt_instance()
_encryption_algorithm_to_crypt_instance ($algorithm)
Maps an encryption algorithm name to an instance of a subclass of \phpseclib\Crypt\Base.
Parameters
string $algorithm Name of the encryption algorithm
Returns
mixed Instance of \phpseclib\Crypt\Base or null for unknown @access private
Definition at line 2137 of file SSH2.php.
    {
        global $VIEW_PATH;
        switch ($algorithm) {
            case '3des-cbc':
                if (!class_exists('Crypt_TripleDES')) {
                    include_once $VIEW_PATH.'/lib/phpseclib/Crypt/TripleDES.php';
                }
                return new Crypt_TripleDES();
            case '3des-ctr':
                if (!class_exists('Crypt_TripleDES')) {
                    include_once $VIEW_PATH.'/lib/phpseclib/Crypt/TripleDES.php';
                }
                return new Crypt_TripleDES(CRYPT_DES_MODE_CTR);
            case 'aes256-cbc':
            case 'aes192-cbc':
            case 'aes128-cbc':
                if (!class_exists('Crypt_Rijndael')) {
                    include_once $VIEW_PATH.'/lib/phpseclib/Crypt/Rijndael.php';
                }
                return new Crypt_Rijndael();
            case 'aes256-ctr':
            case 'aes192-ctr':
            case 'aes128-ctr':
                if (!class_exists('Crypt_Rijndael')) {
                    include_once $VIEW_PATH.'/lib/phpseclib/Crypt/Rijndael.php';
                }
                return new Crypt_Rijndael(CRYPT_RIJNDAEL_MODE_CTR);
            case 'blowfish-cbc':
                if (!class_exists('Crypt_Blowfish')) {
                    include_once $VIEW_PATH.'/lib/phpseclib/Crypt/Blowfish.php';
                }
                return new Crypt_Blowfish();
            case 'blowfish-ctr':
                if (!class_exists('Crypt_Blowfish')) {
                    include_once $VIEW_PATH.'/lib/phpseclib/Crypt/Blowfish.php';
                }
                return new Crypt_Blowfish(CRYPT_BLOWFISH_MODE_CTR);
            case 'twofish128-cbc':
            case 'twofish192-cbc':
            case 'twofish256-cbc':
            case 'twofish-cbc':
                if (!class_exists('Crypt_Twofish')) {
                    include_once $VIEW_PATH.'/lib/phpseclib/Crypt/Twofish.php';
                }
                return new Crypt_Twofish();
            case 'twofish128-ctr':
            case 'twofish192-ctr':
            case 'twofish256-ctr':
                if (!class_exists('Crypt_Twofish')) {
                    include_once $VIEW_PATH.'/lib/phpseclib/Crypt/Twofish.php';
                }
                return new Crypt_Twofish(CRYPT_TWOFISH_MODE_CTR);
            case 'arcfour':
            case 'arcfour128':
            case 'arcfour256':
                if (!class_exists('Crypt_RC4')) {
                    include_once $VIEW_PATH.'/lib/phpseclib/Crypt/RC4.php';
                }
                return new Crypt_RC4();
            case 'none':
                //return new Crypt_Null();
        }
        return null;
    }
References $VIEW_PATH, CRYPT_BLOWFISH_MODE_CTR, CRYPT_DES_MODE_CTR, CRYPT_RIJNDAEL_MODE_CTR, and CRYPT_TWOFISH_MODE_CTR.
Referenced by _key_exchange(), and getSupportedEncryptionAlgorithms().
_encryption_algorithm_to_key_size()
_encryption_algorithm_to_key_size ($algorithm)
Maps an encryption algorithm name to the number of key bytes.
Parameters
string $algorithm Name of the encryption algorithm
Returns
int|null Number of bytes as an integer or null for unknown @access private
Definition at line 2093 of file SSH2.php.
    {
        if ($this->bad_key_size_fix && $this->_bad_algorithm_candidate($algorithm)) {
            return 16;
        }
        switch ($algorithm) {
            case 'none':
                return 0;
            case 'aes128-cbc':
            case 'aes128-ctr':
            case 'arcfour':
            case 'arcfour128':
            case 'blowfish-cbc':
            case 'blowfish-ctr':
            case 'twofish128-cbc':
            case 'twofish128-ctr':
                return 16;
            case '3des-cbc':
            case '3des-ctr':
            case 'aes192-cbc':
            case 'aes192-ctr':
            case 'twofish192-cbc':
            case 'twofish192-ctr':
                return 24;
            case 'aes256-cbc':
            case 'aes256-ctr':
            case 'arcfour256':
            case 'twofish-cbc':
            case 'twofish256-cbc':
            case 'twofish256-ctr':
                return 32;
        }
        return null;
    }
References _bad_algorithm_candidate().
Referenced by _key_exchange().
_filter()
_filter ($payload, $skip_channel_filter)
Filter Binary Packets.
Because some binary packets need to be ignored...
See also
self::_get_binary_packet()
Returns
string @access private
Definition at line 3671 of file SSH2.php.
    {
        switch (ord($payload[0])) {
            case NET_SSH2_MSG_DISCONNECT:
                $this->_string_shift($payload, 1);
                if (strlen($payload) < 8) {
                    return false;
                }
                extract(unpack('Nreason_code/Nlength', $this->_string_shift($payload, 8)));
                $this->errors[] = 'SSH_MSG_DISCONNECT: ' . $this->disconnect_reasons[$reason_code] . "\r\n" . $this->_string_shift($payload, $length);
                $this->bitmap = 0;
                return false;
            case NET_SSH2_MSG_IGNORE:
                $payload = $this->_get_binary_packet($skip_channel_filter);
                break;
            case NET_SSH2_MSG_DEBUG:
                $this->_string_shift($payload, 2);
                if (strlen($payload) < 4) {
                    return false;
                }
                extract(unpack('Nlength', $this->_string_shift($payload, 4)));
                $this->errors[] = 'SSH_MSG_DEBUG: ' . $this->_string_shift($payload, $length);
                $payload = $this->_get_binary_packet($skip_channel_filter);
                break;
            case NET_SSH2_MSG_UNIMPLEMENTED:
                return false;
            case NET_SSH2_MSG_KEXINIT:
                if ($this->session_id !== false) {
                    $this->send_kex_first = false;
                    if (!$this->_key_exchange($payload)) {
                        $this->bitmap = 0;
                        return false;
                    }
                    $payload = $this->_get_binary_packet($skip_channel_filter);
                }
        }
        // see http://tools.ietf.org/html/rfc4252#section-5.4; only called when the encryption has been activated and when we haven't already logged in
        if (($this->bitmap & NET_SSH2_MASK_CONNECTED) && !$this->isAuthenticated() && ord($payload[0]) == NET_SSH2_MSG_USERAUTH_BANNER) {
            $this->_string_shift($payload, 1);
            if (strlen($payload) < 4) {
                return false;
            }
            extract(unpack('Nlength', $this->_string_shift($payload, 4)));
            $this->banner_message = $this->_string_shift($payload, $length);
            $payload = $this->_get_binary_packet();
        }
        // only called when we've already logged in
        if (($this->bitmap & NET_SSH2_MASK_CONNECTED) && $this->isAuthenticated()) {
            if (is_bool($payload)) {
                return $payload;
            }
            switch (ord($payload[0])) {
                case NET_SSH2_MSG_CHANNEL_REQUEST:
                    if (strlen($payload) == 31) {
                        extract(unpack('cpacket_type/Nchannel/Nlength', $payload));
                        if (substr($payload, 9, $length) == 'keepalive@openssh.com' && isset($this->server_channels[$channel])) {
                            if (ord(substr($payload, 9 + $length))) { // want reply
                                $this->_send_binary_packet(pack('CN', NET_SSH2_MSG_CHANNEL_SUCCESS, $this->server_channels[$channel]));
                            }
                            $payload = $this->_get_binary_packet($skip_channel_filter);
                        }
                    }
                    break;
                case NET_SSH2_MSG_CHANNEL_DATA:
                case NET_SSH2_MSG_CHANNEL_EXTENDED_DATA:
                case NET_SSH2_MSG_CHANNEL_CLOSE:
                case NET_SSH2_MSG_CHANNEL_EOF:
                    if (!$skip_channel_filter && !empty($this->server_channels)) {
                        $this->binary_packet_buffer = $payload;
                        $this->_get_channel_packet(true);
                        $payload = $this->_get_binary_packet();
                    }
                    break;
                case NET_SSH2_MSG_GLOBAL_REQUEST: // see http://tools.ietf.org/html/rfc4254#section-4
                    if (strlen($payload) < 4) {
                        return false;
                    }
                    extract(unpack('Nlength', $this->_string_shift($payload, 4)));
                    $this->errors[] = 'SSH_MSG_GLOBAL_REQUEST: ' . $this->_string_shift($payload, $length);
                    if (!$this->_send_binary_packet(pack('C', NET_SSH2_MSG_REQUEST_FAILURE))) {
                        return $this->_disconnect(NET_SSH2_DISCONNECT_BY_APPLICATION);
                    }
                    $payload = $this->_get_binary_packet($skip_channel_filter);
                    break;
                case NET_SSH2_MSG_CHANNEL_OPEN: // see http://tools.ietf.org/html/rfc4254#section-5.1
                    $this->_string_shift($payload, 1);
                    if (strlen($payload) < 4) {
                        return false;
                    }
                    extract(unpack('Nlength', $this->_string_shift($payload, 4)));
                    $data = $this->_string_shift($payload, $length);
                    if (strlen($payload) < 4) {
                        return false;
                    }
                    extract(unpack('Nserver_channel', $this->_string_shift($payload, 4)));
                    switch ($data) {
                        case 'auth-agent':
                        case 'auth-agent@openssh.com':
                            if (isset($this->agent)) {
                                $new_channel = NET_SSH2_CHANNEL_AGENT_FORWARD;
                                if (strlen($payload) < 8) {
                                    return false;
                                }
                                extract(unpack('Nremote_window_size', $this->_string_shift($payload, 4)));
                                extract(unpack('Nremote_maximum_packet_size', $this->_string_shift($payload, 4)));
                                $this->packet_size_client_to_server[$new_channel] = $remote_window_size;
                                $this->window_size_server_to_client[$new_channel] = $remote_maximum_packet_size;
                                $this->window_size_client_to_server[$new_channel] = $this->window_size;
                                $packet_size = 0x4000;
                                $packet = pack(
                                    'CN4',
                                    NET_SSH2_MSG_CHANNEL_OPEN_CONFIRMATION,
                                    $server_channel,
                                    $new_channel,
                                    $packet_size,
                                    $packet_size
                                );
                                $this->server_channels[$new_channel] = $server_channel;
                                $this->channel_status[$new_channel] = NET_SSH2_MSG_CHANNEL_OPEN_CONFIRMATION;
                                if (!$this->_send_binary_packet($packet)) {
                                    return false;
                                }
                            }
                            break;
                        default:
                            $packet = pack(
                                'CN3a*Na*',
                                NET_SSH2_MSG_REQUEST_FAILURE,
                                $server_channel,
                                NET_SSH2_OPEN_ADMINISTRATIVELY_PROHIBITED,
                                0,
                                '',
                                0,
                                ''
                            );
                            if (!$this->_send_binary_packet($packet)) {
                                return $this->_disconnect(NET_SSH2_DISCONNECT_BY_APPLICATION);
                            }
                    }
                    $payload = $this->_get_binary_packet($skip_channel_filter);
                    break;
                case NET_SSH2_MSG_CHANNEL_WINDOW_ADJUST:
                    $this->_string_shift($payload, 1);
                    if (strlen($payload) < 8) {
                        return false;
                    }
                    extract(unpack('Nchannel', $this->_string_shift($payload, 4)));
                    extract(unpack('Nwindow_size', $this->_string_shift($payload, 4)));
                    $this->window_size_client_to_server[$channel]+= $window_size;
                    $payload = ($this->bitmap & NET_SSH2_MASK_WINDOW_ADJUST) ? true : $this->_get_binary_packet($skip_channel_filter);
            }
        }
        return $payload;
    }
References _disconnect(), _get_binary_packet(), _get_channel_packet(), _key_exchange(), _send_binary_packet(), _string_shift(), isAuthenticated(), NET_SSH2_CHANNEL_AGENT_FORWARD, NET_SSH2_MASK_CONNECTED, and NET_SSH2_MASK_WINDOW_ADJUST.
Referenced by _get_binary_packet().
_format_log()
_format_log ($message_log, $message_number_log)
Formats a log for printing.
Parameters
array $message_log
array $message_number_log @access private
Returns
string
Definition at line 4520 of file SSH2.php.
    {
        $output = '';
        for ($i = 0; $i < count($message_log); $i++) {
            $output.= $message_number_log[$i] . "\r\n";
            $current_log = $message_log[$i];
            $j = 0;
            do {
                if (strlen($current_log)) {
                    $output.= str_pad(dechex($j), 7, '0', STR_PAD_LEFT) . '0  ';
                }
                $fragment = $this->_string_shift($current_log, $this->log_short_width);
                $hex = substr(preg_replace_callback('#.#s', array($this, '_format_log_helper'), $fragment), strlen($this->log_boundary));
                // replace non ASCII printable characters with dots
                // http://en.wikipedia.org/wiki/ASCII#ASCII_printable_characters
                // also replace < with a . since < messes up the output on web browsers
                $raw = preg_replace('#[^\x20-\x7E]|<#', '.', $fragment);
                $output.= str_pad($hex, $this->log_long_width - $this->log_short_width, ' ') . $raw . "\r\n";
                $j++;
            } while (strlen($current_log));
            $output.= "\r\n";
        }
        return $output;
    }
References _string_shift().
Referenced by _append_log(), and getLog().
_format_log_helper()
_format_log_helper ($matches)
Helper function for _format_log.
For use with preg_replace_callback()
Parameters
array $matches @access private
Returns
string
Definition at line 4555 of file SSH2.php.
    {
        return $this->log_boundary . str_pad(dechex(ord($matches[0])), 2, '0', STR_PAD_LEFT);
    }
_generate_identifier()
_generate_identifier ()
Generates the SSH identifier.
You should overwrite this method in your own class if you want to use another identifier
@access protected
Returns
string
Definition at line 1414 of file SSH2.php.
    {
        $identifier = 'SSH-2.0-phpseclib_1.0';
        $ext = array();
        if (extension_loaded('openssl')) {
            $ext[] = 'openssl';
        } elseif (extension_loaded('mcrypt')) {
            $ext[] = 'mcrypt';
        }
        if (extension_loaded('gmp')) {
            $ext[] = 'gmp';
        } elseif (extension_loaded('bcmath')) {
            $ext[] = 'bcmath';
        }
        if (!empty($ext)) {
            $identifier .= ' (' . implode(', ', $ext) . ')';
        }
        return $identifier;
    }
Referenced by _connect().
_get_binary_packet()
_get_binary_packet ($skip_channel_filter = false)
Gets Binary Packets.
See '6. Binary Packet Protocol' of rfc4253 for more info.
See also
self::_send_binary_packet()
Returns
string @access private
Definition at line 3488 of file SSH2.php.
    {
        if ($skip_channel_filter) {
            $read = array($this->fsock);
            $write = $except = null;
            if (!$this->curTimeout) {
                if ($this->keepAlive <= 0) {
                    @stream_select($read, $write, $except, null);
                } else {
                    if (!@stream_select($read, $write, $except, $this->keepAlive) && !count($read)) {
                        $this->_send_binary_packet(pack('CN', NET_SSH2_MSG_IGNORE, 0));
                        return $this->_get_binary_packet(true);
                    }
                }
            } else {
                if ($this->curTimeout < 0) {
                    $this->is_timeout = true;
                    return true;
                }
                $read = array($this->fsock);
                $write = $except = null;
                $start = strtok(microtime(), ' ') + strtok(''); // http://php.net/microtime#61838
                if ($this->keepAlive > 0 && $this->keepAlive < $this->curTimeout) {
                    if (!@stream_select($read, $write, $except, $this->keepAlive) && !count($read)) {
                        $this->_send_binary_packet(pack('CN', NET_SSH2_MSG_IGNORE, 0));
                        $elapsed = strtok(microtime(), ' ') + strtok('') - $start;
                        $this->curTimeout-= $elapsed;
                        return $this->_get_binary_packet(true);
                    }
                    $elapsed = strtok(microtime(), ' ') + strtok('') - $start;
                    $this->curTimeout-= $elapsed;
                }
                $sec = floor($this->curTimeout);
                $usec = 1000000 * ($this->curTimeout - $sec);
                // on windows this returns a "Warning: Invalid CRT parameters detected" error
                if (!@stream_select($read, $write, $except, $sec, $usec) && !count($read)) {
                    $this->is_timeout = true;
                    return true;
                }
                $elapsed = strtok(microtime(), ' ') + strtok('') - $start;
                $this->curTimeout-= $elapsed;
            }
        }
        if (!is_resource($this->fsock) || feof($this->fsock)) {
            $this->bitmap = 0;
            user_error('Connection closed (by server) prematurely ' . $elapsed . 's');
            return false;
        }
        $start = strtok(microtime(), ' ') + strtok(''); // http://php.net/microtime#61838
        $raw = fread($this->fsock, $this->decrypt_block_size);
        if (!strlen($raw)) {
            user_error('No data received from server');
            return false;
        }
        if ($this->decrypt !== false) {
            $raw = $this->decrypt->decrypt($raw);
        }
        if ($raw === false) {
            user_error('Unable to decrypt content');
            return false;
        }
        if (strlen($raw) < 5) {
            return false;
        }
        extract(unpack('Npacket_length/Cpadding_length', $this->_string_shift($raw, 5)));
        $remaining_length = $packet_length + 4 - $this->decrypt_block_size;
        // quoting <http://tools.ietf.org/html/rfc4253#section-6.1>,
        // "implementations SHOULD check that the packet length is reasonable"
        // PuTTY uses 0x9000 as the actual max packet size and so to shall we
        if ($remaining_length < -$this->decrypt_block_size || $remaining_length > 0x9000 || $remaining_length % $this->decrypt_block_size != 0) {
            if (!$this->bad_key_size_fix && $this->_bad_algorithm_candidate($this->decrypt->name) && !($this->bitmap & NET_SSH2_MASK_LOGIN)) {
                $this->bad_key_size_fix = true;
                $this->_reset_connection(NET_SSH2_DISCONNECT_KEY_EXCHANGE_FAILED);
                return false;
            }
            user_error('Invalid size');
            return false;
        }
        $buffer = '';
        while ($remaining_length > 0) {
            $temp = fread($this->fsock, $remaining_length);
            if ($temp === false || feof($this->fsock)) {
                $this->bitmap = 0;
                user_error('Error reading from socket');
                return false;
            }
            $buffer.= $temp;
            $remaining_length-= strlen($temp);
        }
        $stop = strtok(microtime(), ' ') + strtok('');
        if (strlen($buffer)) {
            $raw.= $this->decrypt !== false ? $this->decrypt->decrypt($buffer) : $buffer;
        }
        $payload = $this->_string_shift($raw, $packet_length - $padding_length - 1);
        $padding = $this->_string_shift($raw, $padding_length); // should leave $raw empty
        if ($this->hmac_check !== false) {
            $hmac = fread($this->fsock, $this->hmac_size);
            if ($hmac === false || strlen($hmac) != $this->hmac_size) {
                $this->bitmap = 0;
                user_error('Error reading socket');
                return false;
            } elseif ($hmac != $this->hmac_check->hash(pack('NNCa*', $this->get_seq_no, $packet_length, $padding_length, $payload . $padding))) {
                user_error('Invalid HMAC');
                return false;
            }
        }
        switch ($this->decompress) {
            case NET_SSH2_COMPRESSION_ZLIB_AT_OPENSSH:
                if (!$this->isAuthenticated()) {
                    break;
                }
            case NET_SSH2_COMPRESSION_ZLIB:
                if ($this->regenerate_decompression_context) {
                    $this->regenerate_decompression_context = false;
                    $cmf = ord($payload[0]);
                    $cm = $cmf & 0x0F;
                    if ($cm != 8) { // deflate
                        user_error("Only CM = 8 ('deflate') is supported ($cm)");
                    }
                    $cinfo = ($cmf & 0xF0) >> 4;
                    if ($cinfo > 7) {
                        user_error("CINFO above 7 is not allowed ($cinfo)");
                    }
                    $windowSize = 1 << ($cinfo + 8);
                    $flg = ord($payload[1]);
                    //$fcheck = $flg && 0x0F;
                    if ((($cmf << 8) | $flg) % 31) {
                        user_error('fcheck failed');
                    }
                    $fdict = boolval($flg & 0x20);
                    $flevel = ($flg & 0xC0) >> 6;
                    $this->decompress_context = inflate_init(ZLIB_ENCODING_RAW, array('window' => $cinfo + 8));
                    $payload = substr($payload, 2);
                }
                if ($this->decompress_context) {
                    $payload = inflate_add($this->decompress_context, $payload, ZLIB_PARTIAL_FLUSH);
                }
        }
        $this->get_seq_no++;
        if (defined('NET_SSH2_LOGGING')) {
            $current = strtok(microtime(), ' ') + strtok('');
            $message_number = isset($this->message_numbers[ord($payload[0])]) ? $this->message_numbers[ord($payload[0])] : 'UNKNOWN (' . ord($payload[0]) . ')';
            $message_number = '<- ' . $message_number .
                              ' (since last: ' . round($current - $this->last_packet, 4) . ', network: ' . round($stop - $start, 4) . 's)';
            $this->_append_log($message_number, $payload);
            $this->last_packet = $current;
        }
        return $this->_filter($payload, $skip_channel_filter);
    }
References _append_log(), _bad_algorithm_candidate(), _filter(), _get_binary_packet(), _reset_connection(), _send_binary_packet(), _string_shift(), isAuthenticated(), NET_SSH2_COMPRESSION_ZLIB, NET_SSH2_COMPRESSION_ZLIB_AT_OPENSSH, and NET_SSH2_MASK_LOGIN.
Referenced by _connect(), _filter(), _get_binary_packet(), _get_channel_packet(), _key_exchange(), _keyboard_interactive_process(), _login_helper(), and _privatekey_login().
_get_channel_packet()
_get_channel_packet ($client_channel, $skip_extended = false)
Gets channel data.
Returns the data as a string if it's available and false if not.
Parameters
int $client_channel
bool $skip_extended
Returns
mixed|bool @access private
Definition at line 3925 of file SSH2.php.
    {
        if (!empty($this->channel_buffers[$client_channel])) {
            switch ($this->channel_status[$client_channel]) {
                case NET_SSH2_MSG_CHANNEL_REQUEST:
                    foreach ($this->channel_buffers[$client_channel] as $i => $packet) {
                        switch (ord($packet[0])) {
                            case NET_SSH2_MSG_CHANNEL_SUCCESS:
                            case NET_SSH2_MSG_CHANNEL_FAILURE:
                                unset($this->channel_buffers[$client_channel][$i]);
                                return substr($packet, 1);
                        }
                    }
                    break;
                default:
                    return substr(array_shift($this->channel_buffers[$client_channel]), 1);
            }
        }
        while (true) {
            if ($this->binary_packet_buffer !== false) {
                $response = $this->binary_packet_buffer;
                $this->binary_packet_buffer = false;
            } else {
                $response = $this->_get_binary_packet(true);
                if ($response === true && $this->is_timeout) {
                    if ($client_channel == NET_SSH2_CHANNEL_EXEC && !$this->request_pty) {
                        $this->_close_channel($client_channel);
                    }
                    return true;
                }
                if ($response === false) {
                    $this->bitmap = 0;
                    user_error('Connection closed by server');
                    return false;
                }
            }
            if ($client_channel == -1 && $response === true) {
                return true;
            }
            if (!strlen($response)) {
                return false;
            }
            extract(unpack('Ctype', $this->_string_shift($response, 1)));
            if (strlen($response) < 4) {
                return false;
            }
            if ($type == NET_SSH2_MSG_CHANNEL_OPEN) {
                extract(unpack('Nlength', $this->_string_shift($response, 4)));
            } else {
                extract(unpack('Nchannel', $this->_string_shift($response, 4)));
            }
            // will not be setup yet on incoming channel open request
            if (isset($channel) && isset($this->channel_status[$channel]) && isset($this->window_size_server_to_client[$channel])) {
                $this->window_size_server_to_client[$channel]-= strlen($response);
                // resize the window, if appropriate
                if ($this->window_size_server_to_client[$channel] < 0) {
                // PuTTY does something more analogous to the following:
                //if ($this->window_size_server_to_client[$channel] < 0x3FFFFFFF) {
                    $packet = pack('CNN', NET_SSH2_MSG_CHANNEL_WINDOW_ADJUST, $this->server_channels[$channel], $this->window_resize);
                    if (!$this->_send_binary_packet($packet)) {
                        return false;
                    }
                    $this->window_size_server_to_client[$channel]+= $this->window_resize;
                }
                switch ($type) {
                    case NET_SSH2_MSG_CHANNEL_EXTENDED_DATA:
                        /*
                        if ($client_channel == NET_SSH2_CHANNEL_EXEC) {
                            $this->_send_channel_packet($client_channel, chr(0));
                        }
                        */
                        // currently, there's only one possible value for $data_type_code: NET_SSH2_EXTENDED_DATA_STDERR
                        if (strlen($response) < 8) {
                            return false;
                        }
                        extract(unpack('Ndata_type_code/Nlength', $this->_string_shift($response, 8)));
                        $data = $this->_string_shift($response, $length);
                        $this->stdErrorLog.= $data;
                        if ($skip_extended || $this->quiet_mode) {
                            continue 2;
                        }
                        if ($client_channel == $channel && $this->channel_status[$channel] == NET_SSH2_MSG_CHANNEL_DATA) {
                            return $data;
                        }
                        $this->channel_buffers[$channel][] = chr($type) . $data;
                        continue 2;
                    case NET_SSH2_MSG_CHANNEL_REQUEST:
                        if ($this->channel_status[$channel] == NET_SSH2_MSG_CHANNEL_CLOSE) {
                            continue 2;
                        }
                        if (strlen($response) < 4) {
                            return false;
                        }
                        extract(unpack('Nlength', $this->_string_shift($response, 4)));
                        $value = $this->_string_shift($response, $length);
                        switch ($value) {
                            case 'exit-signal':
                                $this->_string_shift($response, 1);
                                if (strlen($response) < 4) {
                                    return false;
                                }
                                extract(unpack('Nlength', $this->_string_shift($response, 4)));
                                $this->errors[] = 'SSH_MSG_CHANNEL_REQUEST (exit-signal): ' . $this->_string_shift($response, $length);
                                $this->_string_shift($response, 1);
                                if (strlen($response) < 4) {
                                    return false;
                                }
                                extract(unpack('Nlength', $this->_string_shift($response, 4)));
                                if ($length) {
                                    $this->errors[count($this->errors)].= "\r\n" . $this->_string_shift($response, $length);
                                }
                                $this->_send_binary_packet(pack('CN', NET_SSH2_MSG_CHANNEL_EOF, $this->server_channels[$client_channel]));
                                $this->_send_binary_packet(pack('CN', NET_SSH2_MSG_CHANNEL_CLOSE, $this->server_channels[$channel]));
                                $this->channel_status[$channel] = NET_SSH2_MSG_CHANNEL_EOF;
                                continue 3;
                            case 'exit-status':
                                if (strlen($response) < 5) {
                                    return false;
                                }
                                extract(unpack('Cfalse/Nexit_status', $this->_string_shift($response, 5)));
                                $this->exit_status = $exit_status;
                                // "The client MAY ignore these messages."
                                // -- http://tools.ietf.org/html/rfc4254#section-6.10
                                continue 3;
                            default:
                                // "Some systems may not implement signals, in which case they SHOULD ignore this message."
                                //  -- http://tools.ietf.org/html/rfc4254#section-6.9
                                continue 3;
                        }
                }
                switch ($this->channel_status[$channel]) {
                    case NET_SSH2_MSG_CHANNEL_OPEN:
                        switch ($type) {
                            case NET_SSH2_MSG_CHANNEL_OPEN_CONFIRMATION:
                                if (strlen($response) < 4) {
                                    return false;
                                }
                                extract(unpack('Nserver_channel', $this->_string_shift($response, 4)));
                                $this->server_channels[$channel] = $server_channel;
                                if (strlen($response) < 4) {
                                    return false;
                                }
                                extract(unpack('Nwindow_size', $this->_string_shift($response, 4)));
                                if ($window_size < 0) {
                                    $window_size&= 0x7FFFFFFF;
                                    $window_size+= 0x80000000;
                                }
                                $this->window_size_client_to_server[$channel] = $window_size;
                                if (strlen($response) < 4) {
                                     return false;
                                }
                                $temp = unpack('Npacket_size_client_to_server', $this->_string_shift($response, 4));
                                $this->packet_size_client_to_server[$channel] = $temp['packet_size_client_to_server'];
                                $result = $client_channel == $channel ? true : $this->_get_channel_packet($client_channel, $skip_extended);
                                $this->_on_channel_open();
                                return $result;
                            case NET_SSH2_MSG_CHANNEL_OPEN_FAILURE:
                                user_error('Unable to open channel');
                                return $this->_disconnect(NET_SSH2_DISCONNECT_BY_APPLICATION);
                            default:
                                if ($client_channel == $channel) {
                                    user_error('Unexpected response to open request');
                                    return $this->_disconnect(NET_SSH2_DISCONNECT_BY_APPLICATION);
                                }
                                return $this->_get_channel_packet($client_channel, $skip_extended);
                        }
                        break;
                    case NET_SSH2_MSG_CHANNEL_REQUEST:
                        switch ($type) {
                            case NET_SSH2_MSG_CHANNEL_SUCCESS:
                                return true;
                            case NET_SSH2_MSG_CHANNEL_FAILURE:
                                return false;
                            case NET_SSH2_MSG_CHANNEL_DATA:
                                if (strlen($response) < 4) {
                                    return false;
                                }
                                extract(unpack('Nlength', $this->_string_shift($response, 4)));
                                $data = $this->_string_shift($response, $length);
                                $this->channel_buffers[$channel][] = chr($type) . $data;
                                return $this->_get_channel_packet($client_channel, $skip_extended);
                            default:
                                user_error('Unable to fulfill channel request');
                                return $this->_disconnect(NET_SSH2_DISCONNECT_BY_APPLICATION);
                        }
                    case NET_SSH2_MSG_CHANNEL_CLOSE:
                        return $type == NET_SSH2_MSG_CHANNEL_CLOSE ? true : $this->_get_channel_packet($client_channel, $skip_extended);
                }
            }
            // ie. $this->channel_status[$channel] == NET_SSH2_MSG_CHANNEL_DATA
            switch ($type) {
                case NET_SSH2_MSG_CHANNEL_DATA:
                    /*
                    if ($channel == NET_SSH2_CHANNEL_EXEC) {
                        // SCP requires null packets, such as this, be sent.  further, in the case of the ssh.com SSH server
                        // this actually seems to make things twice as fast.  more to the point, the message right after
                        // SSH_MSG_CHANNEL_DATA (usually SSH_MSG_IGNORE) won't block for as long as it would have otherwise.
                        // in OpenSSH it slows things down but only by a couple thousandths of a second.
                        $this->_send_channel_packet($channel, chr(0));
                    }
                    */
                    if (strlen($response) < 4) {
                        return false;
                    }
                    extract(unpack('Nlength', $this->_string_shift($response, 4)));
                    $data = $this->_string_shift($response, $length);
                    if ($channel == NET_SSH2_CHANNEL_AGENT_FORWARD) {
                        $agent_response = $this->agent->_forward_data($data);
                        if (!is_bool($agent_response)) {
                            $this->_send_channel_packet($channel, $agent_response);
                        }
                        break;
                    }
                    if ($client_channel == $channel) {
                        return $data;
                    }
                    $this->channel_buffers[$channel][] = chr($type) . $data;
                    break;
                case NET_SSH2_MSG_CHANNEL_CLOSE:
                    $this->curTimeout = 5;
                    if ($this->bitmap & NET_SSH2_MASK_SHELL) {
                        $this->bitmap&= ~NET_SSH2_MASK_SHELL;
                    }
                    if ($this->channel_status[$channel] != NET_SSH2_MSG_CHANNEL_EOF) {
                        $this->_send_binary_packet(pack('CN', NET_SSH2_MSG_CHANNEL_CLOSE, $this->server_channels[$channel]));
                    }
                    $this->channel_status[$channel] = NET_SSH2_MSG_CHANNEL_CLOSE;
                    if ($client_channel == $channel) {
                        return true;
                    }
                case NET_SSH2_MSG_CHANNEL_EOF:
                    break;
                default:
                    user_error("Error reading channel data ($type)");
                    return $this->_disconnect(NET_SSH2_DISCONNECT_BY_APPLICATION);
            }
        }
    }
References _close_channel(), _disconnect(), _get_binary_packet(), _get_channel_packet(), _on_channel_open(), _send_binary_packet(), _send_channel_packet(), _string_shift(), NET_SSH2_CHANNEL_AGENT_FORWARD, NET_SSH2_CHANNEL_EXEC, and NET_SSH2_MASK_SHELL.
Referenced by _close_channel(), _filter(), _get_channel_packet(), _initShell(), _send_channel_packet(), exec(), ping(), read(), and startSubsystem().
_get_interactive_channel()
_get_interactive_channel ()
Return the channel to be used with read() / write()
See also
self::read()
self::write()
Returns
int @access public
Definition at line 3137 of file SSH2.php.
    {
        switch (true) {
            case $this->in_subsystem:
                return NET_SSH2_CHANNEL_SUBSYSTEM;
            case $this->in_request_pty_exec:
                return NET_SSH2_CHANNEL_EXEC;
            default:
                return NET_SSH2_CHANNEL_SHELL;
        }
    }
References NET_SSH2_CHANNEL_EXEC, NET_SSH2_CHANNEL_SHELL, and NET_SSH2_CHANNEL_SUBSYSTEM.
Referenced by read(), reset(), and write().
_get_open_channel()
_get_open_channel ()
Return an available open channel.
Returns
int @access public
Definition at line 3155 of file SSH2.php.
    {
        $channel = NET_SSH2_CHANNEL_EXEC;
        do {
            if (isset($this->channel_status[$channel]) && $this->channel_status[$channel] == NET_SSH2_MSG_CHANNEL_OPEN) {
                return $channel;
            }
        } while ($channel++ < NET_SSH2_CHANNEL_SUBSYSTEM);
        return false;
    }
References NET_SSH2_CHANNEL_EXEC, and NET_SSH2_CHANNEL_SUBSYSTEM.
_initShell()
_initShell ()
Creates an interactive shell.
See also
self::read()
self::write()
Returns
bool @access private
Definition at line 3046 of file SSH2.php.
    {
        if ($this->in_request_pty_exec === true) {
            return true;
        }
        $this->window_size_server_to_client[NET_SSH2_CHANNEL_SHELL] = $this->window_size;
        $packet_size = 0x4000;
        $packet = pack(
            'CNa*N3',
            NET_SSH2_MSG_CHANNEL_OPEN,
            strlen('session'),
            'session',
            NET_SSH2_CHANNEL_SHELL,
            $this->window_size_server_to_client[NET_SSH2_CHANNEL_SHELL],
            $packet_size
        );
        if (!$this->_send_binary_packet($packet)) {
            return false;
        }
        $this->channel_status[NET_SSH2_CHANNEL_SHELL] = NET_SSH2_MSG_CHANNEL_OPEN;
        $response = $this->_get_channel_packet(NET_SSH2_CHANNEL_SHELL);
        if ($response === false) {
            return false;
        }
        $terminal_modes = pack('C', NET_SSH2_TTY_OP_END);
        $packet = pack(
            'CNNa*CNa*N5a*',
            NET_SSH2_MSG_CHANNEL_REQUEST,
            $this->server_channels[NET_SSH2_CHANNEL_SHELL],
            strlen('pty-req'),
            'pty-req',
            1,
            strlen('vt100'),
            'vt100',
            $this->windowColumns,
            $this->windowRows,
            0,
            0,
            strlen($terminal_modes),
            $terminal_modes
        );
        if (!$this->_send_binary_packet($packet)) {
            return false;
        }
        $this->channel_status[NET_SSH2_CHANNEL_SHELL] = NET_SSH2_MSG_CHANNEL_REQUEST;
        if (!$this->_get_channel_packet(NET_SSH2_CHANNEL_SHELL)) {
            user_error('Unable to request pseudo-terminal');
            return $this->_disconnect(NET_SSH2_DISCONNECT_BY_APPLICATION);
        }
        $packet = pack(
            'CNNa*C',
            NET_SSH2_MSG_CHANNEL_REQUEST,
            $this->server_channels[NET_SSH2_CHANNEL_SHELL],
            strlen('shell'),
            'shell',
            1
        );
        if (!$this->_send_binary_packet($packet)) {
            return false;
        }
        $response = $this->_get_channel_packet(NET_SSH2_CHANNEL_SHELL);
        if ($response === false) {
            return false;
        }
        $this->channel_status[NET_SSH2_CHANNEL_SHELL] = NET_SSH2_MSG_CHANNEL_DATA;
        $this->bitmap |= NET_SSH2_MASK_SHELL;
        return true;
    }
References _disconnect(), _get_channel_packet(), _send_binary_packet(), NET_SSH2_CHANNEL_SHELL, and NET_SSH2_MASK_SHELL.
Referenced by read(), and write().
_key_exchange()
_key_exchange ($kexinit_payload_server = false)
Key Exchange.
Parameters
string $kexinit_payload_server optional @access private
Definition at line 1444 of file SSH2.php.
    {
        $preferred = $this->preferred;
        $send_kex = true;
        $kex_algorithms = isset($preferred['kex']) ?
            $preferred['kex'] :
            $this->getSupportedKEXAlgorithms();
        $server_host_key_algorithms = isset($preferred['hostkey']) ?
            $preferred['hostkey'] :
            $this->getSupportedHostKeyAlgorithms();
        $s2c_encryption_algorithms = isset($preferred['server_to_client']['crypt']) ?
            $preferred['server_to_client']['crypt'] :
            $this->getSupportedEncryptionAlgorithms();
        $c2s_encryption_algorithms = isset($preferred['client_to_server']['crypt']) ?
            $preferred['client_to_server']['crypt'] :
            $this->getSupportedEncryptionAlgorithms();
        $s2c_mac_algorithms = isset($preferred['server_to_client']['mac']) ?
            $preferred['server_to_client']['mac'] :
            $this->getSupportedMACAlgorithms();
        $c2s_mac_algorithms = isset($preferred['client_to_server']['mac']) ?
            $preferred['client_to_server']['mac'] :
            $this->getSupportedMACAlgorithms();
        $s2c_compression_algorithms = isset($preferred['server_to_client']['comp']) ?
            $preferred['server_to_client']['comp'] :
            $this->getSupportedCompressionAlgorithms();
        $c2s_compression_algorithms = isset($preferred['client_to_server']['comp']) ?
            $preferred['client_to_server']['comp'] :
            $this->getSupportedCompressionAlgorithms();
        // some SSH servers have buggy implementations of some of the above algorithms
        switch (true) {
            case $this->server_identifier == 'SSH-2.0-SSHD':
            case substr($this->server_identifier, 0, 13) == 'SSH-2.0-DLINK':
                if (!isset($preferred['server_to_client']['mac'])) {
                    $s2c_mac_algorithms = array_values(array_diff(
                        $s2c_mac_algorithms,
                        array('hmac-sha1-96', 'hmac-md5-96')
                    ));
                }
                if (!isset($preferred['client_to_server']['mac'])) {
                    $c2s_mac_algorithms = array_values(array_diff(
                        $c2s_mac_algorithms,
                        array('hmac-sha1-96', 'hmac-md5-96')
                    ));
                }
        }
        $str_kex_algorithms = implode(',', $kex_algorithms);
        $str_server_host_key_algorithms = implode(',', $server_host_key_algorithms);
        $encryption_algorithms_server_to_client = implode(',', $s2c_encryption_algorithms);
        $encryption_algorithms_client_to_server = implode(',', $c2s_encryption_algorithms);
        $mac_algorithms_server_to_client = implode(',', $s2c_mac_algorithms);
        $mac_algorithms_client_to_server = implode(',', $c2s_mac_algorithms);
        $compression_algorithms_server_to_client = implode(',', $s2c_compression_algorithms);
        $compression_algorithms_client_to_server = implode(',', $c2s_compression_algorithms);
        $client_cookie = crypt_random_string(16);
        $kexinit_payload_client = pack(
            'Ca*Na*Na*Na*Na*Na*Na*Na*Na*Na*Na*CN',
            NET_SSH2_MSG_KEXINIT,
            $client_cookie,
            strlen($str_kex_algorithms),
            $str_kex_algorithms,
            strlen($str_server_host_key_algorithms),
            $str_server_host_key_algorithms,
            strlen($encryption_algorithms_client_to_server),
            $encryption_algorithms_client_to_server,
            strlen($encryption_algorithms_server_to_client),
            $encryption_algorithms_server_to_client,
            strlen($mac_algorithms_client_to_server),
            $mac_algorithms_client_to_server,
            strlen($mac_algorithms_server_to_client),
            $mac_algorithms_server_to_client,
            strlen($compression_algorithms_client_to_server),
            $compression_algorithms_client_to_server,
            strlen($compression_algorithms_server_to_client),
            $compression_algorithms_server_to_client,
            0,
            '',
            0,
            '',
            0,
            0
        );
        if ($kexinit_payload_server === false) {
            if (!$this->_send_binary_packet($kexinit_payload_client)) {
                return false;
            }
            $kexinit_payload_server = $this->_get_binary_packet();
            if ($kexinit_payload_server === false) {
                $this->bitmap = 0;
                user_error('Connection closed by server');
                return false;
            }
            if (!strlen($kexinit_payload_server) || ord($kexinit_payload_server[0]) != NET_SSH2_MSG_KEXINIT) {
                user_error('Expected SSH_MSG_KEXINIT');
                return false;
            }
            $send_kex = false;
        }
        $response = $kexinit_payload_server;
        $this->_string_shift($response, 1); // skip past the message number (it should be SSH_MSG_KEXINIT)
        $server_cookie = $this->_string_shift($response, 16);
        if (strlen($response) < 4) {
            return false;
        }
        $temp = unpack('Nlength', $this->_string_shift($response, 4));
        $this->kex_algorithms = explode(',', $this->_string_shift($response, $temp['length']));
        if (strlen($response) < 4) {
            return false;
        }
        $temp = unpack('Nlength', $this->_string_shift($response, 4));
        $this->server_host_key_algorithms = explode(',', $this->_string_shift($response, $temp['length']));
        if (strlen($response) < 4) {
            return false;
        }
        $temp = unpack('Nlength', $this->_string_shift($response, 4));
        $this->encryption_algorithms_client_to_server = explode(',', $this->_string_shift($response, $temp['length']));
        if (strlen($response) < 4) {
            return false;
        }
        $temp = unpack('Nlength', $this->_string_shift($response, 4));
        $this->encryption_algorithms_server_to_client = explode(',', $this->_string_shift($response, $temp['length']));
        if (strlen($response) < 4) {
            return false;
        }
        $temp = unpack('Nlength', $this->_string_shift($response, 4));
        $this->mac_algorithms_client_to_server = explode(',', $this->_string_shift($response, $temp['length']));
        if (strlen($response) < 4) {
            return false;
        }
        $temp = unpack('Nlength', $this->_string_shift($response, 4));
        $this->mac_algorithms_server_to_client = explode(',', $this->_string_shift($response, $temp['length']));
        if (strlen($response) < 4) {
            return false;
        }
        $temp = unpack('Nlength', $this->_string_shift($response, 4));
        $this->compression_algorithms_client_to_server = explode(',', $this->_string_shift($response, $temp['length']));
        if (strlen($response) < 4) {
            return false;
        }
        $temp = unpack('Nlength', $this->_string_shift($response, 4));
        $this->compression_algorithms_server_to_client = explode(',', $this->_string_shift($response, $temp['length']));
        if (strlen($response) < 4) {
            return false;
        }
        $temp = unpack('Nlength', $this->_string_shift($response, 4));
        $this->languages_client_to_server = explode(',', $this->_string_shift($response, $temp['length']));
        if (strlen($response) < 4) {
            return false;
        }
        $temp = unpack('Nlength', $this->_string_shift($response, 4));
        $this->languages_server_to_client = explode(',', $this->_string_shift($response, $temp['length']));
        if (!strlen($response)) {
            return false;
        }
        extract(unpack('Cfirst_kex_packet_follows', $this->_string_shift($response, 1)));
        $first_kex_packet_follows = $first_kex_packet_follows != 0;
        if ($send_kex && !$this->_send_binary_packet($kexinit_payload_client)) {
            return false;
        }
        // we need to decide upon the symmetric encryption algorithms before we do the diffie-hellman key exchange
        // we don't initialize any crypto-objects, yet - we do that, later. for now, we need the lengths to make the
        // diffie-hellman key exchange as fast as possible
        $decrypt = $this->_array_intersect_first($s2c_encryption_algorithms, $this->encryption_algorithms_server_to_client);
        $decryptKeyLength = $this->_encryption_algorithm_to_key_size($decrypt);
        if ($decryptKeyLength === null) {
            user_error('No compatible server to client encryption algorithms found');
            return $this->_disconnect(NET_SSH2_DISCONNECT_KEY_EXCHANGE_FAILED);
        }
        $encrypt = $this->_array_intersect_first($c2s_encryption_algorithms, $this->encryption_algorithms_client_to_server);
        $encryptKeyLength = $this->_encryption_algorithm_to_key_size($encrypt);
        if ($encryptKeyLength === null) {
            user_error('No compatible client to server encryption algorithms found');
            return $this->_disconnect(NET_SSH2_DISCONNECT_KEY_EXCHANGE_FAILED);
        }
        $keyLength = $decryptKeyLength > $encryptKeyLength ? $decryptKeyLength : $encryptKeyLength;
        // through diffie-hellman key exchange a symmetric key is obtained
        $this->kex_algorithm = $kex_algorithm = $this->_array_intersect_first($kex_algorithms, $this->kex_algorithms);
        if ($kex_algorithm === false) {
            user_error('No compatible key exchange algorithms found');
            return $this->_disconnect(NET_SSH2_DISCONNECT_KEY_EXCHANGE_FAILED);
        }
        $server_host_key_algorithm = $this->_array_intersect_first($server_host_key_algorithms, $this->server_host_key_algorithms);
        if ($server_host_key_algorithm === false) {
            user_error('No compatible server host key algorithms found');
            return $this->_disconnect(NET_SSH2_DISCONNECT_KEY_EXCHANGE_FAILED);
        }
        $mac_algorithm_out = $this->_array_intersect_first($c2s_mac_algorithms, $this->mac_algorithms_client_to_server);
        if ($mac_algorithm_out === false) {
            user_error('No compatible client to server message authentication algorithms found');
            return $this->_disconnect(NET_SSH2_DISCONNECT_KEY_EXCHANGE_FAILED);
        }
        $mac_algorithm_in = $this->_array_intersect_first($s2c_mac_algorithms, $this->mac_algorithms_server_to_client);
        if ($mac_algorithm_in === false) {
            user_error('No compatible server to client message authentication algorithms found');
            return $this->_disconnect(NET_SSH2_DISCONNECT_KEY_EXCHANGE_FAILED);
        }
        $compression_map = array(
            'none' => NET_SSH2_COMPRESSION_NONE,
            'zlib' => NET_SSH2_COMPRESSION_ZLIB,
            'zlib@openssh.com' => NET_SSH2_COMPRESSION_ZLIB_AT_OPENSSH
        );
        $compression_algorithm_out = $this->_array_intersect_first($c2s_compression_algorithms, $this->compression_algorithms_client_to_server);
        if ($compression_algorithm_out === false) {
            user_error('No compatible client to server compression algorithms found');
            return $this->_disconnect(NET_SSH2_DISCONNECT_KEY_EXCHANGE_FAILED);
        }
        $this->compress = $compression_map[$compression_algorithm_out];
        $compression_algorithm_in = $this->_array_intersect_first($s2c_compression_algorithms, $this->compression_algorithms_server_to_client);
        if ($compression_algorithm_in === false) {
            user_error('No compatible server to client compression algorithms found');
            return $this->_disconnect(NET_SSH2_DISCONNECT_KEY_EXCHANGE_FAILED);
        }
        $this->decompress = $compression_map[$compression_algorithm_in];
        if (strpos($kex_algorithm, 'diffie-hellman-group-exchange') === 0) {
            $dh_group_sizes_packed = pack(
                'NNN',
                $this->kex_dh_group_size_min,
                $this->kex_dh_group_size_preferred,
                $this->kex_dh_group_size_max
            );
            $packet = pack(
                'Ca*',
                NET_SSH2_MSG_KEXDH_GEX_REQUEST,
                $dh_group_sizes_packed
            );
            if (!$this->_send_binary_packet($packet)) {
                return false;
            }
            $this->_updateLogHistory('UNKNOWN (34)', 'NET_SSH2_MSG_KEXDH_GEX_REQUEST');
            $response = $this->_get_binary_packet();
            if ($response === false) {
                $this->bitmap = 0;
                user_error('Connection closed by server');
                return false;
            }
            if (!strlen($response)) {
                return false;
            }
            extract(unpack('Ctype', $this->_string_shift($response, 1)));
            if ($type != NET_SSH2_MSG_KEXDH_GEX_GROUP) {
                user_error('Expected SSH_MSG_KEX_DH_GEX_GROUP');
                return false;
            }
            $this->_updateLogHistory('NET_SSH2_MSG_KEXDH_REPLY', 'NET_SSH2_MSG_KEXDH_GEX_GROUP');
            if (strlen($response) < 4) {
                return false;
            }
            extract(unpack('NprimeLength', $this->_string_shift($response, 4)));
            $primeBytes = $this->_string_shift($response, $primeLength);
            $prime = new Math_BigInteger($primeBytes, -256);
            if (strlen($response) < 4) {
                return false;
            }
            extract(unpack('NgLength', $this->_string_shift($response, 4)));
            $gBytes = $this->_string_shift($response, $gLength);
            $g = new Math_BigInteger($gBytes, -256);
            $exchange_hash_rfc4419 = pack(
                'a*Na*Na*',
                $dh_group_sizes_packed,
                $primeLength,
                $primeBytes,
                $gLength,
                $gBytes
            );
            $clientKexInitMessage = NET_SSH2_MSG_KEXDH_GEX_INIT;
            $serverKexReplyMessage = NET_SSH2_MSG_KEXDH_GEX_REPLY;
        } else {
            switch ($kex_algorithm) {
                // see http://tools.ietf.org/html/rfc2409#section-6.2 and
                // http://tools.ietf.org/html/rfc2412, appendex E
                case 'diffie-hellman-group1-sha1':
                    $prime = 'FFFFFFFFFFFFFFFFC90FDAA22168C234C4C6628B80DC1CD129024E088A67CC74' .
                            '020BBEA63B139B22514A08798E3404DDEF9519B3CD3A431B302B0A6DF25F1437' .
                            '4FE1356D6D51C245E485B576625E7EC6F44C42E9A637ED6B0BFF5CB6F406B7ED' .
                            'EE386BFB5A899FA5AE9F24117C4B1FE649286651ECE65381FFFFFFFFFFFFFFFF';
                    break;
                // see http://tools.ietf.org/html/rfc3526#section-3
                case 'diffie-hellman-group14-sha1':
                    $prime = 'FFFFFFFFFFFFFFFFC90FDAA22168C234C4C6628B80DC1CD129024E088A67CC74' .
                            '020BBEA63B139B22514A08798E3404DDEF9519B3CD3A431B302B0A6DF25F1437' .
                            '4FE1356D6D51C245E485B576625E7EC6F44C42E9A637ED6B0BFF5CB6F406B7ED' .
                            'EE386BFB5A899FA5AE9F24117C4B1FE649286651ECE45B3DC2007CB8A163BF05' .
                            '98DA48361C55D39A69163FA8FD24CF5F83655D23DCA3AD961C62F356208552BB' .
                            '9ED529077096966D670C354E4ABC9804F1746C08CA18217C32905E462E36CE3B' .
                            'E39E772C180E86039B2783A2EC07A28FB5C55DF06F4C52C9DE2BCBF695581718' .
                            '3995497CEA956AE515D2261898FA051015728E5A8AACAA68FFFFFFFFFFFFFFFF';
                    break;
            }
            // For both diffie-hellman-group1-sha1 and diffie-hellman-group14-sha1
            // the generator field element is 2 (decimal) and the hash function is sha1.
            $g = new Math_BigInteger(2);
            $prime = new Math_BigInteger($prime, 16);
            $exchange_hash_rfc4419 = '';
            $clientKexInitMessage = NET_SSH2_MSG_KEXDH_INIT;
            $serverKexReplyMessage = NET_SSH2_MSG_KEXDH_REPLY;
        }
        switch ($kex_algorithm) {
            case 'diffie-hellman-group-exchange-sha256':
                $kexHash = new Crypt_Hash('sha256');
                break;
            default:
                $kexHash = new Crypt_Hash('sha1');
        }
        /* To increase the speed of the key exchange, both client and server may
           reduce the size of their private exponents.  It should be at least
           twice as long as the key material that is generated from the shared
           secret.  For more details, see the paper by van Oorschot and Wiener
           [VAN-OORSCHOT].
           -- http://tools.ietf.org/html/rfc4419#section-6.2 */
        $one = new Math_BigInteger(1);
        $keyLength = min($keyLength, $kexHash->getLength());
        $max = $one->bitwise_leftShift(16 * $keyLength); // 2 * 8 * $keyLength
        $max = $max->subtract($one);
        $x = $one->random($one, $max);
        $e = $g->modPow($x, $prime);
        $eBytes = $e->toBytes(true);
        $data = pack('CNa*', $clientKexInitMessage, strlen($eBytes), $eBytes);
        if (!$this->_send_binary_packet($data)) {
            $this->bitmap = 0;
            user_error('Connection closed by server');
            return false;
        }
        if ($clientKexInitMessage == NET_SSH2_MSG_KEXDH_GEX_INIT) {
            $this->_updateLogHistory('UNKNOWN (32)', 'NET_SSH2_MSG_KEXDH_GEX_INIT');
        }
        $response = $this->_get_binary_packet();
        if ($response === false) {
            $this->bitmap = 0;
            user_error('Connection closed by server');
            return false;
        }
        if (!strlen($response)) {
            return false;
        }
        extract(unpack('Ctype', $this->_string_shift($response, 1)));
        if ($type != $serverKexReplyMessage) {
            $expected = $serverKexReplyMessage == NET_SSH2_MSG_KEXDH_GEX_REPLY ?
                'SSH_MSG_KEXDH_GEX_REPLY' :
                'SSH_MSG_KEXDH_REPLY';
            user_error("Expected $expected");
            return false;
        }
        if ($serverKexReplyMessage == NET_SSH2_MSG_KEXDH_GEX_REPLY) {
            $this->_updateLogHistory('UNKNOWN (33)', 'NET_SSH2_MSG_KEXDH_GEX_REPLY');
        }
        if (strlen($response) < 4) {
            return false;
        }
        $temp = unpack('Nlength', $this->_string_shift($response, 4));
        $this->server_public_host_key = $server_public_host_key = $this->_string_shift($response, $temp['length']);
        if (strlen($server_public_host_key) < 4) {
            return false;
        }
        $temp = unpack('Nlength', $this->_string_shift($server_public_host_key, 4));
        $public_key_format = $this->_string_shift($server_public_host_key, $temp['length']);
        if (strlen($response) < 4) {
            return false;
        }
        $temp = unpack('Nlength', $this->_string_shift($response, 4));
        $fBytes = $this->_string_shift($response, $temp['length']);
        $f = new Math_BigInteger($fBytes, -256);
        if (strlen($response) < 4) {
            return false;
        }
        $temp = unpack('Nlength', $this->_string_shift($response, 4));
        $this->signature = $this->_string_shift($response, $temp['length']);
        if (strlen($this->signature) < 4) {
            return false;
        }
        $temp = unpack('Nlength', $this->_string_shift($this->signature, 4));
        $this->signature_format = $this->_string_shift($this->signature, $temp['length']);
        $key = $f->modPow($x, $prime);
        $keyBytes = $key->toBytes(true);
        $this->exchange_hash = pack(
            'Na*Na*Na*Na*Na*a*Na*Na*Na*',
            strlen($this->identifier),
            $this->identifier,
            strlen($this->server_identifier),
            $this->server_identifier,
            strlen($kexinit_payload_client),
            $kexinit_payload_client,
            strlen($kexinit_payload_server),
            $kexinit_payload_server,
            strlen($this->server_public_host_key),
            $this->server_public_host_key,
            $exchange_hash_rfc4419,
            strlen($eBytes),
            $eBytes,
            strlen($fBytes),
            $fBytes,
            strlen($keyBytes),
            $keyBytes
        );
        $this->exchange_hash = $kexHash->hash($this->exchange_hash);
        if ($this->session_id === false) {
            $this->session_id = $this->exchange_hash;
        }
        switch ($server_host_key_algorithm) {
            case 'ssh-dss':
                $expected_key_format = 'ssh-dss';
                break;
            //case 'rsa-sha2-256':
            //case 'rsa-sha2-512':
            //case 'ssh-rsa':
            default:
                $expected_key_format = 'ssh-rsa';
        }
        if ($public_key_format != $expected_key_format || $this->signature_format != $server_host_key_algorithm) {
            switch (true) {
                case $this->signature_format == $server_host_key_algorithm:
                case $server_host_key_algorithm != 'rsa-sha2-256' && $server_host_key_algorithm != 'rsa-sha2-512':
                case $this->signature_format != 'ssh-rsa':
                    user_error('Server Host Key Algorithm Mismatch');
                    return $this->_disconnect(NET_SSH2_DISCONNECT_KEY_EXCHANGE_FAILED);
            }
        }
        $packet = pack(
            'C',
            NET_SSH2_MSG_NEWKEYS
        );
        if (!$this->_send_binary_packet($packet)) {
            return false;
        }
        $response = $this->_get_binary_packet();
        if ($response === false) {
            $this->bitmap = 0;
            user_error('Connection closed by server');
            return false;
        }
        if (!strlen($response)) {
            return false;
        }
        extract(unpack('Ctype', $this->_string_shift($response, 1)));
        if ($type != NET_SSH2_MSG_NEWKEYS) {
            user_error('Expected SSH_MSG_NEWKEYS');
            return false;
        }
        $this->encrypt = $this->_encryption_algorithm_to_crypt_instance($encrypt);
        $this->decrypt = $this->_encryption_algorithm_to_crypt_instance($decrypt);
        $keyBytes = pack('Na*', strlen($keyBytes), $keyBytes);
        if ($this->encrypt) {
            if ($this->crypto_engine) {
                $this->encrypt->setPreferredEngine($this->crypto_engine);
            }
            $this->encrypt->enableContinuousBuffer();
            $this->encrypt->disablePadding();
            if ($this->encrypt->getBlockLength()) {
                $this->encrypt_block_size = $this->encrypt->getBlockLength() >> 3;
            }
            $iv = $kexHash->hash($keyBytes . $this->exchange_hash . 'A' . $this->session_id);
            while ($this->encrypt_block_size > strlen($iv)) {
                $iv.= $kexHash->hash($keyBytes . $this->exchange_hash . $iv);
            }
            $this->encrypt->setIV(substr($iv, 0, $this->encrypt_block_size));
            $key = $kexHash->hash($keyBytes . $this->exchange_hash . 'C' . $this->session_id);
            while ($encryptKeyLength > strlen($key)) {
                $key.= $kexHash->hash($keyBytes . $this->exchange_hash . $key);
            }
            $this->encrypt->setKey(substr($key, 0, $encryptKeyLength));
            $this->encrypt->name = $decrypt;
        }
        if ($this->decrypt) {
            if ($this->crypto_engine) {
                $this->decrypt->setPreferredEngine($this->crypto_engine);
            }
            $this->decrypt->enableContinuousBuffer();
            $this->decrypt->disablePadding();
            if ($this->decrypt->getBlockLength()) {
                $this->decrypt_block_size = $this->decrypt->getBlockLength() >> 3;
            }
            $iv = $kexHash->hash($keyBytes . $this->exchange_hash . 'B' . $this->session_id);
            while ($this->decrypt_block_size > strlen($iv)) {
                $iv.= $kexHash->hash($keyBytes . $this->exchange_hash . $iv);
            }
            $this->decrypt->setIV(substr($iv, 0, $this->decrypt_block_size));
            $key = $kexHash->hash($keyBytes . $this->exchange_hash . 'D' . $this->session_id);
            while ($decryptKeyLength > strlen($key)) {
                $key.= $kexHash->hash($keyBytes . $this->exchange_hash . $key);
            }
            $this->decrypt->setKey(substr($key, 0, $decryptKeyLength));
            $this->decrypt->name = $decrypt;
        }
        /* The "arcfour128" algorithm is the RC4 cipher, as described in
           [SCHNEIER], using a 128-bit key.  The first 1536 bytes of keystream
           generated by the cipher MUST be discarded, and the first byte of the
           first encrypted packet MUST be encrypted using the 1537th byte of
           keystream.
           -- http://tools.ietf.org/html/rfc4345#section-4 */
        if ($encrypt == 'arcfour128' || $encrypt == 'arcfour256') {
            $this->encrypt->encrypt(str_repeat("\0", 1536));
        }
        if ($decrypt == 'arcfour128' || $decrypt == 'arcfour256') {
            $this->decrypt->decrypt(str_repeat("\0", 1536));
        }
        $createKeyLength = 0; // ie. $mac_algorithm == 'none'
        switch ($mac_algorithm_out) {
            case 'hmac-sha2-256':
                $this->hmac_create = new Crypt_Hash('sha256');
                $createKeyLength = 32;
                break;
            case 'hmac-sha1':
                $this->hmac_create = new Crypt_Hash('sha1');
                $createKeyLength = 20;
                break;
            case 'hmac-sha1-96':
                $this->hmac_create = new Crypt_Hash('sha1-96');
                $createKeyLength = 20;
                break;
            case 'hmac-md5':
                $this->hmac_create = new Crypt_Hash('md5');
                $createKeyLength = 16;
                break;
            case 'hmac-md5-96':
                $this->hmac_create = new Crypt_Hash('md5-96');
                $createKeyLength = 16;
        }
        $this->hmac_create->name = $mac_algorithm_out;
        $checkKeyLength = 0;
        $this->hmac_size = 0;
        switch ($mac_algorithm_in) {
            case 'hmac-sha2-256':
                $this->hmac_check = new Crypt_Hash('sha256');
                $checkKeyLength = 32;
                $this->hmac_size = 32;
                break;
            case 'hmac-sha1':
                $this->hmac_check = new Crypt_Hash('sha1');
                $checkKeyLength = 20;
                $this->hmac_size = 20;
                break;
            case 'hmac-sha1-96':
                $this->hmac_check = new Crypt_Hash('sha1-96');
                $checkKeyLength = 20;
                $this->hmac_size = 12;
                break;
            case 'hmac-md5':
                $this->hmac_check = new Crypt_Hash('md5');
                $checkKeyLength = 16;
                $this->hmac_size = 16;
                break;
            case 'hmac-md5-96':
                $this->hmac_check = new Crypt_Hash('md5-96');
                $checkKeyLength = 16;
                $this->hmac_size = 12;
        }
        $this->hmac_check->name = $mac_algorithm_in;
        $key = $kexHash->hash($keyBytes . $this->exchange_hash . 'E' . $this->session_id);
        while ($createKeyLength > strlen($key)) {
            $key.= $kexHash->hash($keyBytes . $this->exchange_hash . $key);
        }
        $this->hmac_create->setKey(substr($key, 0, $createKeyLength));
        $key = $kexHash->hash($keyBytes . $this->exchange_hash . 'F' . $this->session_id);
        while ($checkKeyLength > strlen($key)) {
            $key.= $kexHash->hash($keyBytes . $this->exchange_hash . $key);
        }
        $this->hmac_check->setKey(substr($key, 0, $checkKeyLength));
        $this->regenerate_compression_context = $this->regenerate_decompression_context = true;
        return true;
    }
References _array_intersect_first(), _disconnect(), _encryption_algorithm_to_crypt_instance(), _encryption_algorithm_to_key_size(), _get_binary_packet(), _send_binary_packet(), _string_shift(), _updateLogHistory(), getSupportedCompressionAlgorithms(), getSupportedEncryptionAlgorithms(), getSupportedHostKeyAlgorithms(), getSupportedKEXAlgorithms(), getSupportedMACAlgorithms(), NET_SSH2_COMPRESSION_NONE, NET_SSH2_COMPRESSION_ZLIB, and NET_SSH2_COMPRESSION_ZLIB_AT_OPENSSH.
Referenced by _connect(), and _filter().
_keyboard_interactive_login()
_keyboard_interactive_login ($username, $password)
Login via keyboard-interactive authentication.
See RFC4256 for details. This is not a full-featured keyboard-interactive authenticator.
Parameters
string $username
string $password
Returns
bool @access private
Definition at line 2549 of file SSH2.php.
    {
        $packet = pack(
            'CNa*Na*Na*Na*Na*',
            NET_SSH2_MSG_USERAUTH_REQUEST,
            strlen($username),
            $username,
            strlen('ssh-connection'),
            'ssh-connection',
            strlen('keyboard-interactive'),
            'keyboard-interactive',
            0,
            '',
            0,
            ''
        );
        if (!$this->_send_binary_packet($packet)) {
            return false;
        }
        return $this->_keyboard_interactive_process($password);
    }
References _keyboard_interactive_process(), and _send_binary_packet().
Referenced by _login_helper().
_keyboard_interactive_process()
_keyboard_interactive_process ()
Handle the keyboard-interactive requests / responses.
Returns
bool @access private
Definition at line 2579 of file SSH2.php.
    {
        $responses = func_get_args();
        if (strlen($this->last_interactive_response)) {
            $response = $this->last_interactive_response;
        } else {
            $orig = $response = $this->_get_binary_packet();
            if ($response === false) {
                $this->bitmap = 0;
                user_error('Connection closed by server');
                return false;
            }
        }
        if (!strlen($response)) {
            return false;
        }
        extract(unpack('Ctype', $this->_string_shift($response, 1)));
        switch ($type) {
            case NET_SSH2_MSG_USERAUTH_INFO_REQUEST:
                if (strlen($response) < 4) {
                    return false;
                }
                extract(unpack('Nlength', $this->_string_shift($response, 4)));
                $this->_string_shift($response, $length); // name; may be empty
                if (strlen($response) < 4) {
                    return false;
                }
                extract(unpack('Nlength', $this->_string_shift($response, 4)));
                $this->_string_shift($response, $length); // instruction; may be empty
                if (strlen($response) < 4) {
                    return false;
                }
                extract(unpack('Nlength', $this->_string_shift($response, 4)));
                $this->_string_shift($response, $length); // language tag; may be empty
                if (strlen($response) < 4) {
                    return false;
                }
                extract(unpack('Nnum_prompts', $this->_string_shift($response, 4)));
                for ($i = 0; $i < count($responses); $i++) {
                    if (is_array($responses[$i])) {
                        foreach ($responses[$i] as $key => $value) {
                            $this->keyboard_requests_responses[$key] = $value;
                        }
                        unset($responses[$i]);
                    }
                }
                $responses = array_values($responses);
                if (isset($this->keyboard_requests_responses)) {
                    for ($i = 0; $i < $num_prompts; $i++) {
                        if (strlen($response) < 4) {
                            return false;
                        }
                        extract(unpack('Nlength', $this->_string_shift($response, 4)));
                        // prompt - ie. "Password: "; must not be empty
                        $prompt = $this->_string_shift($response, $length);
                        //$echo = $this->_string_shift($response) != chr(0);
                        foreach ($this->keyboard_requests_responses as $key => $value) {
                            if (substr($prompt, 0, strlen($key)) == $key) {
                                $responses[] = $value;
                                break;
                            }
                        }
                    }
                }
                // see http://tools.ietf.org/html/rfc4256#section-3.2
                if (strlen($this->last_interactive_response)) {
                    $this->last_interactive_response = '';
                } else {
                    $this->_updateLogHistory('UNKNOWN (60)', 'NET_SSH2_MSG_USERAUTH_INFO_REQUEST');
                }
                if (!count($responses) && $num_prompts) {
                    $this->last_interactive_response = $orig;
                    return false;
                }
                /*
                   After obtaining the requested information from the user, the client
                   MUST respond with an SSH_MSG_USERAUTH_INFO_RESPONSE message.
                */
                // see http://tools.ietf.org/html/rfc4256#section-3.4
                $packet = $logged = pack('CN', NET_SSH2_MSG_USERAUTH_INFO_RESPONSE, count($responses));
                for ($i = 0; $i < count($responses); $i++) {
                    $packet.= pack('Na*', strlen($responses[$i]), $responses[$i]);
                    $logged.= pack('Na*', strlen('dummy-answer'), 'dummy-answer');
                }
                if (!$this->_send_binary_packet($packet, $logged)) {
                    return false;
                }
                $this->_updateLogHistory('UNKNOWN (61)', 'NET_SSH2_MSG_USERAUTH_INFO_RESPONSE');
                /*
                   After receiving the response, the server MUST send either an
                   SSH_MSG_USERAUTH_SUCCESS, SSH_MSG_USERAUTH_FAILURE, or another
                   SSH_MSG_USERAUTH_INFO_REQUEST message.
                */
                // maybe phpseclib should force close the connection after x request / responses?  unless something like that is done
                // there could be an infinite loop of request / responses.
                return $this->_keyboard_interactive_process();
            case NET_SSH2_MSG_USERAUTH_SUCCESS:
                return true;
            case NET_SSH2_MSG_USERAUTH_FAILURE:
                extract(unpack('Nmethodlistlen', $this->_string_shift($response, 4)));
                $this->auth_methods_to_continue = explode(',', $this->_string_shift($response, $methodlistlen));
                return false;
        }
        return false;
    }
References _get_binary_packet(), _keyboard_interactive_process(), _send_binary_packet(), _string_shift(), and _updateLogHistory().
Referenced by _keyboard_interactive_login(), _keyboard_interactive_process(), and _login_helper().
_login()
_login ($username)
Login Helper.
Parameters
string $username
Returns
bool
See also
self::_login_helper() @access private
Definition at line 2261 of file SSH2.php.
    {
        if (!($this->bitmap & NET_SSH2_MASK_CONSTRUCTOR)) {
            if (!$this->_connect()) {
                return false;
            }
        }
        $args = array_slice(func_get_args(), 1);
        if (empty($args)) {
            return $this->_login_helper($username);
        }
        while (count($args)) {
            if (!$this->auth_methods_to_continue || !$this->smartMFA) {
                $newargs = $args;
                $args = array();
            } else {
                $newargs = array();
                foreach ($this->auth_methods_to_continue as $method) {
                    switch ($method) {
                        case 'publickey':
                            foreach ($args as $key => $arg) {
                                if (is_object($arg)) {
                                    $newargs[] = $arg;
                                    unset($args[$key]);
                                    break;
                                }
                            }
                            break;
                        case 'keyboard-interactive':
                            $hasArray = $hasString = false;
                            foreach ($args as $arg) {
                                if ($hasArray || is_array($arg)) {
                                    $hasArray = true;
                                    break;
                                }
                                if ($hasString || is_string($arg)) {
                                    $hasString = true;
                                    break;
                                }
                            }
                            if ($hasArray && $hasString) {
                                foreach ($args as $key => $arg) {
                                    if (is_array($arg)) {
                                        $newargs[] = $arg;
                                        break 2;
                                    }
                                }
                            }
                        case 'password':
                            foreach ($args as $key => $arg) {
                                $newargs[] = $arg;
                                unset($args[$key]);
                                break;
                            }
                    }
                }
            }
            if (!count($newargs)) {
                return false;
            }
            foreach ($newargs as $arg) {
                if ($this->_login_helper($username, $arg)) {
                    return true;
                }
            }
        }
        return false;
    }
References $args, _connect(), _login_helper(), and NET_SSH2_MASK_CONSTRUCTOR.
Referenced by login().
_login_helper()
_login_helper ($username, $password = null)
Login Helper.
Parameters
string $username
string $password
Returns
bool @access private
Definition at line 2344 of file SSH2.php.
    {
        if (!($this->bitmap & NET_SSH2_MASK_CONNECTED)) {
            return false;
        }
        if (!($this->bitmap & NET_SSH2_MASK_LOGIN_REQ)) {
            $packet = pack(
                'CNa*',
                NET_SSH2_MSG_SERVICE_REQUEST,
                strlen('ssh-userauth'),
                'ssh-userauth'
            );
            if (!$this->_send_binary_packet($packet)) {
                return false;
            }
            $response = $this->_get_binary_packet();
            if ($response === false) {
                if ($this->retry_connect) {
                    $this->retry_connect = false;
                    if (!$this->_connect()) {
                        return false;
                    }
                    return $this->_login_helper($username, $password);
                }
                $this->bitmap = 0;
                user_error('Connection closed by server');
                return false;
            }
            if (strlen($response) < 4) {
                return false;
            }
            extract(unpack('Ctype', $this->_string_shift($response, 1)));
            if ($type != NET_SSH2_MSG_SERVICE_ACCEPT) {
                user_error('Expected SSH_MSG_SERVICE_ACCEPT');
                return false;
            }
            $this->bitmap |= NET_SSH2_MASK_LOGIN_REQ;
        }
        if (strlen($this->last_interactive_response)) {
            return !is_string($password) && !is_array($password) ? false : $this->_keyboard_interactive_process($password);
        }
        // although PHP5's get_class() preserves the case, PHP4's does not
        if (is_object($password)) {
            switch (strtolower(get_class($password))) {
                case 'crypt_rsa':
                    return $this->_privatekey_login($username, $password);
                case 'system_ssh_agent':
                    return $this->_ssh_agent_login($username, $password);
            }
        }
        if (is_array($password)) {
            if ($this->_keyboard_interactive_login($username, $password)) {
                $this->bitmap |= NET_SSH2_MASK_LOGIN;
                return true;
            }
            return false;
        }
        if (!isset($password)) {
            $packet = pack(
                'CNa*Na*Na*',
                NET_SSH2_MSG_USERAUTH_REQUEST,
                strlen($username),
                $username,
                strlen('ssh-connection'),
                'ssh-connection',
                strlen('none'),
                'none'
            );
            if (!$this->_send_binary_packet($packet)) {
                return false;
            }
            $response = $this->_get_binary_packet();
            if ($response === false) {
                $this->bitmap = 0;
                user_error('Connection closed by server');
                return false;
            }
            if (!strlen($response)) {
                return false;
            }
            extract(unpack('Ctype', $this->_string_shift($response, 1)));
            switch ($type) {
                case NET_SSH2_MSG_USERAUTH_SUCCESS:
                    $this->bitmap |= NET_SSH2_MASK_LOGIN;
                    return true;
                case NET_SSH2_MSG_USERAUTH_FAILURE:
                    extract(unpack('Nmethodlistlen', $this->_string_shift($response, 4)));
                    $this->auth_methods_to_continue = explode(',', $this->_string_shift($response, $methodlistlen));
                default:
                    return false;
            }
        }
        $packet = pack(
            'CNa*Na*Na*CNa*',
            NET_SSH2_MSG_USERAUTH_REQUEST,
            strlen($username),
            $username,
            strlen('ssh-connection'),
            'ssh-connection',
            strlen('password'),
            'password',
            0,
            strlen($password),
            $password
        );
        // remove the username and password from the logged packet
        if (!defined('NET_SSH2_LOGGING')) {
            $logged = null;
        } else {
            $logged = pack(
                'CNa*Na*Na*CNa*',
                NET_SSH2_MSG_USERAUTH_REQUEST,
                strlen('username'),
                'username',
                strlen('ssh-connection'),
                'ssh-connection',
                strlen('password'),
                'password',
                0,
                strlen('password'),
                'password'
            );
        }
        if (!$this->_send_binary_packet($packet, $logged)) {
            return false;
        }
        $response = $this->_get_binary_packet();
        if ($response === false) {
            $this->bitmap = 0;
            user_error('Connection closed by server');
            return false;
        }
        if (!strlen($response)) {
            return false;
        }
        extract(unpack('Ctype', $this->_string_shift($response, 1)));
        switch ($type) {
            case NET_SSH2_MSG_USERAUTH_PASSWD_CHANGEREQ: // in theory, the password can be changed
                $this->_updateLogHistory('UNKNOWN (60)', 'NET_SSH2_MSG_USERAUTH_PASSWD_CHANGEREQ');
                if (strlen($response) < 4) {
                    return false;
                }
                extract(unpack('Nlength', $this->_string_shift($response, 4)));
                $this->errors[] = 'SSH_MSG_USERAUTH_PASSWD_CHANGEREQ: ' . $this->_string_shift($response, $length);
                return $this->_disconnect(NET_SSH2_DISCONNECT_AUTH_CANCELLED_BY_USER);
            case NET_SSH2_MSG_USERAUTH_FAILURE:
                // can we use keyboard-interactive authentication?  if not then either the login is bad or the server employees
                // multi-factor authentication
                if (strlen($response) < 4) {
                    return false;
                }
                extract(unpack('Nlength', $this->_string_shift($response, 4)));
                $auth_methods = explode(',', $this->_string_shift($response, $length));
                $this->auth_methods_to_continue = $auth_methods;
                if (!strlen($response)) {
                    return false;
                }
                extract(unpack('Cpartial_success', $this->_string_shift($response, 1)));
                $partial_success = $partial_success != 0;
                if (!$partial_success && in_array('keyboard-interactive', $auth_methods)) {
                    if ($this->_keyboard_interactive_login($username, $password)) {
                        $this->bitmap |= NET_SSH2_MASK_LOGIN;
                        return true;
                    }
                    return false;
                }
                return false;
            case NET_SSH2_MSG_USERAUTH_SUCCESS:
                $this->bitmap |= NET_SSH2_MASK_LOGIN;
                return true;
        }
        return false;
    }
References _connect(), _disconnect(), _get_binary_packet(), _keyboard_interactive_login(), _keyboard_interactive_process(), _login_helper(), _privatekey_login(), _send_binary_packet(), _ssh_agent_login(), _string_shift(), _updateLogHistory(), NET_SSH2_MASK_CONNECTED, NET_SSH2_MASK_LOGIN, and NET_SSH2_MASK_LOGIN_REQ.
Referenced by _login(), and _login_helper().
_on_channel_open()
_on_channel_open ()
Helper function for agent->_on_channel_open()
Used when channels are created to inform agent of said channel opening. Must be called after channel open confirmation received
@access private
Definition at line 4569 of file SSH2.php.
    {
        if (isset($this->agent)) {
            $this->agent->_on_channel_open($this);
        }
    }
Referenced by _get_channel_packet().
_privatekey_login()
_privatekey_login ($username, $privatekey)
Login with an RSA private key.
Parameters
string $username
Crypt_RSA $privatekey
Returns
bool @access private
Definition at line 2728 of file SSH2.php.
    {
        // see http://tools.ietf.org/html/rfc4253#page-15
        $publickey = $privatekey->getPublicKey(CRYPT_RSA_PUBLIC_FORMAT_RAW);
        if ($publickey === false) {
            return false;
        }
        $publickey = array(
            'e' => $publickey['e']->toBytes(true),
            'n' => $publickey['n']->toBytes(true)
        );
        $publickey = pack(
            'Na*Na*Na*',
            strlen('ssh-rsa'),
            'ssh-rsa',
            strlen($publickey['e']),
            $publickey['e'],
            strlen($publickey['n']),
            $publickey['n']
        );
        switch ($this->signature_format) {
            case 'rsa-sha2-512':
                $hash = 'sha512';
                $signatureType = 'rsa-sha2-512';
                break;
            case 'rsa-sha2-256':
                $hash = 'sha256';
                $signatureType = 'rsa-sha2-256';
                break;
            //case 'ssh-rsa':
            default:
                $hash = 'sha1';
                $signatureType = 'ssh-rsa';
        }
        $part1 = pack(
            'CNa*Na*Na*',
            NET_SSH2_MSG_USERAUTH_REQUEST,
            strlen($username),
            $username,
            strlen('ssh-connection'),
            'ssh-connection',
            strlen('publickey'),
            'publickey'
        );
        $part2 = pack('Na*Na*', strlen($signatureType), $signatureType, strlen($publickey), $publickey);
        $packet = $part1 . chr(0) . $part2;
        if (!$this->_send_binary_packet($packet)) {
            return false;
        }
        $response = $this->_get_binary_packet();
        if ($response === false) {
            $this->bitmap = 0;
            user_error('Connection closed by server');
            return false;
        }
        if (!strlen($response)) {
            return false;
        }
        extract(unpack('Ctype', $this->_string_shift($response, 1)));
        switch ($type) {
            case NET_SSH2_MSG_USERAUTH_FAILURE:
                if (strlen($response) < 4) {
                    return false;
                }
                extract(unpack('Nmethodlistlen', $this->_string_shift($response, 4)));
                $this->auth_methods_to_continue = explode(',', $this->_string_shift($response, $methodlistlen));
                $this->errors[] = 'SSH_MSG_USERAUTH_FAILURE';
                return false;
            case NET_SSH2_MSG_USERAUTH_PK_OK:
                // we'll just take it on faith that the public key blob and the public key algorithm name are as
                // they should be
                $this->_updateLogHistory('UNKNOWN (60)', 'NET_SSH2_MSG_USERAUTH_PK_OK');
                break;
            case NET_SSH2_MSG_USERAUTH_SUCCESS:
                $this->bitmap |= NET_SSH2_MASK_LOGIN;
                return true;
            default:
                user_error('Unexpected response to publickey authentication pt 1');
                return $this->_disconnect(NET_SSH2_DISCONNECT_BY_APPLICATION);
        }
        $packet = $part1 . chr(1) . $part2;
        $privatekey->setSignatureMode(CRYPT_RSA_SIGNATURE_PKCS1);
        $privatekey->setHash($hash);
        $signature = $privatekey->sign(pack('Na*a*', strlen($this->session_id), $this->session_id, $packet));
        $signature = pack('Na*Na*', strlen($signatureType), $signatureType, strlen($signature), $signature);
        $packet.= pack('Na*', strlen($signature), $signature);
        if (!$this->_send_binary_packet($packet)) {
            return false;
        }
        $response = $this->_get_binary_packet();
        if ($response === false) {
            $this->bitmap = 0;
            user_error('Connection closed by server');
            return false;
        }
        if (!strlen($response)) {
            return false;
        }
        extract(unpack('Ctype', $this->_string_shift($response, 1)));
        switch ($type) {
            case NET_SSH2_MSG_USERAUTH_FAILURE:
                // either the login is bad or the server employs multi-factor authentication
                extract(unpack('Nmethodlistlen', $this->_string_shift($response, 4)));
                $this->auth_methods_to_continue = explode(',', $this->_string_shift($response, $methodlistlen));
                return false;
            case NET_SSH2_MSG_USERAUTH_SUCCESS:
                $this->bitmap |= NET_SSH2_MASK_LOGIN;
                return true;
        }
        user_error('Unexpected response to publickey authentication pt 2');
        return $this->_disconnect(NET_SSH2_DISCONNECT_BY_APPLICATION);
    }
References _disconnect(), _get_binary_packet(), _send_binary_packet(), _string_shift(), _updateLogHistory(), CRYPT_RSA_PUBLIC_FORMAT_RAW, CRYPT_RSA_SIGNATURE_PKCS1, and NET_SSH2_MASK_LOGIN.
Referenced by _login_helper(), and _ssh_agent_login().
_reconnect()
_reconnect ()
In situ reconnect method.
Returns
boolean @access private
Definition at line 3448 of file SSH2.php.
    {
        $this->_reset_connection(NET_SSH2_DISCONNECT_CONNECTION_LOST);
        $this->retry_connect = true;
        if (!$this->_connect()) {
            return false;
        }
        foreach ($this->auth as $auth) {
            $result = call_user_func_array(array(&$this, 'login'), $auth);
        }
        return $result;
    }
References _connect(), and _reset_connection().
Referenced by ping().
_reset_connection()
_reset_connection ($reason)
Resets a connection for re-use.
Parameters
int $reason @access private
Definition at line 3467 of file SSH2.php.
    {
        $this->_disconnect($reason);
        $this->decrypt = $this->encrypt = false;
        $this->decrypt_block_size = $this->encrypt_block_size = 8;
        $this->hmac_check = $this->hmac_create = false;
        $this->hmac_size = false;
        $this->session_id = false;
        $this->retry_connect = true;
        $this->get_seq_no = $this->send_seq_no = 0;
    }
References _disconnect().
Referenced by _get_binary_packet(), and _reconnect().
_send_binary_packet()
_send_binary_packet ($data, $logged = null)
Sends Binary Packets.
See '6. Binary Packet Protocol' of rfc4253 for more info.
Parameters
string $data
string $logged
See also
self::_get_binary_packet()
Returns
bool @access private
Definition at line 4194 of file SSH2.php.
    {
        if (!is_resource($this->fsock) || feof($this->fsock)) {
            $this->bitmap = 0;
            user_error('Connection closed prematurely');
            return false;
        }
        if (!isset($logged)) {
            $logged = $data;
        }
        switch ($this->compress) {
            case NET_SSH2_COMPRESSION_ZLIB_AT_OPENSSH:
                if (!$this->isAuthenticated()) {
                    break;
                }
            case NET_SSH2_COMPRESSION_ZLIB:
                if (!$this->regenerate_compression_context) {
                    $header = '';
                } else {
                    $this->regenerate_compression_context = false;
                    $this->compress_context = deflate_init(ZLIB_ENCODING_RAW, ['window' => 15]);
                    $header = "\x78\x9C";
                }
                if ($this->compress_context) {
                    $data = $header . deflate_add($this->compress_context, $data, ZLIB_PARTIAL_FLUSH);
                }
        }
        // 4 (packet length) + 1 (padding length) + 4 (minimal padding amount) == 9
        $packet_length = strlen($data) + 9;
        // round up to the nearest $this->encrypt_block_size
        $packet_length+= (($this->encrypt_block_size - 1) * $packet_length) % $this->encrypt_block_size;
        // subtracting strlen($data) is obvious - subtracting 5 is necessary because of packet_length and padding_length
        $padding_length = $packet_length - strlen($data) - 5;
        $padding = crypt_random_string($padding_length);
        // we subtract 4 from packet_length because the packet_length field isn't supposed to include itself
        $packet = pack('NCa*', $packet_length - 4, $padding_length, $data . $padding);
        $hmac = $this->hmac_create !== false ? $this->hmac_create->hash(pack('Na*', $this->send_seq_no, $packet)) : '';
        $this->send_seq_no++;
        if ($this->encrypt !== false) {
            $packet = $this->encrypt->encrypt($packet);
        }
        $packet.= $hmac;
        $start = strtok(microtime(), ' ') + strtok(''); // http://php.net/microtime#61838
        $result = strlen($packet) == @fputs($this->fsock, $packet);
        $stop = strtok(microtime(), ' ') + strtok('');
        if (defined('NET_SSH2_LOGGING')) {
            $current = strtok(microtime(), ' ') + strtok('');
            $message_number = isset($this->message_numbers[ord($logged[0])]) ? $this->message_numbers[ord($logged[0])] : 'UNKNOWN (' . ord($logged[0]) . ')';
            $message_number = '-> ' . $message_number .
                              ' (since last: ' . round($current - $this->last_packet, 4) . ', network: ' . round($stop - $start, 4) . 's)';
            $this->_append_log($message_number, $logged);
            $this->last_packet = $current;
        }
        return $result;
    }
References _append_log(), isAuthenticated(), NET_SSH2_COMPRESSION_ZLIB, and NET_SSH2_COMPRESSION_ZLIB_AT_OPENSSH.
Referenced by _close_channel(), _disconnect(), _filter(), _get_binary_packet(), _get_channel_packet(), _initShell(), _key_exchange(), _keyboard_interactive_login(), _keyboard_interactive_process(), _login_helper(), _privatekey_login(), _send_channel_packet(), exec(), ping(), and startSubsystem().
_send_channel_packet()
_send_channel_packet ($client_channel, $data)
Sends channel data.
Spans multiple SSH_MSG_CHANNEL_DATAs if appropriate
Parameters
int $client_channel
string $data
Returns
bool @access private
Definition at line 4347 of file SSH2.php.
    {
        while (strlen($data)) {
            if (!$this->window_size_client_to_server[$client_channel]) {
                $this->bitmap^= NET_SSH2_MASK_WINDOW_ADJUST;
                // using an invalid channel will let the buffers be built up for the valid channels
                $this->_get_channel_packet(-1);
                $this->bitmap^= NET_SSH2_MASK_WINDOW_ADJUST;
            }
            /* The maximum amount of data allowed is determined by the maximum
               packet size for the channel, and the current window size, whichever
               is smaller.
                 -- http://tools.ietf.org/html/rfc4254#section-5.2 */
            $max_size = min(
                $this->packet_size_client_to_server[$client_channel],
                $this->window_size_client_to_server[$client_channel]
            );
            $temp = $this->_string_shift($data, $max_size);
            $packet = pack(
                'CN2a*',
                NET_SSH2_MSG_CHANNEL_DATA,
                $this->server_channels[$client_channel],
                strlen($temp),
                $temp
            );
            $this->window_size_client_to_server[$client_channel]-= strlen($temp);
            if (!$this->_send_binary_packet($packet)) {
                return false;
            }
        }
        return true;
    }
References _get_channel_packet(), _send_binary_packet(), _string_shift(), and NET_SSH2_MASK_WINDOW_ADJUST.
Referenced by _get_channel_packet(), and write().
_ssh_agent_login()
_ssh_agent_login ($username, $agent)
Login with an ssh-agent provided key.
Parameters
string $username
System_SSH_Agent $agent
Returns
bool @access private
Definition at line 2705 of file SSH2.php.
    {
        $this->agent = $agent;
        $keys = $agent->requestIdentities();
        foreach ($keys as $key) {
            if ($this->_privatekey_login($username, $key)) {
                return true;
            }
        }
        return false;
    }
References _privatekey_login().
Referenced by _login_helper().
_string_shift()
_string_shift (& $string, $index = 1)
String Shift.
Inspired by array_shift
Parameters
string $string
int $index
Returns
string @access private
Definition at line 4457 of file SSH2.php.
    {
        $substr = substr($string, 0, $index);
        $string = substr($string, $index);
        return $substr;
    }
Referenced by _append_log(), _filter(), _format_log(), _get_binary_packet(), _get_channel_packet(), _key_exchange(), _keyboard_interactive_process(), _login_helper(), _privatekey_login(), _send_channel_packet(), getServerPublicHostKey(), and read().
_updateLogHistory()
_updateLogHistory ($old, $new)
Update packet types in log history.
Parameters
string $old
string $new @access private
Definition at line 5370 of file SSH2.php.
    {
        if (defined('NET_SSH2_LOGGING') && NET_SSH2_LOGGING == NET_SSH2_LOG_COMPLEX) {
            $this->message_number_log[count($this->message_number_log) - 1] = str_replace(
                $old,
                $new,
                $this->message_number_log[count($this->message_number_log) - 1]
            );
        }
    }
References NET_SSH2_LOG_COMPLEX.
Referenced by _key_exchange(), _keyboard_interactive_process(), _login_helper(), and _privatekey_login().
disablePTY()
disablePTY ()
Disable request-pty when using exec()
@access public
Definition at line 3892 of file SSH2.php.
    {
        if ($this->in_request_pty_exec) {
            $this->_close_channel(NET_SSH2_CHANNEL_EXEC);
            $this->in_request_pty_exec = false;
        }
        $this->request_pty = false;
    }
References _close_channel(), and NET_SSH2_CHANNEL_EXEC.
disableQuietMode()
disableQuietMode ()
Disable Quiet Mode.
Show stderr in output
@access public
Definition at line 3858 of file SSH2.php.
    {
        $this->quiet_mode = false;
    }
disableSmartMFA()
disableSmartMFA ()
Disables "smart" multi-factor authentication (MFA)
Definition at line 5403 of file SSH2.php.
    {
        $this->smartMFA = false;
    }
disconnect()
disconnect ()
Disconnect.
@access public
Definition at line 3355 of file SSH2.php.
    {
        $this->_disconnect(NET_SSH2_DISCONNECT_BY_APPLICATION);
        if (isset($this->realtime_log_file) && is_resource($this->realtime_log_file)) {
            fclose($this->realtime_log_file);
        }
    }
References _disconnect().
Referenced by __destruct(), and _close_channel().
enablePTY()
enablePTY ()
Enable request-pty when using exec()
@access public
Definition at line 3882 of file SSH2.php.
    {
        $this->request_pty = true;
    }
enableQuietMode()
enableQuietMode ()
Enable Quiet Mode.
Suppress stderr from output
@access public
Definition at line 3846 of file SSH2.php.
    {
        $this->quiet_mode = true;
    }
enableSmartMFA()
enableSmartMFA ()
Enables "smart" multi-factor authentication (MFA)
Definition at line 5395 of file SSH2.php.
    {
        $this->smartMFA = true;
    }
exec()
exec ($command, $callback = null)
Execute Command.
If $callback is set to false then Net_SSH2::_get_channel_packet(NET_SSH2_CHANNEL_EXEC) will need to be called manually. In all likelihood, this is not a feature you want to be taking advantage of.
Parameters
string $command
Callback $callback
Returns
string @access public
Definition at line 2902 of file SSH2.php.
    {
        $this->curTimeout = $this->timeout;
        $this->is_timeout = false;
        $this->stdErrorLog = '';
        if (!$this->isAuthenticated()) {
            return false;
        }
        if ($this->in_request_pty_exec) {
            user_error('If you want to run multiple exec()\'s you will need to disable (and re-enable if appropriate) a PTY for each one.');
            return false;
        }
        // RFC4254 defines the (client) window size as "bytes the other party can send before it must wait for the window to
        // be adjusted".  0x7FFFFFFF is, at 2GB, the max size.  technically, it should probably be decremented, but,
        // honestly, if you're transferring more than 2GB, you probably shouldn't be using phpseclib, anyway.
        // see http://tools.ietf.org/html/rfc4254#section-5.2 for more info
        $this->window_size_server_to_client[NET_SSH2_CHANNEL_EXEC] = $this->window_size;
        // 0x8000 is the maximum max packet size, per http://tools.ietf.org/html/rfc4253#section-6.1, although since PuTTy
        // uses 0x4000, that's what will be used here, as well.
        $packet_size = 0x4000;
        $packet = pack(
            'CNa*N3',
            NET_SSH2_MSG_CHANNEL_OPEN,
            strlen('session'),
            'session',
            NET_SSH2_CHANNEL_EXEC,
            $this->window_size_server_to_client[NET_SSH2_CHANNEL_EXEC],
            $packet_size
        );
        if (!$this->_send_binary_packet($packet)) {
            return false;
        }
        $this->channel_status[NET_SSH2_CHANNEL_EXEC] = NET_SSH2_MSG_CHANNEL_OPEN;
        $response = $this->_get_channel_packet(NET_SSH2_CHANNEL_EXEC);
        if ($response === false) {
            return false;
        }
        if ($this->request_pty === true) {
            $terminal_modes = pack('C', NET_SSH2_TTY_OP_END);
            $packet = pack(
                'CNNa*CNa*N5a*',
                NET_SSH2_MSG_CHANNEL_REQUEST,
                $this->server_channels[NET_SSH2_CHANNEL_EXEC],
                strlen('pty-req'),
                'pty-req',
                1,
                strlen('vt100'),
                'vt100',
                $this->windowColumns,
                $this->windowRows,
                0,
                0,
                strlen($terminal_modes),
                $terminal_modes
            );
            if (!$this->_send_binary_packet($packet)) {
                return false;
            }
            $this->channel_status[NET_SSH2_CHANNEL_EXEC] = NET_SSH2_MSG_CHANNEL_REQUEST;
            if (!$this->_get_channel_packet(NET_SSH2_CHANNEL_EXEC)) {
                user_error('Unable to request pseudo-terminal');
                return $this->_disconnect(NET_SSH2_DISCONNECT_BY_APPLICATION);
            }
            $this->in_request_pty_exec = true;
        }
        // sending a pty-req SSH_MSG_CHANNEL_REQUEST message is unnecessary and, in fact, in most cases, slows things
        // down.  the one place where it might be desirable is if you're doing something like Net_SSH2::exec('ping localhost &').
        // with a pty-req SSH_MSG_CHANNEL_REQUEST, exec() will return immediately and the ping process will then
        // then immediately terminate.  without such a request exec() will loop indefinitely.  the ping process won't end but
        // neither will your script.
        // although, in theory, the size of SSH_MSG_CHANNEL_REQUEST could exceed the maximum packet size established by
        // SSH_MSG_CHANNEL_OPEN_CONFIRMATION, RFC4254#section-5.1 states that the "maximum packet size" refers to the
        // "maximum size of an individual data packet". ie. SSH_MSG_CHANNEL_DATA.  RFC4254#section-5.2 corroborates.
        $packet = pack(
            'CNNa*CNa*',
            NET_SSH2_MSG_CHANNEL_REQUEST,
            $this->server_channels[NET_SSH2_CHANNEL_EXEC],
            strlen('exec'),
            'exec',
            1,
            strlen($command),
            $command
        );
        if (!$this->_send_binary_packet($packet)) {
            return false;
        }
        $this->channel_status[NET_SSH2_CHANNEL_EXEC] = NET_SSH2_MSG_CHANNEL_REQUEST;
        $response = $this->_get_channel_packet(NET_SSH2_CHANNEL_EXEC);
        if ($response === false) {
            return false;
        }
        $this->channel_status[NET_SSH2_CHANNEL_EXEC] = NET_SSH2_MSG_CHANNEL_DATA;
        if ($callback === false || $this->in_request_pty_exec) {
            return true;
        }
        $output = '';
        while (true) {
            $temp = $this->_get_channel_packet(NET_SSH2_CHANNEL_EXEC);
            switch (true) {
                case $temp === true:
                    return is_callable($callback) ? true : $output;
                case $temp === false:
                    return false;
                default:
                    if (is_callable($callback)) {
                        if (call_user_func($callback, $temp) === true) {
                            $this->_close_channel(NET_SSH2_CHANNEL_EXEC);
                            return true;
                        }
                    } else {
                        $output.= $temp;
                    }
            }
        }
    }
References _close_channel(), _disconnect(), _get_channel_packet(), _send_binary_packet(), isAuthenticated(), and NET_SSH2_CHANNEL_EXEC.
getAlgorithmsNegotiated()
getAlgorithmsNegotiated ()
Return list of negotiated algorithms.
Uses the same format as https://www.php.net/ssh2-methods-negotiated
Returns
array @access public
Definition at line 4952 of file SSH2.php.
    {
        $this->_connect();
        $compression_map = array(
            NET_SSH2_COMPRESSION_NONE => 'none',
            NET_SSH2_COMPRESSION_ZLIB => 'zlib',
            NET_SSH2_COMPRESSION_ZLIB_AT_OPENSSH => 'zlib@openssh.com'
        );
        return array(
            'kex' => $this->kex_algorithm,
            'hostkey' => $this->signature_format,
            'client_to_server' => array(
                'crypt' => $this->encrypt->name,
                'mac' => $this->hmac_create->name,
                'comp' => $compression_map[$this->compress],
            ),
            'server_to_client' => array(
                'crypt' => $this->decrypt->name,
                'mac' => $this->hmac_check->name,
                'comp' => $compression_map[$this->decompress],
            )
        );
    }
References _connect(), NET_SSH2_COMPRESSION_NONE, NET_SSH2_COMPRESSION_ZLIB, and NET_SSH2_COMPRESSION_ZLIB_AT_OPENSSH.
getAuthMethodsToContinue()
getAuthMethodsToContinue ()
Return the list of authentication methods that may productively continue authentication.
See also
https://tools.ietf.org/html/rfc4252#section-5.1
Returns
array|null
Definition at line 5387 of file SSH2.php.
    {
        return $this->auth_methods_to_continue;
    }
getBannerMessage()
getBannerMessage ()
Returns the banner message.
Quoting from the RFC, "in some jurisdictions, sending a warning message before authentication may be relevant for getting legal protection."
Returns
string @access public
Definition at line 5073 of file SSH2.php.
    {
        return $this->banner_message;
    }
getCompressionAlgorithmsClient2Server()
getCompressionAlgorithmsClient2Server ()
Return a list of the compression algorithms the server supports, when receiving stuff from the client.
Returns
array @access public
Definition at line 4718 of file SSH2.php.
    {
        $this->_connect();
        return $this->compression_algorithms_client_to_server;
    }
References _connect().
getCompressionAlgorithmsServer2Client()
getCompressionAlgorithmsServer2Client ()
Return a list of the compression algorithms the server supports, when sending stuff to the client.
Returns
array @access public
Definition at line 4731 of file SSH2.php.
    {
        $this->_connect();
        return $this->compression_algorithms_server_to_client;
    }
References _connect().
getEncryptionAlgorithmsClient2Server()
getEncryptionAlgorithmsClient2Server ()
Return a list of the (symmetric key) encryption algorithms the server supports, when receiving stuff from the client.
Returns
array @access public
Definition at line 4666 of file SSH2.php.
    {
        $this->_connect();
        return $this->encryption_algorithms_client_to_server;
    }
References _connect().
getEncryptionAlgorithmsServer2Client()
getEncryptionAlgorithmsServer2Client ()
Return a list of the (symmetric key) encryption algorithms the server supports, when sending stuff to the client.
Returns
array @access public
Definition at line 4679 of file SSH2.php.
    {
        $this->_connect();
        return $this->encryption_algorithms_server_to_client;
    }
References _connect().
getErrors()
getErrors ()
Returns all errors.
Returns
string[] @access public
Definition at line 4601 of file SSH2.php.
    {
        return $this->errors;
    }
getExitStatus()
getExitStatus ()
Returns the exit status of an SSH command or false.
Returns
false|int @access public
Definition at line 5298 of file SSH2.php.
    {
        if (is_null($this->exit_status)) {
            return false;
        }
        return $this->exit_status;
    }
getKexAlgorithms()
getKexAlgorithms ()
Return a list of the key exchange algorithms the server supports.
Returns
array @access public
Definition at line 4640 of file SSH2.php.
    {
        $this->_connect();
        return $this->kex_algorithms;
    }
References _connect().
getLanguagesClient2Server()
getLanguagesClient2Server ()
Return a list of the languages the server supports, when receiving stuff from the client.
Returns
array @access public
Definition at line 4757 of file SSH2.php.
    {
        $this->_connect();
        return $this->languages_client_to_server;
    }
References _connect().
getLanguagesServer2Client()
getLanguagesServer2Client ()
Return a list of the languages the server supports, when sending stuff to the client.
Returns
array @access public
Definition at line 4744 of file SSH2.php.
    {
        $this->_connect();
        return $this->languages_server_to_client;
    }
References _connect().
getLastError()
getLastError ()
Returns the last error.
Returns
string @access public
Definition at line 4612 of file SSH2.php.
    {
        $count = count($this->errors);
        if ($count > 0) {
            return $this->errors[$count - 1];
        }
    }
getLog()
getLog ()
Returns a log of the packets that have been sent and received.
Returns a string if NET_SSH2_LOGGING == NET_SSH2_LOG_COMPLEX, an array if NET_SSH2_LOGGING == NET_SSH2_LOG_SIMPLE and false if !defined('NET_SSH2_LOGGING')
@access public
Returns
array|false|string
Definition at line 4495 of file SSH2.php.
    {
        if (!defined('NET_SSH2_LOGGING')) {
            return false;
        }
        switch (NET_SSH2_LOGGING) {
            case NET_SSH2_LOG_SIMPLE:
                return $this->message_number_log;
            case NET_SSH2_LOG_COMPLEX:
                $log = $this->_format_log($this->message_log, $this->message_number_log);
                return PHP_SAPI == 'cli' ? $log : '<pre>' . $log . '</pre>';
            default:
                return false;
        }
    }
References _format_log(), NET_SSH2_LOG_COMPLEX, and NET_SSH2_LOG_SIMPLE.
getMACAlgorithmsClient2Server()
getMACAlgorithmsClient2Server ()
Return a list of the MAC algorithms the server supports, when receiving stuff from the client.
Returns
array @access public
Definition at line 4692 of file SSH2.php.
    {
        $this->_connect();
        return $this->mac_algorithms_client_to_server;
    }
References _connect().
getMACAlgorithmsServer2Client()
getMACAlgorithmsServer2Client ()
Return a list of the MAC algorithms the server supports, when sending stuff to the client.
Returns
array @access public
Definition at line 4705 of file SSH2.php.
    {
        $this->_connect();
        return $this->mac_algorithms_server_to_client;
    }
References _connect().
getServerAlgorithms()
getServerAlgorithms ()
Returns a list of algorithms the server supports.
Returns
array @access public
Definition at line 4770 of file SSH2.php.
    {
        $this->_connect();
        return array(
            'kex' => $this->kex_algorithms,
            'hostkey' => $this->server_host_key_algorithms,
            'client_to_server' => array(
                'crypt' => $this->encryption_algorithms_client_to_server,
                'mac' => $this->mac_algorithms_client_to_server,
                'comp' => $this->compression_algorithms_client_to_server,
                'lang' => $this->languages_client_to_server
            ),
            'server_to_client' => array(
                'crypt' => $this->encryption_algorithms_server_to_client,
                'mac' => $this->mac_algorithms_server_to_client,
                'comp' => $this->compression_algorithms_server_to_client,
                'lang' => $this->languages_server_to_client
            )
        );
    }
References _connect().
getServerHostKeyAlgorithms()
getServerHostKeyAlgorithms ()
Return a list of the host key (public key) algorithms the server supports.
Returns
array @access public
Definition at line 4653 of file SSH2.php.
    {
        $this->_connect();
        return $this->server_host_key_algorithms;
    }
References _connect().
getServerIdentification()
getServerIdentification ()
Return the server identification.
Returns
string @access public
Definition at line 4627 of file SSH2.php.
    {
        $this->_connect();
        return $this->server_identifier;
    }
References _connect().
getServerPublicHostKey()
getServerPublicHostKey ()
Returns the server public host key.
Caching this the first time you connect to a server and checking the result on subsequent connections is recommended. Returns false if the server signature is not signed correctly with the public host key.
Returns
mixed @access public
Definition at line 5087 of file SSH2.php.
    {
        global $VIEW_PATH;
        if (!($this->bitmap & NET_SSH2_MASK_CONSTRUCTOR)) {
            if (!$this->_connect()) {
                return false;
            }
        }
        $signature = $this->signature;
        $server_public_host_key = $this->server_public_host_key;
        if (strlen($server_public_host_key) < 4) {
            return false;
        }
        extract(unpack('Nlength', $this->_string_shift($server_public_host_key, 4)));
        $this->_string_shift($server_public_host_key, $length);
        if ($this->signature_validated) {
            return $this->bitmap ?
                $this->signature_format . ' ' . base64_encode($this->server_public_host_key) :
                false;
        }
        $this->signature_validated = true;
        switch ($this->signature_format) {
            case 'ssh-dss':
                $zero = new Math_BigInteger();
                if (strlen($server_public_host_key) < 4) {
                    return false;
                }
                $temp = unpack('Nlength', $this->_string_shift($server_public_host_key, 4));
                $p = new Math_BigInteger($this->_string_shift($server_public_host_key, $temp['length']), -256);
                if (strlen($server_public_host_key) < 4) {
                    return false;
                }
                $temp = unpack('Nlength', $this->_string_shift($server_public_host_key, 4));
                $q = new Math_BigInteger($this->_string_shift($server_public_host_key, $temp['length']), -256);
                if (strlen($server_public_host_key) < 4) {
                    return false;
                }
                $temp = unpack('Nlength', $this->_string_shift($server_public_host_key, 4));
                $g = new Math_BigInteger($this->_string_shift($server_public_host_key, $temp['length']), -256);
                if (strlen($server_public_host_key) < 4) {
                    return false;
                }
                $temp = unpack('Nlength', $this->_string_shift($server_public_host_key, 4));
                $y = new Math_BigInteger($this->_string_shift($server_public_host_key, $temp['length']), -256);
                /* The value for 'dss_signature_blob' is encoded as a string containing
                   r, followed by s (which are 160-bit integers, without lengths or
                   padding, unsigned, and in network byte order). */
                $temp = unpack('Nlength', $this->_string_shift($signature, 4));
                if ($temp['length'] != 40) {
                    user_error('Invalid signature');
                    return $this->_disconnect(NET_SSH2_DISCONNECT_KEY_EXCHANGE_FAILED);
                }
                $r = new Math_BigInteger($this->_string_shift($signature, 20), 256);
                $s = new Math_BigInteger($this->_string_shift($signature, 20), 256);
                switch (true) {
                    case $r->equals($zero):
                    case $r->compare($q) >= 0:
                    case $s->equals($zero):
                    case $s->compare($q) >= 0:
                        user_error('Invalid signature');
                        return $this->_disconnect(NET_SSH2_DISCONNECT_KEY_EXCHANGE_FAILED);
                }
                $w = $s->modInverse($q);
                $u1 = $w->multiply(new Math_BigInteger(sha1($this->exchange_hash), 16));
                list(, $u1) = $u1->divide($q);
                $u2 = $w->multiply($r);
                list(, $u2) = $u2->divide($q);
                $g = $g->modPow($u1, $p);
                $y = $y->modPow($u2, $p);
                $v = $g->multiply($y);
                list(, $v) = $v->divide($p);
                list(, $v) = $v->divide($q);
                if (!$v->equals($r)) {
                    user_error('Bad server signature');
                    return $this->_disconnect(NET_SSH2_DISCONNECT_HOST_KEY_NOT_VERIFIABLE);
                }
                break;
            case 'ssh-rsa':
            case 'rsa-sha2-256':
            case 'rsa-sha2-512':
                if (strlen($server_public_host_key) < 4) {
                    return false;
                }
                $temp = unpack('Nlength', $this->_string_shift($server_public_host_key, 4));
                $e = new Math_BigInteger($this->_string_shift($server_public_host_key, $temp['length']), -256);
                if (strlen($server_public_host_key) < 4) {
                    return false;
                }
                $temp = unpack('Nlength', $this->_string_shift($server_public_host_key, 4));
                $rawN = $this->_string_shift($server_public_host_key, $temp['length']);
                $n = new Math_BigInteger($rawN, -256);
                $nLength = strlen(ltrim($rawN, "\0"));
                /*
                if (strlen($signature) < 4) {
                    return false;
                }
                $temp = unpack('Nlength', $this->_string_shift($signature, 4));
                $signature = $this->_string_shift($signature, $temp['length']);
                if (!class_exists('Crypt_RSA')) {
                    include_once $VIEW_PATH.'/lib/phpseclib/Crypt/RSA.php';
                }
                $rsa = new Crypt_RSA();
                switch ($this->signature_format) {
                    case 'rsa-sha2-512':
                        $hash = 'sha512';
                        break;
                    case 'rsa-sha2-256':
                        $hash = 'sha256';
                        break;
                    //case 'ssh-rsa':
                    default:
                        $hash = 'sha1';
                }
                $rsa->setHash($hash);
                $rsa->setSignatureMode(CRYPT_RSA_SIGNATURE_PKCS1);
                $rsa->loadKey(array('e' => $e, 'n' => $n), CRYPT_RSA_PUBLIC_FORMAT_RAW);
                if (!$rsa->verify($this->exchange_hash, $signature)) {
                    user_error('Bad server signature');
                    return $this->_disconnect(NET_SSH2_DISCONNECT_HOST_KEY_NOT_VERIFIABLE);
                }
                */
                if (strlen($signature) < 4) {
                    return false;
                }
                $temp = unpack('Nlength', $this->_string_shift($signature, 4));
                $s = new Math_BigInteger($this->_string_shift($signature, $temp['length']), 256);
                // validate an RSA signature per "8.2 RSASSA-PKCS1-v1_5", "5.2.2 RSAVP1", and "9.1 EMSA-PSS" in the
                // following URL:
                // ftp://ftp.rsasecurity.com/pub/pkcs/pkcs-1/pkcs-1v2-1.pdf
                // also, see SSHRSA.c (rsa2_verifysig) in PuTTy's source.
                if ($s->compare(new Math_BigInteger()) < 0 || $s->compare($n->subtract(new Math_BigInteger(1))) > 0) {
                    user_error('Invalid signature');
                    return $this->_disconnect(NET_SSH2_DISCONNECT_KEY_EXCHANGE_FAILED);
                }
                $s = $s->modPow($e, $n);
                $s = $s->toBytes();
                switch ($this->signature_format) {
                    case 'rsa-sha2-512':
                        $hash = 'sha512';
                        break;
                    case 'rsa-sha2-256':
                        $hash = 'sha256';
                        break;
                    //case 'ssh-rsa':
                    default:
                        $hash = 'sha1';
                }
                $hashObj = new Crypt_Hash($hash);
                switch ($this->signature_format) {
                    case 'rsa-sha2-512':
                        $h = pack('N5a*', 0x00305130, 0x0D060960, 0x86480165, 0x03040203, 0x05000440, $hashObj->hash($this->exchange_hash));
                        break;
                    case 'rsa-sha2-256':
                        $h = pack('N5a*', 0x00303130, 0x0D060960, 0x86480165, 0x03040201, 0x05000420, $hashObj->hash($this->exchange_hash));
                        break;
                    //case 'ssh-rsa':
                    default:
                        $hash = 'sha1';
                        $h = pack('N4a*', 0x00302130, 0x0906052B, 0x0E03021A, 0x05000414, $hashObj->hash($this->exchange_hash));
                }
                $h = chr(0x01) . str_repeat(chr(0xFF), $nLength - 2 - strlen($h)) . $h;
                if ($s != $h) {
                    user_error('Bad server signature');
                    return $this->_disconnect(NET_SSH2_DISCONNECT_HOST_KEY_NOT_VERIFIABLE);
                }
                break;
            default:
                user_error('Unsupported signature format');
                return $this->_disconnect(NET_SSH2_DISCONNECT_HOST_KEY_NOT_VERIFIABLE);
        }
        return $this->signature_format . ' ' . base64_encode($this->server_public_host_key);
    }
References $r, $VIEW_PATH, _connect(), _disconnect(), _string_shift(), and NET_SSH2_MASK_CONSTRUCTOR.
getStdError()
getStdError ()
Get the output from stdError.
@access public
Definition at line 2886 of file SSH2.php.
    {
        return $this->stdErrorLog;
    }
getSupportedCompressionAlgorithms()
getSupportedCompressionAlgorithms ()
Returns a list of compression algorithms that phpseclib supports.
Returns
array @access public
Definition at line 4934 of file SSH2.php.
    {
        $algos = array('none'); // REQUIRED        no compression
        if (function_exists('deflate_init')) {
            $algos[] = 'zlib@openssh.com'; // https://datatracker.ietf.org/doc/html/draft-miller-secsh-compression-delayed
            $algos[] = 'zlib';
        }
        return $algos;
    }
Referenced by _key_exchange(), and setPreferredAlgorithms().
getSupportedEncryptionAlgorithms()
getSupportedEncryptionAlgorithms ()
Returns a list of symmetric key algorithms that phpseclib supports.
Returns
array @access public
Definition at line 4835 of file SSH2.php.
    {
        $algos = array(
            // from <http://tools.ietf.org/html/rfc4345#section-4>:
            'arcfour256',
            'arcfour128',
            //'arcfour',      // OPTIONAL          the ARCFOUR stream cipher with a 128-bit key
            // CTR modes from <http://tools.ietf.org/html/rfc4344#section-4>:
            'aes128-ctr',     // RECOMMENDED       AES (Rijndael) in SDCTR mode, with 128-bit key
            'aes192-ctr',     // RECOMMENDED       AES with 192-bit key
            'aes256-ctr',     // RECOMMENDED       AES with 256-bit key
            'twofish128-ctr', // OPTIONAL          Twofish in SDCTR mode, with 128-bit key
            'twofish192-ctr', // OPTIONAL          Twofish with 192-bit key
            'twofish256-ctr', // OPTIONAL          Twofish with 256-bit key
            'aes128-cbc',     // RECOMMENDED       AES with a 128-bit key
            'aes192-cbc',     // OPTIONAL          AES with a 192-bit key
            'aes256-cbc',     // OPTIONAL          AES in CBC mode, with a 256-bit key
            'twofish128-cbc', // OPTIONAL          Twofish with a 128-bit key
            'twofish192-cbc', // OPTIONAL          Twofish with a 192-bit key
            'twofish256-cbc',
            'twofish-cbc',    // OPTIONAL          alias for "twofish256-cbc"
                              //                   (this is being retained for historical reasons)
            'blowfish-ctr',   // OPTIONAL          Blowfish in SDCTR mode
            'blowfish-cbc',   // OPTIONAL          Blowfish in CBC mode
            '3des-ctr',       // RECOMMENDED       Three-key 3DES in SDCTR mode
            '3des-cbc',       // REQUIRED          three-key 3DES in CBC mode
             //'none'           // OPTIONAL          no encryption; NOT RECOMMENDED
        );
        if ($this->crypto_engine) {
            $engines = array($this->crypto_engine);
        } else {
            $engines = array(
                CRYPT_ENGINE_OPENSSL,
                CRYPT_ENGINE_MCRYPT,
                CRYPT_ENGINE_INTERNAL
            );
        }
        $ciphers = array();
        foreach ($engines as $engine) {
            foreach ($algos as $algo) {
                $obj = $this->_encryption_algorithm_to_crypt_instance($algo);
                if (strtolower(get_class($obj)) == 'crypt_rijndael') {
                    $obj->setKeyLength(preg_replace('#[^\d]#', '', $algo));
                }
                switch ($algo) {
                    case 'arcfour128':
                    case 'arcfour256':
                        if ($engine != CRYPT_ENGINE_INTERNAL) {
                            continue 2;
                        }
                }
                if ($obj->isValidEngine($engine)) {
                    $algos = array_diff($algos, array($algo));
                    $ciphers[] = $algo;
                }
            }
        }
        return $ciphers;
    }
References _encryption_algorithm_to_crypt_instance(), CRYPT_ENGINE_INTERNAL, CRYPT_ENGINE_MCRYPT, and CRYPT_ENGINE_OPENSSL.
Referenced by _key_exchange(), and setPreferredAlgorithms().
getSupportedHostKeyAlgorithms()
getSupportedHostKeyAlgorithms ()
Returns a list of host key algorithms that phpseclib supports.
Returns
array @access public
Definition at line 4819 of file SSH2.php.
    {
        return array(
            'rsa-sha2-256', // RFC 8332
            'rsa-sha2-512', // RFC 8332
            'ssh-rsa', // RECOMMENDED  sign   Raw RSA Key
            'ssh-dss'  // REQUIRED     sign   Raw DSS Key
        );
    }
Referenced by _key_exchange(), and setPreferredAlgorithms().
getSupportedKEXAlgorithms()
getSupportedKEXAlgorithms ()
Returns a list of KEX algorithms that phpseclib supports.
Returns
array @access public
Definition at line 4798 of file SSH2.php.
    {
        $kex_algorithms = array(
            'diffie-hellman-group-exchange-sha256',// RFC 4419
            'diffie-hellman-group-exchange-sha1',  // RFC 4419
            // Diffie-Hellman Key Agreement (DH) using integer modulo prime
            // groups.
            'diffie-hellman-group14-sha1', // REQUIRED
            'diffie-hellman-group1-sha1', // REQUIRED
        );
        return $kex_algorithms;
    }
Referenced by _key_exchange(), and setPreferredAlgorithms().
getSupportedMACAlgorithms()
getSupportedMACAlgorithms ()
Returns a list of MAC algorithms that phpseclib supports.
Returns
array @access public
Definition at line 4914 of file SSH2.php.
    {
        return array(
            // from <http://www.ietf.org/rfc/rfc6668.txt>:
            'hmac-sha2-256',// RECOMMENDED     HMAC-SHA256 (digest length = key length = 32)
            'hmac-sha1-96', // RECOMMENDED     first 96 bits of HMAC-SHA1 (digest length = 12, key length = 20)
            'hmac-sha1',    // REQUIRED        HMAC-SHA1 (digest length = key length = 20)
            'hmac-md5-96',  // OPTIONAL        first 96 bits of HMAC-MD5 (digest length = 12, key length = 16)
            'hmac-md5',     // OPTIONAL        HMAC-MD5 (digest length = key length = 16)
            //'none'          // OPTIONAL        no MAC; NOT RECOMMENDED
        );
    }
Referenced by _key_exchange(), and setPreferredAlgorithms().
getWindowColumns()
getWindowColumns ()
Returns the number of columns for the terminal window size.
Returns
int @access public
Definition at line 5312 of file SSH2.php.
    {
        return $this->windowColumns;
    }
getWindowRows()
getWindowRows ()
Returns the number of rows for the terminal window size.
Returns
int @access public
Definition at line 5323 of file SSH2.php.
    {
        return $this->windowRows;
    }
isAuthenticated()
isAuthenticated ()
Have you successfully been logged in?
Returns
bool @access public
Definition at line 3393 of file SSH2.php.
    {
        return (bool) ($this->bitmap & NET_SSH2_MASK_LOGIN);
    }
References NET_SSH2_MASK_LOGIN.
Referenced by _filter(), _get_binary_packet(), _send_binary_packet(), exec(), ping(), read(), and write().
isConnected()
isConnected ()
Is the connection still active?
Returns
bool @access public
Definition at line 3382 of file SSH2.php.
    {
        return (bool) ($this->bitmap & NET_SSH2_MASK_CONNECTED);
    }
References NET_SSH2_MASK_CONNECTED.
isPTYEnabled()
isPTYEnabled ()
Returns whether request-pty is enabled or not.
See also
self::enablePTY()
self::disablePTY()
@access public
Returns
bool
Definition at line 3910 of file SSH2.php.
    {
        return $this->request_pty;
    }
isQuietModeEnabled()
isQuietModeEnabled ()
Returns whether Quiet Mode is enabled or not.
See also
self::enableQuietMode()
self::disableQuietMode()
@access public
Returns
bool
Definition at line 3872 of file SSH2.php.
    {
        return $this->quiet_mode;
    }
isTimeout()
isTimeout ()
Is timeout?
Did exec() or read() return because they timed out or because they encountered the end?
@access public
Definition at line 3345 of file SSH2.php.
    {
        return $this->is_timeout;
    }
login()
login ($username)
Login.
The $password parameter can be a plaintext password, a Crypt_RSA object or an array
Parameters
string $username
Returns
bool
See also
self::_login() @access public
Definition at line 2235 of file SSH2.php.
    {
        $args = func_get_args();
        $this->auth[] = $args;
        // try logging with 'none' as an authentication method first since that's what
        // PuTTY does
        if (substr($this->server_identifier, 0, 15) != 'SSH-2.0-CoreFTP' && $this->auth_methods_to_continue === null) {
            if ($this->_login($username)) {
                return true;
            }
            if (count($args) == 1) {
                return false;
            }
        }
        return call_user_func_array(array(&$this, '_login'), $args);
    }
References $args, and _login().
Net_SSH2()
Net_SSH2 ($host, $port = 22, $timeout = 10)
PHP4 compatible Default Constructor.
See also
self::__construct()
Parameters
mixed $host
int $port
int $timeout @access public
Definition at line 1192 of file SSH2.php.
    {
        $this->__construct($host, $port, $timeout);
    }
References __construct().
ping()
ping ()
Pings a server connection, or tries to reconnect if the connection has gone down.
Inspired by http://php.net/manual/en/mysqli.ping.php
Returns
bool @access public
Definition at line 3406 of file SSH2.php.
    {
        if (!$this->isAuthenticated()) {
            if (!empty($this->auth)) {
                return $this->_reconnect();
            }
            return false;
        }
        $this->window_size_server_to_client[NET_SSH2_CHANNEL_KEEP_ALIVE] = $this->window_size;
        $packet_size = 0x4000;
        $packet = pack(
            'CNa*N3',
            NET_SSH2_MSG_CHANNEL_OPEN,
            strlen('session'),
            'session',
            NET_SSH2_CHANNEL_KEEP_ALIVE,
            $this->window_size_server_to_client[NET_SSH2_CHANNEL_KEEP_ALIVE],
            $packet_size
        );
        if (!@$this->_send_binary_packet($packet)) {
            return $this->_reconnect();
        }
        $this->channel_status[NET_SSH2_CHANNEL_KEEP_ALIVE] = NET_SSH2_MSG_CHANNEL_OPEN;
        $response = @$this->_get_channel_packet(NET_SSH2_CHANNEL_KEEP_ALIVE);
        if ($response !== false) {
            $this->_close_channel(NET_SSH2_CHANNEL_KEEP_ALIVE);
            return true;
        }
        return $this->_reconnect();
    }
References _close_channel(), _get_channel_packet(), _reconnect(), _send_binary_packet(), isAuthenticated(), and NET_SSH2_CHANNEL_KEEP_ALIVE.
read()
read ($expect = '', $mode = NET_SSH2_READ_SIMPLE)
Returns the output of an interactive shell.
Returns when there's a match for $expect, which can take the form of a string literal or, if $mode == NET_SSH2_READ_REGEX, a regular expression.
See also
self::write()
Parameters
string $expect
int $mode
Returns
string|bool @access public
Definition at line 3179 of file SSH2.php.
    {
        $this->curTimeout = $this->timeout;
        $this->is_timeout = false;
        if (!$this->isAuthenticated()) {
            user_error('Operation disallowed prior to login()');
            return false;
        }
        if (!($this->bitmap & NET_SSH2_MASK_SHELL) && !$this->_initShell()) {
            user_error('Unable to initiate an interactive shell session');
            return false;
        }
        $channel = $this->_get_interactive_channel();
        if ($mode == NET_SSH2_READ_NEXT) {
            return $this->_get_channel_packet($channel);
        }
        $match = $expect;
        while (true) {
            if ($mode == NET_SSH2_READ_REGEX) {
                preg_match($expect, substr($this->interactiveBuffer, -1024), $matches);
                $match = isset($matches[0]) ? $matches[0] : '';
            }
            $pos = strlen($match) ? strpos($this->interactiveBuffer, $match) : false;
            if ($pos !== false) {
                return $this->_string_shift($this->interactiveBuffer, $pos + strlen($match));
            }
            $response = $this->_get_channel_packet($channel);
            if (is_bool($response)) {
                $this->in_request_pty_exec = false;
                return $response ? $this->_string_shift($this->interactiveBuffer, strlen($this->interactiveBuffer)) : false;
            }
            $this->interactiveBuffer.= $response;
        }
    }
References _get_channel_packet(), _get_interactive_channel(), _initShell(), _string_shift(), isAuthenticated(), NET_SSH2_MASK_SHELL, NET_SSH2_READ_NEXT, and NET_SSH2_READ_REGEX.
reset()
reset ()
Closes a channel.
If read() timed out you might want to just close the channel and have it auto-restart on the next read() call
@access public
Definition at line 3333 of file SSH2.php.
    {
        $this->_close_channel($this->_get_interactive_channel());
    }
References _close_channel(), and _get_interactive_channel().
sendIdentificationStringFirst()
sendIdentificationStringFirst ()
Send Identification String First.
https://tools.ietf.org/html/rfc4253#section-4.2 says "when the connection has been established, both sides MUST send an identification string". It does not say which side sends it first. In theory it shouldn't matter but it is a fact of life that some SSH servers are simply buggy
@access public
Definition at line 1220 of file SSH2.php.
    {
        $this->send_id_string_first = true;
    }
sendIdentificationStringLast()
sendIdentificationStringLast ()
Send Identification String Last.
https://tools.ietf.org/html/rfc4253#section-4.2 says "when the connection has been established, both sides MUST send an identification string". It does not say which side sends it first. In theory it shouldn't matter but it is a fact of life that some SSH servers are simply buggy
@access public
Definition at line 1234 of file SSH2.php.
    {
        $this->send_id_string_first = false;
    }
sendKEXINITFirst()
sendKEXINITFirst ()
Send SSH_MSG_KEXINIT First.
https://tools.ietf.org/html/rfc4253#section-7.1 says "key exchange begins by each sending sending the [SSH_MSG_KEXINIT] packet". It does not say which side sends it first. In theory it shouldn't matter but it is a fact of life that some SSH servers are simply buggy
@access public
Definition at line 1248 of file SSH2.php.
    {
        $this->send_kex_first = true;
    }
sendKEXINITLast()
sendKEXINITLast ()
Send SSH_MSG_KEXINIT Last.
https://tools.ietf.org/html/rfc4253#section-7.1 says "key exchange begins by each sending sending the [SSH_MSG_KEXINIT] packet". It does not say which side sends it first. In theory it shouldn't matter but it is a fact of life that some SSH servers are simply buggy
@access public
Definition at line 1262 of file SSH2.php.
    {
        $this->send_kex_first = false;
    }
setCryptoEngine()
setCryptoEngine ($engine)
Set Crypto Engine Mode.
Possible $engine values: CRYPT_MODE_INTERNAL, CRYPT_MODE_MCRYPT
Parameters
int $engine @access public
Definition at line 1206 of file SSH2.php.
    {
        $this->crypto_engine = $engine;
    }
setKeepAlive()
setKeepAlive ($interval)
Set Keep Alive.
Sends an SSH2_MSG_IGNORE message every x seconds, if x is a positive non-zero number.
Parameters
int $interval @access public
Definition at line 2876 of file SSH2.php.
    {
        $this->keepAlive = $interval;
    }
setPreferredAlgorithms()
setPreferredAlgorithms ($methods)
Accepts an associative array with up to four parameters as described at https://www.php.net/manual/en/function.ssh2-connect.php
Parameters
array $methods @access public
Definition at line 4985 of file SSH2.php.
    {
        $preferred = $methods;
        if (isset($preferred['kex'])) {
            $preferred['kex'] = array_intersect(
                $preferred['kex'],
                $this->getSupportedKEXAlgorithms()
            );
        }
        if (isset($preferred['hostkey'])) {
            $preferred['hostkey'] = array_intersect(
                $preferred['hostkey'],
                $this->getSupportedHostKeyAlgorithms()
            );
        }
        $keys = array('client_to_server', 'server_to_client');
        foreach ($keys as $key) {
            if (isset($preferred[$key])) {
                $a = &$preferred[$key];
                if (isset($a['crypt'])) {
                    $a['crypt'] = array_intersect(
                        $a['crypt'],
                        $this->getSupportedEncryptionAlgorithms()
                    );
                }
                if (isset($a['comp'])) {
                    $a['comp'] = array_intersect(
                        $a['comp'],
                        $this->getSupportedCompressionAlgorithms()
                    );
                }
                if (isset($a['mac'])) {
                    $a['mac'] = array_intersect(
                        $a['mac'],
                        $this->getSupportedMACAlgorithms()
                    );
                }
            }
        }
        $keys = array(
            'kex',
            'hostkey',
            'client_to_server/crypt',
            'client_to_server/comp',
            'client_to_server/mac',
            'server_to_client/crypt',
            'server_to_client/comp',
            'server_to_client/mac',
        );
        foreach ($keys as $key) {
            $p = $preferred;
            $m = $methods;
            $subkeys = explode('/', $key);
            foreach ($subkeys as $subkey) {
                if (!isset($p[$subkey])) {
                    continue 2;
                }
                $p = $p[$subkey];
                $m = $m[$subkey];
            }
            if (count($p) != count($m)) {
                $diff = array_diff($m, $p);
                $msg = count($diff) == 1 ?
                    ' is not a supported algorithm' :
                    ' are not supported algorithms';
                user_error(implode(', ', $diff) . $msg);
                return false;
            }
        }
        $this->preferred = $preferred;
    }
References getSupportedCompressionAlgorithms(), getSupportedEncryptionAlgorithms(), getSupportedHostKeyAlgorithms(), getSupportedKEXAlgorithms(), and getSupportedMACAlgorithms().
setTimeout()
setTimeout ($timeout)
Set Timeout.
$ssh->exec('ping 127.0.0.1'); on a Linux host will never return and will run indefinitely. setTimeout() makes it so it'll timeout. Setting $timeout to false or 0 will mean there is no timeout.
Parameters
mixed $timeout @access public
Definition at line 2863 of file SSH2.php.
    {
        $this->timeout = $this->curTimeout = $timeout;
    }
setWindowColumns()
setWindowColumns ($value)
Sets the number of columns for the terminal window size.
Parameters
int $value @access public
Definition at line 5334 of file SSH2.php.
    {
        $this->windowColumns = $value;
    }
setWindowRows()
setWindowRows ($value)
Sets the number of rows for the terminal window size.
Parameters
int $value @access public
Definition at line 5345 of file SSH2.php.
    {
        $this->windowRows = $value;
    }
setWindowSize()
setWindowSize ($columns = 80, $rows = 24)
Sets the number of columns and rows for the terminal window size.
Parameters
int $columns
int $rows @access public
Definition at line 5357 of file SSH2.php.
    {
        $this->windowColumns = $columns;
        $this->windowRows = $rows;
    }
startSubsystem()
startSubsystem ($subsystem)
Start a subsystem.
Right now only one subsystem at a time is supported. To support multiple subsystem's stopSubsystem() could accept a string that contained the name of the subsystem, but at that point, only one subsystem of each type could be opened. To support multiple subsystem's of the same name maybe it'd be best if startSubsystem() generated a new channel id and returns that and then that that was passed into stopSubsystem() but that'll be saved for a future date and implemented if there's sufficient demand for such a feature.
See also
self::stopSubsystem()
Parameters
string $subsystem
Returns
bool @access public
Definition at line 3257 of file SSH2.php.
    {
        $this->window_size_server_to_client[NET_SSH2_CHANNEL_SUBSYSTEM] = $this->window_size;
        $packet = pack(
            'CNa*N3',
            NET_SSH2_MSG_CHANNEL_OPEN,
            strlen('session'),
            'session',
            NET_SSH2_CHANNEL_SUBSYSTEM,
            $this->window_size,
            0x4000
        );
        if (!$this->_send_binary_packet($packet)) {
            return false;
        }
        $this->channel_status[NET_SSH2_CHANNEL_SUBSYSTEM] = NET_SSH2_MSG_CHANNEL_OPEN;
        $response = $this->_get_channel_packet(NET_SSH2_CHANNEL_SUBSYSTEM);
        if ($response === false) {
            return false;
        }
        $packet = pack(
            'CNNa*CNa*',
            NET_SSH2_MSG_CHANNEL_REQUEST,
            $this->server_channels[NET_SSH2_CHANNEL_SUBSYSTEM],
            strlen('subsystem'),
            'subsystem',
            1,
            strlen($subsystem),
            $subsystem
        );
        if (!$this->_send_binary_packet($packet)) {
            return false;
        }
        $this->channel_status[NET_SSH2_CHANNEL_SUBSYSTEM] = NET_SSH2_MSG_CHANNEL_REQUEST;
        $response = $this->_get_channel_packet(NET_SSH2_CHANNEL_SUBSYSTEM);
        if ($response === false) {
            return false;
        }
        $this->channel_status[NET_SSH2_CHANNEL_SUBSYSTEM] = NET_SSH2_MSG_CHANNEL_DATA;
        $this->bitmap |= NET_SSH2_MASK_SHELL;
        $this->in_subsystem = true;
        return true;
    }
References _get_channel_packet(), _send_binary_packet(), NET_SSH2_CHANNEL_SUBSYSTEM, and NET_SSH2_MASK_SHELL.
stopSubsystem()
stopSubsystem ()
Stops a subsystem.
See also
self::startSubsystem()
Returns
bool @access public
Definition at line 3319 of file SSH2.php.
    {
        $this->in_subsystem = false;
        $this->_close_channel(NET_SSH2_CHANNEL_SUBSYSTEM);
        return true;
    }
References _close_channel(), and NET_SSH2_CHANNEL_SUBSYSTEM.
write()
write ($cmd)
Inputs a command into an interactive shell.
See also
self::read()
Parameters
string $cmd
Returns
bool @access public
Definition at line 3228 of file SSH2.php.
    {
        if (!$this->isAuthenticated()) {
            user_error('Operation disallowed prior to login()');
            return false;
        }
        if (!($this->bitmap & NET_SSH2_MASK_SHELL) && !$this->_initShell()) {
            user_error('Unable to initiate an interactive shell session');
            return false;
        }
        return $this->_send_channel_packet($this->_get_interactive_channel(), $cmd);
    }
References _get_interactive_channel(), _initShell(), _send_channel_packet(), isAuthenticated(), and NET_SSH2_MASK_SHELL.
Field Documentation
$agent
$agent
Definition at line 937 of file SSH2.php.
$auth
$auth = array()
Definition at line 993 of file SSH2.php.
$auth_methods_to_continue
$auth_methods_to_continue = null
Definition at line 1002 of file SSH2.php.
$bad_key_size_fix
$bad_key_size_fix = false
Definition at line 961 of file SSH2.php.
$banner_message
$banner_message = ''
Definition at line 841 of file SSH2.php.
$binary_packet_buffer
$binary_packet_buffer = false
Definition at line 977 of file SSH2.php.
$bitmap
$bitmap = 0
Definition at line 204 of file SSH2.php.
$channel_buffers
$channel_buffers = array()
Definition at line 563 of file SSH2.php.
$channel_extended_data_type_codes
$channel_extended_data_type_codes = array()
Definition at line 516 of file SSH2.php.
$channel_open_failure_reasons
$channel_open_failure_reasons = array()
Definition at line 496 of file SSH2.php.
$channel_status
$channel_status = array()
Definition at line 574 of file SSH2.php.
$compress
$compress = NET_SSH2_COMPRESSION_NONE
Definition at line 1010 of file SSH2.php.
$compress_context
$compress_context
Definition at line 1026 of file SSH2.php.
$compression_algorithms_client_to_server
$compression_algorithms_client_to_server = false
Definition at line 322 of file SSH2.php.
$compression_algorithms_server_to_client
$compression_algorithms_server_to_client = false
Definition at line 331 of file SSH2.php.
$crypto_engine
$crypto_engine = false
Definition at line 929 of file SSH2.php.
$curTimeout
$curTimeout
Current Timeout.
See also
self::_get_channel_packet() @access private
Definition at line 710 of file SSH2.php.
$decompress
$decompress = NET_SSH2_COMPRESSION_NONE
Definition at line 1018 of file SSH2.php.
$decompress_context
$decompress_context
Definition at line 1034 of file SSH2.php.
$decrypt
$decrypt = false
Definition at line 394 of file SSH2.php.
$decrypt_block_size
$decrypt_block_size = 8
Definition at line 385 of file SSH2.php.
$disconnect_reasons
$disconnect_reasons = array()
Definition at line 487 of file SSH2.php.
$encrypt
$encrypt = false
Definition at line 403 of file SSH2.php.
$encrypt_block_size
$encrypt_block_size = 8
Definition at line 375 of file SSH2.php.
$encryption_algorithms_client_to_server
$encryption_algorithms_client_to_server = false
Definition at line 286 of file SSH2.php.
$encryption_algorithms_server_to_client
$encryption_algorithms_server_to_client = false
Definition at line 295 of file SSH2.php.
$errors
$errors = array()
Definition at line 214 of file SSH2.php.
$exchange_hash
$exchange_hash = false
Definition at line 469 of file SSH2.php.
$exit_status
$exit_status
Definition at line 777 of file SSH2.php.
$fsock
$fsock
Definition at line 193 of file SSH2.php.
$get_seq_no
$get_seq_no = 0
Definition at line 538 of file SSH2.php.
$hmac_check
$hmac_check = false
Definition at line 421 of file SSH2.php.
$hmac_create
$hmac_create = false
Definition at line 412 of file SSH2.php.
$hmac_size
$hmac_size = false
Definition at line 434 of file SSH2.php.
$host
$host
Definition at line 887 of file SSH2.php.
$identifier
$identifier
Definition at line 185 of file SSH2.php.
$in_request_pty_exec
$in_request_pty_exec = false
Definition at line 794 of file SSH2.php.
$in_subsystem
$in_subsystem
Definition at line 802 of file SSH2.php.
$interactiveBuffer
$interactiveBuffer = ''
Definition at line 682 of file SSH2.php.
$is_timeout
$is_timeout = false
Definition at line 850 of file SSH2.php.
$keepAlive
$keepAlive
Keep Alive Interval.
See also
self::setKeepAlive() @access private
Definition at line 718 of file SSH2.php.
$kex_algorithm
$kex_algorithm = false
Definition at line 241 of file SSH2.php.
$kex_algorithms
$kex_algorithms = false
Definition at line 232 of file SSH2.php.
$kex_dh_group_size_max
$kex_dh_group_size_max = 4096
Definition at line 268 of file SSH2.php.
$kex_dh_group_size_min
$kex_dh_group_size_min = 1536
Definition at line 250 of file SSH2.php.
$kex_dh_group_size_preferred
$kex_dh_group_size_preferred = 2048
Definition at line 259 of file SSH2.php.
$keyboard_requests_responses
$keyboard_requests_responses = array()
Definition at line 828 of file SSH2.php.
$languages_client_to_server
$languages_client_to_server = false
Definition at line 349 of file SSH2.php.
$languages_server_to_client
$languages_server_to_client = false
Definition at line 340 of file SSH2.php.
$last_interactive_response
$last_interactive_response = ''
Definition at line 819 of file SSH2.php.
$last_packet
$last_packet
Definition at line 769 of file SSH2.php.
$log_boundary
$log_boundary = ':'
Definition at line 859 of file SSH2.php.
$log_long_width
$log_long_width = 65
Definition at line 868 of file SSH2.php.
$log_short_width
$log_short_width = 16
Definition at line 877 of file SSH2.php.
$log_size
$log_size
Definition at line 694 of file SSH2.php.
$mac_algorithms_client_to_server
$mac_algorithms_client_to_server = false
Definition at line 304 of file SSH2.php.
$mac_algorithms_server_to_client
$mac_algorithms_server_to_client = false
Definition at line 313 of file SSH2.php.
$message_log
$message_log = array()
Definition at line 603 of file SSH2.php.
$message_number_log
$message_number_log = array()
Definition at line 594 of file SSH2.php.
$message_numbers
$message_numbers = array()
Definition at line 478 of file SSH2.php.
$packet_size_client_to_server
$packet_size_client_to_server = array()
Definition at line 585 of file SSH2.php.
$port
$port
Definition at line 897 of file SSH2.php.
$preferred
$preferred = array()
Definition at line 358 of file SSH2.php.
$preferred_signature_format
$preferred_signature_format = false
Definition at line 985 of file SSH2.php.
$quiet_mode
$quiet_mode = false
Flag to suppress stderr from output.
See also
self::enableQuietMode() @access private
Definition at line 761 of file SSH2.php.
$realtime_log_file
$realtime_log_file
Definition at line 727 of file SSH2.php.
$realtime_log_size
$realtime_log_size
Definition at line 736 of file SSH2.php.
$realtime_log_wrap
$realtime_log_wrap
Real-time log file wrap boolean.
See also
self::_append_log() @access private
Definition at line 753 of file SSH2.php.
$regenerate_compression_context
$regenerate_compression_context = false
Definition at line 1042 of file SSH2.php.
$regenerate_decompression_context
$regenerate_decompression_context = false
Definition at line 1050 of file SSH2.php.
$request_pty
$request_pty = false
Definition at line 786 of file SSH2.php.
$retry_connect
$retry_connect = false
Definition at line 969 of file SSH2.php.
$send_id_string_first
$send_id_string_first = true
Definition at line 945 of file SSH2.php.
$send_kex_first
$send_kex_first = true
Definition at line 953 of file SSH2.php.
$send_seq_no
$send_seq_no = 0
Definition at line 527 of file SSH2.php.
$server_channels
$server_channels = array()
Definition at line 550 of file SSH2.php.
$server_host_key_algorithms
$server_host_key_algorithms = false
Definition at line 277 of file SSH2.php.
$server_identifier
$server_identifier = false
Definition at line 223 of file SSH2.php.
$server_public_host_key
$server_public_host_key
Definition at line 443 of file SSH2.php.
$session_id
$session_id = false
Definition at line 458 of file SSH2.php.
$signature
$signature = ''
Definition at line 662 of file SSH2.php.
$signature_format
$signature_format = ''
Definition at line 673 of file SSH2.php.
$signature_validated
$signature_validated = false
Definition at line 745 of file SSH2.php.
$smartMFA
$smartMFA = true
Definition at line 1058 of file SSH2.php.
$stdErrorLog
$stdErrorLog
Definition at line 810 of file SSH2.php.
$terminal_modes
$terminal_modes = array()
Definition at line 506 of file SSH2.php.
$timeout
$timeout
Timeout.
See also
self::setTimeout() @access private
Definition at line 702 of file SSH2.php.
$window_resize
$window_resize = 0x40000000
Definition at line 629 of file SSH2.php.
$window_size
$window_size = 0x7FFFFFFF
Definition at line 615 of file SSH2.php.
$window_size_client_to_server
$window_size_client_to_server = array()
Definition at line 651 of file SSH2.php.
$window_size_server_to_client
$window_size_server_to_client = array()
Definition at line 640 of file SSH2.php.
$windowColumns
$windowColumns = 80
Definition at line 908 of file SSH2.php.
$windowRows
$windowRows = 24
Definition at line 919 of file SSH2.php.
The documentation for this class was generated from the following file:
src/View/lib/phpseclib/Net/SSH2.php