PF Firewall: System_SSH_Agent Class Reference
System_SSH_Agent Class Reference
Public Member Functions
__construct ($address=null)
Default Constructor.
System_SSH_Agent ($address=null)
PHP4 compatible Default Constructor.
requestIdentities ()
Request Identities.
startSSHForwarding ($ssh)
Signal that agent forwarding should be requested when a channel is opened.
_request_forwarding ($ssh)
Request agent forwarding of remote server.
_on_channel_open ($ssh)
On successful channel open.
_forward_data ($data)
Forward data to SSH Agent and return data reply.
Data Fields
$fsock
$forward_status = SYSTEM_SSH_AGENT_FORWARD_NONE
Agent forwarding status.
$socket_buffer = ''
Buffer for accumulating forwarded authentication agent data arriving on SSH data channel destined for agent unix socket.
$expected_bytes = 0
Tracking the number of bytes we are expecting to arrive for the agent socket on the SSH data channel.
Detailed Description
Definition at line 329 of file Agent.php.
Constructor & Destructor Documentation
__construct()
__construct ($address = null)
Default Constructor.
Returns
System_SSH_Agent @access public
Definition at line 368 of file Agent.php.
    {
        if (!$address) {
            switch (true) {
                case isset($_SERVER['SSH_AUTH_SOCK']):
                    $address = $_SERVER['SSH_AUTH_SOCK'];
                    break;
                case isset($_ENV['SSH_AUTH_SOCK']):
                    $address = $_ENV['SSH_AUTH_SOCK'];
                    break;
                default:
                    user_error('SSH_AUTH_SOCK not found');
                    return false;
            }
        }
        $this->fsock = fsockopen('unix://' . $address, 0, $errno, $errstr);
        if (!$this->fsock) {
            user_error("Unable to connect to ssh-agent (Error $errno: $errstr)");
        }
    }
Referenced by System_SSH_Agent().
Member Function Documentation
_forward_data()
_forward_data ($data)
Forward data to SSH Agent and return data reply.
Parameters
string $data
Returns
data from SSH Agent @access private
Definition at line 576 of file Agent.php.
    {
        if ($this->expected_bytes > 0) {
            $this->socket_buffer.= $data;
            $this->expected_bytes -= strlen($data);
        } else {
            $agent_data_bytes = current(unpack('N', $data));
            $current_data_bytes = strlen($data);
            $this->socket_buffer = $data;
            if ($current_data_bytes != $agent_data_bytes + 4) {
                $this->expected_bytes = ($agent_data_bytes + 4) - $current_data_bytes;
                return false;
            }
        }
        if (strlen($this->socket_buffer) != fwrite($this->fsock, $this->socket_buffer)) {
            user_error('Connection closed attempting to forward data to SSH agent');
            return false;
        }
        $this->socket_buffer = '';
        $this->expected_bytes = 0;
        $temp = fread($this->fsock, 4);
        if (strlen($temp) != 4) {
            user_error('Connection closed while reading data response');
            return false;
        }
        $agent_reply_bytes = current(unpack('N', $temp));
        $agent_reply_data = fread($this->fsock, $agent_reply_bytes);
        if (strlen($agent_reply_data) != $agent_reply_bytes) {
            user_error('Connection closed while reading data response');
            return false;
        }
        $agent_reply_data = current(unpack('a*', $agent_reply_data));
        return pack('Na*', $agent_reply_bytes, $agent_reply_data);
    }
_on_channel_open()
_on_channel_open ($ssh)
On successful channel open.
This method is called upon successful channel open to give the SSH Agent an opportunity to take further action. i.e. request agent forwarding
Parameters
Net_SSH2 $ssh @access private
Definition at line 562 of file Agent.php.
    {
        if ($this->forward_status == SYSTEM_SSH_AGENT_FORWARD_REQUEST) {
            $this->_request_forwarding($ssh);
        }
    }
References _request_forwarding(), and SYSTEM_SSH_AGENT_FORWARD_REQUEST.
_request_forwarding()
_request_forwarding ($ssh)
Request agent forwarding of remote server.
Parameters
Net_SSH2 $ssh
Returns
bool @access private
Definition at line 519 of file Agent.php.
    {
        $request_channel = $ssh->_get_open_channel();
        if ($request_channel === false) {
            return false;
        }
        $packet = pack(
            'CNNa*C',
            NET_SSH2_MSG_CHANNEL_REQUEST,
            $ssh->server_channels[$request_channel],
            strlen('auth-agent-req@openssh.com'),
            'auth-agent-req@openssh.com',
            1
        );
        $ssh->channel_status[$request_channel] = NET_SSH2_MSG_CHANNEL_REQUEST;
        if (!$ssh->_send_binary_packet($packet)) {
            return false;
        }
        $response = $ssh->_get_channel_packet($request_channel);
        if ($response === false) {
            return false;
        }
        $ssh->channel_status[$request_channel] = NET_SSH2_MSG_CHANNEL_OPEN;
        $this->forward_status = SYSTEM_SSH_AGENT_FORWARD_ACTIVE;
        return true;
    }
References SYSTEM_SSH_AGENT_FORWARD_ACTIVE.
Referenced by _on_channel_open().
requestIdentities()
requestIdentities ()
Request Identities.
See "2.5.2 Requesting a list of protocol 2 keys" Returns an array containing zero or more System_SSH_Agent_Identity objects
Returns
array @access public
Definition at line 410 of file Agent.php.
    {
        global $VIEW_PATH;
        if (!$this->fsock) {
            return array();
        }
        $packet = pack('NC', 1, SYSTEM_SSH_AGENTC_REQUEST_IDENTITIES);
        if (strlen($packet) != fputs($this->fsock, $packet)) {
            user_error('Connection closed while requesting identities');
            return array();
        }
        $temp = fread($this->fsock, 4);
        if (strlen($temp) != 4) {
            user_error('Connection closed while requesting identities');
            return array();
        }
        $length = current(unpack('N', $temp));
        $type = ord(fread($this->fsock, 1));
        if ($type != SYSTEM_SSH_AGENT_IDENTITIES_ANSWER) {
            user_error('Unable to request identities');
            return array();
        }
        $identities = array();
        $temp = fread($this->fsock, 4);
        if (strlen($temp) != 4) {
            user_error('Connection closed while requesting identities');
            return array();
        }
        $keyCount = current(unpack('N', $temp));
        for ($i = 0; $i < $keyCount; $i++) {
            $temp = fread($this->fsock, 4);
            if (strlen($temp) != 4) {
                user_error('Connection closed while requesting identities');
                return array();
            }
            $length = current(unpack('N', $temp));
            $key_blob = fread($this->fsock, $length);
            if (strlen($key_blob) != $length) {
                user_error('Connection closed while requesting identities');
                return array();
            }
            $key_str = 'ssh-rsa ' . base64_encode($key_blob);
            $temp = fread($this->fsock, 4);
            if (strlen($temp) != 4) {
                user_error('Connection closed while requesting identities');
                return array();
            }
            $length = current(unpack('N', $temp));
            if ($length) {
                $temp = fread($this->fsock, $length);
                if (strlen($temp) != $length) {
                    user_error('Connection closed while requesting identities');
                    return array();
                }
                $key_str.= ' ' . $temp;
            }
            $length = current(unpack('N', substr($key_blob, 0, 4)));
            $key_type = substr($key_blob, 4, $length);
            switch ($key_type) {
                case 'ssh-rsa':
                    if (!class_exists('Crypt_RSA')) {
                        include_once $VIEW_PATH.'/lib/phpseclib/Crypt/RSA.php';
                    }
                    $key = new Crypt_RSA();
                    $key->loadKey($key_str);
                    break;
                case 'ssh-dss':
                    // not currently supported
                    break;
            }
            // resources are passed by reference by default
            if (isset($key)) {
                $identity = new System_SSH_Agent_Identity($this->fsock);
                $identity->setPublicKey($key);
                $identity->setPublicKeyBlob($key_blob);
                $identities[] = $identity;
                unset($key);
            }
        }
        return $identities;
    }
References $VIEW_PATH, SYSTEM_SSH_AGENT_IDENTITIES_ANSWER, and SYSTEM_SSH_AGENTC_REQUEST_IDENTITIES.
startSSHForwarding()
startSSHForwarding ($ssh)
Signal that agent forwarding should be requested when a channel is opened.
Parameters
Net_SSH2 $ssh
Returns
bool @access public
Definition at line 505 of file Agent.php.
    {
        if ($this->forward_status == SYSTEM_SSH_AGENT_FORWARD_NONE) {
            $this->forward_status = SYSTEM_SSH_AGENT_FORWARD_REQUEST;
        }
    }
References SYSTEM_SSH_AGENT_FORWARD_NONE, and SYSTEM_SSH_AGENT_FORWARD_REQUEST.
System_SSH_Agent()
System_SSH_Agent ($address = null)
PHP4 compatible Default Constructor.
See also
self::__construct() @access public
Definition at line 396 of file Agent.php.
    {
        $this->__construct($address);
    }
References __construct().
Field Documentation
$expected_bytes
$expected_bytes = 0
Tracking the number of bytes we are expecting to arrive for the agent socket on the SSH data channel.
Definition at line 360 of file Agent.php.
$forward_status
$forward_status = SYSTEM_SSH_AGENT_FORWARD_NONE
Agent forwarding status.
@access private
Definition at line 344 of file Agent.php.
$fsock
$fsock
Definition at line 337 of file Agent.php.
$socket_buffer
$socket_buffer = ''
Buffer for accumulating forwarded authentication agent data arriving on SSH data channel destined for agent unix socket.
@access private
Definition at line 353 of file Agent.php.
The documentation for this class was generated from the following file:
src/View/lib/phpseclib/System/SSH/Agent.php