PF Firewall: FilterBase Class Reference
FilterBase Class Reference
Public Member Functions
display ($ruleNumber, $count)
Processes inputs submitted on the edit page.
dispAction ()
dispSrcDest ()
dispQueue ()
input ()
Processes inputs submitted on the edit page.
inputFilterHead ()
inputFilterOpts ()
inputQueue ()
inputAddIcmpType ($key)
inputAll ()
edit ($ruleNumber, $modified, $testResult, $generateResult, $action)
Prints edit page.
editFilterHead ()
editFilterOpts ()
editDirection ()
editHost ($key, $title, $delName, $addName, $hint, $help=NULL, $size=0, $disabled=FALSE)
editStateFilter ()
editIcmpType ($key, $title, $delName, $addName)
editQueue ()
editTagged ()
editReceivedOn ()
Public Member Functions inherited from State
display ($ruleNumber, $count)
Processes inputs submitted on the edit page.
dispState ()
dispText ($key)
dispBool ($key)
dispOverload ()
dispSourceTrack ()
input ()
Processes inputs submitted on the edit page.
inputState ()
edit ($ruleNumber, $modified, $testResult, $generateResult, $action)
Prints edit page.
editState ()
editIfBinding ()
editOverload ()
editSourceTrack ()
Public Member Functions inherited from Timeout
display ($ruleNumber, $count)
Processes inputs submitted on the edit page.
dispTimeout ()
dispTimeoutOpts ()
input ()
Processes inputs submitted on the edit page.
inputTimeout ()
inputTimeoutOpt ($key, $var, $parent)
edit ($ruleNumber, $modified, $testResult, $generateResult, $action)
Prints edit page.
editTimeout ()
editFragment ()
editInterval ()
editSrcTrack ()
editTcpTimeouts ()
editUdpTimeouts ()
editIcmpTimeouts ()
editOtherTimeouts ()
editAdaptiveTimeouts ()
editTimeoutOpt ($timeout, $key)
Public Member Functions inherited from Rule
__construct ()
setType ()
Sets the type of certain Translation rules.
display ($ruleNumber, $count)
Processes inputs submitted on the edit page.
dispHead ($ruleNumber, $count)
Prints rule number, rule type, and line number.
countLines ()
Returns the number of extra lines.
dispTail ($ruleNumber)
Prints inline comments and edit links.
dispHeadEditLinks ($ruleNumber, $count)
Prints edit links in a cell.
dispEditLinks ($ruleNumber, $count, $up='up', $down='down', $del='del')
Prints e, u, d, and x links.
dispKey ($key, $title)
Displays the given key in a cell if its value is TRUE.
dispValue ($key, $title)
Displays the value(s) of the given key in a cell.
dispValues ($key, $title)
Displays the value(s) of the given host key in a cell.
dispInterface ()
printValue ($value, $pre='', $post='', $count=10)
Prints the given value(s).
dispLog ($colspan=1)
Displays log specification in a cell.
printHostPort ($value, $noAny=TRUE, $count=10)
Prints host or port values.
input ()
Processes inputs submitted on the edit page.
inputKey ($key, $parent=NULL)
Gets the value of the given POST input key.
inputBool ($key, $parent=NULL)
Gets the boolean value of the given POST input key.
inputKeyIfHasVar ($key, $var)
Gets the value of the given POST input key, if another given key exists already.
inputDel ($key, $var, $parent=NULL)
Gets the value of the given GET input var and deletes it from the given key.
inputDelValue ($key, $value, $parent=NULL)
Deletes the given value from the given key.
inputAdd ($key, $var, $parent=NULL)
Gets the value of the given POST input var and adds it to the given key.
inputAddValue ($key, $value, $parent=NULL)
Adds the given value to the given key.
inputInterface ()
Deletes or adds interface definitions.
inputLog ()
Gets the POST input vars of log specifications.
inputDelEmpty ($flatten=TRUE)
Deletes empty values in internal rule structure.
inputDelEmptyRecursive ($array, $flatten)
Recursively deletes empty values in NVP arrays.
edit ($ruleNumber, $modified, $testResult, $generateResult, $action)
Prints edit page.
editCheckbox ($key, $title)
Prints a checkbox for the given key, within a table row.
editText ($key, $title, $help=NULL, $size=0, $hint='')
Prints an edit box for the given key, within a table row.
editValues ($key, $title, $delName, $addName, $hint, $help=NULL, $size=0, $disabled=FALSE)
Prints delete links and input boxes for multi-valued keys, within a table row.
editHead ($modified, $testResult, $generateResult, $action)
Prints rule title, generated rule, and form header at the top of the edit page.
editTail ()
Closes the table and form on the edit page.
editInterface ()
editAf ()
editLog ()
Prints edit controls for log specifications.
editComment ()
Prints input box for inline comments.
editDeleteValueLinks ($value, $name, $prefix='', $postfix='')
Prints delete links for values.
editAddValueBox ($id, $label, $hint, $size=0, $disabled=FALSE)
Prints add input box for values.
editHelp ($label)
Prints help image with a link to an anchor in pf.conf man page.
Additional Inherited Members
Data Fields inherited from Rule
$cat = ''
Category or type of rule.
$rule = array()
Internal structure of rule properties in NVP format.
Protected Attributes inherited from Rule
$ref = ''
Name used in href.
$href = ''
Common part of edit links.
$ruleNumber = 0
Rule number.
$arr = array()
Used by certain rule types while displaying themselves on the list.
$editIndex = 0
Current count of rows on edit pages.
Detailed Description
Definition at line 23 of file FilterBase.php.
Member Function Documentation
dispAction()
dispAction ()
Reimplemented in Anchor.
Definition at line 40 of file FilterBase.php.
    {
        ?>
        <td title="<?php echo _TITLE('Action') ?>" class="<?php echo isset($this->rule['action']) ? $this->rule['action'] : ''; ?>" nowrap="nowrap">
            <?php
            if (isset($this->rule['action'])) {
                echo $this->rule['action'];
            }
            ?>
        </td>
        <?php
    }
display()
display ($ruleNumber, $count)
Processes inputs submitted on the edit page.
All child classes should override this method.
Parameters
int $ruleNumber Rule number.
int $count Number of rules in the ruleset.
Reimplemented from State.
Reimplemented in AfTo, Anchor, DivertPacket, DivertTo, NatBase, Route, and Scrub.
Definition at line 25 of file FilterBase.php.
    {
        $this->dispHead($ruleNumber, $count);
        $this->dispAction();
        $this->dispValue('direction', _TITLE('Direction'));
        $this->dispInterface();
        $this->dispLog();
        $this->dispKey('quick', _TITLE('Quick'));
        $this->dispValue('proto', _TITLE('Proto'));
        $this->dispSrcDest();
        $this->dispValue('state-filter', _TITLE('State'));
        $this->dispQueue();
        $this->dispTail($ruleNumber);
    }
References _TITLE().
dispQueue()
dispQueue ()
Definition at line 99 of file FilterBase.php.
    {
        ?>
        <td title="<?php echo _TITLE('Queue') ?>">
            <?php echo isset($this->rule['queue']) ? (!is_array($this->rule['queue']) ? $this->rule['queue'] : $this->rule['queue'][0] . '<br>' . $this->rule['queue'][1]) : ''; ?>
        </td>
        <?php
    }
dispSrcDest()
dispSrcDest ()
Definition at line 53 of file FilterBase.php.
    {
        if (isset($this->rule['all'])) {
            ?>
            <td title="<?php echo _TITLE('Source->Destination') ?>" colspan="4" class="all">
                all
            </td>
            <?php
        } else {
            ?>
            <td title="<?php echo _TITLE('Source') ?>">
                <?php
                if (isset($this->rule['from'])) {
                    $this->printHostPort($this->rule['from']);
                } elseif (isset($this->rule['fromroute'])) {
                    echo 'route ' . $this->rule['fromroute'];
                }
                ?>
            </td>
            <td title="<?php echo _TITLE('Source Port') ?>">
                <?php
                if (isset($this->rule['fromport'])) {
                    $this->printHostPort($this->rule['fromport']);
                }
                ?>
            </td>
            <td title="<?php echo _TITLE('Destination') ?>">
                <?php
                if (isset($this->rule['to'])) {
                    $this->printHostPort($this->rule['to']);
                } elseif (isset($this->rule['toroute'])) {
                    echo 'route ' . $this->rule['toroute'];
                }
                ?>
            </td>
            <td title="<?php echo _TITLE('Destination Port') ?>">
                <?php
                if (isset($this->rule['toport'])) {
                    $this->printHostPort($this->rule['toport']);
                }
                ?>
            </td>
            <?php
        }
    }
edit()
edit ($ruleNumber, $modified, $testResult, $generateResult, $action)
Prints edit page.
All child classes should override this method.
Parameters
int $ruleNumber Rule number.
bool $modified Whether the rule is modified or not.
bool $testResult Test result.
bool $generateResult Rule generation result.
string $action Current state of the edit page.
Reimplemented from State.
Reimplemented in AfTo, Anchor, DivertPacket, DivertTo, Filter, NatBase, NatTo, Route, and Scrub.
Definition at line 251 of file FilterBase.php.
    {
        $this->editIndex= 0;
        $this->ruleNumber= $ruleNumber;
        $this->editHead($modified, $testResult, $generateResult, $action);
        $this->editFilterHead();
        $this->editFilterOpts();
        $this->editComment();
        $this->editTail();
    }
References $testResult.
editDirection()
editDirection ()
Definition at line 308 of file FilterBase.php.
    {
        ?>
        <tr class="<?php echo ($this->editIndex++ % 2 ? 'evenline' : 'oddline'); ?>">
            <td class="title">
                <?php echo _TITLE('Direction').':' ?>
            </td>
            <td>
                <select id="direction" name="direction">
                    <option value="" label=""></option>
                    <option value="in" label="in" <?php echo (isset($this->rule['direction']) && $this->rule['direction'] == 'in' ? 'selected' : ''); ?>>in</option>
                    <option value="out" label="out" <?php echo (isset($this->rule['direction']) && $this->rule['direction'] == 'out' ? 'selected' : ''); ?>>out</option>
                </select>
                <?php $this->editHelp('direction') ?>
            </td>
        </tr>
        <?php
    }
References _TITLE().
editFilterHead()
editFilterHead ()
Definition at line 265 of file FilterBase.php.
    {
        $this->editDirection();
        $this->editInterface();
        $this->editAf();
        $this->editValues('proto', _TITLE('Protocol'), 'delProto', 'addProto', _CONTROL('protocol'), NULL, 10);
        $this->editCheckbox('all', _TITLE('Match All'));
        $this->editHost('from', _TITLE('Source'), 'delFrom', 'addFrom', _CONTROL('ip, host, table or macro'), 'src-dst', NULL, isset($this->rule['all']));
        $this->editValues('fromport', _TITLE('Source Port'), 'delFromPort', 'addFromPort', _CONTROL('number, name, table or macro'), FALSE, NULL, isset($this->rule['all']));
        $this->editHost('to', _TITLE('Destination'), 'delTo', 'addTo', _CONTROL('ip, host, table or macro'), FALSE, NULL, isset($this->rule['all']));
        $this->editValues('toport', _TITLE('Destination Port'), 'delToPort', 'addToPort', _CONTROL('number, name, table or macro'), FALSE, NULL, isset($this->rule['all']));
        $this->editValues('os', _TITLE('OS'), 'delOs', 'addOs', _CONTROL('os name or macro'));
    }
References _CONTROL(), and _TITLE().
editFilterOpts()
editFilterOpts ()
Definition at line 279 of file FilterBase.php.
    {
        $this->editStateFilter();
        $this->editText('flags', _TITLE('TCP Flags'), NULL, 20, _CONTROL('defaults to S/SA'));
        $this->editQueue();
        $this->editIcmpType('icmp', _TITLE('ICMP Type'), 'delIcmpType', 'addIcmpType');
        $this->editIcmpType('icmp6', _TITLE('ICMP6 Type'), 'delIcmp6Type', 'addIcmp6Type');
        $this->editCheckbox('fragment', _TITLE('Fragment'));
        $this->editCheckbox('allow-opts', _TITLE('Allow Opts'));
        $this->editCheckbox('once', _TITLE('Once'));
        $this->editCheckbox('divert-reply', _TITLE('Divert Reply'));
        $this->editValues('user', _TITLE('User'), 'delUser', 'addUser', _CONTROL('username or userid'));
        $this->editValues('group', _TITLE('Group'), 'delGroup', 'addGroup', _CONTROL('groupname or groupid'));
        $this->editText('label', _TITLE('Label'), NULL, NULL, _CONTROL('string'));
        $this->editTagged();
        $this->editText('tag', _TITLE('Assign Tag'), NULL, NULL, _CONTROL('string'));
        $this->editText('tos', _TITLE('Match TOS'), NULL, NULL, _CONTROL('string or number'));
        $this->editText('set-tos', _TITLE('Enforce TOS'), NULL, NULL, _CONTROL('string or number'));
        $this->editText('prio', _TITLE('Match Priority'), NULL, 10, _CONTROL('number 0-7'));
        $this->editValues('set-prio', _TITLE('Assign Priority'), 'delPrio', 'addPrio', _CONTROL('number 0-7'), NULL, 10);
        $this->editText('set-delay', _TITLE('Delay Packets'), NULL, NULL, _CONTROL('milliseconds'));
        $this->editText('max-pkt-rate', _TITLE('Max Packet Rate'), NULL, 10, _CONTROL('number/seconds'));
        $this->editText('probability', _TITLE('Probability'), NULL, 10, _CONTROL('0-100% or 0-1'));
        $this->editText('rtable', _TITLE('Routing Table'), NULL, 10, _CONTROL('number'));
        $this->editReceivedOn();
    }
References _CONTROL(), and _TITLE().
editHost()
editHost ($key, $title, $delName, $addName, $hint, $help = NULL, $size = 0, $disabled = FALSE)
Definition at line 327 of file FilterBase.php.
    {
        $help= $help === NULL ? $key : $help;
        ?>
        <tr class="<?php echo ($this->editIndex++ % 2 ? 'evenline' : 'oddline'); ?>">
            <td class="title">
                <?php echo $title.':' ?>
            </td>
            <td>
                <?php
                if (isset($this->rule[$key])) {
                    $this->editDeleteValueLinks($this->rule[$key], $delName);
                }
                $this->editAddValueBox($addName, NULL, $hint, $size, $disabled || isset($this->rule[$key . 'route']));
                ?>
                <input type="text" id="<?php echo $key . 'route' ?>" name="<?php echo $key . 'route' ?>" value="<?php echo isset($this->rule[$key . 'route']) ? $this->rule[$key . 'route'] : ''; ?>" size="20" placeholder="<?php echo _CONTROL('label') ?>" <?php echo $disabled || isset($this->rule[$key]) ? 'disabled' : ''; ?> />
                <label for="<?php echo $key . 'route' ?>">route</label>
                <?php
                if ($help !== FALSE) {
                    $this->editHelp($help);
                }
                ?>
            </td>
        </tr>
        <?php
    }
editIcmpType()
editIcmpType ($key, $title, $delName, $addName)
Definition at line 378 of file FilterBase.php.
    {
        $help= $key;
        if (isset($this->rule['proto']) && ($this->rule['proto'] == $key || is_array($this->rule['proto']) && in_array($key, $this->rule['proto']))) {
            ?>
            <tr class="<?php echo ($this->editIndex++ % 2 ? 'evenline' : 'oddline'); ?>">
                <td class="title">
                    <?php echo $title . ':' ?>
                </td>
                <td>
                    <?php
                    if (isset($this->rule[$key . '-type'])) {
                        $this->editDeleteValueLinks($this->rule[$key . '-type'], $delName);
                    }
                    ?>
                    <input type="text" id="<?php echo $key; ?>-type" name="<?php echo $key; ?>-type" placeholder="<?php echo _CONTROL('number or name') ?>" />
                    <label for="<?php echo $key; ?>-type">type</label>
                    <input type="text" id="<?php echo $key; ?>-code" name="<?php echo $key; ?>-code" placeholder="<?php echo _CONTROL('number or name') ?>" />
                    <label for="<?php echo $key; ?>-code">code</label>
                    <?php
                    $this->editHelp($key. '-type');
                    ?>
                </td>
            </tr>
            <?php
        }
    }
editQueue()
editQueue ()
Definition at line 406 of file FilterBase.php.
    {
        global $View;
        $queueNames= $View->RuleSet->getQueueNames();
        ?>
        <tr class="<?php echo ($this->editIndex++ % 2 ? 'evenline' : 'oddline'); ?>">
            <td class="title">
                <?php echo _TITLE('Queue').':' ?>
            </td>
            <td>
                <select id="queuePri" name="queuePri">
                <?php
                if (count($queueNames) == 0) {
                    ?>
                    <option value="" disabled><?php echo _CONTROL('No Queues defined') ?></option>
                    <?php
                } else {
                    ?>
                    <option value=""><?php echo _CONTROL('none') ?></option>
                    <?php
                    $queuePri= '';
                    if (isset($this->rule['queue'])) {
                        if (!is_array($this->rule['queue'])) {
                            $queuePri= $this->rule['queue'];
                        } else {
                            $queuePri= $this->rule['queue'][0];
                        }
                    }
                    foreach ($queueNames as $queue) {
                        ?>
                        <option value="<?php echo $queue; ?>" <?php echo $queuePri == $queue ? 'selected' : ''; ?>><?php echo $queue; ?></option>
                        <?php
                    }
                }
                ?>
                </select>
                <?php echo _TITLE('primary') ?>
                <select id="queueSec" name="queueSec">
                <?php
                if (count($queueNames) == 0) {
                    ?>
                    <option value="" disabled><?php echo _CONTROL('No Queues defined') ?></option>
                    <?php
                } else {
                    ?>
                    <option value=""><?php echo _CONTROL('none') ?></option>
                    <?php
                    if (isset($this->rule['queue'])) {
                        foreach ($queueNames as $queue) {
                            ?>
                            <option value="<?php echo $queue; ?>" <?php echo isset($this->rule['queue'][1]) && $this->rule['queue'][1] == $queue ? 'selected' : ''; ?>><?php echo $queue; ?></option>
                            <?php
                        }
                    }
                }
                ?>
                </select>
                <?php echo _TITLE('secondary') ?>
                <?php $this->editHelp('filter-queue') ?>
            </td>
        </tr>
        <?php
    }
References $View, _CONTROL(), and _TITLE().
editReceivedOn()
editReceivedOn ()
Definition at line 489 of file FilterBase.php.
    {
        ?>
        <tr class="<?php echo ($this->editIndex++ % 2 ? 'evenline' : 'oddline'); ?>">
            <td class="title">
                <?php echo _TITLE('Received on Interface') . ':' ?>
            </td>
            <td>
                <input type="text" id="received-on" name="received-on" value="<?php echo isset($this->rule['received-on']) ? $this->rule['received-on'] : ''; ?>" size="10" placeholder="<?php echo _CONTROL('if or macro') ?>" />
                <?php $this->editHelp('received-on'); ?>
                <input type="checkbox" id="not-received-on" name="not-received-on" value="not-received-on" <?php echo (isset($this->rule['not-received-on']) ? 'checked' : ''); ?> <?php echo (!isset($this->rule['received-on']) ? 'disabled' : ''); ?> />
                <label for="not-received-on"><?php echo _TITLE('negated') ?></label>
            </td>
        </tr>
        <?php
    }
References _TITLE().
editStateFilter()
editStateFilter ()
Definition at line 354 of file FilterBase.php.
    {
        ?>
        <tr class="<?php echo ($this->editIndex++ % 2 ? 'evenline' : 'oddline'); ?>">
            <td class="title">
                <?php echo _TITLE('Stateful Filtering').':' ?>
            </td>
            <td>
                <select id="state-filter" name="state-filter">
                    <option value=""></option>
                    <option value="no" <?php echo (isset($this->rule['state-filter']) && $this->rule['state-filter'] == 'no' ? 'selected' : ''); ?>>No State</option>
                    <option value="keep" <?php echo (isset($this->rule['state-filter']) && $this->rule['state-filter'] == 'keep' ? 'selected' : ''); ?>>Keep State</option>
                    <option value="modulate" <?php echo (isset($this->rule['state-filter']) && $this->rule['state-filter'] == 'modulate' ? 'selected' : ''); ?>>Modulate State</option>
                    <option value="synproxy" <?php echo (isset($this->rule['state-filter']) && $this->rule['state-filter'] == 'synproxy' ? 'selected' : ''); ?>>Synproxy</option>
                </select>
                <?php $this->editHelp('state-filter') ?>
            </td>
        </tr>
        <?php
        if (isset($this->rule['state-filter'])) {
            $this->editState();
        }
    }
References _TITLE().
editTagged()
editTagged ()
Definition at line 472 of file FilterBase.php.
    {
        ?>
        <tr class="<?php echo ($this->editIndex++ % 2 ? 'evenline' : 'oddline'); ?>">
            <td class="title">
                <?php echo _TITLE('Match Tagged') . ':' ?>
            </td>
            <td>
                <input type="text" id="tagged" name="tagged" value="<?php echo isset($this->rule['tagged']) ? $this->rule['tagged'] : ''; ?>" placeholder="<?php echo _CONTROL('string') ?>" />
                <?php $this->editHelp('tagged'); ?>
                <input type="checkbox" id="not-tagged" name="not-tagged" value="not-tagged" <?php echo (isset($this->rule['not-tagged']) ? 'checked' : ''); ?> <?php echo (!isset($this->rule['tagged']) ? 'disabled' : ''); ?> />
                <label for="not-tagged"><?php echo _TITLE('negated') ?></label>
            </td>
        </tr>
        <?php
    }
References _TITLE().
input()
input ()
Processes inputs submitted on the edit page.
All child classes should override this method.
Reimplemented from State.
Reimplemented in AfTo, Anchor, DivertPacket, DivertTo, Filter, NatBase, NatTo, Route, and Scrub.
Definition at line 108 of file FilterBase.php.
    {
        $this->inputFilterHead();
        $this->inputFilterOpts();
        $this->inputKey('comment');
        $this->inputDelEmpty();
    }
inputAddIcmpType()
inputAddIcmpType ($key)
Definition at line 217 of file FilterBase.php.
    {
        if (filter_has_var(INPUT_POST, 'state')) {
            $typeVar= $key . '-type';
            if (filter_has_var(INPUT_POST, $typeVar) && filter_input(INPUT_POST, $typeVar) !== '') {
                $value= filter_input(INPUT_POST, $typeVar);
                $codeVar= $key . '-code';
                if (filter_has_var(INPUT_POST, $codeVar) && filter_input(INPUT_POST, $codeVar) !== '') {
                    $value.= ' code ' . filter_input(INPUT_POST, $codeVar);
                }
                $this->inputAddValue($key . '-type', $value);
            }
        }
    }
inputAll()
inputAll ()
Definition at line 234 of file FilterBase.php.
    {
        if (filter_has_var(INPUT_POST, 'state')) {
            if (filter_has_var(INPUT_POST, 'all')) {
                $this->rule['all']= TRUE;
                unset($this->rule['from']);
                unset($this->rule['fromroute']);
                unset($this->rule['fromport']);
                unset($this->rule['to']);
                unset($this->rule['toroute']);
                unset($this->rule['toport']);
            } else {
                unset($this->rule['all']);
            }
        }
    }
inputFilterHead()
inputFilterHead ()
Attention
Process 'all' after src and dest, because inputAll() unsets src and dest if necessary.
Definition at line 117 of file FilterBase.php.
    {
        $this->inputKey('direction');
        $this->inputInterface();
        $this->inputKey('af');
        $this->inputDel('proto', 'delProto');
        $this->inputAdd('proto', 'addProto');
        $this->inputDel('from', 'delFrom');
        $this->inputAdd('from', 'addFrom');
        if (!isset($this->rule['from'])) {
            $this->inputKey('fromroute');
        }
        $this->inputDel('fromport', 'delFromPort');
        $this->inputAdd('fromport', 'addFromPort');
        $this->inputDel('to', 'delTo');
        $this->inputAdd('to', 'addTo');
        if (!isset($this->rule['to'])) {
            $this->inputKey('toroute');
        }
        $this->inputDel('toport', 'delToPort');
        $this->inputAdd('toport', 'addToPort');
        $this->inputAll();
        $this->inputDel('os', 'delOs');
        $this->inputAdd('os', 'addOs');
    }
inputFilterOpts()
inputFilterOpts ()
Definition at line 155 of file FilterBase.php.
    {
        $this->inputKey('state-filter');
        $this->inputState();
        $this->inputKey('flags');
        $this->inputQueue();
        $this->inputDel('icmp-type', 'delIcmpType');
        $this->inputAddIcmpType('icmp');
        $this->inputDel('icmp6-type', 'delIcmp6Type');
        $this->inputAddIcmpType('icmp6');
        $this->inputBool('fragment');
        $this->inputBool('allow-opts');
        $this->inputBool('once');
        $this->inputBool('divert-reply');
        $this->inputDel('user', 'delUser');
        $this->inputAdd('user', 'addUser');
        $this->inputDel('group', 'delGroup');
        $this->inputAdd('group', 'addGroup');
        $this->inputKey('label');
        $this->inputKey('tag');
        $this->inputKey('tagged');
        $this->inputBool('not-tagged');
        $this->inputKey('tos');
        $this->inputKey('set-tos');
        $this->inputKey('prio');
        $this->inputDel('set-prio', 'delPrio');
        $this->inputAdd('set-prio', 'addPrio');
        $this->inputKey('set-delay');
        $this->inputKey('max-pkt-rate');
        $this->inputKey('probability');
        $this->inputKey('rtable');
        $this->inputKey('received-on');
        $this->inputBool('not-received-on');
    }
inputQueue()
inputQueue ()
Definition at line 201 of file FilterBase.php.
    {
        if (filter_has_var(INPUT_POST, 'state')) {
            if (filter_has_var(INPUT_POST, 'queuePri') && filter_input(INPUT_POST, 'queuePri') !== '' &&
                filter_has_var(INPUT_POST, 'queueSec') && filter_input(INPUT_POST, 'queueSec') !== '') {
                $this->rule['queue']= array();
                $this->rule['queue'][0]= filter_input(INPUT_POST, 'queuePri');
                $this->rule['queue'][1]= filter_input(INPUT_POST, 'queueSec');
            } elseif (filter_has_var(INPUT_POST, 'queuePri') && filter_input(INPUT_POST, 'queuePri') !== '') {
                $this->rule['queue']= filter_input(INPUT_POST, 'queuePri');
            } else {
                unset($this->rule['queue']);
            }
        }
    }
The documentation for this class was generated from the following file:
src/View/pf/lib/FilterBase.php