PF Firewall: Table Class Reference
Table Class Reference
Public Member Functions
display ($ruleNumber, $count)
Processes inputs submitted on the edit page.
dispId ()
dispValues ($key, $title)
Displays the value(s) of the given host key in a cell.
input ()
Processes inputs submitted on the edit page.
edit ($ruleNumber, $modified, $testResult, $generateResult, $action)
Prints edit page.
editFlags ()
editValues ($key, $title, $delName, $addName, $hint, $help=NULL, $size=0, $disabled=FALSE)
Prints delete links and input boxes for multi-valued keys, within a table row.
Public Member Functions inherited from Rule
__construct ()
setType ()
Sets the type of certain Translation rules.
display ($ruleNumber, $count)
Processes inputs submitted on the edit page.
dispHead ($ruleNumber, $count)
Prints rule number, rule type, and line number.
countLines ()
Returns the number of extra lines.
dispTail ($ruleNumber)
Prints inline comments and edit links.
dispHeadEditLinks ($ruleNumber, $count)
Prints edit links in a cell.
dispEditLinks ($ruleNumber, $count, $up='up', $down='down', $del='del')
Prints e, u, d, and x links.
dispKey ($key, $title)
Displays the given key in a cell if its value is TRUE.
dispValue ($key, $title)
Displays the value(s) of the given key in a cell.
dispValues ($key, $title)
Displays the value(s) of the given host key in a cell.
dispInterface ()
printValue ($value, $pre='', $post='', $count=10)
Prints the given value(s).
dispLog ($colspan=1)
Displays log specification in a cell.
printHostPort ($value, $noAny=TRUE, $count=10)
Prints host or port values.
input ()
Processes inputs submitted on the edit page.
inputKey ($key, $parent=NULL)
Gets the value of the given POST input key.
inputBool ($key, $parent=NULL)
Gets the boolean value of the given POST input key.
inputKeyIfHasVar ($key, $var)
Gets the value of the given POST input key, if another given key exists already.
inputDel ($key, $var, $parent=NULL)
Gets the value of the given GET input var and deletes it from the given key.
inputDelValue ($key, $value, $parent=NULL)
Deletes the given value from the given key.
inputAdd ($key, $var, $parent=NULL)
Gets the value of the given POST input var and adds it to the given key.
inputAddValue ($key, $value, $parent=NULL)
Adds the given value to the given key.
inputInterface ()
Deletes or adds interface definitions.
inputLog ()
Gets the POST input vars of log specifications.
inputDelEmpty ($flatten=TRUE)
Deletes empty values in internal rule structure.
inputDelEmptyRecursive ($array, $flatten)
Recursively deletes empty values in NVP arrays.
edit ($ruleNumber, $modified, $testResult, $generateResult, $action)
Prints edit page.
editCheckbox ($key, $title)
Prints a checkbox for the given key, within a table row.
editText ($key, $title, $help=NULL, $size=0, $hint='')
Prints an edit box for the given key, within a table row.
editValues ($key, $title, $delName, $addName, $hint, $help=NULL, $size=0, $disabled=FALSE)
Prints delete links and input boxes for multi-valued keys, within a table row.
editHead ($modified, $testResult, $generateResult, $action)
Prints rule title, generated rule, and form header at the top of the edit page.
editTail ()
Closes the table and form on the edit page.
editInterface ()
editAf ()
editLog ()
Prints edit controls for log specifications.
editComment ()
Prints input box for inline comments.
editDeleteValueLinks ($value, $name, $prefix='', $postfix='')
Prints delete links for values.
editAddValueBox ($id, $label, $hint, $size=0, $disabled=FALSE)
Prints add input box for values.
editHelp ($label)
Prints help image with a link to an anchor in pf.conf man page.
Additional Inherited Members
Data Fields inherited from Rule
$cat = ''
Category or type of rule.
$rule = array()
Internal structure of rule properties in NVP format.
Protected Attributes inherited from Rule
$ref = ''
Name used in href.
$href = ''
Common part of edit links.
$ruleNumber = 0
Rule number.
$arr = array()
Used by certain rule types while displaying themselves on the list.
$editIndex = 0
Current count of rows on edit pages.
Detailed Description
Definition at line 23 of file Table.php.
Member Function Documentation
dispId()
dispId ()
Definition at line 37 of file Table.php.
    {
        ?>
        <td title="Id">
            <?php
            if (isset($this->rule['identifier'])) {
                echo htmlentities($this->rule['identifier']);
            }
            ?>
        </td>
        <?php
    }
display()
display ($ruleNumber, $count)
Processes inputs submitted on the edit page.
All child classes should override this method.
Parameters
int $ruleNumber Rule number.
int $count Number of rules in the ruleset.
Reimplemented from Rule.
Definition at line 25 of file Table.php.
    {
        $this->dispHead($ruleNumber, $count);
        $this->dispId();
        $this->dispKey('const', _TITLE('Flag'));
        $this->dispKey('persist', _TITLE('Flag'));
        $this->dispKey('counters', _TITLE('Flag'));
        // Dummy params
        $this->dispValues('', '');
        $this->dispTail($ruleNumber);
    }
References _TITLE().
dispValues()
dispValues ($key, $title)
Displays the value(s) of the given host key in a cell.
Parameters
string $key Host key to print the value of.
string $title Title of the cell.
Reimplemented from Rule.
Definition at line 50 of file Table.php.
    {
        ?>
        <td title="<?php echo _TITLE('Values') ?>" colspan="8">
            <?php
            if (isset($this->rule['data'])) {
                $this->printValue($this->rule['data']);
            }
            if (isset($this->rule['file'])) {
                $this->printValue($this->rule['file'], 'file "', '"');
            }
            ?>
        </td>
        <?php
    }
edit()
edit ($ruleNumber, $modified, $testResult, $generateResult, $action)
Prints edit page.
All child classes should override this method.
Parameters
int $ruleNumber Rule number.
bool $modified Whether the rule is modified or not.
bool $testResult Test result.
bool $generateResult Rule generation result.
string $action Current state of the edit page.
Reimplemented from Rule.
Definition at line 81 of file Table.php.
    {
        $this->editIndex= 0;
        $this->ruleNumber= $ruleNumber;
        $this->editHead($modified, $testResult, $generateResult, $action);
        $this->editText('identifier', _TITLE('Identifier'), FALSE, NULL, _CONTROL('string'));
        $this->editFlags();
        // Dummy params
        $this->editValues('', '', '', '', '');
        $this->editComment();
        $this->editTail();
    }
References $testResult, _CONTROL(), and _TITLE().
editFlags()
editFlags ()
Definition at line 97 of file Table.php.
    {
        ?>
        <tr class="<?php echo ($this->editIndex++ % 2 ? 'evenline' : 'oddline'); ?>">
            <td class="title">
                <?php echo _TITLE('Flags').':' ?>
            </td>
            <td>
                <input type="checkbox" id="const" name="const" value="const" <?php echo isset($this->rule['const']) ? 'checked' : ''; ?> />
                <label for="const">const</label>
                <?php $this->editHelp('const') ?>
                <br>
                <input type="checkbox" id="persist" name="persist" value="persist" <?php echo isset($this->rule['persist']) ? 'checked' : ''; ?> />
                <label for="persist">persist</label>
                <?php $this->editHelp('persist') ?>
                <br>
                <input type="checkbox" id="counters" name="counters" value="counters" <?php echo isset($this->rule['counters']) ? 'checked' : ''; ?> />
                <label for="counters">counters</label>
                <?php $this->editHelp('counters') ?>
            </td>
        </tr>
        <?php
    }
References _TITLE().
editValues()
editValues ($key, $title, $delName, $addName, $hint, $help = NULL, $size = 0, $disabled = FALSE)
Prints delete links and input boxes for multi-valued keys, within a table row.
Parameters
string $key Id and name of the checkbox.
string $title Title for the key.
string $delName Var name to use in delete links.
string $addName Id of input box.
string $hint Hint text.
string $help Anchor in the html file for the pf.conf(5) man page.
mixed $size Size of the input, int or NULL.
bool $disabled Condition to disable the input
Reimplemented from Rule.
Definition at line 121 of file Table.php.
    {
        ?>
        <tr class="<?php echo ($this->editIndex++ % 2 ? 'evenline' : 'oddline'); ?>">
            <td class="title">
                <?php echo _TITLE('Values').':' ?>
            </td>
            <td>
                <?php
                if (isset($this->rule['data'])) {
                    $this->editDeleteValueLinks($this->rule['data'], 'delValue');
                }
                if (isset($this->rule['file'])) {
                    $this->editDeleteValueLinks($this->rule['file'], 'delFile', 'file "', '"');
                }
                $this->editAddValueBox('addValue', _TITLE('add host or network'), _CONTROL('host or network'), 30);
                echo '<br />';
                $this->editAddValueBox('addFile', _TITLE('add file'), _CONTROL('filename'), 30);
                ?>
            </td>
        </tr>
        <?php
    }
References _CONTROL(), and _TITLE().
input()
input ()
Processes inputs submitted on the edit page.
All child classes should override this method.
Reimplemented from Rule.
Definition at line 66 of file Table.php.
    {
        $this->inputKey('identifier');
        $this->inputBool('const');
        $this->inputBool('persist');
        $this->inputBool('counters');
        $this->inputDel('data', 'delValue');
        $this->inputAdd('data', 'addValue');
        $this->inputDel('file', 'delFile');
        $this->inputAdd('file', 'addFile');
        $this->inputKey('comment');
        $this->inputDelEmpty();
    }
The documentation for this class was generated from the following file:
src/View/pf/lib/Table.php