PF Firewall: Cache Class Reference
Cache Class Reference
Public Member Functions
__construct ()
_load ()
_cache ($filename)
_iscached ($filename)
_get ($filename)
insert (&$content, $extension='')
obtain_filecache ($key)
getfilename ($key)
expire_key ($key)
_expire_all ()
_display ()
_test ()
Data Fields
$db
$timestamp
Detailed Description
Definition at line 53 of file class_cache.inc.
Constructor & Destructor Documentation
__construct()
__construct ()
Definition at line 57 of file class_cache.inc.
{
    global $symon;
    if (!isset($symon["cache_duration"])) {
        config_error("cache_duration", "is not set");
        return 0;
    }
    if (!isset($symon["cache_dir"])) {
        config_error("cache_dir", "is not set");
        return 0;
    }
    if (!is_dir($symon["cache_dir"])) {
        config_error("cache_dir", "does not point to a directory");
        return 0;
    }
    return $this->_load();
    }
References $symon, _load(), and config_error().
Member Function Documentation
_cache()
_cache ($filename)
Definition at line 96 of file class_cache.inc.
{
    global $symon;
    if (preg_match("/^([0-9]+)_([0-9a-f]+)(\.[a-z]+)?$/i",
               $filename, $match)) {
        $this->db[$match[2]] = $filename;
        if (($this->timestamp > $match[1]) &&
        (!isset($symon['cache_keepstale']))) {
        $this->expire_key($match[2]);
        }
    } else {
        runtime_error("'".$filename."' is not a cache file");
        return 0;
    }
    }
References $symon, expire_key(), and runtime_error().
Referenced by _load(), insert(), and obtain_filecache().
_display()
_display ()
Definition at line 215 of file class_cache.inc.
{
    if (is_array($this->db)) {
        foreach($this->db as $key => $value) {
        print "\xa ".$key.'='.$value;
        }
    }
    }
References print.
Referenced by _test().
_expire_all()
_expire_all ()
Definition at line 207 of file class_cache.inc.
{
    if (is_array($this->db)) {
        foreach($this->db as $key => $value) {
        $this->expire_key($key);
        }
    }
    }
References expire_key().
Referenced by _test().
_get()
_get ($filename)
Definition at line 126 of file class_cache.inc.
{
    if (preg_match("/^([0-9]+)_([0-9a-f]+)(\.[a-z]+)?$/i",
               $filename, $match)) {
        if (isset($this->db[$match[2]])) {
        return $this->db[$match[2]];
        }
    } else {
        if (preg_match("/^([0-9a-f]+)(\.[a-z]+)?$/i",
               $filename, $match)) {
        if (isset($this->db[$match[1]])) {
            return $this->db[$match[1]];
        }
        } else {
        if (isset($this->db[$filename])) {
            return $this->db[$filename];
        }
        }
    }
    return undef;
    }
Referenced by getfilename().
_iscached()
_iscached ($filename)
Definition at line 112 of file class_cache.inc.
{
    if (preg_match("/^([0-9]+)_([0-9a-f]+)(\.[a-z]+)?$/i",
               $filename, $match)) {
        return isset($this->db[$match[2]]);
    } else {
        if (preg_match("/^([0-9a-f]+)(\.[a-z]+)?$/i",
               $filename, $match)) {
        return isset($this->db[$match[1]]);
        } else {
        return isset($this->db[$filename]);
        }
    }
    }
Referenced by getfilename(), insert(), and obtain_filecache().
_load()
_load ()
Definition at line 76 of file class_cache.inc.
                     {
    global $symon;
    $ts = time();
    $this->timestamp = $ts - ($ts % $symon["cache_duration"]);
    $dir = dir($symon["cache_dir"]);
    while ($file = $dir->read()) {
        if ($file == '.' || $file == '..') {
        continue;
        }
        if (!is_file($symon["cache_dir"].'/'.$file)) {
        runtime_error("'".$file."' is not a cache file");
        return 0;
        }
        $this->_cache($file);
    }
    }
References $symon, _cache(), and runtime_error().
Referenced by __construct().
_test()
_test ()
Definition at line 223 of file class_cache.inc.
                     {
    $r1 = 'this is recipe 1';
    $r2 = 'this is recipe 2';
    print "\xa display current cache";
    $this->_display();
    print "\xa flushing cache";
    $this->_expire_all();
    print "\xa insert tests 1 2 3";
    $c1 = $this->insert($r1);
    $c2 = $this->insert($r1, '.txt');
    $c3 = $this->insert($r2);
    print "\xa display current cache\xa";
    $this->_display();
    print "\xa flushing cache";
    $this->_expire_all();
    }
References _display(), _expire_all(), insert(), and print.
expire_key()
expire_key ($key)
Definition at line 194 of file class_cache.inc.
{
    global $runtime_args;
    $filename = $this->getfilename($key);
    if (is_file($filename)) {
        if (!unlink($filename)) {
        runtime_error("'".$filename."' cannot be deleted");
        }
    }
    unset($this->db[$key]);
    }
References getfilename(), and runtime_error().
Referenced by _cache(), and _expire_all().
getfilename()
getfilename ($key)
Definition at line 183 of file class_cache.inc.
{
    global $symon;
    if ($this->_iscached($key)) {
        $filename = $this->_get($key);
        return $symon["cache_dir"].'/'.$filename;
    } else {
        return '';
    }
    }
References $symon, _get(), and _iscached().
Referenced by expire_key(), insert(), and obtain_filecache().
insert()
insert (& $content, $extension = '')
Definition at line 148 of file class_cache.inc.
                                                { /* variadric */
    $args = '';
    $maxargs = func_num_args();
    $arg_list = func_get_args();
    for ($i = 0; $i < $maxargs; $i++) {
        if (is_array($arg_list[$i])) {
        $args .= join($arg_list[$i]);
        } elseif (is_scalar($arg_list[$i])) {
        $args .= $arg_list[$i];
        } else {
        runtime_error('cache: wrong type of argument '.gettype($arg_list[$i]) .' in "insert"');
        }
    }
    $key = md5($args);
    if (!$this->_iscached($key)) {
        $this->_cache($this->timestamp . '_' . $key . $extension);
        $filename = $this->getfilename($key);
        if (strlen($content) > 0) {
        save($filename, $content);
        }
    }
    return $key;
    }
References $args, _cache(), _iscached(), getfilename(), runtime_error(), and save().
Referenced by _test().
obtain_filecache()
obtain_filecache ($key)
Definition at line 175 of file class_cache.inc.
{
    if (!$this->_iscached($key)) {
        $this->_cache($this->timestamp . '_' . $key);
    }
    return $this->getfilename($key);
    }
References _cache(), _iscached(), and getfilename().
Field Documentation
$db
$db
Definition at line 54 of file class_cache.inc.
$timestamp
$timestamp
Definition at line 55 of file class_cache.inc.
The documentation for this class was generated from the following file:
src/View/symon/class_cache.inc