PF Firewall: Dhcpd Class Reference
Dhcpd Class Reference
Public Member Functions
__construct ()
Start ()
Starts dhcpd with the list of interfaces obtained from rc.conf.local file.
GetIfs ()
Gets the list of dhcpd interfaces from rc.conf.local file.
_getIfs ()
AddIf ($if)
Adds a dhcpd interface to listen.
DelIf ($if)
Deletes a dhcpd interface to listen.
SetIfs ($ifs)
Sets dhcpd interfaces.
GetOption ($option)
Reads the value of the given dhcpd option.
GetRange ()
Reads dhcpd range option.
SetOptions ($dns, $router, $mask, $bc, $lr, $ur)
Sets dhcpd configuration.
SetOption ($option, $value)
Sets the value of the given dhcpd option.
SetRange ($lower, $upper)
Sets dhcpd range option.
SetDhcpdConf ($lanip, $lanmask, $lannet, $lanbc, $lanmin, $lanmax)
Sets dhcpd configuration.
_getModuleInfo ($start)
GetArpTable ($re='', $end=0, $count=0)
Gets arp table.
_getArpTable ($re='', $end=0, $count=0)
GetArpTableLineCount ($re='')
_getArpTableLineCount ($re='')
GetLeases ($re='', $end=0, $count=0)
Gets dhcpd leases.
_getLeases ($re='', $end=0, $count=0)
GetLeasesLineCount ($re='')
_getLeasesLineCount ($re='')
__construct ()
Public Member Functions inherited from Model
__construct ()
IsRunning ($proc='')
Checks if the given process(es) is running.
GetProcList ()
Gets the list of processes running.
SelectProcesses ($psout)
Selects user processes from ps output.
Start ()
Start module process(es).
Stop ()
Stops module process(es)
Pkill ($proc, $args='')
Kills the given process(es).
GetIntIf ()
Get int_if.
_getIntIf ()
GetExtIf ()
Get ext_if.
_getExtIf ()
isWifiIf ($if)
CreateUser ($user, $passwd, $uid)
Creates a system user.
SetPassword ($user, $passwd)
Sets user's password in the system password file.
SetLogLevel ($level)
Sets global log level.
SetHelpBox ($bool)
Enables or disables help boxes.
SetSessionTimeout ($timeout)
Sets session timeout.
SetDefaultLocale ($locale)
Sets default locale.
SetForceHTTPs ($bool)
Enables or disables HTTPs.
SetUseSSH ($bool)
Enables or disables SSH.
SetMaxAnchorNesting ($max)
Sets the max number of nested anchors allowed.
SetPfctlTimeout ($timeout)
Sets pfctl timeout.
SetStatusCheckInterval ($interval)
Sets status check interval.
SetMaxFileSizeToProcess ($size)
Sets max file size to process.
GetReloadRate ()
Gets default reload rate.
_getReloadRate ()
SetReloadRate ($rate)
Sets default reload rate.
RunShellCommand ($cmd)
Runs the given shell command and returns its output as string.
GetFiles ($filepath)
Returns files with the given filepath pattern.
GetFile ($file)
Reads file contents.
DeleteFile ($path)
Deletes the given file or directory.
PutFile ($file, $contents)
Writes contents to file.
SetNVP ($file, $name, $newvalue)
Changes value of NVP.
GetNVP ($file, $name, $set=0, $trimchars='')
Reads value of NVP.
SearchFile ($file, $re, $set=0, $trimchars='')
Searches the given file with the given regex.
SearchFileAll ($file, $re, $set=1)
Multi-searches a given file with a given regexp.
ReplaceRegexp ($file, $matchre, $replacere)
Searches a needle and replaces with a value in the given file.
AppendToFile ($file, $line)
Appends a string to a file.
GetDateTime ()
Gets system datetime.
GetPhyIfs ()
Extracts physical interface names from ifconfig output.
_getPhyIfs ()
GetDefaultLogFile ()
Gets the log file of the module.
SelectLogFile ($file)
Gets the log file under the tmp folder.
IsLogFileModified ($logfile)
Checks if the given log file has been updated.
GetTmpLogFileName ($file)
Gets the name of the file in the tmp folder.
UpdateTmpLogFile ($file)
Copies the original log file to tmp folder.
formatDateHourRegexp ($month, $day, $hour, $minute)
Generates the module specific datetime regexp for filtering logs.
formatDateHourRegexpDayLeadingZero ($month, $day, $hour, $minute)
formatDateHourRegexpWeekDays ($month, $day, $hour, $minute)
GetFileLineCount ($file, $re='', $needle='', $month='', $day='', $hour='', $minute='')
Gets line count of the given log file.
_getFileLineCount ($file, $re='', $needle='', $month='', $day='', $hour='', $minute='')
GetLogs ($file, $end, $count, $re='', $needle='', $month='', $day='', $hour='', $minute='')
Gets lines in log file.
GetLiveLogs ($file, $count, $re='')
Gets logs for live logs pages.
_getLiveLogs ($file, $count, $re='', $needle='', $reportFileExistResult=TRUE)
Gets logs for live logs pages, the actual method.
GetLastLogs ($file, $count)
GetLogFilesList ()
Gets log files list with start dates.
GetLogStartDate ($file)
Extracts the datetime of the first line in the log file.
_getLogStartDate ($file)
GetFileFirstLine ($file)
Gets first line of file.
ParseLogLine ($logline, &$cols)
Parses the given log line.
PostProcessCols (&$cols)
Further processes parser output fields.
PrepareFileForDownload ($file)
Prepares file for download over WUI.
GetOrigFileName ($logfile)
Gets the original file name for the given log file.
GetProcStatLines ($logfile)
Collects text statistics for the proc stats general page.
CopyLogFileToTmp ($file, $tmpdir)
Uncompresses gzipped log file to tmp dir.
GetStatsLogLines ($logfile, $tail=-1)
Builds generic grep command and extracts log lines.
GetAllStats ($logfile, $collecthours='')
Gets both brief and full statistics.
GetStats ($logfile, $date, $collecthours='')
Main statistics collector, as module data set.
_getStats ($logfile, $date, $collecthours='')
ValidateFile ($file, $reportFileExistResult=TRUE)
Checks if the given file exists and not larger than $MaxFileSizeToProcess in MBs.
ValidateFileExists ($file, $reportFileExistResult=TRUE)
CountDiffLogLines ($logfile, &$count)
Gets the number of lines added to log files since last tmp file update.
UpdateStats ($logfile, &$stats, &$briefstats)
Updates statistics incrementally, both brief and full.
GetDateRegexp ($date)
Generates date regexp to be used by statistics functions.
GetHourRegexp ($date)
Generates hour regexp to be used by statistics functions.
GetSavedStats ($logfile, &$stats, &$briefstats)
Gets saved statistics for the given log file.
GetStatsFileInfo ($logfile, &$linecount, &$filestat)
Gets previous line count and stat() from statistics file.
GetStatsFileName ($logfile)
Gets name of the tmp statistics file for the given log file.
SaveStats ($logfile, $stats, $briefstats, $linecount)
Saves collected statistics with the current line count and stat() output.
CollectDayStats ($statsdefs, $values, $line, &$stats)
Day statistics collector.
CollectHourStats ($statsdefs, $hour, $min, $values, $line, &$daystats)
Hour statistics collector.
IncStats ($line, $values, $statsdefs, &$stats)
Increments stats for the given values.
CollectMinuteStats ($statsdefs, $min, $values, $line, &$hourstats)
Minute statistics collector.
GetConfigValues ($conf, $group)
Gets all configuration for a given configuration type.
GetValue ($name, $conf, $group)
Returns all enabled configuration for a given configuration type.
GetDisabledValue ($name, $conf, $group)
Returns all disabled configuration for a given configuration type.
getValidValues ($name)
GetDisabledNVP ($file, $name, $set=0, $trimchars='')
Reads value of commented-out NVP.
GetName ($file, $name)
Checks if Name exists.
GetDisabledName ($file, $name)
Checks if commented-out Name exists.
SetConfValue ($name, $newvalue, $conf, $group)
Sets the value of NVP configuration.
GetConfValueType ($name)
EnableConf ($name, $conf, $group)
Enables a configuration item in conf file.
DisableConf ($name, $conf, $group)
Disables a configuration item in conf file.
EnableNVP ($file, $name, $type)
Enables an NVP configuration item with value.
EnableName ($file, $name)
Enables a Name: configuration item without value.
DisableNVP ($file, $name, $type)
Disables an NVP.
DisableName ($file, $name)
Disables a Name.
GetConfFile ($conf, $group)
Returns configuration file of the module.
SetConfig ($confname)
Sets configuration file based on config type provided.
Kill ()
Stops module's parent process with its pid.
KillPid ($pid)
Kills process with the given pid.
IsModulePidRunning ($pid)
Checks if the pid is running.
GetVersion ()
Gets software version string.
GetServiceStatus ($get_info=0, $start='10min', $interval_changed=0)
Gets service statuses.
getCachedContents ($filename, &$contents)
GetModuleStatus ($generate_status)
_getModuleStatus ($start, $generate_status, $do_cache=1)
_getModuleInfo ($start)
getFifoLogs ($interval=60)
getRrdValue ($rrd, $start=60, &$result, $type='derive')
getRrdfetchResolution ($output)
GetStatus ()
isPrio ($log, $prio)
GetSysCtl ($option)
Gets sysctl output for the given arg.
_getSysCtl ($option)
ParseSyslogLine ($logline, &$cols)
Parses standard syslog line.
GetNewsyslogConfig ($model)
Gets newsyslog configuration for log file.
SetNewsyslogConfig ($file, $count, $size, $when)
Sets newsyslog configuration for log file.
_getPartitions ()
Returns all partitions mounted.
GetSensors ()
Finds sysctl temp and fan sensors.
Public Member Functions inherited from View
Controller (&$output)
Calls the controller.
CheckAuthentication ($user, $passwd)
Checks the given user:password pair by testing login.
Restart ()
Stops and restarts module process(es).
Stop ()
Stops module process(es).
Start ()
Starts module process(es).
ProcessStartStopRequests ()
Processes user posts for process start and stop.
PrintStatusForm ($generate_status=0, $printcount=FALSE, $showbuttons=TRUE, $printprocs=TRUE, $showrestartbutton=FALSE)
Displays module status, software version, Restart/Stop buttons, and process table.
PrintProcessTable ($output, $printcount=FALSE)
Gets and lists processes for daemons/services.
PrintProcessTableHeader ()
Prints headers for processes table.
UploadLogFile ()
Uploads selected log file.
PrintStats ($file='')
Prints general text statistics.
IsDateRange ($date)
Checks if the date array contains a range, meaning an empty string.
FormatDate ($date)
Generic date array to string formatter.
FormatDateArray ($datestr, &$date)
Date string to array formatter.
PrintLogLine ($cols, $linenum, $lastlinenum)
Generic parser, highlighter, and printer for the log line.
getLogLineClass ($cols)
Determines log line color class.
FormatLogCols (&$cols)
Post-processes log columns for display.
SetSessionConfOpt ()
Static Public Member Functions
static DisplayDashboardExtras ()
Data Fields
$Name = 'dhcpd'
$User = '_dhcp'
$ConfFile = '/etc/dhcpd.conf'
$LogFile = '/var/log/dhcpd.log'
$Model = 'dhcpd'
$Layout = 'dhcpd'
Data Fields inherited from Model
$Nesting = 0
Keeps the count of nested anchors in inline rules.
$Name = ''
$Proc = ''
$User = ''
$StartCmd = ''
const PROC_STAT_TIMEOUT = 30
Max number of iterations to try while starting or stopping processes.
const PROC_STAT_SLEEP_TIME = 1
$Commands = array()
Argument lists and descriptions of commands.
$NVPS = '='
$COMC = '#'
$LogFile = ''
$TmpLogsDir = ''
$PfRulesFile = '/etc/pf.conf'
$ConfFile = ''
$Config = ''
$ReloadCmd = ''
$CmdLogStart = '/usr/bin/head -1 <LF>'
$VersionCmd = ''
$PidFile = ''
Data Fields inherited from View
$Model = 'model'
$Module = 'model'
$Caption = 'Model'
$LogsHelpMsg = ''
$GraphHelpMsg = ''
$ConfHelpMsg = ''
$Layout = ''
$LogsPage = 'logs.php'
$StatsPage = 'stats.php'
$Config = array()
Configuration.
Additional Inherited Members
Protected Attributes inherited from Model
$psCmd = '/bin/ps arwwx -o pid,start,%cpu,time,%mem,rss,vsz,stat,pri,nice,tty,user,group,command | /usr/bin/grep -v -e grep | /usr/bin/grep -E <PROC>'
$rcConfLocal = '/etc/rc.conf.local'
$PFFWDIR = PFFWDIR
Makes the PFFWDIR define easier to use in functions, without adding a global var.
$CollectdName = ''
Used in collectd rrd and fifo file names.
$CollectdRrdFolder = PFFWDIR.'/collectd/rrd/localhost'
$CollectdFifoFolder = PFFWDIR.'/collectd/fifo'
$newSyslogConf = '/etc/newsyslog.conf'
$dateTimeFormat = 'M j H:i:s'
This datetime format is for error logs, not access logs.
Detailed Description
Definition at line 23 of file dhcpd.php.
Constructor & Destructor Documentation
__construct() [1/2]
__construct ()
Reimplemented from Model.
Definition at line 35 of file dhcpd.php.
    {
        parent::__construct();
        $this->Commands= array_merge(
            $this->Commands,
            array(
                'GetIfs'    => array(
                    'argv'  => array(),
                    'desc'  => _('Get DHCP interfaces'),
                    ),
                'GetOption' => array(
                    'argv'  => array(NAME),
                    'desc'  => _('Get DHCP option'),
                    ),
                'GetRange'  =>  array(
                    'argv'  => array(),
                    'desc'  => _('Get DHCP IP range'),
                    ),
                'AddIf' =>  array(
                    'argv'  => array(NAME),
                    'desc'  => _('Add DHCP interface'),
                    ),
                'DelIf' =>  array(
                    'argv'  => array(NAME),
                    'desc'  => _('Delete DHCP interface'),
                    ),
                'GetArpTable'   =>  array(
                    'argv'  => array(REGEXP|NONE, NUM|NONE, TAIL|NONE),
                    'desc'  => _('Get arp table'),
                    ),
                'GetArpTableLineCount'  =>  array(
                    'argv'  => array(REGEXP|NONE),
                    'desc'  => _('Get arp table size'),
                    ),
                'GetLeases' =>  array(
                    'argv'  => array(REGEXP|NONE, NUM|NONE, TAIL|NONE),
                    'desc'  => _('Get dhcp leases'),
                    ),
                'GetLeasesLineCount'    =>  array(
                    'argv'  => array(REGEXP|NONE),
                    'desc'  => _('Get dhcp leases count'),
                    ),
                'SetOptions'=>  array(
                    'argv'  => array(IPADR, IPADR, IPADR, IPADR, IPADR, IPADR),
                    'desc'  => _('Set configuration'),
                    ),
                'SetDhcpdConf'  =>  array(
                    'argv'  => array(IPADR, IPADR, IPADR, IPADR, IPADR, IPADR),
                    'desc'  => _('Set dhcpd conf'),
                    ),
                )
            );
    }
References IPADR, NAME, NONE, NUM, REGEXP, and TAIL.
__construct() [2/2]
__construct ()
Reimplemented from Model.
Definition at line 85 of file include.php.
    {
        $this->Module= basename(dirname($_SERVER['PHP_SELF']));
        $this->Caption= _TITLE('DHCP Server');
        $this->LogsHelpMsg= _HELPWINDOW('DHCP server logs the details of communications with DHCP clients.');
    }
References _HELPWINDOW(), _TITLE(), and Caption.
Member Function Documentation
_getArpTable()
_getArpTable ($re = '', $end = 0, $count = 0)
Attention
Delete the table header: Host Ethernet Address Netif Expire Flags
Definition at line 305 of file dhcpd.php.
    {
        global $preIP, $preMac, $preIfName;
        $cmd= '/usr/sbin/arp -an | /usr/bin/grep -v Host';
        if ($re != '') {
            $cmd.= " | /usr/bin/grep -a -E $re";
        }
        if ($end != 0) {
            $cmd.= " | /usr/bin/head -$end";
        }
        if ($count != 0) {
            $cmd.= " | /usr/bin/tail -$count";
        }
        $lines= $this->RunShellCommand($cmd);
        //Host                                 Ethernet Address   Netif Expire     Flags
        //192.168.0.1                          00:0c:29:a2:8c:56    em1 permanent  l
        //192.168.0.3                          00:0c:29:d3:9b:50    em1 14m40s
        $re_arp= "/^($preIP)\s+($preMac)\s+($preIfName)\s+(\S+).*$/m";
        $logs= array();
        if (preg_match_all($re_arp, $lines, $match, PREG_SET_ORDER)) {
            foreach ($match as $fields) {
                $cols['IP']= $fields[1];
                $cols['MAC']= $fields[6];
                $cols['Interface']= $fields[7];
                $cols['Expire']= $fields[8];
                $logs[]= $cols;
            }
        }
        return $logs;
    }
References $preIfName, $preIP, $preMac, and Model\RunShellCommand().
Referenced by _getArpTableLineCount(), and GetArpTable().
_getArpTableLineCount()
_getArpTableLineCount ($re = '')
Definition at line 346 of file dhcpd.php.
    {
        return count($this->_getArpTable($re));
    }
References _getArpTable().
Referenced by _getModuleInfo(), and GetArpTableLineCount().
_getIfs()
_getIfs ()
Definition at line 127 of file dhcpd.php.
    {
        $ifs= $this->SearchFile($this->rcConfLocal, '/^\h*#*\h*dhcpd_flags\h*=\h*("[^#"]*"|)(\h*|\h*#.*)$/m', 0, '"');
        if ($ifs !== FALSE) {
            return implode("\n", preg_split('/\h+/', $ifs));
        }
        return FALSE;
    }
References $ifs, and Model\SearchFile().
Referenced by AddIf(), DelIf(), GetIfs(), and Start().
_getLeases()
_getLeases ($re = '', $end = 0, $count = 0)
Attention
Empty $re matches all
Definition at line 363 of file dhcpd.php.
    {
        global $Re_Ip;
        //lease 192.168.9.3 {
        //        starts 1 2017/10/30 16:32:46 UTC;
        //        ends 2 2017/10/31 04:32:46 UTC;
        //        hardware ethernet 08:62:66:b9:b4:c5;
        //        client-hostname "soner";
        //}
        //lease 192.168.9.2 {
        //        starts 1 2017/10/30 15:03:45 UTC;
        //        ends 2 2017/10/31 03:03:45 UTC;
        //
        //        abandoned;
        //        client-hostname "soner";
        //}
        $re_starts= '\s*starts\s+(\d+)\s+(\d+\/\d+\/\d+)\s+(\d+:\d+:\d+\s+\w*)\s*';
        $re_ends= '\s*ends\s+(\d+)\s+(\d+\/\d+\/\d+)\s+(\d+:\d+:\d+\s+\w*)\s*';
        $re_mac= '\s*hardware\s+\w+\s+(\w+:\w+:\w+:\w+:\w+:\w+)\s*';
        $re_uid= '\s*uid\s+(.+)\s*';
        $re_host= '\s*(client-hostname|hostname)\s+"(.+)"\s*';
        $re_status= '\s*(\S+)\s*';
        $re_lease= "/lease\s+($Re_Ip)\s*\{($re_starts;|)($re_ends;|)($re_mac;|)($re_uid;|)($re_status;|)($re_host;|)\s*\}/m";
        $lines= $this->GetFile($this->leasesFile);
        $logs= array();
        if (preg_match_all($re_lease, $lines, $match, PREG_SET_ORDER)) {
            $start= $end - $count;
            $line= 0;
            $lineCount= 0;
            foreach ($match as $fields) {
                $cols['IP']= $fields[1];
                $cols['Start']= "$fields[4] $fields[5]";
                $cols['End']= "$fields[8] $fields[9]";
                $cols['MAC']= $fields[11];
                $cols['Status']= isset($fields[15]) ? $fields[15] : '';
                $cols['Host']= isset($fields[18]) ? $fields[18] : '';
                if (preg_match('/'.Escape($re, '/').'/m', $fields[0]) && (($end == 0 && $count == 0) || ($line >= $start && $lineCount < $count))) {
                    $logs[]= $cols;
                    $lineCount++;
                    if ($count > 0 && $lineCount >= $count) {
                        break;
                    }
                }
                $line++;
            }
        }
        return $logs;
    }
References $Re_Ip, Escape(), and Model\GetFile().
Referenced by _getLeasesLineCount(), and GetLeases().
_getLeasesLineCount()
_getLeasesLineCount ($re = '')
Definition at line 424 of file dhcpd.php.
    {
        return count($this->_getLeases($re));
    }
References _getLeases().
Referenced by _getModuleInfo(), and GetLeasesLineCount().
_getModuleInfo()
_getModuleInfo ($start)
Reimplemented from Model.
Definition at line 285 of file dhcpd.php.
    {
        return array(
            'leases'    =>  $this->_getLeasesLineCount(),
            'hosts'     =>  $this->_getArpTableLineCount(),
            );
    }
References _getArpTableLineCount(), and _getLeasesLineCount().
AddIf()
AddIf ($if)
Adds a dhcpd interface to listen.
Parameters
string $if Interface to add.
Returns
bool TRUE on success, FALSE on fail.
Definition at line 142 of file dhcpd.php.
    {
        // Clean up any duplicates first
        $this->DelIf($if);
        if (($ifs= $this->_getIfs()) !== FALSE) {
            $ifs= explode("\n", $ifs);
            $ifs= trim(implode(' ', $ifs)." $if");
            return $this->SetIfs($ifs);
        }
        return FALSE;
    }
References $ifs, _getIfs(), DelIf(), and SetIfs().
DelIf()
DelIf ($if)
Deletes a dhcpd interface to listen.
Parameters
string $if Interface to delete.
Returns
bool TRUE on success, FALSE on fail.
Definition at line 160 of file dhcpd.php.
    {
        if (($ifs= $this->_getIfs()) !== FALSE) {
            $ifs= explode("\n", $ifs);
            // Don't use: unset($ifs[array_search($if, $ifs)]), check strictly
            if (($key= array_search($if, $ifs)) !== FALSE) {
                unset($ifs[$key]);
                $ifs= implode(' ', $ifs);
                return $this->SetIfs($ifs);
            }
        }
        return FALSE;
    }
References $ifs, _getIfs(), and SetIfs().
Referenced by AddIf().
DisplayDashboardExtras()
static DisplayDashboardExtras () static
Definition at line 92 of file include.php.
    {
        global $ServiceInfo;
        ?>
        <tr>
            <td colspan="4">
                <a class="transparent" href="/dhcpd/graphs.php"><img src="/system/dashboard/dhcpd.png" name="dhcpd" alt="dhcpd" title="<?php echo _TITLE2('CPU load of the DHCP Server') ?>"></a>
            </td>
        </tr>
        <tr>
            <td colspan="4">
                <table>
                    <tr id="dashboard">
                        <td class="halfcountleft" title="<?php echo _TITLE2('Number of leases assigned to clients by the DHCP Server') ?>">
                            <a class="transparent-white" href="/dhcpd/info.php?submenu=dhcpd">
                            <div class="halfcount" style="background-color: blue">
                                <table>
                                    <tr>
                                        <td class="count">
                                        <?php echo $ServiceInfo['dhcpd']['leases'] ?>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="prio">
                                        <?php echo _TITLE('LEASES') ?>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                            </a>
                        </td>
                        <td class="halfcountright" title="<?php echo _TITLE2('Number of hosts on the system ARP table') ?>">
                            <a class="transparent-white" href="/dhcpd/info.php?submenu=arptable">
                            <div class="halfcount" style="background-color: #490067">
                                <table>
                                    <tr>
                                        <td class="count">
                                        <?php echo $ServiceInfo['dhcpd']['hosts'] ?>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="prio">
                                        <?php echo _TITLE('HOSTS') ?>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                            </a>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
        <?php
    }
References _TITLE().
GetArpTable()
GetArpTable ($re = '', $end = 0, $count = 0)
Gets arp table.
Gets and parses the output of the arp command.
Returns
array Arp table.
Definition at line 300 of file dhcpd.php.
    {
        return Output(json_encode($this->_getArpTable($re, $end, $count)));
    }
References _getArpTable(), and Output().
GetArpTableLineCount()
GetArpTableLineCount ($re = '')
Definition at line 341 of file dhcpd.php.
    {
        return Output($this->_getArpTableLineCount($re));
    }
References _getArpTableLineCount(), and Output().
GetIfs()
GetIfs ()
Gets the list of dhcpd interfaces from rc.conf.local file.
Returns
string List of interfaces.
Definition at line 122 of file dhcpd.php.
    {
        return Output($this->_getIfs());
    }
References _getIfs(), and Output().
GetLeases()
GetLeases ($re = '', $end = 0, $count = 0)
Gets dhcpd leases.
Gets and parses the leases file.
Returns
array IP leases.
Definition at line 358 of file dhcpd.php.
    {
        return Output(json_encode($this->_getLeases($re, $end, $count)));
    }
References _getLeases(), and Output().
GetLeasesLineCount()
GetLeasesLineCount ($re = '')
Definition at line 419 of file dhcpd.php.
    {
        return Output($this->_getLeasesLineCount($re));
    }
References _getLeasesLineCount(), and Output().
GetOption()
GetOption ($option)
Reads the value of the given dhcpd option.
DHCP server options are usually IPs. Range is read by GetRange().
Parameters
string $option Option name to get the value of.
Returns
string Option value.
Definition at line 194 of file dhcpd.php.
    {
        return Output($this->SearchFile($this->ConfFile, "/^\h*option\h*$option\h*([^#;]*)\h*\;\h*$/m"));
    }
References Output(), and Model\SearchFile().
GetRange()
GetRange ()
Reads dhcpd range option.
Returns
string IP range or FALSE on failure.
Definition at line 204 of file dhcpd.php.
    {
        global $Re_Ip;
        $re= "/^\h*range\h*(($Re_Ip)\h*($Re_Ip))\h*\;\h*$/m";
        if (($output= $this->SearchFile($this->ConfFile, $re)) !== FALSE) {
            return Output(preg_replace("/\s+/", "\n", $output));
        }
        return FALSE;
    }
References $Re_Ip, Output(), and Model\SearchFile().
SetDhcpdConf()
SetDhcpdConf ($lanip, $lanmask, $lannet, $lanbc, $lanmin, $lanmax)
Sets dhcpd configuration.
Parameters
string $lanip IP address.
string $lanmask Address netmask.
string $lannet Subnet.
string $lanbc Broadcast address.
string $lanmin Lower limit of IP range.
string $lanmax Upper limit of IP range.
Returns
bool TRUE on success, FALSE on fail.
Definition at line 275 of file dhcpd.php.
    {
        global $Re_Ip;
        $retval=  $this->ReplaceRegexp($this->ConfFile, "/^(\h*subnet\h+)($Re_Ip)(\h+netmask\h+$Re_Ip\h*\{.*)/m", '${1}'.$lannet.'${3}');
        $retval&= $this->ReplaceRegexp($this->ConfFile, "/^(\h*subnet\h+$Re_Ip\h+netmask\h+)($Re_Ip)(\h*\{.*)/m", '${1}'.$lanmask.'${3}');
        $retval&= $this->SetOptions($lanip, $lanip, $lanmask, $lanbc, $lanmin, $lanmax);
        return $retval;
    }
References $Re_Ip, $retval, Model\ReplaceRegexp(), and SetOptions().
SetIfs()
SetIfs ($ifs)
Sets dhcpd interfaces.
Parameters
string $ifs List of ifs separated by spaces.
Returns
bool TRUE on success, FALSE on fail.
Definition at line 181 of file dhcpd.php.
    {
        return $this->ReplaceRegexp($this->rcConfLocal, '/^(\h*#*\h*dhcpd_flags\h*=\h*)("[^#"]*"|)(\h*|\h*#.*)$/m', '${1}"'.$ifs.'"${3}');
    }
References $ifs, and Model\ReplaceRegexp().
Referenced by AddIf(), and DelIf().
SetOption()
SetOption ($option, $value)
Sets the value of the given dhcpd option.
Parameters
string $option Option name to set the value of.
string $value Option value to set.
Returns
bool TRUE on success, FALSE on fail.
Definition at line 243 of file dhcpd.php.
    {
        global $Re_Ip;
        return $this->ReplaceRegexp($this->ConfFile, "/^(\h*option\h*$option\b\h*)($Re_Ip)(\h*\;\h*)$/m", '${1}'.$value.'${3}');
    }
References $Re_Ip, and Model\ReplaceRegexp().
Referenced by SetOptions().
SetOptions()
SetOptions ($dns, $router, $mask, $bc, $lr, $ur)
Sets dhcpd configuration.
Parameters
string $dns DNS server.
string $router Gateway.
string $mask Netmask.
string $bc Broadcast address.
string $lr Lower IP range.
string $ur Upper IP range.
Returns
bool TRUE on success, FALSE on fail.
Definition at line 226 of file dhcpd.php.
    {
        $retval=  $this->SetOption('domain-name-servers', $dns);
        $retval&= $this->SetOption('routers', $router);
        $retval&= $this->SetOption('subnet-mask', $mask);
        $retval&= $this->SetOption('broadcast-address', $bc);
        $retval&= $this->SetRange($lr, $ur);
        return $retval;
    }
References $retval, SetOption(), and SetRange().
Referenced by SetDhcpdConf().
SetRange()
SetRange ($lower, $upper)
Sets dhcpd range option.
Parameters
string $lower Lower limit of IP range.
string $upper Upper limit of IP range.
Returns
bool TRUE on success, FALSE on fail.
Definition at line 257 of file dhcpd.php.
    {
        global $Re_Ip;
        return $this->ReplaceRegexp($this->ConfFile, "/^(\h*range\h*)($Re_Ip)(\h+)($Re_Ip)(\h*\;\h*)$/m", '${1}'.$lower.'${3}'.$upper.'${5}');
    }
References $Re_Ip, and Model\ReplaceRegexp().
Referenced by SetOptions().
Start()
Start ()
Starts dhcpd with the list of interfaces obtained from rc.conf.local file.
Returns
bool TRUE on success, FALSE on fail.
Reimplemented from Model.
Definition at line 105 of file dhcpd.php.
    {
        if (($ifs= $this->_getIfs()) !== FALSE) {
            $ifs= explode("\n", $ifs);
            $ifs= implode(' ', $ifs);
            $this->StartCmd= "/usr/sbin/dhcpd $ifs";
            return parent::Start();
        }
        ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Cannot get dhcpd ifs");
        return FALSE;
    }
References $ifs, _getIfs(), and ctlr_syslog().
Field Documentation
$ConfFile
$ConfFile = '/etc/dhcpd.conf'
Definition at line 31 of file dhcpd.php.
$Layout
$Layout = 'dhcpd'
Definition at line 83 of file include.php.
$LogFile
$LogFile = '/var/log/dhcpd.log'
Definition at line 33 of file dhcpd.php.
$Model
$Model = 'dhcpd'
Definition at line 82 of file include.php.
$Name
$Name = 'dhcpd'
Definition at line 25 of file dhcpd.php.
$User
$User = '_dhcp'
Definition at line 26 of file dhcpd.php.
The documentation for this class was generated from the following files:
src/Model/dhcpd.php
src/View/dhcpd/include.php