PF Firewall: Pf Class Reference
Pf Class Reference
Public Member Functions
__construct ()
SetIfs ($lanif, $wanif)
Sets interface names in pf.conf.
SetIntnet ($net)
Sets int_net.
IsRunning ($proc='')
Checks if pf is enabled or not.
Start ()
Enable pf.
Stop ()
Disable pf.
_getModuleInfo ($start)
RunPfInfoCmd ($cmd)
Runs pfctl info commands.
GetPfInfo ()
Gets general pf info.
_getPfInfo ()
GetPfMemInfo ()
Gets pf memory info.
GetPfTimeoutInfo ()
Gets pf timeouts.
GetPfQueueInfo ()
Gets pf queue info.
parsePfQueueInfo ($lines)
GetPfIfsInfo ()
Gets pf interfaces info.
parsePfIfsInfo ($lines)
GetPfRulesInfo ()
Gets pf rules info.
parsePfRulesInfo ($lines)
getTestRulesCmd ($rulesStr, &$tmpFile)
ParseLogLine ($logline, &$cols)
Parses the given log line.
GetDateRegexp ($date)
Generates date regexp to be used by statistics functions.
_getFileLineCount ($file, $re='', $needle='', $month='', $day='', $hour='', $minute='')
GetLogs ($file, $end, $count, $re='', $needle='', $month='', $day='', $hour='', $minute='')
Gets lines in log file.
formatDateHourRegexp ($month, $day, $hour, $minute)
Generates the module specific datetime regexp for filtering logs.
_getLiveLogs ($file, $count, $re='', $needle='', $reportFileExistResult=TRUE)
Gets logs for live logs pages, the actual method.
GetStateCount ($re='')
Gets pf state count.
_getStateCount ($re='')
GetStateList ($end, $count, $re='')
Gets the pftop output.
ParsePftop ($pftopout)
Parses pftop output.
__construct ()
FormatDate ($date)
Builds PF (tcpdump) specific string from $date.
PrintStatesTable ()
Gets and lists pf states.
PrintStatesTableHeader ()
Prints headers for states table.
Public Member Functions inherited from Model
__construct ()
IsRunning ($proc='')
Checks if the given process(es) is running.
GetProcList ()
Gets the list of processes running.
SelectProcesses ($psout)
Selects user processes from ps output.
Start ()
Start module process(es).
Stop ()
Stops module process(es)
Pkill ($proc, $args='')
Kills the given process(es).
GetIntIf ()
Get int_if.
_getIntIf ()
GetExtIf ()
Get ext_if.
_getExtIf ()
isWifiIf ($if)
CreateUser ($user, $passwd, $uid)
Creates a system user.
SetPassword ($user, $passwd)
Sets user's password in the system password file.
SetLogLevel ($level)
Sets global log level.
SetHelpBox ($bool)
Enables or disables help boxes.
SetSessionTimeout ($timeout)
Sets session timeout.
SetDefaultLocale ($locale)
Sets default locale.
SetForceHTTPs ($bool)
Enables or disables HTTPs.
SetUseSSH ($bool)
Enables or disables SSH.
SetMaxAnchorNesting ($max)
Sets the max number of nested anchors allowed.
SetPfctlTimeout ($timeout)
Sets pfctl timeout.
SetStatusCheckInterval ($interval)
Sets status check interval.
SetMaxFileSizeToProcess ($size)
Sets max file size to process.
GetReloadRate ()
Gets default reload rate.
_getReloadRate ()
SetReloadRate ($rate)
Sets default reload rate.
RunShellCommand ($cmd)
Runs the given shell command and returns its output as string.
GetFiles ($filepath)
Returns files with the given filepath pattern.
GetFile ($file)
Reads file contents.
DeleteFile ($path)
Deletes the given file or directory.
PutFile ($file, $contents)
Writes contents to file.
SetNVP ($file, $name, $newvalue)
Changes value of NVP.
GetNVP ($file, $name, $set=0, $trimchars='')
Reads value of NVP.
SearchFile ($file, $re, $set=0, $trimchars='')
Searches the given file with the given regex.
SearchFileAll ($file, $re, $set=1)
Multi-searches a given file with a given regexp.
ReplaceRegexp ($file, $matchre, $replacere)
Searches a needle and replaces with a value in the given file.
AppendToFile ($file, $line)
Appends a string to a file.
GetDateTime ()
Gets system datetime.
GetPhyIfs ()
Extracts physical interface names from ifconfig output.
_getPhyIfs ()
GetDefaultLogFile ()
Gets the log file of the module.
SelectLogFile ($file)
Gets the log file under the tmp folder.
IsLogFileModified ($logfile)
Checks if the given log file has been updated.
GetTmpLogFileName ($file)
Gets the name of the file in the tmp folder.
UpdateTmpLogFile ($file)
Copies the original log file to tmp folder.
formatDateHourRegexp ($month, $day, $hour, $minute)
Generates the module specific datetime regexp for filtering logs.
formatDateHourRegexpDayLeadingZero ($month, $day, $hour, $minute)
formatDateHourRegexpWeekDays ($month, $day, $hour, $minute)
GetFileLineCount ($file, $re='', $needle='', $month='', $day='', $hour='', $minute='')
Gets line count of the given log file.
_getFileLineCount ($file, $re='', $needle='', $month='', $day='', $hour='', $minute='')
GetLogs ($file, $end, $count, $re='', $needle='', $month='', $day='', $hour='', $minute='')
Gets lines in log file.
GetLiveLogs ($file, $count, $re='')
Gets logs for live logs pages.
_getLiveLogs ($file, $count, $re='', $needle='', $reportFileExistResult=TRUE)
Gets logs for live logs pages, the actual method.
GetLastLogs ($file, $count)
GetLogFilesList ()
Gets log files list with start dates.
GetLogStartDate ($file)
Extracts the datetime of the first line in the log file.
_getLogStartDate ($file)
GetFileFirstLine ($file)
Gets first line of file.
ParseLogLine ($logline, &$cols)
Parses the given log line.
PostProcessCols (&$cols)
Further processes parser output fields.
PrepareFileForDownload ($file)
Prepares file for download over WUI.
GetOrigFileName ($logfile)
Gets the original file name for the given log file.
GetProcStatLines ($logfile)
Collects text statistics for the proc stats general page.
CopyLogFileToTmp ($file, $tmpdir)
Uncompresses gzipped log file to tmp dir.
GetStatsLogLines ($logfile, $tail=-1)
Builds generic grep command and extracts log lines.
GetAllStats ($logfile, $collecthours='')
Gets both brief and full statistics.
GetStats ($logfile, $date, $collecthours='')
Main statistics collector, as module data set.
_getStats ($logfile, $date, $collecthours='')
ValidateFile ($file, $reportFileExistResult=TRUE)
Checks if the given file exists and not larger than $MaxFileSizeToProcess in MBs.
ValidateFileExists ($file, $reportFileExistResult=TRUE)
CountDiffLogLines ($logfile, &$count)
Gets the number of lines added to log files since last tmp file update.
UpdateStats ($logfile, &$stats, &$briefstats)
Updates statistics incrementally, both brief and full.
GetDateRegexp ($date)
Generates date regexp to be used by statistics functions.
GetHourRegexp ($date)
Generates hour regexp to be used by statistics functions.
GetSavedStats ($logfile, &$stats, &$briefstats)
Gets saved statistics for the given log file.
GetStatsFileInfo ($logfile, &$linecount, &$filestat)
Gets previous line count and stat() from statistics file.
GetStatsFileName ($logfile)
Gets name of the tmp statistics file for the given log file.
SaveStats ($logfile, $stats, $briefstats, $linecount)
Saves collected statistics with the current line count and stat() output.
CollectDayStats ($statsdefs, $values, $line, &$stats)
Day statistics collector.
CollectHourStats ($statsdefs, $hour, $min, $values, $line, &$daystats)
Hour statistics collector.
IncStats ($line, $values, $statsdefs, &$stats)
Increments stats for the given values.
CollectMinuteStats ($statsdefs, $min, $values, $line, &$hourstats)
Minute statistics collector.
GetConfigValues ($conf, $group)
Gets all configuration for a given configuration type.
GetValue ($name, $conf, $group)
Returns all enabled configuration for a given configuration type.
GetDisabledValue ($name, $conf, $group)
Returns all disabled configuration for a given configuration type.
getValidValues ($name)
GetDisabledNVP ($file, $name, $set=0, $trimchars='')
Reads value of commented-out NVP.
GetName ($file, $name)
Checks if Name exists.
GetDisabledName ($file, $name)
Checks if commented-out Name exists.
SetConfValue ($name, $newvalue, $conf, $group)
Sets the value of NVP configuration.
GetConfValueType ($name)
EnableConf ($name, $conf, $group)
Enables a configuration item in conf file.
DisableConf ($name, $conf, $group)
Disables a configuration item in conf file.
EnableNVP ($file, $name, $type)
Enables an NVP configuration item with value.
EnableName ($file, $name)
Enables a Name: configuration item without value.
DisableNVP ($file, $name, $type)
Disables an NVP.
DisableName ($file, $name)
Disables a Name.
GetConfFile ($conf, $group)
Returns configuration file of the module.
SetConfig ($confname)
Sets configuration file based on config type provided.
Kill ()
Stops module's parent process with its pid.
KillPid ($pid)
Kills process with the given pid.
IsModulePidRunning ($pid)
Checks if the pid is running.
GetVersion ()
Gets software version string.
GetServiceStatus ($get_info=0, $start='10min', $interval_changed=0)
Gets service statuses.
getCachedContents ($filename, &$contents)
GetModuleStatus ($generate_status)
_getModuleStatus ($start, $generate_status, $do_cache=1)
_getModuleInfo ($start)
getFifoLogs ($interval=60)
getRrdValue ($rrd, $start=60, &$result, $type='derive')
getRrdfetchResolution ($output)
GetStatus ()
isPrio ($log, $prio)
GetSysCtl ($option)
Gets sysctl output for the given arg.
_getSysCtl ($option)
ParseSyslogLine ($logline, &$cols)
Parses standard syslog line.
GetNewsyslogConfig ($model)
Gets newsyslog configuration for log file.
SetNewsyslogConfig ($file, $count, $size, $when)
Sets newsyslog configuration for log file.
_getPartitions ()
Returns all partitions mounted.
GetSensors ()
Finds sysctl temp and fan sensors.
Public Member Functions inherited from View
Controller (&$output)
Calls the controller.
CheckAuthentication ($user, $passwd)
Checks the given user:password pair by testing login.
Restart ()
Stops and restarts module process(es).
Stop ()
Stops module process(es).
Start ()
Starts module process(es).
ProcessStartStopRequests ()
Processes user posts for process start and stop.
PrintStatusForm ($generate_status=0, $printcount=FALSE, $showbuttons=TRUE, $printprocs=TRUE, $showrestartbutton=FALSE)
Displays module status, software version, Restart/Stop buttons, and process table.
PrintProcessTable ($output, $printcount=FALSE)
Gets and lists processes for daemons/services.
PrintProcessTableHeader ()
Prints headers for processes table.
UploadLogFile ()
Uploads selected log file.
PrintStats ($file='')
Prints general text statistics.
IsDateRange ($date)
Checks if the date array contains a range, meaning an empty string.
FormatDate ($date)
Generic date array to string formatter.
FormatDateArray ($datestr, &$date)
Date string to array formatter.
PrintLogLine ($cols, $linenum, $lastlinenum)
Generic parser, highlighter, and printer for the log line.
getLogLineClass ($cols)
Determines log line color class.
FormatLogCols (&$cols)
Post-processes log columns for display.
SetSessionConfOpt ()
Static Public Member Functions
static DisplayDashboardExtras ()
Data Fields
$Name = 'pf'
$LogFile = '/var/log/pflog'
$ConfPath = '/etc/pfre'
$ConfFile = '/etc/pf.conf'
$ReloadCmd = "/sbin/pfctl -f <FILE> 2>&1"
$Model = 'pf'
$RuleSet
Data Fields inherited from Model
$Nesting = 0
Keeps the count of nested anchors in inline rules.
$Name = ''
$Proc = ''
$User = ''
$StartCmd = ''
const PROC_STAT_TIMEOUT = 30
Max number of iterations to try while starting or stopping processes.
const PROC_STAT_SLEEP_TIME = 1
$Commands = array()
Argument lists and descriptions of commands.
$NVPS = '='
$COMC = '#'
$LogFile = ''
$TmpLogsDir = ''
$PfRulesFile = '/etc/pf.conf'
$ConfFile = ''
$Config = ''
$ReloadCmd = ''
$CmdLogStart = '/usr/bin/head -1 <LF>'
$VersionCmd = ''
$PidFile = ''
Data Fields inherited from View
$Model = 'model'
$Module = 'model'
$Caption = 'Model'
$LogsHelpMsg = ''
$GraphHelpMsg = ''
$ConfHelpMsg = ''
$Layout = ''
$LogsPage = 'logs.php'
$StatsPage = 'stats.php'
$Config = array()
Configuration.
Additional Inherited Members
Protected Attributes inherited from Model
$psCmd = '/bin/ps arwwx -o pid,start,%cpu,time,%mem,rss,vsz,stat,pri,nice,tty,user,group,command | /usr/bin/grep -v -e grep | /usr/bin/grep -E <PROC>'
$rcConfLocal = '/etc/rc.conf.local'
$PFFWDIR = PFFWDIR
Makes the PFFWDIR define easier to use in functions, without adding a global var.
$CollectdName = ''
Used in collectd rrd and fifo file names.
$CollectdRrdFolder = PFFWDIR.'/collectd/rrd/localhost'
$CollectdFifoFolder = PFFWDIR.'/collectd/fifo'
$newSyslogConf = '/etc/newsyslog.conf'
$dateTimeFormat = 'M j H:i:s'
This datetime format is for error logs, not access logs.
Detailed Description
Definition at line 29 of file pf.php.
Constructor & Destructor Documentation
__construct() [1/2]
__construct ()
Reimplemented from Model.
Definition at line 48 of file pf.php.
    {
        global $TCPDUMP;
        parent::__construct();
        $this->CmdLogStart= $TCPDUMP.' <LF> | /usr/bin/head -1';
        $this->Commands= array_merge(
            $this->Commands,
            array(
                'SetIfs'=>  array(
                    'argv'  =>  array(NAME, NAME),
                    'desc'  =>  _('Set interfaces'),
                    ),
                'SetIntnet'=>   array(
                    'argv'  =>  array(IPRANGE),
                    'desc'  =>  _('Set internal net'),
                    ),
                'GetPfInfo'=>   array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Get pf info'),
                    ),
                'GetPfTimeoutInfo'=>    array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Get pf timeout info'),
                    ),
                'GetPfMemInfo'=>    array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Get pf memory info'),
                    ),
                'GetPfQueueInfo'=>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Get pf queue info'),
                    ),
                'GetPfRulesInfo'=>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Get pf rules info'),
                    ),
                'GetPfIfsInfo'=>    array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Get pf interface info'),
                    ),
                'GetStateCount' =>  array(
                    'argv'  =>  array(REGEXP|NONE),
                    'desc'  =>  _('Get pf state count'),
                    ),
                'GetStateList'  =>  array(
                    'argv'  =>  array(NUM, TAIL, REGEXP|NONE),
                    'desc'  =>  _('Get pf states'),
                    ),
                )
            );
        $this->registerRulesCommands();
    }
References $TCPDUMP, IPRANGE, NAME, NONE, NUM, REGEXP, and TAIL.
__construct() [2/2]
__construct ()
Reimplemented from Model.
Definition at line 58 of file pf.php.
    {
        $this->Module= basename(dirname($_SERVER['PHP_SELF']));
        $this->Caption= _TITLE('Packet Filter');
        if (!isset($_SESSION['pf']['ruleset'])) {
            $_SESSION['pf']['ruleset']= new RuleSet();
        }
        $this->RuleSet= &$_SESSION['pf']['ruleset'];
        $this->LogsHelpMsg= _HELPWINDOW('What is recorded in packet filter logs is determined by pf rules you can configure under Rules tab.');
    }
References $_SESSION, _HELPWINDOW(), _TITLE(), and Caption.
Member Function Documentation
_getFileLineCount()
_getFileLineCount ($file, $re = '', $needle = '', $month = '', $day = '', $hour = '', $minute = '')
Reimplemented from Model.
Definition at line 542 of file pf.php.
    {
        global $TCPDUMP;
        if (!$this->ValidateFile($file)) {
            return FALSE;
        }
        $cmd= "$TCPDUMP $file";
        if ($month != '' || $day != '' || $hour != '' || $minute != '') {
            $cmd.= ' | /usr/bin/grep -a -E "' . $this->formatDateHourRegexp($month, $day, $hour, $minute) . '"';
        }
        if ($needle != '') {
            $needle= escapeshellarg($needle);
            $cmd.= " | /usr/bin/grep -a -E $needle";
        }
        if ($re !== '') {
            $re= escapeshellarg($re);
            $cmd.= " | /usr/bin/grep -a -E $re";
        }
        $cmd.= ' | /usr/bin/wc -l';
        // OpenBSD wc returns with leading blanks
        return trim($this->RunShellCommand($cmd));
    }
References $TCPDUMP, formatDateHourRegexp(), Model\RunShellCommand(), and Model\ValidateFile().
_getLiveLogs()
_getLiveLogs ($file, $count, $re = '', $needle = '', $reportFileExistResult = TRUE)
Gets logs for live logs pages, the actual method.
A few modules share their log files with other processes. So the $needle param is used to filter module log lines.
Parameters
string $needle Second regexp to further restrict the result set.
Reimplemented from Model.
Definition at line 617 of file pf.php.
    {
        global $TCPDUMP;
        if (!$this->ValidateFile($file, $reportFileExistResult)) {
            return FALSE;
        }
        $cmd= "$TCPDUMP $file";
        if ($re !== '') {
            $re= escapeshellarg($re);
            $cmd.= " | /usr/bin/grep -a -E $re";
        }
        $cmd.= " | /usr/bin/tail -$count";
        $lines= explode("\n", $this->RunShellCommand($cmd));
        $logs= array();
        foreach ($lines as $line) {
            if ($this->ParseLogLine($line, $Cols)) {
                $logs[]= $Cols;
            }
        }
        return $logs;
    }
References $TCPDUMP, ParseLogLine(), Model\RunShellCommand(), and Model\ValidateFile().
_getModuleInfo()
_getModuleInfo ($start)
Todo:
Should we get more status info from pfctl -s info output?
Reimplemented from Model.
Definition at line 189 of file pf.php.
    {
        // For example, the memory counter seems important: 'memory could not be allocated'
        return array('states'   =>  $this->_getStateCount());
    }
References _getStateCount().
_getPfInfo()
_getPfInfo ()
Definition at line 236 of file pf.php.
    {
        exec('/sbin/pfctl -vs info', $output, $retval);
        if ($retval === 0) {
            return $output;
        }
        return FALSE;
    }
References $retval.
Referenced by GetPfInfo().
_getStateCount()
_getStateCount ($re = '')
Todo:
pfctl may take too long to return
Definition at line 655 of file pf.php.
    {
//      if ($re == '') {
//          $ce= exec('/sbin/pfctl -s info | grep "current entries"', $output, $retval);
//          if ($retval === 0) {
//              if (preg_match('/current entries\s+(\d+)/', $ce, $match)) {
//                  return $match[1];
//              }
//          }
//      } else {
            // Skip header lines by grepping for In or Out
            // Empty $re is not an issue for grep, greps all
            $cmd= "$this->pftopCmd | /usr/bin/egrep -a 'In|Out'";
            if ($re !== '') {
                $re= escapeshellarg($re);
                $cmd.= " | /usr/bin/grep -a -E $re";
            }
            $cmd.= ' | /usr/bin/wc -l';
            // OpenBSD wc returns with leading blanks
            return trim($this->RunShellCommand($cmd));
//      }
    }
References Model\RunShellCommand().
Referenced by _getModuleInfo(), and GetStateCount().
DisplayDashboardExtras()
static DisplayDashboardExtras () static
Definition at line 168 of file pf.php.
    {
        global $ServiceInfo;
        ?>
        <tr>
            <td colspan="4">
                <a class="transparent" href="/pf/graphs.php?submenu=states"><img src="/system/dashboard/pf.png" name="pf" alt="pf" title="<?php echo _TITLE2('States and state searches on the Packet Filter') ?>"></a>
            </td>
        </tr>
        <tr>
            <td id="dashboard" colspan="4" title="<?php echo _TITLE2('Number of states') ?>">
                <a class="transparent-white" href="/pf/info.php?submenu=states">
                <div id="count" style="background-color: #a800ae">
                    <table>
                        <tr class="count">
                            <td class="count">
                            <?php echo $ServiceInfo['pf']['states'] ?>
                            </td>
                        </tr>
                        <tr>
                            <td class="prio">
                            <?php echo _TITLE('STATES') ?>
                            </td>
                        </tr>
                    </table>
                </div>
                </a>
            </td>
        </tr>
        <tr>
            <td colspan="4">
                <a class="transparent" href="/pf/graphs.php?submenu=transfer"><img src="/system/dashboard/dataxfer.png" name="transfer" alt="transfer" title="<?php echo _TITLE2('Data transfer between internal and external interfaces') ?>"></a><br>
                <a class="transparent" href="/pf/graphs.php?submenu=ifs#Internal%20Interface"><img src="/system/dashboard/intif.png" name="intif" alt="intif" title="<?php echo _TITLE2('Traffic on the internal interface') ?>"></a><br>
                <a class="transparent" href="/pf/graphs.php?submenu=ifs#External%20Interface"><img src="/system/dashboard/extif.png" name="extif" alt="extif" title="<?php echo _TITLE2('Traffic on the external interface') ?>"></a><br>
                <a class="transparent" href="/pf/graphs.php?submenu=ifs#Loopback%20Interface"><img src="/system/dashboard/loif.png" name="loif" alt="loif" title="<?php echo _TITLE2('Traffic on the loopback interface') ?>"></a>
            </td>
        </tr>
        <?php
    }
References _TITLE().
FormatDate()
FormatDate ($date)
Builds PF (tcpdump) specific string from $date.
Parameters
array $date Datetime struct
Reimplemented from View.
Definition at line 76 of file pf.php.
    {
        global $MonthNames;
        return $MonthNames[$date['Month']].' '.$date['Day'];
    }
References $MonthNames.
formatDateHourRegexp()
formatDateHourRegexp ($month, $day, $hour, $minute)
Generates the module specific datetime regexp for filtering logs.
Parameters
string $month Two-digit month, or empty string for match all.
string $day Two-digit day, or empty string for match all.
string $hour Two-digit hour, or empty string for match all.
string $minute Two-digit minute, or empty string for match all.
Returns
string Regexp to use as datetime filter.
Reimplemented from Model.
Definition at line 612 of file pf.php.
    {
        return $this->formatDateHourRegexpDayLeadingZero($month, $day, $hour, $minute);
    }
References Model\formatDateHourRegexpDayLeadingZero().
Referenced by _getFileLineCount(), and GetLogs().
GetDateRegexp()
GetDateRegexp ($date)
Generates date regexp to be used by statistics functions.
Used to match date indeces of stats array to get stats for date ranges.
Parameters
array $date Date struct.
Returns
string Regexp.
Reimplemented from Model.
Definition at line 523 of file pf.php.
    {
        global $MonthNames;
        if ($date['Month'] == '') {
            $re= '.*';
        }
        else {
            $re= $MonthNames[$date['Month']].'\s+';
            if ($date['Day'] == '') {
                $re.= '.*';
            }
            else {
                $re.= sprintf('%02d', $date['Day']);
            }
        }
        return $re;
    }
References $MonthNames.
GetLogs()
GetLogs ($file, $end, $count, $re = '', $needle = '', $month = '', $day = '', $hour = '', $minute = '')
Gets lines in log file.
Parameters
string $file Log file pathname.
int $end Head option, start line.
int $count Tail option, page line count.
string $re Regexp to restrict the result set.
string $needle Optional regexp to use with a second grep over logs, used by Stats pages.
string $month Two-digit month, or empty string for match all.
string $day Two-digit day, or empty string for match all.
string $hour Two-digit hour, or empty string for match all.
string $minute Two-digit minute, or empty string for match all.
Returns
array Log lines.
Reimplemented from Model.
Definition at line 572 of file pf.php.
    {
        global $TCPDUMP;
        if (!$this->ValidateFile($file)) {
            return FALSE;
        }
        $cmd= "$TCPDUMP $file";
        if ($month != '' || $day != '' || $hour != '' || $minute != '') {
            $cmd.= ' | /usr/bin/grep -a -E "' . $this->formatDateHourRegexp($month, $day, $hour, $minute) . '"';
        }
        if ($needle != '') {
            $needle= escapeshellarg($needle);
            $cmd.= " | /usr/bin/grep -a -E $needle";
        }
        if ($re !== '') {
            $re= escapeshellarg($re);
            $cmd.= " | /usr/bin/grep -a -E $re";
        }
        $cmd.= " | /usr/bin/head -$end | /usr/bin/tail -$count";
        $lines= explode("\n", $this->RunShellCommand($cmd));
        $logs= array();
        foreach ($lines as $line) {
            unset($Cols);
            if ($this->ParseLogLine($line, $Cols)) {
                $logs[]= $Cols;
            } else {
                ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, 'Failed parsing log line: ' . $line);
            }
        }
        return Output(json_encode($logs));
    }
References $TCPDUMP, ctlr_syslog(), formatDateHourRegexp(), Output(), ParseLogLine(), Model\RunShellCommand(), and Model\ValidateFile().
GetPfIfsInfo()
GetPfIfsInfo ()
Gets pf interfaces info.
Attention
Do not use the following line: return $this->RunPfInfoCmd('/sbin/pfctl -s Interfaces -vv'); See GetPfInfo() for the details of this bug.
Returns
mixed Parsed output of the command on success, FALSE on fail.
Definition at line 321 of file pf.php.
    {
        exec('/sbin/pfctl -s Interfaces -vv', $output, $retval);
        if ($retval === 0) {
            return Output(json_encode($this->parsePfIfsInfo($output)));
        }
        return FALSE;
    }
References $retval, Output(), and parsePfIfsInfo().
GetPfInfo()
GetPfInfo ()
Gets general pf info.
Bug:
We cannot use RunCmd() here, because pfctl info output gives: msg_send(): msgsnd failed: Invalid argument This issue still persists on OpenBSD 6.4 with PHP 7.0.32.
Attention
So, do not use the following line: return $this->RunPfInfoCmd('/sbin/pfctl -s info');
Returns
mixed Output of the command on success, FALSE on fail.
Definition at line 227 of file pf.php.
    {
        $info= $this->_getPfInfo();
        if ($info !== FALSE) {
            return Output(implode("\n", $info));
        }
        return FALSE;
    }
References _getPfInfo(), and Output().
GetPfMemInfo()
GetPfMemInfo ()
Gets pf memory info.
Returns
mixed Output of the command on success, FALSE on fail.
Definition at line 250 of file pf.php.
    {
        return $this->RunPfInfoCmd('/sbin/pfctl -s memory');
    }
References RunPfInfoCmd().
GetPfQueueInfo()
GetPfQueueInfo ()
Gets pf queue info.
Returns
mixed Parsed output of the command on success, FALSE on fail.
Definition at line 270 of file pf.php.
    {
        exec('/sbin/pfctl -s queue -v', $output, $retval);
        if ($retval === 0) {
            return Output(json_encode($this->parsePfQueueInfo($output)));
        }
        return FALSE;
    }
References $retval, Output(), and parsePfQueueInfo().
GetPfRulesInfo()
GetPfRulesInfo ()
Gets pf rules info.
Attention
Do not use the following line: return $this->RunPfInfoCmd('/sbin/pfctl -s rules -vv'); See GetPfInfo() for the details of this bug.
Returns
mixed Parsed output of the command on success, FALSE on fail.
Definition at line 405 of file pf.php.
    {
        exec('/sbin/pfctl -s rules -vv', $output, $retval);
        if ($retval === 0) {
            return Output(json_encode($this->parsePfRulesInfo($output)));
        }
        return FALSE;
    }
References $retval, Output(), and parsePfRulesInfo().
GetPfTimeoutInfo()
GetPfTimeoutInfo ()
Gets pf timeouts.
Returns
mixed Output of the command on success, FALSE on fail.
Definition at line 260 of file pf.php.
    {
        return $this->RunPfInfoCmd('/sbin/pfctl -s timeouts');
    }
References RunPfInfoCmd().
GetStateCount()
GetStateCount ($re = '')
Gets pf state count.
Parameters
string $re Regexp to get count of a restricted result set
Returns
int Line count
Definition at line 650 of file pf.php.
    {
        return Output($this->_getStateCount($re));
    }
References _getStateCount(), and Output().
GetStateList()
GetStateList ($end, $count, $re = '')
Gets the pftop output.
Parameters
int $end Head option, start line
int $count Tail option, page line count
string $re Regexp to restrict the result set
Returns
serialized Lines
Definition at line 687 of file pf.php.
    {
        // Skip header lines by grepping for In or Out
        // Empty $re is not an issue for grep, greps all
        $re= escapeshellarg($re);
        $cmd= "$this->pftopCmd | /usr/bin/egrep -a 'In|Out' | /usr/bin/grep -a -E $re | /usr/bin/head -$end | /usr/bin/tail -$count";
        exec($cmd, $output, $retval);
        if ($retval === 0) {
            return Output(json_encode($this->ParsePftop($output)));
        }
        Error(implode("\n", $output));
        ctlr_syslog(LOG_DEBUG, __FILE__, __FUNCTION__, __LINE__, 'Failed running pftop');
        return FALSE;
    }
References $retval, ctlr_syslog(), Error(), Output(), and ParsePftop().
getTestRulesCmd()
getTestRulesCmd ($rulesStr, & $tmpFile)
Definition at line 455 of file pf.php.
    {
        return "/bin/echo '$rulesStr' | /sbin/pfctl -nf - 2>&1";
    }
IsRunning()
IsRunning ($proc = '')
Checks if pf is enabled or not.
Returns
bool TRUE if enabled, FALSE otherwise.
Reimplemented from Model.
Definition at line 144 of file pf.php.
    {
        $output= $this->RunShellCommand('/sbin/pfctl -s info');
        if (preg_match('/Status:\s*(Enabled|Disabled)\s*/', $output, $match)) {
            return ($match[1] == 'Enabled');
        }
        return FALSE;
    }
References Model\RunShellCommand().
Referenced by Start(), and Stop().
ParseLogLine()
ParseLogLine ($logline, & $cols)
Parses the given log line.
Parameters
string $logline Log line.
array $cols Parsed fields.
Returns
bool TRUE on success, FALSE on fail.
Reimplemented from Model.
Definition at line 460 of file pf.php.
    {
        global $Re_Ip;
        // Sep 28 03:50:22.683986 rule 39/(match) pass in on em1: 10.0.0.11.40284 > 10.0.0.13.443: S 3537547021:3537547021(0) win 5840 <mss 1460,sackOK,timestamp 6440374[|tcp]> (DF)
        // Sep 27 14:32:21.715363 rule 37/(match) pass in on em1: 10.0.0.11.40546 > 10.0.0.13.22: S 2853072521:2853072521(0) win 5840 <mss 1460,sackOK,timestamp 3609332[|tcp]> (DF)
        // Sep 28 02:57:36.888668 rule 47/(match) pass out on em1: 10.0.0.13.16227 > 194.27.110.130.123: v4 client strat 0 poll 0 prec 0 [tos 0x10]
        //
        // Sep 26 14:26:28.605638 rule 11/(match) block in on em1: 10.0.0.11.59299 > 239.255.255.250.1900: udp 132 (DF) [ttl 1]
        //
        // Sep 28 03:50:20.124951 rule 11/(match) block in on em1: 10.0.0.11 > 224.0.0.22: igmp-2 [v2] (DF) [tos 0xc0] [ttl 1]
        //
        // Sep 28 03:50:16.900084 rule 11/(match) block in on em1: 10.0.0.11.5353 > 224.0.0.251.5353: 0*- [0q] 7/0/0[|domain] (DF)
        // Sep 28 03:30:02.676705 rule 47/(match) pass out on em1: 10.0.0.13.41578 > 10.0.0.2.53: 61952+% [1au][|domain]
        //
        // Sep 28 03:50:03.858844 rule 11/(match) block in on em0: 10.0.0.2.67 > 255.255.255.255.68: xid:0xf2ed6079 flags:0x8000 [|bootp] (DF)
        // Sep 28 03:50:03.858828 rule 11/(match) block in on em0: 0.0.0.0.68 > 255.255.255.255.67: xid:0xf2ed6079 [|bootp] [tos 0x10]
        //
        // Sep 28 03:50:03.749086 rule 11/(match) block in on em1: fe80::21f:e2ff:fe61:969a > ff02::2: icmp6: router solicitation
        // Sep 28 03:49:54.705294 rule 11/(match) block in on em0: :: > ff02::1:ff61:969a: [|icmp6]
        // Sep 26 17:46:27.631418 rule 11/(match) block in on em0: :: > ff02::16: HBH icmp6: type-#143 [hlim 1]
        // Oct 18 05:16:52.230791 rule 11/(match) block in on em1: fe80::a00:27ff:fe4f:2af9.546 > ff02::1:2.547:dhcp6 solicit [hlim 1]
        $re_datetime= '(\w+\s+\d+)\s+(\d+:\d+:\d+)\.\d+';
        $re_rule= 'rule\s+([\w\.]+)\/\S+';
        $re_action= '(block|pass|match)';
        $re_direction= '(in|out)';
        $re_if= 'on\s+(\w+\d+):';
        $re_srcipport= "($Re_Ip|[\w:]+)(.(\d+)|)";
        $re_dstipport= "($Re_Ip|[\w:]+)(.(\d+)|)";
        $re_rest= '(.*)';
        $re= "/^$re_datetime\s+$re_rule\s+$re_action\s+$re_direction\s+$re_if\s+$re_srcipport\s+>\s+$re_dstipport:\s*$re_rest$/";
        if (preg_match($re, $logline, $match)) {
            $cols['Date']= $match[1];
            $cols['Time']= $match[2];
            $cols['Rule']= $match[3];
            $cols['Act']= $match[4];
            $cols['Dir']= $match[5];
            $cols['If']= $match[6];
            $cols['SrcIP']= $match[7];
            $cols['SPort']= $match[9];
            $cols['DstIP']= $match[10];
            $cols['DPort']= $match[12];
            $rest= $match[13];
            $re= '/(tcp|udp|domain|icmp6|icmp\b|igmp\-2|igmp\b|bootp|\back\b|v4|dhcp\d*)/';
            if (preg_match($re, $rest, $match)) {
                $cols['Type']= $match[1];
            }
            elseif (preg_match('/\s+win\s+\d+/', $rest)) {
                $cols['Type']= 'tcp';
            }
            else {
                $cols['Type']= 'other';
            }
            $cols['Log']= $rest;
            return TRUE;
        }
        return FALSE;
    }
References $Re_Ip.
Referenced by _getLiveLogs(), and GetLogs().
parsePfIfsInfo()
parsePfIfsInfo ($lines)
Definition at line 330 of file pf.php.
    {
        $ifs= array();
        $i= array();
        //all
        //  Cleared:     Thu Jan  1 02:00:01 1970
        //  References:  [ States:  13                 Rules: 1                  ]
        //  In4/Pass:    [ Packets: 0                  Bytes: 0                  ]
        //  In4/Block:   [ Packets: 0                  Bytes: 0                  ]
        //  Out4/Pass:   [ Packets: 0                  Bytes: 0                  ]
        //  Out4/Block:  [ Packets: 0                  Bytes: 0                  ]
        //  In6/Pass:    [ Packets: 0                  Bytes: 0                  ]
        //  In6/Block:   [ Packets: 0                  Bytes: 0                  ]
        //  Out6/Pass:   [ Packets: 0                  Bytes: 0                  ]
        //  Out6/Block:  [ Packets: 0                  Bytes: 0                  ]
        foreach ($lines as $line) {
            if (preg_match('/^([\w\s\‍(\‍)]+)$/', $line, $match)) {
                if (count($i) > 0) {
                    if (!isset($i['name'])) {
                        $i['name']= '';
                    }
                    $ifs[]= $i;
                }
                $i= array('name' => $match[1]);
            } elseif (preg_match('/^\s*Cleared:\s*(.*)\s*$/', $line, $match)) {
                $i['cleared']= $match[1];
            } elseif (preg_match('/^\s*References:\s*\[\s*States:\s*(\d+)\s*Rules:\s*(\d+)\s*\]/', $line, $match)) {
                $i['states']= convertDecimal($match[1]);
                $i['rules']= convertDecimal($match[2]);
            } elseif (preg_match('/^\s*In4\/Pass:\s*\[\s*Packets:\s*(\d+)\s*Bytes:\s*(\d+)\s*\]/', $line, $match)) {
                $i['in4PassPackets']= convertDecimal($match[1]);
                $i['in4PassBytes']= convertBinary($match[2]);
            } elseif (preg_match('/^\s*In4\/Block:\s*\[\s*Packets:\s*(\d+)\s*Bytes:\s*(\d+)\s*\]/', $line, $match)) {
                $i['in4BlockPackets']= convertDecimal($match[1]);
                $i['in4BlockBytes']= convertBinary($match[2]);
            } elseif (preg_match('/^\s*Out4\/Pass:\s*\[\s*Packets:\s*(\d+)\s*Bytes:\s*(\d+)\s*\]/', $line, $match)) {
                $i['out4PassPackets']= convertDecimal($match[1]);
                $i['out4PassBytes']= convertBinary($match[2]);
            } elseif (preg_match('/^\s*Out4\/Block:\s*\[\s*Packets:\s*(\d+)\s*Bytes:\s*(\d+)\s*\]/', $line, $match)) {
                $i['out4BlockPackets']= convertDecimal($match[1]);
                $i['out4BlockBytes']= convertBinary($match[2]);
            } elseif (preg_match('/^\s*In6\/Pass:\s*\[\s*Packets:\s*(\d+)\s*Bytes:\s*(\d+)\s*\]/', $line, $match)) {
                $i['in6PassPackets']= convertDecimal($match[1]);
                $i['in6PassBytes']= convertBinary($match[2]);
            } elseif (preg_match('/^\s*In6\/Block:\s*\[\s*Packets:\s*(\d+)\s*Bytes:\s*(\d+)\s*\]/', $line, $match)) {
                $i['in6BlockPackets']= convertDecimal($match[1]);
                $i['in6BlockBytes']= convertBinary($match[2]);
            } elseif (preg_match('/^\s*Out6\/Pass:\s*\[\s*Packets:\s*(\d+)\s*Bytes:\s*(\d+)\s*\]/', $line, $match)) {
                $i['out6PassPackets']= convertDecimal($match[1]);
                $i['out6PassBytes']= convertBinary($match[2]);
            } elseif (preg_match('/^\s*Out6\/Block:\s*\[\s*Packets:\s*(\d+)\s*Bytes:\s*(\d+)\s*\]/', $line, $match)) {
                $i['out6BlockPackets']= convertDecimal($match[1]);
                $i['out6BlockBytes']= convertBinary($match[2]);
            } else {
                ctlr_syslog(LOG_WARNING, __FILE__, __FUNCTION__, __LINE__, "Failed parsing interface line: $line");
            }
        }
        if (count($i) > 0) {
            $ifs[]= $i;
        }
        return $ifs;
    }
References $ifs, convertBinary(), convertDecimal(), and ctlr_syslog().
Referenced by GetPfIfsInfo().
parsePfQueueInfo()
parsePfQueueInfo ($lines)
Definition at line 279 of file pf.php.
    {
        $queues= array();
        $q= array();
        //queue std on em1 bandwidth 100M qlimit 50
        //  [ pkts:          0  bytes:          0  dropped pkts:      0 bytes:      0 ]
        //  [ qlength:   0/ 50 ]
        foreach ($lines as $line) {
            if (preg_match('/^queue\s+(\S+)/', $line, $match)) {
                if (!isset($q['name'])) {
                    $q['name']= '';
                }
                $queues[]= $q;
                $q= array('name' => $match[1]);
            } elseif (preg_match('/^\s*\[\s*pkts:\s*(\d+)\s*bytes:\s*(\d+)\s*dropped pkts:\s*(\d+)\s*bytes:\s*(\d+)\s*\]/', $line, $match)) {
                $q['pkts']= convertDecimal($match[1]);
                $q['bytes']= convertBinary($match[2]);
                $q['droppedPkts']= convertDecimal($match[3]);
                $q['droppedBytes']= convertBinary($match[4]);
            } elseif (preg_match('/^\s*\[\s*qlength:\s*(\d+)\s*\/\s*(\d+)\s*/', $line, $match)) {
                $q['length']= $match[1] . '/' . $match[2];
            } else {
                ctlr_syslog(LOG_WARNING, __FILE__, __FUNCTION__, __LINE__, "Failed parsing queue line: $line");
            }
        }
        if (count($q) > 0) {
            $queues[]= $q;
        }
        return $queues;
    }
References $queues, convertBinary(), convertDecimal(), and ctlr_syslog().
Referenced by GetPfQueueInfo().
parsePfRulesInfo()
parsePfRulesInfo ($lines)
Definition at line 414 of file pf.php.
    {
        $rules= array();
        $r= array();
        //@0 match in all scrub (no-df)
        //  [ Evaluations: 1558      Packets: 16048     Bytes: 7312376     States: 2     ]
        //  [ Inserted: uid 0 pid 7529 State Creations: 0     ]
        foreach ($lines as $line) {
            if (preg_match('/^@(\d+)\s+(.*)$/', $line, $match)) {
                if (count($r) > 0) {
                    if (!isset($r['number'])) {
                        $r['number']= '';
                    }
                    $rules[]= $r;
                }
                $r= array(
                    'number' => $match[1],
                    'rule' => $match[2],
                    );
            } elseif (preg_match('/^\s*\[\s*Evaluations:\s*(\d+)\s*Packets:\s*(\d+)\s*Bytes:\s*(\d+)\s*States:\s*(\d+)\s*\]/', $line, $match)) {
                $r['evaluations']= convertDecimal($match[1]);
                $r['packets']= convertDecimal($match[2]);
                $r['bytes']= convertBinary($match[3]);
                $r['states']= convertDecimal($match[4]);
            } elseif (preg_match('/^\s*\[\s*Inserted:\s*(.*)\s*State Creations:\s*(\d+)\s*\]/', $line, $match)) {
                $r['inserted']= $match[1];
                $r['stateCreations']= convertDecimal($match[2]);
            } else {
                ctlr_syslog(LOG_WARNING, __FILE__, __FUNCTION__, __LINE__, "Failed parsing rule line: $line");
            }
        }
        if (count($r) > 0) {
            $rules[]= $r;
        }
        return $rules;
    }
References $r, $rules, convertBinary(), convertDecimal(), and ctlr_syslog().
Referenced by GetPfRulesInfo().
ParsePftop()
ParsePftop ($pftopout)
Parses pftop output.
Parameters
array $pftopout pftop output
Returns
array States
Definition at line 710 of file pf.php.
    {
        $states= array();
        foreach ($pftopout as $line) {
            if (preg_match($this->re_Pftop, $line, $match)) {
                $states[]= array(
                    $match[1],
                    $match[2],
                    $match[3],
                    $match[4],
                    $match[5],
                    $match[6],
                    $match[7],
                    $match[8],
                    $match[9],
                    );
            }
        }
        return $states;
    }
Referenced by GetStateList().
PrintStatesTable()
PrintStatesTable ()
Gets and lists pf states.
Definition at line 86 of file pf.php.
    {
        global $HeadStart, $StartLine, $StateCount, $LinesPerPage, $SearchRegExp;
        PrintLogHeaderForm($StartLine, $StateCount, $LinesPerPage, $SearchRegExp, '');
        $states= array();
        if ($this->Controller($output, 'GetStateList', $HeadStart, $LinesPerPage, $SearchRegExp)) {
            $states= json_decode($output[0], TRUE);
        }
        $total= count($states);
        if ($total > 0) {
            ?>
            <table id="logline">
                <?php
                $this->PrintStatesTableHeader();
                $linenum= 0;
                foreach ($states as $cols) {
                    $rowClass= ($linenum++ % 2 == 0) ? 'evenline' : 'oddline';
                    $lastLine= $linenum == $total;
                    ?>
                    <tr>
                        <td class="<?php echo $rowClass.($lastLine ? ' lastLineFirstCell':'') ?> center">
                            <?php echo $linenum + $StartLine ?>
                        </td>
                        <?php
                        $totalCols= count($cols);
                        $count= 1;
                        foreach ($cols as $c) {
                            $cellClass= $rowClass;
                            if (in_array($count, array(1, 2, 5, 6, 7))) {
                                $cellClass.= ' center';
                            }
                            else if (in_array($count, array(8, 9))) {
                                $cellClass.= ' right';
                            }
                            if ($lastLine && $count == $totalCols) {
                                $cellClass.= ' lastLineLastCell';
                            }
                            ?>
                            <td class="<?php echo $cellClass ?>">
                                <?php echo $c ?>
                            </td>
                            <?php
                            $count++;
                        }
                        ?>
                    </tr>
                    <?php
                }
                ?>
            </table>
            <?php
        }
    }
References $StateCount, View\Controller(), PrintLogHeaderForm(), and PrintStatesTableHeader().
PrintStatesTableHeader()
PrintStatesTableHeader ()
Prints headers for states table.
PR D SRC DEST STATE AGE EXP PKTS BYTES
Definition at line 150 of file pf.php.
    {
        ?>
        <tr id="logline">
            <th><?php echo _('Line') ?></th>
            <th><?php echo _('Proto') ?></th>
            <th><?php echo _('Dir') ?></th>
            <th><?php echo _('Source') ?></th>
            <th><?php echo _('Dest') ?></th>
            <th><?php echo _('State') ?></th>
            <th><?php echo _('Age') ?></th>
            <th><?php echo _('Expr') ?></th>
            <th><?php echo _('Packets') ?></th>
            <th><?php echo _('Bytes') ?></th>
        </tr>
        <?php
    }
Referenced by PrintStatesTable().
RunPfInfoCmd()
RunPfInfoCmd ($cmd)
Runs pfctl info commands.
Parameters
string $cmd Command to execute.
Returns
mixed Output of the command on success, FALSE on fail.
Definition at line 202 of file pf.php.
    {
        if (!$this->RunCmd($cmd, $output, $retval)) {
            Error(_('Failed running pfctl command') . ': ' . $cmd);
            ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Failed running pfctl stats command: $cmd");
            return FALSE;
        }
        if ($retval === 0) {
            return Output(implode("\n", $output));
        }
        return FALSE;
    }
References $retval, ctlr_syslog(), Error(), and Output().
Referenced by GetPfMemInfo(), and GetPfTimeoutInfo().
SetIfs()
SetIfs ($lanif, $wanif)
Sets interface names in pf.conf.
Parameters
string $lanif Name of the internal interface.
string $wanif Name of the external interface.
Returns
bool TRUE on success, FALSE on fail.
Definition at line 121 of file pf.php.
    {
        $retval= $this->SetNVP($this->PfRulesFile, 'int_if', '"'.$lanif.'"');
        $retval&= $this->SetNVP($this->PfRulesFile, 'ext_if', '"'.$wanif.'"');
        return $retval;
    }
References $retval, and Model\SetNVP().
SetIntnet()
SetIntnet ($net)
Sets int_net.
Parameters
string $net Internal network address.
Returns
bool TRUE on success, FALSE on fail.
Definition at line 134 of file pf.php.
    {
        return $this->SetNVP($this->PfRulesFile, 'int_net', '"'.$net.'"');
    }
References Model\SetNVP().
Start()
Start ()
Enable pf.
Returns
bool TRUE on success, FALSE on fail.
Reimplemented from Model.
Definition at line 158 of file pf.php.
    {
        if (!$this->IsRunning()) {
            exec('/sbin/pfctl -e 2>&1', $output, $retval);
            if ($retval !== 0) {
                Error(implode("\n", $output));
            }
            return $this->IsRunning();
        } else {
            return TRUE;
        }
    }
References $retval, Error(), and IsRunning().
Stop()
Stop ()
Disable pf.
Returns
bool TRUE on success, FALSE on fail.
Reimplemented from Model.
Definition at line 176 of file pf.php.
    {
        if ($this->IsRunning()) {
            exec('/sbin/pfctl -d 2>&1', $output, $retval);
            if ($retval !== 0) {
                Error(implode("\n", $output));
            }
            return !$this->IsRunning();
        } else {
            return TRUE;
        }
    }
References $retval, Error(), and IsRunning().
Field Documentation
$ConfFile
$ConfFile = '/etc/pf.conf'
Definition at line 44 of file pf.php.
$ConfPath
$ConfPath = '/etc/pfre'
Definition at line 43 of file pf.php.
$LogFile
$LogFile = '/var/log/pflog'
Definition at line 35 of file pf.php.
$Model
$Model = 'pf'
Definition at line 54 of file pf.php.
$Name
$Name = 'pf'
Definition at line 33 of file pf.php.
$ReloadCmd
$ReloadCmd = "/sbin/pfctl -f <FILE> 2>&1"
Definition at line 46 of file pf.php.
$RuleSet
$RuleSet
Definition at line 56 of file pf.php.
The documentation for this class was generated from the following files:
src/Model/pf.php
src/View/pf/pf.php