PF Firewall: Anchor Class Reference
Anchor Class Reference
Public Member Functions
display ($ruleNumber, $count)
Processes inputs submitted on the edit page.
countLines ()
Counts the lines in inline rules.
dispAction ()
dispInline ()
Displays inline rules.
input ()
Processes inputs submitted on the edit page.
inputInline ()
Gets submitted inline rules.
edit ($ruleNumber, $modified, $testResult, $generateResult, $action)
Prints edit page.
editInlineRules ()
Public Member Functions inherited from FilterBase
display ($ruleNumber, $count)
Processes inputs submitted on the edit page.
dispAction ()
dispSrcDest ()
dispQueue ()
input ()
Processes inputs submitted on the edit page.
inputFilterHead ()
inputFilterOpts ()
inputQueue ()
inputAddIcmpType ($key)
inputAll ()
edit ($ruleNumber, $modified, $testResult, $generateResult, $action)
Prints edit page.
editFilterHead ()
editFilterOpts ()
editDirection ()
editHost ($key, $title, $delName, $addName, $hint, $help=NULL, $size=0, $disabled=FALSE)
editStateFilter ()
editIcmpType ($key, $title, $delName, $addName)
editQueue ()
editTagged ()
editReceivedOn ()
Public Member Functions inherited from State
display ($ruleNumber, $count)
Processes inputs submitted on the edit page.
dispState ()
dispText ($key)
dispBool ($key)
dispOverload ()
dispSourceTrack ()
input ()
Processes inputs submitted on the edit page.
inputState ()
edit ($ruleNumber, $modified, $testResult, $generateResult, $action)
Prints edit page.
editState ()
editIfBinding ()
editOverload ()
editSourceTrack ()
Public Member Functions inherited from Timeout
display ($ruleNumber, $count)
Processes inputs submitted on the edit page.
dispTimeout ()
dispTimeoutOpts ()
input ()
Processes inputs submitted on the edit page.
inputTimeout ()
inputTimeoutOpt ($key, $var, $parent)
edit ($ruleNumber, $modified, $testResult, $generateResult, $action)
Prints edit page.
editTimeout ()
editFragment ()
editInterval ()
editSrcTrack ()
editTcpTimeouts ()
editUdpTimeouts ()
editIcmpTimeouts ()
editOtherTimeouts ()
editAdaptiveTimeouts ()
editTimeoutOpt ($timeout, $key)
Public Member Functions inherited from Rule
__construct ()
setType ()
Sets the type of certain Translation rules.
display ($ruleNumber, $count)
Processes inputs submitted on the edit page.
dispHead ($ruleNumber, $count)
Prints rule number, rule type, and line number.
countLines ()
Returns the number of extra lines.
dispTail ($ruleNumber)
Prints inline comments and edit links.
dispHeadEditLinks ($ruleNumber, $count)
Prints edit links in a cell.
dispEditLinks ($ruleNumber, $count, $up='up', $down='down', $del='del')
Prints e, u, d, and x links.
dispKey ($key, $title)
Displays the given key in a cell if its value is TRUE.
dispValue ($key, $title)
Displays the value(s) of the given key in a cell.
dispValues ($key, $title)
Displays the value(s) of the given host key in a cell.
dispInterface ()
printValue ($value, $pre='', $post='', $count=10)
Prints the given value(s).
dispLog ($colspan=1)
Displays log specification in a cell.
printHostPort ($value, $noAny=TRUE, $count=10)
Prints host or port values.
input ()
Processes inputs submitted on the edit page.
inputKey ($key, $parent=NULL)
Gets the value of the given POST input key.
inputBool ($key, $parent=NULL)
Gets the boolean value of the given POST input key.
inputKeyIfHasVar ($key, $var)
Gets the value of the given POST input key, if another given key exists already.
inputDel ($key, $var, $parent=NULL)
Gets the value of the given GET input var and deletes it from the given key.
inputDelValue ($key, $value, $parent=NULL)
Deletes the given value from the given key.
inputAdd ($key, $var, $parent=NULL)
Gets the value of the given POST input var and adds it to the given key.
inputAddValue ($key, $value, $parent=NULL)
Adds the given value to the given key.
inputInterface ()
Deletes or adds interface definitions.
inputLog ()
Gets the POST input vars of log specifications.
inputDelEmpty ($flatten=TRUE)
Deletes empty values in internal rule structure.
inputDelEmptyRecursive ($array, $flatten)
Recursively deletes empty values in NVP arrays.
edit ($ruleNumber, $modified, $testResult, $generateResult, $action)
Prints edit page.
editCheckbox ($key, $title)
Prints a checkbox for the given key, within a table row.
editText ($key, $title, $help=NULL, $size=0, $hint='')
Prints an edit box for the given key, within a table row.
editValues ($key, $title, $delName, $addName, $hint, $help=NULL, $size=0, $disabled=FALSE)
Prints delete links and input boxes for multi-valued keys, within a table row.
editHead ($modified, $testResult, $generateResult, $action)
Prints rule title, generated rule, and form header at the top of the edit page.
editTail ()
Closes the table and form on the edit page.
editInterface ()
editAf ()
editLog ()
Prints edit controls for log specifications.
editComment ()
Prints input box for inline comments.
editDeleteValueLinks ($value, $name, $prefix='', $postfix='')
Prints delete links for values.
editAddValueBox ($id, $label, $hint, $size=0, $disabled=FALSE)
Prints add input box for values.
editHelp ($label)
Prints help image with a link to an anchor in pf.conf man page.
Additional Inherited Members
Data Fields inherited from Rule
$cat = ''
Category or type of rule.
$rule = array()
Internal structure of rule properties in NVP format.
Protected Attributes inherited from Rule
$ref = ''
Name used in href.
$href = ''
Common part of edit links.
$ruleNumber = 0
Rule number.
$arr = array()
Used by certain rule types while displaying themselves on the list.
$editIndex = 0
Current count of rows on edit pages.
Detailed Description
Definition at line 23 of file Anchor.php.
Member Function Documentation
countLines()
countLines ()
Counts the lines in inline rules.
Inline rules always span beyond the anchor rule itself.
Reimplemented from Rule.
Definition at line 44 of file Anchor.php.
    {
        if (isset($this->rule['inline'])) {
            // Add 1 for anchor-close line
            return count(explode("\n", $this->rule['inline'])) + 1;
        } else {
            return 0;
        }
    }
dispAction()
dispAction ()
Reimplemented from FilterBase.
Definition at line 54 of file Anchor.php.
    {
        ?>
        <td title="<?php echo _TITLE('Id') ?>" nowrap="nowrap">
            <?php
            if (isset($this->rule['identifier'])) {
                echo $this->rule['identifier'];
            }
            ?>
        </td>
        <?php
    }
dispInline()
dispInline ()
Displays inline rules.
We enclose all tabs into code tags, otherwise indentation is lost.
Definition at line 72 of file Anchor.php.
    {
        ?>
        <td title="<?php echo _TITLE('Inline rules') ?>" colspan="2" nowrap="nowrap">
            <?php
            if (isset($this->rule['inline'])) {
                echo str_replace("\t", "<code>\t</code><code>\t</code>", nl2br(htmlentities($this->rule['inline'])));
            }
            ?>
        </td>
        <?php
    }
display()
display ($ruleNumber, $count)
Processes inputs submitted on the edit page.
All child classes should override this method.
Parameters
int $ruleNumber Rule number.
int $count Number of rules in the ruleset.
Reimplemented from FilterBase.
Definition at line 25 of file Anchor.php.
    {
        $this->dispHead($ruleNumber, $count);
        $this->dispAction();
        $this->dispValue('direction', _TITLE('Direction'));
        $this->dispInterface();
        $this->dispValue('proto', _TITLE('Proto'));
        $this->dispSrcDest();
        $this->dispValue('state-filter', _TITLE('State'));
        $this->dispQueue();
        $this->dispInline();
        $this->dispTail($ruleNumber);
    }
References _TITLE().
edit()
edit ($ruleNumber, $modified, $testResult, $generateResult, $action)
Prints edit page.
All child classes should override this method.
Parameters
int $ruleNumber Rule number.
bool $modified Whether the rule is modified or not.
bool $testResult Test result.
bool $generateResult Rule generation result.
string $action Current state of the edit page.
Reimplemented from FilterBase.
Definition at line 111 of file Anchor.php.
    {
        $this->editIndex= 0;
        $this->ruleNumber= $ruleNumber;
        $this->editHead($modified, $testResult, $generateResult, $action);
        $this->editText('identifier', _TITLE('Identifier'), 'anchor-id', NULL, _CONTROL('name, may be nested'));
        $this->editFilterHead();
        $this->editFilterOpts();
        $this->editInlineRules();
        $this->editComment();
        $this->editTail();
    }
References $testResult, _CONTROL(), and _TITLE().
editInlineRules()
editInlineRules ()
Definition at line 129 of file Anchor.php.
    {
        ?>
        <tr class="<?php echo ($this->editIndex++ % 2 ? 'evenline' : 'oddline'); ?>">
            <td class="title">
                <?php echo _TITLE('Inline Rules').':' ?>
            </td>
            <td>
                <textarea cols="80" rows="5" id="inline" name="inline" placeholder="<?php echo _CONTROL('Enter inline rules here') ?>"><?php echo isset($this->rule['inline']) ? $this->rule['inline'] : ''; ?></textarea>
                <?php $this->editHelp('inline') ?>
            </td>
        </tr>
        <?php
    }
References _TITLE().
input()
input ()
Processes inputs submitted on the edit page.
All child classes should override this method.
Reimplemented from FilterBase.
Definition at line 85 of file Anchor.php.
    {
        $this->inputKey('identifier');
        $this->inputFilterHead();
        $this->inputFilterOpts();
        $this->inputInline();
        $this->inputKey('comment');
        $this->inputDelEmpty();
    }
inputInline()
inputInline ()
Gets submitted inline rules.
inputKey() trims, hence this new method.
Definition at line 103 of file Anchor.php.
    {
        if (filter_has_var(INPUT_POST, 'state')) {
            // textarea inserts \r\n instead of just \n, which pfctl complains about, so delete \r chars
            $this->rule['inline']= preg_replace('/\r/', '', filter_input(INPUT_POST, 'inline'));
        }
    }
The documentation for this class was generated from the following file:
src/View/pf/lib/Anchor.php