PF Firewall: Rule Class Reference
Rule Class Reference
Base class for all rule types.
Public Member Functions
__construct ()
setType ()
Sets the type of certain Translation rules.
display ($ruleNumber, $count)
Processes inputs submitted on the edit page.
dispHead ($ruleNumber, $count)
Prints rule number, rule type, and line number.
countLines ()
Returns the number of extra lines.
dispTail ($ruleNumber)
Prints inline comments and edit links.
dispHeadEditLinks ($ruleNumber, $count)
Prints edit links in a cell.
dispEditLinks ($ruleNumber, $count, $up='up', $down='down', $del='del')
Prints e, u, d, and x links.
dispKey ($key, $title)
Displays the given key in a cell if its value is TRUE.
dispValue ($key, $title)
Displays the value(s) of the given key in a cell.
dispValues ($key, $title)
Displays the value(s) of the given host key in a cell.
dispInterface ()
printValue ($value, $pre='', $post='', $count=10)
Prints the given value(s).
dispLog ($colspan=1)
Displays log specification in a cell.
printHostPort ($value, $noAny=TRUE, $count=10)
Prints host or port values.
input ()
Processes inputs submitted on the edit page.
inputKey ($key, $parent=NULL)
Gets the value of the given POST input key.
inputBool ($key, $parent=NULL)
Gets the boolean value of the given POST input key.
inputKeyIfHasVar ($key, $var)
Gets the value of the given POST input key, if another given key exists already.
inputDel ($key, $var, $parent=NULL)
Gets the value of the given GET input var and deletes it from the given key.
inputDelValue ($key, $value, $parent=NULL)
Deletes the given value from the given key.
inputAdd ($key, $var, $parent=NULL)
Gets the value of the given POST input var and adds it to the given key.
inputAddValue ($key, $value, $parent=NULL)
Adds the given value to the given key.
inputInterface ()
Deletes or adds interface definitions.
inputLog ()
Gets the POST input vars of log specifications.
inputDelEmpty ($flatten=TRUE)
Deletes empty values in internal rule structure.
inputDelEmptyRecursive ($array, $flatten)
Recursively deletes empty values in NVP arrays.
edit ($ruleNumber, $modified, $testResult, $generateResult, $action)
Prints edit page.
editCheckbox ($key, $title)
Prints a checkbox for the given key, within a table row.
editText ($key, $title, $help=NULL, $size=0, $hint='')
Prints an edit box for the given key, within a table row.
editValues ($key, $title, $delName, $addName, $hint, $help=NULL, $size=0, $disabled=FALSE)
Prints delete links and input boxes for multi-valued keys, within a table row.
editHead ($modified, $testResult, $generateResult, $action)
Prints rule title, generated rule, and form header at the top of the edit page.
editTail ()
Closes the table and form on the edit page.
editInterface ()
editAf ()
editLog ()
Prints edit controls for log specifications.
editComment ()
Prints input box for inline comments.
editDeleteValueLinks ($value, $name, $prefix='', $postfix='')
Prints delete links for values.
editAddValueBox ($id, $label, $hint, $size=0, $disabled=FALSE)
Prints add input box for values.
editHelp ($label)
Prints help image with a link to an anchor in pf.conf man page.
Data Fields
$cat = ''
Category or type of rule.
$rule = array()
Internal structure of rule properties in NVP format.
Protected Attributes
$ref = ''
Name used in href.
$href = ''
Common part of edit links.
$ruleNumber = 0
Rule number.
$arr = array()
Used by certain rule types while displaying themselves on the list.
$editIndex = 0
Current count of rows on edit pages.
Detailed Description
Base class for all rule types.
Definition at line 30 of file Rule.php.
Constructor & Destructor Documentation
__construct()
__construct ()
Todo:
Make conf.php a parameter
Definition at line 74 of file Rule.php.
    {
        $this->cat= str_replace(__NAMESPACE__ . '\\', '', get_called_class());
        $this->ref= strtolower(ltrim($this->cat, '_'));
        $this->href= 'conf.php?sender=' . $this->ref . '&amp;rulenumber=';
        $this->setType();
    }
Member Function Documentation
countLines()
countLines ()
Returns the number of extra lines.
Almost all rules occupy only one line, except possibly Blank, Comment, or Anchor rules. To compute the actual number of lines a rule occupy we need a method like this, which those rule types override and return the extra number of lines they occupy.
Returns
int Number of extra lines in the rule.
Reimplemented in Anchor, Blank, and Comment.
Definition at line 158 of file Rule.php.
    {
        return 0;
    }
dispEditLinks()
dispEditLinks ($ruleNumber, $count, $up = 'up', $down = 'down', $del = 'del')
Prints e, u, d, and x links.
$count is used to disable up or down edit links of the first and the last rule in the rule set.
Parameters
int $ruleNumber Rule number.
int $count Number of rules in the ruleset.
string $up Used in href for GET input, currently the default value is used only.
string $down Used in href for GET input, currently the default value is used only.
string $del Used in href for GET input, currently the default value is used only.
Definition at line 217 of file Rule.php.
    {
        global $ruleCategoryNames;
        ?>
        <a href="<?php echo $this->href . $ruleNumber ?>" title="<?php echo _TITLE('Edit') ?>">
            <input type="button" value="E" /></a>
        <?php
        if ($ruleNumber > 0) {
            ?>
            <a href="<?php echo filter_input(INPUT_SERVER, 'PHP_SELF') ?>?<?php echo $up ?>=<?php echo $ruleNumber ?>" title="<?php echo _TITLE('Move up') ?>">
                <input type="button" value="U" /></a>
            <?php
        } else {
            ?>
            <input type="button" value="U" title="<?php echo _TITLE('Move up') ?>" disabled/>
            <?php
        }
        if ($ruleNumber < $count) {
            ?>
            <a href="<?php echo filter_input(INPUT_SERVER, 'PHP_SELF') ?>?<?php echo $down ?>=<?php echo $ruleNumber ?>" title="<?php echo _TITLE('Move down') ?>">
                <input type="button" value="D" /></a>
            <?php
        } else {
            ?>
            <input type="button" value="D" title="<?php echo _TITLE('Move down') ?>" disabled/>
            <?php
        }
        $ruleType= $ruleCategoryNames[$this->ref];
        $confirmMsg= _CONTROL('Are you sure you want to delete <RULE_TYPE> rule number <RULE_NUMBER>?');
        $confirmMsg= str_replace('<RULE_TYPE>', $ruleType, $confirmMsg);
        $confirmMsg= str_replace('<RULE_NUMBER>', $ruleNumber, $confirmMsg);
        ?>
        <a href="<?php echo filter_input(INPUT_SERVER, 'PHP_SELF') ?>?<?php echo $del ?>=<?php echo $ruleNumber ?>" title="<?php echo _TITLE('Delete') ?>" onclick="return confirm('<?php echo $confirmMsg ?>')">
            <input type="button" value="X" /></a>
        <?php
        if ($this->cat != 'Comment') {
            ?>
            <a href="<?php echo filter_input(INPUT_SERVER, 'PHP_SELF') ?>?comment=<?php echo $ruleNumber ?>" title="<?php echo _TITLE('Comment') ?>">
                <input type="button" value="C" /></a>
            <a href="<?php echo filter_input(INPUT_SERVER, 'PHP_SELF') ?>?separate=<?php echo $ruleNumber ?>" title="<?php echo _TITLE('Separate') ?>">
                <input type="button" value="S"  disabled/></a>
            <?php
        } else {
            // countLines() returns extra lines, hence > 0, not > 1
            $disabled= $this->countLines() > 0 ? '' : 'disabled';
            ?>
            <a href="<?php echo filter_input(INPUT_SERVER, 'PHP_SELF') ?>?uncomment=<?php echo $ruleNumber ?>" title="<?php echo _TITLE('Uncomment') ?>">
                <input type="button" value="N" /></a>
            <a href="<?php echo filter_input(INPUT_SERVER, 'PHP_SELF') ?>?separate=<?php echo $ruleNumber ?>" title="<?php echo _TITLE('Separate') ?>">
                <input type="button" value="S" <?php echo $disabled ?>/></a>
            <?php
        }
    }
References $ruleCategoryNames, and _CONTROL().
dispHead()
dispHead ($ruleNumber, $count)
Prints rule number, rule type, and line number.
Used by almost all rule types. Passes $count to dispHeadEditLinks() to disable up or down edit links of the first and the last rule in the rule set.
Parameters
int $ruleNumber Rule number.
int $count Number of rules in the ruleset.
Definition at line 117 of file Rule.php.
    {
        global $lineNumber, $ruleCategoryNames;
        $ruleType= $ruleCategoryNames[$this->ref];
        $lineCount= $this->countLines();
        $title= _TITLE('<RULE_TYPE> rule');
        $title= str_replace('<RULE_TYPE>', $ruleType, $title);
        ?>
        <tr title="<?php echo $title ?>"<?php echo ($ruleNumber % 2 ? ' class="oddline"' : ' class="evenline"') ?>>
            <td title="<?php echo _TITLE('Rule number') ?>" class="center">
                <?php echo $ruleNumber; ?>
            </td>
            <?php
            $this->dispHeadEditLinks($ruleNumber, $count);
            ?>
            <td title="<?php echo _TITLE('Category') ?>" class="category">
                <?php echo $ruleType; ?>
            </td>
            <td title="<?php echo _TITLE('Line number') ?>" class="center">
                <?php
                $lines= array();
                for ($i= 0; $i <= $lineCount; $i++) {
                    $lines[]= ($lineNumber + $i);
                }
                echo implode('<br>', $lines);
                ?>
            </td>
        <?php
        $lineNumber+= $lineCount;
    }
References $ruleCategoryNames, and _TITLE().
dispHeadEditLinks()
dispHeadEditLinks ($ruleNumber, $count)
Prints edit links in a cell.
Certain rule types do not have inline comments, such as Blank and Comment rules. Such rules call this method, instead of dispTail(). Passes $count to dispEditLinks() to disable up or down edit links of the first and the last rule in the rule set.
Parameters
int $ruleNumber Rule number.
int $count Number of rules in the ruleset.
Definition at line 195 of file Rule.php.
    {
        ?>
            <td class="<?php echo ($ruleNumber % 2 ? 'editoddline' : 'edit') ?>">
                <?php
                $this->dispEditLinks($ruleNumber, $count);
                ?>
            </td>
        <?php
    }
dispInterface()
dispInterface ()
Reimplemented in Filter.
Definition at line 332 of file Rule.php.
    {
        ?>
        <td title="<?php echo _TITLE('Interface') ?>">
            <?php
            if (isset($this->rule['interface'])) {
                $this->printValue($this->rule['interface']);
            }
            ?>
        </td>
        <?php
    }
dispKey()
dispKey ($key, $title)
Displays the given key in a cell if its value is TRUE.
Used with boolean key values only.
Parameters
string $key Key to print.
string $title Title of the cell.
Definition at line 280 of file Rule.php.
    {
        ?>
        <td title="<?php echo $title ?>">
            <?php
            if (isset($this->rule[$key])) {
                echo $key;
            }
            ?>
        </td>
        <?php
    }
display()
display ($ruleNumber, $count)
Processes inputs submitted on the edit page.
All child classes should override this method.
Parameters
int $ruleNumber Rule number.
int $count Number of rules in the ruleset.
Reimplemented in AfTo, Anchor, Antispoof, Blank, Comment, DivertPacket, DivertTo, FilterBase, _Include, Limit, LoadAnchor, Macro, NatBase, Option, Queue, Route, Scrub, State, Table, and Timeout.
Definition at line 103 of file Rule.php.
    {
    }
dispLog()
dispLog ($colspan = 1)
Displays log specification in a cell.
Parameters
int $colspan Number of columns to span.
Definition at line 377 of file Rule.php.
    {
        ?>
        <td title="Log" colspan="<?php echo $colspan; ?>">
            <?php
            if (isset($this->rule['log'])) {
                if (is_array($this->rule['log'])) {
                    $s= 'log ';
                    foreach ($this->rule['log'] as $k => $v) {
                        $s.= (is_bool($v) ? "$k" : "$k=$v") . ', ';
                    }
                    echo trim($s, ', ');
                } else {
                    echo 'log';
                }
            }
            ?>
        </td>
        <?php
    }
dispTail()
dispTail ($ruleNumber)
Prints inline comments and edit links.
Used by almost all rule types.
Parameters
int $ruleNumber Rule number.
Definition at line 170 of file Rule.php.
    {
        ?>
            <td class="comment">
                <?php
                if (isset($this->rule['comment'])) {
                    echo htmlentities(stripslashes($this->rule['comment']));
                }
                ?>
            </td>
        </tr>
        <?php
    }
dispValue()
dispValue ($key, $title)
Displays the value(s) of the given key in a cell.
Parameters
string $key Key to print the value of.
string $title Title of the cell.
Definition at line 300 of file Rule.php.
    {
        ?>
        <td title="<?php echo $title ?>">
            <?php
            if (isset($this->rule[$key])) {
                $this->printValue($this->rule[$key]);
            }
            ?>
        </td>
        <?php
    }
dispValues()
dispValues ($key, $title)
Displays the value(s) of the given host key in a cell.
Parameters
string $key Host key to print the value of.
string $title Title of the cell.
Reimplemented in Table.
Definition at line 319 of file Rule.php.
    {
        ?>
        <td title="<?php echo $title ?>">
            <?php
            if (isset($this->rule[$key])) {
                $this->printHostPort($this->rule[$key]);
            }
            ?>
        </td>
        <?php
    }
edit()
edit ($ruleNumber, $modified, $testResult, $generateResult, $action)
Prints edit page.
All child classes should override this method.
Parameters
int $ruleNumber Rule number.
bool $modified Whether the rule is modified or not.
bool $testResult Test result.
bool $generateResult Rule generation result.
string $action Current state of the edit page.
Reimplemented in AfTo, Anchor, Antispoof, Blank, Comment, DivertPacket, DivertTo, Filter, FilterBase, _Include, Limit, LoadAnchor, Macro, NatBase, NatTo, Option, Queue, Route, Scrub, State, Table, and Timeout.
Definition at line 699 of file Rule.php.
    {
    }
editAddValueBox()
editAddValueBox ($id, $label, $hint, $size = 0, $disabled = FALSE)
Prints add input box for values.
Simply a text input box and a label. Used for multi-value fields in rules.
Parameters
string $id Id of the input
mixed $label Label, string or NULL.
string $hint Hint text.
string $value Value instead of hint.
mixed $size Size of the input, int or NULL.
bool $disabled Condition to disable the input.
Definition at line 961 of file Rule.php.
    {
        ?>
        <input type="text" id="<?php echo $id ?>" name="<?php echo $id ?>" size="<?php echo $size ?>" placeholder="<?php echo $hint ?>" <?php echo $disabled ? 'disabled' : '' ?> />
        <label for="<?php echo $id ?>"><?php echo $label ?></label>
        <?php
    }
editAf()
editAf ()
Definition at line 847 of file Rule.php.
    {
        ?>
        <tr class="<?php echo ($this->editIndex++ % 2 ? 'evenline' : 'oddline'); ?>">
            <td class="title">
                <?php echo _TITLE('Address Family').':' ?>
            </td>
            <td>
                <select id="af" name="af">
                    <option value="" label=""></option>
                    <option value="inet" label="inet" <?php echo (isset($this->rule['af']) && $this->rule['af'] == 'inet' ? 'selected' : '') ?>>inet</option>
                    <option value="inet6" label="inet6" <?php echo (isset($this->rule['af']) && $this->rule['af'] == 'inet6' ? 'selected' : '') ?>>inet6</option>
                </select>
                <?php $this->editHelp('address-family') ?>
            </td>
        </tr>
        <?php
    }
References _TITLE().
editCheckbox()
editCheckbox ($key, $title)
Prints a checkbox for the given key, within a table row.
Used for keys with boolean values.
Parameters
string $key Id and name of the checkbox.
string $title Title for the key.
Definition at line 711 of file Rule.php.
    {
        ?>
        <tr class="<?php echo ($this->editIndex++ % 2 ? 'evenline' : 'oddline'); ?>">
            <td class="title">
                <?php echo $title.':' ?>
            </td>
            <td>
                <input type="checkbox" id="<?php echo $key ?>" name="<?php echo $key ?>" value="<?php echo $key ?>" <?php echo (isset($this->rule[$key]) ? 'checked' : '') ?> />
                <?php $this->editHelp($key) ?>
            </td>
        </tr>
        <?php
    }
editComment()
editComment ()
Prints input box for inline comments.
Definition at line 899 of file Rule.php.
    {
        ?>
        <tr class="<?php echo ($this->editIndex++ % 2 ? 'evenline' : 'oddline'); ?>">
            <td class="title">
                <?php echo _TITLE('Comment').':' ?>
            </td>
            <td>
                <input type="text" id="comment" name="comment" value="<?php echo isset($this->rule['comment']) ? stripslashes($this->rule['comment']) : '' ?>" size="80" placeholder="<?php echo _CONTROL('enter comment, such as a description of the rule') ?>" />
            </td>
        </tr>
        <?php
    }
References _TITLE().
editDeleteValueLinks()
editDeleteValueLinks ($value, $name, $prefix = '', $postfix = '')
Prints delete links for values.
Used for multi-value fields in rules. Followed by add input box.
Parameters
mixed $value Value for delete link, array or string.
string $name Get input var name, usually with a del prefix.
string $prefix Prefix to print.
string $postfix Postfix to print.
Definition at line 924 of file Rule.php.
    {
        global $action;
        if (is_array($value)) {
            foreach ($value as $v) {
                $v= htmlentities($v);
                echo "$prefix$v$postfix";
                ?>
                <a href="<?php echo $this->href . $this->ruleNumber ?>&amp;<?php echo $name ?>=<?php echo $v ?>&amp;state=<?php echo $action ?>"><?php echo _CONTROL('delete') ?></a><br>
                <?php
            }
        } else {
            $value= htmlentities($value);
            echo "$prefix$value$postfix";
            ?>
            <a href="<?php echo $this->href . $this->ruleNumber ?>&amp;<?php echo $name ?>=<?php echo $value ?>&amp;state=<?php echo $action ?>"><?php echo _CONTROL('delete') ?></a><br>
            <?php
        }
        ?>
        <hr style="border: 0; border-bottom: 1px solid #CCC;" />
        <?php
    }
References _CONTROL().
editHead()
editHead ($modified, $testResult, $generateResult, $action)
Prints rule title, generated rule, and form header at the top of the edit page.
Also prints buttons and checkboxes to apply, save or cancel any modification on the edit page. Almost all edit pages use this method.
Parameters
bool $modified Whether the rule is modified or not.
bool $testResult Test result of the rule.
bool $generateResult Rule generation result.
string $action State of the edit page.
Definition at line 803 of file Rule.php.
    {
        global $ruleStr, $ruleCategoryNames;
        $ruleType= $ruleCategoryNames[$this->ref];
        $editHeader= _TITLE('Edit <RULE_TYPE> Rule <RULE_NUMBER>');
        $editHeader= str_replace('<RULE_TYPE>', $ruleType, $editHeader);
        $editHeader= str_replace('<RULE_NUMBER>', $this->ruleNumber, $editHeader);
        ?>
        <h2><?php echo $editHeader . ($modified ? ' (' . _TITLE('modified') . ')' : '') ?><?php $this->editHelp(ltrim($this->cat, '_')) ?></h2>
        <h4><?php echo str_replace("\t", "<code>\t</code><code>\t</code>", nl2br(htmlentities($ruleStr))) ?></h4>
        <form id="editForm" name="editForm" action="<?php echo $this->href . $this->ruleNumber ?>" method="post">
            <div class="buttons">
                <input type="submit" id="apply" name="apply" value="<?php echo _CONTROL('Apply') ?>" />
                <input type="submit" id="save" name="save" value="<?php echo _CONTROL('Save') ?>" <?php echo $modified ? '' : 'disabled' ?> />
                <input type="submit" id="cancel" name="cancel" value="<?php echo _CONTROL('Cancel') ?>" />
                <input type="checkbox" id="forcesave" name="forcesave" <?php echo $modified && !$testResult ? '' : 'disabled' ?> />
                <label for="forcesave"><?php echo _CONTROL('Save with errors') ?></label>
                <input type="checkbox" id="forcegenerate" name="forcegenerate" <?php echo !$generateResult ? '' : 'disabled' ?> <?php echo filter_has_var(INPUT_POST, 'forcegenerate') ? 'checked' : '' ?> />
                <label for="forcegenerate"><?php echo _CONTROL('Generate with errors') ?></label>
                <input type="hidden" name="state" value="<?php echo $action ?>" />
            </div>
            <table id="nvp">
            <?php
    }
References $ruleCategoryNames, $testResult, _CONTROL(), and _TITLE().
editHelp()
editHelp ($label)
Prints help image with a link to an anchor in pf.conf man page.
pf.conf man page is an html file generated from the actual pf.conf(5). The anchors are added manually to match with the labels given here.
Parameters
string $label Anchor in pf.conf man page.
Definition at line 977 of file Rule.php.
    {
        global $IMG_PATH;
        ?>
        <a target="<?php echo $label ?>" href="/pf/pf.conf.html#<?php echo $label ?>">
            <img src="<?php echo "$IMG_PATH/help.png" ?>" name="<?php echo $label ?>" alt="(?)" border="0" width="12" height="12">
        </a>
        <?php
    }
References $IMG_PATH, and width.
editInterface()
editInterface ()
Reimplemented in Filter.
Definition at line 842 of file Rule.php.
    {
        $this->editValues('interface', 'Interface', 'delInterface', 'addInterface', _CONTROL('if or macro'), NULL, 10);
    }
References _CONTROL().
editLog()
editLog ()
Prints edit controls for log specifications.
Definition at line 869 of file Rule.php.
    {
        ?>
        <tr class="<?php echo ($this->editIndex++ % 2 ? 'evenline' : 'oddline') ?>">
            <td class="title">
                <?php echo _TITLE('Logging').':' ?>
            </td>
            <td>
                <input type="checkbox" id="log" name="log" value="log" <?php echo (isset($this->rule['log']) ? 'checked' : '') ?> />
                <label for="log">Log</label>
                <?php
                $disabled= isset($this->rule['log']) ? '' : 'disabled';
                ?>
                <label for="log"><?php echo _TITLE('to') ?>:</label>
                <input type="text" id="log-to" name="log-to" value="<?php echo (isset($this->rule['log']['to']) ? $this->rule['log']['to'] : ''); ?>" placeholder="<?php echo _CONTROL('logging interface') ?>" <?php echo $disabled; ?> />
                <input type="checkbox" id="log-all" name="log-all" value="log-all" <?php echo (isset($this->rule['log']['all']) ? 'checked' : '') ?> <?php echo $disabled ?> />
                <label for="log">all</label>
                <input type="checkbox" id="log-matches" name="log-matches" value="log-matches" <?php echo (isset($this->rule['log']['matches']) ? 'checked' : ''); ?> <?php echo $disabled ?> />
                <label for="log">matches</label>
                <input type="checkbox" id="log-user" name="log-user" value="log-user" <?php echo (isset($this->rule['log']['user']) ? 'checked' : '') ?> <?php echo $disabled ?> />
                <label for="log">user</label>
                <?php $this->editHelp('log') ?>
            </td>
        </tr>
        <?php
    }
References _TITLE().
editTail()
editTail ()
Closes the table and form on the edit page.
Almost all edit pages use this method.
Definition at line 834 of file Rule.php.
    {
            ?>
            </table>
        </form>
        <?php
    }
editText()
editText ($key, $title, $help = NULL, $size = 0, $hint = '')
Prints an edit box for the given key, within a table row.
Used for keys with a single value.
Parameters
string $key Id and name of the checkbox.
string $title Title for the key.
string $help Anchor in the html file for the pf.conf(5) man page.
mixed $size Size of the input, int or NULL.
string $hint Hint text.
Definition at line 737 of file Rule.php.
    {
        $help= $help === NULL ? $key : $help;
        ?>
        <tr class="<?php echo ($this->editIndex++ % 2 ? 'evenline' : 'oddline') ?>">
            <td class="title">
                <?php echo $title.':' ?>
            </td>
            <td>
                <input type="text" id="<?php echo $key ?>" name="<?php echo $key ?>" value="<?php echo isset($this->rule[$key]) ? $this->rule[$key] : '' ?>" size="<?php echo $size ?>" placeholder="<?php echo $hint ?>" />
                <?php
                if ($help !== FALSE) {
                    $this->editHelp($help);
                }
                ?>
            </td>
        </tr>
        <?php
    }
editValues()
editValues ($key, $title, $delName, $addName, $hint, $help = NULL, $size = 0, $disabled = FALSE)
Prints delete links and input boxes for multi-valued keys, within a table row.
Parameters
string $key Id and name of the checkbox.
string $title Title for the key.
string $delName Var name to use in delete links.
string $addName Id of input box.
string $hint Hint text.
string $help Anchor in the html file for the pf.conf(5) man page.
mixed $size Size of the input, int or NULL.
bool $disabled Condition to disable the input
Reimplemented in Table.
Definition at line 769 of file Rule.php.
    {
        $help= $help === NULL ? $key : $help;
        ?>
        <tr class="<?php echo ($this->editIndex++ % 2 ? 'evenline' : 'oddline') ?>">
            <td class="title">
                <?php echo $title.':' ?>
            </td>
            <td>
                <?php
                if (isset($this->rule[$key])) {
                    $this->editDeleteValueLinks($this->rule[$key], $delName);
                }
                $this->editAddValueBox($addName, NULL, $hint, $size, $disabled);
                if ($help !== FALSE) {
                    $this->editHelp($help);
                }
                ?>
            </td>
        </tr>
        <?php
    }
input()
input ()
Processes inputs submitted on the edit page.
All child classes should override this method.
Reimplemented in AfTo, Anchor, Antispoof, Blank, Comment, DivertPacket, DivertTo, Filter, FilterBase, _Include, Limit, LoadAnchor, Macro, NatBase, NatTo, Option, Queue, Route, Scrub, State, Table, and Timeout.
Definition at line 426 of file Rule.php.
    {
    }
inputAdd()
inputAdd ($key, $var, $parent = NULL)
Gets the value of the given POST input var and adds it to the given key.
This method is used to get the values of multi-valued keys. All such inputs should have matching delete links, and visa-versa.
If a $parent is supplied, we use it as the parent of the given key.
Parameters
string $key Key to add the value to.
string $var Input key or variable to get the value of.
string $parent Parent of the given key.
Definition at line 559 of file Rule.php.
    {
        if (filter_has_var(INPUT_POST, 'state')) {
            if (filter_has_var(INPUT_POST, $var) && filter_input(INPUT_POST, $var) !== '') {
                $this->inputAddValue($key, preg_replace('/"/', '', filter_input(INPUT_POST, $var)), $parent);
            }
        }
    }
inputAddValue()
inputAddValue ($key, $value, $parent = NULL)
Adds the given value to the given key.
Converts a simple value to an array, if the number of values becomes more than 1.
If a $parent is supplied, we use it as the parent of the given key.
Parameters
string $key Key to add the value to.
string $value Value to add.
string $parent Parent of the given key.
Definition at line 579 of file Rule.php.
    {
        $rule= &$this->rule;
        if ($parent !== NULL) {
            $rule= &$this->rule[$parent];
        }
        if (!isset($rule[$key])) {
            $rule[$key]= $value;
        } else {
            if (!is_array($rule[$key])) {
                // Make array
                $tmp= $rule[$key];
                unset($rule[$key]);
                $rule[$key][]= $tmp;
            }
            $rule[$key][]= $value;
            $rule[$key]= array_unique($rule[$key]);
        }
    }
inputBool()
inputBool ($key, $parent = NULL)
Gets the boolean value of the given POST input key.
If a $parent is supplied, we use it as the parent of the given key.
Parameters
string $key Input key or variable to get the value of.
string $parent Parent of the given key.
Definition at line 466 of file Rule.php.
    {
        if (filter_has_var(INPUT_POST, 'state')) {
            $value= (filter_has_var(INPUT_POST, $key) ? TRUE : '');
            if ($parent == NULL) {
                $this->rule[$key]= $value;
            } else {
                $this->rule[$parent][$key]= $value;
            }
        }
    }
inputDel()
inputDel ($key, $var, $parent = NULL)
Gets the value of the given GET input var and deletes it from the given key.
This method is used to get the values of delete links.
If a $parent is supplied, we use it as the parent of the given key.
Parameters
string $key Key to delete the value from.
string $var Input key or variable to get the value of.
string $parent Parent of the given key.
Definition at line 507 of file Rule.php.
    {
        if (count($_GET)) {
            if (filter_has_var(INPUT_GET, $var)) {
                $this->inputDelValue($key, filter_input(INPUT_GET, $var), $parent);
            }
        }
    }
inputDelEmpty()
inputDelEmpty ($flatten = TRUE)
Deletes empty values in internal rule structure.
Converts single valued arrays to simple values, if $flatten is TRUE.
Parameters
bool $flatten Whether to flatten arrays with single values.
Todo:
Check why we cannot combine inputDelEmpty() with inputDelEmptyRecursive()
Definition at line 649 of file Rule.php.
    {
        $this->rule= $this->inputDelEmptyRecursive($this->rule, $flatten);
    }
inputDelEmptyRecursive()
inputDelEmptyRecursive ($array, $flatten)
Recursively deletes empty values in NVP arrays.
Converts single valued arrays to simple values, if $flatten is TRUE.
Parameters
array $array Array to delete empty values from.
bool $flatten Whether to flatten arrays with single values.
Returns
array Converted array.
Todo:
Is there a better way? Passing $flatten=FALSE down from Timeout and Limit objects does not work, Filter objects need TRUE
Attention
Do not flatten timeout, limit, and log options; their structure should always be array.
Definition at line 664 of file Rule.php.
    {
        foreach ($array as $key => $value) {
            if ($value == '') {
                unset($array[$key]);
            } elseif (is_array($value)) {
                $array[$key]= $this->inputDelEmptyRecursive($value, in_array($key, array('timeout', 'limit', 'log')) ? FALSE : $flatten);
                if (count($array[$key]) == 0) {
                    // Array is empty, delete it
                    unset($array[$key]);
                } elseif (count($array[$key]) == 1 && $flatten && !in_array($key, array('timeout', 'limit', 'log'))) {
                    // Array has only one element, convert from array to simple NVP
                    $v= current($array[$key]);
                    unset($array[$key]);
                    $array[$key]= $v;
                }
            }
        }
        return $array;
    }
inputDelValue()
inputDelValue ($key, $value, $parent = NULL)
Deletes the given value from the given key.
If the number of values drops to 1, we convert the values from array to simple value.
If a $parent is supplied, we use it as the parent of the given key.
Parameters
string $key Key to delete the value from.
string $value Value to delete.
string $parent Parent of the given key.
Todo:
After unseting, should we also update the keys in the array?
Definition at line 527 of file Rule.php.
    {
        $rule= &$this->rule;
        if ($parent !== NULL) {
            $rule= &$this->rule[$parent];
        }
        if (is_array($rule[$key])) {
            $index= array_search($value, $rule[$key]);
            if ($index !== FALSE) {
                unset($rule[$key][$index]);
            }
            FlattenArray($rule[$key]);
        } else {
            unset($rule[$key]);
        }
    }
References FlattenArray().
inputInterface()
inputInterface ()
Deletes or adds interface definitions.
This is an example that all such inputs should have matching delete links and add input boxes.
Todo:
We should force such dependencies: If there is addInterface, then delInterface should exist.
Reimplemented in Filter.
Definition at line 607 of file Rule.php.
    {
        $this->inputDel('interface', 'delInterface');
        $this->inputAdd('interface', 'addInterface');
    }
inputKey()
inputKey ($key, $parent = NULL)
Gets the value of the given POST input key.
If a $parent is supplied, we use it as the parent of the given key.
Note that we use 'state' POST input variable to make sure if the submit form on the edit page has been used or not. All edit pages have 'state' var as hidden input of the submit form. Otherwise, the rules page has submit forms using POST vars and they are visible on edit pages too. So, this is the way we differentiate the POST vars on the edit pages from the ones on the rules page.
Parameters
string $key Input key or variable to get the value of.
string $parent Parent of the given key.
Definition at line 444 of file Rule.php.
    {
        if (filter_has_var(INPUT_POST, 'state')) {
            //$value= preg_replace('/"/', '', filter_input(INPUT_POST, $key));
            $value= trim(filter_input(INPUT_POST, $key), "\" \t\n\r\0\x0B");
            if ($parent == NULL) {
                $this->rule[$key]= $value;
            } else {
                $this->rule[$parent][$key]= $value;
            }
        }
    }
inputKeyIfHasVar()
inputKeyIfHasVar ($key, $var)
Gets the value of the given POST input key, if another given key exists already.
Used to implement dependencies, e.g. between source-hash and source-hash-key
Parameters
string $key Input key or variable to get the value of.
string $var Key to check if exists.
Definition at line 487 of file Rule.php.
    {
        if (filter_has_var(INPUT_POST, 'state')) {
            if (isset($this->rule[$var])) {
                $this->rule[$key]= filter_input(INPUT_POST, $key);
            }
        }
    }
inputLog()
inputLog ()
Gets the POST input vars of log specifications.
Definition at line 616 of file Rule.php.
    {
        if (filter_has_var(INPUT_POST, 'state')) {
            $this->inputBool('log');
            if ($this->rule['log'] == TRUE) {
                if (filter_has_var(INPUT_POST, 'log-all') || filter_has_var(INPUT_POST, 'log-matches') ||
                    filter_has_var(INPUT_POST, 'log-user') || (filter_has_var(INPUT_POST, 'log-to') && filter_input(INPUT_POST, 'log-to') !== '')) {
                    $this->rule['log']= array();
                    if (filter_has_var(INPUT_POST, 'log-all')) {
                        $this->rule['log']['all']= TRUE;
                    }
                    if (filter_has_var(INPUT_POST, 'log-matches')) {
                        $this->rule['log']['matches']= TRUE;
                    }
                    if (filter_has_var(INPUT_POST, 'log-user')) {
                        $this->rule['log']['user']= TRUE;
                    }
                    if (filter_has_var(INPUT_POST, 'log-to') && filter_input(INPUT_POST, 'log-to') !== '') {
                        $this->rule['log']['to']= filter_input(INPUT_POST, 'log-to');
                    }
                }
            }
        }
    }
printHostPort()
printHostPort ($value, $noAny = TRUE, $count = 10)
Prints host or port values.
Parameters
mixed $value Value to print.
bool $noAny Whether to print 'any' or not.
int $count Max number of values to print.
Definition at line 405 of file Rule.php.
    {
        if (!is_array($value)) {
            echo $value || $noAny ? htmlentities($value) : 'any';
        } else {
            $i= 1;
            foreach ($value as $v) {
                echo htmlentities($v) . '<br>';
                if (++$i > $count) {
                    echo '+' . (count($value) - $count) . ' more entries (not displayed)<br>';
                    break;
                }
            }
        }
    }
printValue()
printValue ($value, $pre = '', $post = '', $count = 10)
Prints the given value(s).
Parameters
mixed $value Value to print.
string $pre Prefix to print.
string $post Postfix to print.
int $count Max number of values to print.
Definition at line 353 of file Rule.php.
    {
        if ($value) {
            if (!is_array($value)) {
                // Add <br> to call this function twice
                echo "$pre$value$post<br>";
            } else {
                $i= 1;
                foreach ($value as $v) {
                    echo "$pre$v$post<br>";
                    if (++$i > $count) {
                        echo '+' . (count($value) - $count) . ' more entries (not displayed)<br>';
                        break;
                    }
                }
            }
        }
    }
setType()
setType ()
Sets the type of certain Translation rules.
The 'type' key keeps the translation type of such rules. We set the value of this key to either the rule type itself or the translation type of certain rules, such as Route. Also note that, we need a default type for Route rules, so such rules set this to one of the possible translation types they allow, when they are first created.
Reimplemented in AfTo, BinatTo, DivertPacket, DivertTo, NatTo, RdrTo, and Route.
Definition at line 91 of file Rule.php.
    {
    }
Field Documentation
$arr
$arr = array() protected
Used by certain rule types while displaying themselves on the list.
Definition at line 63 of file Rule.php.
$cat
$cat = ''
Category or type of rule.
Definition at line 35 of file Rule.php.
$editIndex
$editIndex = 0 protected
Current count of rows on edit pages.
This number changes dynamically based on the properties of the rule that the user modifies. For example, if the user sets a state, the edit page displays state options too. This is used to alternate the color of consecutive rows.
Definition at line 72 of file Rule.php.
$href
$href = '' protected
Common part of edit links.
Definition at line 50 of file Rule.php.
$ref
$ref = '' protected
Name used in href.
Definition at line 45 of file Rule.php.
$rule
$rule = array()
Internal structure of rule properties in NVP format.
Definition at line 40 of file Rule.php.
$ruleNumber
$ruleNumber = 0 protected
Rule number.
Normally rules do not know their order in the ruleset. We pass this number when necessary only. Otherwise, rules can freely move up or down in the ruleset.
Definition at line 58 of file Rule.php.
The documentation for this class was generated from the following file:
src/View/pf/lib/Rule.php