PF Firewall: Crypt_RC4 Class Reference
Crypt_RC4 Class Reference
Public Member Functions
__construct ()
Default Constructor.
Crypt_RC4 ()
PHP4 compatible Default Constructor.
isValidEngine ($engine)
Test for engine validity.
setIV ($iv)
Dummy function.
setKeyLength ($length)
Sets the key length.
encrypt ($plaintext)
Encrypts a message.
decrypt ($ciphertext)
Decrypts a message.
_setupKey ()
Setup the key (expansion)
_crypt ($text, $mode)
Encrypts or decrypts a message.
Public Member Functions inherited from Crypt_Base
__construct ($mode=CRYPT_MODE_CBC)
Default Constructor.
Crypt_Base ($mode=CRYPT_MODE_CBC)
PHP4 compatible Default Constructor.
setIV ($iv)
Sets the initialization vector.
setKeyLength ($length)
Sets the key length.
getKeyLength ()
Returns the current key length in bits.
getBlockLength ()
Returns the current block length in bits.
setKey ($key)
Sets the key.
setPassword ($password, $method='pbkdf2')
Sets the password.
encrypt ($plaintext)
Encrypts a message.
decrypt ($ciphertext)
Decrypts a message.
_openssl_ctr_process ($plaintext, &$encryptIV, &$buffer)
OpenSSL CTR Processor.
_openssl_ofb_process ($plaintext, &$encryptIV, &$buffer)
OpenSSL OFB Processor.
_openssl_translate_mode ()
phpseclib <-> OpenSSL Mode Mapper
enablePadding ()
Pad "packets".
disablePadding ()
Do not pad packets.
enableContinuousBuffer ()
Treat consecutive "packets" as if they are a continuous buffer.
disableContinuousBuffer ()
Treat consecutive packets as if they are a discontinuous buffer.
isValidEngine ($engine)
Test for engine validity.
setPreferredEngine ($engine)
Sets the preferred crypt engine.
getEngine ()
Returns the engine currently being utilized.
_setEngine ()
Sets the engine as appropriate.
_encryptBlock ($in)
Encrypts a block.
_decryptBlock ($in)
Decrypts a block.
_setupKey ()
Setup the key (expansion)
_setup ()
Setup the CRYPT_ENGINE_INTERNAL $engine.
_setupMcrypt ()
Setup the CRYPT_ENGINE_MCRYPT $engine.
_pad ($text)
Pads a string.
_unpad ($text)
Unpads a string.
_clearBuffers ()
Clears internal buffers.
_string_shift (&$string, $index=1)
String Shift.
_string_pop (&$string, $index=1)
String Pop.
_increment_str (&$var)
Increment the current string.
_setupInlineCrypt ()
Setup the performance-optimized function for de/encrypt()
_createInlineCryptFunction ($cipher_code)
Creates the performance-optimized function for en/decrypt()
& _getLambdaFunctions ()
Holds the lambda_functions table (classwide)
_hashInlineCryptFunction ($bytes)
Generates a digest from $bytes.
safe_intval ($x)
Convert float to int.
safe_intval_inline ()
eval()'able string for in-line float to int
do_nothing ()
Dummy error handler to suppress mcrypt errors.
Data Fields
$block_size = 0
$key_length = 128
$const_namespace = 'RC4'
$cipher_name_mcrypt = 'arcfour'
$use_inline_crypt = false
$key
$stream
Data Fields inherited from Crypt_Base
$mode
$block_size = 16
$key = "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
$iv
$encryptIV
$decryptIV
$continuousBuffer = false
$enbuffer
$debuffer
$enmcrypt
$demcrypt
$enchanged = true
$dechanged = true
$ecb
$cfb_init_len = 600
$changed = true
$padding = true
$paddable = false
$engine
$preferredEngine
$cipher_name_mcrypt
$cipher_name_openssl
$cipher_name_openssl_ecb
$password_default_salt = 'phpseclib/salt'
$const_namespace
$inline_crypt
$use_inline_crypt
$openssl_emulate_ctr = false
$openssl_options
$explicit_key_length = false
$skip_key_adjustment = false
Detailed Description
Definition at line 87 of file RC4.php.
Constructor & Destructor Documentation
__construct()
__construct ()
Default Constructor.
Determines whether or not the mcrypt extension should be used.
See also
Crypt_Base::Crypt_Base()
Returns
Crypt_RC4 @access public
Definition at line 164 of file RC4.php.
    {
        parent::__construct(CRYPT_MODE_STREAM);
    }
References CRYPT_MODE_STREAM.
Referenced by Crypt_RC4().
Member Function Documentation
_crypt()
_crypt ($text, $mode)
Encrypts or decrypts a message.
See also
self::encrypt()
self::decrypt() @access private
Parameters
string $text
int $mode
Returns
string $text
Definition at line 334 of file RC4.php.
    {
        if ($this->changed) {
            $this->_setup();
            $this->changed = false;
        }
        $stream = &$this->stream[$mode];
        if ($this->continuousBuffer) {
            $i = &$stream[0];
            $j = &$stream[1];
            $keyStream = &$stream[2];
        } else {
            $i = $stream[0];
            $j = $stream[1];
            $keyStream = $stream[2];
        }
        $len = strlen($text);
        for ($k = 0; $k < $len; ++$k) {
            $i = ($i + 1) & 255;
            $ksi = $keyStream[$i];
            $j = ($j + $ksi) & 255;
            $ksj = $keyStream[$j];
            $keyStream[$i] = $ksj;
            $keyStream[$j] = $ksi;
            $text[$k] = $text[$k] ^ chr($keyStream[($ksj + $ksi) & 255]);
        }
        return $text;
    }
References Crypt_Base\$mode, and Crypt_Base\_setup().
Referenced by decrypt(), and encrypt().
_setupKey()
_setupKey ()
Setup the key (expansion)
See also
Crypt_Base::_setupKey() @access private
Reimplemented from Crypt_Base.
Definition at line 303 of file RC4.php.
    {
        $key = $this->key;
        $keyLength = strlen($key);
        $keyStream = range(0, 255);
        $j = 0;
        for ($i = 0; $i < 256; $i++) {
            $j = ($j + $keyStream[$i] + ord($key[$i % $keyLength])) & 255;
            $temp = $keyStream[$i];
            $keyStream[$i] = $keyStream[$j];
            $keyStream[$j] = $temp;
        }
        $this->stream = array();
        $this->stream[CRYPT_RC4_DECRYPT] = $this->stream[CRYPT_RC4_ENCRYPT] = array(
            0, // index $i
            0, // index $j
            $keyStream
        );
    }
References CRYPT_RC4_DECRYPT, and CRYPT_RC4_ENCRYPT.
Crypt_RC4()
Crypt_RC4 ()
PHP4 compatible Default Constructor.
See also
self::__construct() @access public
Definition at line 175 of file RC4.php.
    {
        $this->__construct();
    }
References __construct().
decrypt()
decrypt ($ciphertext)
Decrypts a message.
$this->decrypt($this->encrypt($plaintext)) == $this->encrypt($this->encrypt($plaintext)). At least if the continuous buffer is disabled.
See also
Crypt_Base::encrypt()
self::_crypt() @access public
Parameters
string $ciphertext
Returns
string $plaintext
Reimplemented from Crypt_Base.
Definition at line 288 of file RC4.php.
    {
        if ($this->engine != CRYPT_ENGINE_INTERNAL) {
            return parent::decrypt($ciphertext);
        }
        return $this->_crypt($ciphertext, CRYPT_RC4_DECRYPT);
    }
References _crypt(), CRYPT_ENGINE_INTERNAL, and CRYPT_RC4_DECRYPT.
encrypt()
encrypt ($plaintext)
Encrypts a message.
See also
Crypt_Base::decrypt()
self::_crypt() @access public
Parameters
string $plaintext
Returns
string $ciphertext
Reimplemented from Crypt_Base.
Definition at line 268 of file RC4.php.
    {
        if ($this->engine != CRYPT_ENGINE_INTERNAL) {
            return parent::encrypt($plaintext);
        }
        return $this->_crypt($plaintext, CRYPT_RC4_ENCRYPT);
    }
References _crypt(), CRYPT_ENGINE_INTERNAL, and CRYPT_RC4_ENCRYPT.
isValidEngine()
isValidEngine ($engine)
Test for engine validity.
This is mainly just a wrapper to set things up for Crypt_Base::isValidEngine()
See also
Crypt_Base::Crypt_Base()
Parameters
int $engine @access public
Returns
bool
Reimplemented from Crypt_Base.
Definition at line 190 of file RC4.php.
    {
        if ($engine == CRYPT_ENGINE_OPENSSL) {
            if (version_compare(PHP_VERSION, '5.3.7') >= 0) {
                $this->cipher_name_openssl = 'rc4-40';
            } else {
                switch (strlen($this->key)) {
                    case 5:
                        $this->cipher_name_openssl = 'rc4-40';
                        break;
                    case 8:
                        $this->cipher_name_openssl = 'rc4-64';
                        break;
                    case 16:
                        $this->cipher_name_openssl = 'rc4';
                        break;
                    default:
                        return false;
                }
            }
        }
        return parent::isValidEngine($engine);
    }
References Crypt_Base\$engine, CRYPT_ENGINE_OPENSSL, and PHP_VERSION.
setIV()
setIV ($iv)
Dummy function.
Some protocols, such as WEP, prepend an "initialization vector" to the key, effectively creating a new key [1]. If you need to use an initialization vector in this manner, feel free to prepend it to the key, yourself, before calling setKey().
[1] WEP's initialization vectors (IV's) are used in a somewhat insecure way. Since, in that protocol, the IV's are relatively easy to predict, an attack described by Scott Fluhrer, Itsik Mantin, and Adi Shamir can be used to quickly guess at the rest of the key. The following links elaborate:
http://www.rsa.com/rsalabs/node.asp?id=2009 http://en.wikipedia.org/wiki/Related_key_attack
Parameters
string $iv
See also
self::setKey() @access public
Reimplemented from Crypt_Base.
Definition at line 234 of file RC4.php.
    {
    }
setKeyLength()
setKeyLength ($length)
Sets the key length.
Keys can be between 1 and 256 bytes long.
@access public
Parameters
int $length
Reimplemented from Crypt_Base.
Definition at line 246 of file RC4.php.
    {
        if ($length < 8) {
            $this->key_length = 1;
        } elseif ($length > 2048) {
            $this->key_length = 256;
        } else {
            $this->key_length = $length >> 3;
        }
        parent::setKeyLength($length);
    }
Field Documentation
$block_size
$block_size = 0
Definition at line 99 of file RC4.php.
$cipher_name_mcrypt
$cipher_name_mcrypt = 'arcfour'
Definition at line 126 of file RC4.php.
$const_namespace
$const_namespace = 'RC4'
Definition at line 117 of file RC4.php.
$key
$key
Definition at line 144 of file RC4.php.
$key_length
$key_length = 128
Definition at line 108 of file RC4.php.
$stream
$stream
Definition at line 153 of file RC4.php.
$use_inline_crypt
$use_inline_crypt = false
Definition at line 135 of file RC4.php.
The documentation for this class was generated from the following file:
src/View/lib/phpseclib/Crypt/RC4.php