PF Firewall: System_SSH_Agent_Identity Class Reference
System_SSH_Agent_Identity Class Reference
Public Member Functions
__construct ($fsock)
Default Constructor.
System_SSH_Agent_Identity ($fsock)
PHP4 compatible Default Constructor.
setPublicKey ($key)
Set Public Key.
setPublicKeyBlob ($key_blob)
Set Public Key.
getPublicKey ($format=null)
Get Public Key.
setSignatureMode ($mode)
Set Signature Mode.
setHash ($hash)
Set Hash.
sign ($message)
Create a signature.
_string_shift (&$string, $index=1)
String Shift.
Data Fields
$key
$key_blob
$fsock
$flags = 0
Detailed Description
Definition at line 107 of file Agent.php.
Constructor & Destructor Documentation
__construct()
__construct ($fsock)
Default Constructor.
Parameters
resource $fsock
Returns
System_SSH_Agent_Identity @access private
Definition at line 153 of file Agent.php.
    {
        $this->fsock = $fsock;
    }
References $fsock.
Referenced by System_SSH_Agent_Identity().
Member Function Documentation
_string_shift()
_string_shift (& $string, $index = 1)
String Shift.
Inspired by array_shift
Parameters
string $string
int $index
Returns
string @access private
Definition at line 312 of file Agent.php.
    {
        $substr = substr($string, 0, $index);
        $string = substr($string, $index);
        return $substr;
    }
Referenced by sign().
getPublicKey()
getPublicKey ($format = null)
Get Public Key.
Wrapper for $this->key->getPublicKey()
Parameters
int $format optional
Returns
mixed @access public
Definition at line 207 of file Agent.php.
    {
        return !isset($format) ? $this->key->getPublicKey() : $this->key->getPublicKey($format);
    }
setHash()
setHash ($hash)
Set Hash.
ssh-agent doesn't support using hashes for RSA other than SHA1
Parameters
string $hash @access public
Definition at line 233 of file Agent.php.
    {
        $this->flags = 0;
        switch ($hash) {
            case 'sha1':
                break;
            case 'sha256':
                $this->flags = SYSTEM_SSH_AGENT_RSA2_256;
                break;
            case 'sha512':
                $this->flags = SYSTEM_SSH_AGENT_RSA2_512;
                break;
            default:
                user_error('The only supported hashes for RSA are sha1, sha256 and sha512');
        }
    }
References SYSTEM_SSH_AGENT_RSA2_256, and SYSTEM_SSH_AGENT_RSA2_512.
setPublicKey()
setPublicKey ($key)
Set Public Key.
Called by System_SSH_Agent::requestIdentities()
Parameters
Crypt_RSA $key @access private
Definition at line 178 of file Agent.php.
    {
        $this->key = $key;
        $this->key->setPublicKey();
    }
References $key.
setPublicKeyBlob()
setPublicKeyBlob ($key_blob)
Set Public Key.
Called by System_SSH_Agent::requestIdentities(). The key blob could be extracted from $this->key but this saves a small amount of computation.
Parameters
string $key_blob @access private
Definition at line 193 of file Agent.php.
    {
        $this->key_blob = $key_blob;
    }
References $key_blob.
setSignatureMode()
setSignatureMode ($mode)
Set Signature Mode.
Doesn't do anything as ssh-agent doesn't let you pick and choose the signature mode. ie. ssh-agent's only supported mode is CRYPT_RSA_SIGNATURE_PKCS1
Parameters
int $mode @access public
Definition at line 221 of file Agent.php.
    {
    }
sign()
sign ($message)
Create a signature.
See "2.6.2 Protocol 2 private key signature request"
Parameters
string $message
Returns
string @access public
Definition at line 259 of file Agent.php.
    {
        // the last parameter (currently 0) is for flags and ssh-agent only defines one flag (for ssh-dss): SSH_AGENT_OLD_SIGNATURE
        $packet = pack('CNa*Na*N', SYSTEM_SSH_AGENTC_SIGN_REQUEST, strlen($this->key_blob), $this->key_blob, strlen($message), $message, $this->flags);
        $packet = pack('Na*', strlen($packet), $packet);
        if (strlen($packet) != fputs($this->fsock, $packet)) {
            user_error('Connection closed during signing');
            return false;
        }
        $temp = fread($this->fsock, 4);
        if (strlen($temp) != 4) {
            user_error('Connection closed during signing');
            return false;
        }
        $length = current(unpack('N', $temp));
        $type = ord(fread($this->fsock, 1));
        if ($type != SYSTEM_SSH_AGENT_SIGN_RESPONSE) {
            user_error('Unable to retreive signature');
            return false;
        }
        $signature_blob = fread($this->fsock, $length - 1);
        if (strlen($signature_blob) != $length - 1) {
            user_error('Connection closed during signing');
            return false;
        }
        $length = current(unpack('N', $this->_string_shift($signature_blob, 4)));
        if ($length != strlen($signature_blob)) {
            user_error('Malformed signature blob');
            return false;
        }
        $length = current(unpack('N', $this->_string_shift($signature_blob, 4)));
        if ($length > strlen($signature_blob) + 4) {
            user_error('Malformed signature blob');
            return false;
        }
        $type = $this->_string_shift($signature_blob, $length);
        $this->_string_shift($signature_blob, 4);
        return $signature_blob;
    }
References _string_shift(), SYSTEM_SSH_AGENT_SIGN_RESPONSE, and SYSTEM_SSH_AGENTC_SIGN_REQUEST.
System_SSH_Agent_Identity()
System_SSH_Agent_Identity ($fsock)
PHP4 compatible Default Constructor.
See also
self::__construct()
Parameters
resource $fsock @access public
Definition at line 165 of file Agent.php.
    {
        $this->__construct($fsock);
    }
References __construct().
Field Documentation
$flags
$flags = 0
Definition at line 144 of file Agent.php.
$fsock
$fsock
Definition at line 134 of file Agent.php.
Referenced by __construct().
$key
$key
Definition at line 116 of file Agent.php.
Referenced by setPublicKey().
$key_blob
$key_blob
Definition at line 125 of file Agent.php.
Referenced by setPublicKeyBlob().
The documentation for this class was generated from the following file:
src/View/lib/phpseclib/System/SSH/Agent.php