PF Firewall: RuleSet Class Reference
RuleSet Class Reference
Loads and maintains rules.
Public Member Functions
load ($filename, $tmp=0, $force=0, $tmpFilename='')
Loads the rules in a given file.
loadArray ($rulesArray)
Loads the rules from a given rules array.
deleteRules ()
up ($ruleNumber)
Moves a rule up in the ruleset.
down ($ruleNumber)
Moves a rule down in the ruleset.
del ($ruleNumber)
Deletes a rule from the ruleset.
move ($ruleNumber, $moveTo)
Moves a rule to another location in the ruleset.
add ($ruleNumber=0)
Adds an empty rule location to the ruleset.
comment ($ruleNumber)
uncomment ($ruleNumber)
separate ($ruleNumber)
parse ()
computeNewRuleNumber ($ruleNumber=0)
Computes the actual rule number which can be allocated.
nextRuleNumber ()
Returns the number of a new rule to be appended to the end of the ruleset.
setupEditSession ($cat, &$action, &$ruleNumber)
Sets the current state of the edit page and sets up the session vars.
test ($ruleNumber, $ruleObj)
Tests the given rule.
cancel ()
Cancels the edit session.
save ($action, $ruleNumber, $ruleObj, $testResult)
Saves the modified rule.
isModified ($ruleNumber, $ruleObj)
Checks if the rule is modified.
getQueueNames ()
Returns the list of queues defined in the current ruleset.
Data Fields
$filename = ''
The name of the currently loaded file.
$uploaded = FALSE
Whether the file is uploaded or not.
$rules = array()
The list holding the ruleset.
Detailed Description
Loads and maintains rules.
Definition at line 48 of file RuleSet.php.
Member Function Documentation
add()
add ($ruleNumber = 0)
Adds an empty rule location to the ruleset.
Parameters
int $ruleNumber The location of the new rule.
Returns
int The actual rule location allocated.
Attention
We cannot simply insert an empty array(), array_merge() discards it
Definition at line 210 of file RuleSet.php.
    {
        if (count($this->rules) == 0 || ($ruleNumber >= $this->nextRuleNumber())) {
            // Add the first rule or append a new one to the end
            array_push($this->rules, array());
            return $this->nextRuleNumber();
        } else {
            // Insert a new rule in the middle
            $head= array_slice($this->rules, 0, $ruleNumber);
            $tail= array_slice($this->rules, $ruleNumber);
            // hence insert an array with an empty string element, which will be overwritten by the caller
            // or we could use array_push($head, array()) instead
            $this->rules= array_merge($head, array(''), $tail);
            return $ruleNumber;
        }
    }
cancel()
cancel ()
Cancels the edit session.
First checks if the user has clicked the Cancel button.
Todo:
Make conf.php a parameter
Definition at line 477 of file RuleSet.php.
    {
        if (filter_has_var(INPUT_POST, 'cancel') && (filter_input(INPUT_POST, 'cancel') == _CONTROL('Cancel'))) {
            unset($_SESSION['edit']);
            header('Location: /pf/conf.php');
            exit;
        }
    }
References $_SESSION, _CONTROL(), and exit.
comment()
comment ($ruleNumber)
Attention
Inline rules are multi-line, hence implode.
Definition at line 228 of file RuleSet.php.
    {
        global $View;
        $retval= $View->Controller($output, 'GenerateRule', json_encode($this->rules[$ruleNumber]), $ruleNumber, 1);
        if (!$retval) {
            PrintHelpWindow(_NOTICE('ERROR') . ': ' . _NOTICE('Cannot generate rule'), 'auto', 'ERROR');
        }
        $output= explode("\n", trim(implode("\n", $output)));
        for ($i= 0; $i < count($output); $i++) {
            $output[$i]= '# '.trim($output[$i]);
        }
        $ruleStr= implode("\n", $output);
        unset($output);
        $rulesArray= array();
        $retval= $View->Controller($output, 'ParseRules', json_encode($ruleStr), 1);
        if (!$retval) {
            PrintHelpWindow(_NOTICE('ERROR') . ': ' . _NOTICE('Cannot parse rules'), 'auto', 'ERROR');
        }
        $rulesArray= json_decode($output[0], TRUE)['rules'];
        $ruleSet= new RuleSet();
        $ruleSet->loadArray($rulesArray);
        unset($this->rules[$ruleNumber]);
        // array_slice() takes care of possible off-by-one error due to unset above
        $head= array_slice($this->rules, 0, $ruleNumber);
        $tail= array_slice($this->rules, $ruleNumber);
        $this->rules= array_merge($head, $ruleSet->rules, $tail);
    }
References $retval, $View, _NOTICE(), and PrintHelpWindow().
computeNewRuleNumber()
computeNewRuleNumber ($ruleNumber = 0)
Computes the actual rule number which can be allocated.
Parameters
int $ruleNumber The rule number requested.
Returns
int Actual rule number which can be allocated.
Definition at line 351 of file RuleSet.php.
    {
        if (count($this->rules) == 0 || ($ruleNumber >= $this->nextRuleNumber())) {
            // Add the first rule or append a new one to the end
            return $this->nextRuleNumber();
        } else {
            // Insert a new rule in the middle
            return $ruleNumber;
        }
    }
del()
del ($ruleNumber)
Deletes a rule from the ruleset.
Attention
We slice the array to update the keys, otherwise the unset() call leaves a hole in the ruleset indeces.
Parameters
int $ruleNumber The number of the rule to delete.
Definition at line 172 of file RuleSet.php.
    {
        unset($this->rules[$ruleNumber]);
        // Fake slice to update the keys
        $this->rules= array_slice($this->rules, 0);
    }
deleteRules()
deleteRules ()
Definition at line 128 of file RuleSet.php.
    {
        $this->rules= array();
    }
down()
down ($ruleNumber)
Moves a rule down in the ruleset.
Simply switches the places of two rules.
Parameters
int $ruleNumber The number of the rule to move down.
Definition at line 156 of file RuleSet.php.
    {
        if (isset($this->rules[$ruleNumber + 1])) {
            $tmp= $this->rules[$ruleNumber + 1];
            $this->rules[$ruleNumber + 1]= $this->rules[$ruleNumber];
            $this->rules[$ruleNumber]= $tmp;
        }
    }
getQueueNames()
getQueueNames ()
Returns the list of queues defined in the current ruleset.
Returns
array List of queues.
Definition at line 559 of file RuleSet.php.
    {
        $queues= array();
        foreach ($this->rules as $ruleObj) {
            if  ($ruleObj->cat == 'Queue' && isset($ruleObj->rule['name'])) {
                $queues[]= $ruleObj->rule['name'];
            }
        }
        return $queues;
    }
References $queues.
isModified()
isModified ($ruleNumber, $ruleObj)
Checks if the rule is modified.
First checks if the rule already exists in the ruleset, i.e. the user is editing an existing rule. Otherwise, we always return TRUE for new rules.
We sort the keys because the modification of the rule on the edit page may result in different key orders.
Serialization allows for an easy comparison of the rules.
Parameters
int $ruleNumber Rule number.
object $ruleObj Rule object to check.
Returns
bool TRUE if the rule is modified, or FALSE otherwise.
Definition at line 534 of file RuleSet.php.
    {
        $modified= TRUE;
        if (key_exists($ruleNumber, $this->rules)) {
            // Make sure keys are sorted before comparison
            $newRule= $ruleObj->rule;
            ksort($newRule);
            $origRule= $this->rules[$ruleNumber]->rule;
            ksort($origRule);
            if (serialize($newRule) === serialize($origRule)) {
                $modified= FALSE;
            }
        }
        return $modified;
    }
load()
load ($filename, $tmp = 0, $force = 0, $tmpFilename = '')
Loads the rules in a given file.
Refers to the Model to parse and create the rules array, which the Model returns as json encoded string.
$filename and $tmpFilename are displayed on rules and install pages.
Parameters
string $filename File name in the filesystem.
int $tmp Whether the file is uploaded from a browser.
int $force Whether to force loading the file even with errors.
string $tmpFilename Name if the temporary file uploaded.
Returns
bool TRUE on success, FALSE on fail.
Definition at line 79 of file RuleSet.php.
    {
        global $View;
        $retval= TRUE;
        if ($filename == '/etc/pf.conf') {
            $retval= $View->Controller($Output, 'GetRules', $filename, 0, $force);
        } else {
            $retval= $View->Controller($Output, 'GetRules', $filename, $tmp, $force);
        }
        if ($retval !== FALSE || $force) {
            if ($tmp && $tmpFilename !== '') {
                $this->filename= $tmpFilename;
                // Mark uploaded files as such
                $this->uploaded= TRUE;
            } else {
                $this->filename= $filename;
                $this->uploaded= FALSE;
            }
            $rulesArray= json_decode($Output[0], TRUE)['rules'];
        } else {
            return FALSE;
        }
        $this->loadArray($rulesArray);
        return TRUE;
    }
References $force, $Output, $retval, and $View.
loadArray()
loadArray ($rulesArray)
Loads the rules from a given rules array.
First, we delete the rules list, then create the rule objects. A simple assignment of rule structure to the rules member var is sufficient.
Parameters
array $rulesArray Rules in an array.
Definition at line 117 of file RuleSet.php.
    {
        $this->deleteRules();
        foreach ($rulesArray as $ruleDef) {
            $cat= __NAMESPACE__ . '\\' . $ruleDef['cat'];
            $ruleObj= new $cat();
            $ruleObj->rule= $ruleDef['rule'];
            $this->rules[]= $ruleObj;
        }
    }
move()
move ($ruleNumber, $moveTo)
Moves a rule to another location in the ruleset.
Parameters
int $ruleNumber The number of the rule to move.
int $moveTo The location to move the rule to.
Definition at line 185 of file RuleSet.php.
    {
        if ($ruleNumber < 0 || $ruleNumber >= count($this->rules)) {
            PrintHelpWindow(_NOTICE('FAILED') . ': ' . _NOTICE('Invalid rule number') . ": $ruleNumber", 'auto', 'ERROR');
            return;
        }
        if ($moveTo < 0 || $moveTo >= count($this->rules) || $ruleNumber == $moveTo) {
            PrintHelpWindow(_NOTICE('FAILED') . ': ' . _NOTICE('Invalid destination rule number') . ": $moveTo", 'auto', 'ERROR');
            return;
        }
        $rule= $this->rules[$ruleNumber];
        unset($this->rules[$ruleNumber]);
        // array_slice() takes care of possible off-by-one error due to unset above
        $head= array_slice($this->rules, 0, $moveTo);
        $tail= array_slice($this->rules, $moveTo);
        $this->rules= array_merge($head, array($rule), $tail);
    }
References _NOTICE(), and PrintHelpWindow().
nextRuleNumber()
nextRuleNumber ()
Returns the number of a new rule to be appended to the end of the ruleset.
This is simply the count of the rules in the ruleset, because the list is zero-based.
Returns
int New rule number.
Definition at line 369 of file RuleSet.php.
    {
        return count($this->rules);
    }
parse()
parse ()
Definition at line 323 of file RuleSet.php.
    {
        global $View;
        // Merge comments by reloading rules
        $retval= $View->Controller($output, 'GenerateRules', json_encode($this->rules), 0, 1);
        if (!$retval) {
            PrintHelpWindow(_NOTICE('ERROR') . ': ' . _NOTICE('Cannot generate rules'), 'auto', 'ERROR');
        }
        $ruleStr= trim(implode("\n", $output));
        unset($output);
        $retval= $View->Controller($output, 'ParseRules', json_encode($ruleStr), 1);
        if (!$retval) {
            PrintHelpWindow(_NOTICE('ERROR') . ': ' . _NOTICE('Cannot parse rules'), 'auto', 'ERROR');
        }
        $rulesArray= json_decode($output[0], TRUE)['rules'];
        $this->loadArray($rulesArray);
    }
References $retval, $View, _NOTICE(), and PrintHelpWindow().
save()
save ($action, $ruleNumber, $ruleObj, $testResult)
Saves the modified rule.
First checks if the user has clicked the Save button.
We don't save the rule if there are errors, unless the user forces saving.
We need the $action param to see if we are editing an existing rule or adding a new one. So if the user was editing a new rule, it does not exist in the ruleset yet. Because we do not modify the ruleset until the rule is saved.
Parameters
string $action Current state of the edit page.
int $ruleNumber Rule number.
object $ruleObj Modified rule object to save.
bool $testResult Test result of the rule.
Todo:
Make conf.php a parameter
Definition at line 503 of file RuleSet.php.
    {
        if (filter_has_var(INPUT_POST, 'save') && filter_input(INPUT_POST, 'save') == _CONTROL('Save')) {
            if ($testResult || filter_input(INPUT_POST, 'forcesave')) {
                if ($action == 'create') {
                    $this->add($ruleNumber);
                }
                $this->rules[$ruleNumber]= $ruleObj;
                unset($_SESSION['edit']);
                header('Location: /pf/conf.php');
                exit;
            }
        }
    }
References $_SESSION, $testResult, _CONTROL(), and exit.
separate()
separate ($ruleNumber)
Definition at line 294 of file RuleSet.php.
    {
        global $View;
        $rulesArray= array();
        // Can be used to merge separated comments by reloading rules
        $lines= explode("\n", $this->rules[$ruleNumber]->rule['comment']);
        for ($i= 0; $i < count($lines); $i++) {
            $ruleStr= '# '.trim($lines[$i]);
            $retval= $View->Controller($parseOut, 'ParseRules', json_encode($ruleStr), 1);
            if (!$retval) {
                PrintHelpWindow(_NOTICE('ERROR') . ': ' . _NOTICE('Cannot parse rules'), 'auto', 'ERROR');
            }
            $rulesArray[]= json_decode($parseOut[0], TRUE)['rules'][0];
        }
        $ruleSet= new RuleSet();
        $ruleSet->loadArray($rulesArray);
        unset($this->rules[$ruleNumber]);
        // array_slice() takes care of possible off-by-one error due to unset above
        $head= array_slice($this->rules, 0, $ruleNumber);
        $tail= array_slice($this->rules, $ruleNumber);
        $this->rules= array_merge($head, $ruleSet->rules, $tail);
    }
References $retval, $View, _NOTICE(), and PrintHelpWindow().
setupEditSession()
setupEditSession ($cat, & $action, & $ruleNumber)
Sets the current state of the edit page and sets up the session vars.
If we change the rule number requested, perhaps because it is not a valid number in the ruleset, we change the current state to 'add'.
We change the state from 'create' to 'add' if the session properties do not match. Such a mismatch means that the user was editing a different rule previously.
If the state is 'edit' and the session variables are not set up yet, we clone the rule for editing. However, we also check if the user arrives the edit page by requesting on the address line, in which case we should make sure that the rule number exists and there was a previous edit session.
Note that the 'add' state means that we should reinitialize the session variables.
Note also that we always work on a clone of the rule, not the actual rule in the ruleset. Because we should not modify the rule until the user saves the changes s/he made.
One purpose of this state machine is that we should not reinitialize the session vars each time the user submits the edit page.
Todo:
We need a state diagram for this FSM.
Parameters
string $cat Type of the current rule to be edited.
string $action Current state of the edit page.
int $ruleNumber Rule number.
Attention
Add and del operations on multi-valued vars use GET method, so check if there is an active edit session.
Definition at line 401 of file RuleSet.php.
    {
        global $View;
        // Make sure we deal only with rule numbers possible in the current ruleset
        if (!array_key_exists($ruleNumber, $View->RuleSet->rules)) {
            $ruleNumber= $this->computeNewRuleNumber($ruleNumber);
            if ($action == 'edit') {
                $action= 'add';
            }
        }
        if ($action == 'create') {
            if (!isset($_SESSION['edit']['object']) || $_SESSION['edit']['object']->cat!= $cat || $_SESSION['edit']['ruleNumber'] != $ruleNumber) {
                $action= 'add';
            }
        }
        if ($action == 'edit') {
            if (!isset($_SESSION['edit']['object']) || $_SESSION['edit']['object']->cat != $cat || $_SESSION['edit']['ruleNumber'] != $ruleNumber ||
                $View->RuleSet->rules[$ruleNumber]->cat != $cat) {
                // The rule being edited has changed, setup a new edit session
                if (array_key_exists($ruleNumber, $View->RuleSet->rules)) {
                    // Rule exists, so clone from the ruleset
                    unset($_SESSION['edit']);
                    $_SESSION['edit']['ruleNumber']= $ruleNumber;
                    $_SESSION['edit']['object']= clone $this->rules[$ruleNumber];
                } elseif (!isset($_SESSION['edit'])) {
                    // Rule does not exists, assume add if we are not already editing a new rule
                    // Assume a new rule requested, if the page is submitted on the address line with a non-existing rule number
                    $action= 'add';
                }
            }
        }
        if ($action == 'add') {
            // Create a new rule and setup a new edit session
            // Change action state to create, so we don't come back here to reinit session
            $action= 'create';
            unset($_SESSION['edit']);
            $_SESSION['edit']['ruleNumber']= $ruleNumber;
            $cat= __NAMESPACE__ . '\\' . $cat;
            $_SESSION['edit']['object']= new $cat('');
        }
    }
References $_SESSION, and $View.
test()
test ($ruleNumber, $ruleObj)
Tests the given rule.
We create a rules array upto the rule number provided, and append the rule to be tested to the end. Note that the $ruleObj is the the clone rule modified on the edit page.
We simply use json encode and decode functions to create the rules array, because json encode function includes only the public member variables only. Note also that we pass TRUE for $assoc param, to convert objects to arrays.
Parameters
int $ruleNumber The number of the rule to test.
\View\Rule $ruleObj The rule object to test.
Returns
bool Test result returned from the Model.
Definition at line 462 of file RuleSet.php.
    {
        global $View;
        $rulesArray= array_slice(json_decode(json_encode($this), TRUE)['rules'], 0, $ruleNumber);
        $rulesArray[]= json_decode(json_encode($ruleObj), TRUE);
        return $View->Controller($Output, 'TestRules', json_encode($rulesArray));
    }
References $Output, and $View.
uncomment()
uncomment ($ruleNumber)
Definition at line 264 of file RuleSet.php.
    {
        global $View;
        $rulesArray= array();
        $retval= $View->Controller($output, 'ParseRules', json_encode($this->rules[$ruleNumber]->rule['comment']), 1);
        if (!$retval) {
            PrintHelpWindow(_NOTICE('ERROR') . ': ' . _NOTICE('Cannot parse rules'), 'auto', 'ERROR');
        }
        $rulesArray= json_decode($output[0], TRUE)['rules'];
        $ruleSet= new RuleSet();
        $ruleSet->loadArray($rulesArray);
        unset($this->rules[$ruleNumber]);
        // array_slice() takes care of possible off-by-one error due to unset above
        $head= array_slice($this->rules, 0, $ruleNumber);
        $tail= array_slice($this->rules, $ruleNumber);
        if (count($ruleSet->rules)) {
            $this->rules= array_merge($head, $ruleSet->rules, $tail);
        }
        else {
            $blank= new Blank();
            $blank->rule['blank']= "\n";
            $this->rules= array_merge($head, array($blank), $tail);
        }
    }
References $retval, $View, _NOTICE(), and PrintHelpWindow().
up()
up ($ruleNumber)
Moves a rule up in the ruleset.
Simply switches the places of two rules.
Parameters
int $ruleNumber The number of the rule to move up.
Definition at line 140 of file RuleSet.php.
    {
        if (isset($this->rules[$ruleNumber - 1])) {
            $tmp= $this->rules[$ruleNumber - 1];
            $this->rules[$ruleNumber - 1]= $this->rules[$ruleNumber];
            $this->rules[$ruleNumber]= $tmp;
        }
    }
Field Documentation
$filename
$filename = ''
The name of the currently loaded file.
Definition at line 53 of file RuleSet.php.
$rules
$rules = array()
The list holding the ruleset.
Definition at line 63 of file RuleSet.php.
$uploaded
$uploaded = FALSE
Whether the file is uploaded or not.
Definition at line 58 of file RuleSet.php.
The documentation for this class was generated from the following file:
src/View/pf/lib/RuleSet.php