PF Firewall: Option Class Reference
Option Class Reference
Public Member Functions
display ($ruleNumber, $count)
Processes inputs submitted on the edit page.
dispOption ()
input ()
Processes inputs submitted on the edit page.
edit ($ruleNumber, $modified, $testResult, $generateResult, $action)
Prints edit page.
editSelectOption ()
editBlockPolicy ()
editOptimization ()
editRulesetOptimization ()
editStatePolicy ()
editFingerprints ()
editHostid ()
editLogInterface ()
editDebug ()
editSkip ()
editReassemble ()
editSyncookies ()
Public Member Functions inherited from Rule
__construct ()
setType ()
Sets the type of certain Translation rules.
display ($ruleNumber, $count)
Processes inputs submitted on the edit page.
dispHead ($ruleNumber, $count)
Prints rule number, rule type, and line number.
countLines ()
Returns the number of extra lines.
dispTail ($ruleNumber)
Prints inline comments and edit links.
dispHeadEditLinks ($ruleNumber, $count)
Prints edit links in a cell.
dispEditLinks ($ruleNumber, $count, $up='up', $down='down', $del='del')
Prints e, u, d, and x links.
dispKey ($key, $title)
Displays the given key in a cell if its value is TRUE.
dispValue ($key, $title)
Displays the value(s) of the given key in a cell.
dispValues ($key, $title)
Displays the value(s) of the given host key in a cell.
dispInterface ()
printValue ($value, $pre='', $post='', $count=10)
Prints the given value(s).
dispLog ($colspan=1)
Displays log specification in a cell.
printHostPort ($value, $noAny=TRUE, $count=10)
Prints host or port values.
input ()
Processes inputs submitted on the edit page.
inputKey ($key, $parent=NULL)
Gets the value of the given POST input key.
inputBool ($key, $parent=NULL)
Gets the boolean value of the given POST input key.
inputKeyIfHasVar ($key, $var)
Gets the value of the given POST input key, if another given key exists already.
inputDel ($key, $var, $parent=NULL)
Gets the value of the given GET input var and deletes it from the given key.
inputDelValue ($key, $value, $parent=NULL)
Deletes the given value from the given key.
inputAdd ($key, $var, $parent=NULL)
Gets the value of the given POST input var and adds it to the given key.
inputAddValue ($key, $value, $parent=NULL)
Adds the given value to the given key.
inputInterface ()
Deletes or adds interface definitions.
inputLog ()
Gets the POST input vars of log specifications.
inputDelEmpty ($flatten=TRUE)
Deletes empty values in internal rule structure.
inputDelEmptyRecursive ($array, $flatten)
Recursively deletes empty values in NVP arrays.
edit ($ruleNumber, $modified, $testResult, $generateResult, $action)
Prints edit page.
editCheckbox ($key, $title)
Prints a checkbox for the given key, within a table row.
editText ($key, $title, $help=NULL, $size=0, $hint='')
Prints an edit box for the given key, within a table row.
editValues ($key, $title, $delName, $addName, $hint, $help=NULL, $size=0, $disabled=FALSE)
Prints delete links and input boxes for multi-valued keys, within a table row.
editHead ($modified, $testResult, $generateResult, $action)
Prints rule title, generated rule, and form header at the top of the edit page.
editTail ()
Closes the table and form on the edit page.
editInterface ()
editAf ()
editLog ()
Prints edit controls for log specifications.
editComment ()
Prints input box for inline comments.
editDeleteValueLinks ($value, $name, $prefix='', $postfix='')
Prints delete links for values.
editAddValueBox ($id, $label, $hint, $size=0, $disabled=FALSE)
Prints add input box for values.
editHelp ($label)
Prints help image with a link to an anchor in pf.conf man page.
Additional Inherited Members
Data Fields inherited from Rule
$cat = ''
Category or type of rule.
$rule = array()
Internal structure of rule properties in NVP format.
Protected Attributes inherited from Rule
$ref = ''
Name used in href.
$href = ''
Common part of edit links.
$ruleNumber = 0
Rule number.
$arr = array()
Used by certain rule types while displaying themselves on the list.
$editIndex = 0
Current count of rows on edit pages.
Detailed Description
Definition at line 23 of file Option.php.
Member Function Documentation
display()
display ($ruleNumber, $count)
Processes inputs submitted on the edit page.
All child classes should override this method.
Parameters
int $ruleNumber Rule number.
int $count Number of rules in the ruleset.
Reimplemented from Rule.
Definition at line 25 of file Option.php.
    {
        $this->dispHead($ruleNumber, $count);
        $this->dispOption();
        $this->dispTail($ruleNumber);
    }
dispOption()
dispOption ()
Definition at line 32 of file Option.php.
    {
        ?>
        <td title="<?php echo _TITLE('Option') ?>" colspan="12">
            <?php
            if (isset($this->rule['type'])) {
                $value= isset($this->rule[$this->rule['type']]) ? $this->rule[$this->rule['type']] : '';
                if (in_array($this->rule['type'], array('loginterface', 'optimization', 'ruleset-optimization', 'block-policy', 'state-policy', 'debug', 'fingerprints', 'hostid'))) {
                    echo $this->rule['type'] . ": $value";
                } elseif ($this->rule['type'] == 'skip') {
                    if (!is_array($value)) {
                        echo "skip on $value";
                    } else {
                        echo 'skip on ' . implode(', ', $value);
                    }
                } elseif ($this->rule['type'] == 'reassemble') {
                    echo $this->rule['type'] . ": $value";
                    if (isset($this->rule['no-df'])) {
                        echo ' no-df';
                    }
                } elseif ($this->rule['type'] == 'syncookies') {
                    echo $this->rule['type'] . ": $value";
                    if ($value === 'adaptive') {
                        echo ' (start ' . (isset($this->rule['start']) ? $this->rule['start'] : '') . ', end ' . (isset($this->rule['end']) ? $this->rule['end'] : '') . ')';
                    }
                }
            }
            ?>
        </td>
        <?php
    }
edit()
edit ($ruleNumber, $modified, $testResult, $generateResult, $action)
Prints edit page.
All child classes should override this method.
Parameters
int $ruleNumber Rule number.
bool $modified Whether the rule is modified or not.
bool $testResult Test result.
bool $generateResult Rule generation result.
string $action Current state of the edit page.
Todo:
Should we disable the Save button by turning $modified off?
Reimplemented from Rule.
Definition at line 86 of file Option.php.
    {
        $this->editIndex= 0;
        $this->ruleNumber= $ruleNumber;
        $this->editHead($modified, $testResult, $generateResult, $action);
        if (filter_has_var(INPUT_POST, 'state') && filter_has_var(INPUT_POST, 'type')) {
            $this->rule['type']= filter_input(INPUT_POST, 'type');
        }
        if (!isset($this->rule['type'])) {
            $this->editSelectOption();
            // Otherwise, the user can save a blank option rule. But this may not be a mistake.
            //$modified= FALSE;
        }
        $this->editBlockPolicy();
        $this->editOptimization();
        $this->editRulesetOptimization();
        $this->editStatePolicy();
        $this->editFingerprints();
        $this->editHostid();
        $this->editLogInterface();
        $this->editDebug();
        $this->editSkip();
        $this->editReassemble();
        $this->editSyncookies();
        if (isset($this->rule['type'])) {
            $this->editComment();
        }
        $this->editTail();
    }
References $testResult.
editBlockPolicy()
editBlockPolicy ()
Definition at line 148 of file Option.php.
    {
        if (isset($this->rule['type']) && $this->rule['type'] == 'block-policy') {
            ?>
            <tr class="<?php echo ($this->editIndex++ % 2 ? 'evenline' : 'oddline'); ?>">
                <td class="title">
                    <?php echo _TITLE('Block Policy').':' ?>
                </td>
                <td>
                    <select id="block-policy" name="block-policy">
                        <option value="drop" label="drop" <?php echo (isset($this->rule['block-policy']) && $this->rule['block-policy'] == 'drop' ? 'selected' : ''); ?>>drop</option>
                        <option value="return" label="return" <?php echo (isset($this->rule['block-policy']) && $this->rule['block-policy'] == 'return' ? 'selected' : ''); ?>>return</option>
                    </select>
                    <?php $this->editHelp('block-policy') ?>
                </td>
            </tr>
            <?php
        }
    }
References _TITLE().
editDebug()
editDebug ()
Definition at line 283 of file Option.php.
    {
        if (isset($this->rule['type']) && $this->rule['type'] == 'debug') {
            ?>
            <tr class="<?php echo ($this->editIndex++ % 2 ? 'evenline' : 'oddline'); ?>">
                <td class="title">
                    <?php echo _TITLE('Debug').':' ?>
                </td>
                <td>
                    <select id="debug" name="debug">
                        <option value="emerg" <?php echo (isset($this->rule['debug']) && $this->rule['debug'] == 'emerg' ? 'selected' : ''); ?>>emerg</option>
                        <option value="alert" <?php echo (isset($this->rule['debug']) && $this->rule['debug'] == 'alert' ? 'selected' : ''); ?>>alert</option>
                        <option value="crit" <?php echo (isset($this->rule['debug']) && $this->rule['debug'] == 'crit' ? 'selected' : ''); ?>>crit</option>
                        <option value="err" <?php echo (isset($this->rule['debug']) && $this->rule['debug'] == 'err' ? 'selected' : ''); ?>>err</option>
                        <option value="warning" <?php echo (isset($this->rule['debug']) && $this->rule['debug'] == 'warning' ? 'selected' : ''); ?>>warning</option>
                        <option value="notice" <?php echo (isset($this->rule['debug']) && $this->rule['debug'] == 'notice' ? 'selected' : ''); ?>>notice</option>
                        <option value="info" <?php echo (isset($this->rule['debug']) && $this->rule['debug'] == 'info' ? 'selected' : ''); ?>>info</option>
                        <option value="debug" <?php echo (isset($this->rule['debug']) && $this->rule['debug'] == 'debug' ? 'selected' : ''); ?>>debug</option>
                    </select>
                    <?php $this->editHelp('debug') ?>
                </td>
            </tr>
            <?php
        }
    }
References _TITLE(), and warning().
editFingerprints()
editFingerprints ()
Definition at line 232 of file Option.php.
    {
        if (isset($this->rule['type']) && $this->rule['type'] == 'fingerprints') {
            ?>
            <tr class="<?php echo ($this->editIndex++ % 2 ? 'evenline' : 'oddline'); ?>">
                <td class="title">
                    <?php echo _TITLE('Fingerprints File').':' ?>
                </td>
                <td>
                    <input type="text" size="50" id="fingerprints" name="fingerprints" value="<?php echo isset($this->rule['fingerprints']) ? $this->rule['fingerprints'] : ''; ?>" placeholder="<?php echo _CONTROL('filename') ?>"/>
                    <?php $this->editHelp('fingerprints') ?>
                </td>
            </tr>
            <?php
        }
    }
References _TITLE().
editHostid()
editHostid ()
Definition at line 249 of file Option.php.
    {
        if (isset($this->rule['type']) && $this->rule['type'] == 'hostid') {
            ?>
            <tr class="<?php echo ($this->editIndex++ % 2 ? 'evenline' : 'oddline'); ?>">
                <td class="title">
                    <?php echo _TITLE('Host Id').':' ?>
                </td>
                <td>
                    <input type="text" size="20" id="hostid" name="hostid" value="<?php echo isset($this->rule['hostid']) ? $this->rule['hostid'] : ''; ?>"  placeholder="<?php echo _CONTROL('number') ?>"/>
                    <?php $this->editHelp('hostid') ?>
                </td>
            </tr>
            <?php
        }
    }
References _TITLE().
editLogInterface()
editLogInterface ()
Definition at line 266 of file Option.php.
    {
        if (isset($this->rule['type']) && $this->rule['type'] == 'loginterface') {
            ?>
            <tr class="<?php echo ($this->editIndex++ % 2 ? 'evenline' : 'oddline'); ?>">
                <td class="title">
                    <?php echo _TITLE('Log Interface').':' ?>
                </td>
                <td>
                    <input type="text" size="10" id="loginterface" name="loginterface" value="<?php echo isset($this->rule['loginterface']) ? $this->rule['loginterface'] : ''; ?>"  placeholder="<?php echo _CONTROL('interface') ?>"/>
                    <?php $this->editHelp('loginterface') ?>
                </td>
            </tr>
            <?php
        }
    }
References _TITLE().
editOptimization()
editOptimization ()
Definition at line 168 of file Option.php.
    {
        if (isset($this->rule['type']) && $this->rule['type'] == 'optimization') {
            ?>
            <tr class="<?php echo ($this->editIndex++ % 2 ? 'evenline' : 'oddline'); ?>">
                <td class="title">
                    <?php echo _TITLE('Optimization').':' ?>
                </td>
                <td>
                    <select id="optimization" name="optimization">
                        <option value="normal" <?php echo (isset($this->rule['optimization']) && $this->rule['optimization'] == 'normal' ? 'selected' : ''); ?>>normal</option>
                        <option value="high-latency" <?php echo (isset($this->rule['optimization']) && $this->rule['optimization'] == 'high-latency' ? 'selected' : ''); ?>>high-latency</option>
                        <option value="satellite" <?php echo (isset($this->rule['optimization']) && $this->rule['optimization'] == 'satellite' ? 'selected' : ''); ?>>satellite</option>
                        <option value="aggressive" <?php echo (isset($this->rule['optimization']) && $this->rule['optimization'] == 'aggressive' ? 'selected' : ''); ?>>aggressive</option>
                        <option value="conservative" <?php echo (isset($this->rule['optimization']) && $this->rule['optimization'] == 'conservative' ? 'selected' : ''); ?>>conservative</option>
                    </select>
                    <?php $this->editHelp('optimization') ?>
                </td>
            </tr>
            <?php
        }
    }
References _TITLE().
editReassemble()
editReassemble ()
Definition at line 331 of file Option.php.
    {
        if (isset($this->rule['type']) && $this->rule['type'] == 'reassemble') {
            ?>
            <tr class="<?php echo ($this->editIndex++ % 2 ? 'evenline' : 'oddline'); ?>">
                <td class="title">
                    <?php echo _TITLE('Reassemble').':' ?>
                </td>
                <td>
                    <select id="reassemble" name="reassemble">
                        <option value="yes" <?php echo (isset($this->rule['reassemble']) && $this->rule['reassemble'] == 'yes' ? 'selected' : ''); ?>><?php echo _CONTROL('yes') ?></option>
                        <option value="no" <?php echo (isset($this->rule['reassemble']) && $this->rule['reassemble'] == 'no' ? 'selected' : ''); ?>><?php echo _CONTROL('no') ?></option>
                    </select>
                    <?php $this->editHelp('reassemble') ?>
                    <input type="checkbox" id="no-df" name="no-df" value="no-df" <?php echo (isset($this->rule['no-df']) && $this->rule['no-df'] ? 'checked' : ''); ?> />
                    <label for="no-df">no-df</label>
                </td>
            </tr>
            <?php
        }
    }
References _CONTROL(), and _TITLE().
editRulesetOptimization()
editRulesetOptimization ()
Definition at line 191 of file Option.php.
    {
        if (isset($this->rule['type']) && $this->rule['type'] == 'ruleset-optimization') {
            ?>
            <tr class="<?php echo ($this->editIndex++ % 2 ? 'evenline' : 'oddline'); ?>">
                <td class="title">
                    <?php echo _TITLE('Ruleset Optimization').':' ?>
                </td>
                <td>
                    <select id="ruleset-optimization" name="ruleset-optimization">
                        <option value="none" <?php echo (isset($this->rule['ruleset-optimization']) && $this->rule['ruleset-optimization'] == 'none' ? 'selected' : ''); ?>>none</option>
                        <option value="basic" <?php echo (isset($this->rule['ruleset-optimization']) && $this->rule['ruleset-optimization'] == 'basic' ? 'selected' : ''); ?>>basic</option>
                        <option value="profile" <?php echo (isset($this->rule['ruleset-optimization']) && $this->rule['ruleset-optimization'] == 'profile' ? 'selected' : ''); ?>>profile</option>
                    </select>
                    <?php $this->editHelp('ruleset-optimization') ?>
                </td>
            </tr>
            <?php
        }
    }
References _TITLE().
editSelectOption()
editSelectOption ()
Definition at line 122 of file Option.php.
    {
        ?>
        <tr class="oddline">
            <td class="title">
                <?php echo _TITLE('Select Option Type').':' ?>
            </td>
            <td>
                <select id="type" name="type">
                    <option value="block-policy" <?php echo (isset($this->rule['type']) && $this->rule['type'] == 'block-policy' ? 'selected' : ''); ?>>block-policy</option>
                    <option value="optimization" <?php echo (isset($this->rule['type']) && $this->rule['type'] == 'optimization' ? 'selected' : ''); ?>>optimization</option>
                    <option value="ruleset-optimization" <?php echo (isset($this->rule['type']) && $this->rule['type'] == 'ruleset-optimization' ? 'selected' : ''); ?>>ruleset-optimization</option>
                    <option value="state-policy" <?php echo (isset($this->rule['type']) && $this->rule['type'] == 'state-policy' ? 'selected' : ''); ?>>state-policy</option>
                    <option value="fingerprints" <?php echo (isset($this->rule['type']) && $this->rule['type'] == 'fingerprints' ? 'selected' : ''); ?>>fingerprints</option>
                    <option value="hostid" <?php echo (isset($this->rule['type']) && $this->rule['type'] == 'hostid' ? 'selected' : ''); ?>>hostid</option>
                    <option value="loginterface" <?php echo (isset($this->rule['type']) && $this->rule['type'] == 'loginterface' ? 'selected' : ''); ?>>loginterface</option>
                    <option value="debug" <?php echo (isset($this->rule['type']) && $this->rule['type'] == 'debug' ? 'selected' : ''); ?>>debug</option>
                    <option value="skip" <?php echo (isset($this->rule['type']) && $this->rule['type'] == 'skip' ? 'selected' : ''); ?>>skip</option>
                    <option value="reassemble" <?php echo (isset($this->rule['type']) && $this->rule['type'] == 'reassemble' ? 'selected' : ''); ?>>reassemble</option>
                    <option value="syncookies" <?php echo (isset($this->rule['type']) && $this->rule['type'] == 'syncookies' ? 'selected' : ''); ?>>syncookies</option>
                </select>
            </td>
        </tr>
        <?php
    }
References _TITLE().
editSkip()
editSkip ()
Definition at line 309 of file Option.php.
    {
        if (isset($this->rule['type']) && $this->rule['type'] == 'skip') {
            ?>
            <tr class="<?php echo ($this->editIndex++ % 2 ? 'evenline' : 'oddline'); ?>">
                <td class="title">
                    <?php echo _TITLE('Skip Interfaces').':' ?>
                </td>
                <td>
                    <?php
                    if (isset($this->rule['skip'])) {
                        $this->editDeleteValueLinks($this->rule['skip'], 'delSkip');
                    }
                    $this->editAddValueBox('addSkip', NULL, _CONTROL('if or macro'), 40);
                    $this->editHelp('skip');
                    ?>
                </td>
            </tr>
            <?php
        }
    }
References _CONTROL(), and _TITLE().
editStatePolicy()
editStatePolicy ()
Definition at line 212 of file Option.php.
    {
        if (isset($this->rule['type']) && $this->rule['type'] == 'state-policy') {
            ?>
            <tr class="<?php echo ($this->editIndex++ % 2 ? 'evenline' : 'oddline'); ?>">
                <td class="title">
                    <?php echo _TITLE('State Policy').':' ?>
                </td>
                <td>
                    <select id="state-policy" name="state-policy">
                        <option value="if-bound" <?php echo (isset($this->rule['state-policy']) && $this->rule['state-policy'] == 'if-bound' ? 'selected' : ''); ?>>if-bound</option>
                        <option value="floating" <?php echo (isset($this->rule['state-policy']) && $this->rule['state-policy'] == 'floating' ? 'selected' : ''); ?>>floating</option>
                    </select>
                    <?php $this->editHelp('state-policy') ?>
                </td>
            </tr>
            <?php
        }
    }
References _TITLE().
editSyncookies()
editSyncookies ()
Definition at line 353 of file Option.php.
    {
        if (isset($this->rule['type']) && $this->rule['type'] == 'syncookies') {
            ?>
            <tr class="<?php echo ($this->editIndex++ % 2 ? 'evenline' : 'oddline'); ?>">
                <td class="title">
                    <?php echo _TITLE('Syncookies').':' ?>
                </td>
                <td>
                    <select id="syncookies" name="syncookies">
                        <option value="never" <?php echo (isset($this->rule['syncookies']) && $this->rule['syncookies'] == 'never' ? 'selected' : ''); ?>><?php echo _CONTROL('never') ?></option>
                        <option value="always" <?php echo (isset($this->rule['syncookies']) && $this->rule['syncookies'] == 'always' ? 'selected' : ''); ?>><?php echo _CONTROL('always') ?></option>
                        <option value="adaptive" <?php echo (isset($this->rule['syncookies']) && $this->rule['syncookies'] == 'adaptive' ? 'selected' : ''); ?>><?php echo _CONTROL('adaptive') ?></option>
                    </select>
                    <input type="text" id="start" name="start" value="<?php echo isset($this->rule['start']) ? $this->rule['start'] : ''; ?>" size="10" placeholder="<?php echo _CONTROL('number%') ?>" <?php echo isset($this->rule['syncookies']) && $this->rule['syncookies'] !== 'adaptive' ? 'disabled' : ''; ?> />
                    <label for="start">start</label>
                    <input type="text" id="end" name="end" value="<?php echo isset($this->rule['end']) ? $this->rule['end'] : ''; ?>" size="10" placeholder="<?php echo _CONTROL('number%') ?>" <?php echo isset($this->rule['syncookies']) && $this->rule['syncookies'] !== 'adaptive' ? 'disabled' : ''; ?> />
                    <label for="end">end</label>
                    <?php $this->editHelp('syncookies') ?>
                </td>
            </tr>
            <?php
        }
    }
References _CONTROL(), and _TITLE().
input()
input ()
Processes inputs submitted on the edit page.
All child classes should override this method.
Reimplemented from Rule.
Definition at line 64 of file Option.php.
    {
        $this->inputKey('block-policy');
        $this->inputKey('optimization');
        $this->inputKey('ruleset-optimization');
        $this->inputKey('state-policy');
        $this->inputKey('fingerprints');
        $this->inputKey('hostid');
        $this->inputKey('loginterface');
        $this->inputKey('debug');
        $this->inputDel('skip', 'delSkip');
        $this->inputAdd('skip', 'addSkip');
        $this->inputKey('reassemble');
        $this->inputBool('no-df');
        $this->inputKey('syncookies');
        $this->inputKey('start');
        $this->inputKey('end');
        $this->inputKey('comment');
        $this->inputDelEmpty();
    }
The documentation for this class was generated from the following file:
src/View/pf/lib/Option.php