PF Firewall: Session Class Reference
Session Class Reference
Public Member Functions
__construct ()
getvars ()
getform ($name, $val='')
get ($n)
printoptions ($name, $options)
getformdefault ($name)
getformconstrained ($name, $value)
purge ()
_display ()
_test ()
Data Fields
$vars
Detailed Description
Definition at line 46 of file class_session.inc.
Constructor & Destructor Documentation
__construct()
__construct ()
Definition at line 49 of file class_session.inc.
{
    $this->vars = new Vars();
    }
Member Function Documentation
_display()
_display ()
Definition at line 166 of file class_session.inc.
{
    $this->vars->_display();
    }
_test()
_test ()
Definition at line 170 of file class_session.inc.
                     {
    $this->getform('end');
    $this->getform('heigth');
    $this->getform('layout');
    $this->getform('size');
    $this->getform('start');
    $this->getform('timespan');
    $this->getform('width');
    $this->getform('layout');
    }
References getform().
get()
get ($n)
Definition at line 106 of file class_session.inc.
                     {
    if ($this->vars->defp($n)) {
        return $this->vars->get($n);
    }
    }
getform()
getform ($name, $val = '')
Definition at line 57 of file class_session.inc.
{
    global $symon, $View, $Submenu;
    if (isset($_SESSION)) {
        if ($Submenu) {
            $session= &$_SESSION[$View->Model]['Graphs'][$Submenu];
        }
        else {
            $session= &$_SESSION[$View->Model]['Graphs'];
        }
    }
    if (isset($_REQUEST[$name])) {
        $value = $_REQUEST[$name];
        // POSTed values have precedence over session vars
        $session[$name]= $value;
    }
    if (isset($session[$name])) {
        $value= $session[$name];
    }
    if ($val != '') {
        $value= $val;
    }
    if (!isset($value)) {
        $value = $this->getformdefault($name);
    } else {
        $value = $this->getformconstrained($name, $value);
    }
    // Do not forget to save the new/default value to session var
    $session[$name]= $value;
    /* unroll items if named var selected */
    if ($symon['defaults'][$name]['type'] == 'named') {
        $s = $symon['defaults'][$name]['namedvalues'][$value];
        if (is_array($s)) {
        foreach ($s as $k => $v) {
            $this->vars->set($k, $v);
        }
        }
    }
    $this->vars->set($name, $value);
    return $value;
    }
References $_SESSION, $Submenu, $symon, $View, getformconstrained(), and getformdefault().
Referenced by _test().
getformconstrained()
getformconstrained ($name, $value)
Definition at line 135 of file class_session.inc.
{
    global $symon;
    if (!isset($symon['defaults'][$name])) {
        runtime_error('session: unknown variable "'.$name.'" requested');
    }
    switch ($symon['defaults'][$name]['type']) {
    case 'named':
        if (!isset($symon['defaults'][$name]['namedvalues'][$value])) {
        $value = $this->getformdefault($name);
        }
        break;
    case 'integer':
        if ($value < $symon['defaults'][$name]['bounds']['min'] ||
        $value > $symon['defaults'][$name]['bounds']['max']) {
        $value = $this->getformdefault($name);
        }
        break;
    default:
        runtime_error('session: unknown variable type "'.$symon['defaults'][$name]['type'].'" requested');
        break;
    }
    return $value;
    }
References $symon, getformdefault(), and runtime_error().
Referenced by getform().
getformdefault()
getformdefault ($name)
Definition at line 123 of file class_session.inc.
{
    global $symon;
    if (!isset($symon['defaults'][$name]['default'])) {
        runtime_error('session: unknown variable "'.$name.'" requested');
    }
    $value = $symon['defaults'][$name]['default'];
    return $value;
    }
References $symon, and runtime_error().
Referenced by getform(), and getformconstrained().
getvars()
getvars ()
Definition at line 53 of file class_session.inc.
                       {
    return $this->vars;
    }
References $vars.
printoptions()
printoptions ($name, $options)
Definition at line 112 of file class_session.inc.
{
    foreach($options as $k => $v) {
        print '    <option ';
        if ($this->vars->defp($name) &&
        $this->vars->get($name) == $k) {
        print 'selected ';
        }
        print 'value="'.$k.'">'.$v."</option>\xa";
    }
    }
References print.
purge()
purge ()
Definition at line 162 of file class_session.inc.
                     {
    $vars = new Vars();
    }
References $vars.
Field Documentation
$vars
$vars
Definition at line 47 of file class_session.inc.
Referenced by getvars(), and purge().
The documentation for this class was generated from the following file:
src/View/symon/class_session.inc