PF Firewall: Timeout Class Reference
Timeout Class Reference
Public Member Functions
display ($ruleNumber, $count)
Processes inputs submitted on the edit page.
dispTimeout ()
dispTimeoutOpts ()
input ()
Processes inputs submitted on the edit page.
inputTimeout ()
inputTimeoutOpt ($key, $var, $parent)
edit ($ruleNumber, $modified, $testResult, $generateResult, $action)
Prints edit page.
editTimeout ()
editFragment ()
editInterval ()
editSrcTrack ()
editTcpTimeouts ()
editUdpTimeouts ()
editIcmpTimeouts ()
editOtherTimeouts ()
editAdaptiveTimeouts ()
editTimeoutOpt ($timeout, $key)
Public Member Functions inherited from Rule
__construct ()
setType ()
Sets the type of certain Translation rules.
display ($ruleNumber, $count)
Processes inputs submitted on the edit page.
dispHead ($ruleNumber, $count)
Prints rule number, rule type, and line number.
countLines ()
Returns the number of extra lines.
dispTail ($ruleNumber)
Prints inline comments and edit links.
dispHeadEditLinks ($ruleNumber, $count)
Prints edit links in a cell.
dispEditLinks ($ruleNumber, $count, $up='up', $down='down', $del='del')
Prints e, u, d, and x links.
dispKey ($key, $title)
Displays the given key in a cell if its value is TRUE.
dispValue ($key, $title)
Displays the value(s) of the given key in a cell.
dispValues ($key, $title)
Displays the value(s) of the given host key in a cell.
dispInterface ()
printValue ($value, $pre='', $post='', $count=10)
Prints the given value(s).
dispLog ($colspan=1)
Displays log specification in a cell.
printHostPort ($value, $noAny=TRUE, $count=10)
Prints host or port values.
input ()
Processes inputs submitted on the edit page.
inputKey ($key, $parent=NULL)
Gets the value of the given POST input key.
inputBool ($key, $parent=NULL)
Gets the boolean value of the given POST input key.
inputKeyIfHasVar ($key, $var)
Gets the value of the given POST input key, if another given key exists already.
inputDel ($key, $var, $parent=NULL)
Gets the value of the given GET input var and deletes it from the given key.
inputDelValue ($key, $value, $parent=NULL)
Deletes the given value from the given key.
inputAdd ($key, $var, $parent=NULL)
Gets the value of the given POST input var and adds it to the given key.
inputAddValue ($key, $value, $parent=NULL)
Adds the given value to the given key.
inputInterface ()
Deletes or adds interface definitions.
inputLog ()
Gets the POST input vars of log specifications.
inputDelEmpty ($flatten=TRUE)
Deletes empty values in internal rule structure.
inputDelEmptyRecursive ($array, $flatten)
Recursively deletes empty values in NVP arrays.
edit ($ruleNumber, $modified, $testResult, $generateResult, $action)
Prints edit page.
editCheckbox ($key, $title)
Prints a checkbox for the given key, within a table row.
editText ($key, $title, $help=NULL, $size=0, $hint='')
Prints an edit box for the given key, within a table row.
editValues ($key, $title, $delName, $addName, $hint, $help=NULL, $size=0, $disabled=FALSE)
Prints delete links and input boxes for multi-valued keys, within a table row.
editHead ($modified, $testResult, $generateResult, $action)
Prints rule title, generated rule, and form header at the top of the edit page.
editTail ()
Closes the table and form on the edit page.
editInterface ()
editAf ()
editLog ()
Prints edit controls for log specifications.
editComment ()
Prints input box for inline comments.
editDeleteValueLinks ($value, $name, $prefix='', $postfix='')
Prints delete links for values.
editAddValueBox ($id, $label, $hint, $size=0, $disabled=FALSE)
Prints add input box for values.
editHelp ($label)
Prints help image with a link to an anchor in pf.conf man page.
Additional Inherited Members
Data Fields inherited from Rule
$cat = ''
Category or type of rule.
$rule = array()
Internal structure of rule properties in NVP format.
Protected Attributes inherited from Rule
$ref = ''
Name used in href.
$href = ''
Common part of edit links.
$ruleNumber = 0
Rule number.
$arr = array()
Used by certain rule types while displaying themselves on the list.
$editIndex = 0
Current count of rows on edit pages.
Detailed Description
Definition at line 23 of file Timeout.php.
Member Function Documentation
display()
display ($ruleNumber, $count)
Processes inputs submitted on the edit page.
All child classes should override this method.
Parameters
int $ruleNumber Rule number.
int $count Number of rules in the ruleset.
Reimplemented from Rule.
Reimplemented in AfTo, Anchor, DivertPacket, DivertTo, FilterBase, NatBase, Route, Scrub, and State.
Definition at line 25 of file Timeout.php.
    {
        $this->dispHead($ruleNumber, $count);
        $this->dispTimeout();
        $this->dispTail($ruleNumber);
    }
dispTimeout()
dispTimeout ()
Definition at line 32 of file Timeout.php.
    {
        ?>
        <td title="<?php echo _TITLE('Timeout') ?>" colspan="12">
            <?php
            $this->arr= array();
            $this->dispTimeoutOpts();
            echo implode(', ', $this->arr);
            ?>
        </td>
        <?php
    }
dispTimeoutOpts()
dispTimeoutOpts ()
Definition at line 45 of file Timeout.php.
    {
        if (isset($this->rule['timeout']) && count($this->rule['timeout'])) {
            reset($this->rule['timeout']);
            foreach ($this->rule['timeout'] as $timeout => $kvps) {
                $timeout= $timeout == 'all' ? '' : "$timeout.";
                foreach ($kvps as $key => $val) {
                    $this->arr[]= "$timeout$key: $val";
                }
            }
        }
    }
edit()
edit ($ruleNumber, $modified, $testResult, $generateResult, $action)
Prints edit page.
All child classes should override this method.
Parameters
int $ruleNumber Rule number.
bool $modified Whether the rule is modified or not.
bool $testResult Test result.
bool $generateResult Rule generation result.
string $action Current state of the edit page.
Reimplemented from Rule.
Reimplemented in AfTo, Anchor, DivertPacket, DivertTo, Filter, FilterBase, NatBase, NatTo, Route, Scrub, and State.
Definition at line 102 of file Timeout.php.
    {
        $this->editIndex= 0;
        $this->ruleNumber= $ruleNumber;
        $this->editHead($modified, $testResult, $generateResult, $action);
        $this->editFragment();
        $this->editInterval();
        $this->editTimeout();
        $this->editComment();
        $this->editTail();
    }
References $testResult.
editAdaptiveTimeouts()
editAdaptiveTimeouts ()
Definition at line 255 of file Timeout.php.
    {
        ?>
        <tr class="<?php echo ($this->editIndex++ % 2 ? 'evenline' : 'oddline'); ?>">
            <td class="title">
                <?php $this->editHelp('adaptive_timeout') ?><?php echo _TITLE('Adaptive Timeouts').':' ?>
            </td>
            <td>
                <table style="width: auto;">
                    <?php
                    $this->editTimeoutOpt('adaptive', 'start');
                    $this->editTimeoutOpt('adaptive', 'end');
                    ?>
                </table>
            </td>
        </tr>
        <?php
    }
References _TITLE().
editFragment()
editFragment ()
Definition at line 128 of file Timeout.php.
    {
        ?>
        <tr class="<?php echo ($this->editIndex++ % 2 ? 'evenline' : 'oddline'); ?>">
            <td class="title">
                <?php echo _TITLE('Fragment').':' ?>
            </td>
            <td>
                <input type="text" id="frag" name="frag" size="10" value="<?php echo isset($this->rule['timeout']['all']['frag']) ? $this->rule['timeout']['all']['frag'] : ''; ?>" placeholder="<?php echo _CONTROL('number') ?>" />
                <?php $this->editHelp('frag') ?>
            </td>
        </tr>
        <?php
    }
References _TITLE().
editIcmpTimeouts()
editIcmpTimeouts ()
Definition at line 216 of file Timeout.php.
    {
        ?>
        <tr class="<?php echo ($this->editIndex++ % 2 ? 'evenline' : 'oddline'); ?>">
            <td class="title">
                <?php $this->editHelp('icmp_timeout') ?><?php echo _TITLE('ICMP Timeouts').':' ?>
            </td>
            <td>
                <table style="width: auto;">
                    <?php
                    $this->editTimeoutOpt('icmp', 'first');
                    $this->editTimeoutOpt('icmp', 'error');
                    ?>
                </table>
            </td>
        </tr>
        <?php
    }
References _TITLE().
editInterval()
editInterval ()
Definition at line 143 of file Timeout.php.
    {
        ?>
        <tr class="<?php echo ($this->editIndex++ % 2 ? 'evenline' : 'oddline'); ?>">
            <td class="title">
                <?php echo _TITLE('Interval').':' ?>
            </td>
            <td>
                <input type="text" id="interval" name="interval" size="10" value="<?php echo isset($this->rule['timeout']['all']['interval']) ? $this->rule['timeout']['all']['interval'] : ''; ?>" placeholder="<?php echo _CONTROL('number') ?>" />
                <?php $this->editHelp('interval') ?>
            </td>
        </tr>
        <?php
    }
References _TITLE().
editOtherTimeouts()
editOtherTimeouts ()
Definition at line 235 of file Timeout.php.
    {
        ?>
        <tr class="<?php echo ($this->editIndex++ % 2 ? 'evenline' : 'oddline'); ?>">
            <td class="title">
                <?php $this->editHelp('other_timeout') ?><?php echo _TITLE('Other Timeouts').':' ?>
            </td>
            <td>
                <table style="width: auto;">
                    <?php
                    $this->editTimeoutOpt('other', 'first');
                    $this->editTimeoutOpt('other', 'single');
                    $this->editTimeoutOpt('other', 'multiple');
                    ?>
                </table>
            </td>
        </tr>
        <?php
    }
References _TITLE().
editSrcTrack()
editSrcTrack ()
Definition at line 158 of file Timeout.php.
    {
        ?>
        <tr class="<?php echo ($this->editIndex++ % 2 ? 'evenline' : 'oddline'); ?>">
            <td class="title">
                <?php echo _TITLE('Source Track Timeout').':' ?>
            </td>
            <td>
                <input type="text" id="src_track" name="src_track" size="10" value="<?php echo isset($this->rule['timeout']['all']['src.track']) ? $this->rule['timeout']['all']['src.track'] : ''; ?>" placeholder="<?php echo _CONTROL('number') ?>" />
                <?php $this->editHelp('src.track') ?>
            </td>
        </tr>
        <?php
    }
References _TITLE().
editTcpTimeouts()
editTcpTimeouts ()
Definition at line 173 of file Timeout.php.
    {
        ?>
        <tr class="<?php echo ($this->editIndex++ % 2 ? 'evenline' : 'oddline'); ?>">
            <td class="title">
                <?php $this->editHelp('tcp_timeout') ?><?php echo _TITLE('TCP Timeouts').':' ?>
            </td>
            <td>
                <table style="width: auto;">
                    <?php
                    $this->editTimeoutOpt('tcp', 'first');
                    $this->editTimeoutOpt('tcp', 'opening');
                    $this->editTimeoutOpt('tcp', 'established');
                    $this->editTimeoutOpt('tcp', 'closing');
                    $this->editTimeoutOpt('tcp', 'finwait');
                    $this->editTimeoutOpt('tcp', 'closed');
                    ?>
                </table>
            </td>
        </tr>
        <?php
    }
References _TITLE().
editTimeout()
editTimeout ()
Definition at line 118 of file Timeout.php.
    {
        $this->editSrcTrack();
        $this->editTcpTimeouts();
        $this->editUdpTimeouts();
        $this->editIcmpTimeouts();
        $this->editOtherTimeouts();
        $this->editAdaptiveTimeouts();
    }
editTimeoutOpt()
editTimeoutOpt ($timeout, $key)
Definition at line 274 of file Timeout.php.
    {
        ?>
        <tr>
            <td class="ifs">
                <input type="text" size="10" id="<?php echo $timeout ?>_<?php echo $key ?>" name="<?php echo $timeout ?>_<?php echo $key ?>" value="<?php echo isset($this->rule['timeout'][$timeout][$key]) ? $this->rule['timeout'][$timeout][$key] : ''; ?>" placeholder="<?php echo _CONTROL('number') ?>" />
            </td>
            <td class="optitle"><?php echo $key ?></td>
        </tr>
        <?php
    }
editUdpTimeouts()
editUdpTimeouts ()
Definition at line 196 of file Timeout.php.
    {
        ?>
        <tr class="<?php echo ($this->editIndex++ % 2 ? 'evenline' : 'oddline'); ?>">
            <td class="title">
                <?php $this->editHelp('udp_timeout') ?><?php echo _TITLE('UDP Timeouts').':' ?>
            </td>
            <td>
                <table style="width: auto;">
                    <?php
                    $this->editTimeoutOpt('udp', 'first');
                    $this->editTimeoutOpt('udp', 'single');
                    $this->editTimeoutOpt('udp', 'multiple');
                    ?>
                </table>
            </td>
        </tr>
        <?php
    }
References _TITLE().
input()
input ()
Processes inputs submitted on the edit page.
All child classes should override this method.
Reimplemented from Rule.
Reimplemented in AfTo, Anchor, DivertPacket, DivertTo, Filter, FilterBase, NatBase, NatTo, Route, Scrub, and State.
Definition at line 58 of file Timeout.php.
    {
        $this->inputTimeoutOpt('frag', 'frag', 'all');
        $this->inputTimeoutOpt('interval', 'interval', 'all');
        $this->inputTimeout();
        $this->inputKey('comment');
        $this->inputDelEmpty();
    }
inputTimeout()
inputTimeout ()
Definition at line 69 of file Timeout.php.
    {
        $this->inputTimeoutOpt('src.track', 'src_track', 'all');
        $this->inputTimeoutOpt('first', 'tcp_first', 'tcp');
        $this->inputTimeoutOpt('opening', 'tcp_opening', 'tcp');
        $this->inputTimeoutOpt('established', 'tcp_established', 'tcp');
        $this->inputTimeoutOpt('closing', 'tcp_closing', 'tcp');
        $this->inputTimeoutOpt('finwait', 'tcp_finwait', 'tcp');
        $this->inputTimeoutOpt('closed', 'tcp_closed', 'tcp');
        $this->inputTimeoutOpt('first', 'udp_first', 'udp');
        $this->inputTimeoutOpt('single', 'udp_single', 'udp');
        $this->inputTimeoutOpt('multiple', 'udp_multiple', 'udp');
        $this->inputTimeoutOpt('first', 'icmp_first', 'icmp');
        $this->inputTimeoutOpt('error', 'icmp_error', 'icmp');
        $this->inputTimeoutOpt('first', 'other_first', 'other');
        $this->inputTimeoutOpt('single', 'other_single', 'other');
        $this->inputTimeoutOpt('multiple', 'other_multiple', 'other');
        $this->inputTimeoutOpt('start', 'adaptive_start', 'adaptive');
        $this->inputTimeoutOpt('end', 'adaptive_end', 'adaptive');
    }
inputTimeoutOpt()
inputTimeoutOpt ($key, $var, $parent)
Definition at line 95 of file Timeout.php.
    {
        if (filter_has_var(INPUT_POST, 'state')) {
            $this->rule['timeout'][$parent][$key]= trim(filter_input(INPUT_POST, $var), '" ');
        }
    }
The documentation for this class was generated from the following file:
src/View/pf/lib/Timeout.php