PF Firewall: Crypt_TripleDES Class Reference
Crypt_TripleDES Class Reference
Public Member Functions
__construct ($mode=CRYPT_MODE_CBC)
Default Constructor.
Crypt_TripleDES ($mode=CRYPT_MODE_CBC)
PHP4 compatible Default Constructor.
isValidEngine ($engine)
Test for engine validity.
setIV ($iv)
Sets the initialization vector.
setKeyLength ($length)
Sets the key length.
setKey ($key)
Sets the key.
encrypt ($plaintext)
Encrypts a message.
decrypt ($ciphertext)
Decrypts a message.
enableContinuousBuffer ()
Treat consecutive "packets" as if they are a continuous buffer.
disableContinuousBuffer ()
Treat consecutive packets as if they are a discontinuous buffer.
_setupKey ()
Creates the key schedule.
setPreferredEngine ($engine)
Sets the internal crypt engine.
Public Member Functions inherited from Crypt_DES
isValidEngine ($engine)
Test for engine validity.
setKey ($key)
Sets the key.
_encryptBlock ($in)
Encrypts a block.
_decryptBlock ($in)
Decrypts a block.
_processBlock ($block, $mode)
Encrypts or decrypts a 64-bit block.
_setupKey ()
Creates the key schedule.
_setupInlineCrypt ()
Setup the performance-optimized function for de/encrypt()
Public Member Functions inherited from Crypt_Base
__construct ($mode=CRYPT_MODE_CBC)
Default Constructor.
Crypt_Base ($mode=CRYPT_MODE_CBC)
PHP4 compatible Default Constructor.
setIV ($iv)
Sets the initialization vector.
setKeyLength ($length)
Sets the key length.
getKeyLength ()
Returns the current key length in bits.
getBlockLength ()
Returns the current block length in bits.
setKey ($key)
Sets the key.
setPassword ($password, $method='pbkdf2')
Sets the password.
encrypt ($plaintext)
Encrypts a message.
decrypt ($ciphertext)
Decrypts a message.
_openssl_ctr_process ($plaintext, &$encryptIV, &$buffer)
OpenSSL CTR Processor.
_openssl_ofb_process ($plaintext, &$encryptIV, &$buffer)
OpenSSL OFB Processor.
_openssl_translate_mode ()
phpseclib <-> OpenSSL Mode Mapper
enablePadding ()
Pad "packets".
disablePadding ()
Do not pad packets.
enableContinuousBuffer ()
Treat consecutive "packets" as if they are a continuous buffer.
disableContinuousBuffer ()
Treat consecutive packets as if they are a discontinuous buffer.
isValidEngine ($engine)
Test for engine validity.
setPreferredEngine ($engine)
Sets the preferred crypt engine.
getEngine ()
Returns the engine currently being utilized.
_setEngine ()
Sets the engine as appropriate.
_encryptBlock ($in)
Encrypts a block.
_decryptBlock ($in)
Decrypts a block.
_setupKey ()
Setup the key (expansion)
_setup ()
Setup the CRYPT_ENGINE_INTERNAL $engine.
_setupMcrypt ()
Setup the CRYPT_ENGINE_MCRYPT $engine.
_pad ($text)
Pads a string.
_unpad ($text)
Unpads a string.
_clearBuffers ()
Clears internal buffers.
_string_shift (&$string, $index=1)
String Shift.
_string_pop (&$string, $index=1)
String Pop.
_increment_str (&$var)
Increment the current string.
_setupInlineCrypt ()
Setup the performance-optimized function for de/encrypt()
_createInlineCryptFunction ($cipher_code)
Creates the performance-optimized function for en/decrypt()
& _getLambdaFunctions ()
Holds the lambda_functions table (classwide)
_hashInlineCryptFunction ($bytes)
Generates a digest from $bytes.
safe_intval ($x)
Convert float to int.
safe_intval_inline ()
eval()'able string for in-line float to int
do_nothing ()
Dummy error handler to suppress mcrypt errors.
Data Fields
$key_length = 24
$password_default_salt = 'phpseclib'
$const_namespace = 'DES'
$cipher_name_mcrypt = 'tripledes'
$cfb_init_len = 750
$key_length_max = 24
$mode_3cbc
$des
Data Fields inherited from Crypt_DES
$block_size = 8
$key_length = 8
$const_namespace = 'DES'
$cipher_name_mcrypt = 'des'
$openssl_mode_names
$cfb_init_len = 500
$des_rounds = 1
$key_length_max = 8
$keys
$shuffle
$ipmap
$invipmap
$sbox1
$sbox2
$sbox3
$sbox4
$sbox5
$sbox6
$sbox7
$sbox8
Data Fields inherited from Crypt_Base
$mode
$block_size = 16
$key = "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
$iv
$encryptIV
$decryptIV
$continuousBuffer = false
$enbuffer
$debuffer
$enmcrypt
$demcrypt
$enchanged = true
$dechanged = true
$ecb
$cfb_init_len = 600
$changed = true
$padding = true
$paddable = false
$engine
$preferredEngine
$cipher_name_mcrypt
$cipher_name_openssl
$cipher_name_openssl_ecb
$password_default_salt = 'phpseclib/salt'
$const_namespace
$inline_crypt
$use_inline_crypt
$openssl_emulate_ctr = false
$openssl_options
$explicit_key_length = false
$skip_key_adjustment = false
Detailed Description
Definition at line 95 of file TripleDES.php.
Constructor & Destructor Documentation
__construct()
__construct ($mode = CRYPT_MODE_CBC)
Default Constructor.
Determines whether or not the mcrypt extension should be used.
$mode could be:
CRYPT_DES_MODE_ECB
CRYPT_DES_MODE_CBC
CRYPT_DES_MODE_CTR
CRYPT_DES_MODE_CFB
CRYPT_DES_MODE_OFB
CRYPT_DES_MODE_3CBC
If not explicitly set, CRYPT_DES_MODE_CBC will be used.
See also
Crypt_DES::Crypt_DES()
Crypt_Base::Crypt_Base()
Parameters
int $mode @access public
Reimplemented from Crypt_Base.
Definition at line 199 of file TripleDES.php.
    {
        switch ($mode) {
            // In case of CRYPT_DES_MODE_3CBC, we init as CRYPT_DES_MODE_CBC
            // and additional flag us internally as 3CBC
            case CRYPT_DES_MODE_3CBC:
                parent::Crypt_Base(CRYPT_MODE_CBC);
                $this->mode_3cbc = true;
                // This three $des'es will do the 3CBC work (if $key > 64bits)
                $this->des = array(
                    new Crypt_DES(CRYPT_MODE_CBC),
                    new Crypt_DES(CRYPT_MODE_CBC),
                    new Crypt_DES(CRYPT_MODE_CBC),
                );
                // we're going to be doing the padding, ourselves, so disable it in the Crypt_DES objects
                $this->des[0]->disablePadding();
                $this->des[1]->disablePadding();
                $this->des[2]->disablePadding();
                break;
            // If not 3CBC, we init as usual
            default:
                parent::__construct($mode);
        }
    }
References Crypt_Base\$mode, CRYPT_DES_MODE_3CBC, and CRYPT_MODE_CBC.
Referenced by Crypt_TripleDES().
Member Function Documentation
_setupKey()
_setupKey ()
Creates the key schedule.
See also
Crypt_DES::_setupKey()
Crypt_Base::_setupKey() @access private
Reimplemented from Crypt_DES.
Definition at line 470 of file TripleDES.php.
    {
        switch (true) {
            // if $key <= 64bits we configure our internal pure-php cipher engine
            // to act as regular [1]DES, not as 3DES. mcrypt.so::tripledes does the same.
            case strlen($this->key) <= 8:
                $this->des_rounds = 1;
                break;
            // otherwise, if $key > 64bits, we configure our engine to work as 3DES.
            default:
                $this->des_rounds = 3;
                // (only) if 3CBC is used we have, of course, to setup the $des[0-2] keys also separately.
                if ($this->mode_3cbc) {
                    $this->des[0]->_setupKey();
                    $this->des[1]->_setupKey();
                    $this->des[2]->_setupKey();
                    // because $des[0-2] will, now, do all the work we can return here
                    // not need unnecessary stress parent::_setupKey() with our, now unused, $key.
                    return;
                }
        }
        // setup our key
        parent::_setupKey();
    }
Crypt_TripleDES()
Crypt_TripleDES ($mode = CRYPT_MODE_CBC)
PHP4 compatible Default Constructor.
See also
self::__construct()
Parameters
int $mode @access public
Definition at line 233 of file TripleDES.php.
    {
        $this->__construct($mode);
    }
References Crypt_Base\$mode, and __construct().
decrypt()
decrypt ($ciphertext)
Decrypts a message.
See also
Crypt_Base::decrypt() @access public
Parameters
string $ciphertext
Returns
string $plaintext
Reimplemented from Crypt_Base.
Definition at line 379 of file TripleDES.php.
    {
        if ($this->mode_3cbc && strlen($this->key) > 8) {
            return $this->_unpad(
                $this->des[0]->decrypt(
                    $this->des[1]->encrypt(
                        $this->des[2]->decrypt(
                            str_pad($ciphertext, (strlen($ciphertext) + 7) & 0xFFFFFFF8, "\0")
                        )
                    )
                )
            );
        }
        return parent::decrypt($ciphertext);
    }
References Crypt_Base\_unpad(), decrypt(), and encrypt().
Referenced by decrypt(), and encrypt().
disableContinuousBuffer()
disableContinuousBuffer ()
Treat consecutive packets as if they are a discontinuous buffer.
The default behavior.
See also
Crypt_Base::disableContinuousBuffer()
self::enableContinuousBuffer() @access public
Reimplemented from Crypt_Base.
Definition at line 453 of file TripleDES.php.
    {
        parent::disableContinuousBuffer();
        if ($this->mode_3cbc) {
            $this->des[0]->disableContinuousBuffer();
            $this->des[1]->disableContinuousBuffer();
            $this->des[2]->disableContinuousBuffer();
        }
    }
enableContinuousBuffer()
enableContinuousBuffer ()
Treat consecutive "packets" as if they are a continuous buffer.
Say you have a 16-byte plaintext $plaintext. Using the default behavior, the two following code snippets will yield different outputs:
echo $des->encrypt(substr($plaintext, 0, 8)); echo $des->encrypt(substr($plaintext, 8, 8)); echo $des->encrypt($plaintext);
The solution is to enable the continuous buffer. Although this will resolve the above discrepancy, it creates another, as demonstrated with the following:
$des->encrypt(substr($plaintext, 0, 8)); echo $des->decrypt($des->encrypt(substr($plaintext, 8, 8))); echo $des->decrypt($des->encrypt(substr($plaintext, 8, 8)));
With the continuous buffer disabled, these would yield the same output. With it enabled, they yield different outputs. The reason is due to the fact that the initialization vector's change after every encryption / decryption round when the continuous buffer is enabled. When it's disabled, they remain constant.
Put another way, when the continuous buffer is enabled, the state of the Crypt_DES() object changes after each encryption / decryption round, whereas otherwise, it'd remain constant. For this reason, it's recommended that continuous buffers not be used. They do offer better security and are, in fact, sometimes required (SSH uses them), however, they are also less intuitive and more likely to cause you problems.
See also
Crypt_Base::enableContinuousBuffer()
self::disableContinuousBuffer() @access public
Reimplemented from Crypt_Base.
Definition at line 434 of file TripleDES.php.
    {
        parent::enableContinuousBuffer();
        if ($this->mode_3cbc) {
            $this->des[0]->enableContinuousBuffer();
            $this->des[1]->enableContinuousBuffer();
            $this->des[2]->enableContinuousBuffer();
        }
    }
encrypt()
encrypt ($plaintext)
Encrypts a message.
See also
Crypt_Base::encrypt() @access public
Parameters
string $plaintext
Returns
string $cipertext
Reimplemented from Crypt_Base.
Definition at line 352 of file TripleDES.php.
    {
        // parent::en/decrypt() is able to do all the work for all modes and keylengths,
        // except for: CRYPT_MODE_3CBC (inner chaining CBC) with a key > 64bits
        // if the key is smaller then 8, do what we'd normally do
        if ($this->mode_3cbc && strlen($this->key) > 8) {
            return $this->des[2]->encrypt(
                $this->des[1]->decrypt(
                    $this->des[0]->encrypt(
                        $this->_pad($plaintext)
                    )
                )
            );
        }
        return parent::encrypt($plaintext);
    }
References Crypt_Base\_pad(), decrypt(), and encrypt().
Referenced by decrypt(), and encrypt().
isValidEngine()
isValidEngine ($engine)
Test for engine validity.
This is mainly just a wrapper to set things up for Crypt_Base::isValidEngine()
See also
Crypt_Base::Crypt_Base()
Parameters
int $engine @access public
Returns
bool
Reimplemented from Crypt_DES.
Definition at line 248 of file TripleDES.php.
    {
        if ($engine == CRYPT_ENGINE_OPENSSL) {
            $this->cipher_name_openssl_ecb = 'des-ede3';
            $mode = $this->_openssl_translate_mode();
            $this->cipher_name_openssl = $mode == 'ecb' ? 'des-ede3' : 'des-ede3-' . $mode;
        }
        return parent::isValidEngine($engine);
    }
References Crypt_Base\$engine, Crypt_Base\$mode, Crypt_Base\_openssl_translate_mode(), and CRYPT_ENGINE_OPENSSL.
setIV()
setIV ($iv)
Sets the initialization vector.
(optional)
SetIV is not required when CRYPT_DES_MODE_ECB is being used. If not explicitly set, it'll be assumed to be all zero's.
See also
Crypt_Base::setIV() @access public
Parameters
string $iv
Reimplemented from Crypt_Base.
Definition at line 269 of file TripleDES.php.
    {
        parent::setIV($iv);
        if ($this->mode_3cbc) {
            $this->des[0]->setIV($iv);
            $this->des[1]->setIV($iv);
            $this->des[2]->setIV($iv);
        }
    }
References Crypt_Base\$iv.
setKey()
setKey ($key)
Sets the key.
Keys can be of any length. Triple DES, itself, can use 128-bit (eg. strlen($key) == 16) or 192-bit (eg. strlen($key) == 24) keys. This function pads and truncates $key as appropriate.
DES also requires that every eighth bit be a parity bit, however, we'll ignore that.
If the key is not explicitly set, it'll be assumed to be all null bytes.
@access public
See also
Crypt_DES::setKey()
Crypt_Base::setKey()
Parameters
string $key
Reimplemented from Crypt_DES.
Definition at line 320 of file TripleDES.php.
    {
        $length = $this->explicit_key_length ? $this->key_length : strlen($key);
        if ($length > 8) {
            $key = str_pad(substr($key, 0, 24), 24, chr(0));
            // if $key is between 64 and 128-bits, use the first 64-bits as the last, per this:
            // http://php.net/function.mcrypt-encrypt#47973
            $key = $length <= 16 ? substr_replace($key, substr($key, 0, 8), 16) : substr($key, 0, 24);
        } else {
            $key = str_pad($key, 8, chr(0));
        }
        parent::setKey($key);
        // And in case of CRYPT_DES_MODE_3CBC:
        // if key <= 64bits we not need the 3 $des to work,
        // because we will then act as regular DES-CBC with just a <= 64bit key.
        // So only if the key > 64bits (> 8 bytes) we will call setKey() for the 3 $des.
        if ($this->mode_3cbc && $length > 8) {
            $this->des[0]->setKey(substr($key,  0, 8));
            $this->des[1]->setKey(substr($key,  8, 8));
            $this->des[2]->setKey(substr($key, 16, 8));
        }
    }
References Crypt_Base\$key.
setKeyLength()
setKeyLength ($length)
Sets the key length.
Valid key lengths are 64, 128 and 192
See also
Crypt_Base:setKeyLength() @access public
Parameters
int $length
Reimplemented from Crypt_Base.
Definition at line 288 of file TripleDES.php.
    {
        $length >>= 3;
        switch (true) {
            case $length <= 8:
                $this->key_length = 8;
                break;
            case $length <= 16:
                $this->key_length = 16;
                break;
            default:
                $this->key_length = 24;
        }
        parent::setKeyLength($length);
    }
setPreferredEngine()
setPreferredEngine ($engine)
Sets the internal crypt engine.
See also
Crypt_Base::Crypt_Base()
Crypt_Base::setPreferredEngine()
Parameters
int $engine @access public
Returns
int
Reimplemented from Crypt_Base.
Definition at line 507 of file TripleDES.php.
    {
        if ($this->mode_3cbc) {
            $this->des[0]->setPreferredEngine($engine);
            $this->des[1]->setPreferredEngine($engine);
            $this->des[2]->setPreferredEngine($engine);
        }
        return parent::setPreferredEngine($engine);
    }
References Crypt_Base\$engine.
Field Documentation
$cfb_init_len
$cfb_init_len = 750
Definition at line 143 of file TripleDES.php.
$cipher_name_mcrypt
$cipher_name_mcrypt = 'tripledes'
Definition at line 134 of file TripleDES.php.
$const_namespace
$const_namespace = 'DES'
Definition at line 124 of file TripleDES.php.
$des
$des
Definition at line 171 of file TripleDES.php.
$key_length
$key_length = 24
Definition at line 104 of file TripleDES.php.
$key_length_max
$key_length_max = 24
Definition at line 153 of file TripleDES.php.
$mode_3cbc
$mode_3cbc
Definition at line 161 of file TripleDES.php.
$password_default_salt
$password_default_salt = 'phpseclib'
Definition at line 114 of file TripleDES.php.
The documentation for this class was generated from the following file:
src/View/lib/phpseclib/Crypt/TripleDES.php