PF Firewall: Model Class Reference
Model Class Reference
Public Member Functions
__construct ()
IsRunning ($proc='')
Checks if the given process(es) is running.
GetProcList ()
Gets the list of processes running.
SelectProcesses ($psout)
Selects user processes from ps output.
Start ()
Start module process(es).
Stop ()
Stops module process(es)
Pkill ($proc, $args='')
Kills the given process(es).
GetIntIf ()
Get int_if.
_getIntIf ()
GetExtIf ()
Get ext_if.
_getExtIf ()
isWifiIf ($if)
CreateUser ($user, $passwd, $uid)
Creates a system user.
SetPassword ($user, $passwd)
Sets user's password in the system password file.
SetLogLevel ($level)
Sets global log level.
SetHelpBox ($bool)
Enables or disables help boxes.
SetSessionTimeout ($timeout)
Sets session timeout.
SetDefaultLocale ($locale)
Sets default locale.
SetForceHTTPs ($bool)
Enables or disables HTTPs.
SetUseSSH ($bool)
Enables or disables SSH.
SetMaxAnchorNesting ($max)
Sets the max number of nested anchors allowed.
SetPfctlTimeout ($timeout)
Sets pfctl timeout.
SetStatusCheckInterval ($interval)
Sets status check interval.
SetMaxFileSizeToProcess ($size)
Sets max file size to process.
GetReloadRate ()
Gets default reload rate.
_getReloadRate ()
SetReloadRate ($rate)
Sets default reload rate.
RunShellCommand ($cmd)
Runs the given shell command and returns its output as string.
GetFiles ($filepath)
Returns files with the given filepath pattern.
GetFile ($file)
Reads file contents.
DeleteFile ($path)
Deletes the given file or directory.
PutFile ($file, $contents)
Writes contents to file.
SetNVP ($file, $name, $newvalue)
Changes value of NVP.
GetNVP ($file, $name, $set=0, $trimchars='')
Reads value of NVP.
SearchFile ($file, $re, $set=0, $trimchars='')
Searches the given file with the given regex.
SearchFileAll ($file, $re, $set=1)
Multi-searches a given file with a given regexp.
ReplaceRegexp ($file, $matchre, $replacere)
Searches a needle and replaces with a value in the given file.
AppendToFile ($file, $line)
Appends a string to a file.
GetDateTime ()
Gets system datetime.
GetPhyIfs ()
Extracts physical interface names from ifconfig output.
_getPhyIfs ()
GetDefaultLogFile ()
Gets the log file of the module.
SelectLogFile ($file)
Gets the log file under the tmp folder.
IsLogFileModified ($logfile)
Checks if the given log file has been updated.
GetTmpLogFileName ($file)
Gets the name of the file in the tmp folder.
UpdateTmpLogFile ($file)
Copies the original log file to tmp folder.
formatDateHourRegexp ($month, $day, $hour, $minute)
Generates the module specific datetime regexp for filtering logs.
formatDateHourRegexpDayLeadingZero ($month, $day, $hour, $minute)
formatDateHourRegexpWeekDays ($month, $day, $hour, $minute)
GetFileLineCount ($file, $re='', $needle='', $month='', $day='', $hour='', $minute='')
Gets line count of the given log file.
_getFileLineCount ($file, $re='', $needle='', $month='', $day='', $hour='', $minute='')
GetLogs ($file, $end, $count, $re='', $needle='', $month='', $day='', $hour='', $minute='')
Gets lines in log file.
GetLiveLogs ($file, $count, $re='')
Gets logs for live logs pages.
_getLiveLogs ($file, $count, $re='', $needle='', $reportFileExistResult=TRUE)
Gets logs for live logs pages, the actual method.
GetLastLogs ($file, $count)
GetLogFilesList ()
Gets log files list with start dates.
GetLogStartDate ($file)
Extracts the datetime of the first line in the log file.
_getLogStartDate ($file)
GetFileFirstLine ($file)
Gets first line of file.
ParseLogLine ($logline, &$cols)
Parses the given log line.
PostProcessCols (&$cols)
Further processes parser output fields.
PrepareFileForDownload ($file)
Prepares file for download over WUI.
GetOrigFileName ($logfile)
Gets the original file name for the given log file.
GetProcStatLines ($logfile)
Collects text statistics for the proc stats general page.
CopyLogFileToTmp ($file, $tmpdir)
Uncompresses gzipped log file to tmp dir.
GetStatsLogLines ($logfile, $tail=-1)
Builds generic grep command and extracts log lines.
GetAllStats ($logfile, $collecthours='')
Gets both brief and full statistics.
GetStats ($logfile, $date, $collecthours='')
Main statistics collector, as module data set.
_getStats ($logfile, $date, $collecthours='')
ValidateFile ($file, $reportFileExistResult=TRUE)
Checks if the given file exists and not larger than $MaxFileSizeToProcess in MBs.
ValidateFileExists ($file, $reportFileExistResult=TRUE)
CountDiffLogLines ($logfile, &$count)
Gets the number of lines added to log files since last tmp file update.
UpdateStats ($logfile, &$stats, &$briefstats)
Updates statistics incrementally, both brief and full.
GetDateRegexp ($date)
Generates date regexp to be used by statistics functions.
GetHourRegexp ($date)
Generates hour regexp to be used by statistics functions.
GetSavedStats ($logfile, &$stats, &$briefstats)
Gets saved statistics for the given log file.
GetStatsFileInfo ($logfile, &$linecount, &$filestat)
Gets previous line count and stat() from statistics file.
GetStatsFileName ($logfile)
Gets name of the tmp statistics file for the given log file.
SaveStats ($logfile, $stats, $briefstats, $linecount)
Saves collected statistics with the current line count and stat() output.
CollectDayStats ($statsdefs, $values, $line, &$stats)
Day statistics collector.
CollectHourStats ($statsdefs, $hour, $min, $values, $line, &$daystats)
Hour statistics collector.
IncStats ($line, $values, $statsdefs, &$stats)
Increments stats for the given values.
CollectMinuteStats ($statsdefs, $min, $values, $line, &$hourstats)
Minute statistics collector.
GetConfigValues ($conf, $group)
Gets all configuration for a given configuration type.
GetValue ($name, $conf, $group)
Returns all enabled configuration for a given configuration type.
GetDisabledValue ($name, $conf, $group)
Returns all disabled configuration for a given configuration type.
getValidValues ($name)
GetDisabledNVP ($file, $name, $set=0, $trimchars='')
Reads value of commented-out NVP.
GetName ($file, $name)
Checks if Name exists.
GetDisabledName ($file, $name)
Checks if commented-out Name exists.
SetConfValue ($name, $newvalue, $conf, $group)
Sets the value of NVP configuration.
GetConfValueType ($name)
EnableConf ($name, $conf, $group)
Enables a configuration item in conf file.
DisableConf ($name, $conf, $group)
Disables a configuration item in conf file.
EnableNVP ($file, $name, $type)
Enables an NVP configuration item with value.
EnableName ($file, $name)
Enables a Name: configuration item without value.
DisableNVP ($file, $name, $type)
Disables an NVP.
DisableName ($file, $name)
Disables a Name.
GetConfFile ($conf, $group)
Returns configuration file of the module.
SetConfig ($confname)
Sets configuration file based on config type provided.
Kill ()
Stops module's parent process with its pid.
KillPid ($pid)
Kills process with the given pid.
IsModulePidRunning ($pid)
Checks if the pid is running.
GetVersion ()
Gets software version string.
GetServiceStatus ($get_info=0, $start='10min', $interval_changed=0)
Gets service statuses.
getCachedContents ($filename, &$contents)
GetModuleStatus ($generate_status)
_getModuleStatus ($start, $generate_status, $do_cache=1)
_getModuleInfo ($start)
getFifoLogs ($interval=60)
getRrdValue ($rrd, $start=60, &$result, $type='derive')
getRrdfetchResolution ($output)
GetStatus ()
isPrio ($log, $prio)
GetSysCtl ($option)
Gets sysctl output for the given arg.
_getSysCtl ($option)
ParseSyslogLine ($logline, &$cols)
Parses standard syslog line.
GetNewsyslogConfig ($model)
Gets newsyslog configuration for log file.
SetNewsyslogConfig ($file, $count, $size, $when)
Sets newsyslog configuration for log file.
_getPartitions ()
Returns all partitions mounted.
GetSensors ()
Finds sysctl temp and fan sensors.
Data Fields
$Nesting = 0
Keeps the count of nested anchors in inline rules.
$Name = ''
$Proc = ''
$User = ''
$StartCmd = ''
const PROC_STAT_TIMEOUT = 30
Max number of iterations to try while starting or stopping processes.
const PROC_STAT_SLEEP_TIME = 1
$Commands = array()
Argument lists and descriptions of commands.
$NVPS = '='
$COMC = '#'
$LogFile = ''
$TmpLogsDir = ''
$PfRulesFile = '/etc/pf.conf'
$ConfFile = ''
$Config = ''
$ReloadCmd = ''
$CmdLogStart = '/usr/bin/head -1 <LF>'
$VersionCmd = ''
$PidFile = ''
Protected Attributes
$psCmd = '/bin/ps arwwx -o pid,start,%cpu,time,%mem,rss,vsz,stat,pri,nice,tty,user,group,command | /usr/bin/grep -v -e grep | /usr/bin/grep -E <PROC>'
$rcConfLocal = '/etc/rc.conf.local'
$PFFWDIR = PFFWDIR
Makes the PFFWDIR define easier to use in functions, without adding a global var.
$CollectdName = ''
Used in collectd rrd and fifo file names.
$CollectdRrdFolder = PFFWDIR.'/collectd/rrd/localhost'
$CollectdFifoFolder = PFFWDIR.'/collectd/fifo'
$newSyslogConf = '/etc/newsyslog.conf'
$dateTimeFormat = 'M j H:i:s'
This datetime format is for error logs, not access logs.
Detailed Description
Definition at line 27 of file model.php.
Constructor & Destructor Documentation
__construct()
__construct ()
Todo:
Is there any pattern or size for new value, 2nd param?
Reimplemented in Collectd, Dhcpd, Dnsmasq, Docs, Ftpproxy, Httpd, Openssh, Pf, Symon, Symux, System, Dhcpd, Dnsmasq, Ftpproxy, Ctlrlogs, Httpd, Httpdlogs, Wuilogs, Docs, Monitoring, Openssh, Pf, and System.
Definition at line 90 of file model.php.
    {
        global $ModelConfig;
        $this->Proc= $this->Name;
        $this->CollectdName= $this->Name;
        $this->TmpLogsDir= PFFWDIR.'/logs/'.get_class($this).'/';
        $this->Config= $ModelConfig;
        $this->Commands= array_merge(
            $this->Commands,
            array(
                'IsRunning' =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Check if process running'),
                    ),
                'Start' =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Start '.get_class($this)),
                    ),
                'Stop'  =>  array(
                    'argv'  =>  array(),
                    'desc'  => _('Stop '.get_class($this)),
                    ),
                'GetProcList'   =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Get process list'),
                    ),
                'GetIntIf'=>    array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Get int_if'),
                    ),
                'GetExtIf'=>    array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Get ext_if'),
                    ),
                'CreateUser'    =>  array(
                    'argv'  =>  array(NAME, SHA1STR, NUM),
                    'desc'  =>  _('Create user'),
                    ),
                'SetPassword'   =>  array(
                    'argv'  =>  array(NAME, SHA1STR),
                    'desc'  =>  _('Set user password'),
                    ),
                'SetLogLevel'=> array(
                    'argv'  =>  array(NAME),
                    'desc'  =>  _('Set log level'),
                    ),
                'SetHelpBox'=>  array(
                    'argv'  =>  array(NAME),
                    'desc'  =>  _('Set help boxes'),
                    ),
                'SetSessionTimeout'=>   array(
                    'argv'  =>  array(NUM),
                    'desc'  =>  _('Set session timeout'),
                    ),
                'SetDefaultLocale'=>    array(
                    'argv'  =>  array(NAME),
                    'desc'  =>  _('Set default locale'),
                    ),
                'SetForceHTTPs'=>   array(
                    'argv'  =>  array(NAME),
                    'desc'  =>  _('Set force HTTPs'),
                    ),
                'SetUseSSH'=>   array(
                    'argv'  =>  array(NAME),
                    'desc'  =>  _('Set use SSH'),
                    ),
                'SetMaxAnchorNesting'=> array(
                    'argv'  =>  array(NUM),
                    'desc'  =>  _('Set max anchor nesting'),
                    ),
                'SetPfctlTimeout'=> array(
                    'argv'  =>  array(NUM),
                    'desc'  =>  _('Set pfctl timeout'),
                    ),
                'SetStatusCheckInterval'=>  array(
                    'argv'  =>  array(NUM),
                    'desc'  =>  _('Set status check interval'),
                    ),
                'SetMaxFileSizeToProcess'=> array(
                    'argv'  =>  array(NUM),
                    'desc'  =>  _('Set max file size to process'),
                    ),
                'GetReloadRate'=>   array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Get reload rate'),
                    ),
                'SetReloadRate'=>   array(
                    'argv'  =>  array(NUM),
                    'desc'  =>  _('Set reload rate'),
                    ),
                'GetDateTime'   =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Get datetime'),
                    ),
                'GetPhyIfs'     =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('List physical interfaces'),
                    ),
                'GetDefaultLogFile' =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Get log file'),
                    ),
                'SelectLogFile' =>  array(
                    'argv'  =>  array(FILEPATH|EMPTYSTR),
                    'desc'  =>  _('Select log file'),
                    ),
                'GetLogFilesList'   =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Get log files list'),
                    ),
                'GetLogStartDate'   =>  array(
                    'argv'  =>  array(FILEPATH),
                    'desc'  =>  _('Get log start date'),
                    ),
                'GetFileLineCount'  =>  array(
                    'argv'  =>  array(FILEPATH, REGEXP|NONE, REGEXP|NONE, NUM|EMPTYSTR|NONE, NUM|EMPTYSTR|NONE, NUM|EMPTYSTR|NONE, NUM|EMPTYSTR|NONE),
                    'desc'  =>  _('Get line count'),
                    ),
                'GetLogs'   =>  array(
                    'argv'  =>  array(FILEPATH, NUM, TAIL, REGEXP|NONE, REGEXP|NONE, NUM|EMPTYSTR|NONE, NUM|EMPTYSTR|NONE, NUM|EMPTYSTR|NONE, NUM|EMPTYSTR|NONE),
                    'desc'  =>  _('Get lines'),
                    ),
                'GetLiveLogs'   =>  array(
                    'argv'  =>  array(FILEPATH, TAIL, REGEXP|NONE),
                    'desc'  =>  _('Get tail'),
                    ),
                'GetLastLogs'   =>  array(
                    'argv'  =>  array(FILEPATH, TAIL),
                    'desc'  =>  _('Get last logs'),
                    ),
                'GetAllStats'=> array(
                    'argv'  =>  array(FILEPATH, NAME|EMPTYSTR),
                    'desc'  =>  _('Get all stats'),
                    ),
                'GetStats'=>    array(
                    'argv'  =>  array(FILEPATH, SERIALARRAY, NAME|EMPTYSTR),
                    'desc'  =>  _('Get stats'),
                    ),
                'GetProcStatLines'  =>  array(
                    'argv'  =>  array(FILEPATH|NONE),
                    'desc'  =>  _('Get stat lines'),
                    ),
                'PrepareFileForDownload'    =>  array(
                    'argv'  =>  array(FILEPATH),
                    'desc'  =>  _('Prepare file for download'),
                    ),
                'GetVersion'    =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Get software version'),
                    ),
                'GetServiceStatus'  =>  array(
                    'argv'  =>  array(BOOL|NONE, STR|NONE, BOOL|NONE),
                    'desc'  =>  _('Get service status'),
                    ),
                'GetModuleStatus'   =>  array(
                    // Trailing comma to avoid syntax error
                    'argv'  =>  array(BOOL,),
                    'desc'  =>  _('Get module status'),
                    ),
                'GetSysCtl' =>  array(
                    'argv'  =>  array(NAME),
                    'desc'  =>  _('Get sysctl values'),
                    ),
                'GetConfigValues'   =>  array(
                    'argv'  =>  array(NAME|EMPTYSTR, NUM|EMPTYSTR),
                    'desc'  =>  _('Get config values'),
                    ),
                'SetConfValue'  =>  array(
                    'argv'  =>  array(CONFNAME, STR, NAME|EMPTYSTR, NUM|EMPTYSTR),
                    'desc'  =>  _('Set name value pair'),
                    ),
                'EnableConf'    =>  array(
                    'argv'  =>  array(CONFNAME, NAME|EMPTYSTR, NUM|EMPTYSTR),
                    'desc'  =>  _('Enable config'),
                    ),
                'DisableConf'   =>  array(
                    'argv'  =>  array(CONFNAME, NAME|EMPTYSTR, NUM|EMPTYSTR),
                    'desc'  =>  _('Disable config'),
                    ),
                'GetStatus' => array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Get critical errors'),
                    ),
                )
            );
    }
References $ModelConfig, BOOL, CONFNAME, EMPTYSTR, FILEPATH, NAME, NONE, NUM, PFFWDIR, REGEXP, SERIALARRAY, SHA1STR, STR, and TAIL.
Member Function Documentation
_getExtIf()
_getExtIf ()
Definition at line 515 of file model.php.
    {
        return $this->GetNVP($this->PfRulesFile, 'ext_if');
    }
References GetNVP().
Referenced by System\GetConfig(), GetExtIf(), GetServiceStatus(), and System\NetStart().
_getFileLineCount()
_getFileLineCount ($file, $re = '', $needle = '', $month = '', $day = '', $hour = '', $minute = '')
Warning
Input redirection is necessary, otherwise wc adds file name to its output too
Reimplemented in Openssh, and Pf.
Definition at line 1279 of file model.php.
    {
        if (!$this->ValidateFile($file)) {
            return FALSE;
        }
        if ($re == '' && $needle == '' && $month == '' && $day == '' && $hour == '' && $minute == '') {
            $cmd= "/usr/bin/wc -l < $file";
        }
        else {
            // Skip for speed, otherwise we could use datetime regexp for empty strings too
            if ($month == '' && $day == '' && $hour == '' && $minute == '') {
                $re= escapeshellarg($re);
                if ($needle == '') {
                    $cmd= "/usr/bin/grep -a -E $re $file";
                }
                else {
                    $needle= escapeshellarg($needle);
                    $cmd= "/usr/bin/grep -a -E $needle $file | /usr/bin/grep -a -E $re";
                }
            }
            else {
                $cmd= '/usr/bin/grep -a -E "' . $this->formatDateHourRegexp($month, $day, $hour, $minute) . '" ' . $file;
                $re= escapeshellarg($re);
                if ($needle == '') {
                    $cmd.= " | /usr/bin/grep -a -E $re";
                }
                else {
                    $needle= escapeshellarg($needle);
                    $cmd.= " | /usr/bin/grep -a -E $needle | /usr/bin/grep -a -E $re";
                }
            }
            $cmd.= ' | /usr/bin/wc -l';
        }
        // OpenBSD wc returns with leading blanks
        return trim($this->RunShellCommand($cmd));
    }
References formatDateHourRegexp(), RunShellCommand(), and ValidateFile().
Referenced by CountDiffLogLines(), GetFileLineCount(), and UpdateStats().
_getIntIf()
_getIntIf ()
Definition at line 500 of file model.php.
    {
        return $this->GetNVP($this->PfRulesFile, 'int_if');
    }
References GetNVP().
Referenced by System\GetConfig(), GetIntIf(), GetServiceStatus(), and System\NetStart().
_getLiveLogs()
_getLiveLogs ($file, $count, $re = '', $needle = '', $reportFileExistResult = TRUE)
Gets logs for live logs pages, the actual method.
A few modules share their log files with other processes. So the $needle param is used to filter module log lines.
Parameters
string $needle Second regexp to further restrict the result set.
Reimplemented in Monitoring, Openssh, and Pf.
Definition at line 1407 of file model.php.
    {
        if (!$this->ValidateFile($file, $reportFileExistResult)) {
            return FALSE;
        }
        // Empty $re is not an issue for grep, greps all
        $re= escapeshellarg($re);
        if ($needle == '') {
            $cmd= "/usr/bin/grep -a -E $re $file";
        }
        else {
            $needle= escapeshellarg($needle);
            $cmd= "/usr/bin/grep -a -E $needle $file | /usr/bin/grep -a -E $re";
        }
        $cmd.= " | /usr/bin/tail -$count";
        exec($cmd, $output, $retval);
        $logs= array();
        foreach ($output as $line) {
            unset($cols);
            if ($this->ParseLogLine($line, $cols)) {
                $logs[]= $cols;
            }
        }
        return $logs;
    }
References $retval, ParseLogLine(), and ValidateFile().
Referenced by getFifoLogs(), and GetLiveLogs().
_getLogStartDate()
_getLogStartDate ($file)
Definition at line 1489 of file model.php.
    {
        if (preg_match('/.*\.gz$/', $file)) {
            $tmpfile= $this->GetTmpLogFileName($file);
            // Log file may have been rotated, shifting compressed archive file numbers,
            // hence modification check
            if (file_exists($tmpfile) && !$this->IsLogFileModified($tmpfile)) {
                $file= $tmpfile;
            }
        }
        if (!preg_match('/.*\.gz$/', $file)) {
            $logline= $this->GetFileFirstLine($file);
            if ($this->ParseLogLine($logline, $cols)) {
                return $cols['Date'].' '.$cols['Time'];
            } else {
                return _('Unknown');
            }
        }
        return _('Compressed');
    }
References GetFileFirstLine(), GetTmpLogFileName(), IsLogFileModified(), and ParseLogLine().
Referenced by GetLogFilesList(), and GetLogStartDate().
_getModuleInfo()
_getModuleInfo ($start)
Reimplemented in Dhcpd, Openssh, Pf, and System.
Definition at line 2857 of file model.php.
    {
        return FALSE;
    }
_getModuleStatus()
_getModuleStatus ($start, $generate_status, $do_cache = 1)
Definition at line 2804 of file model.php.
    {
        $status= array();
        $cache= "{$this->PFFWDIR}/cache/{$this->Name}_status.json";
        if ($generate_status || !$this->getCachedContents($cache, $status)) {
            $runStatus= $this->IsRunning() ? 'R' : 'S';
            $status= array(
                'Status' => $runStatus,
                'ErrorStatus' => 'U',
                'Critical' => 0,
                'Error' => 0,
                'Warning' => 0,
                'Logs' => array(),
                );
            $logs= $this->getFifoLogs($start);
            if ($logs !== FALSE) {
                $status['Logs']= $logs;
            }
            $result= array(
                'critical' => TRUE,
                'error' => TRUE,
                'warning' => TRUE,
                );
            foreach (array('warning', 'error', 'critical') as $prio) {
                $status[ucfirst($prio)]= $this->getRrdValue("derive-$prio.rrd", $start, $result[$prio]);
            }
            if ($status['Critical']) {
                $status['ErrorStatus']= 'C';
            }
            else if ($status['Error']) {
                $status['ErrorStatus']= 'E';
            }
            else if ($status['Warning']) {
                $status['ErrorStatus']= 'W';
            }
            else if ($result['critical'] && $result['error'] && $result['warning']) {
                $status['ErrorStatus']= 'N';
            }
            if ($do_cache) {
                file_put_contents($cache, json_encode($status), LOCK_EX);
            }
        }
        return $status;
    }
References $generate_status, getCachedContents(), getFifoLogs(), getRrdValue(), and IsRunning().
Referenced by GetModuleStatus().
_getPartitions()
_getPartitions ()
Returns all partitions mounted.
Reimplemented in System.
Definition at line 3154 of file model.php.
    {
        if (($contents= $this->RunShellCommand("/sbin/mount")) !== '') {
            $contents= explode("\n", $contents);
            $partitions= array();
            foreach ($contents as $line) {
                if (preg_match('/^(\S+)\s+on\s+(\S+)/', $line, $match)) {
                    $partitions[$match[1]]= $match[2];
                }
            }
            return $partitions;
        }
        return FALSE;
    }
References RunShellCommand().
Referenced by Symon\SetConf(), and Symon\SetPartitions().
_getPhyIfs()
_getPhyIfs ()
Definition at line 1036 of file model.php.
    {
        return $this->RunShellCommand("/sbin/ifconfig -a | /usr/bin/grep ': flags=' | /usr/bin/sed 's/: flags=.*//g' | /usr/bin/grep -v -e lo -e pflog -e pfsync -e enc -e tun");
    }
References RunShellCommand().
Referenced by System\GetConfig(), and GetPhyIfs().
_getReloadRate()
_getReloadRate ()
Definition at line 760 of file model.php.
    {
        global $VIEW_PATH;
        require($VIEW_PATH.'/lib/setup.php');
        return $DefaultReloadRate;
    }
References $DefaultReloadRate, and $VIEW_PATH.
Referenced by getCachedContents(), and GetReloadRate().
_getStats()
_getStats ($logfile, $date, $collecthours = '')
Definition at line 1780 of file model.php.
    {
        if (!$this->ValidateFile($logfile)) {
            return FALSE;
        }
        $date= json_decode($date, TRUE);
        $stats= array();
        $briefstats= array();
        $uptodate= FALSE;
        if ($this->IsLogFileModified($logfile)) {
            $this->UpdateTmpLogFile($logfile);
        }
        else {
            $uptodate= $this->GetSavedStats($logfile, $stats, $briefstats);
        }
        if (!$uptodate) {
            $this->UpdateStats($logfile, $stats, $briefstats);
        }
        if (isset($stats['Date'])) {
            if ($collecthours === '') {
                foreach ($stats['Date'] as $day => $daystats) {
                    unset($stats['Date'][$day]['Hours']);
                }
            }
            $re= $this->GetDateRegexp($date);
            foreach ($stats['Date'] as $day => $daystats) {
                if (!preg_match("/$re/", $day)) {
                    unset($stats['Date'][$day]);
                }
            }
            $re= $this->GetHourRegexp($date);
            foreach ($stats['Date'] as $day => $daystats) {
                if (isset($daystats['Hours'])) {
                    foreach ($daystats['Hours'] as $hour => $hourstats) {
                        if (!preg_match("/$re/", $hour)) {
                            unset($stats['Date'][$day]['Hours'][$hour]);
                        }
                    }
                }
            }
        }
        return json_encode($stats);
    }
References GetDateRegexp(), GetHourRegexp(), GetSavedStats(), IsLogFileModified(), UpdateStats(), UpdateTmpLogFile(), and ValidateFile().
Referenced by GetAllStats(), and GetStats().
_getSysCtl()
_getSysCtl ($option)
Definition at line 3050 of file model.php.
    {
        return $this->RunShellCommand("/sbin/sysctl $option 2>&1");
    }
References RunShellCommand().
Referenced by GetSensors(), GetSysCtl(), Symon\SetConf(), and Symon\SetCpus().
AppendToFile()
AppendToFile ($file, $line)
Appends a string to a file.
Parameters
string $file Config file pathname.
string $line Line to add.
Returns
bool TRUE on success, FALSE on fail.
Todo:
Return the return value of file_put_contents()? Check and test all usages of AppendToFile() first.
Definition at line 994 of file model.php.
    {
        if (copy($file, $file.'.bak')) {
            $contents= file_get_contents($file).$line."\n";
            file_put_contents($file, $contents);
            return TRUE;
        }
        else {
            ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Cannot copy file: $file");
        }
        return FALSE;
    }
References ctlr_syslog().
Referenced by System\AddHost().
CollectDayStats()
CollectDayStats ($statsdefs, $values, $line, & $stats)
Day statistics collector.
$statsdefs has all the information to collect what data.
If parsed log time does not have an appropriate hour/min, then 12:00 is assumed.
Todo:
How is it possible that Time does not have hour/min? Should have a module Time field processor as well?
Parameters
array $statsdefs Module stats section of $StatsConf.
array $values Log fields parsed by caller function.
string $line Current log line needed to search for keywords.
array $stats Statistics data set collected.
Definition at line 2164 of file model.php.
    {
        $re= '/^(\d+):(\d+):(\d+)$/';
        if (preg_match($re, $values['Time'], $match)) {
            $hour= $match[1];
            $min= $match[2];
        }
        else {
            // Should be unreachable
            $hour= '12';
            $min= '00';
            ctlr_syslog(LOG_DEBUG, __FILE__, __FUNCTION__, __LINE__, 'There was no Time in log values, defaulting to 12:00');
        }
        $daystats= &$stats['Date'][$values['Date']];
        $this->IncStats($line, $values, $statsdefs, $daystats);
        $this->CollectHourStats($statsdefs, $hour, $min, $values, $line, $daystats);
    }
References CollectHourStats(), ctlr_syslog(), and IncStats().
Referenced by UpdateStats().
CollectHourStats()
CollectHourStats ($statsdefs, $hour, $min, $values, $line, & $daystats)
Hour statistics collector.
$statsdefs has all the information to collect what data.
$daystats is the subsection of the main $stats array for the current date.
Parameters
array $statsdefs Module stats section of $StatsConf.
string $hour Hour to collect stats for.
string $min Min to collect stats for, passed to CollectMinuteStats().
array $values Log fields parsed by caller function.
string $line Current log line needed to search for keywords.
array $daystats Statistics data set collected.
Definition at line 2198 of file model.php.
    {
        $hourstats= &$daystats['Hours'][$hour];
        $this->IncStats($line, $values, $statsdefs, $hourstats);
        $this->CollectMinuteStats($statsdefs, $min, $values, $line, $hourstats);
    }
References CollectMinuteStats(), and IncStats().
Referenced by CollectDayStats().
CollectMinuteStats()
CollectMinuteStats ($statsdefs, $min, $values, $line, & $hourstats)
Minute statistics collector.
$statsdefs has all the information to collect what data.
$hourstats is the subsection of the $stats array for the current hour.
Parameters
array $statsdefs Module stats section of $StatsConf.
string $min Min to collect stats for, passed to CollectMinuteStats().
array $values Log fields parsed by caller function.
string $line Current log line needed to search for keywords.
array $hourstats Statistics data set collected.
Definition at line 2274 of file model.php.
    {
        $minstats= &$hourstats['Mins'][$min];
        AddValueCreateKey($minstats, 'Sum', 1);
        foreach ($statsdefs as $stat => $statconf) {
            if (isset($statconf['Counters'])) {
                foreach ($statconf['Counters'] as $counter => $conf) {
                    if (isset($values[$conf['Field']])) {
                        AddValueCreateKey($minstats, $counter, $values[$conf['Field']]);
                    }
                }
            }
        }
        foreach ($statsdefs as $stat => $conf) {
            if (isset($conf['Needle'])) {
                if (preg_match('/'.$conf['Needle'].'/', $line)) {
                    AddValueCreateKey($minstats, $stat, 1);
                }
            }
        }
    }
References AddValueCreateKey().
Referenced by CollectHourStats().
CopyLogFileToTmp()
CopyLogFileToTmp ($file, $tmpdir)
Uncompresses gzipped log file to tmp dir.
Parameters
string $file Log file.
string $tmpdir Tmp folder to copy to.
Returns
bool TRUE on success, FALSE on fail.
Definition at line 1654 of file model.php.
    {
        if (!$this->ValidateFile($file)) {
            return FALSE;
        }
        $retval= 0;
        if (!file_exists($tmpdir)) {
            exec("/bin/mkdir -p $tmpdir 2>&1", $output, $retval);
        }
        if ($retval === 0) {
            exec("/bin/cp $file $tmpdir 2>&1", $output, $retval);
            if ($retval === 0) {
                $tmpfile= $tmpdir.basename($file);
                if (preg_match('/(.*)\.gz$/', $tmpfile, $match)) {
                    // Delete the old uncompressed file, otherwise gunzip fails
                    $this->DeleteFile($match[1]);
                    exec("/usr/bin/gunzip $tmpfile 2>&1", $output, $retval);
                    if ($retval === 0) {
                        return TRUE;
                    }
                    else {
                        ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, 'gunzip failed: '.$tmpdir.basename($file));
                    }
                }
                else {
                    return TRUE;
                }
            }
            else {
                ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, 'cp failed: '.$file);
            }
        }
        else {
            ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, 'mkdir failed: '.$tmpdir);
        }
        Error(implode("\n", $output));
        return FALSE;
    }
References $retval, ctlr_syslog(), DeleteFile(), Error(), and ValidateFile().
Referenced by UpdateTmpLogFile().
CountDiffLogLines()
CountDiffLogLines ($logfile, & $count)
Gets the number of lines added to log files since last tmp file update.
Parameters
string $logfile Log file pathname.
int $count Number of new log lines.
Returns
bool TRUE on success, FALSE on fail.
Definition at line 1873 of file model.php.
    {
        global $StatsConf;
        $count= -1;
        if ($this->GetStatsFileInfo($logfile, $oldlinecount, $oldfilestat)) {
            $needle= '';
            $statsdefs= $StatsConf[$this->Name];
            if (isset($statsdefs) && isset($statsdefs['Total']['Needle'])) {
                $needle= $statsdefs['Total']['Needle'];
            }
            $newlinecount= $this->_getFileLineCount($logfile, $needle);
            if ($newlinecount === FALSE) {
                return FALSE;
            }
            $origfile= $this->GetOrigFileName($logfile);
            if (($newlinecount >= $oldlinecount) && !preg_match('/\.gz$/', $origfile)) {
                ctlr_syslog(LOG_DEBUG, __FILE__, __FUNCTION__, __LINE__, "Logfile modified: $logfile, linecount $oldlinecount->$newlinecount");
                $count= $newlinecount - $oldlinecount;
                ctlr_syslog(LOG_DEBUG, __FILE__, __FUNCTION__, __LINE__, "Logfile has grown by $count lines: $logfile");
                return TRUE;
            }
            else {
                // Logs probably rotated, recollect the stats
                // Also stats for compressed files are always recollected on rotation, otherwise stats would be merged with the old stats
                ctlr_syslog(LOG_DEBUG, __FILE__, __FUNCTION__, __LINE__, "Assuming log file rotation: $logfile");
            }
        }
        else {
            ctlr_syslog(LOG_DEBUG, __FILE__, __FUNCTION__, __LINE__, "Cannot get file info: $logfile");
        }
        return FALSE;
    }
References $StatsConf, _getFileLineCount(), ctlr_syslog(), GetOrigFileName(), and GetStatsFileInfo().
Referenced by UpdateStats().
CreateUser()
CreateUser ($user, $passwd, $uid)
Creates a system user.
Note that passwords are double encrypted.
Parameters
string $user User name.
string $passwd SHA encrypted password.
int $uid User id.
Returns
bool TRUE on success, FALSE on fail.
Definition at line 536 of file model.php.
    {
        exec("/bin/cat /etc/master.passwd | /usr/bin/grep -E '^$user:' 2>&1", $output, $retval);
        // If the user does not exist
        if ($retval !== 0 && count($output) == 0) {
            $uline= "$user:$(/usr/bin/encrypt $passwd):$uid:$uid::0:0:PFFW $user:/var/empty:/var/www/htdocs/pffw/Controller/sh.php";
            exec("/bin/echo $uline >>/etc/master.passwd 2>&1", $output, $retval);
            if ($retval === 0) {
                $gline= "$user:*:$uid:";
                exec("/bin/echo $gline >>/etc/group 2>&1", $output, $retval);
                if ($retval === 0) {
                    exec("/usr/sbin/pwd_mkdb -p /etc/master.passwd 2>&1", $output, $retval);
                    return $retval === 0;
                }
            }
        }
        $errout= implode("\n", $output);
        Error($errout);
        ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Create user failed: $errout");
        return FALSE;
    }
References $retval, ctlr_syslog(), and Error().
DeleteFile()
DeleteFile ($path)
Deletes the given file or directory.
Parameters
string $path File or dir to delete.
Returns
bool TRUE on success, FALSE on fail.
Definition at line 836 of file model.php.
    {
        if (file_exists($path)) {
            exec("/bin/rm -rf $path 2>&1", $output, $retval);
            if ($retval === 0) {
                return TRUE;
            }
            else {
                $errout= implode("\n", $output);
                Error($errout);
                ctlr_syslog(LOG_DEBUG, __FILE__, __FUNCTION__, __LINE__, "Failed deleting: $path, $errout");
            }
        }
        else {
            ctlr_syslog(LOG_DEBUG, __FILE__, __FUNCTION__, __LINE__, "File path does not exist: $path");
        }
        return FALSE;
    }
References $retval, ctlr_syslog(), and Error().
Referenced by CopyLogFileToTmp(), System\DeleteIf(), and System\SystemMakeDynamicGateway().
DisableConf()
DisableConf ($name, $conf, $group)
Disables a configuration item in conf file.
Definition at line 2508 of file model.php.
    {
        $file= $this->GetConfFile($conf, $group);
        $this->SetConfig($conf);
        if ((isset($this->Config[$name]['type'])) && ($this->Config[$name]['type'] === FALSE)) {
            return $this->DisableName($file, $name);
        }
        return $this->DisableNVP($file, $name, $this->GetConfValueType($name));
    }
References DisableName(), DisableNVP(), GetConfFile(), GetConfValueType(), and SetConfig().
DisableName()
DisableName ($file, $name)
Disables a Name.
Definition at line 2553 of file model.php.
    {
        return $this->ReplaceRegexp($file, "/^(\h*$name(\h*$this->COMC.*|\h*))$/m", $this->COMC.'${1}');
    }
References ReplaceRegexp().
Referenced by DisableConf().
DisableNVP()
DisableNVP ($file, $name, $type)
Disables an NVP.
Attention
Value may be empty, so we allow for empty values with the re ($type|), while disabling
Definition at line 2544 of file model.php.
    {
        return $this->ReplaceRegexp($file, "/^(\h*$name\b\s*$this->NVPS\s*($type|))$/m", $this->COMC.'${1}');
    }
References ReplaceRegexp().
Referenced by DisableConf().
EnableConf()
EnableConf ($name, $conf, $group)
Enables a configuration item in conf file.
Certain modules have multiple configuration files, hence they override this method.
Parameters
string $name Config name
string $conf Config type
int $group E2guardian group
Returns
bool TRUE on success, FALSE on fail.
Definition at line 2494 of file model.php.
    {
        $file= $this->GetConfFile($conf, $group);
        $this->SetConfig($conf);
        if ((isset($this->Config[$name]['type'])) && ($this->Config[$name]['type'] === FALSE)) {
            return $this->EnableName($file, $name);
        }
        return $this->EnableNVP($file, $name, $this->GetConfValueType($name));
    }
References EnableName(), EnableNVP(), GetConfFile(), GetConfValueType(), and SetConfig().
EnableName()
EnableName ($file, $name)
Enables a Name: configuration item without value.
Definition at line 2536 of file model.php.
    {
        return $this->ReplaceRegexp($file, "/^\h*$this->COMC(\h*$name(\h*$this->COMC.*|\h*))$/m", '${1}');
    }
References ReplaceRegexp().
Referenced by EnableConf().
EnableNVP()
EnableNVP ($file, $name, $type)
Enables an NVP configuration item with value.
Parameters
string $file Config file
string $name Config name
string $type Type regexp of value
Returns
bool TRUE on success, FALSE on fail.
Attention
Value may be empty, so we allow for empty values with the re ($type|), while enabling
Definition at line 2527 of file model.php.
    {
        return $this->ReplaceRegexp($file, "/^\h*$this->COMC(\s*$name\b\s*$this->NVPS\s*($type|))$/m", '${1}');
    }
References ReplaceRegexp().
Referenced by EnableConf().
formatDateHourRegexp()
formatDateHourRegexp ($month, $day, $hour, $minute)
Generates the module specific datetime regexp for filtering logs.
Parameters
string $month Two-digit month, or empty string for match all.
string $day Two-digit day, or empty string for match all.
string $hour Two-digit hour, or empty string for match all.
string $minute Two-digit minute, or empty string for match all.
Returns
string Regexp to use as datetime filter.
Reimplemented in Pf.
Definition at line 1164 of file model.php.
    {
        global $MonthNames, $Re_MonthNames;
        // Sep  7 13:49:06
        if ($month != '') {
            $reMonth= $MonthNames[$month];
        } else {
            $reMonth= '('.$Re_MonthNames.')';
        }
        if ($day != '') {
            $reDay= sprintf('% 2d', $day);
        } else {
            $reDay= '([[:digit:][:blank:]][[:digit:]])';
        }
        if ($hour != '') {
            $reHour= $hour;
        } else {
            $reHour= '([[:digit:]][[:digit:]])';
        }
        if ($minute != '') {
            $reMinute= $minute;
        } else {
            $reMinute= '([[:digit:]][[:digit:]])';
        }
        return "^$reMonth $reDay $reHour:$reMinute:";
    }
References $MonthNames, and $Re_MonthNames.
Referenced by _getFileLineCount(), Openssh\_getFileLineCount(), GetLogs(), and Openssh\GetLogs().
formatDateHourRegexpDayLeadingZero()
formatDateHourRegexpDayLeadingZero ($month, $day, $hour, $minute)
Definition at line 1196 of file model.php.
    {
        global $MonthNames, $Re_MonthNames;
        // Sep 07 13:49:06
        if ($month != '') {
            $reMonth= $MonthNames[$month];
        } else {
            $reMonth= '('.$Re_MonthNames.')';
        }
        if ($day != '') {
            $reDay= $day;
        } else {
            $reDay= '([[:digit:]][[:digit:]])';
        }
        if ($hour != '') {
            $reHour= $hour;
        } else {
            $reHour= '([[:digit:]][[:digit:]])';
        }
        if ($minute != '') {
            $reMinute= $minute;
        } else {
            $reMinute= '([[:digit:]][[:digit:]])';
        }
        return "^$reMonth $reDay $reHour:$reMinute:";
    }
References $MonthNames, and $Re_MonthNames.
Referenced by Pf\formatDateHourRegexp().
formatDateHourRegexpWeekDays()
formatDateHourRegexpWeekDays ($month, $day, $hour, $minute)
Definition at line 1228 of file model.php.
    {
        global $MonthNames, $Re_MonthNames, $Re_WeekDays;
        // Mon Sep  4 23:51:31
        if ($month != '') {
            $reMonth= $MonthNames[$month];
        } else {
            $reMonth= '('.$Re_MonthNames.')';
        }
        if ($day != '') {
            $reDay= sprintf('% 2d', $day);
        } else {
            $reDay= '([[:digit:][:blank:]][[:digit:]])';
        }
        if ($hour != '') {
            $reHour= $hour;
        } else {
            $reHour= '([[:digit:]][[:digit:]])';
        }
        if ($minute != '') {
            $reMinute= $minute;
        } else {
            $reMinute= '([[:digit:]][[:digit:]])';
        }
        $reWeekDays= '('.$Re_WeekDays.')';
        return "^$reWeekDays $reMonth $reDay $reHour:$reMinute:";
    }
References $MonthNames, $Re_MonthNames, and $Re_WeekDays.
GetAllStats()
GetAllStats ($logfile, $collecthours = '')
Gets both brief and full statistics.
Parameters
string $logfile Log file pathname.
bool $collecthours Flag to get hour statistics also.
Returns
array Statistics in serialized arrays.
Attention
We need $stats return value of GetStats() because of $collecthours constraint
Definition at line 1742 of file model.php.
    {
        $date= json_encode(array('Month' => '', 'Day' => ''));
        $stats= $this->_getStats($logfile, $date, $collecthours);
        if ($stats === FALSE) {
            return FALSE;
        }
        // Do not get $stats here, just $briefstats
        $this->GetSavedStats($logfile, $dummy, $briefstats);
        $briefstats= json_encode($briefstats);
        // Use serialized stats as array elements to prevent otherwise extra json_decode() for $stats,
        // which is already serialized by GetStat() above.
        // They are ordinary strings now, this json_encode() should be quite fast
        return Output(json_encode(
                array(
                    'stats'     => $stats,
                    'briefstats'=> $briefstats,
                    )
                )
            );
    }
References _getStats(), GetSavedStats(), and Output().
getCachedContents()
getCachedContents ($filename, & $contents)
Definition at line 2775 of file model.php.
    {
        if (file_exists($filename)) {
            $now= intval(exec('date "+%s"'));
            $ctime= intval(stat($filename)['ctime']);
            $diff= $now - $ctime;
            $reload_rate= $this->_getReloadRate();
            if ($diff < $reload_rate) {
                if ($cachedContents= json_decode(file_get_contents($filename), TRUE)) {
                    ctlr_syslog(LOG_DEBUG, __FILE__, __FUNCTION__, __LINE__, "Using cached contents from $filename, refresh interval < default reload rate: $diff < $reload_rate seconds");
                    $contents= $cachedContents;
                    return TRUE;
                } else {
                    ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Cannot json_decode cached contents from $filename");
                }
            }
        }
        return FALSE;
    }
References _getReloadRate(), and ctlr_syslog().
Referenced by _getModuleStatus(), and GetServiceStatus().
GetConfFile()
GetConfFile ($conf, $group)
Returns configuration file of the module.
Certain modules have configuration divided into multiple pages/files, hence they override this method.
Parameters
string $conf Config type
int $group E2guardian group
Returns
string Config file pathname
Definition at line 2568 of file model.php.
    {
        return $this->ConfFile;
    }
Referenced by DisableConf(), EnableConf(), GetDisabledValue(), GetValue(), and SetConfValue().
GetConfigValues()
GetConfigValues ($conf, $group)
Gets all configuration for a given configuration type.
Parameters
string $conf Config type
int $group E2guardian group
Returns
array Array of config items
Definition at line 2305 of file model.php.
    {
        $this->SetConfig($conf);
        $values= array();
        foreach ($this->Config as $name => $config) {
            if (($output= $this->GetValue($name, $conf, $group)) !== FALSE) {
                $values[$name]= array(
                    'Value' => $output,
                    'Type' => $this->GetConfValueType($name),
                    'Enabled' => TRUE,
                    );
            }
            else if (($output= $this->GetDisabledValue($name, $conf, $group)) !== FALSE) {
                $values[$name]= array(
                    'Value' => $output,
                    'Type' => $this->GetConfValueType($name),
                    'Enabled' => FALSE,
                    );
            }
        }
        return Output(json_encode($values));
    }
References GetConfValueType(), GetDisabledValue(), GetValue(), Output(), and SetConfig().
GetConfValueType()
GetConfValueType ($name)
Definition at line 2474 of file model.php.
    {
        if (isset($this->Config[$name]['type'])) {
            return $this->Config[$name]['type'];
        } else {
            return '.*';
        }
    }
Referenced by DisableConf(), EnableConf(), and GetConfigValues().
GetDateRegexp()
GetDateRegexp ($date)
Generates date regexp to be used by statistics functions.
Used to match date indeces of stats array to get stats for date ranges.
Parameters
array $date Date struct.
Returns
string Regexp.
Reimplemented in Pf.
Definition at line 1989 of file model.php.
    {
        global $MonthNames;
        if ($date['Month'] == '') {
            $re= '.*';
        }
        else {
            $re= $MonthNames[$date['Month']].'\s+';
            if ($date['Day'] == '') {
                $re.= '.*';
            }
            else {
                $re.= sprintf('% 2d', $date['Day']);
            }
        }
        return $re;
    }
References $MonthNames.
Referenced by _getStats().
GetDateTime()
GetDateTime ()
Gets system datetime.
Returns
array Datetime.
Definition at line 1013 of file model.php.
    {
        $dateArray= array();
        $dateArray['Month']= exec('/bin/date +%m');
        $dateArray['Day']= exec('/bin/date +%d');
        $dateArray['Hour']= exec('/bin/date +%H');
        $dateArray['Minute']= exec('/bin/date +%M');
        return Output(json_encode($dateArray));
    }
References Output().
GetDefaultLogFile()
GetDefaultLogFile ()
Gets the log file of the module.
Returns
string Name of log file.
Definition at line 1046 of file model.php.
    {
        return Output($this->LogFile);
    }
References Output().
GetDisabledName()
GetDisabledName ($file, $name)
Checks if commented-out Name exists.
Parameters
string $file Config file
string $name Name of NVP
Returns
mixed Commented Name or FALSE on failure
Definition at line 2441 of file model.php.
    {
        return $this->SearchFile($file, "/^\h*$this->COMC\h*($name)(\h*$this->COMC.*|\h*)$/m");
    }
References SearchFile().
Referenced by GetDisabledValue().
GetDisabledNVP()
GetDisabledNVP ($file, $name, $set = 0, $trimchars = '')
Reads value of commented-out NVP.
Parameters
string $file Config file
string $name Name of NVP
int $set There may be multiple parentheses in $re, which one to return
string $trimchars If given, these chars are trimmed on the left or right.
Returns
string Value of commented NVP or NULL on failure
Definition at line 2417 of file model.php.
    {
        return $this->SearchFile($file, "/^\h*$this->COMC\h*$name\b\h*$this->NVPS\h*([^$this->COMC'\"\n]*|'[^'\n]*'|\"[^\"\n]*\"|[^$this->COMC\n]*)(\h*|\h*$this->COMC.*)$/m", $set, $trimchars);
    }
References SearchFile().
Referenced by GetDisabledValue().
GetDisabledValue()
GetDisabledValue ($name, $conf, $group)
Returns all disabled configuration for a given configuration type.
Definition at line 2366 of file model.php.
    {
        $file= $this->GetConfFile($conf, $group);
        if ((isset($this->Config[$name]['type'])) && ($this->Config[$name]['type'] === FALSE)) {
            return $this->GetDisabledName($file, $name);
        }
        $validValues= $this->getValidValues($name);
        $value= FALSE;
        $set= 0;
        // Try max 5 possible values
        while ($set < 5) {
            $value= $this->GetDisabledNVP($file, $name, $set);
            if ($value === FALSE) {
                return FALSE;
            }
            if (!count($validValues) || in_array($value, $validValues)) {
                return "$name=$value";
            }
            ctlr_syslog(LOG_NOTICE, __FILE__, __FUNCTION__, __LINE__, "Failed validating value: $name: $value");
            $set++;
        }
        return $value;
    }
References ctlr_syslog(), GetConfFile(), GetDisabledName(), GetDisabledNVP(), and getValidValues().
Referenced by GetConfigValues().
GetExtIf()
GetExtIf ()
Get ext_if.
Returns
string External interface name.
Definition at line 510 of file model.php.
    {
        return Output($this->_getExtIf());
    }
References _getExtIf(), and Output().
getFifoLogs()
getFifoLogs ($interval = 60)
Attention
Don't call date_create('now') to get current time, it uses UTC in php.ini, but the timezone in the logs may be different
Definition at line 2862 of file model.php.
    {
        $lastLogs= array();
        $rv= FALSE;
        foreach (array('warning', 'error', 'critical') as $prio) {
            // We could get Capacity from collectd.conf, but each fifo may have its own Capacity definition
            // So we use 100
            $logs= $this->_getLiveLogs("{$this->CollectdFifoFolder}/{$this->CollectdName}_$prio.fifo", 100, '', '', FALSE);
            if ($logs === FALSE) {
                continue;
            }
            $rv= TRUE;
            $count= count($logs);
            if ($count > 0) {
                // Create datetime from /bin/date output to match the timezone in the logs
                $dt= DateTime::createFromFormat($this->dateTimeFormat, exec('/bin/date "+%b %e %H:%M:%S"'));
                if ($dt) {
                    $lastTs= $dt->getTimestamp();
                    // Loop in reverse order to break out asap
                    while (--$count >= 0) {
                        $l= $logs[$count];
                        // @attention Always check the retval of createFromFormat(), it may fail due to format mismatch, e.g. log rotation lines
                        $dt= DateTime::createFromFormat($this->dateTimeFormat, $l['Date'].' '.$l['Time']);
                        if ($dt) {
                            $ts= $dt->getTimestamp();
                            if ($lastTs - $ts <= $interval) {
                                $lastLogs[]= $l;
                            } else {
                                break;
                            }
                        }
                    }
                }
            }
        }
        return $rv ? $lastLogs : FALSE;
    }
References _getLiveLogs().
Referenced by _getModuleStatus(), and GetStatus().
GetFile()
GetFile ($file)
Reads file contents.
Parameters
string $file Config file.
Returns
mixed File contents in a string or FALSE on fail.
Definition at line 822 of file model.php.
    {
        if (file_exists($file)) {
            return file_get_contents($file);
        }
        return FALSE;
    }
Referenced by System\_getIfConfig(), Dhcpd\_getLeases(), System\_getMyName(), System\_getStaticGateway(), System\DaemonizedRotateLogFile(), System\EnableHostap(), System\GetMFSConfig(), GetNewsyslogConfig(), System\GetRemoteTime(), System\getRootCronTab(), GetSavedStats(), Kill(), and SetNewsyslogConfig().
GetFileFirstLine()
GetFileFirstLine ($file)
Gets first line of file.
Used to get the start date of log files.
Parameters
string $file Log file pathname.
Returns
string First line in file.
Definition at line 1520 of file model.php.
    {
        $cmd= preg_replace('/<LF>/', $file, $this->CmdLogStart);
        return $this->RunShellCommand($cmd);
    }
References RunShellCommand().
Referenced by _getLogStartDate().
GetFileLineCount()
GetFileLineCount ($file, $re = '', $needle = '', $month = '', $day = '', $hour = '', $minute = '')
Gets line count of the given log file.
Parameters
string $file Log file pathname.
string $re Regexp to get count of a restricted result set.
string $needle Optional regexp to use with a second grep over logs, used by Stats pages.
string $month Two-digit month, or empty string for match all.
string $day Two-digit day, or empty string for match all.
string $hour Two-digit hour, or empty string for match all.
string $minute Two-digit minute, or empty string for match all.
Returns
int Line count.
Definition at line 1274 of file model.php.
    {
        return Output($this->_getFileLineCount($file, $re, $needle, $month, $day, $hour, $minute));
    }
References _getFileLineCount(), and Output().
GetFiles()
GetFiles ($filepath)
Returns files with the given filepath pattern.
$filepath does not have to be just directory path, and may contain wildcards.
Parameters
string $filepath File pattern to match.
Returns
string List of file names, without path.
Definition at line 811 of file model.php.
    {
        return $this->RunShellCommand("ls -1 $filepath");
    }
References RunShellCommand().
Referenced by GetLogFilesList().
GetHourRegexp()
GetHourRegexp ($date)
Generates hour regexp to be used by statistics functions.
Parameters
array $date Date struct.
Returns
string Regexp.
Definition at line 2014 of file model.php.
    {
        if (!isset($date['Hour']) || $date['Hour'] == '') {
            $re= '.*';
        }
        else {
            $re= $date['Hour'];
        }
        return $re;
    }
Referenced by _getStats().
GetIntIf()
GetIntIf ()
Get int_if.
Returns
string Internal interface name.
Definition at line 495 of file model.php.
    {
        return Output($this->_getIntIf());
    }
References _getIntIf(), and Output().
GetLastLogs()
GetLastLogs ($file, $count)
Definition at line 1437 of file model.php.
    {
        exec("/usr/bin/tail -$count $file", $output, $retval);
        if (!$this->ValidateFileExists($file, TRUE)) {
            return FALSE;
        }
        $logs= array();
        foreach ($output as $line) {
            unset($cols);
            if ($this->ParseLogLine($line, $cols)) {
                $logs[]= $cols;
            }
        }
        return Output(json_encode($logs));
    }
References $retval, Output(), ParseLogLine(), and ValidateFileExists().
GetLiveLogs()
GetLiveLogs ($file, $count, $re = '')
Gets logs for live logs pages.
Used to extract lines in last section of the log file or of the lines grep'd.
Difference from the archives method is that this one always gets the tail of the log or grep'd lines.
Parameters
string $file Log file.
int $count Tail length, page line count.
string $re Regexp to restrict the result set.
Returns
array Log lines.
Definition at line 1394 of file model.php.
    {
        return Output(json_encode($this->_getLiveLogs($file, $count, $re)));
    }
References _getLiveLogs(), and Output().
GetLogFilesList()
GetLogFilesList ()
Gets log files list with start dates.
Searches the logs directory for all possible archives according to the default file name.
Returns
array File names with start dates.
Definition at line 1463 of file model.php.
    {
        $file= $this->LogFile;
        $filelist= explode("\n", $this->GetFiles("$file*"));
        asort($filelist);
        $result= array();
        foreach ($filelist as $filepath) {
            $result[$filepath]= $this->_getLogStartDate($filepath);
        }
        return Output(json_encode($result));
    }
References $LogFile, _getLogStartDate(), GetFiles(), and Output().
GetLogs()
GetLogs ($file, $end, $count, $re = '', $needle = '', $month = '', $day = '', $hour = '', $minute = '')
Gets lines in log file.
Parameters
string $file Log file pathname.
int $end Head option, start line.
int $count Tail option, page line count.
string $re Regexp to restrict the result set.
string $needle Optional regexp to use with a second grep over logs, used by Stats pages.
string $month Two-digit month, or empty string for match all.
string $day Two-digit day, or empty string for match all.
string $hour Two-digit hour, or empty string for match all.
string $minute Two-digit minute, or empty string for match all.
Returns
array Log lines.
Reimplemented in Openssh, and Pf.
Definition at line 1335 of file model.php.
    {
        if (!$this->ValidateFile($file)) {
            return FALSE;
        }
        // Empty $re is not an issue for grep, greps all
        // Skip for speed, otherwise we could use datetime regexp for empty strings too
        if ($month == '' && $day == '' && $hour == '' && $minute == '') {
            $re= escapeshellarg($re);
            if ($needle == '') {
                $cmd= "/usr/bin/grep -a -E $re $file";
            }
            else {
                $needle= escapeshellarg($needle);
                $cmd= "/usr/bin/grep -a -E $needle $file | /usr/bin/grep -a -E $re";
            }
        }
        else {
            $cmd= '/usr/bin/grep -a -E "' . $this->formatDateHourRegexp($month, $day, $hour, $minute) . '" ' . $file;
            $re= escapeshellarg($re);
            if ($needle == '') {
                $cmd.= " | /usr/bin/grep -a -E $re";
            }
            else {
                $needle= escapeshellarg($needle);
                $cmd.= " | /usr/bin/grep -a -E $needle | /usr/bin/grep -a -E $re";
            }
        }
        $cmd.= " | /usr/bin/head -$end | /usr/bin/tail -$count";
        exec($cmd, $output, $retval);
        $logs= array();
        foreach ($output as $line) {
            unset($cols);
            if ($this->ParseLogLine($line, $cols)) {
                $logs[]= $cols;
            }
        }
        return Output(json_encode($logs));
    }
References $retval, formatDateHourRegexp(), Output(), ParseLogLine(), and ValidateFile().
GetLogStartDate()
GetLogStartDate ($file)
Extracts the datetime of the first line in the log file.
Works only on uncompressed log files.
Parameters
string $file Log file pathname.
Returns
string DateTime or a message if the archive is compressed.
Definition at line 1484 of file model.php.
    {
        return Output($this->_getLogStartDate($file));
    }
References _getLogStartDate(), and Output().
GetModuleStatus()
GetModuleStatus ($generate_status)
Definition at line 2797 of file model.php.
    {
        global $StatusCheckInterval;
        return Output(json_encode($this->_getModuleStatus($StatusCheckInterval, $generate_status)));
    }
References $generate_status, $StatusCheckInterval, _getModuleStatus(), and Output().
GetName()
GetName ($file, $name)
Checks if Name exists.
Parameters
string $file Config file
string $name Name of NVP
Returns
mixed Name or FALSE on failure
Definition at line 2429 of file model.php.
    {
        return $this->SearchFile($file, "/^\h*($name)(\h*$this->COMC.*|\h*)$/m");
    }
References SearchFile().
Referenced by GetValue().
GetNewsyslogConfig()
GetNewsyslogConfig ($model)
Gets newsyslog configuration for log file.
Certain log files do not have model classes, hence the $model param.
Parameters
string $model Index to $ModelsToLogConfig
Returns
mixed Configuration array or FALSE on failure
Definition at line 3088 of file model.php.
    {
        $output= FALSE;
        if (($contents= $this->GetFile($this->newSyslogConf)) !== FALSE) {
            $re_filepath= Escape($this->LogFile, '/');
            $re_owner= '([\w:]+|)';
            $re_mode= '(\d+)';
            $re_count= '(\d+)';
            $re_size= '(\d+|\*)';
            $re_when= '(\d+|\*)';
            $re= "/^\s*$re_filepath\s+$re_owner\s*$re_mode\s+$re_count\s+$re_size\s+$re_when\s+.*$/m";
            if (preg_match($re, $contents, $match)) {
                $output= array(
                    $this->LogFile => array(
                        'Model' => $model,
                        'Count' => $match[3],
                        'Size' => $match[4],
                        'When' => $match[5],
                        ),
                    );
            }
        }
        return $output;
    }
References Escape(), and GetFile().
GetNVP()
GetNVP ($file, $name, $set = 0, $trimchars = '')
Reads value of NVP.
Parameters
string $file Config file.
string $name Name of NVP.
int $set There may be multiple parentheses in $re, which one to return.
string $trimchars Chars to trim in the results.
Returns
mixed Value of NVP or FALSE on failure.
Definition at line 915 of file model.php.
    {
        return $this->SearchFile($file, "/^\h*$name\b\h*$this->NVPS\h*([^$this->COMC'\"\n]*|'[^'\n]*'|\"[^\"\n]*\"|[^$this->COMC\n]*)(\h*|\h*$this->COMC.*)$/m", $set, $trimchars);
    }
References SearchFile().
Referenced by _getExtIf(), _getIntIf(), Dnsmasq\GetListenOn(), GetValue(), and SetNVP().
GetOrigFileName()
GetOrigFileName ($logfile)
Gets the original file name for the given log file.
Parameters
string $logfile Log file.
Returns
string Log file name.
Definition at line 1594 of file model.php.
    {
        $origfilename= basename($logfile);
        // Do not append an extra .gz to compressed files
        if ((basename($this->LogFile) !== $origfilename) && !preg_match('/\.gz$/', $origfilename)) {
            $origfilename.= '.gz';
        }
        return dirname($this->LogFile).'/'.$origfilename;
    }
Referenced by CountDiffLogLines(), GetStatsFileName(), IsLogFileModified(), SaveStats(), and UpdateTmpLogFile().
GetPhyIfs()
GetPhyIfs ()
Extracts physical interface names from ifconfig output.
Removes non-physical interfaces from the output.
Returns
string Names of physical interfaces.
Definition at line 1031 of file model.php.
    {
        return Output($this->_getPhyIfs());
    }
References _getPhyIfs(), and Output().
GetProcList()
GetProcList ()
Gets the list of processes running.
Returns
mixed List of processes on success, FALSE on failure.
Definition at line 354 of file model.php.
    {
        $cmd= preg_replace('/<PROC>/', escapeshellarg($this->Proc), $this->psCmd);
        exec($cmd, $output, $retval);
        if ($retval === 0) {
            return Output(json_encode($this->SelectProcesses($output)));
        }
        Error(implode("\n", $output));
        ctlr_syslog(LOG_DEBUG, __FILE__, __FUNCTION__, __LINE__, "Process list failed for $this->Proc");
        return FALSE;
    }
References $retval, ctlr_syslog(), Error(), Output(), and SelectProcesses().
GetProcStatLines()
GetProcStatLines ($logfile)
Collects text statistics for the proc stats general page.
Builds the shell command to count with grep first. Counts the number of lines in the grep output.
Parameters
string $logfile Log file.
Returns
array Statistics.
Definition at line 1613 of file model.php.
    {
        global $StatsConf;
        if (!$this->ValidateFile($logfile)) {
            return FALSE;
        }
        $stats= array();
        foreach ($StatsConf[$this->Name] as $stat => $conf) {
            if (isset($conf['Title'])) {
                if (isset($conf['Cmd'])) {
                    $cmd= $conf['Cmd'];
                    if (isset($conf['Needle'])) {
                        $cmd.= ' | /usr/bin/grep -a -E <NDL>';
                        $cmd= preg_replace('/<NDL>/', escapeshellarg($conf['Needle']), $cmd);
                    }
                    $cmd.= ' | /usr/bin/wc -l';
                }
                else if (isset($conf['Needle'])) {
                    $cmd= '/usr/bin/grep -a -E <NDL> <LF> | /usr/bin/wc -l';
                    $cmd= preg_replace('/<NDL>/', escapeshellarg($conf['Needle']), $cmd);
                }
                if ($logfile == '') {
                    $logfile= $this->LogFile;
                }
                $cmd= preg_replace('/<LF>/', $logfile, $cmd);
                $stats[$conf['Title']]= trim($this->RunShellCommand($cmd));
            }
        }
        return Output(json_encode($stats));
    }
References $LogFile, $StatsConf, Output(), RunShellCommand(), and ValidateFile().
GetReloadRate()
GetReloadRate ()
Gets default reload rate.
Returns
string Reload rate in seconds.
Definition at line 755 of file model.php.
    {
        return Output($this->_getReloadRate());
    }
References _getReloadRate(), and Output().
getRrdfetchResolution()
getRrdfetchResolution ($output)
Definition at line 2960 of file model.php.
    {
        $resolution= 0;
        $startTime= 0;
        foreach ($output as $o) {
            // 1626645180: 0.0000000000e+00
            if (preg_match('/^(\d+):\s+\S+$/', $o, $match)) {
                if (!$startTime) {
                    $startTime= intval($match[1]);
                } else {
                    // endTime - startTime
                    $resolution= intval($match[1]) - $startTime;
                    break;
                }
            }
        }
        return $resolution;
    }
Referenced by getRrdValue().
getRrdValue()
getRrdValue ($rrd, $start = 60, & $result, $type = 'derive')
Attention
We cannot use the Interval in collectd.conf
Definition at line 2906 of file model.php.
    {
        $result= FALSE;
        $rrd= "{$this->CollectdRrdFolder}/tail-{$this->CollectdName}/$rrd";
        if (!file_exists($rrd)) {
            Error(_('RRD file does not exist').': '.$rrd);
            ctlr_syslog(LOG_INFO, __FILE__, __FUNCTION__, __LINE__, "RRD file does not exist: $rrd");
            return 0;
        }
        $value= 0;
        // Ask rrdtool to use the highest resolution possible: 10 seconds
        // Passing -r $start can produce shorter output, but it is not reliable, seems too lossy
        $cmd= "/usr/local/bin/rrdtool fetch $rrd AVERAGE -s -$start -r 10";
        exec($cmd, $output, $retval);
        if ($retval === 0) {
            if ($type == 'derive') {
                // rrdfetch chooses its own resolution close to what we asked for
                // so we have to compute it ourselves in the output
                $resolution= $this->getRrdfetchResolution($output);
                if (!$resolution) {
                    Error(_('Cannot determine the resolution in rrdfetch output').": $cmd");
                    ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Cannot determine the resolution in rrdfetch output: $cmd");
                    return 0;
                }
            }
            foreach ($output as $o) {
                if (preg_match('/^\d+:\s+(\S+)$/', $o, $match)) {
                    if ($match[1] != 'nan') {
                        $v= floatval($match[1]);
                        if ($type == 'gauge') {
                            $value= max($value, $v);
                        } else {
                            $value+= $v * $resolution;
                        }
                    }
                }
            }
        } else {
            Error(_('Failed executing rrdfetch').": $cmd");
            ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Failed executing rrdfetch: $cmd");
            return 0;
        }
        $result= TRUE;
        return round($value);
    }
References $retval, ctlr_syslog(), Error(), and getRrdfetchResolution().
Referenced by Openssh\_getModuleInfo(), _getModuleStatus(), and GetStatus().
GetSavedStats()
GetSavedStats ($logfile, & $stats, & $briefstats)
Gets saved statistics for the given log file.
Parameters
string $logfile Log file.
array $stats Statistics.
array $briefstats Brief statistics.
Returns
bool TRUE on success, FALSE on fail.
Definition at line 2033 of file model.php.
    {
        $statsfile= $this->GetStatsFileName($logfile);
        if (($filecontents= $this->GetFile($statsfile)) !== FALSE) {
            if ($serialized_stats= preg_replace("|^(<filestat>.*</filestat>\s)|m", '', $filecontents)) {
                $allstats= json_decode($serialized_stats, TRUE);
                if (isset($allstats['stats']) && isset($allstats['briefstats'])) {
                    $stats= $allstats['stats'];
                    $briefstats= $allstats['briefstats'];
                    return TRUE;
                }
                else {
                    ctlr_syslog(LOG_DEBUG, __FILE__, __FUNCTION__, __LINE__, "Missing stats in file: $statsfile");
                }
            }
            else {
                ctlr_syslog(LOG_DEBUG, __FILE__, __FUNCTION__, __LINE__, "filestat removal failed in file: $statsfile");
            }
        }
        return FALSE;
    }
References ctlr_syslog(), GetFile(), and GetStatsFileName().
Referenced by _getStats(), GetAllStats(), and UpdateStats().
GetSensors()
GetSensors ()
Finds sysctl temp and fan sensors.
There may be multiple sensors. And we don't know which is CPU sensor.
Returns
array Sensors extracted from sysctl output, FALSE if error or no sensors.
Definition at line 3177 of file model.php.
    {
        if (($hwsensors= $this->_getSysCtl('hw.sensors')) !== FALSE) {
            $hwsensors= explode("\n", $hwsensors);
            if (count($hwsensors) > 0) {
                $tempsensors= array();
                $fansensors= array();
                foreach ($hwsensors as $sensor) {
                    if (preg_match("/^hw\.sensors\.(\w+\d+\.temp\d+)/", $sensor, $match)) {
                        if (!in_array($match[1], $tempsensors)) {
                            $tempsensors[]= $match[1];
                        }
                    }
                    else if (preg_match("/^hw\.sensors\.(\w+\d+\.fan\d+)/", $sensor, $match)) {
                        if (!in_array($match[1], $fansensors)) {
                            $fansensors[]= $match[1];
                        }
                    }
                }
                return array(
                    'temp'  => $tempsensors,
                    'fan'   => $fansensors,
                    );
            }
        }
        return FALSE;
    }
References _getSysCtl().
Referenced by Symon\SetConf(), and Symon\SetSensors().
GetServiceStatus()
GetServiceStatus ($get_info = 0, $start = '10min', $interval_changed = 0)
Gets service statuses.
Definition at line 2683 of file model.php.
    {
        global $MODEL_PATH, $ModelFiles, $Models, $ModelsToStat, $DashboardIntervals2Seconds;
        if ($interval_changed) {
            $this->SetStatusCheckInterval($DashboardIntervals2Seconds[$start]);
        }
        $info= array();
        $cacheInfo= PFFWDIR.'/cache/info.json';
        if ($get_info && ($interval_changed || !$this->getCachedContents($cacheInfo, $info))) {
            if (($intif= $this->_getIntIf()) !== FALSE) {
                $intif= trim($intif, '"');
            } else {
                $intif= 'lan0';
                ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, 'Cannot get internal interface name');
            }
            if (($extif= $this->_getExtIf()) !== FALSE) {
                $extif= trim($extif, '"');
            } else {
                $extif= 'wan0';
                ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, 'Cannot get external interface name');
            }
            // @attention Use $model, not $this here, otherwise $this is an instance of System class, which has its own _getPartitions() method
            // Model has the _getPartitions() method we want
            $model= new Model();
            $partitions= $model->_getPartitions();
            $disks= array();
            foreach ($partitions as $part => $mdir) {
                if (preg_match('|/dev/((\w+\d+)[a-z]+)|', $part, $match)) {
                    if (!in_array($match[2], $disks)) {
                        $disks[]= $match[2];
                    }
                }
            }
            $disk= 'wd0';
            if (count($disks) > 0) {
                $disk= $disks[0];
            }
            exec("doas sh $MODEL_PATH/rrdgraph.sh -$start $intif $extif $disk $interval_changed", $output, $retval);
            Error(implode("\n", $output));
            foreach ($ModelsToStat as $name => $caption) {
                require_once($MODEL_PATH.'/'.$ModelFiles[$name]);
                $model= new $Models[$name]();
                $module_info= $model->_getModuleInfo($DashboardIntervals2Seconds[$start]);
                if ($module_info !== FALSE) {
                    $info[$name]= $module_info;
                }
            }
            file_put_contents($cacheInfo, json_encode($info), LOCK_EX);
        }
        $status= array();
        $cacheStatus= PFFWDIR.'/cache/status.json';
        if ($interval_changed || !$this->getCachedContents($cacheStatus, $status)) {
            foreach ($ModelsToStat as $name => $caption) {
                require_once($MODEL_PATH.'/'.$ModelFiles[$name]);
                $model= new $Models[$name]();
                // Do not cache module status individually here, we accumulate and cache them all in status.json below
                $module_status= $model->_getModuleStatus($DashboardIntervals2Seconds[$start], 1, 0);
                if ($module_status !== FALSE) {
                    $status[$name]= $module_status;
                }
            }
            file_put_contents($cacheStatus, json_encode($status), LOCK_EX);
        }
        $output= array();
        $output['status']= $status;
        if ($get_info) {
            $output['info']= $info;
        }
        if (file_exists(PFFWDIR.'/.starting')) {
            Error(_('System is starting up...'));
        }
        return Output(json_encode($output));
    }
References $DashboardIntervals2Seconds, $MODEL_PATH, $ModelFiles, $Models, $ModelsToStat, $retval, _getExtIf(), _getIntIf(), ctlr_syslog(), Error(), getCachedContents(), Output(), PFFWDIR, and SetStatusCheckInterval().
GetStats()
GetStats ($logfile, $date, $collecthours = '')
Main statistics collector, as module data set.
Parameters
string $logfile Log file pathname.
array $date Datetime struct.
bool $collecthours Flag to collect hour statistics also.
Returns
array Statistics data set collected.
Definition at line 1775 of file model.php.
    {
        return Output($this->_getStats($logfile, $date, $collecthours));
    }
References _getStats(), and Output().
GetStatsFileInfo()
GetStatsFileInfo ($logfile, & $linecount, & $filestat)
Gets previous line count and stat() from statistics file.
Parameters
string $logfile Log file.
int $linecount Previous line count.
array $filestat Previous stat() output.
Returns
bool TRUE on success, FALSE on fail.
Todo:
Should check file format too, and delete the stats file if corrupted
Definition at line 2063 of file model.php.
    {
        $linecount= 0;
        $filestat= array();
        $statsfile= $this->GetStatsFileName($logfile);
        if (file_exists($statsfile)) {
            $filestatline= $this->RunShellCommand("/usr/bin/head -1 $statsfile");
            if (preg_match('|^<filestat>(.*)</filestat>$|', $filestatline, $match)) {
                $fileinfo= json_decode($match[1], TRUE);
                $linecount= $fileinfo['linecount'];
                $filestat= $fileinfo['stat'];
                return TRUE;
            }
            else {
                ctlr_syslog(LOG_DEBUG, __FILE__, __FUNCTION__, __LINE__, "filestat missing in: $statsfile");
            }
        }
        else {
            ctlr_syslog(LOG_DEBUG, __FILE__, __FUNCTION__, __LINE__, "No such file: $statsfile");
        }
        return FALSE;
    }
References ctlr_syslog(), GetStatsFileName(), and RunShellCommand().
Referenced by CountDiffLogLines(), and IsLogFileModified().
GetStatsFileName()
GetStatsFileName ($logfile)
Gets name of the tmp statistics file for the given log file.
Parameters
string $logfile Log file.
Returns
string Statistics file name.
Definition at line 2096 of file model.php.
    {
        $origfilename= basename($this->GetOrigFileName($logfile));
        $statsdir= PFFWDIR.'/stats/'.get_class($this);
        $statsfile= "$statsdir/$origfilename";
        return $statsfile;
    }
References GetOrigFileName(), and PFFWDIR.
Referenced by GetSavedStats(), GetStatsFileInfo(), IsLogFileModified(), and SaveStats().
GetStatsLogLines()
GetStatsLogLines ($logfile, $tail = -1)
Builds generic grep command and extracts log lines.
Parameters
string $logfile Log file pathname.
int $tail Tail len to get the new log lines to update the stats with.
Returns
string Log lines.
Attention
Normally would never allow large $tail numbers here, but this $tail is computed in the code.
Definition at line 1704 of file model.php.
    {
        global $StatsConf;
        if (!$this->ValidateFile($logfile)) {
            return FALSE;
        }
        $statsdefs= $StatsConf[$this->Name];
        $needle= '';
        if (isset($statsdefs['Total']['Needle'])) {
            $needle= $statsdefs['Total']['Needle'];
        }
        $cmd= $statsdefs['Total']['Cmd'];
        if ($needle != '') {
            $needle= escapeshellarg($needle);
            $cmd.= " | /usr/bin/grep -a -E $needle";
        }
        if ($tail > -1) {
            $cmd.= " | /usr/bin/tail -$tail";
        }
        $cmd= preg_replace('/<LF>/', $logfile, $cmd);
        return $this->RunShellCommand($cmd);
    }
References $StatsConf, RunShellCommand(), and ValidateFile().
Referenced by UpdateStats().
GetStatus()
GetStatus ()
Definition at line 2979 of file model.php.
    {
        global $ModelsToStat, $StatusCheckInterval;
        $logs= $this->getFifoLogs($StatusCheckInterval);
        if ($logs === FALSE) {
            return FALSE;
        }
        if (count($logs)) {
            $prios= array(
                'critical' => array(
                    'key' => 'CRITICAL|ALERT|EMERGENCY',
                    'msg' => _TITLE('<MODEL> has CRITICAL errors'),
                    ),
                'error' => array(
                    'key' => 'ERROR',
                    'msg' => _TITLE('<MODEL> has ERRORs'),
                    ),
                'warning' => array(
                    'key' => 'WARNING',
                    'msg' => _TITLE('<MODEL> has WARNINGs'),
                    ),
                );
            foreach ($prios as $prio => $p) {
                $keys= explode('|', $p['key']);
                $errorStr= '';
                $shown= 0;
                foreach ($logs as $l) {
                    foreach ($keys as $k) {
                        if ($this->isPrio($l, $k)) {
                            if ($shown < 5) {
                                $errorStr.= "\n" . $l['Log'];
                                $shown++;
                            }
                            break;
                        }
                    }
                }
                if ($shown) {
                    $total= $this->getRrdValue("derive-$prio.rrd", $StatusCheckInterval, $result);
                    if ($total > $shown) {
                        $errorStr.= "\n" . str_replace('<COUNT>', $total - $shown, _TITLE('And <COUNT> others not shown.'));
                    }
                    Error(str_replace('<MODEL>', _($ModelsToStat[$this->Name]), _($p['msg'])) . ':' . $errorStr);
                }
            }
            Error(str_replace('<INTERVAL>', $StatusCheckInterval, _TITLE('In the last <INTERVAL> seconds.')) );
        }
        return TRUE;
    }
References $ModelsToStat, $StatusCheckInterval, _TITLE(), Error(), getFifoLogs(), getRrdValue(), and isPrio().
GetSysCtl()
GetSysCtl ($option)
Gets sysctl output for the given arg.
Parameters
string $option sysctl arg, such as hw.sensors.
Returns
string sysctl output lines.
Definition at line 3045 of file model.php.
    {
        return Output($this->_getSysCtl($option));
    }
References _getSysCtl(), and Output().
GetTmpLogFileName()
GetTmpLogFileName ($file)
Gets the name of the file in the tmp folder.
Parameters
string $file File pathname.
Returns
string Pathname of the tmp file.
Definition at line 1127 of file model.php.
    {
        if (preg_match('/(.*)\.gz$/', $file, $match)) {
            $file= $this->TmpLogsDir.basename($match[1]);
        }
        else {
            $file= $this->TmpLogsDir.basename($file);
        }
        return $file;
    }
Referenced by _getLogStartDate(), and SelectLogFile().
getValidValues()
getValidValues ($name)
Definition at line 2392 of file model.php.
    {
        $validValues= array();
        if (isset($this->Config[$name]['type'])) {
            $type= $this->Config[$name]['type'];
            if ($type == STR_on_off) {
                $validValues= array('on', 'off');
            } elseif ($type == STR_On_Off) {
                $validValues= array('On', 'Off');
            } elseif ($type == STR_yes_no) {
                $validValues= array('yes', 'no');
            }
        }
        return $validValues;
    }
References STR_on_off, STR_On_Off, and STR_yes_no.
Referenced by GetDisabledValue(), and GetValue().
GetValue()
GetValue ($name, $conf, $group)
Returns all enabled configuration for a given configuration type.
Parameters
string $name Config name
string $conf Config type
int $group E2guardian group
Returns
array Array of config items
Definition at line 2337 of file model.php.
    {
        $file= $this->GetConfFile($conf, $group);
        if ((isset($this->Config[$name]['type'])) && ($this->Config[$name]['type'] === FALSE)) {
            return $this->GetName($file, $name);
        }
        $validValues= $this->getValidValues($name);
        $value= FALSE;
        $set= 0;
        // Try max 5 possible values
        while ($set < 5) {
            $value= $this->GetNVP($file, $name, $set);
            if ($value === FALSE) {
                return FALSE;
            }
            if (!count($validValues) || in_array($value, $validValues)) {
                return "$name=$value";
            }
            ctlr_syslog(LOG_NOTICE, __FILE__, __FUNCTION__, __LINE__, "Failed validating value: $name: $value");
            $set++;
        }
        return $value;
    }
References ctlr_syslog(), GetConfFile(), GetName(), GetNVP(), and getValidValues().
Referenced by GetConfigValues().
GetVersion()
GetVersion ()
Gets software version string.
Reimplemented in Collectd, Dnsmasq, and Httpd.
Definition at line 2672 of file model.php.
    {
        if ($this->VersionCmd !== '') {
            return Output($this->RunShellCommand($this->VersionCmd.' | /usr/bin/head -1'));
        }
        return FALSE;
    }
References Output(), and RunShellCommand().
IncStats()
IncStats ($line, $values, $statsdefs, & $stats)
Increments stats for the given values.
Parameters
string $line Current log line needed to search for keywords.
array $values Log fields parsed by caller function.
array $statsdefs Module stats section of $StatsConf.
array $stats Statistics data set collected.
Definition at line 2214 of file model.php.
    {
        AddValueCreateKey($stats, 'Sum', 1);
        foreach ($statsdefs as $stat => $statconf) {
            if (isset($statconf['Counters'])) {
                foreach ($statconf['Counters'] as $counter => $conf) {
                    if (isset($values[$conf['Field']])) {
                        $value= $values[$conf['Field']];
                        if (!isset($stats[$counter])) {
                            $stats[$counter]= array();
                        }
                        AddValueCreateKey($stats[$counter], 'Sum', $value);
                        if (isset($conf['NVPs'])) {
                            foreach ($conf['NVPs'] as $name => $title) {
                                if (isset($values[$name])) {
                                    AddValueCreateKey($stats[$counter][$name], $values[$name], $value);
                                }
                            }
                        }
                    }
                }
            }
        }
        foreach ($statsdefs as $stat => $conf) {
            if (isset($conf['Needle'])) {
                if (preg_match('/'.$conf['Needle'].'/', $line)) {
                    if (!isset($stats[$stat])) {
                        $stats[$stat]= array();
                    }
                    AddValueCreateKey($stats[$stat], 'Sum', 1);
                    if (isset($conf['NVPs'])) {
                        foreach ($conf['NVPs'] as $name => $title) {
                            if (isset($values[$name])) {
                                AddValueCreateKey($stats[$stat][$name], $values[$name], 1);
                            }
                        }
                    }
                }
            }
        }
    }
References AddValueCreateKey().
Referenced by CollectDayStats(), and CollectHourStats().
IsLogFileModified()
IsLogFileModified ($logfile)
Checks if the given log file has been updated.
Compares the full stat info of the orig and tmp files. We unset the last access time before the diff, because it is updated by the stat() call itself too.
Parameters
string $logfile Log file.
Returns
bool TRUE if modified, FALSE otherwise.
Definition at line 1094 of file model.php.
    {
        $origfile= $this->GetOrigFileName($logfile);
        if ($this->GetStatsFileInfo($logfile, $linecount, $filestat)) {
            if (file_exists($origfile)) {
                $newfilestat= stat($origfile);
                $diff= array_diff($newfilestat, $filestat);
                unset($diff['8']);
                unset($diff['atime']);
                if (count($diff) === 0) {
                    ctlr_syslog(LOG_DEBUG, __FILE__, __FUNCTION__, __LINE__, "Logfile not modified: $logfile, linecount $linecount");
                    return FALSE;
                }
                // Reset the accumulated stats if the log file turned over
                if ($newfilestat['ino'] != $filestat['ino']) {
                    $statsfile= $this->GetStatsFileName($logfile);
                    exec("/bin/rm -f $statsfile 2>&1", $output, $retval);
                    ctlr_syslog(LOG_INFO, __FILE__, __FUNCTION__, __LINE__, "Logfile turned over: $logfile, deleted stats file: $statsfile");
                }
            }
        }
        return TRUE;
    }
References $retval, ctlr_syslog(), GetOrigFileName(), GetStatsFileInfo(), and GetStatsFileName().
Referenced by _getLogStartDate(), _getStats(), and SelectLogFile().
IsModulePidRunning()
IsModulePidRunning ($pid)
Checks if the pid is running.
Parameters
int $pid Pid
Returns
bool TRUE on success, FALSE on fail.
Definition at line 2660 of file model.php.
    {
        $pidcmd= "/bin/ps -o pid -p $pid | /usr/bin/grep '$pid'";
        $output= $this->RunShellCommand($pidcmd);
        return ($output !== '');
    }
References RunShellCommand().
Referenced by KillPid().
isPrio()
isPrio ($log, $prio)
Definition at line 3034 of file model.php.
    {
        return array_key_exists('Prio', $log) && strtoupper($log['Prio']) == $prio;
    }
Referenced by GetStatus().
IsRunning()
IsRunning ($proc = '')
Checks if the given process(es) is running.
Uses ps with grep.
Parameters
string $proc Module process name.
Returns
bool TRUE if there is any process running, FALSE otherwise.
Todo:
Should use pid files instead of ps, if possible at all
Reimplemented in Pf.
Definition at line 332 of file model.php.
    {
        if ($proc == '') {
            $proc= $this->Proc;
        }
        $cmd= preg_replace('/<PROC>/', escapeshellarg($proc), $this->psCmd);
        exec($cmd, $output, $retval);
        if ($retval === 0) {
            return count($this->SelectProcesses($output)) > 0;
        }
        Error(implode("\n", $output));
        ctlr_syslog(LOG_DEBUG, __FILE__, __FUNCTION__, __LINE__, "No such process: $proc");
        return FALSE;
    }
References $retval, ctlr_syslog(), Error(), and SelectProcesses().
Referenced by _getModuleStatus(), System\GetRemoteTime(), Kill(), Pkill(), and Start().
isWifiIf()
isWifiIf ($if)
Definition at line 520 of file model.php.
    {
        exec("ifconfig $if 2>/dev/null | grep -q \"^[[:space:]]*ieee80211:\"", $output, $retval);
        return $retval === 0;
    }
References $retval.
Referenced by System\_getIfConfig(), and System\NetStart().
Kill()
Kill ()
Stops module's parent process with its pid.
Todo:
Check $TmpFile for error messages, if so break out instead
Attention
Missing pid file means success, proc is not running anyway
Definition at line 2588 of file model.php.
    {
        global $TmpFile;
        if (($pid= $this->GetFile($this->PidFile)) !== FALSE) {
            $cmd= "/bin/kill $pid";
            $count= 0;
            while ($count++ < self::PROC_STAT_TIMEOUT) {
                if (!$this->IsRunning()) {
                    return TRUE;
                }
                $this->RunShellCommand("$cmd > $TmpFile 2>&1");
                exec('/bin/sleep ' . self::PROC_STAT_SLEEP_TIME);
            }
            // Check one last time due to the last sleep in the loop
            if (!$this->IsRunning()) {
                return TRUE;
            }
            // Kill command is redirected to tmp file
            $output= file_get_contents($TmpFile);
            Error($output);
            ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Kill failed with: $output");
            return FALSE;
        }
        return TRUE;
    }
References $TmpFile, ctlr_syslog(), Error(), GetFile(), IsRunning(), and RunShellCommand().
KillPid()
KillPid ($pid)
Kills process with the given pid.
Tries PROC_STAT_TIMEOUT times.
Todo:
Actually should stop retrying on some error conditions?
Parameters
int $pid Pid
Returns
bool TRUE on success, FALSE on fail.
Todo:
Check $TmpFile for error messages, if so break out instead
Kill command is redirected to tmp file
Definition at line 2629 of file model.php.
    {
        global $TmpFile;
        $cmd= '/bin/kill '.$pid;
        $count= 0;
        while ($count++ < self::PROC_STAT_TIMEOUT) {
            if (!$this->IsModulePidRunning($pid)) {
                return TRUE;
            }
            $this->RunShellCommand("$cmd > $TmpFile 2>&1");
            exec('/bin/sleep ' . self::PROC_STAT_SLEEP_TIME);
        }
        $output= file_get_contents($TmpFile);
        Error($output);
        ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Kill failed with: $output");
        // Check one last time due to the last sleep in the loop
        return !$this->IsModulePidRunning($pid);
    }
References $TmpFile, ctlr_syslog(), Error(), IsModulePidRunning(), and RunShellCommand().
ParseLogLine()
ParseLogLine ($logline, & $cols)
Parses the given log line.
Parameters
string $logline Log line.
array $cols Parsed fields.
Returns
bool TRUE on success, FALSE on fail.
Reimplemented in Dnsmasq, Ftpproxy, Fwlogs, Httpd, Httpdlogs, Openssh, and Pf.
Definition at line 1533 of file model.php.
    {
        return $this->ParseSyslogLine($logline, $cols);
    }
References ParseSyslogLine().
Referenced by _getLiveLogs(), _getLogStartDate(), GetLastLogs(), GetLogs(), and UpdateStats().
ParseSyslogLine()
ParseSyslogLine ($logline, & $cols)
Parses standard syslog line.
Parameters
string $logline Log line
array $cols Parsed fields
Returns
bool TRUE on success, FALSE on fail.
Definition at line 3062 of file model.php.
    {
        $re_datetime= '(\w+\s+\d+)\s+(\d+:\d+:\d+)';
        $re_proc= '((\S+(\[\d+\]|)):|)';
        $re_prio= '((EMERGENCY|ALERT|CRITICAL|ERROR|WARNING|NOTICE|INFO|DEBUG|emergency|alert|critical|error|warning|notice|info|debug):|)';
        $re= "/^$re_datetime\s+(\S+|)\s+$re_proc\s*$re_prio\s*(.*|)$/";
        if (preg_match($re, $logline, $match)) {
            $cols['Date']= $match[1];
            $cols['Time']= $match[2];
            $cols['Process']= $match[5];
            $cols['Prio']= $match[8];
            $cols['Log']= $match[9];
            return TRUE;
        }
        return FALSE;
    }
Referenced by Dnsmasq\ParseLogLine(), Ftpproxy\ParseLogLine(), Fwlogs\ParseLogLine(), Httpd\ParseLogLine(), Httpdlogs\ParseLogLine(), ParseLogLine(), and Openssh\ParseLogLine().
Pkill()
Pkill ($proc, $args = '')
Kills the given process(es).
Used to kill processes without a model definition, hence the $proc param. Tries PROC_STAT_TIMEOUT times.
Todo:
Actually should stop retrying on error?
Parameters
string $proc Process name
string $args Args to pass to pkill, e.g. signal name or number
Returns
bool TRUE on success, FALSE on fail.
Todo:
Check $TmpFile for error messages, if so break out instead
Definition at line 462 of file model.php.
    {
        global $TmpFile;
        $cmd= "/usr/bin/pkill $args -x $proc";
        $count= 0;
        while ($count++ < self::PROC_STAT_TIMEOUT) {
            if (!$this->IsRunning($proc)) {
                return TRUE;
            }
            $this->RunShellCommand("$cmd > $TmpFile 2>&1");
            exec('/bin/sleep ' . self::PROC_STAT_SLEEP_TIME);
        }
        // Check one last time due to the last sleep in the loop
        if (!$this->IsRunning($proc)) {
            return TRUE;
        }
        // Pkill command is redirected to the tmp file
        $output= file_get_contents($TmpFile);
        Error($output);
        ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Pkill failed for $proc with: $output");
        return FALSE;
    }
References $TmpFile, ctlr_syslog(), Error(), IsRunning(), and RunShellCommand().
Referenced by System\DisplayRemoteTime(), System\SetRemoteTime(), Collectd\Stop(), and Stop().
PostProcessCols()
PostProcessCols (& $cols)
Further processes parser output fields.
Used by statistics collector functions.
Attention
This cannot be done in the parser. Because details of the Link field is lost, which are needed on log pages.
Parameters
array $cols Updated parser output.
Reimplemented in Httpdlogs.
Definition at line 1548 of file model.php.
    {
    }
Referenced by UpdateStats().
PrepareFileForDownload()
PrepareFileForDownload ($file)
Prepares file for download over WUI.
Returns
mixed File name or FALSE on failure.
Definition at line 1557 of file model.php.
    {
        if (!$this->ValidateFile($file)) {
            return FALSE;
        }
        $tmpdir= PFFWDIR.'/downloads';
        $retval= 0;
        if (!file_exists($tmpdir)) {
            exec("/bin/mkdir -p $tmpdir 2>&1", $output, $retval);
        }
        if ($retval === 0) {
            exec("/bin/rm -f $tmpdir/* 2>&1", $output, $retval);
            if ($retval === 0) {
                $tmpfile= "$tmpdir/".basename($file);
                exec("/bin/cp $file $tmpfile 2>&1", $output, $retval);
                if ($retval === 0) {
                    exec("/sbin/chown www:www $tmpfile 2>&1", $output, $retval);
                    if ($retval === 0) {
                        return Output($tmpfile);
                    }
                }
            }
        }
        $errout= implode("\n", $output);
        Error($errout);
        ctlr_syslog(LOG_DEBUG, __FILE__, __FUNCTION__, __LINE__, "FAILED: $errout");
        return FALSE;
    }
References $retval, ctlr_syslog(), Error(), Output(), PFFWDIR, and ValidateFile().
PutFile()
PutFile ($file, $contents)
Writes contents to file.
Parameters
string $file Config filename.
string $contents Contents to write.
Returns
mixed Output of file_put_contents() or FALSE on fail.
Definition at line 862 of file model.php.
    {
        if (file_exists($file)) {
            return file_put_contents($file, $contents, LOCK_EX);
        }
        return FALSE;
    }
Referenced by SaveStats(), and SetNewsyslogConfig().
ReplaceRegexp()
ReplaceRegexp ($file, $matchre, $replacere)
Searches a needle and replaces with a value in the given file.
Parameters
string $file Config file.
string $matchre Match re.
string $replacere Replace re.
Returns
bool TRUE on success, FALSE on fail.
Definition at line 968 of file model.php.
    {
        if (copy($file, $file.'.bak')) {
            $contents= preg_replace($matchre, $replacere, file_get_contents($file), 1, $count);
            if ($contents !== NULL && $count === 1) {
                file_put_contents($file, $contents);
                return TRUE;
            }
            else {
                // Replace failure may not be important, we sometimes search and try to replace possibly nonexistent needles
                ctlr_syslog(LOG_DEBUG, __FILE__, __FUNCTION__, __LINE__, "Cannot replace in: $file");
            }
        }
        else {
            ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Cannot copy file: $file");
        }
        return FALSE;
    }
References ctlr_syslog().
Referenced by System\DelHost(), DisableName(), System\DisableNotifier(), DisableNVP(), System\DisableServiceRcConfLocal(), System\DisableServiceRcLocal(), EnableName(), System\EnableNotifier(), EnableNVP(), System\EnableServiceRcConfLocal(), System\EnableServiceRcLocal(), Symon\SetConf(), Symon\SetCpus(), Dhcpd\SetDhcpdConf(), Dhcpd\SetIfs(), Symon\SetIfs(), System\SetManCgiHome(), System\SetNameServer(), Dhcpd\SetOption(), Symon\SetPartitions(), Dhcpd\SetRange(), System\SetRootEmail(), and Symon\SetSensors().
RunShellCommand()
RunShellCommand ($cmd)
Runs the given shell command and returns its output as string.
Todo:
Fix return value checks in some references, RunShellCommand() does not return FALSE
Parameters
string $cmd Command string to run.
Returns
string Command result in a string.
Attention
Do not use shell_exec() here, because it is disabled when PHP is running in safe_mode
Warning
Not all shell commands return 0 on success, such as grep, date... Hence, do not check return value
Definition at line 791 of file model.php.
    {
        exec($cmd, $output);
        if (is_array($output)) {
            return implode("\n", $output);
        }
        return '';
    }
Referenced by Dhcpd\_getArpTable(), _getFileLineCount(), Openssh\_getFileLineCount(), Pf\_getFileLineCount(), System\_getIfConfig(), Openssh\_getLiveLogs(), Pf\_getLiveLogs(), System\_getModuleInfo(), _getPartitions(), System\_getPartitions(), _getPhyIfs(), Pf\_getStateCount(), _getSysCtl(), System\DisplayRemoteTime(), GetFileFirstLine(), GetFiles(), Openssh\GetLogs(), Pf\GetLogs(), GetProcStatLines(), GetStatsFileInfo(), GetStatsLogLines(), System\GetSystemInfo(), Collectd\GetVersion(), Dnsmasq\GetVersion(), Httpd\GetVersion(), GetVersion(), IsModulePidRunning(), Pf\IsRunning(), Kill(), KillPid(), Pkill(), System\Restart(), System\SetRemoteTime(), System\Shutdown(), and System\UpdateMailAliases().
SaveStats()
SaveStats ($logfile, $stats, $briefstats, $linecount)
Saves collected statistics with the current line count and stat() output.
Attention
Line count should be obtained before statistics collection, otherwise new lines appended during stats processing may be skipped, hence the $linecount param.
Parameters
string $logfile Log file.
array $stats Statistics.
array $briefstats Brief statistics.
int $linecount Line count.
Definition at line 2117 of file model.php.
    {
        $origfile= $this->GetOrigFileName($logfile);
        $statsfile= $this->GetStatsFileName($logfile);
        $savestats=
            '<filestat>'.
            json_encode(
                array(
                    'linecount' => $linecount,
                    'stat'      => stat($origfile),
                    )
            ).
            '</filestat>'."\n".
            json_encode(
                array(
                    'stats'     => $stats,
                    'briefstats'=> $briefstats,
                    )
            );
        $statsdir= dirname($statsfile);
        if (!file_exists($statsdir)) {
            exec('/bin/mkdir -p '.$statsdir);
        }
        exec('/usr/bin/touch '.$statsfile);
        $this->PutFile($statsfile, $savestats);
        ctlr_syslog(LOG_DEBUG, __FILE__, __FUNCTION__, __LINE__, "Saved stats to: $statsfile");
    }
References ctlr_syslog(), GetOrigFileName(), GetStatsFileName(), and PutFile().
Referenced by UpdateStats().
SearchFile()
SearchFile ($file, $re, $set = 0, $trimchars = '')
Searches the given file with the given regex.
Parameters
string $file Config file.
string $re Regex to search the file with, should have end markers.
int $set There may be multiple parentheses in $re, which one to return.
string $trimchars If given, these chars are trimmed on the left or right.
Returns
mixed String found or FALSE if no match.
Definition at line 929 of file model.php.
    {
        // There may be multiple matching NVPs
        if (preg_match_all($re, file_get_contents($file), $match)) {
            // Index 0 always gives full matches, so use index 1
            $retval= $match[1][$set];
            if ($trimchars !== '') {
                $retval= trim($retval, $trimchars);
            }
            return rtrim($retval);
        }
        return FALSE;
    }
References $retval.
Referenced by Dhcpd\_getIfs(), GetDisabledName(), GetDisabledNVP(), GetName(), System\GetNameServer(), GetNVP(), Dhcpd\GetOption(), Dhcpd\GetRange(), System\GetRootEmail(), System\GetServiceStatRcConfLocal(), System\GetServiceStatRcLocal(), and System\IsNotifierEnabled().
SearchFileAll()
SearchFileAll ($file, $re, $set = 1)
Multi-searches a given file with a given regexp.
Parameters
string $file Config file.
string $re Regexp to search the file with, should have end markers.
int $set There may be multiple parentheses in $re, which one to return.
Returns
mixed String found or FALSE on fail.
Todo:
What to do multiple matching NVPs
Definition at line 951 of file model.php.
    {
        if (preg_match_all($re, file_get_contents($file), $match)) {
            return implode("\n", array_values($match[$set]));
        }
        return FALSE;
    }
Referenced by System\GetHosts().
SelectLogFile()
SelectLogFile ($file)
Gets the log file under the tmp folder.
Updates the tmp file if the original file is modified. Updates the stat info of the file in the tmp statistics file, which is used to check file modification.
Parameters
string $file Original file name.
Returns
string Pathname of the log file.
Definition at line 1060 of file model.php.
    {
        if ($file === '') {
            $file= $this->LogFile;
        }
        if (!$this->ValidateFile($file)) {
            return FALSE;
        }
        $file= $this->GetTmpLogFileName($file);
        if (!file_exists($file) || $this->IsLogFileModified($file)) {
            if ($this->UpdateTmpLogFile($file)) {
                // Update stats to update file stat info only
                $this->UpdateStats($file, $stats, $briefstats);
            }
            else {
                $file= $this->LogFile;
                ctlr_syslog(LOG_DEBUG, __FILE__, __FUNCTION__, __LINE__, "Logfile tmp copy update failed, defaulting to: $file");
            }
        }
        return Output($file);
    }
References $LogFile, ctlr_syslog(), GetTmpLogFileName(), IsLogFileModified(), Output(), UpdateStats(), UpdateTmpLogFile(), and ValidateFile().
SelectProcesses()
SelectProcesses ($psout)
Selects user processes from ps output.
Parameters
array $psout ps output obtained elsewhere.
Returns
array Parsed ps output of user processes.
Reimplemented in System.
Definition at line 372 of file model.php.
    {
        //   PID STARTED  %CPU      TIME %MEM   RSS   VSZ STAT  PRI  NI TTY      USER     GROUP    COMMAND
        //     1  5:10PM   0.0   0:00.03  0.0   388   412 Is     10   0 ??       root     wheel    /sbin/init
        // Skip processes running on terminals, e.g. vi, tail, man
        // Select based on daemon user
        $re= "/^\s*(\d+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\d+)\s+(\d+)\s+(\S+)\s+(\d+)\s+(\d+)\s+\?\?\s+($this->User)\s+(\S+)\s+(.+)$/";
        $processes= array();
        foreach ($psout as $line) {
            if (preg_match($re, $line, $match)) {
                // Skip processes initiated by this WUI
                if (!preg_match('/\b(ctlr\.php|grep|kill|pkill)\b/', $match[13])) {
                    $processes[]= array(
                        $match[1],
                        $match[2],
                        $match[3],
                        $match[4],
                        $match[5],
                        $match[6],
                        $match[7],
                        $match[8],
                        $match[9],
                        $match[10],
                        $match[11],
                        $match[12],
                        $match[13],
                        );
                }
            }
        }
        return $processes;
    }
Referenced by GetProcList(), and IsRunning().
SetConfig()
SetConfig ($confname)
Sets configuration file based on config type provided.
Certain modules have configuration divided into multiple pages/files, hence they override this method.
Parameters
string $confname Config type
Definition at line 2581 of file model.php.
    {
    }
Referenced by DisableConf(), EnableConf(), GetConfigValues(), and SetConfValue().
SetConfValue()
SetConfValue ($name, $newvalue, $conf, $group)
Sets the value of NVP configuration.
Parameters
string $name Config name
string $newvalue New Config value
string $conf Config type
int $group E2guardian group
Returns
bool TRUE on success, FALSE on fail.
Definition at line 2455 of file model.php.
    {
        $this->SetConfig($conf);
        if (isset($this->Config[$name]['type'])) {
            $re= $this->Config[$name]['type'];
        }
        else {
            $re= '.*';
        }
        if (preg_match("/^($re)$/", $newvalue)) {
            $file= $this->GetConfFile($conf, $group);
            return $this->SetNVP($file, $name, $newvalue);
        }
        Error(_('Invalid value').": $name: $newvalue");
        ctlr_syslog(LOG_NOTICE, __FILE__, __FUNCTION__, __LINE__, "Configuration change failed, invalid value: $name: $newvalue");
        return FALSE;
    }
References ctlr_syslog(), Error(), GetConfFile(), SetConfig(), and SetNVP().
SetDefaultLocale()
SetDefaultLocale ($locale)
Sets default locale.
Parameters
string $locale Locale.
Returns
bool TRUE on success, FALSE on fail.
Definition at line 646 of file model.php.
    {
        global $ROOT, $TEST_DIR_SRC;
        // Append semi-colon to new value, this setting is a PHP line
        return $this->SetNVP($ROOT . $TEST_DIR_SRC . '/lib/setup.php', '\$DefaultLocale', $locale.';');
    }
References $ROOT, $TEST_DIR_SRC, and SetNVP().
SetForceHTTPs()
SetForceHTTPs ($bool)
Enables or disables HTTPs.
Parameters
string $bool 'TRUE' to enable, 'FALSE' otherwise.
Returns
bool TRUE on success, FALSE on fail.
Definition at line 660 of file model.php.
    {
        global $ROOT, $TEST_DIR_SRC;
        // Append semi-colon to new value, this setting is a PHP line
        return $this->SetNVP($ROOT . $TEST_DIR_SRC . '/lib/setup.php', '\$ForceHTTPs', $bool.';');
    }
References $ROOT, $TEST_DIR_SRC, and SetNVP().
SetHelpBox()
SetHelpBox ($bool)
Enables or disables help boxes.
Parameters
string $bool 'TRUE' to enable, 'FALSE' otherwise.
Returns
bool TRUE on success, FALSE on fail.
Definition at line 612 of file model.php.
    {
        global $ROOT, $TEST_DIR_SRC;
        // Append semi-colon to new value, this setting is a PHP line
        return $this->SetNVP($ROOT . $TEST_DIR_SRC . '/View/lib/setup.php', '\$ShowHelpBox', $bool.';');
    }
References $ROOT, $TEST_DIR_SRC, and SetNVP().
SetLogLevel()
SetLogLevel ($level)
Sets global log level.
Parameters
string $level Level to set to.
Returns
bool TRUE on success, FALSE on fail.
Definition at line 598 of file model.php.
    {
        global $ROOT, $TEST_DIR_SRC;
        // Append semi-colon to new value, this setting is a PHP line
        return $this->SetNVP($ROOT . $TEST_DIR_SRC . '/lib/setup.php', '\$LOG_LEVEL', $level.';');
    }
References $ROOT, $TEST_DIR_SRC, and SetNVP().
SetMaxAnchorNesting()
SetMaxAnchorNesting ($max)
Sets the max number of nested anchors allowed.
Parameters
int $max Number of nested anchors allowed.
Returns
bool TRUE on success, FALSE on fail.
Definition at line 688 of file model.php.
    {
        global $ROOT, $TEST_DIR_SRC;
        // Append semi-colon to new value, this setting is a PHP line
        return $this->SetNVP($ROOT . $TEST_DIR_SRC . '/lib/setup.php', '\$MaxAnchorNesting', $max.';');
    }
References $ROOT, $TEST_DIR_SRC, and SetNVP().
SetMaxFileSizeToProcess()
SetMaxFileSizeToProcess ($size)
Sets max file size to process.
Parameters
int $size Max size in MB.
Returns
bool TRUE on success, FALSE on fail.
Definition at line 736 of file model.php.
    {
        global $ROOT, $TEST_DIR_SRC;
        if ($size < 1) {
            $size= 1;
        } else if ($size > 1000) {
            $size= 1000;
        }
        // Append semi-colon to new value, this setting is a PHP line
        return $this->SetNVP($ROOT . $TEST_DIR_SRC . '/lib/setup.php', '\$MaxFileSizeToProcess', $size.';');
    }
References $ROOT, $TEST_DIR_SRC, and SetNVP().
SetNewsyslogConfig()
SetNewsyslogConfig ($file, $count, $size, $when)
Sets newsyslog configuration for log file.
Parameters
string $file Log file pathname
int $count How many archives to keep
int/* $size Max site to rotate, or don't care
int/* $when Interval to rotate in hours, or don't care
Returns
bool TRUE on success, FALSE on fail.
Definition at line 3123 of file model.php.
    {
        if (copy($this->newSyslogConf, $this->newSyslogConf.'.bak')) {
            if (($contents= $this->GetFile($this->newSyslogConf)) !== FALSE) {
                $re_filepath= Escape($file, '/');
                $re_owner= '([\w:]+|)';
                $re_mode= '(\d+)';
                $re_count= '(\d+)';
                $re_size= '(\d+|\*)';
                $re_when= '(\d+|\*)';
                $re= "/^(\s*$re_filepath\s+$re_owner\s*$re_mode\s+)$re_count(\s+)$re_size(\s+)$re_when(\s+.*)$/m";
                $re_replace= '${1}'.$count.'${5}'.$size.'${7}'.$when.'${9}';
                if (($newcontents= preg_replace($re, $re_replace, $contents)) !== FALSE) {
                    $this->PutFile($this->newSyslogConf, $newcontents);
                    return TRUE;
                }
                else {
                    ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Cannot set new value: $file, $count, $size, $when");
                }
            }
        }
        else {
            ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Cannot copy file $this->newSyslogConf");
        }
        return FALSE;
    }
References ctlr_syslog(), Escape(), GetFile(), and PutFile().
SetNVP()
SetNVP ($file, $name, $newvalue)
Changes value of NVP.
Parameters
string $file Config file.
string $name Name of NVP.
string $newvalue New value to set.
Returns
bool TRUE on success, FALSE on fail.
Warning
Backslash should be escaped first, or causes double escapes
Todo:
Put strings between single quotes, otherwise PHP conf files complain about certain chars, such as ':'
Definition at line 878 of file model.php.
    {
        if (copy($file, $file.'.bak')) {
            if (($value= $this->GetNVP($file, $name)) !== FALSE) {
                $value= Escape($value, '\/$^*().-[]"');
                $re= "^(\h*$name\b\h*$this->NVPS\h*)($value)(\h*$this->COMC.*|\h*)$";
                $contents= preg_replace("/$re/m", '${1}'.$newvalue.'${3}', file_get_contents($file), 1, $count);
                if ($contents !== NULL && $count == 1) {
                    file_put_contents($file, $contents);
                    return TRUE;
                }
                else {
                    ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Cannot set new value $file, $name, new: $newvalue, old: $value, re: $re, $count");
                }
            }
            else {
                ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Cannot find NVP: $file, $name");
            }
        }
        else {
            ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Cannot copy file: $file");
        }
        return FALSE;
    }
References ctlr_syslog(), Escape(), and GetNVP().
Referenced by System\AddFilter(), System\AddNotifierUser(), System\DelFilter(), System\DelNotifierUser(), System\DisableNotifierSSLVerifyPeer(), System\EnableNotifierSSLVerifyPeer(), SetConfValue(), SetDefaultLocale(), SetForceHTTPs(), SetHelpBox(), Pf\SetIfs(), Pf\SetIntnet(), Dnsmasq\SetListenOn(), SetLogLevel(), SetMaxAnchorNesting(), SetMaxFileSizeToProcess(), System\SetMFS(), System\SetMFSSize(), System\SetNotifierAPIKey(), System\SetNotifierHost(), System\SetNotifierTimeout(), System\SetNotifyLevel(), SetPfctlTimeout(), SetReloadRate(), SetSessionTimeout(), SetStatusCheckInterval(), System\SetSyncMFS(), and SetUseSSH().
SetPassword()
SetPassword ($user, $passwd)
Sets user's password in the system password file.
Note that passwords are double encrypted.
Parameters
string $user User name.
string $passwd SHA encrypted password.
Returns
bool TRUE on success, FALSE on fail.
Definition at line 571 of file model.php.
    {
        exec("/bin/cat /etc/master.passwd | /usr/bin/grep -E '^$user:' 2>&1", $output, $retval);
        if ($retval === 0) {
            $line= $output[0];
            if (preg_match("/^$user:[^:]+(:.+)$/", $line, $match)) {
                unset($output);
                $cmdline= '/usr/bin/chpass -a "' . $user . ':$(/usr/bin/encrypt ' . $passwd . ')' . $match[1] . '"';
                exec($cmdline, $output, $retval);
                if ($retval === 0) {
                    return TRUE;
                }
            }
        }
        $errout= implode("\n", $output);
        Error($errout);
        ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Set password failed: $errout");
        return FALSE;
    }
References $retval, ctlr_syslog(), and Error().
SetPfctlTimeout()
SetPfctlTimeout ($timeout)
Sets pfctl timeout.
Note that setting this value to 0 effectively fails all pfctl calls.
Parameters
int $timeout Timeout waiting pfctl output in seconds.
Returns
bool TRUE on success, FALSE on fail.
Definition at line 704 of file model.php.
    {
        global $ROOT, $TEST_DIR_SRC;
        // Append semi-colon to new value, this setting is a PHP line
        return $this->SetNVP($ROOT . $TEST_DIR_SRC . '/lib/setup.php', '\$PfctlTimeout', $timeout.';');
    }
References $ROOT, $TEST_DIR_SRC, and SetNVP().
SetReloadRate()
SetReloadRate ($rate)
Sets default reload rate.
Parameters
int $rate Reload rate in seconds.
Returns
bool TRUE on success, FALSE on fail.
Definition at line 775 of file model.php.
    {
        global $ROOT, $TEST_DIR_SRC;
        // Append semi-colon to new value, this setting is a PHP line
        return $this->SetNVP($ROOT . $TEST_DIR_SRC . '/View/lib/setup.php', '\$DefaultReloadRate', $rate.';');
    }
References $ROOT, $TEST_DIR_SRC, and SetNVP().
SetSessionTimeout()
SetSessionTimeout ($timeout)
Sets session timeout.
If the given values is less than 10, we set the timeout to 10 seconds.
Parameters
int $timeout Timeout in seconds.
Returns
bool TRUE on success, FALSE on fail.
Definition at line 628 of file model.php.
    {
        global $ROOT, $TEST_DIR_SRC;
        if ($timeout < 10) {
            $timeout= 10;
        }
        // Append semi-colon to new value, this setting is a PHP line
        return $this->SetNVP($ROOT . $TEST_DIR_SRC . '/View/lib/setup.php', '\$SessionTimeout', $timeout.';');
    }
References $ROOT, $TEST_DIR_SRC, and SetNVP().
SetStatusCheckInterval()
SetStatusCheckInterval ($interval)
Sets status check interval.
Parameters
int $interval Interval to check module statuses.
Returns
bool TRUE on success, FALSE on fail.
Definition at line 718 of file model.php.
    {
        global $ROOT, $TEST_DIR_SRC;
        if ($interval < 10) {
            $interval= 10;
        }
        // Append semi-colon to new value, this setting is a PHP line
        return $this->SetNVP($ROOT . $TEST_DIR_SRC . '/lib/setup.php', '\$StatusCheckInterval', $interval.';');
    }
References $ROOT, $TEST_DIR_SRC, and SetNVP().
Referenced by GetServiceStatus().
SetUseSSH()
SetUseSSH ($bool)
Enables or disables SSH.
Parameters
string $bool 'TRUE' to enable, 'FALSE' otherwise.
Returns
bool TRUE on success, FALSE on fail.
Definition at line 674 of file model.php.
    {
        global $ROOT, $TEST_DIR_SRC;
        // Append semi-colon to new value, this setting is a PHP line
        return $this->SetNVP($ROOT . $TEST_DIR_SRC . '/View/lib/setup.php', '\$UseSSH', $bool.';');
    }
References $ROOT, $TEST_DIR_SRC, and SetNVP().
Start()
Start ()
Start module process(es).
Waits PROC_STAT_TIMEOUT times.
Todo:
Actually should stop retrying on error?
Returns
bool TRUE on success, FALSE on fail.
Todo:
Check $TmpFile for error messages, if so break out instead
Reimplemented in Dhcpd, and Pf.
Definition at line 415 of file model.php.
    {
        global $TmpFile, $RetvalFile;
        exec($this->StartCmd." > $TmpFile 2>&1 && echo -n '0' > $RetvalFile || echo -n '1' > $RetvalFile &", $output);
        $retval= file_get_contents($RetvalFile);
        $running= FALSE;
        if ($retval === '0') {
            $count= 0;
            while (!($running= $this->IsRunning()) && $count++ < self::PROC_STAT_TIMEOUT) {
                exec('/bin/sleep ' . self::PROC_STAT_SLEEP_TIME);
            }
        }
        // Start command is redirected to tmp file, report its contents, success or failure
        $output= file_get_contents($TmpFile);
        Error($output);
        if (!$running) {
            ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Start failed with: $output");
        }
        return $running;
    }
References $retval, $RetvalFile, $TmpFile, ctlr_syslog(), Error(), and IsRunning().
Stop()
Stop ()
Stops module process(es)
Returns
bool TRUE on success, FALSE on fail.
Reimplemented in Collectd, and Pf.
Definition at line 445 of file model.php.
    {
        return $this->Pkill($this->Proc);
    }
References Pkill().
UpdateStats()
UpdateStats ($logfile, & $stats, & $briefstats)
Updates statistics incrementally, both brief and full.
Parameters
string $logfile Log file pathname.
array $stats Full stats.
array $briefstats Brief stats.
Definition at line 1919 of file model.php.
    {
        global $StatsConf;
        $stats= array();
        $briefstats= array();
        $linecount= 0;
        if (isset($StatsConf[$this->Name])) {
            $statsdefs= $StatsConf[$this->Name];
            $needle= '';
            if (isset($statsdefs['Total']['Needle'])) {
                $needle= $statsdefs['Total']['Needle'];
            }
            // Line count should be obtained here, see SaveStats() for explanation
            $linecount= $this->_getFileLineCount($logfile, $needle);
            if ($this->CountDiffLogLines($logfile, $tail)) {
                $this->GetSavedStats($logfile, $stats, $briefstats);
            }
            $lines= $this->GetStatsLogLines($logfile, $tail);
            if ($lines === FALSE) {
                return FALSE;
            }
            if ($lines !== '') {
                $lines= explode("\n", $lines);
                foreach ($lines as $line) {
                    unset($values);
                    if ($this->ParseLogLine($line, $values)) {
                        // Post-processing modifies link and/or datetime values.
                        $this->PostProcessCols($values);
                        $this->CollectDayStats($statsdefs, $values, $line, $stats);
                        $briefstatsdefs= $statsdefs['Total']['BriefStats'];
                        if (isset($briefstatsdefs)) {
                            if (!isset($briefstatsdefs['Date'])) {
                                // Always collect Date field
                                $briefstatsdefs['Date'] = _('Requests by date');
                            }
                            // Collect the fields listed under BriefStats
                            foreach ($briefstatsdefs as $name => $title) {
                                if (isset($values[$name])) {
                                    AddValueCreateKey($briefstats[$name], $values[$name], 1);
                                }
                            }
                        }
                    }
                }
            }
        }
        $this->SaveStats($logfile, $stats, $briefstats, $linecount);
    }
References $StatsConf, _getFileLineCount(), AddValueCreateKey(), CollectDayStats(), CountDiffLogLines(), GetSavedStats(), GetStatsLogLines(), ParseLogLine(), PostProcessCols(), and SaveStats().
Referenced by _getStats(), and SelectLogFile().
UpdateTmpLogFile()
UpdateTmpLogFile ($file)
Copies the original log file to tmp folder.
Parameters
string $file File pathname.
Returns
bool TRUE on success, FALSE on fail.
Definition at line 1144 of file model.php.
    {
        $origfile= $this->GetOrigFileName($file);
        if ($this->CopyLogFileToTmp($origfile, $this->TmpLogsDir)) {
            return TRUE;
        }
        ctlr_syslog(LOG_DEBUG, __FILE__, __FUNCTION__, __LINE__, "Copy failed: $file");
        return FALSE;
    }
References CopyLogFileToTmp(), ctlr_syslog(), and GetOrigFileName().
Referenced by _getStats(), and SelectLogFile().
ValidateFile()
ValidateFile ($file, $reportFileExistResult = TRUE)
Checks if the given file exists and not larger than $MaxFileSizeToProcess in MBs.
Parameters
string $file File pathname.
string $reportFileExistResult Whether to report if file does not exist.
Returns
bool TRUE on success, FALSE on fail.
Definition at line 1838 of file model.php.
    {
        global $MaxFileSizeToProcess;
        if (!$this->ValidateFileExists($file, $reportFileExistResult)) {
            return FALSE;
        }
        $filestat= stat($file);
        if ($filestat['size'] > $MaxFileSizeToProcess*1000000) {
            $error_msg= preg_replace('/<SIZE>/', $MaxFileSizeToProcess, _('File too large, will not process files larger than <SIZE> MB'));
            Error("$error_msg: $file = ".$filestat['size']);
            return FALSE;
        }
        return TRUE;
    }
References $MaxFileSizeToProcess, Error(), and ValidateFileExists().
Referenced by _getFileLineCount(), Openssh\_getFileLineCount(), Pf\_getFileLineCount(), _getLiveLogs(), Openssh\_getLiveLogs(), Pf\_getLiveLogs(), _getStats(), CopyLogFileToTmp(), GetLogs(), Openssh\GetLogs(), Pf\GetLogs(), GetProcStatLines(), GetStatsLogLines(), PrepareFileForDownload(), and SelectLogFile().
ValidateFileExists()
ValidateFileExists ($file, $reportFileExistResult = TRUE)
Definition at line 1855 of file model.php.
    {
        if (!file_exists($file)) {
            if ($reportFileExistResult) {
                Error(_('File does not exit').': '.$file);
            }
            return FALSE;
        }
        return TRUE;
    }
References Error().
Referenced by GetLastLogs(), and ValidateFile().
Field Documentation
$CmdLogStart
$CmdLogStart = '/usr/bin/head -1 <LF>'
Definition at line 70 of file model.php.
$CollectdFifoFolder
$CollectdFifoFolder = PFFWDIR.'/collectd/fifo' protected
Definition at line 82 of file model.php.
$CollectdName
$CollectdName = '' protected
Used in collectd rrd and fifo file names.
Definition at line 80 of file model.php.
$CollectdRrdFolder
$CollectdRrdFolder = PFFWDIR.'/collectd/rrd/localhost' protected
Definition at line 81 of file model.php.
$COMC
$COMC = '#'
Definition at line 56 of file model.php.
$Commands
$Commands = array()
Argument lists and descriptions of commands.
Todo:
Should we implement $Commands using Interfaces in OOP?
Parameters
array argv Array of arg types in order.
string desc Description of the shell function.
Definition at line 53 of file model.php.
$ConfFile
$ConfFile = ''
Definition at line 65 of file model.php.
$Config
$Config = ''
Definition at line 66 of file model.php.
$dateTimeFormat
$dateTimeFormat = 'M j H:i:s' protected
This datetime format is for error logs, not access logs.
Certain modules use the default syslog format.
Definition at line 88 of file model.php.
$LogFile
$LogFile = ''
Definition at line 58 of file model.php.
$Name
$Name = ''
Attention
Should be updated in constructors of children
Definition at line 30 of file model.php.
$Nesting
$Nesting = 0
Keeps the count of nested anchors in inline rules.
Definition at line 26 of file Anchor.php.
$newSyslogConf
$newSyslogConf = '/etc/newsyslog.conf' protected
Definition at line 84 of file model.php.
$NVPS
$NVPS = '='
Definition at line 55 of file model.php.
$PFFWDIR
$PFFWDIR = PFFWDIR protected
Makes the PFFWDIR define easier to use in functions, without adding a global var.
Definition at line 75 of file model.php.
$PfRulesFile
$PfRulesFile = '/etc/pf.conf'
Definition at line 63 of file model.php.
$PidFile
$PidFile = ''
Definition at line 77 of file model.php.
$Proc
$Proc = ''
Definition at line 32 of file model.php.
$psCmd
$psCmd = '/bin/ps arwwx -o pid,start,%cpu,time,%mem,rss,vsz,stat,pri,nice,tty,user,group,command | /usr/bin/grep -v -e grep | /usr/bin/grep -E <PROC>' protected
Definition at line 37 of file model.php.
$rcConfLocal
$rcConfLocal = '/etc/rc.conf.local' protected
Definition at line 61 of file model.php.
$ReloadCmd
$ReloadCmd = ''
Definition at line 68 of file model.php.
$StartCmd
$StartCmd = ''
Definition at line 39 of file model.php.
$TmpLogsDir
$TmpLogsDir = ''
Definition at line 59 of file model.php.
$User
$User = ''
Definition at line 33 of file model.php.
$VersionCmd
$VersionCmd = ''
Definition at line 72 of file model.php.
PROC_STAT_SLEEP_TIME
const PROC_STAT_SLEEP_TIME = 1
Definition at line 43 of file model.php.
PROC_STAT_TIMEOUT
const PROC_STAT_TIMEOUT = 30
Max number of iterations to try while starting or stopping processes.
Definition at line 42 of file model.php.
The documentation for this class was generated from the following files:
src/Model/model.php
src/Model/lib/Anchor.php