PF Firewall: RRDTool Class Reference
RRDTool Class Reference
Public Member Functions
__construct ()
graph ($filename, $args)
get_error ()
get_output ()
_test ()
exec ($cmdline)
Data Fields
$cmdline
$error
$output
Detailed Description
Definition at line 38 of file class_rrdtool.inc.
Constructor & Destructor Documentation
__construct()
__construct ()
Definition at line 43 of file class_rrdtool.inc.
{
    global $symon;
    $this->method = '';
    if (isset($symon['rrdtool_path'])) {
        if (!is_executable($symon['rrdtool_path'])) {
        config_error('rrdtool_path', 'is not an executable');
        return 0;
        }
    } else {
        config_error('rrdtool_path', 'is not set');
        return 0;
    }
    return 1;
    }
References $symon, and config_error().
Member Function Documentation
_test()
_test ()
Definition at line 99 of file class_rrdtool.inc.
                     {
    global $symon;
    $cmdline = $symon['rrdtool_path'] . ' -v';
    if ($this->exec($cmdline) == 0) {
        runtime_error('apache or php setup faulty: cannot execute '.$symon['rrdtool_path']);
        return 0;
    } else {
        $version_info = $this->get_output();
        if (strlen($version_info) == 0) {
        runtime_error('apache or php setup faulty: can execute '.$symon['rrdtool_path']. ', but no results are returned');
        return 0;
        } else {
        print "\xa rrdtool version: ";
        if (preg_match("/rrdtool\s+(\S+)/i", $version_info, $match)) {
            print $match[1];
        } else {
            print "unknown";
        }
        return 1;
        }
    }
    }
References $cmdline, $symon, exec(), get_output(), print, and runtime_error().
exec()
exec ($cmdline)
Definition at line 123 of file class_rrdtool.inc.
{
    global $runtime;
    $this->error = '';
    $this->output = '';
    $this->cmdline = $cmdline;
    unset($reta);
    exec($cmdline, $reta, $ret);
    if ($ret != 0) {
        foreach($reta as $key => $value) {
        $this->error .= '<pre>'.$value.'</pre><br>';
        }
        return 0;
    } else {
        foreach($reta as $value) {
        if ($value != "") {
            $this->output .= '<p>'.$value.'</p>';
        }
        }
        if (strstr($this->output, '<p>ERROR:')) {
        return 0;
        }
        return 1;
    }
    return 1;
    }
References $cmdline, and exec().
Referenced by _test(), exec(), and graph().
get_error()
get_error ()
Definition at line 91 of file class_rrdtool.inc.
{
    return $this->error;
    }
References $error.
get_output()
get_output ()
Definition at line 95 of file class_rrdtool.inc.
{
    return $this->output;
    }
References $output.
Referenced by _test(), and graph().
graph()
graph ($filename, $args)
Definition at line 61 of file class_rrdtool.inc.
{
    global $symon;
    if (!is_array($args)) {
        $temp = preg_split("/\n/", $args);
    } else {
        $temp = $args;
    }
    $args = array();
    reset($temp);
    foreach ($temp as $t) {
        if ($t == '') continue;
        if (preg_match("/^\s+$/s", $t)) continue;
        array_push($args, $t);
    }
    $cmdline = $symon['rrdtool_path'] . ' graph '. $filename .
        hash2cmdline($args) . ' 2>&1';
    $result = $this->exec($cmdline);
    if (isset($symon['rrdtool_debug'])) {
        $output = "\xa rrdtool graph debug output \xa cmdline: '$cmdline'\xa errors:'".$this->get_error()."'\xa output:'".$this->get_output()."'";
        error_log($output);
    }
    return $result;
    }
References $args, $cmdline, $output, $symon, exec(), get_output(), and hash2cmdline().
Field Documentation
$cmdline
$cmdline
Definition at line 39 of file class_rrdtool.inc.
Referenced by _test(), exec(), and graph().
$error
$error
Definition at line 40 of file class_rrdtool.inc.
Referenced by get_error().
$output
$output
Definition at line 41 of file class_rrdtool.inc.
Referenced by get_output(), and graph().
The documentation for this class was generated from the following file:
src/View/symon/class_rrdtool.inc