PF Firewall: Crypt_Base Class Reference
Crypt_Base Class Reference
Public Member Functions
__construct ($mode=CRYPT_MODE_CBC)
Default Constructor.
Crypt_Base ($mode=CRYPT_MODE_CBC)
PHP4 compatible Default Constructor.
setIV ($iv)
Sets the initialization vector.
setKeyLength ($length)
Sets the key length.
getKeyLength ()
Returns the current key length in bits.
getBlockLength ()
Returns the current block length in bits.
setKey ($key)
Sets the key.
setPassword ($password, $method='pbkdf2')
Sets the password.
encrypt ($plaintext)
Encrypts a message.
decrypt ($ciphertext)
Decrypts a message.
_openssl_ctr_process ($plaintext, &$encryptIV, &$buffer)
OpenSSL CTR Processor.
_openssl_ofb_process ($plaintext, &$encryptIV, &$buffer)
OpenSSL OFB Processor.
_openssl_translate_mode ()
phpseclib <-> OpenSSL Mode Mapper
enablePadding ()
Pad "packets".
disablePadding ()
Do not pad packets.
enableContinuousBuffer ()
Treat consecutive "packets" as if they are a continuous buffer.
disableContinuousBuffer ()
Treat consecutive packets as if they are a discontinuous buffer.
isValidEngine ($engine)
Test for engine validity.
setPreferredEngine ($engine)
Sets the preferred crypt engine.
getEngine ()
Returns the engine currently being utilized.
_setEngine ()
Sets the engine as appropriate.
_encryptBlock ($in)
Encrypts a block.
_decryptBlock ($in)
Decrypts a block.
_setupKey ()
Setup the key (expansion)
_setup ()
Setup the CRYPT_ENGINE_INTERNAL $engine.
_setupMcrypt ()
Setup the CRYPT_ENGINE_MCRYPT $engine.
_pad ($text)
Pads a string.
_unpad ($text)
Unpads a string.
_clearBuffers ()
Clears internal buffers.
_string_shift (&$string, $index=1)
String Shift.
_string_pop (&$string, $index=1)
String Pop.
_increment_str (&$var)
Increment the current string.
_setupInlineCrypt ()
Setup the performance-optimized function for de/encrypt()
_createInlineCryptFunction ($cipher_code)
Creates the performance-optimized function for en/decrypt()
& _getLambdaFunctions ()
Holds the lambda_functions table (classwide)
_hashInlineCryptFunction ($bytes)
Generates a digest from $bytes.
safe_intval ($x)
Convert float to int.
safe_intval_inline ()
eval()'able string for in-line float to int
do_nothing ()
Dummy error handler to suppress mcrypt errors.
Data Fields
$mode
$block_size = 16
$key = "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
$iv
$encryptIV
$decryptIV
$continuousBuffer = false
$enbuffer
$debuffer
$enmcrypt
$demcrypt
$enchanged = true
$dechanged = true
$ecb
$cfb_init_len = 600
$changed = true
$padding = true
$paddable = false
$engine
$preferredEngine
$cipher_name_mcrypt
$cipher_name_openssl
$cipher_name_openssl_ecb
$password_default_salt = 'phpseclib/salt'
$const_namespace
$inline_crypt
$use_inline_crypt
$openssl_emulate_ctr = false
$openssl_options
$explicit_key_length = false
$skip_key_adjustment = false
Detailed Description
Definition at line 125 of file Base.php.
Constructor & Destructor Documentation
__construct()
__construct ($mode = CRYPT_MODE_CBC)
Default Constructor.
Determines whether or not the mcrypt extension should be used.
$mode could be:
CRYPT_MODE_ECB
CRYPT_MODE_CBC
CRYPT_MODE_CTR
CRYPT_MODE_CFB
CRYPT_MODE_OFB
(or the alias constants of the chosen cipher, for example for AES: CRYPT_AES_MODE_ECB or CRYPT_AES_MODE_CBC ...)
If not explicitly set, CRYPT_MODE_CBC will be used.
Parameters
int $mode @access public
Reimplemented in Crypt_TripleDES.
Definition at line 506 of file Base.php.
    {
        // $mode dependent settings
        switch ($mode) {
            case CRYPT_MODE_ECB:
                $this->paddable = true;
                $this->mode = CRYPT_MODE_ECB;
                break;
            case CRYPT_MODE_CTR:
            case CRYPT_MODE_CFB:
            case CRYPT_MODE_OFB:
            case CRYPT_MODE_STREAM:
                $this->mode = $mode;
                break;
            case CRYPT_MODE_CBC:
            default:
                $this->paddable = true;
                $this->mode = CRYPT_MODE_CBC;
        }
        $this->_setEngine();
        // Determining whether inline crypting can be used by the cipher
        if ($this->use_inline_crypt !== false) {
            $this->use_inline_crypt = version_compare(PHP_VERSION, '5.3.0') >= 0 || function_exists('create_function');
        }
    }
References _setEngine(), CRYPT_MODE_CBC, CRYPT_MODE_CFB, CRYPT_MODE_CTR, CRYPT_MODE_ECB, CRYPT_MODE_OFB, CRYPT_MODE_STREAM, and PHP_VERSION.
Referenced by Crypt_Base().
Member Function Documentation
_clearBuffers()
_clearBuffers ()
Clears internal buffers.
Clearing/resetting the internal buffers is done everytime after disableContinuousBuffer() or on cipher $engine (re)init ie after setKey() or setIV()
@access public
Definition at line 1955 of file Base.php.
    {
        $this->enbuffer = $this->debuffer = array('ciphertext' => '', 'xor' => '', 'pos' => 0, 'enmcrypt_init' => true);
        // mcrypt's handling of invalid's $iv:
        // $this->encryptIV = $this->decryptIV = strlen($this->iv) == $this->block_size ? $this->iv : str_repeat("\0", $this->block_size);
        $this->encryptIV = $this->decryptIV = str_pad(substr($this->iv, 0, $this->block_size), $this->block_size, "\0");
        if (!$this->skip_key_adjustment) {
            $this->key = str_pad(substr($this->key, 0, $this->key_length), $this->key_length, "\0");
        }
    }
Referenced by _setup(), _setupMcrypt(), decrypt(), and encrypt().
_createInlineCryptFunction()
_createInlineCryptFunction ($cipher_code)
Creates the performance-optimized function for en/decrypt()
Internally for phpseclib developers:
_createInlineCryptFunction():
merge the $cipher_code [setup'ed by _setupInlineCrypt()] with the current [$this->]mode of operation code
create the $inline function, which called by encrypt() / decrypt() as its replacement to speed up the en/decryption operations.
return the name of the created $inline callback function
used to speed up en/decryption
The main reason why can speed up things [up to 50%] this way are:
using variables more effective then regular. (ie no use of expensive arrays but integers $k_0, $k_1 ... or even, for example, the pure $key[] values hardcoded)
avoiding 1000's of function calls of ie _encryptBlock() but inlining the crypt operations. in the mode of operation for() loop.
full loop unroll the (sometimes key-dependent) rounds avoiding this way ++$i counters and runtime-if's etc...
The basic code architectur of the generated $inline en/decrypt() lambda function, in pseudo php, is:
+-------------------------------------------------------------------------------------------—+ | callback $inline = create_function: | | lambda_function_0001_crypt_ECB($action, $text) | | { | | INSERT PHP CODE OF: | | $cipher_code['init_crypt']; // general init code. | | // ie: $sbox'es declarations used for |
// encrypt and decrypt'ing.
switch ($action) {
case 'encrypt':
INSERT PHP CODE OF:
$cipher_code['init_encrypt']; // encrypt sepcific init code.
ie: specified $key or $box
declarations for encrypt'ing.
foreach ($ciphertext) {
$in = $block_size of $ciphertext;
INSERT PHP CODE OF:
$cipher_code['encrypt_block']; // encrypt's (string) $in, which is always:
// strlen($in) == $this->block_size
// here comes the cipher algorithm in action
// for encryption.
// $cipher_code['encrypt_block'] has to
// encrypt the content of the $in variable
$plaintext .= $in;
}
return $plaintext;
case 'decrypt':
INSERT PHP CODE OF:
$cipher_code['init_decrypt']; // decrypt sepcific init code
ie: specified $key or $box
declarations for decrypt'ing.
foreach ($plaintext) {
$in = $block_size of $plaintext;
INSERT PHP CODE OF:
$cipher_code['decrypt_block']; // decrypt's (string) $in, which is always
// strlen($in) == $this->block_size
// here comes the cipher algorithm in action
// for decryption.
// $cipher_code['decrypt_block'] has to
// decrypt the content of the $in variable
$ciphertext .= $in;
}
return $ciphertext;
}
}
+-------------------------------------------------------------------------------------------—+
See also the Crypt_*::_setupInlineCrypt()'s for productive inline $cipher_code's how they works.
Structure of: $cipher_code = array('init_crypt' => (string) '', // optional 'init_encrypt' => (string) '', // optional 'init_decrypt' => (string) '', // optional 'encrypt_block' => (string) '', // required 'decrypt_block' => (string) '' // required);
See also
self::_setupInlineCrypt()
self::encrypt()
self::decrypt()
Parameters
array $cipher_code @access private
Returns
string (the name of the created callback function)
Definition at line 2221 of file Base.php.
    {
        $block_size = $this->block_size;
        // optional
        $init_crypt    = isset($cipher_code['init_crypt'])    ? $cipher_code['init_crypt']    : '';
        $init_encrypt  = isset($cipher_code['init_encrypt'])  ? $cipher_code['init_encrypt']  : '';
        $init_decrypt  = isset($cipher_code['init_decrypt'])  ? $cipher_code['init_decrypt']  : '';
        // required
        $encrypt_block = $cipher_code['encrypt_block'];
        $decrypt_block = $cipher_code['decrypt_block'];
        // Generating mode of operation inline code,
        // merged with the $cipher_code algorithm
        // for encrypt- and decryption.
        switch ($this->mode) {
            case CRYPT_MODE_ECB:
                $encrypt = $init_encrypt . '
                    $_ciphertext = "";
                    $_plaintext_len = strlen($_text);
                    for ($_i = 0; $_i < $_plaintext_len; $_i+= '.$block_size.') {
                        $in = substr($_text, $_i, '.$block_size.');
                        '.$encrypt_block.'
                        $_ciphertext.= $in;
                    }
                    return $_ciphertext;
                    ';
                $decrypt = $init_decrypt . '
                    $_plaintext = "";
                    $_text = str_pad($_text, strlen($_text) + ('.$block_size.' - strlen($_text) % '.$block_size.') % '.$block_size.', chr(0));
                    $_ciphertext_len = strlen($_text);
                    for ($_i = 0; $_i < $_ciphertext_len; $_i+= '.$block_size.') {
                        $in = substr($_text, $_i, '.$block_size.');
                        '.$decrypt_block.'
                        $_plaintext.= $in;
                    }
                    return $self->_unpad($_plaintext);
                    ';
                break;
            case CRYPT_MODE_CTR:
                $encrypt = $init_encrypt . '
                    $_ciphertext = "";
                    $_plaintext_len = strlen($_text);
                    $_xor = $self->encryptIV;
                    $_buffer = &$self->enbuffer;
                    if (strlen($_buffer["ciphertext"])) {
                        for ($_i = 0; $_i < $_plaintext_len; $_i+= '.$block_size.') {
                            $_block = substr($_text, $_i, '.$block_size.');
                            if (strlen($_block) > strlen($_buffer["ciphertext"])) {
                                $in = $_xor;
                                '.$encrypt_block.'
                                $self->_increment_str($_xor);
                                $_buffer["ciphertext"].= $in;
                            }
                            $_key = $self->_string_shift($_buffer["ciphertext"], '.$block_size.');
                            $_ciphertext.= $_block ^ $_key;
                        }
                    } else {
                        for ($_i = 0; $_i < $_plaintext_len; $_i+= '.$block_size.') {
                            $_block = substr($_text, $_i, '.$block_size.');
                            $in = $_xor;
                            '.$encrypt_block.'
                            $self->_increment_str($_xor);
                            $_key = $in;
                            $_ciphertext.= $_block ^ $_key;
                        }
                    }
                    if ($self->continuousBuffer) {
                        $self->encryptIV = $_xor;
                        if ($_start = $_plaintext_len % '.$block_size.') {
                            $_buffer["ciphertext"] = substr($_key, $_start) . $_buffer["ciphertext"];
                        }
                    }
                    return $_ciphertext;
                ';
                $decrypt = $init_encrypt . '
                    $_plaintext = "";
                    $_ciphertext_len = strlen($_text);
                    $_xor = $self->decryptIV;
                    $_buffer = &$self->debuffer;
                    if (strlen($_buffer["ciphertext"])) {
                        for ($_i = 0; $_i < $_ciphertext_len; $_i+= '.$block_size.') {
                            $_block = substr($_text, $_i, '.$block_size.');
                            if (strlen($_block) > strlen($_buffer["ciphertext"])) {
                                $in = $_xor;
                                '.$encrypt_block.'
                                $self->_increment_str($_xor);
                                $_buffer["ciphertext"].= $in;
                            }
                            $_key = $self->_string_shift($_buffer["ciphertext"], '.$block_size.');
                            $_plaintext.= $_block ^ $_key;
                        }
                    } else {
                        for ($_i = 0; $_i < $_ciphertext_len; $_i+= '.$block_size.') {
                            $_block = substr($_text, $_i, '.$block_size.');
                            $in = $_xor;
                            '.$encrypt_block.'
                            $self->_increment_str($_xor);
                            $_key = $in;
                            $_plaintext.= $_block ^ $_key;
                        }
                    }
                    if ($self->continuousBuffer) {
                        $self->decryptIV = $_xor;
                        if ($_start = $_ciphertext_len % '.$block_size.') {
                            $_buffer["ciphertext"] = substr($_key, $_start) . $_buffer["ciphertext"];
                        }
                    }
                    return $_plaintext;
                    ';
                break;
            case CRYPT_MODE_CFB:
                $encrypt = $init_encrypt . '
                    $_ciphertext = "";
                    $_buffer = &$self->enbuffer;
                    if ($self->continuousBuffer) {
                        $_iv = &$self->encryptIV;
                        $_pos = &$_buffer["pos"];
                    } else {
                        $_iv = $self->encryptIV;
                        $_pos = 0;
                    }
                    $_len = strlen($_text);
                    $_i = 0;
                    if ($_pos) {
                        $_orig_pos = $_pos;
                        $_max = '.$block_size.' - $_pos;
                        if ($_len >= $_max) {
                            $_i = $_max;
                            $_len-= $_max;
                            $_pos = 0;
                        } else {
                            $_i = $_len;
                            $_pos+= $_len;
                            $_len = 0;
                        }
                        $_ciphertext = substr($_iv, $_orig_pos) ^ $_text;
                        $_iv = substr_replace($_iv, $_ciphertext, $_orig_pos, $_i);
                    }
                    while ($_len >= '.$block_size.') {
                        $in = $_iv;
                        '.$encrypt_block.';
                        $_iv = $in ^ substr($_text, $_i, '.$block_size.');
                        $_ciphertext.= $_iv;
                        $_len-= '.$block_size.';
                        $_i+= '.$block_size.';
                    }
                    if ($_len) {
                        $in = $_iv;
                        '.$encrypt_block.'
                        $_iv = $in;
                        $_block = $_iv ^ substr($_text, $_i);
                        $_iv = substr_replace($_iv, $_block, 0, $_len);
                        $_ciphertext.= $_block;
                        $_pos = $_len;
                    }
                    return $_ciphertext;
                ';
                $decrypt = $init_encrypt . '
                    $_plaintext = "";
                    $_buffer = &$self->debuffer;
                    if ($self->continuousBuffer) {
                        $_iv = &$self->decryptIV;
                        $_pos = &$_buffer["pos"];
                    } else {
                        $_iv = $self->decryptIV;
                        $_pos = 0;
                    }
                    $_len = strlen($_text);
                    $_i = 0;
                    if ($_pos) {
                        $_orig_pos = $_pos;
                        $_max = '.$block_size.' - $_pos;
                        if ($_len >= $_max) {
                            $_i = $_max;
                            $_len-= $_max;
                            $_pos = 0;
                        } else {
                            $_i = $_len;
                            $_pos+= $_len;
                            $_len = 0;
                        }
                        $_plaintext = substr($_iv, $_orig_pos) ^ $_text;
                        $_iv = substr_replace($_iv, substr($_text, 0, $_i), $_orig_pos, $_i);
                    }
                    while ($_len >= '.$block_size.') {
                        $in = $_iv;
                        '.$encrypt_block.'
                        $_iv = $in;
                        $cb = substr($_text, $_i, '.$block_size.');
                        $_plaintext.= $_iv ^ $cb;
                        $_iv = $cb;
                        $_len-= '.$block_size.';
                        $_i+= '.$block_size.';
                    }
                    if ($_len) {
                        $in = $_iv;
                        '.$encrypt_block.'
                        $_iv = $in;
                        $_plaintext.= $_iv ^ substr($_text, $_i);
                        $_iv = substr_replace($_iv, substr($_text, $_i), 0, $_len);
                        $_pos = $_len;
                    }
                    return $_plaintext;
                    ';
                break;
            case CRYPT_MODE_OFB:
                $encrypt = $init_encrypt . '
                    $_ciphertext = "";
                    $_plaintext_len = strlen($_text);
                    $_xor = $self->encryptIV;
                    $_buffer = &$self->enbuffer;
                    if (strlen($_buffer["xor"])) {
                        for ($_i = 0; $_i < $_plaintext_len; $_i+= '.$block_size.') {
                            $_block = substr($_text, $_i, '.$block_size.');
                            if (strlen($_block) > strlen($_buffer["xor"])) {
                                $in = $_xor;
                                '.$encrypt_block.'
                                $_xor = $in;
                                $_buffer["xor"].= $_xor;
                            }
                            $_key = $self->_string_shift($_buffer["xor"], '.$block_size.');
                            $_ciphertext.= $_block ^ $_key;
                        }
                    } else {
                        for ($_i = 0; $_i < $_plaintext_len; $_i+= '.$block_size.') {
                            $in = $_xor;
                            '.$encrypt_block.'
                            $_xor = $in;
                            $_ciphertext.= substr($_text, $_i, '.$block_size.') ^ $_xor;
                        }
                        $_key = $_xor;
                    }
                    if ($self->continuousBuffer) {
                        $self->encryptIV = $_xor;
                        if ($_start = $_plaintext_len % '.$block_size.') {
                             $_buffer["xor"] = substr($_key, $_start) . $_buffer["xor"];
                        }
                    }
                    return $_ciphertext;
                    ';
                $decrypt = $init_encrypt . '
                    $_plaintext = "";
                    $_ciphertext_len = strlen($_text);
                    $_xor = $self->decryptIV;
                    $_buffer = &$self->debuffer;
                    if (strlen($_buffer["xor"])) {
                        for ($_i = 0; $_i < $_ciphertext_len; $_i+= '.$block_size.') {
                            $_block = substr($_text, $_i, '.$block_size.');
                            if (strlen($_block) > strlen($_buffer["xor"])) {
                                $in = $_xor;
                                '.$encrypt_block.'
                                $_xor = $in;
                                $_buffer["xor"].= $_xor;
                            }
                            $_key = $self->_string_shift($_buffer["xor"], '.$block_size.');
                            $_plaintext.= $_block ^ $_key;
                        }
                    } else {
                        for ($_i = 0; $_i < $_ciphertext_len; $_i+= '.$block_size.') {
                            $in = $_xor;
                            '.$encrypt_block.'
                            $_xor = $in;
                            $_plaintext.= substr($_text, $_i, '.$block_size.') ^ $_xor;
                        }
                        $_key = $_xor;
                    }
                    if ($self->continuousBuffer) {
                        $self->decryptIV = $_xor;
                        if ($_start = $_ciphertext_len % '.$block_size.') {
                             $_buffer["xor"] = substr($_key, $_start) . $_buffer["xor"];
                        }
                    }
                    return $_plaintext;
                    ';
                break;
            case CRYPT_MODE_STREAM:
                $encrypt = $init_encrypt . '
                    $_ciphertext = "";
                    '.$encrypt_block.'
                    return $_ciphertext;
                    ';
                $decrypt = $init_decrypt . '
                    $_plaintext = "";
                    '.$decrypt_block.'
                    return $_plaintext;
                    ';
                break;
            // case CRYPT_MODE_CBC:
            default:
                $encrypt = $init_encrypt . '
                    $_ciphertext = "";
                    $_plaintext_len = strlen($_text);
                    $in = $self->encryptIV;
                    for ($_i = 0; $_i < $_plaintext_len; $_i+= '.$block_size.') {
                        $in = substr($_text, $_i, '.$block_size.') ^ $in;
                        '.$encrypt_block.'
                        $_ciphertext.= $in;
                    }
                    if ($self->continuousBuffer) {
                        $self->encryptIV = $in;
                    }
                    return $_ciphertext;
                    ';
                $decrypt = $init_decrypt . '
                    $_plaintext = "";
                    $_text = str_pad($_text, strlen($_text) + ('.$block_size.' - strlen($_text) % '.$block_size.') % '.$block_size.', chr(0));
                    $_ciphertext_len = strlen($_text);
                    $_iv = $self->decryptIV;
                    for ($_i = 0; $_i < $_ciphertext_len; $_i+= '.$block_size.') {
                        $in = $_block = substr($_text, $_i, '.$block_size.');
                        '.$decrypt_block.'
                        $_plaintext.= $in ^ $_iv;
                        $_iv = $_block;
                    }
                    if ($self->continuousBuffer) {
                        $self->decryptIV = $_iv;
                    }
                    return $self->_unpad($_plaintext);
                    ';
                break;
        }
        // Create the $inline function and return its name as string. Ready to run!
        if (version_compare(PHP_VERSION, '5.3.0') >= 0) {
            eval('$func = function ($_action, &$self, $_text) { ' . $init_crypt . 'if ($_action == "encrypt") { ' . $encrypt . ' } else { ' . $decrypt . ' } };');
            return $func;
        }
        return create_function('$_action, &$self, $_text', $init_crypt . 'if ($_action == "encrypt") { ' . $encrypt . ' } else { ' . $decrypt . ' }');
    }
References CRYPT_MODE_CFB, CRYPT_MODE_CTR, CRYPT_MODE_ECB, CRYPT_MODE_OFB, CRYPT_MODE_STREAM, and PHP_VERSION.
Referenced by Crypt_Blowfish\_setupInlineCrypt(), Crypt_DES\_setupInlineCrypt(), Crypt_RC2\_setupInlineCrypt(), Crypt_Rijndael\_setupInlineCrypt(), and Crypt_Twofish\_setupInlineCrypt().
_decryptBlock()
_decryptBlock ($in)
Decrypts a block.
@access private
Parameters
string $in
Returns
string
Reimplemented in Crypt_Blowfish, Crypt_DES, Crypt_RC2, Crypt_Rijndael, and Crypt_Twofish.
Definition at line 1779 of file Base.php.
    {
        user_error((version_compare(PHP_VERSION, '5.0.0', '>=')  ? __METHOD__ : __FUNCTION__)  . '() must extend by class ' . get_class($this), E_USER_ERROR);
    }
References PHP_VERSION.
Referenced by decrypt().
_encryptBlock()
_encryptBlock ($in)
Encrypts a block.
@access private
Parameters
string $in
Returns
string
Reimplemented in Crypt_Blowfish, Crypt_DES, Crypt_RC2, Crypt_Rijndael, and Crypt_Twofish.
Definition at line 1766 of file Base.php.
    {
        user_error((version_compare(PHP_VERSION, '5.0.0', '>=')  ? __METHOD__ : __FUNCTION__)  . '() must extend by class ' . get_class($this), E_USER_ERROR);
    }
References PHP_VERSION.
Referenced by decrypt(), and encrypt().
_getLambdaFunctions()
& _getLambdaFunctions ()
Holds the lambda_functions table (classwide)
Each name of the lambda function, created from _setupInlineCrypt() && _createInlineCryptFunction() is stored, classwide (!), here for reusing.
The string-based index of $function is a classwide unique value representing, at least, the $mode of operation (or more... depends of the optimizing level) for which $mode the lambda function was created.
@access private
Returns
array &$functions
Definition at line 2593 of file Base.php.
    {
        static $functions = array();
        return $functions;
    }
Referenced by Crypt_Blowfish\_setupInlineCrypt(), Crypt_DES\_setupInlineCrypt(), Crypt_RC2\_setupInlineCrypt(), Crypt_Rijndael\_setupInlineCrypt(), and Crypt_Twofish\_setupInlineCrypt().
_hashInlineCryptFunction()
_hashInlineCryptFunction ($bytes)
Generates a digest from $bytes.
See also
self::_setupInlineCrypt() @access private
Parameters
string $bytes
Returns
string
Definition at line 2607 of file Base.php.
    {
        if (!defined('CRYPT_BASE_WHIRLPOOL_AVAILABLE')) {
            define('CRYPT_BASE_WHIRLPOOL_AVAILABLE', (bool)(extension_loaded('hash') && in_array('whirlpool', hash_algos())));
        }
        $result = '';
        $hash = $bytes;
        switch (true) {
            case CRYPT_BASE_WHIRLPOOL_AVAILABLE:
                foreach (str_split($bytes, 64) as $t) {
                    $hash = hash('whirlpool', $hash, true);
                    $result .= $t ^ $hash;
                }
                return $result . hash('whirlpool', $hash, true);
            default:
                $len = strlen($bytes);
                for ($i = 0; $i < $len; $i+=20) {
                    $t = substr($bytes, $i, 20);
                    $hash = pack('H*', sha1($hash));
                    $result .= $t ^ $hash;
                }
                return $result . pack('H*', sha1($hash));
        }
    }
Referenced by Crypt_Blowfish\_setupInlineCrypt(), Crypt_DES\_setupInlineCrypt(), Crypt_RC2\_setupInlineCrypt(), Crypt_Rijndael\_setupInlineCrypt(), and Crypt_Twofish\_setupInlineCrypt().
_increment_str()
_increment_str (& $var)
Increment the current string.
See also
self::decrypt()
self::encrypt()
Parameters
string $var @access private
Definition at line 2010 of file Base.php.
    {
        for ($i = 4; $i <= strlen($var); $i+= 4) {
            $temp = substr($var, -$i, 4);
            switch ($temp) {
                case "\xFF\xFF\xFF\xFF":
                    $var = substr_replace($var, "\x00\x00\x00\x00", -$i, 4);
                    break;
                case "\x7F\xFF\xFF\xFF":
                    $var = substr_replace($var, "\x80\x00\x00\x00", -$i, 4);
                    return;
                default:
                    $temp = unpack('Nnum', $temp);
                    $var = substr_replace($var, pack('N', $temp['num'] + 1), -$i, 4);
                    return;
            }
        }
        $remainder = strlen($var) % 4;
        if ($remainder == 0) {
            return;
        }
        $temp = unpack('Nnum', str_pad(substr($var, 0, $remainder), 4, "\0", STR_PAD_LEFT));
        $temp = substr(pack('N', $temp['num'] + 1), -$remainder);
        $var = substr_replace($var, $temp, 0, $remainder);
    }
Referenced by _openssl_ctr_process(), decrypt(), and encrypt().
_openssl_ctr_process()
_openssl_ctr_process ($plaintext, & $encryptIV, & $buffer)
OpenSSL CTR Processor.
PHP's OpenSSL bindings do not operate in continuous mode so we'll wrap around it. Since the keystream for CTR is the same for both encrypting and decrypting this function is re-used by both Crypt_Base::encrypt() and Crypt_Base::decrypt(). Also, OpenSSL doesn't implement CTR for all of it's symmetric ciphers so this function will emulate CTR with ECB when necessary.
See also
self::encrypt()
self::decrypt()
Parameters
string $plaintext
string $encryptIV
array $buffer
Returns
string @access private
Definition at line 1351 of file Base.php.
    {
        $ciphertext = '';
        $block_size = $this->block_size;
        $key = $this->key;
        if ($this->openssl_emulate_ctr) {
            $xor = $encryptIV;
            if (strlen($buffer['ciphertext'])) {
                for ($i = 0; $i < strlen($plaintext); $i+=$block_size) {
                    $block = substr($plaintext, $i, $block_size);
                    if (strlen($block) > strlen($buffer['ciphertext'])) {
                        $result = @openssl_encrypt($xor, $this->cipher_name_openssl_ecb, $key, $this->openssl_options);
                        $result = !defined('OPENSSL_RAW_DATA') ? substr($result, 0, -$this->block_size) : $result;
                        $buffer['ciphertext'].= $result;
                    }
                    $this->_increment_str($xor);
                    $otp = $this->_string_shift($buffer['ciphertext'], $block_size);
                    $ciphertext.= $block ^ $otp;
                }
            } else {
                for ($i = 0; $i < strlen($plaintext); $i+=$block_size) {
                    $block = substr($plaintext, $i, $block_size);
                    $otp = @openssl_encrypt($xor, $this->cipher_name_openssl_ecb, $key, $this->openssl_options);
                    $otp = !defined('OPENSSL_RAW_DATA') ? substr($otp, 0, -$this->block_size) : $otp;
                    $this->_increment_str($xor);
                    $ciphertext.= $block ^ $otp;
                }
            }
            if ($this->continuousBuffer) {
                $encryptIV = $xor;
                if ($start = strlen($plaintext) % $block_size) {
                    $buffer['ciphertext'] = substr($key, $start) . $buffer['ciphertext'];
                }
            }
            return $ciphertext;
        }
        if (strlen($buffer['ciphertext'])) {
            $ciphertext = $plaintext ^ $this->_string_shift($buffer['ciphertext'], strlen($plaintext));
            $plaintext = substr($plaintext, strlen($ciphertext));
            if (!strlen($plaintext)) {
                return $ciphertext;
            }
        }
        $overflow = strlen($plaintext) % $block_size;
        if ($overflow) {
            $plaintext2 = $this->_string_pop($plaintext, $overflow); // ie. trim $plaintext to a multiple of $block_size and put rest of $plaintext in $plaintext2
            $encrypted = openssl_encrypt($plaintext . str_repeat("\0", $block_size), $this->cipher_name_openssl, $key, $this->openssl_options, $encryptIV);
            $temp = $this->_string_pop($encrypted, $block_size);
            $ciphertext.= $encrypted . ($plaintext2 ^ $temp);
            if ($this->continuousBuffer) {
                $buffer['ciphertext'] = substr($temp, $overflow);
                $encryptIV = $temp;
            }
        } elseif (!strlen($buffer['ciphertext'])) {
            $ciphertext.= openssl_encrypt($plaintext . str_repeat("\0", $block_size), $this->cipher_name_openssl, $key, $this->openssl_options, $encryptIV);
            $temp = $this->_string_pop($ciphertext, $block_size);
            if ($this->continuousBuffer) {
                $encryptIV = $temp;
            }
        }
        if ($this->continuousBuffer) {
            if (!defined('OPENSSL_RAW_DATA')) {
                $encryptIV.= @openssl_encrypt('', $this->cipher_name_openssl_ecb, $key, $this->openssl_options);
            }
            $encryptIV = openssl_decrypt($encryptIV, $this->cipher_name_openssl_ecb, $key, $this->openssl_options);
            if ($overflow) {
                $this->_increment_str($encryptIV);
            }
        }
        return $ciphertext;
    }
References _increment_str(), _string_pop(), and _string_shift().
Referenced by decrypt(), and encrypt().
_openssl_ofb_process()
_openssl_ofb_process ($plaintext, & $encryptIV, & $buffer)
OpenSSL OFB Processor.
PHP's OpenSSL bindings do not operate in continuous mode so we'll wrap around it. Since the keystream for OFB is the same for both encrypting and decrypting this function is re-used by both Crypt_Base::encrypt() and Crypt_Base::decrypt().
See also
self::encrypt()
self::decrypt()
Parameters
string $plaintext
string $encryptIV
array $buffer
Returns
string @access private
Definition at line 1445 of file Base.php.
    {
        if (strlen($buffer['xor'])) {
            $ciphertext = $plaintext ^ $buffer['xor'];
            $buffer['xor'] = substr($buffer['xor'], strlen($ciphertext));
            $plaintext = substr($plaintext, strlen($ciphertext));
        } else {
            $ciphertext = '';
        }
        $block_size = $this->block_size;
        $len = strlen($plaintext);
        $key = $this->key;
        $overflow = $len % $block_size;
        if (strlen($plaintext)) {
            if ($overflow) {
                $ciphertext.= openssl_encrypt(substr($plaintext, 0, -$overflow) . str_repeat("\0", $block_size), $this->cipher_name_openssl, $key, $this->openssl_options, $encryptIV);
                $xor = $this->_string_pop($ciphertext, $block_size);
                if ($this->continuousBuffer) {
                    $encryptIV = $xor;
                }
                $ciphertext.= $this->_string_shift($xor, $overflow) ^ substr($plaintext, -$overflow);
                if ($this->continuousBuffer) {
                    $buffer['xor'] = $xor;
                }
            } else {
                $ciphertext = openssl_encrypt($plaintext, $this->cipher_name_openssl, $key, $this->openssl_options, $encryptIV);
                if ($this->continuousBuffer) {
                    $encryptIV = substr($ciphertext, -$block_size) ^ substr($plaintext, -$block_size);
                }
            }
        }
        return $ciphertext;
    }
References _string_pop(), and _string_shift().
Referenced by decrypt(), and encrypt().
_openssl_translate_mode()
_openssl_translate_mode ()
phpseclib <-> OpenSSL Mode Mapper
May need to be overwritten by classes extending this one in some cases
Returns
int @access private
Definition at line 1491 of file Base.php.
    {
        switch ($this->mode) {
            case CRYPT_MODE_ECB:
                return 'ecb';
            case CRYPT_MODE_CBC:
                return 'cbc';
            case CRYPT_MODE_CTR:
                return 'ctr';
            case CRYPT_MODE_CFB:
                return 'cfb';
            case CRYPT_MODE_OFB:
                return 'ofb';
        }
    }
References CRYPT_MODE_CBC, CRYPT_MODE_CFB, CRYPT_MODE_CTR, CRYPT_MODE_ECB, and CRYPT_MODE_OFB.
Referenced by Crypt_Blowfish\isValidEngine(), Crypt_DES\isValidEngine(), Crypt_RC2\isValidEngine(), Crypt_Rijndael\isValidEngine(), and Crypt_TripleDES\isValidEngine().
_pad()
_pad ($text)
Pads a string.
Pads a string using the RSA PKCS padding standards so that its length is a multiple of the blocksize. $this->block_size - (strlen($text) % $this->block_size) bytes are added, each of which is equal to chr($this->block_size - (strlen($text) % $this->block_size)
If padding is disabled and $text is not a multiple of the blocksize, the string will be padded regardless and padding will, hence forth, be enabled.
See also
self::_unpad()
Parameters
string $text @access private
Returns
string
Definition at line 1901 of file Base.php.
    {
        $length = strlen($text);
        if (!$this->padding) {
            if ($length % $this->block_size == 0) {
                return $text;
            } else {
                user_error("The plaintext's length ($length) is not a multiple of the block size ({$this->block_size})");
                $this->padding = true;
            }
        }
        $pad = $this->block_size - ($length % $this->block_size);
        return str_pad($text, $length + $pad, chr($pad));
    }
Referenced by encrypt(), and Crypt_TripleDES\encrypt().
_setEngine()
_setEngine ()
Sets the engine as appropriate.
See also
self::Crypt_Base() @access private
Definition at line 1720 of file Base.php.
    {
        $this->engine = null;
        $candidateEngines = array(
            $this->preferredEngine,
            CRYPT_ENGINE_OPENSSL,
            CRYPT_ENGINE_MCRYPT
        );
        foreach ($candidateEngines as $engine) {
            if ($this->isValidEngine($engine)) {
                $this->engine = $engine;
                break;
            }
        }
        if (!$this->engine) {
            $this->engine = CRYPT_ENGINE_INTERNAL;
        }
        if ($this->engine != CRYPT_ENGINE_MCRYPT && $this->enmcrypt) {
            set_error_handler(array($this, 'do_nothing'));
            // Closing the current mcrypt resource(s). _mcryptSetup() will, if needed,
            // (re)open them with the module named in $this->cipher_name_mcrypt
            mcrypt_module_close($this->enmcrypt);
            mcrypt_module_close($this->demcrypt);
            $this->enmcrypt = null;
            $this->demcrypt = null;
            if ($this->ecb) {
                mcrypt_module_close($this->ecb);
                $this->ecb = null;
            }
            restore_error_handler();
        }
        $this->changed = true;
    }
References CRYPT_ENGINE_INTERNAL, CRYPT_ENGINE_MCRYPT, CRYPT_ENGINE_OPENSSL, and isValidEngine().
Referenced by __construct(), disableContinuousBuffer(), enableContinuousBuffer(), Crypt_Rijndael\setBlockLength(), Crypt_AES\setKey(), setKey(), setKeyLength(), and setPreferredEngine().
_setup()
_setup ()
Setup the CRYPT_ENGINE_INTERNAL $engine.
(re)init, if necessary, the internal cipher $engine and flush all $buffers Used (only) if $engine == CRYPT_ENGINE_INTERNAL
_setup() will be called each time if $changed === true typically this happens when using one or more of following public methods:
setKey()
setIV()
disableContinuousBuffer()
First run of encrypt() / decrypt() with no init-settings
See also
self::setKey()
self::setIV()
self::disableContinuousBuffer() @access private
Definition at line 1822 of file Base.php.
    {
        $this->_clearBuffers();
        $this->_setupKey();
        if ($this->use_inline_crypt) {
            $this->_setupInlineCrypt();
        }
    }
References _clearBuffers(), _setupInlineCrypt(), and _setupKey().
Referenced by Crypt_RC4\_crypt(), decrypt(), and encrypt().
_setupInlineCrypt()
_setupInlineCrypt ()
Setup the performance-optimized function for de/encrypt()
Stores the created (or existing) callback function-name in $this->inline_crypt
Internally for phpseclib developers:
_setupInlineCrypt() would be called only if:
- $engine == CRYPT_ENGINE_INTERNAL and
- $use_inline_crypt === true
- each time on _setup(), after(!) _setupKey()
This ensures that _setupInlineCrypt() has always a
full ready2go initializated internal cipher $engine state
where, for example, the keys allready expanded,
keys/block_size calculated and such.
It is, each time if called, the responsibility of _setupInlineCrypt():
- to set $this->inline_crypt to a valid and fully working callback function
  as a (faster) replacement for encrypt() / decrypt()
- NOT to create unlimited callback functions (for memory reasons!)
  no matter how often _setupInlineCrypt() would be called. At some
  point of amount they must be generic re-useable.
- the code of _setupInlineCrypt() it self,
  and the generated callback code,
  must be, in following order:
  - 100% safe
  - 100% compatible to encrypt()/decrypt()
  - using only php5+ features/lang-constructs/php-extensions if
    compatibility (down to php4) or fallback is provided
  - readable/maintainable/understandable/commented and... not-cryptic-styled-code :-)
  - >= 10% faster than encrypt()/decrypt() [which is, by the way,
    the reason for the existence of _setupInlineCrypt() :-)]
  - memory-nice
  - short (as good as possible)
Note: - setupInlineCrypt() is using _createInlineCryptFunction() to create the full callback function code.
In case of using inline crypting, _setupInlineCrypt() must extend by the child Crypt* class.
The following variable names are reserved:
$_* (all variable names prefixed with an underscore)
$self (object reference to it self. Do not use $this, but $self instead)
$in (the content of $in has to en/decrypt by the generated code)
The callback function should not use the 'return' statement, but en/decrypt'ing the content of $in only
See also
self::_setup()
self::_createInlineCryptFunction()
self::encrypt()
self::decrypt() @access private
Reimplemented in Crypt_Blowfish, Crypt_DES, Crypt_RC2, Crypt_Rijndael, and Crypt_Twofish.
Definition at line 2099 of file Base.php.
    {
        // If, for any reason, an extending Crypt_Base() Crypt_* class
        // not using inline crypting then it must be ensured that: $this->use_inline_crypt = false
        // ie in the class var declaration of $use_inline_crypt in general for the Crypt_* class,
        // in the constructor at object instance-time
        // or, if it's runtime-specific, at runtime
        $this->use_inline_crypt = false;
    }
Referenced by _setup().
_setupKey()
_setupKey ()
Setup the key (expansion)
Only used if $engine == CRYPT_ENGINE_INTERNAL
See also
self::_setup() @access private
Reimplemented in Crypt_Blowfish, Crypt_DES, Crypt_RC2, Crypt_RC4, Crypt_Rijndael, Crypt_TripleDES, and Crypt_Twofish.
Definition at line 1793 of file Base.php.
    {
        user_error((version_compare(PHP_VERSION, '5.0.0', '>=')  ? __METHOD__ : __FUNCTION__)  . '() must extend by class ' . get_class($this), E_USER_ERROR);
    }
References PHP_VERSION.
Referenced by _setup().
_setupMcrypt()
_setupMcrypt ()
Setup the CRYPT_ENGINE_MCRYPT $engine.
(re)init, if necessary, the (ext)mcrypt resources and flush all $buffers Used (only) if $engine = CRYPT_ENGINE_MCRYPT
_setupMcrypt() will be called each time if $changed === true typically this happens when using one or more of following public methods:
setKey()
setIV()
disableContinuousBuffer()
First run of encrypt() / decrypt()
See also
self::setKey()
self::setIV()
self::disableContinuousBuffer() @access private
Reimplemented in Crypt_RC2.
Definition at line 1855 of file Base.php.
    {
        $this->_clearBuffers();
        $this->enchanged = $this->dechanged = true;
        if (!isset($this->enmcrypt)) {
            static $mcrypt_modes = array(
                CRYPT_MODE_CTR    => 'ctr',
                CRYPT_MODE_ECB    => MCRYPT_MODE_ECB,
                CRYPT_MODE_CBC    => MCRYPT_MODE_CBC,
                CRYPT_MODE_CFB    => 'ncfb',
                CRYPT_MODE_OFB    => MCRYPT_MODE_NOFB,
                CRYPT_MODE_STREAM => MCRYPT_MODE_STREAM,
            );
            $this->demcrypt = mcrypt_module_open($this->cipher_name_mcrypt, '', $mcrypt_modes[$this->mode], '');
            $this->enmcrypt = mcrypt_module_open($this->cipher_name_mcrypt, '', $mcrypt_modes[$this->mode], '');
            // we need the $ecb mcrypt resource (only) in MODE_CFB with enableContinuousBuffer()
            // to workaround mcrypt's broken ncfb implementation in buffered mode
            // see: {@link http://phpseclib.sourceforge.net/cfb-demo.phps}
            if ($this->mode == CRYPT_MODE_CFB) {
                $this->ecb = mcrypt_module_open($this->cipher_name_mcrypt, '', MCRYPT_MODE_ECB, '');
            }
        } // else should mcrypt_generic_deinit be called?
        if ($this->mode == CRYPT_MODE_CFB) {
            mcrypt_generic_init($this->ecb, $this->key, str_repeat("\0", $this->block_size));
        }
    }
References _clearBuffers(), CRYPT_MODE_CBC, CRYPT_MODE_CFB, CRYPT_MODE_CTR, CRYPT_MODE_ECB, CRYPT_MODE_OFB, and CRYPT_MODE_STREAM.
Referenced by decrypt(), and encrypt().
_string_pop()
_string_pop (& $string, $index = 1)
String Pop.
Inspired by array_pop
Parameters
string $string
int $index @access private
Returns
string
Definition at line 1995 of file Base.php.
    {
        $substr = substr($string, -$index);
        $string = substr($string, 0, -$index);
        return $substr;
    }
Referenced by _openssl_ctr_process(), _openssl_ofb_process(), and encrypt().
_string_shift()
_string_shift (& $string, $index = 1)
String Shift.
Inspired by array_shift
Parameters
string $string
int $index @access private
Returns
string
Definition at line 1978 of file Base.php.
    {
        $substr = substr($string, 0, $index);
        $string = substr($string, $index);
        return $substr;
    }
Referenced by _openssl_ctr_process(), _openssl_ofb_process(), decrypt(), and encrypt().
_unpad()
_unpad ($text)
Unpads a string.
If padding is enabled and the reported padding length is invalid the encryption key will be assumed to be wrong and false will be returned.
See also
self::_pad()
Parameters
string $text @access private
Returns
string
Definition at line 1930 of file Base.php.
    {
        if (!$this->padding) {
            return $text;
        }
        $length = ord($text[strlen($text) - 1]);
        if (!$length || $length > $this->block_size) {
            return false;
        }
        return substr($text, 0, -$length);
    }
Referenced by decrypt(), and Crypt_TripleDES\decrypt().
Crypt_Base()
Crypt_Base ($mode = CRYPT_MODE_CBC)
PHP4 compatible Default Constructor.
See also
self::__construct()
Parameters
int $mode @access public
Definition at line 541 of file Base.php.
    {
        $this->__construct($mode);
    }
References __construct().
decrypt()
decrypt ($ciphertext)
Decrypts a message.
If strlen($ciphertext) is not a multiple of the block size, null bytes will be added to the end of the string until it is.
See also
self::encrypt() @access public
Parameters
string $ciphertext
Returns
string $plaintext
Reimplemented in Crypt_RC2, Crypt_RC4, and Crypt_TripleDES.
Definition at line 1050 of file Base.php.
    {
        if ($this->paddable) {
            // we pad with chr(0) since that's what mcrypt_generic does.  to quote from {@link http://www.php.net/function.mcrypt-generic}:
            // "The data is padded with "\0" to make sure the length of the data is n * blocksize."
            $ciphertext = str_pad($ciphertext, strlen($ciphertext) + ($this->block_size - strlen($ciphertext) % $this->block_size) % $this->block_size, chr(0));
        }
        if ($this->engine === CRYPT_ENGINE_OPENSSL) {
            if ($this->changed) {
                $this->_clearBuffers();
                $this->changed = false;
            }
            switch ($this->mode) {
                case CRYPT_MODE_STREAM:
                    $plaintext = openssl_decrypt($ciphertext, $this->cipher_name_openssl, $this->key, $this->openssl_options);
                    break;
                case CRYPT_MODE_ECB:
                    if (!defined('OPENSSL_RAW_DATA')) {
                        $ciphertext.= @openssl_encrypt('', $this->cipher_name_openssl_ecb, $this->key, true);
                    }
                    $plaintext = openssl_decrypt($ciphertext, $this->cipher_name_openssl, $this->key, $this->openssl_options);
                    break;
                case CRYPT_MODE_CBC:
                    if (!defined('OPENSSL_RAW_DATA')) {
                        $padding = str_repeat(chr($this->block_size), $this->block_size) ^ substr($ciphertext, -$this->block_size);
                        $ciphertext.= substr(@openssl_encrypt($padding, $this->cipher_name_openssl_ecb, $this->key, true), 0, $this->block_size);
                        $offset = 2 * $this->block_size;
                    } else {
                        $offset = $this->block_size;
                    }
                    $plaintext = openssl_decrypt($ciphertext, $this->cipher_name_openssl, $this->key, $this->openssl_options, $this->decryptIV);
                    if ($this->continuousBuffer) {
                        $this->decryptIV = substr($ciphertext, -$offset, $this->block_size);
                    }
                    break;
                case CRYPT_MODE_CTR:
                    $plaintext = $this->_openssl_ctr_process($ciphertext, $this->decryptIV, $this->debuffer);
                    break;
                case CRYPT_MODE_CFB:
                    // cfb loosely routines inspired by openssl's:
                    // {@link http://cvs.openssl.org/fileview?f=openssl/crypto/modes/cfb128.c&v=1.3.2.2.2.1}
                    $plaintext = '';
                    if ($this->continuousBuffer) {
                        $iv = &$this->decryptIV;
                        $pos = &$this->buffer['pos'];
                    } else {
                        $iv = $this->decryptIV;
                        $pos = 0;
                    }
                    $len = strlen($ciphertext);
                    $i = 0;
                    if ($pos) {
                        $orig_pos = $pos;
                        $max = $this->block_size - $pos;
                        if ($len >= $max) {
                            $i = $max;
                            $len-= $max;
                            $pos = 0;
                        } else {
                            $i = $len;
                            $pos+= $len;
                            $len = 0;
                        }
                        // ie. $i = min($max, $len), $len-= $i, $pos+= $i, $pos%= $this->blocksize
                        $plaintext = substr($iv, $orig_pos) ^ $ciphertext;
                        $iv = substr_replace($iv, substr($ciphertext, 0, $i), $orig_pos, $i);
                        $ciphertext = substr($ciphertext, $i);
                    }
                    $overflow = $len % $this->block_size;
                    if ($overflow) {
                        $plaintext.= openssl_decrypt(substr($ciphertext, 0, -$overflow), $this->cipher_name_openssl, $this->key, $this->openssl_options, $iv);
                        if ($len - $overflow) {
                            $iv = substr($ciphertext, -$overflow - $this->block_size, -$overflow);
                        }
                        $iv = openssl_encrypt(str_repeat("\0", $this->block_size), $this->cipher_name_openssl, $this->key, $this->openssl_options, $iv);
                        $plaintext.= $iv ^ substr($ciphertext, -$overflow);
                        $iv = substr_replace($iv, substr($ciphertext, -$overflow), 0, $overflow);
                        $pos = $overflow;
                    } elseif ($len) {
                        $plaintext.= openssl_decrypt($ciphertext, $this->cipher_name_openssl, $this->key, $this->openssl_options, $iv);
                        $iv = substr($ciphertext, -$this->block_size);
                    }
                    break;
                case CRYPT_MODE_OFB:
                    $plaintext = $this->_openssl_ofb_process($ciphertext, $this->decryptIV, $this->debuffer);
            }
            return $this->paddable ? $this->_unpad($plaintext) : $plaintext;
        }
        if ($this->engine === CRYPT_ENGINE_MCRYPT) {
            set_error_handler(array($this, 'do_nothing'));
            $block_size = $this->block_size;
            if ($this->changed) {
                $this->_setupMcrypt();
                $this->changed = false;
            }
            if ($this->dechanged) {
                mcrypt_generic_init($this->demcrypt, $this->key, $this->decryptIV);
                $this->dechanged = false;
            }
            if ($this->mode == CRYPT_MODE_CFB && $this->continuousBuffer) {
                $iv = &$this->decryptIV;
                $pos = &$this->debuffer['pos'];
                $len = strlen($ciphertext);
                $plaintext = '';
                $i = 0;
                if ($pos) {
                    $orig_pos = $pos;
                    $max = $block_size - $pos;
                    if ($len >= $max) {
                        $i = $max;
                        $len-= $max;
                        $pos = 0;
                    } else {
                        $i = $len;
                        $pos+= $len;
                        $len = 0;
                    }
                    // ie. $i = min($max, $len), $len-= $i, $pos+= $i, $pos%= $blocksize
                    $plaintext = substr($iv, $orig_pos) ^ $ciphertext;
                    $iv = substr_replace($iv, substr($ciphertext, 0, $i), $orig_pos, $i);
                }
                if ($len >= $block_size) {
                    $cb = substr($ciphertext, $i, $len - $len % $block_size);
                    $plaintext.= mcrypt_generic($this->ecb, $iv . $cb) ^ $cb;
                    $iv = substr($cb, -$block_size);
                    $len%= $block_size;
                }
                if ($len) {
                    $iv = mcrypt_generic($this->ecb, $iv);
                    $plaintext.= $iv ^ substr($ciphertext, -$len);
                    $iv = substr_replace($iv, substr($ciphertext, -$len), 0, $len);
                    $pos = $len;
                }
                restore_error_handler();
                return $plaintext;
            }
            $plaintext = mdecrypt_generic($this->demcrypt, $ciphertext);
            if (!$this->continuousBuffer) {
                mcrypt_generic_init($this->demcrypt, $this->key, $this->decryptIV);
            }
            restore_error_handler();
            return $this->paddable ? $this->_unpad($plaintext) : $plaintext;
        }
        if ($this->changed) {
            $this->_setup();
            $this->changed = false;
        }
        if ($this->use_inline_crypt) {
            $inline = $this->inline_crypt;
            return $inline('decrypt', $this, $ciphertext);
        }
        $block_size = $this->block_size;
        $buffer = &$this->debuffer;
        $plaintext = '';
        switch ($this->mode) {
            case CRYPT_MODE_ECB:
                for ($i = 0; $i < strlen($ciphertext); $i+=$block_size) {
                    $plaintext.= $this->_decryptBlock(substr($ciphertext, $i, $block_size));
                }
                break;
            case CRYPT_MODE_CBC:
                $xor = $this->decryptIV;
                for ($i = 0; $i < strlen($ciphertext); $i+=$block_size) {
                    $block = substr($ciphertext, $i, $block_size);
                    $plaintext.= $this->_decryptBlock($block) ^ $xor;
                    $xor = $block;
                }
                if ($this->continuousBuffer) {
                    $this->decryptIV = $xor;
                }
                break;
            case CRYPT_MODE_CTR:
                $xor = $this->decryptIV;
                if (strlen($buffer['ciphertext'])) {
                    for ($i = 0; $i < strlen($ciphertext); $i+=$block_size) {
                        $block = substr($ciphertext, $i, $block_size);
                        if (strlen($block) > strlen($buffer['ciphertext'])) {
                            $buffer['ciphertext'].= $this->_encryptBlock($xor);
                            $this->_increment_str($xor);
                        }
                        $key = $this->_string_shift($buffer['ciphertext'], $block_size);
                        $plaintext.= $block ^ $key;
                    }
                } else {
                    for ($i = 0; $i < strlen($ciphertext); $i+=$block_size) {
                        $block = substr($ciphertext, $i, $block_size);
                        $key = $this->_encryptBlock($xor);
                        $this->_increment_str($xor);
                        $plaintext.= $block ^ $key;
                    }
                }
                if ($this->continuousBuffer) {
                    $this->decryptIV = $xor;
                    if ($start = strlen($ciphertext) % $block_size) {
                        $buffer['ciphertext'] = substr($key, $start) . $buffer['ciphertext'];
                    }
                }
                break;
            case CRYPT_MODE_CFB:
                if ($this->continuousBuffer) {
                    $iv = &$this->decryptIV;
                    $pos = &$buffer['pos'];
                } else {
                    $iv = $this->decryptIV;
                    $pos = 0;
                }
                $len = strlen($ciphertext);
                $i = 0;
                if ($pos) {
                    $orig_pos = $pos;
                    $max = $block_size - $pos;
                    if ($len >= $max) {
                        $i = $max;
                        $len-= $max;
                        $pos = 0;
                    } else {
                        $i = $len;
                        $pos+= $len;
                        $len = 0;
                    }
                    // ie. $i = min($max, $len), $len-= $i, $pos+= $i, $pos%= $blocksize
                    $plaintext = substr($iv, $orig_pos) ^ $ciphertext;
                    $iv = substr_replace($iv, substr($ciphertext, 0, $i), $orig_pos, $i);
                }
                while ($len >= $block_size) {
                    $iv = $this->_encryptBlock($iv);
                    $cb = substr($ciphertext, $i, $block_size);
                    $plaintext.= $iv ^ $cb;
                    $iv = $cb;
                    $len-= $block_size;
                    $i+= $block_size;
                }
                if ($len) {
                    $iv = $this->_encryptBlock($iv);
                    $plaintext.= $iv ^ substr($ciphertext, $i);
                    $iv = substr_replace($iv, substr($ciphertext, $i), 0, $len);
                    $pos = $len;
                }
                break;
            case CRYPT_MODE_OFB:
                $xor = $this->decryptIV;
                if (strlen($buffer['xor'])) {
                    for ($i = 0; $i < strlen($ciphertext); $i+=$block_size) {
                        $block = substr($ciphertext, $i, $block_size);
                        if (strlen($block) > strlen($buffer['xor'])) {
                            $xor = $this->_encryptBlock($xor);
                            $buffer['xor'].= $xor;
                        }
                        $key = $this->_string_shift($buffer['xor'], $block_size);
                        $plaintext.= $block ^ $key;
                    }
                } else {
                    for ($i = 0; $i < strlen($ciphertext); $i+=$block_size) {
                        $xor = $this->_encryptBlock($xor);
                        $plaintext.= substr($ciphertext, $i, $block_size) ^ $xor;
                    }
                    $key = $xor;
                }
                if ($this->continuousBuffer) {
                    $this->decryptIV = $xor;
                    if ($start = strlen($ciphertext) % $block_size) {
                        $buffer['xor'] = substr($key, $start) . $buffer['xor'];
                    }
                }
                break;
            case CRYPT_MODE_STREAM:
                $plaintext = $this->_decryptBlock($ciphertext);
                break;
        }
        return $this->paddable ? $this->_unpad($plaintext) : $plaintext;
    }
References _clearBuffers(), _decryptBlock(), _encryptBlock(), _increment_str(), _openssl_ctr_process(), _openssl_ofb_process(), _setup(), _setupMcrypt(), _string_shift(), _unpad(), CRYPT_ENGINE_MCRYPT, CRYPT_ENGINE_OPENSSL, CRYPT_MODE_CBC, CRYPT_MODE_CFB, CRYPT_MODE_CTR, CRYPT_MODE_ECB, CRYPT_MODE_OFB, and CRYPT_MODE_STREAM.
disableContinuousBuffer()
disableContinuousBuffer ()
Treat consecutive packets as if they are a discontinuous buffer.
The default behavior.
See also
self::enableContinuousBuffer() @access public
Reimplemented in Crypt_TripleDES.
Definition at line 1596 of file Base.php.
    {
        if ($this->mode == CRYPT_MODE_ECB) {
            return;
        }
        if (!$this->continuousBuffer) {
            return;
        }
        $this->continuousBuffer = false;
        $this->changed = true;
        $this->_setEngine();
    }
References _setEngine(), and CRYPT_MODE_ECB.
disablePadding()
disablePadding ()
Do not pad packets.
See also
self::enablePadding() @access public
Definition at line 1533 of file Base.php.
    {
        $this->padding = false;
    }
do_nothing()
do_nothing ()
Dummy error handler to suppress mcrypt errors.
@access private
Definition at line 2683 of file Base.php.
    {
    }
enableContinuousBuffer()
enableContinuousBuffer ()
Treat consecutive "packets" as if they are a continuous buffer.
Say you have a 32-byte plaintext $plaintext. Using the default behavior, the two following code snippets will yield different outputs:
echo $rijndael->encrypt(substr($plaintext, 0, 16)); echo $rijndael->encrypt(substr($plaintext, 16, 16)); echo $rijndael->encrypt($plaintext);
The solution is to enable the continuous buffer. Although this will resolve the above discrepancy, it creates another, as demonstrated with the following:
$rijndael->encrypt(substr($plaintext, 0, 16)); echo $rijndael->decrypt($rijndael->encrypt(substr($plaintext, 16, 16))); echo $rijndael->decrypt($rijndael->encrypt(substr($plaintext, 16, 16)));
With the continuous buffer disabled, these would yield the same output. With it enabled, they yield different outputs. The reason is due to the fact that the initialization vector's change after every encryption / decryption round when the continuous buffer is enabled. When it's disabled, they remain constant.
Put another way, when the continuous buffer is enabled, the state of the Crypt_*() object changes after each encryption / decryption round, whereas otherwise, it'd remain constant. For this reason, it's recommended that continuous buffers not be used. They do offer better security and are, in fact, sometimes required (SSH uses them), however, they are also less intuitive and more likely to cause you problems.
See also
self::disableContinuousBuffer() @access public
Reimplemented in Crypt_TripleDES.
Definition at line 1576 of file Base.php.
    {
        if ($this->mode == CRYPT_MODE_ECB) {
            return;
        }
        $this->continuousBuffer = true;
        $this->_setEngine();
    }
References _setEngine(), and CRYPT_MODE_ECB.
enablePadding()
enablePadding ()
Pad "packets".
Block ciphers working by encrypting between their specified [$this->]block_size at a time If you ever need to encrypt or decrypt something that isn't of the proper length, it becomes necessary to pad the input so that it is of the proper length.
Padding is enabled by default. Sometimes, however, it is undesirable to pad strings. Such is the case in SSH, where "packets" are padded with random bytes before being encrypted. Unpad these packets and you risk stripping away characters that shouldn't be stripped away. (SSH knows how many bytes are added because the length is transmitted separately)
See also
self::disablePadding() @access public
Definition at line 1522 of file Base.php.
    {
        $this->padding = true;
    }
encrypt()
encrypt ($plaintext)
Encrypts a message.
$plaintext will be padded with additional bytes such that it's length is a multiple of the block size. Other cipher implementations may or may not pad in the same manner. Other common approaches to padding and the reasons why it's necessary are discussed in the following URL:
http://www.di-mgt.com.au/cryptopad.html
An alternative to padding is to, separately, send the length of the file. This is what SSH, in fact, does. strlen($plaintext) will still need to be a multiple of the block size, however, arbitrary values can be added to make it that length.
See also
self::decrypt() @access public
Parameters
string $plaintext
Returns
string $ciphertext
Reimplemented in Crypt_RC2, Crypt_RC4, and Crypt_TripleDES.
Definition at line 744 of file Base.php.
    {
        if ($this->paddable) {
            $plaintext = $this->_pad($plaintext);
        }
        if ($this->engine === CRYPT_ENGINE_OPENSSL) {
            if ($this->changed) {
                $this->_clearBuffers();
                $this->changed = false;
            }
            switch ($this->mode) {
                case CRYPT_MODE_STREAM:
                    return openssl_encrypt($plaintext, $this->cipher_name_openssl, $this->key, $this->openssl_options);
                case CRYPT_MODE_ECB:
                    $result = @openssl_encrypt($plaintext, $this->cipher_name_openssl, $this->key, $this->openssl_options);
                    return !defined('OPENSSL_RAW_DATA') ? substr($result, 0, -$this->block_size) : $result;
                case CRYPT_MODE_CBC:
                    $result = openssl_encrypt($plaintext, $this->cipher_name_openssl, $this->key, $this->openssl_options, $this->encryptIV);
                    if (!defined('OPENSSL_RAW_DATA')) {
                        $result = substr($result, 0, -$this->block_size);
                    }
                    if ($this->continuousBuffer) {
                        $this->encryptIV = substr($result, -$this->block_size);
                    }
                    return $result;
                case CRYPT_MODE_CTR:
                    return $this->_openssl_ctr_process($plaintext, $this->encryptIV, $this->enbuffer);
                case CRYPT_MODE_CFB:
                    // cfb loosely routines inspired by openssl's:
                    // {@link http://cvs.openssl.org/fileview?f=openssl/crypto/modes/cfb128.c&v=1.3.2.2.2.1}
                    $ciphertext = '';
                    if ($this->continuousBuffer) {
                        $iv = &$this->encryptIV;
                        $pos = &$this->enbuffer['pos'];
                    } else {
                        $iv = $this->encryptIV;
                        $pos = 0;
                    }
                    $len = strlen($plaintext);
                    $i = 0;
                    if ($pos) {
                        $orig_pos = $pos;
                        $max = $this->block_size - $pos;
                        if ($len >= $max) {
                            $i = $max;
                            $len-= $max;
                            $pos = 0;
                        } else {
                            $i = $len;
                            $pos+= $len;
                            $len = 0;
                        }
                        // ie. $i = min($max, $len), $len-= $i, $pos+= $i, $pos%= $blocksize
                        $ciphertext = substr($iv, $orig_pos) ^ $plaintext;
                        $iv = substr_replace($iv, $ciphertext, $orig_pos, $i);
                        $plaintext = substr($plaintext, $i);
                    }
                    $overflow = $len % $this->block_size;
                    if ($overflow) {
                        $ciphertext.= openssl_encrypt(substr($plaintext, 0, -$overflow) . str_repeat("\0", $this->block_size), $this->cipher_name_openssl, $this->key, $this->openssl_options, $iv);
                        $iv = $this->_string_pop($ciphertext, $this->block_size);
                        $size = $len - $overflow;
                        $block = $iv ^ substr($plaintext, -$overflow);
                        $iv = substr_replace($iv, $block, 0, $overflow);
                        $ciphertext.= $block;
                        $pos = $overflow;
                    } elseif ($len) {
                        $ciphertext = openssl_encrypt($plaintext, $this->cipher_name_openssl, $this->key, $this->openssl_options, $iv);
                        $iv = substr($ciphertext, -$this->block_size);
                    }
                    return $ciphertext;
                case CRYPT_MODE_OFB:
                    return $this->_openssl_ofb_process($plaintext, $this->encryptIV, $this->enbuffer);
            }
        }
        if ($this->engine === CRYPT_ENGINE_MCRYPT) {
            set_error_handler(array($this, 'do_nothing'));
            if ($this->changed) {
                $this->_setupMcrypt();
                $this->changed = false;
            }
            if ($this->enchanged) {
                mcrypt_generic_init($this->enmcrypt, $this->key, $this->encryptIV);
                $this->enchanged = false;
            }
            // re: {@link http://phpseclib.sourceforge.net/cfb-demo.phps}
            // using mcrypt's default handing of CFB the above would output two different things.  using phpseclib's
            // rewritten CFB implementation the above outputs the same thing twice.
            if ($this->mode == CRYPT_MODE_CFB && $this->continuousBuffer) {
                $block_size = $this->block_size;
                $iv = &$this->encryptIV;
                $pos = &$this->enbuffer['pos'];
                $len = strlen($plaintext);
                $ciphertext = '';
                $i = 0;
                if ($pos) {
                    $orig_pos = $pos;
                    $max = $block_size - $pos;
                    if ($len >= $max) {
                        $i = $max;
                        $len-= $max;
                        $pos = 0;
                    } else {
                        $i = $len;
                        $pos+= $len;
                        $len = 0;
                    }
                    $ciphertext = substr($iv, $orig_pos) ^ $plaintext;
                    $iv = substr_replace($iv, $ciphertext, $orig_pos, $i);
                    $this->enbuffer['enmcrypt_init'] = true;
                }
                if ($len >= $block_size) {
                    if ($this->enbuffer['enmcrypt_init'] === false || $len > $this->cfb_init_len) {
                        if ($this->enbuffer['enmcrypt_init'] === true) {
                            mcrypt_generic_init($this->enmcrypt, $this->key, $iv);
                            $this->enbuffer['enmcrypt_init'] = false;
                        }
                        $ciphertext.= mcrypt_generic($this->enmcrypt, substr($plaintext, $i, $len - $len % $block_size));
                        $iv = substr($ciphertext, -$block_size);
                        $len%= $block_size;
                    } else {
                        while ($len >= $block_size) {
                            $iv = mcrypt_generic($this->ecb, $iv) ^ substr($plaintext, $i, $block_size);
                            $ciphertext.= $iv;
                            $len-= $block_size;
                            $i+= $block_size;
                        }
                    }
                }
                if ($len) {
                    $iv = mcrypt_generic($this->ecb, $iv);
                    $block = $iv ^ substr($plaintext, -$len);
                    $iv = substr_replace($iv, $block, 0, $len);
                    $ciphertext.= $block;
                    $pos = $len;
                }
                restore_error_handler();
                return $ciphertext;
            }
            $ciphertext = mcrypt_generic($this->enmcrypt, $plaintext);
            if (!$this->continuousBuffer) {
                mcrypt_generic_init($this->enmcrypt, $this->key, $this->encryptIV);
            }
            restore_error_handler();
            return $ciphertext;
        }
        if ($this->changed) {
            $this->_setup();
            $this->changed = false;
        }
        if ($this->use_inline_crypt) {
            $inline = $this->inline_crypt;
            return $inline('encrypt', $this, $plaintext);
        }
        $buffer = &$this->enbuffer;
        $block_size = $this->block_size;
        $ciphertext = '';
        switch ($this->mode) {
            case CRYPT_MODE_ECB:
                for ($i = 0; $i < strlen($plaintext); $i+=$block_size) {
                    $ciphertext.= $this->_encryptBlock(substr($plaintext, $i, $block_size));
                }
                break;
            case CRYPT_MODE_CBC:
                $xor = $this->encryptIV;
                for ($i = 0; $i < strlen($plaintext); $i+=$block_size) {
                    $block = substr($plaintext, $i, $block_size);
                    $block = $this->_encryptBlock($block ^ $xor);
                    $xor = $block;
                    $ciphertext.= $block;
                }
                if ($this->continuousBuffer) {
                    $this->encryptIV = $xor;
                }
                break;
            case CRYPT_MODE_CTR:
                $xor = $this->encryptIV;
                if (strlen($buffer['ciphertext'])) {
                    for ($i = 0; $i < strlen($plaintext); $i+=$block_size) {
                        $block = substr($plaintext, $i, $block_size);
                        if (strlen($block) > strlen($buffer['ciphertext'])) {
                            $buffer['ciphertext'].= $this->_encryptBlock($xor);
                        }
                        $this->_increment_str($xor);
                        $key = $this->_string_shift($buffer['ciphertext'], $block_size);
                        $ciphertext.= $block ^ $key;
                    }
                } else {
                    for ($i = 0; $i < strlen($plaintext); $i+=$block_size) {
                        $block = substr($plaintext, $i, $block_size);
                        $key = $this->_encryptBlock($xor);
                        $this->_increment_str($xor);
                        $ciphertext.= $block ^ $key;
                    }
                }
                if ($this->continuousBuffer) {
                    $this->encryptIV = $xor;
                    if ($start = strlen($plaintext) % $block_size) {
                        $buffer['ciphertext'] = substr($key, $start) . $buffer['ciphertext'];
                    }
                }
                break;
            case CRYPT_MODE_CFB:
                // cfb loosely routines inspired by openssl's:
                // {@link http://cvs.openssl.org/fileview?f=openssl/crypto/modes/cfb128.c&v=1.3.2.2.2.1}
                if ($this->continuousBuffer) {
                    $iv = &$this->encryptIV;
                    $pos = &$buffer['pos'];
                } else {
                    $iv = $this->encryptIV;
                    $pos = 0;
                }
                $len = strlen($plaintext);
                $i = 0;
                if ($pos) {
                    $orig_pos = $pos;
                    $max = $block_size - $pos;
                    if ($len >= $max) {
                        $i = $max;
                        $len-= $max;
                        $pos = 0;
                    } else {
                        $i = $len;
                        $pos+= $len;
                        $len = 0;
                    }
                    // ie. $i = min($max, $len), $len-= $i, $pos+= $i, $pos%= $blocksize
                    $ciphertext = substr($iv, $orig_pos) ^ $plaintext;
                    $iv = substr_replace($iv, $ciphertext, $orig_pos, $i);
                }
                while ($len >= $block_size) {
                    $iv = $this->_encryptBlock($iv) ^ substr($plaintext, $i, $block_size);
                    $ciphertext.= $iv;
                    $len-= $block_size;
                    $i+= $block_size;
                }
                if ($len) {
                    $iv = $this->_encryptBlock($iv);
                    $block = $iv ^ substr($plaintext, $i);
                    $iv = substr_replace($iv, $block, 0, $len);
                    $ciphertext.= $block;
                    $pos = $len;
                }
                break;
            case CRYPT_MODE_OFB:
                $xor = $this->encryptIV;
                if (strlen($buffer['xor'])) {
                    for ($i = 0; $i < strlen($plaintext); $i+=$block_size) {
                        $block = substr($plaintext, $i, $block_size);
                        if (strlen($block) > strlen($buffer['xor'])) {
                            $xor = $this->_encryptBlock($xor);
                            $buffer['xor'].= $xor;
                        }
                        $key = $this->_string_shift($buffer['xor'], $block_size);
                        $ciphertext.= $block ^ $key;
                    }
                } else {
                    for ($i = 0; $i < strlen($plaintext); $i+=$block_size) {
                        $xor = $this->_encryptBlock($xor);
                        $ciphertext.= substr($plaintext, $i, $block_size) ^ $xor;
                    }
                    $key = $xor;
                }
                if ($this->continuousBuffer) {
                    $this->encryptIV = $xor;
                    if ($start = strlen($plaintext) % $block_size) {
                        $buffer['xor'] = substr($key, $start) . $buffer['xor'];
                    }
                }
                break;
            case CRYPT_MODE_STREAM:
                $ciphertext = $this->_encryptBlock($plaintext);
                break;
        }
        return $ciphertext;
    }
References _clearBuffers(), _encryptBlock(), _increment_str(), _openssl_ctr_process(), _openssl_ofb_process(), _pad(), _setup(), _setupMcrypt(), _string_pop(), _string_shift(), CRYPT_ENGINE_MCRYPT, CRYPT_ENGINE_OPENSSL, CRYPT_MODE_CBC, CRYPT_MODE_CFB, CRYPT_MODE_CTR, CRYPT_MODE_ECB, CRYPT_MODE_OFB, and CRYPT_MODE_STREAM.
getBlockLength()
getBlockLength ()
Returns the current block length in bits.
@access public
Returns
int
Definition at line 598 of file Base.php.
    {
        return $this->block_size << 3;
    }
getEngine()
getEngine ()
Returns the engine currently being utilized.
See also
self::_setEngine() @access public
Definition at line 1709 of file Base.php.
    {
        return $this->engine;
    }
getKeyLength()
getKeyLength ()
Returns the current key length in bits.
@access public
Returns
int
Reimplemented in Crypt_RC2.
Definition at line 587 of file Base.php.
    {
        return $this->key_length << 3;
    }
isValidEngine()
isValidEngine ($engine)
Test for engine validity.
See also
self::Crypt_Base()
Parameters
int $engine @access public
Returns
bool
Reimplemented in Crypt_Blowfish, Crypt_DES, Crypt_RC2, Crypt_RC4, Crypt_Rijndael, and Crypt_TripleDES.
Definition at line 1619 of file Base.php.
    {
        switch ($engine) {
            case CRYPT_ENGINE_OPENSSL:
                if ($this->mode == CRYPT_MODE_STREAM && $this->continuousBuffer) {
                    return false;
                }
                $this->openssl_emulate_ctr = false;
                $result = $this->cipher_name_openssl &&
                          extension_loaded('openssl') &&
                          // PHP 5.3.0 - 5.3.2 did not let you set IV's
                          version_compare(PHP_VERSION, '5.3.3', '>=');
                if (!$result) {
                    return false;
                }
                // prior to PHP 5.4.0 OPENSSL_RAW_DATA and OPENSSL_ZERO_PADDING were not defined. instead of expecting an integer
                // $options openssl_encrypt expected a boolean $raw_data.
                if (!defined('OPENSSL_RAW_DATA')) {
                    $this->openssl_options = true;
                } else {
                    $this->openssl_options = OPENSSL_RAW_DATA | OPENSSL_ZERO_PADDING;
                }
                $methods = openssl_get_cipher_methods();
                if (in_array($this->cipher_name_openssl, $methods)) {
                    return true;
                }
                // not all of openssl's symmetric cipher's support ctr. for those
                // that don't we'll emulate it
                switch ($this->mode) {
                    case CRYPT_MODE_CTR:
                        if (in_array($this->cipher_name_openssl_ecb, $methods)) {
                            $this->openssl_emulate_ctr = true;
                            return true;
                        }
                }
                return false;
            case CRYPT_ENGINE_MCRYPT:
                set_error_handler(array($this, 'do_nothing'));
                $result = $this->cipher_name_mcrypt &&
                       extension_loaded('mcrypt') &&
                       in_array($this->cipher_name_mcrypt, mcrypt_list_algorithms());
                restore_error_handler();
                return $result;
            case CRYPT_ENGINE_INTERNAL:
                return true;
        }
        return false;
    }
References CRYPT_ENGINE_INTERNAL, CRYPT_ENGINE_MCRYPT, CRYPT_ENGINE_OPENSSL, CRYPT_MODE_CTR, CRYPT_MODE_STREAM, and PHP_VERSION.
Referenced by _setEngine().
safe_intval()
safe_intval ($x)
Convert float to int.
On 32-bit Linux installs running PHP < 5.3 converting floats to ints doesn't always work
@access private
Parameters
string $x
Returns
int
Definition at line 2643 of file Base.php.
    {
        switch (true) {
            case is_int($x):
            // PHP 5.3, per http://php.net/releases/5_3_0.php, introduced "more consistent float rounding"
            case version_compare(PHP_VERSION, '5.3.0') >= 0 && (php_uname('m') & "\xDF\xDF\xDF") != 'ARM':
            // PHP_OS & "\xDF\xDF\xDF" == strtoupper(substr(PHP_OS, 0, 3)), but a lot faster
            case (PHP_OS & "\xDF\xDF\xDF") === 'WIN':
                return $x;
        }
        return (fmod($x, 0x80000000) & 0x7FFFFFFF) |
            ((fmod(floor($x / 0x80000000), 2) & 1) << 31);
    }
References PHP_VERSION.
Referenced by Crypt_Blowfish\_decryptBlock(), Crypt_Twofish\_decryptBlock(), Crypt_Blowfish\_encryptBlock(), Crypt_Twofish\_encryptBlock(), and Crypt_Twofish\_setupKey().
safe_intval_inline()
safe_intval_inline ()
eval()'able string for in-line float to int
@access private
Returns
string
Definition at line 2663 of file Base.php.
    {
        // on 32-bit linux systems with PHP < 5.3 float to integer conversion is bad
        switch (true) {
            case defined('PHP_INT_SIZE') && PHP_INT_SIZE == 8:
            case version_compare(PHP_VERSION, '5.3.0') >= 0 && (php_uname('m') & "\xDF\xDF\xDF") != 'ARM':
            case (PHP_OS & "\xDF\xDF\xDF") === 'WIN':
                return '%s';
                break;
            default:
                $safeint = '(is_int($temp = %s) ? $temp : (fmod($temp, 0x80000000) & 0x7FFFFFFF) | ';
                return $safeint . '((fmod(floor($temp / 0x80000000), 2) & 1) << 31))';
        }
    }
References PHP_VERSION.
Referenced by Crypt_Blowfish\_setupInlineCrypt(), and Crypt_Twofish\_setupInlineCrypt().
setIV()
setIV ($iv)
Sets the initialization vector.
(optional)
SetIV is not required when CRYPT_MODE_ECB (or ie for AES: CRYPT_AES_MODE_ECB) is being used. If not explicitly set, it'll be assumed to be all zero's.
@access public
Parameters
string $iv
Reimplemented in Crypt_RC4, and Crypt_TripleDES.
Definition at line 556 of file Base.php.
    {
        if ($this->mode == CRYPT_MODE_ECB) {
            return;
        }
        $this->iv = $iv;
        $this->changed = true;
    }
References CRYPT_MODE_ECB.
Referenced by setPassword().
setKey()
setKey ($key)
Sets the key.
The min/max length(s) of the key depends on the cipher which is used. If the key not fits the length(s) of the cipher it will paded with null bytes up to the closest valid key length. If the key is more than max length, we trim the excess bits.
If the key is not explicitly set, it'll be assumed to be all null bytes.
@access public
Parameters
string $key
Reimplemented in Crypt_AES, Crypt_DES, Crypt_Rijndael, and Crypt_TripleDES.
Definition at line 617 of file Base.php.
    {
        if (!$this->explicit_key_length) {
            $this->setKeyLength(strlen($key) << 3);
            $this->explicit_key_length = false;
        }
        $this->key = $key;
        $this->changed = true;
        $this->_setEngine();
    }
References _setEngine(), and setKeyLength().
Referenced by setPassword().
setKeyLength()
setKeyLength ($length)
Sets the key length.
Keys with explicitly set lengths need to be treated accordingly
@access public
Parameters
int $length
Reimplemented in Crypt_AES, Crypt_Blowfish, Crypt_RC2, Crypt_RC4, Crypt_Rijndael, Crypt_TripleDES, and Crypt_Twofish.
Definition at line 574 of file Base.php.
    {
        $this->explicit_key_length = true;
        $this->changed = true;
        $this->_setEngine();
    }
References _setEngine().
Referenced by setKey().
setPassword()
setPassword ($password, $method = 'pbkdf2')
Sets the password.
Depending on what $method is set to, setPassword()'s (optional) parameters are as follows: pbkdf2 or pbkdf1: $hash, $salt, $count, $dkLen
Where $hash (default = sha1) currently supports the following hashes: see: Crypt/Hash.php
See also
Crypt/Hash.php
Parameters
string $password
string $method
Returns
bool @access public
Definition at line 645 of file Base.php.
    {
        global $VIEW_PATH;
        $key = '';
        switch ($method) {
            default: // 'pbkdf2' or 'pbkdf1'
                $func_args = func_get_args();
                // Hash function
                $hash = isset($func_args[2]) ? $func_args[2] : 'sha1';
                // WPA and WPA2 use the SSID as the salt
                $salt = isset($func_args[3]) ? $func_args[3] : $this->password_default_salt;
                // RFC2898#section-4.2 uses 1,000 iterations by default
                // WPA and WPA2 use 4,096.
                $count = isset($func_args[4]) ? $func_args[4] : 1000;
                // Keylength
                if (isset($func_args[5]) && $func_args[5] > 0) {
                    $dkLen = $func_args[5];
                } else {
                    $dkLen = $method == 'pbkdf1' ? 2 * $this->key_length : $this->key_length;
                }
                switch (true) {
                    case $method == 'pbkdf1':
                        if (!class_exists('Crypt_Hash')) {
                            include_once $VIEW_PATH.'/lib/phpseclib/Crypt/Hash.php';
                        }
                        $hashObj = new Crypt_Hash();
                        $hashObj->setHash($hash);
                        if ($dkLen > $hashObj->getLength()) {
                            user_error('Derived key too long');
                            return false;
                        }
                        $t = $password . $salt;
                        for ($i = 0; $i < $count; ++$i) {
                            $t = $hashObj->hash($t);
                        }
                        $key = substr($t, 0, $dkLen);
                        $this->setKey(substr($key, 0, $dkLen >> 1));
                        $this->setIV(substr($key, $dkLen >> 1));
                        return true;
                    // Determining if php[>=5.5.0]'s hash_pbkdf2() function avail- and useable
                    case !function_exists('hash_pbkdf2'):
                    case !function_exists('hash_algos'):
                    case !in_array($hash, hash_algos()):
                        if (!class_exists('Crypt_Hash')) {
                            include_once $VIEW_PATH.'/lib/phpseclib/Crypt/Hash.php';
                        }
                        $i = 1;
                        $hmac = new Crypt_Hash();
                        $hmac->setHash($hash);
                        $hmac->setKey($password);
                        while (strlen($key) < $dkLen) {
                            $f = $u = $hmac->hash($salt . pack('N', $i++));
                            for ($j = 2; $j <= $count; ++$j) {
                                $u = $hmac->hash($u);
                                $f^= $u;
                            }
                            $key.= $f;
                        }
                        $key = substr($key, 0, $dkLen);
                        break;
                    default:
                        $key = hash_pbkdf2($hash, $password, $salt, $count, $dkLen, true);
                }
        }
        $this->setKey($key);
        return true;
    }
References $VIEW_PATH, setIV(), and setKey().
setPreferredEngine()
setPreferredEngine ($engine)
Sets the preferred crypt engine.
Currently, $engine could be:
CRYPT_ENGINE_OPENSSL [very fast]
CRYPT_ENGINE_MCRYPT [fast]
CRYPT_ENGINE_INTERNAL [slow]
If the preferred crypt engine is not available the fastest available one will be used
See also
self::Crypt_Base()
Parameters
int $engine @access public
Reimplemented in Crypt_TripleDES.
Definition at line 1688 of file Base.php.
    {
        switch ($engine) {
            //case CRYPT_ENGINE_OPENSSL:
            case CRYPT_ENGINE_MCRYPT:
            case CRYPT_ENGINE_INTERNAL:
                $this->preferredEngine = $engine;
                break;
            default:
                $this->preferredEngine = CRYPT_ENGINE_OPENSSL;
        }
        $this->_setEngine();
    }
References _setEngine(), CRYPT_ENGINE_INTERNAL, CRYPT_ENGINE_MCRYPT, and CRYPT_ENGINE_OPENSSL.
Field Documentation
$block_size
$block_size = 16
Definition at line 142 of file Base.php.
$cfb_init_len
$cfb_init_len = 600
Definition at line 294 of file Base.php.
$changed
$changed = true
Definition at line 305 of file Base.php.
$cipher_name_mcrypt
$cipher_name_mcrypt
Definition at line 363 of file Base.php.
$cipher_name_openssl
$cipher_name_openssl
Definition at line 374 of file Base.php.
$cipher_name_openssl_ecb
$cipher_name_openssl_ecb
Definition at line 386 of file Base.php.
$const_namespace
$const_namespace
Definition at line 418 of file Base.php.
$continuousBuffer
$continuousBuffer = false
Definition at line 189 of file Base.php.
$debuffer
$debuffer
Definition at line 209 of file Base.php.
$dechanged
$dechanged = true
Definition at line 253 of file Base.php.
$decryptIV
$decryptIV
Definition at line 180 of file Base.php.
$demcrypt
$demcrypt
Definition at line 233 of file Base.php.
$ecb
$ecb
Definition at line 272 of file Base.php.
$enbuffer
$enbuffer
Definition at line 199 of file Base.php.
$enchanged
$enchanged = true
Definition at line 243 of file Base.php.
$encryptIV
$encryptIV
Definition at line 170 of file Base.php.
$engine
$engine
Definition at line 340 of file Base.php.
Referenced by Crypt_Blowfish\isValidEngine(), Crypt_DES\isValidEngine(), Crypt_RC2\isValidEngine(), Crypt_RC4\isValidEngine(), Crypt_Rijndael\isValidEngine(), Crypt_TripleDES\isValidEngine(), and Crypt_TripleDES\setPreferredEngine().
$enmcrypt
$enmcrypt
Definition at line 221 of file Base.php.
$explicit_key_length
$explicit_key_length = false
Definition at line 471 of file Base.php.
$inline_crypt
$inline_crypt
Definition at line 433 of file Base.php.
$iv
$iv
Definition at line 160 of file Base.php.
Referenced by Crypt_TripleDES\setIV().
$key
$key = "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
Definition at line 151 of file Base.php.
Referenced by Crypt_Blowfish\_setupKey(), Crypt_DES\_setupKey(), Crypt_Twofish\_setupKey(), Crypt_AES\setKey(), Crypt_DES\setKey(), Crypt_Rijndael\setKey(), and Crypt_TripleDES\setKey().
$mode
$mode
Definition at line 134 of file Base.php.
Referenced by Crypt_TripleDES\__construct(), Crypt_RC4\_crypt(), Crypt_DES\_processBlock(), Crypt_TripleDES\Crypt_TripleDES(), and Crypt_TripleDES\isValidEngine().
$openssl_emulate_ctr
$openssl_emulate_ctr = false
Definition at line 453 of file Base.php.
$openssl_options
$openssl_options
Definition at line 462 of file Base.php.
$paddable
$paddable = false
Definition at line 323 of file Base.php.
$padding
$padding = true
Definition at line 314 of file Base.php.
$password_default_salt
$password_default_salt = 'phpseclib/salt'
Definition at line 395 of file Base.php.
$preferredEngine
$preferredEngine
Definition at line 350 of file Base.php.
$skip_key_adjustment
$skip_key_adjustment = false
Definition at line 480 of file Base.php.
$use_inline_crypt
$use_inline_crypt
Definition at line 444 of file Base.php.
The documentation for this class was generated from the following file:
src/View/lib/phpseclib/Crypt/Base.php