PF Firewall: Layout Class Reference
Layout Class Reference
Public Member Functions
__construct ($name='')
_generate_default ()
_generate_host ($machine)
_add_group (&$vars)
_add_item ($groupname, &$value)
_reset ()
_load ($name)
render ($html=true)
getgrouptitles ()
_display ()
_test ()
Data Fields
$groups
$groupvars
Detailed Description
Definition at line 46 of file class_layout.inc.
Constructor & Destructor Documentation
__construct()
__construct ($name = '')
Definition at line 50 of file class_layout.inc.
{
        global $symon;
        $this->_reset();
        if ($name != '') {
            if (!isset($symon["layout_dir"])) {
            config_error("layout_dir", "is not set");
            return 0;
            }
            if (!is_dir($symon["layout_dir"])) {
            config_error("layout_dir", "does not point to a directory");
            return 0;
            }
                if (isset($symon["isolate_hosts"]) &&
                    ($symon["isolate_hosts"] > 0) &&
                    is_dir($symon["host_tree"]."/".normalise_filename($name))) {
                    $this->_generate_host($name);
                } else {
                    $this->_load($name);
                }
        } else {
            $this->_generate_default();
        }
        if (!isset($this->groups)) {
            runtime_error('layout: no valid layout selected');
            return 0;
        }
    }
References $symon, _generate_default(), _generate_host(), _load(), _reset(), config_error(), normalise_filename(), and runtime_error().
Member Function Documentation
_add_group()
_add_group (& $vars)
Definition at line 169 of file class_layout.inc.
{
        if (strtolower(get_class($vars)) != 'vars') {
            print_r($vars);
            runtime_error('layout: internal: add_group(vars) - vars are not variables');
        }
        if (!$vars->defp('name')) {
            $this->_display();
            runtime_error('layout: need a valid group name for a group to add');
        }
        $name = $vars->get('name');
        if (isset($this->groupvars[$name])) {
            $this->_display();
            runtime_error("layout: group $name redefined");
        }
        $this->groupvars[$name] = $vars;
        $this->groups[$name] = array();
    }
References _display(), and runtime_error().
Referenced by _generate_host(), and _load().
_add_item()
_add_item ($groupname, & $value)
Definition at line 189 of file class_layout.inc.
{
        if (!isset($this->groupvars[$groupname])) {
            $this->_display();
            runtime_error("layout: cannot add item $value : group $groupname has not been defined");
        }
        array_push($this->groups[$groupname], $value);
    }
References _display(), and runtime_error().
Referenced by _generate_host(), and _load().
_display()
_display ()
Definition at line 324 of file class_layout.inc.
{
        print "<pre>";
        if (is_array($this->groups)) {
            reset($this->groups);
            foreach($this->groups as $group => $items) {
            print "\xa\xa group ";
            $vars = $this->groupvars[$group]->tostring();
            if (strlen($vars) > 0) {
                print $vars;
            }
            print ";";
            foreach ($items as $key => $value) {
                print $value->_display();
            }
            }
        }
        print "</pre>";
    }
References print.
Referenced by _add_group(), _add_item(), _load(), and _test().
_generate_default()
_generate_default ()
Definition at line 82 of file class_layout.inc.
{
        global $symon;
        if (!is_dir($symon["host_tree"])) {
            config_error("host_tree", "does not point to a directory");
            return 0;
        }
        $root_dir = dir($symon["host_tree"]);
        while ($host = $root_dir->read()) {
                $this->_generate_host($host);
            }
        if (!isset($this->groups)) {
            runtime_error('layout: need $symon["host_tree"]/hostname/cpu0.rrd like files to generate the default layout - none found.');
            return 0;
        }
    }
References $symon, _generate_host(), config_error(), and runtime_error().
Referenced by __construct().
_generate_host()
_generate_host ($machine)
Definition at line 101 of file class_layout.inc.
{
        global $symon;
        if (!is_dir($symon["host_tree"])) {
            config_error("host_tree", "does not point to a directory");
            return 0;
        }
        if (is_file($symon["host_tree"]."/".$machine)) {
            runtime_error('$symon["host_tree"] should contain machine directories, not files. ($symon["host_tree"]/cpu0.rrd => $symon["host_tree"]/localhost/cpu0.rrd)');
        }
        if ($machine != '.' &&
            $machine != '..' &&
            is_dir($symon["host_tree"]."/".$machine)) {
            $groupvars = new Vars();
            $groupvars->set('host', $machine);
            $groupvars->set('dir', $symon["host_tree"].'/'.$machine);
            $groupvars->set('name', $machine);
            $this->_add_group($groupvars);
            /* get all graphs */
            $graph_dir = dir($symon["host_tree"].'/'.$machine);
            $files = array();
            while ($item = $graph_dir->read()) {
                if ($item != '.' &&
                    $item != '..' &&
                    preg_match("/.rrd$/", $item)) {
                    $files[] = $item;
                }
            }
            asort($files);
            /* get combined graphs */
            foreach ($symon['combine'] as $type => $enabled) {
                if ($enabled) {
                    $combine = array();
                    $newfiles = array();
                    foreach ($files as $key => $item) {
                        if (preg_match("/^".$type."[0-9_]/", $item)) {
                            $combine[] = $item;
                        } else {
                            $newfiles[] = $item;
                        }
                    }
                    $files = $newfiles;
                    if (count($combine)) {
                        $v = new Vars();
                        foreach ($combine as $key => $item) {
                            $v->set('rrdfile'.$key, $symon["host_tree"].'/'.$machine.'/'.$item);
                        }
                        $g = new Graph($groupvars);
                        $g->set_graph_vars($v);
                        $this->_add_item($machine, $g);
                    }
                }
            }
            foreach ($files as $key => $item) {
                $v = new Vars();
                $v->set('rrdfile', $symon["host_tree"].'/'.$machine.'/'.$item);
                $g = new Graph($groupvars);
                $g->set_graph_vars($v);
                $this->_add_item($machine, $g);
            }
        }
    }
References $groupvars, $symon, _add_group(), _add_item(), config_error(), and runtime_error().
Referenced by __construct(), and _generate_default().
_load()
_load ($name)
Definition at line 203 of file class_layout.inc.
{
        global $symon;
        if ($name == '' || $name == 'default' || $name == 'empty') {
            runtime_error('layout: need a valid layout name to load');
            return 0;
        }
        $name = normalise_filename($name);
        $file = $symon["layout_dir"].'/'.$name.'.layout';
        $lexer = new Lexer();
        $lexer->load($name);
        $groupvars = 0;
        $token = $lexer->next_token();
        do {
            if ($token === 0) {
            $token_string = '';
            } else {
            $token_string = $token;
            }
            switch ($token_string) {
            case 'group':
            $groupvars = new Vars();
            $groupvars->parse($lexer);
            $lexer->parse_semicolon();
            $this->_add_group($groupvars);
            $groupname = $groupvars->get('name');
            break;
            case 'graph':
            $graph = new Graph($groupvars);
            $graph->parse($lexer);
            $lexer->parse_semicolon();
            $this->_add_item($groupname, $graph);
            break;
            case 'text':
            $text = new Text();
            $text->parse($lexer);
            $lexer->parse_semicolon();
            $this->_add_item($groupname, $text);
            break;
            default:
            $lexer->parse_error('Expected group|graph|text');
            break;
            }
            $token = $lexer->next_token();
        } while (!$lexer->is_eof());
        if (isset($symon['layout_debug'])) {
            $this->_display();
        }
    }
References $groupvars, $symon, _add_group(), _add_item(), _display(), normalise_filename(), and runtime_error().
Referenced by __construct().
_reset()
_reset ()
Definition at line 197 of file class_layout.inc.
                      {
        /* reset current layout */
        unset($this->groups);
        unset($this->groupvars);
    }
Referenced by __construct().
_test()
_test ()
Definition at line 343 of file class_layout.inc.
                     {
        print "\xa layout definition:";
        $this->_display();
        print "\xa\xa render layout:";
        $this->render();
    }
References _display(), print, and render().
getgrouptitles()
getgrouptitles ()
Definition at line 313 of file class_layout.inc.
{
        $a = array();
        if (is_array($this->groups)) {
            reset($this->groups);
            foreach($this->groups as $group => $value) {
            array_push($a, $group);
            }
        }
        return $a;
    }
render()
render ($html = true)
Definition at line 262 of file class_layout.inc.
{
        $LinkNames = array(
            _TITLE('CPU Load'),
            _TITLE('Temperature'),
            _TITLE('Fan'),
            _TITLE('Memory Usage'),
            _TITLE('Disk I/O'),
            _TITLE('Partitions Usages'),
            _TITLE('Loopback Interface'),
            _TITLE('Internal Interface'),
            _TITLE('External Interface'),
            _TITLE('State Statistics'),
            _TITLE('State Searches vs Packets'),
            _TITLE('Data Transfer'),
            _TITLE('Mbuf Statistics'),
            _TITLE('Network Protocol Usage'),
            _TITLE('Number of Processes'),
            _TITLE('Process CPU Load'),
        );
        $graphs= array();
        reset($this->groups);
        if (is_array($this->groups)) {
            foreach($this->groups as $group => $items) {
                if (array_key_exists($group, $LinkNames)) {
                    $LinkName= $LinkNames[$group];
                }
                else {
                    $LinkName= $group;
                }
                if ($html) {
                    print ' <div class="group">
                            <h3 class="header" style="margin: 4px 0 2px 0;"><a name="' . $group . '">' . _($LinkName) . '</a></h3>
                        </div>';
                }
                reset($items);
                foreach($items as $item) {
                    $graphs[$LinkName]= $item->render($html);
                }
                if ($html) {
                    print '<div class="item-footer"></div>';
                }
            }
        }
        return $graphs;
    }
References $graphs, _TITLE(), and print.
Referenced by _test().
Field Documentation
$groups
$groups
Definition at line 47 of file class_layout.inc.
$groupvars
$groupvars
Definition at line 48 of file class_layout.inc.
Referenced by _generate_host(), and _load().
The documentation for this class was generated from the following file:
src/View/symon/class_layout.inc