PF Firewall: State Class Reference
State Class Reference
Public Member Functions
display ($ruleNumber, $count)
Processes inputs submitted on the edit page.
dispState ()
dispText ($key)
dispBool ($key)
dispOverload ()
dispSourceTrack ()
input ()
Processes inputs submitted on the edit page.
inputState ()
edit ($ruleNumber, $modified, $testResult, $generateResult, $action)
Prints edit page.
editState ()
editIfBinding ()
editOverload ()
editSourceTrack ()
Public Member Functions inherited from Timeout
display ($ruleNumber, $count)
Processes inputs submitted on the edit page.
dispTimeout ()
dispTimeoutOpts ()
input ()
Processes inputs submitted on the edit page.
inputTimeout ()
inputTimeoutOpt ($key, $var, $parent)
edit ($ruleNumber, $modified, $testResult, $generateResult, $action)
Prints edit page.
editTimeout ()
editFragment ()
editInterval ()
editSrcTrack ()
editTcpTimeouts ()
editUdpTimeouts ()
editIcmpTimeouts ()
editOtherTimeouts ()
editAdaptiveTimeouts ()
editTimeoutOpt ($timeout, $key)
Public Member Functions inherited from Rule
__construct ()
setType ()
Sets the type of certain Translation rules.
display ($ruleNumber, $count)
Processes inputs submitted on the edit page.
dispHead ($ruleNumber, $count)
Prints rule number, rule type, and line number.
countLines ()
Returns the number of extra lines.
dispTail ($ruleNumber)
Prints inline comments and edit links.
dispHeadEditLinks ($ruleNumber, $count)
Prints edit links in a cell.
dispEditLinks ($ruleNumber, $count, $up='up', $down='down', $del='del')
Prints e, u, d, and x links.
dispKey ($key, $title)
Displays the given key in a cell if its value is TRUE.
dispValue ($key, $title)
Displays the value(s) of the given key in a cell.
dispValues ($key, $title)
Displays the value(s) of the given host key in a cell.
dispInterface ()
printValue ($value, $pre='', $post='', $count=10)
Prints the given value(s).
dispLog ($colspan=1)
Displays log specification in a cell.
printHostPort ($value, $noAny=TRUE, $count=10)
Prints host or port values.
input ()
Processes inputs submitted on the edit page.
inputKey ($key, $parent=NULL)
Gets the value of the given POST input key.
inputBool ($key, $parent=NULL)
Gets the boolean value of the given POST input key.
inputKeyIfHasVar ($key, $var)
Gets the value of the given POST input key, if another given key exists already.
inputDel ($key, $var, $parent=NULL)
Gets the value of the given GET input var and deletes it from the given key.
inputDelValue ($key, $value, $parent=NULL)
Deletes the given value from the given key.
inputAdd ($key, $var, $parent=NULL)
Gets the value of the given POST input var and adds it to the given key.
inputAddValue ($key, $value, $parent=NULL)
Adds the given value to the given key.
inputInterface ()
Deletes or adds interface definitions.
inputLog ()
Gets the POST input vars of log specifications.
inputDelEmpty ($flatten=TRUE)
Deletes empty values in internal rule structure.
inputDelEmptyRecursive ($array, $flatten)
Recursively deletes empty values in NVP arrays.
edit ($ruleNumber, $modified, $testResult, $generateResult, $action)
Prints edit page.
editCheckbox ($key, $title)
Prints a checkbox for the given key, within a table row.
editText ($key, $title, $help=NULL, $size=0, $hint='')
Prints an edit box for the given key, within a table row.
editValues ($key, $title, $delName, $addName, $hint, $help=NULL, $size=0, $disabled=FALSE)
Prints delete links and input boxes for multi-valued keys, within a table row.
editHead ($modified, $testResult, $generateResult, $action)
Prints rule title, generated rule, and form header at the top of the edit page.
editTail ()
Closes the table and form on the edit page.
editInterface ()
editAf ()
editLog ()
Prints edit controls for log specifications.
editComment ()
Prints input box for inline comments.
editDeleteValueLinks ($value, $name, $prefix='', $postfix='')
Prints delete links for values.
editAddValueBox ($id, $label, $hint, $size=0, $disabled=FALSE)
Prints add input box for values.
editHelp ($label)
Prints help image with a link to an anchor in pf.conf man page.
Additional Inherited Members
Data Fields inherited from Rule
$cat = ''
Category or type of rule.
$rule = array()
Internal structure of rule properties in NVP format.
Protected Attributes inherited from Rule
$ref = ''
Name used in href.
$href = ''
Common part of edit links.
$ruleNumber = 0
Rule number.
$arr = array()
Used by certain rule types while displaying themselves on the list.
$editIndex = 0
Current count of rows on edit pages.
Detailed Description
Definition at line 23 of file State.php.
Member Function Documentation
dispBool()
dispBool ($key)
Definition at line 70 of file State.php.
    {
        if (isset($this->rule[$key])) {
            $this->arr[]= $key;
        }
    }
display()
display ($ruleNumber, $count)
Processes inputs submitted on the edit page.
All child classes should override this method.
Parameters
int $ruleNumber Rule number.
int $count Number of rules in the ruleset.
Reimplemented from Timeout.
Reimplemented in AfTo, Anchor, DivertPacket, DivertTo, FilterBase, NatBase, Route, and Scrub.
Definition at line 25 of file State.php.
    {
        $this->dispHead($ruleNumber, $count);
        $this->dispState();
        $this->dispTail($ruleNumber);
    }
dispOverload()
dispOverload ()
Definition at line 77 of file State.php.
    {
        if (isset($this->rule['overload'])) {
            $str= 'overload: <' . $this->rule['overload'] . '>';
            if (isset($this->rule['flush'])) {
                $str.= ' flush';
                if (isset($this->rule['global'])) {
                    $str.= ' global';
                }
            }
            $this->arr[]= htmlentities($str);
        }
    }
dispSourceTrack()
dispSourceTrack ()
Definition at line 91 of file State.php.
    {
        if (isset($this->rule['source-track'])) {
            $str= 'source-track';
            if (isset($this->rule['source-track-option'])) {
                $str.= ' ' . $this->rule['source-track-option'];
            }
            $this->arr[]= $str;
        }
    }
dispState()
dispState ()
Definition at line 32 of file State.php.
    {
        ?>
        <td title="<?php echo _TITLE('State Defaults') ?>" colspan="12">
            <?php
            $this->arr= array();
            $this->dispText('max');
            $this->dispText('max-src-states');
            $this->dispText('max-src-nodes');
            $this->dispText('max-src-conn');
            $this->dispText('max-src-conn-rate');
            $this->dispBool('sloppy');
            $this->dispBool('no-sync');
            $this->dispBool('pflow');
            $this->dispBool('if-bound');
            $this->dispBool('floating');
            $this->dispOverload();
            $this->dispSourceTrack();
            $this->dispTimeoutOpts();
            echo implode(', ', $this->arr);
            ?>
        </td>
        <?php
    }
dispText()
dispText ($key)
Definition at line 63 of file State.php.
    {
        if (isset($this->rule[$key])) {
            $this->arr[]= "$key: " . $this->rule[$key];
        }
    }
edit()
edit ($ruleNumber, $modified, $testResult, $generateResult, $action)
Prints edit page.
All child classes should override this method.
Parameters
int $ruleNumber Rule number.
bool $modified Whether the rule is modified or not.
bool $testResult Test result.
bool $generateResult Rule generation result.
string $action Current state of the edit page.
Reimplemented from Timeout.
Reimplemented in AfTo, Anchor, DivertPacket, DivertTo, Filter, FilterBase, NatBase, NatTo, Route, and Scrub.
Definition at line 137 of file State.php.
    {
        $this->editIndex= 0;
        $this->ruleNumber= $ruleNumber;
        $this->editHead($modified, $testResult, $generateResult, $action);
        $this->editState();
        $this->editComment();
        $this->editTail();
    }
References $testResult.
editIfBinding()
editIfBinding ()
Definition at line 166 of file State.php.
    {
        ?>
        <tr class="<?php echo ($this->editIndex++ % 2 ? 'evenline' : 'oddline'); ?>">
            <td class="title">
                <?php echo _TITLE('Interface Binding').':' ?>
            </td>
            <td>
                <input type="checkbox" id="if-bound" name="if-bound" value="if-bound" <?php echo (isset($this->rule['if-bound']) && $this->rule['if-bound'] ? 'checked' : ''); ?> <?php echo (isset($this->rule['floating']) ? 'disabled' : ''); ?> />
                <label for="if-bound">if-bound</label>
                <input type="checkbox" id="floating" name="floating" value="floating" <?php echo (isset($this->rule['floating']) && $this->rule['floating'] ? 'checked' : ''); ?> <?php echo (isset($this->rule['if-bound']) ? 'disabled' : ''); ?> />
                <label for="floating">floating</label>
                <?php $this->editHelp('if-binding') ?>
            </td>
        </tr>
        <?php
    }
References _TITLE().
editOverload()
editOverload ()
Definition at line 184 of file State.php.
    {
        ?>
        <tr class="<?php echo ($this->editIndex++ % 2 ? 'evenline' : 'oddline'); ?>">
            <td class="title">
                <?php echo _TITLE('Overload').':' ?>
            </td>
            <td>
                <input type="text" size="20" id="overload" name="overload" value="<?php echo isset($this->rule['overload']) ? $this->rule['overload'] : ''; ?>"  placeholder="<?php echo _CONTROL('string') ?>"/>
                <input type="checkbox" id="flush" name="flush" value="flush" <?php echo (isset($this->rule['flush']) && $this->rule['flush'] ? 'checked' : ''); ?> <?php echo (!isset($this->rule['overload']) ? 'disabled' : ''); ?> />
                <label for="flush">flush</label>
                <input type="checkbox" id="global" name="global" value="global" <?php echo (isset($this->rule['global']) && $this->rule['global'] ? 'checked' : ''); ?> <?php echo (!isset($this->rule['flush']) ? 'disabled' : ''); ?> />
                <label for="global">global</label>
                <?php $this->editHelp('overload') ?>
            </td>
        </tr>
        <?php
    }
References _TITLE().
editSourceTrack()
editSourceTrack ()
Definition at line 203 of file State.php.
    {
        ?>
        <tr class="<?php echo ($this->editIndex++ % 2 ? 'evenline' : 'oddline'); ?>">
            <td class="title">
                <?php echo _TITLE('Enable Source Track').':' ?>
            </td>
            <td>
                <input type="checkbox" id="source-track" name="source-track" value="source-track" <?php echo (isset($this->rule['source-track']) && $this->rule['source-track'] ? 'checked' : ''); ?> />
                <select id="source-track-option" name="source-track-option" <?php echo (!isset($this->rule['source-track']) ? 'disabled' : ''); ?>>
                    <option value=""></option>
                    <option value="rule" <?php echo (isset($this->rule['source-track-option']) && $this->rule['source-track-option'] == 'rule' ? 'selected' : ''); ?>>rule</option>
                    <option value="global" <?php echo (isset($this->rule['source-track-option']) && $this->rule['source-track-option'] == 'global' ? 'selected' : ''); ?>>global</option>
                </select>
                <?php $this->editHelp('source-track') ?>
            </td>
        </tr>
        <?php
    }
References _TITLE().
editState()
editState ()
Definition at line 150 of file State.php.
    {
        $this->editText('max', _TITLE('Max States'), 'max', 10, _CONTROL('number'));
        $this->editText('max-src-states', _TITLE('Max Single Host States'), 'max-src-states', 10, _CONTROL('number'));
        $this->editText('max-src-nodes', _TITLE('Max Addresses'), 'max-src-nodes', 10, _CONTROL('number'));
        $this->editText('max-src-conn', _TITLE('Max Connection'), 'max-src-conn', 10, _CONTROL('number'));
        $this->editText('max-src-conn-rate', _TITLE('Max Connection Rate'), 'max-src-conn-rate', 20, _CONTROL('number/number'));
        $this->editCheckbox('sloppy', _TITLE('Sloppy Tracker'));
        $this->editCheckbox('no-sync', _TITLE('No pfsync'));
        $this->editCheckbox('pflow', _TITLE('Export To pflow'));
        $this->editIfBinding();
        $this->editOverload();
        $this->editSourceTrack();
        $this->editTimeout();
    }
References _CONTROL(), and _TITLE().
input()
input ()
Processes inputs submitted on the edit page.
All child classes should override this method.
Reimplemented from Timeout.
Reimplemented in AfTo, Anchor, DivertPacket, DivertTo, Filter, FilterBase, NatBase, NatTo, Route, and Scrub.
Definition at line 102 of file State.php.
    {
        $this->inputState();
        $this->inputKey('comment');
        $this->inputDelEmpty();
    }
inputState()
inputState ()
Definition at line 110 of file State.php.
    {
        $this->inputKey('max');
        $this->inputKey('max-src-states');
        $this->inputKey('max-src-nodes');
        $this->inputKey('max-src-conn');
        $this->inputKey('max-src-conn-rate');
        $this->inputBool('sloppy');
        $this->inputBool('no-sync');
        $this->inputBool('pflow');
        $this->inputBool('if-bound');
        if (!isset($this->rule['if-bound'])) {
            $this->inputBool('floating');
        }
        $this->inputKey('overload');
        $this->inputBool('flush');
        $this->inputBool('global');
        $this->inputBool('source-track');
        $this->inputKey('source-track-option');
        $this->inputTimeout();
    }
The documentation for this class was generated from the following file:
src/View/pf/lib/State.php