PF Firewall: Symon Class Reference
Symon Class Reference
Public Member Functions
__construct ()
SetIfs ($lanif, $wanif)
Sets interface names in the layout files.
SetConf ($lanif, $wanif)
Sets interface names in the symon and symux config files.
RenderLayout ($layout, $width=700, $heigth=250)
Generates graphs for the given layout.
GetGraph ($file)
SetCpus ()
SetSensors ()
SetPartitions ()
Public Member Functions inherited from Monitoring
_getLiveLogs ($file, $count, $re='', $needle='', $reportFileExistResult=TRUE)
Gets logs for live logs pages, the actual method.
__construct ()
Public Member Functions inherited from Model
__construct ()
IsRunning ($proc='')
Checks if the given process(es) is running.
GetProcList ()
Gets the list of processes running.
SelectProcesses ($psout)
Selects user processes from ps output.
Start ()
Start module process(es).
Stop ()
Stops module process(es)
Pkill ($proc, $args='')
Kills the given process(es).
GetIntIf ()
Get int_if.
_getIntIf ()
GetExtIf ()
Get ext_if.
_getExtIf ()
isWifiIf ($if)
CreateUser ($user, $passwd, $uid)
Creates a system user.
SetPassword ($user, $passwd)
Sets user's password in the system password file.
SetLogLevel ($level)
Sets global log level.
SetHelpBox ($bool)
Enables or disables help boxes.
SetSessionTimeout ($timeout)
Sets session timeout.
SetDefaultLocale ($locale)
Sets default locale.
SetForceHTTPs ($bool)
Enables or disables HTTPs.
SetUseSSH ($bool)
Enables or disables SSH.
SetMaxAnchorNesting ($max)
Sets the max number of nested anchors allowed.
SetPfctlTimeout ($timeout)
Sets pfctl timeout.
SetStatusCheckInterval ($interval)
Sets status check interval.
SetMaxFileSizeToProcess ($size)
Sets max file size to process.
GetReloadRate ()
Gets default reload rate.
_getReloadRate ()
SetReloadRate ($rate)
Sets default reload rate.
RunShellCommand ($cmd)
Runs the given shell command and returns its output as string.
GetFiles ($filepath)
Returns files with the given filepath pattern.
GetFile ($file)
Reads file contents.
DeleteFile ($path)
Deletes the given file or directory.
PutFile ($file, $contents)
Writes contents to file.
SetNVP ($file, $name, $newvalue)
Changes value of NVP.
GetNVP ($file, $name, $set=0, $trimchars='')
Reads value of NVP.
SearchFile ($file, $re, $set=0, $trimchars='')
Searches the given file with the given regex.
SearchFileAll ($file, $re, $set=1)
Multi-searches a given file with a given regexp.
ReplaceRegexp ($file, $matchre, $replacere)
Searches a needle and replaces with a value in the given file.
AppendToFile ($file, $line)
Appends a string to a file.
GetDateTime ()
Gets system datetime.
GetPhyIfs ()
Extracts physical interface names from ifconfig output.
_getPhyIfs ()
GetDefaultLogFile ()
Gets the log file of the module.
SelectLogFile ($file)
Gets the log file under the tmp folder.
IsLogFileModified ($logfile)
Checks if the given log file has been updated.
GetTmpLogFileName ($file)
Gets the name of the file in the tmp folder.
UpdateTmpLogFile ($file)
Copies the original log file to tmp folder.
formatDateHourRegexp ($month, $day, $hour, $minute)
Generates the module specific datetime regexp for filtering logs.
formatDateHourRegexpDayLeadingZero ($month, $day, $hour, $minute)
formatDateHourRegexpWeekDays ($month, $day, $hour, $minute)
GetFileLineCount ($file, $re='', $needle='', $month='', $day='', $hour='', $minute='')
Gets line count of the given log file.
_getFileLineCount ($file, $re='', $needle='', $month='', $day='', $hour='', $minute='')
GetLogs ($file, $end, $count, $re='', $needle='', $month='', $day='', $hour='', $minute='')
Gets lines in log file.
GetLiveLogs ($file, $count, $re='')
Gets logs for live logs pages.
_getLiveLogs ($file, $count, $re='', $needle='', $reportFileExistResult=TRUE)
Gets logs for live logs pages, the actual method.
GetLastLogs ($file, $count)
GetLogFilesList ()
Gets log files list with start dates.
GetLogStartDate ($file)
Extracts the datetime of the first line in the log file.
_getLogStartDate ($file)
GetFileFirstLine ($file)
Gets first line of file.
ParseLogLine ($logline, &$cols)
Parses the given log line.
PostProcessCols (&$cols)
Further processes parser output fields.
PrepareFileForDownload ($file)
Prepares file for download over WUI.
GetOrigFileName ($logfile)
Gets the original file name for the given log file.
GetProcStatLines ($logfile)
Collects text statistics for the proc stats general page.
CopyLogFileToTmp ($file, $tmpdir)
Uncompresses gzipped log file to tmp dir.
GetStatsLogLines ($logfile, $tail=-1)
Builds generic grep command and extracts log lines.
GetAllStats ($logfile, $collecthours='')
Gets both brief and full statistics.
GetStats ($logfile, $date, $collecthours='')
Main statistics collector, as module data set.
_getStats ($logfile, $date, $collecthours='')
ValidateFile ($file, $reportFileExistResult=TRUE)
Checks if the given file exists and not larger than $MaxFileSizeToProcess in MBs.
ValidateFileExists ($file, $reportFileExistResult=TRUE)
CountDiffLogLines ($logfile, &$count)
Gets the number of lines added to log files since last tmp file update.
UpdateStats ($logfile, &$stats, &$briefstats)
Updates statistics incrementally, both brief and full.
GetDateRegexp ($date)
Generates date regexp to be used by statistics functions.
GetHourRegexp ($date)
Generates hour regexp to be used by statistics functions.
GetSavedStats ($logfile, &$stats, &$briefstats)
Gets saved statistics for the given log file.
GetStatsFileInfo ($logfile, &$linecount, &$filestat)
Gets previous line count and stat() from statistics file.
GetStatsFileName ($logfile)
Gets name of the tmp statistics file for the given log file.
SaveStats ($logfile, $stats, $briefstats, $linecount)
Saves collected statistics with the current line count and stat() output.
CollectDayStats ($statsdefs, $values, $line, &$stats)
Day statistics collector.
CollectHourStats ($statsdefs, $hour, $min, $values, $line, &$daystats)
Hour statistics collector.
IncStats ($line, $values, $statsdefs, &$stats)
Increments stats for the given values.
CollectMinuteStats ($statsdefs, $min, $values, $line, &$hourstats)
Minute statistics collector.
GetConfigValues ($conf, $group)
Gets all configuration for a given configuration type.
GetValue ($name, $conf, $group)
Returns all enabled configuration for a given configuration type.
GetDisabledValue ($name, $conf, $group)
Returns all disabled configuration for a given configuration type.
getValidValues ($name)
GetDisabledNVP ($file, $name, $set=0, $trimchars='')
Reads value of commented-out NVP.
GetName ($file, $name)
Checks if Name exists.
GetDisabledName ($file, $name)
Checks if commented-out Name exists.
SetConfValue ($name, $newvalue, $conf, $group)
Sets the value of NVP configuration.
GetConfValueType ($name)
EnableConf ($name, $conf, $group)
Enables a configuration item in conf file.
DisableConf ($name, $conf, $group)
Disables a configuration item in conf file.
EnableNVP ($file, $name, $type)
Enables an NVP configuration item with value.
EnableName ($file, $name)
Enables a Name: configuration item without value.
DisableNVP ($file, $name, $type)
Disables an NVP.
DisableName ($file, $name)
Disables a Name.
GetConfFile ($conf, $group)
Returns configuration file of the module.
SetConfig ($confname)
Sets configuration file based on config type provided.
Kill ()
Stops module's parent process with its pid.
KillPid ($pid)
Kills process with the given pid.
IsModulePidRunning ($pid)
Checks if the pid is running.
GetVersion ()
Gets software version string.
GetServiceStatus ($get_info=0, $start='10min', $interval_changed=0)
Gets service statuses.
getCachedContents ($filename, &$contents)
GetModuleStatus ($generate_status)
_getModuleStatus ($start, $generate_status, $do_cache=1)
_getModuleInfo ($start)
getFifoLogs ($interval=60)
getRrdValue ($rrd, $start=60, &$result, $type='derive')
getRrdfetchResolution ($output)
GetStatus ()
isPrio ($log, $prio)
GetSysCtl ($option)
Gets sysctl output for the given arg.
_getSysCtl ($option)
ParseSyslogLine ($logline, &$cols)
Parses standard syslog line.
GetNewsyslogConfig ($model)
Gets newsyslog configuration for log file.
SetNewsyslogConfig ($file, $count, $size, $when)
Sets newsyslog configuration for log file.
_getPartitions ()
Returns all partitions mounted.
GetSensors ()
Finds sysctl temp and fan sensors.
Public Member Functions inherited from View
Controller (&$output)
Calls the controller.
CheckAuthentication ($user, $passwd)
Checks the given user:password pair by testing login.
Restart ()
Stops and restarts module process(es).
Stop ()
Stops module process(es).
Start ()
Starts module process(es).
ProcessStartStopRequests ()
Processes user posts for process start and stop.
PrintStatusForm ($generate_status=0, $printcount=FALSE, $showbuttons=TRUE, $printprocs=TRUE, $showrestartbutton=FALSE)
Displays module status, software version, Restart/Stop buttons, and process table.
PrintProcessTable ($output, $printcount=FALSE)
Gets and lists processes for daemons/services.
PrintProcessTableHeader ()
Prints headers for processes table.
UploadLogFile ()
Uploads selected log file.
PrintStats ($file='')
Prints general text statistics.
IsDateRange ($date)
Checks if the date array contains a range, meaning an empty string.
FormatDate ($date)
Generic date array to string formatter.
FormatDateArray ($datestr, &$date)
Date string to array formatter.
PrintLogLine ($cols, $linenum, $lastlinenum)
Generic parser, highlighter, and printer for the log line.
getLogLineClass ($cols)
Determines log line color class.
FormatLogCols (&$cols)
Post-processes log columns for display.
SetSessionConfOpt ()
Data Fields
$Name = 'symon'
$User = '_symon'
$VersionCmd = '/usr/local/libexec/symon -v 2>&1'
Data Fields inherited from Monitoring
$LogFile = '/var/log/monitoring.log'
$Model = 'monitoring'
Data Fields inherited from Model
$Nesting = 0
Keeps the count of nested anchors in inline rules.
$Name = ''
$Proc = ''
$User = ''
$StartCmd = ''
const PROC_STAT_TIMEOUT = 30
Max number of iterations to try while starting or stopping processes.
const PROC_STAT_SLEEP_TIME = 1
$Commands = array()
Argument lists and descriptions of commands.
$NVPS = '='
$COMC = '#'
$LogFile = ''
$TmpLogsDir = ''
$PfRulesFile = '/etc/pf.conf'
$ConfFile = ''
$Config = ''
$ReloadCmd = ''
$CmdLogStart = '/usr/bin/head -1 <LF>'
$VersionCmd = ''
$PidFile = ''
Data Fields inherited from View
$Model = 'model'
$Module = 'model'
$Caption = 'Model'
$LogsHelpMsg = ''
$GraphHelpMsg = ''
$ConfHelpMsg = ''
$Layout = ''
$LogsPage = 'logs.php'
$StatsPage = 'stats.php'
$Config = array()
Configuration.
Protected Attributes
$LogFilter = 'symon'
Protected Attributes inherited from Monitoring
$LogFilter = ''
Protected Attributes inherited from Model
$psCmd = '/bin/ps arwwx -o pid,start,%cpu,time,%mem,rss,vsz,stat,pri,nice,tty,user,group,command | /usr/bin/grep -v -e grep | /usr/bin/grep -E <PROC>'
$rcConfLocal = '/etc/rc.conf.local'
$PFFWDIR = PFFWDIR
Makes the PFFWDIR define easier to use in functions, without adding a global var.
$CollectdName = ''
Used in collectd rrd and fifo file names.
$CollectdRrdFolder = PFFWDIR.'/collectd/rrd/localhost'
$CollectdFifoFolder = PFFWDIR.'/collectd/fifo'
$newSyslogConf = '/etc/newsyslog.conf'
$dateTimeFormat = 'M j H:i:s'
This datetime format is for error logs, not access logs.
Detailed Description
Definition at line 27 of file symon.php.
Constructor & Destructor Documentation
__construct()
__construct ()
Reimplemented from Monitoring.
Definition at line 39 of file symon.php.
    {
        parent::__construct();
        $this->StartCmd= '/usr/local/libexec/symon';
        $this->Commands= array_merge(
            $this->Commands,
            array(
                'SetIfs'=>  array(
                    'argv'  =>  array(NAME, NAME),
                    'desc'  =>  _('Set symon ifs'),
                    ),
                'SetConf'=> array(
                    'argv'  =>  array(NAME, NAME),
                    'desc'  =>  _('Set symon conf'),
                    ),
                'RenderLayout'=>    array(
                    'argv'  =>  array(NAME, NUM|NONE, NUM|NONE),
                    'desc'  =>  _('Render layout'),
                    ),
                'SetCpus'=> array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Set symon cpus'),
                    ),
                'SetSensors'=>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Set symon sensors'),
                    ),
                'SetPartitions'=>   array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Set symon partitions'),
                    ),
                'GetGraph'=>    array(
                    'argv'  =>  array(NAME),
                    'desc'  =>  _('Get graph'),
                    ),
                )
            );
    }
References NAME, NONE, and NUM.
Member Function Documentation
GetGraph()
GetGraph ($file)
Attention
If json_encode() inserts slashes, it is hard to decode the base64 encoded graph string on the receiving end
Definition at line 247 of file symon.php.
    {
        $graphFile= "{$this->PFFWDIR}/symon/cache/$file";
        $base64Graph= '';
        if (file_exists($graphFile)) {
            $base64Graph= base64_encode(file_get_contents($graphFile));
        }
        return Output(json_encode($base64Graph, JSON_UNESCAPED_SLASHES));
    }
References Output().
RenderLayout()
RenderLayout ($layout, $width = 700, $heigth = 250)
Generates graphs for the given layout.
This is a hacky workaround until we move symon code in the View to the Model.
Parameters
string $layout Layout name.
Returns
array Graph titles and files.
XXX
Definition at line 201 of file symon.php.
    {
        global $SRC_ROOT, $symon, $cache, $session, $chr2html, $runtime;
        require_once ("$SRC_ROOT/View/symon/class_session.inc");
        require_once ("$SRC_ROOT/View/symon/class_layout.inc");
        $session->getform('start');
        $session->getform('end');
        $session->getform('width', $width);
        $session->getform('heigth', $heigth);
        $session->getform('layout');
        $session->getform('timespan');
        $session->getform('size', 'custom');
        $l = new Layout($layout);
        $graphs = $l->render(false);
        require_once("$SRC_ROOT/View/symon/class_rrdtool.inc");
        $graphFiles= array();
        foreach ($graphs as $title => $g) {
            if (preg_match("/^([0-9a-f]+)/", $g, $match)) {
                $key = $match[1];
                $filename = $cache->getfilename($key);
                $extension = get_extension($filename);
                if ($extension == 'txt') {
                    $definition = load($filename);
                    $cache->expire_key($key);
                    $rrdtool = new RRDTool();
                    $graph_file = $cache->obtain_filecache($key);
                    $result = $rrdtool->graph($graph_file, $definition);
                } else {
                    $graph_file = $filename;
                    $result = 1;
                }
                $graphFiles[$title]= basename($graph_file);
            }
        }
        return Output(json_encode($graphFiles));
    }
References $chr2html, $graphs, $layout, $SRC_ROOT, $symon, get_extension(), load(), and Output().
SetConf()
SetConf ($lanif, $wanif)
Sets interface names in the symon and symux config files.
Parameters
string $lanif Internal interface.
string $wanif External interface.
Returns
bool TRUE on success, FALSE on fail.
Todo:
See the new OpenBSD installer to get this and sensors paths
Definition at line 117 of file symon.php.
    {
        $ncpu= 1;
        if (($hwncpu= $this->_getSysCtl('hw.ncpu')) !== FALSE) {
            if (preg_match('|^hw.ncpu=(\d+)$|ms', $hwncpu, $match)) {
                $ncpu= $match[1];
            }
        }
        $cpus= '';
        for ($i= 0; $i < $ncpu; $i++) {
            $cpus.= "   cpu($i),\n";
        }
        $others= "  mem,\n  pf,\n   mbuf,\n";
        $ifs= " if(lo0),\n  if($lanif),\n   if($wanif),\n";
        $partitions= $this->_getPartitions();
        $parts= '';
        $disks= array();
        foreach ($partitions as $part => $mdir) {
            if (preg_match('|/dev/((\w+\d+)[a-z]+)|', $part, $match)) {
                $parts.= '  df('.$match[1]."),\n";
                if (!in_array($match[2], $disks)) {
                    $disks[]= $match[2];
                }
            }
        }
        $ios= '';
        foreach ($disks as $io) {
            $ios.= "    io($io),\n";
        }
        $sensors= '';
        if (($sensorslist= $this->GetSensors()) !== FALSE) {
            if (isset($sensorslist['temp']) && count($sensorslist['temp']) > 0) {
                foreach ($sensorslist['temp'] as $s) {
                    $sensors.= "    sensor($s),\n";
                }
            }
            if (isset($sensorslist['fan']) && count($sensorslist['fan']) > 0) {
                foreach ($sensorslist['fan'] as $s) {
                    $sensors.= "    sensor($s),\n";
                }
            }
        }
        $proclist= array(
            'httpd',
            'sshd',
            'dnsmasq',
            'dhcpd',
            'ftp-proxy',
        );
        $procs= '';
        foreach ($proclist as $p) {
            $procs.= "  proc($p),\n";
        }
        $conf= "\n".$cpus.$others.$ifs.$ios.$parts.$sensors.$procs;
        $re= '|(\s*monitor\s*\{\h*)([^\}]*)(\s*\})|ms';
        $retval=  $this->ReplaceRegexp('/etc/symon.conf', $re, '${1}'.$conf.'${3}');
        $conf= preg_replace('/( )/ms', '        ', $conf);
        $re= '|(\s*source\s*127\.0\.0\.1\s*\{\s*accept\s*\{\h*)([^\}]*)(\h*\})|ms';
        $retval&= $this->ReplaceRegexp('/etc/symux.conf', $re, '${1}'.$conf.'   ${3}');
        return $retval;
    }
References $ifs, $retval, Model\_getPartitions(), Model\_getSysCtl(), Model\GetSensors(), and Model\ReplaceRegexp().
SetCpus()
SetCpus ()
Definition at line 260 of file symon.php.
    {
        $ncpu= 1;
        if (($hwncpu= $this->_getSysCtl('hw.ncpu')) !== FALSE) {
            if (preg_match('|^hw.ncpu=(\d+)$|ms', $hwncpu, $match)) {
                $ncpu= $match[1];
            }
        }
        $layout= '';
        for ($c= 0; $c < $ncpu; $c++) {
            $layout.= "graph    rrdfile=$this->rrdsPath/cpu$c.rrd, title=\"CPU $c\";\n";
        }
        $re= '|(\s*group\h+name\h*=\h*"CPU\h+Load";\s*)(.*)|ms';
        return $this->ReplaceRegexp($this->layoutsPath.'/cpus.layout', $re, '${1}'.$layout);
    }
References $layout, Model\_getSysCtl(), and Model\ReplaceRegexp().
SetIfs()
SetIfs ($lanif, $wanif)
Sets interface names in the layout files.
Parameters
string $lanif Internal interface.
string $wanif External interface.
Returns
bool TRUE on success, FALSE on fail.
Definition at line 93 of file symon.php.
    {
        $re= '|^(\s*graph\s+rrdfile\s*=\s*[\w/]+/if_)(\w+\d+)(\.rrd\s*,\s*title\s*=\s*"Internal Interface\s+\‍()(\w+\d+)(\‍)\s*"\s*;)|ms';
        $retval=  $this->ReplaceRegexp($this->layoutsPath.'/ifs.layout', $re, '${1}'.$lanif.'${3}'.$lanif.'${5}');
        $re= '|^(\s*graph\s+rrdfile\s*=\s*[\w/]+/if_)(\w+\d+)(\.rrd\s*,\s*title\s*=\s*"External Interface\s+\‍()(\w+\d+)(\‍)\s*"\s*;)|ms';
        $retval&= $this->ReplaceRegexp($this->layoutsPath.'/ifs.layout', $re, '${1}'.$wanif.'${3}'.$wanif.'${5}');
        $re= '|(\s+lan_rrd\s*=\s*[\w/]+/if_)(\w+\d+)(\.rrd\s*,\s*)|ms';
        $retval&= $this->ReplaceRegexp($this->layoutsPath.'/states.layout', $re, '${1}'.$lanif.'${3}');
        $re= '|(\s+wan_rrd\s*=\s*[\w/]+/if_)(\w+\d+)(\.rrd\s*,\s*)|ms';
        $retval&= $this->ReplaceRegexp($this->layoutsPath.'/states.layout', $re, '${1}'.$wanif.'${3}');
        return $retval;
    }
References $retval, and Model\ReplaceRegexp().
SetPartitions()
SetPartitions ()
Definition at line 301 of file symon.php.
    {
        $partitions= $this->_getPartitions();
        $layout= '';
        $disks= array();
        foreach ($partitions as $part => $mdir) {
            if (preg_match('|/dev/((\w+\d+)[a-z]+)|', $part, $match)) {
                $p= $match[1];
                $layout.= "graph    rrdfile=$this->rrdsPath/df_$p.rrd, title=\"Partition $p ($mdir)\";\n";
                if (!in_array($match[2], $disks)) {
                    $disks[]= $match[2];
                }
            }
        }
        $re= '|(\s*group\h+name\h*=\h*"Partitions\h+Usages";\s*)(.*)|ms';
        $retval=  $this->ReplaceRegexp($this->layoutsPath.'/partitions.layout', $re, '${1}'.$layout);
        $layout= '';
        foreach ($disks as $d) {
            $layout.= "graph    rrdfile=$this->rrdsPath/io_$d.rrd, title=\"Disk $d\";\n";
        }
        $re= '|(\s*group\h+name\h*=\h*"Disk\h+I/O";\s*)(.*)|ms';
        $retval&= $this->ReplaceRegexp($this->layoutsPath.'/disks.layout', $re, '${1}'.$layout);
        return $retval;
    }
References $layout, $retval, Model\_getPartitions(), and Model\ReplaceRegexp().
SetSensors()
SetSensors ()
Definition at line 278 of file symon.php.
    {
        if (($sensorslist= $this->GetSensors()) !== FALSE) {
            $layout= '';
            if (isset($sensorslist['temp']) && count($sensorslist['temp']) > 0) {
                foreach ($sensorslist['temp'] as $s) {
                    $layout.= "graph    rrdfile=$this->rrdsPath/sensor_$s.rrd, title=\"Temperature ($s)\";\n";
                }
            }
            $layout.= 'group    name="Fan";'."\n";
            if (isset($sensorslist['fan']) && count($sensorslist['fan']) > 0) {
                foreach ($sensorslist['fan'] as $s) {
                    $layout.= "graph    rrdfile=$this->rrdsPath/sensor_$s.rrd, title=\"Fan ($s)\";\n";
                }
            }
            $re= '|(\s*group\h+name\h*=\h*"Temperature";\s*)(.*)|ms';
            return $this->ReplaceRegexp($this->layoutsPath.'/sensors.layout', $re, '${1}'.$layout);
        }
        return FALSE;
    }
References $layout, Model\GetSensors(), and Model\ReplaceRegexp().
Field Documentation
$LogFilter
$LogFilter = 'symon' protected
Definition at line 37 of file symon.php.
$Name
$Name = 'symon'
Definition at line 29 of file symon.php.
$User
$User = '_symon'
Definition at line 30 of file symon.php.
$VersionCmd
$VersionCmd = '/usr/local/libexec/symon -v 2>&1'
Definition at line 35 of file symon.php.
The documentation for this class was generated from the following file:
src/Model/symon.php