PF Firewall: Graph Class Reference
Graph Class Reference
Public Member Functions
__construct (&$group_vars)
set_graph_vars (&$graph_vars)
_makevars ()
_parse_filename ($filename, $index='')
parse (&$lexer)
render ($html=true)
_url ()
_save ()
_preprocess ()
_constrain ()
_display ()
Data Fields
$template
$vars
$graph_vars
$group_vars
$definition
$url
Detailed Description
Definition at line 44 of file class_graph.inc.
Constructor & Destructor Documentation
__construct()
__construct (& $group_vars)
Definition at line 52 of file class_graph.inc.
{
    $this->group_vars = $group_vars;
    }
References $group_vars.
Member Function Documentation
_constrain()
_constrain ()
Definition at line 250 of file class_graph.inc.
{
    global $symon;
    $definition = '';
    if (!is_array($this->definition)) {
        return 1;
    }
    reset($this->definition);
    foreach ($this->definition as $t) {
        if (preg_match("/^([^-]*)(-[^ ]+) ([^ ]+)(.*)$/", $t)) {
        while (preg_match("/^([^-]*)(-[^ ]+) ([^ ]+)(.*)$/", $t, $match)) {
            $definition .= $match[1];
            foreach ($symon['constraints'] as $k => $v) {
            if ($k == $match[2]) {
                if (is_array($symon['constraints'][$k])
                && isset($symon['constraints'][$k]["max"])
                && ($match[3] > $symon['constraints'][$k]["max"])) {
                $match[3] = $symon['constraints'][$k]["max"];
                }
                if (is_array($symon['constraints'][$k])
                && isset($symon['constraints'][$k]["min"])
                && ($match[3] < $symon['constraints'][$k]["min"])) {
                $match[3] = $symon['constraints'][$k]["min"];
                }
            }
            }
            $definition .= $match[2].' '.$match[3];
            $t = $match[4];
        }
        }
        $definition .= $t . "\n";
    }
    $this->definition = preg_split("/\n/", $definition);
    }
References $definition, and $symon.
Referenced by _save().
_display()
_display ()
Definition at line 286 of file class_graph.inc.
{
    print "\xa graph ";
    if (isset($this->template)) {
        print "\xa  template=";
        foreach ($this->template as $line) {
        print "\xa    '$line'";
        }
    }
    if (isset($this->vars)) {
        $vars = $this->vars->tostring();
        if (strlen($vars) > 0) {
        print $vars;
        }
        print ";";
    } else if (isset($this->graph_vars)) {
        $vars = $this->graph_vars->tostring();
        if (strlen($vars) > 0) {
        print $vars;
        }
        print ";";
    }
    }
References $vars, and print.
Referenced by _makevars(), _parse_filename(), and _save().
_makevars()
_makevars ()
Definition at line 60 of file class_graph.inc.
{
    global $session;
    global $symon;
    $this->definition = '';
    unset($this->url);
    /* create local state by combining group and local graph args */
    $this->vars = new Vars();
    $this->vars->addvars($session->getvars());
    $this->vars->addvars($this->graph_vars);
    $this->vars->addvars($this->group_vars);
    if ($this->vars->defp('rrdfile')) {
        $this->_parse_filename($this->vars->get('rrdfile'));
    } else if ($this->vars->defp('rrdfile0')) {
        $n = 0;
        $this->_parse_filename($this->vars->get('rrdfile0'));
        while ($this->vars->defp('rrdfile'.$n)) {
        $this->_parse_filename($this->vars->get('rrdfile'.$n), $n);
        $n++;
        }
    }
    if (!$this->vars->defp('template')) {
        if ($this->vars->defp('rrdtype0')) {
        $template = get_combined_template($this->vars->get('rrdtype0'), $n);
        } else if ($this->vars->defp('rrdtype')) {
        $template = get_single_template($this->vars->get('rrdtype'));
        } else {
        warning('graph: cannot load graph template: filename does not yield a graphtype ('. $this->vars->get('rrdfile'));
        if (isset($symon['graph_debug'])) {
            $this->_display();
        }
        }
    } else {
        $template = $this->vars->get('template');
    }
    if ($template != "") {
        $this->template = preg_split("/\n/", $template);
    } else {
        if (isset($symon['graph_debug'])) {
        $this->_display();
        warning('graph: template not set');
        }
    }
    }
References $symon, $template, _display(), _parse_filename(), get_combined_template(), get_single_template(), and warning().
Referenced by _save().
_parse_filename()
_parse_filename ($filename, $index = '')
Definition at line 109 of file class_graph.inc.
{
    if (preg_match("/^(.*\/)?((cpu|if|io|mem|pf|pfq|proc|debug|mbuf|sensor|df)([0-9]{0,2}))(_([a-z0-9\.]+))?([0-9]{0,4}[a-z]{0,1}[0-9]{0,1}[a-z]{0,1}).rrd$/",
               $filename, $match)) {
        $this->vars->def('rrdtype'. $index, $match[2]);
        $this->vars->def('rrdwhat'. $index, $match[6]);
        $this->vars->def('rrdwhich'. $index, $match[7]);
        $this->vars->def('title'. $index,
                 $match[2].'('.$match[6].$match[7].') of '. $this->vars->get('name'));
    }
    else if (preg_match("/^(.*\/)?(sensor)(it[0-9]+\.[a-z]+)?([0-9]{0,1}).rrd$/",
               $filename, $match)) {
        $this->vars->def('rrdtype'. $index, $match[2]);
        $this->vars->def('rrdwhat'. $index, $match[3]);
        $this->vars->def('rrdwhich'. $index, $match[4]);
        $this->vars->def('title'. $index,
                 $match[2].'('.$match[3].$match[4].') of '. $this->vars->get('name'));
    } else {
        if (isset($symon['graph_debug'])) {
        $this->_display();
        warning('graph: cannot determine rrd type from filename "'.$filename.'"');
        }
    }
    }
References $symon, _display(), and warning().
Referenced by _makevars().
_preprocess()
_preprocess ()
Definition at line 206 of file class_graph.inc.
{
    $definition = '';
    if (!isset($this->template) || !is_array($this->template)) {
        return;
    }
    reset($this->template);
    foreach ($this->template as $t) {
        $startpos = strpos($t, "%", 0);
        if ($startpos + 1 > strlen($t)) {
        $endpos = false;
        } else {
        $endpos = strpos($t, "%", $startpos + 1);
        }
        while ($startpos !== false && $endpos !== false) {
        $leader = substr($t, 0, $startpos);
        $key = substr($t, $startpos + 1, $endpos - $startpos - 1);
        $tailer = substr($t, $endpos + 1);
        $definition .= $leader;
        if ($this->vars->defp($key)) {
            $definition .= $this->vars->get($key);
        } else {
            $definition .= "%" . $key;
            $tailer = "%" . $tailer;
        }
        $t = $tailer;
        $startpos=strpos($t, "%", 0);
        if ($startpos + 1 > strlen($t)) {
            $endpos = false;
        } else {
            $endpos = strpos($t, "%", $startpos + 1);
        }
        }
        $definition .= $t . "\n";
    }
    $this->definition = preg_split("/\n/", $definition);
    }
References $definition.
Referenced by _save().
_save()
_save ()
Definition at line 158 of file class_graph.inc.
                     {
    global $cache;
    global $symon;
    $this->_makevars();
    if (isset($symon['graph_debug'])) {
        print "<pre>";
        $this->_display();
        print "</pre>";
    }
    $this->_preprocess();
    if (isset($symon['graph_debug'])) {
        print "<pre>\xa preprocessed template = ";
        if (isset($this->definition) && $this->definition != "") {
        foreach ($this->definition as $line) {
            print "\xa    '$line'";
        }
        }
        print "</pre>";
    }
    $this->_constrain();
    if (isset($symon['graph_debug'])) {
        print "<pre>\xa constrained template = ";
        if (isset($this->definition) && $this->definition != "") {
        foreach ($this->definition as $line) {
            print "\xa    '$line'";
        }
        }
        print "</pre>";
    }
    if ($this->definition != "") {
        $seed = $this->vars->tostring();
        $graph_command = implode("\n", $this->definition);
        $this->url = $cache->insert($graph_command, '.txt', $seed);
        if (isset($symon['graph_debug'])) {
        print "<pre>\xa url = ". $this->url. "</pre>";
        }
    }
    }
References $symon, _constrain(), _display(), _makevars(), _preprocess(), and print.
Referenced by render().
_url()
_url ()
Definition at line 148 of file class_graph.inc.
                    {
    if (!isset($this->url)) {
        runtime_error("graph: internal error : need to save the graph before an url can be requested");
        return '';
    } else {
        return $this->url;
    }
    }
References $url, and runtime_error().
Referenced by render().
parse()
parse (& $lexer)
Definition at line 133 of file class_graph.inc.
{
    $this->graph_vars = new Vars();
    $this->graph_vars->parse($lexer);
    }
render()
render ($html = true)
Definition at line 138 of file class_graph.inc.
{
        $this->_save();
        if (isset($this->template)) {
            if ($html) {
                print '<img src="../symon/graph.php?' . $this->_url() . '" class="graph">';
            }
        }
        return $this->_url();
    }
References _save(), _url(), and print.
set_graph_vars()
set_graph_vars (& $graph_vars)
Definition at line 56 of file class_graph.inc.
{
    $this->graph_vars = $graph_vars;
    }
References $graph_vars.
Field Documentation
$definition
$definition
Definition at line 49 of file class_graph.inc.
Referenced by _constrain(), and _preprocess().
$graph_vars
$graph_vars
Definition at line 47 of file class_graph.inc.
Referenced by set_graph_vars().
$group_vars
$group_vars
Definition at line 48 of file class_graph.inc.
Referenced by __construct().
$template
$template
Definition at line 45 of file class_graph.inc.
Referenced by _makevars().
$url
$url
Definition at line 50 of file class_graph.inc.
Referenced by _url().
$vars
$vars
Definition at line 46 of file class_graph.inc.
Referenced by _display().
The documentation for this class was generated from the following file:
src/View/symon/class_graph.inc