PF Firewall: Lexer Class Reference
Lexer Class Reference
Public Member Functions
__construct ()
is_eof ()
load ($filename='')
next_token ()
parse_error ($errorstring, $lineno=0)
parse_semicolon ()
unget ($token)
_get_chr ()
_get_chr_and_nl ()
_get_next_line ()
_next_token ()
_get_quoted_string ($quote)
_unget_chr ($ch)
_display ()
_test ()
Data Fields
$filename
$lineno
$lineitems
$line
$buffer
$token
$unget
$keywordchrs
Detailed Description
Definition at line 36 of file class_lexer.inc.
Constructor & Destructor Documentation
__construct()
__construct ()
Definition at line 46 of file class_lexer.inc.
{
    $this->filename = '';
    $this->lineno = 0;
    $this->buffer = array();
    $this->line = array();
    $this->eof = 0;
    $this->token = '';
    $this->unget = array();
    $this->keywordchrs = '/ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_.';
    }
References unget().
Member Function Documentation
_display()
_display ()
Definition at line 224 of file class_lexer.inc.
{
    print "<pre>\xa -- token = $this->token";
    print "\xa lexing $this->filename:$this->lineno";
    print "\xa line = $this->line";
    print "\xa items = ";
    if (count($this->lineitems)) {
        foreach ($this->lineitems as $k => $item) {
        print $item. '|';
        }
    }
    print "\xa unget = ";
    if (count($this->unget) > 0) {
        foreach ($this->unget as $item) {
        print $item. '|';
        }
    }
    print "\xa eof = $this->eof </pre>";
    }
References print, and unget().
Referenced by next_token().
_get_chr()
_get_chr ()
Definition at line 111 of file class_lexer.inc.
{
    $item = $this->_get_chr_and_nl();
    if ($item == "\n") {
        $item = ' ';
    }
    return $item;
    }
References _get_chr_and_nl().
Referenced by _next_token().
_get_chr_and_nl()
_get_chr_and_nl ()
Definition at line 119 of file class_lexer.inc.
{
    if ($this->eof) {
        runtime_error('internal: trying to get_chr while eof has been signalled');
    }
    if (count($this->unget)) {
        return array_shift($this->unget);
    }
    $item = '';
    while ($item == '') {
        if (!is_array($this->lineitems) || count($this->lineitems) == 0) {
        $this->_get_next_line();
        if ($this->eof) {
            return;
        }
        return "\n";
        }
        $item = array_shift($this->lineitems);
    }
    return $item;
    }
References _get_next_line(), runtime_error(), and unget().
Referenced by _get_chr(), and _get_quoted_string().
_get_next_line()
_get_next_line ()
Definition at line 140 of file class_lexer.inc.
{
    if ($this->eof) {
        runtime_error('internal: trying to get_next_line while eof has been signalled');
    }
    if (count($this->buffer) == 0) {
        $this->eof = 1;
        return;
    }
    $this->line = array_shift($this->buffer);
    $this->lineno += 1;
    $this->lineitems = preg_split('//', $this->line, -1, PREG_SPLIT_NO_EMPTY);
    }
References runtime_error().
Referenced by _get_chr_and_nl(), and _next_token().
_get_quoted_string()
_get_quoted_string ($quote)
Definition at line 199 of file class_lexer.inc.
{
    $start_lineno = $this->lineno;
    $this->token = '';
    $delimited = 0;
    $ch = $this->_get_chr_and_nl();
    while ($ch != $quote) {
        if ($this->eof) {
        $this->parse_error("starting $quote without closing $quote", $start_lineno);
        return;
        }
        if ($ch == "\\" && $quote == '"') {
        $ch = $this->_get_chr_and_nl();
        }
        $this->token .= $ch;
        $ch = $this->_get_chr_and_nl();
    }
    return $this->token;
    }
References $lineno, $token, _get_chr_and_nl(), and parse_error().
Referenced by _next_token().
_next_token()
_next_token ()
Definition at line 153 of file class_lexer.inc.
{
    if ($this->eof) {
        runtime_error('internal: trying next_token while eof has been signalled');
    }
    $this->token = '';
    $ch = $this->_get_chr();
    while ($this->eof || !(strpos(" \t\r\n#", $ch) === FALSE)) {
        if ($this->eof) {
        return;
        }
        if ($ch == '#') {
        $this->_get_next_line();
        }
        $ch = $this->_get_chr();
    }
    if ($this->eof) {
        $this->token = '';
        return $this->token;
    }
    if ($ch == '"') {
        $this->token = $this->_get_quoted_string('"');
        return $this->token;
    }
    if ($ch == "'") {
        $this->token = $this->_get_quoted_string("'");
        return $this->token;
    }
    if (!(strpos($this->keywordchrs, $ch) === FALSE)) {
        $this->token = '';
        while (!(strpos($this->keywordchrs, $ch) === FALSE) || $this->eof) {
        $this->token .= $ch;
        $ch = $this->_get_chr();
        }
        if (!$this->eof) {
        $this->_unget_chr($ch);
        }
        return $this->token;
    }
    $this->token = $ch;
    return $this->token;
    }
References $token, _get_chr(), _get_next_line(), _get_quoted_string(), _unget_chr(), and runtime_error().
Referenced by next_token().
_test()
_test ()
Definition at line 243 of file class_lexer.inc.
                     {
    global $symon;
    $this->load('hifn_test.layout');
    while(!$this->eof) {
        $token = $this->next_token();
    }
    }
References $symon, $token, load(), and next_token().
_unget_chr()
_unget_chr ($ch)
Definition at line 220 of file class_lexer.inc.
{
    $this->unget[] = $ch;
    }
References unget().
Referenced by _next_token(), and unget().
is_eof()
is_eof ()
Definition at line 57 of file class_lexer.inc.
                      {
    return $this->eof;
    }
load()
load ($filename = '')
Definition at line 61 of file class_lexer.inc.
{
    global $symon;
    if ($filename == '') {
        runtime_error('layout parser: no file to load');
    }
    $filename = normalise_filename($filename);
    $filename = $symon['layout_dir'].'/'.normalise_filename($filename).'.layout';
    $this->filename = $filename;
    $buffer = load($filename);
    $this->buffer = preg_split("/\n/", $buffer);
    }
References $buffer, $filename, $symon, load(), normalise_filename(), and runtime_error().
Referenced by _test(), and load().
next_token()
next_token ()
Definition at line 74 of file class_lexer.inc.
{
    global $symon;
    $token = $this->_next_token();
    if (isset($symon['lexer_debug'])) {
        $this->_display();
    }
    return $token;
    }
References $symon, $token, _display(), and _next_token().
Referenced by _test(), and parse_semicolon().
parse_error()
parse_error ($errorstring, $lineno = 0)
Definition at line 86 of file class_lexer.inc.
{
    if ($lineno == 0) {
        $lineno = $this->lineno;
    }
    runtime_error("parse error: $this->filename : $lineno : '$this->token' : $errorstring");
    }
References $lineno, and runtime_error().
Referenced by _get_quoted_string(), and parse_semicolon().
parse_semicolon()
parse_semicolon ()
Definition at line 94 of file class_lexer.inc.
{
    if ($this->eof) {
        $this->parse_error('Expected ;');
    }
    $token = $this->next_token();
    if ($token != ';') {
        $this->parse_error('Expected ;');
    }
    }
References next_token(), and parse_error().
unget()
unget ($token)
Definition at line 104 of file class_lexer.inc.
{
    $items = preg_split('//', $token, -1, PREG_SPLIT_NO_EMPTY);
    foreach ($items as $k => $item) {
        $this->_unget_chr($item);
    }
    }
References $token, and _unget_chr().
Referenced by __construct(), _display(), _get_chr_and_nl(), and _unget_chr().
Field Documentation
$buffer
$buffer
Definition at line 41 of file class_lexer.inc.
Referenced by load().
$filename
$filename
Definition at line 37 of file class_lexer.inc.
Referenced by load().
$keywordchrs
$keywordchrs
Definition at line 44 of file class_lexer.inc.
$line
$line
Definition at line 40 of file class_lexer.inc.
$lineitems
$lineitems
Definition at line 39 of file class_lexer.inc.
$lineno
$lineno
Definition at line 38 of file class_lexer.inc.
Referenced by _get_quoted_string(), and parse_error().
$token
$token
Definition at line 42 of file class_lexer.inc.
Referenced by _get_quoted_string(), _next_token(), _test(), next_token(), and unget().
$unget
$unget
Definition at line 43 of file class_lexer.inc.
The documentation for this class was generated from the following file:
src/View/symon/class_lexer.inc