PF Firewall: System Class Reference
System Class Reference
Public Member Functions
__construct ()
AddHost ($host)
Adds host line to hosts file.
DelHost ($host)
Deletes host line from hosts file.
GetHosts ()
Reads hosts file contents.
GetMyName ()
Reads hostname.
_getMyName ()
GetNameServer ()
Reads nameserver setting.
GetRootEmail ()
Reads root e-mail address.
GetIfConfig ($if)
Reads interface configuration.
_getIfConfig ($if)
isIfUp ($if)
GetStaticGateway ()
Reads static gateway address from mygate file.
GetDynamicGateway ()
Reads the default gateway on the routing table.
getSystemGateway ()
Gets system gateway, static or dynamic.
_getStaticGateway ()
_getDynamicGateway ()
GetConfig ()
Reads hostname, gateway, and interface configuration.
_getModuleInfo ($start)
SystemMakeStaticGateway ()
Converts dynamic gateway address to static address.
SystemMakeDynamicGateway ()
Converts static gateway address to dynamic address.
SetMyGate ($mygate)
Sets system static gateway.
SetMyName ($myname)
Sets system hostname.
SetIf ($if, $type, $ip, $mask, $bc, $opt, $nwid, $keytype, $key, $hostap)
Sets system interface configuration.
DeleteIf ($if)
Deconfigures an interface by deleting its hostname file.
SetNameServer ($nameserver)
Changes nameserver.
SetRootEmail ($emailaddr)
Changes root e-mail address.
SetDateTime ($datetime)
Sets system clock.
UpdateMailAliases ()
Updates mail aliases.
AutoConfig ()
Runs installer with the automatic configuration option.
InitGraphs ()
Deletes all graph files and recreates them as necessary.
DeleteStats ()
Deletes temporary logs, statistics, and output files created by the WUI.
Shutdown ()
Halts and powers the system down.
Restart ()
Restarts the system.
DisplayRemoteTime ($timeserver)
Displays datetime from the given time server.
SetRemoteTime ($timeserver)
Sets datetime from the given time server.
GetRemoteTime ()
Reads datetime temporary output file.
NetStart ($if='')
Restarts the network.
reloadPfRules ()
IfUpDown ($if, $updown)
SelectProcesses ($psout)
Reads all processes from ps output.
SetManCgiHome ($ip)
Set int_net.
GetPartitions ()
Gets partition list.
_getPartitions ()
Returns all partitions mounted.
GetSystemInfo ()
Gets system information.
GetServiceStartStatus ()
Gets service start stati.
GetServiceStatRcConfLocal ($file, $service)
Gets service startup status in rc.conf.local.
GetServiceStatRcLocal ($file, $service)
Gets service startup status in rc.local.
DisableService ($service)
Turn off (disable) service startup.
EnableService ($service)
Turn on (enable) service startup.
DisableServiceRcConfLocal ($service)
Turn off (disable) service startup in rc.conf.local.
DisableServiceRcLocal ($service)
Turn off (disable) service startup in rc.local.
EnableServiceRcConfLocal ($service)
Turn on (enable) service startup in rc.conf.local.
EnableServiceRcLocal ($service)
Turn on (enable) service startup in rc.local.
GetLogsConfig ()
Get logs configuration.
SetLogsConfig ($model, $file, $count, $size, $when)
Set logs configuration.
RotateLogFile ($file)
Calls forked rotation function.
DaemonizedRotateLogFile ($file)
Rotate log file via newsyslog.
RotateAllLogFiles ()
Calls forked full rotation function.
DaemonizedRotateAllLogFiles ()
Rotate all log files via newsyslog.
DaemonizeFunc ($func, $param='')
Daemonizes to run the given function.
IsNotifierEnabled ()
DisableNotifier ()
EnableNotifier ()
getRootCronTab ()
SetNotifyLevel ($level)
SetNotifierHost ($host)
DisableNotifierSSLVerifyPeer ($bool)
EnableNotifierSSLVerifyPeer ($bool)
SetNotifierAPIKey ($apikey)
AddNotifierUser ($userJson)
DelNotifierUser ($token)
AddFilter ($filter)
DelFilter ($filter)
_delFilter ($tokens, $token)
SetNotifierTimeout ($timeout)
GenerateSSLKeyPair ($set_serial)
Generates SSL key pair for httpd.
EnableHostap ($if)
Enables hostap on the given interface.
GetMFSConfig ()
SetMFS ($value)
SetMFSSize ($value)
SetSyncMFS ($value)
__construct ()
FormatLogCols (&$cols)
Post-processes log columns for display.
Public Member Functions inherited from Model
__construct ()
IsRunning ($proc='')
Checks if the given process(es) is running.
GetProcList ()
Gets the list of processes running.
SelectProcesses ($psout)
Selects user processes from ps output.
Start ()
Start module process(es).
Stop ()
Stops module process(es)
Pkill ($proc, $args='')
Kills the given process(es).
GetIntIf ()
Get int_if.
_getIntIf ()
GetExtIf ()
Get ext_if.
_getExtIf ()
isWifiIf ($if)
CreateUser ($user, $passwd, $uid)
Creates a system user.
SetPassword ($user, $passwd)
Sets user's password in the system password file.
SetLogLevel ($level)
Sets global log level.
SetHelpBox ($bool)
Enables or disables help boxes.
SetSessionTimeout ($timeout)
Sets session timeout.
SetDefaultLocale ($locale)
Sets default locale.
SetForceHTTPs ($bool)
Enables or disables HTTPs.
SetUseSSH ($bool)
Enables or disables SSH.
SetMaxAnchorNesting ($max)
Sets the max number of nested anchors allowed.
SetPfctlTimeout ($timeout)
Sets pfctl timeout.
SetStatusCheckInterval ($interval)
Sets status check interval.
SetMaxFileSizeToProcess ($size)
Sets max file size to process.
GetReloadRate ()
Gets default reload rate.
_getReloadRate ()
SetReloadRate ($rate)
Sets default reload rate.
RunShellCommand ($cmd)
Runs the given shell command and returns its output as string.
GetFiles ($filepath)
Returns files with the given filepath pattern.
GetFile ($file)
Reads file contents.
DeleteFile ($path)
Deletes the given file or directory.
PutFile ($file, $contents)
Writes contents to file.
SetNVP ($file, $name, $newvalue)
Changes value of NVP.
GetNVP ($file, $name, $set=0, $trimchars='')
Reads value of NVP.
SearchFile ($file, $re, $set=0, $trimchars='')
Searches the given file with the given regex.
SearchFileAll ($file, $re, $set=1)
Multi-searches a given file with a given regexp.
ReplaceRegexp ($file, $matchre, $replacere)
Searches a needle and replaces with a value in the given file.
AppendToFile ($file, $line)
Appends a string to a file.
GetDateTime ()
Gets system datetime.
GetPhyIfs ()
Extracts physical interface names from ifconfig output.
_getPhyIfs ()
GetDefaultLogFile ()
Gets the log file of the module.
SelectLogFile ($file)
Gets the log file under the tmp folder.
IsLogFileModified ($logfile)
Checks if the given log file has been updated.
GetTmpLogFileName ($file)
Gets the name of the file in the tmp folder.
UpdateTmpLogFile ($file)
Copies the original log file to tmp folder.
formatDateHourRegexp ($month, $day, $hour, $minute)
Generates the module specific datetime regexp for filtering logs.
formatDateHourRegexpDayLeadingZero ($month, $day, $hour, $minute)
formatDateHourRegexpWeekDays ($month, $day, $hour, $minute)
GetFileLineCount ($file, $re='', $needle='', $month='', $day='', $hour='', $minute='')
Gets line count of the given log file.
_getFileLineCount ($file, $re='', $needle='', $month='', $day='', $hour='', $minute='')
GetLogs ($file, $end, $count, $re='', $needle='', $month='', $day='', $hour='', $minute='')
Gets lines in log file.
GetLiveLogs ($file, $count, $re='')
Gets logs for live logs pages.
_getLiveLogs ($file, $count, $re='', $needle='', $reportFileExistResult=TRUE)
Gets logs for live logs pages, the actual method.
GetLastLogs ($file, $count)
GetLogFilesList ()
Gets log files list with start dates.
GetLogStartDate ($file)
Extracts the datetime of the first line in the log file.
_getLogStartDate ($file)
GetFileFirstLine ($file)
Gets first line of file.
ParseLogLine ($logline, &$cols)
Parses the given log line.
PostProcessCols (&$cols)
Further processes parser output fields.
PrepareFileForDownload ($file)
Prepares file for download over WUI.
GetOrigFileName ($logfile)
Gets the original file name for the given log file.
GetProcStatLines ($logfile)
Collects text statistics for the proc stats general page.
CopyLogFileToTmp ($file, $tmpdir)
Uncompresses gzipped log file to tmp dir.
GetStatsLogLines ($logfile, $tail=-1)
Builds generic grep command and extracts log lines.
GetAllStats ($logfile, $collecthours='')
Gets both brief and full statistics.
GetStats ($logfile, $date, $collecthours='')
Main statistics collector, as module data set.
_getStats ($logfile, $date, $collecthours='')
ValidateFile ($file, $reportFileExistResult=TRUE)
Checks if the given file exists and not larger than $MaxFileSizeToProcess in MBs.
ValidateFileExists ($file, $reportFileExistResult=TRUE)
CountDiffLogLines ($logfile, &$count)
Gets the number of lines added to log files since last tmp file update.
UpdateStats ($logfile, &$stats, &$briefstats)
Updates statistics incrementally, both brief and full.
GetDateRegexp ($date)
Generates date regexp to be used by statistics functions.
GetHourRegexp ($date)
Generates hour regexp to be used by statistics functions.
GetSavedStats ($logfile, &$stats, &$briefstats)
Gets saved statistics for the given log file.
GetStatsFileInfo ($logfile, &$linecount, &$filestat)
Gets previous line count and stat() from statistics file.
GetStatsFileName ($logfile)
Gets name of the tmp statistics file for the given log file.
SaveStats ($logfile, $stats, $briefstats, $linecount)
Saves collected statistics with the current line count and stat() output.
CollectDayStats ($statsdefs, $values, $line, &$stats)
Day statistics collector.
CollectHourStats ($statsdefs, $hour, $min, $values, $line, &$daystats)
Hour statistics collector.
IncStats ($line, $values, $statsdefs, &$stats)
Increments stats for the given values.
CollectMinuteStats ($statsdefs, $min, $values, $line, &$hourstats)
Minute statistics collector.
GetConfigValues ($conf, $group)
Gets all configuration for a given configuration type.
GetValue ($name, $conf, $group)
Returns all enabled configuration for a given configuration type.
GetDisabledValue ($name, $conf, $group)
Returns all disabled configuration for a given configuration type.
getValidValues ($name)
GetDisabledNVP ($file, $name, $set=0, $trimchars='')
Reads value of commented-out NVP.
GetName ($file, $name)
Checks if Name exists.
GetDisabledName ($file, $name)
Checks if commented-out Name exists.
SetConfValue ($name, $newvalue, $conf, $group)
Sets the value of NVP configuration.
GetConfValueType ($name)
EnableConf ($name, $conf, $group)
Enables a configuration item in conf file.
DisableConf ($name, $conf, $group)
Disables a configuration item in conf file.
EnableNVP ($file, $name, $type)
Enables an NVP configuration item with value.
EnableName ($file, $name)
Enables a Name: configuration item without value.
DisableNVP ($file, $name, $type)
Disables an NVP.
DisableName ($file, $name)
Disables a Name.
GetConfFile ($conf, $group)
Returns configuration file of the module.
SetConfig ($confname)
Sets configuration file based on config type provided.
Kill ()
Stops module's parent process with its pid.
KillPid ($pid)
Kills process with the given pid.
IsModulePidRunning ($pid)
Checks if the pid is running.
GetVersion ()
Gets software version string.
GetServiceStatus ($get_info=0, $start='10min', $interval_changed=0)
Gets service statuses.
getCachedContents ($filename, &$contents)
GetModuleStatus ($generate_status)
_getModuleStatus ($start, $generate_status, $do_cache=1)
_getModuleInfo ($start)
getFifoLogs ($interval=60)
getRrdValue ($rrd, $start=60, &$result, $type='derive')
getRrdfetchResolution ($output)
GetStatus ()
isPrio ($log, $prio)
GetSysCtl ($option)
Gets sysctl output for the given arg.
_getSysCtl ($option)
ParseSyslogLine ($logline, &$cols)
Parses standard syslog line.
GetNewsyslogConfig ($model)
Gets newsyslog configuration for log file.
SetNewsyslogConfig ($file, $count, $size, $when)
Sets newsyslog configuration for log file.
_getPartitions ()
Returns all partitions mounted.
GetSensors ()
Finds sysctl temp and fan sensors.
Public Member Functions inherited from View
Controller (&$output)
Calls the controller.
CheckAuthentication ($user, $passwd)
Checks the given user:password pair by testing login.
Restart ()
Stops and restarts module process(es).
Stop ()
Stops module process(es).
Start ()
Starts module process(es).
ProcessStartStopRequests ()
Processes user posts for process start and stop.
PrintStatusForm ($generate_status=0, $printcount=FALSE, $showbuttons=TRUE, $printprocs=TRUE, $showrestartbutton=FALSE)
Displays module status, software version, Restart/Stop buttons, and process table.
PrintProcessTable ($output, $printcount=FALSE)
Gets and lists processes for daemons/services.
PrintProcessTableHeader ()
Prints headers for processes table.
UploadLogFile ()
Uploads selected log file.
PrintStats ($file='')
Prints general text statistics.
IsDateRange ($date)
Checks if the date array contains a range, meaning an empty string.
FormatDate ($date)
Generic date array to string formatter.
FormatDateArray ($datestr, &$date)
Date string to array formatter.
PrintLogLine ($cols, $linenum, $lastlinenum)
Generic parser, highlighter, and printer for the log line.
getLogLineClass ($cols)
Determines log line color class.
FormatLogCols (&$cols)
Post-processes log columns for display.
SetSessionConfOpt ()
Static Public Member Functions
static DisplayDashboardExtras ()
Data Fields
$Name = 'system'
$confDir = '/etc/'
$User = '\S+'
$LogFile = '/var/log/messages'
$Model = 'system'
$Layout = 'system'
Data Fields inherited from Model
$Nesting = 0
Keeps the count of nested anchors in inline rules.
$Name = ''
$Proc = ''
$User = ''
$StartCmd = ''
const PROC_STAT_TIMEOUT = 30
Max number of iterations to try while starting or stopping processes.
const PROC_STAT_SLEEP_TIME = 1
$Commands = array()
Argument lists and descriptions of commands.
$NVPS = '='
$COMC = '#'
$LogFile = ''
$TmpLogsDir = ''
$PfRulesFile = '/etc/pf.conf'
$ConfFile = ''
$Config = ''
$ReloadCmd = ''
$CmdLogStart = '/usr/bin/head -1 <LF>'
$VersionCmd = ''
$PidFile = ''
Data Fields inherited from View
$Model = 'model'
$Module = 'model'
$Caption = 'Model'
$LogsHelpMsg = ''
$GraphHelpMsg = ''
$ConfHelpMsg = ''
$Layout = ''
$LogsPage = 'logs.php'
$StatsPage = 'stats.php'
$Config = array()
Configuration.
Additional Inherited Members
Protected Attributes inherited from Model
$psCmd = '/bin/ps arwwx -o pid,start,%cpu,time,%mem,rss,vsz,stat,pri,nice,tty,user,group,command | /usr/bin/grep -v -e grep | /usr/bin/grep -E <PROC>'
$rcConfLocal = '/etc/rc.conf.local'
$PFFWDIR = PFFWDIR
Makes the PFFWDIR define easier to use in functions, without adding a global var.
$CollectdName = ''
Used in collectd rrd and fifo file names.
$CollectdRrdFolder = PFFWDIR.'/collectd/rrd/localhost'
$CollectdFifoFolder = PFFWDIR.'/collectd/fifo'
$newSyslogConf = '/etc/newsyslog.conf'
$dateTimeFormat = 'M j H:i:s'
This datetime format is for error logs, not access logs.
Detailed Description
Definition at line 27 of file system.php.
Constructor & Destructor Documentation
__construct() [1/2]
__construct ()
rc.local module search strings and descriptions
rc.local file should have lines like the following:
if [ -x /usr/local/libexec/symon ]; then
    echo -n ' symon';
    /usr/local/libexec/symon
fi
Indeces of this array are used to comment or uncomment the lines like the 3rd one above.
rc.conf.local module search strings and descriptions
Todo:
Is there any pattern or size for options, 6th param?
Reimplemented from Model.
Definition at line 44 of file system.php.
    {
        parent::__construct();
        $this->Proc= '.';
        $this->rcLocalServices= array(
            '/usr/local/sbin/php-fpm-8.2',
            '/usr/local/sbin/dnsmasq',
            '/usr/local/libexec/symux',
            '/usr/local/libexec/symon',
            '/usr/local/sbin/collectd',
            );
        $this->rcConfLocalServices= array(
            'pf',
            'httpd_flags',
            'slowcgi_flags',
            'dhcpd_flags',
            'ftpproxy_flags',
            'ntpd_flags',
            'apmd_flags',
            );
        $this->Commands= array_merge(
            $this->Commands,
            array(
                'GetMyName'     =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Read system hostname'),
                    ),
                'GetRootEmail'  =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Get system admin e-mail address'),
                    ),
                'GetIfConfig'       =>  array(
                    'argv'  =>  array(NAME),
                    'desc'  =>  _('Get if config'),
                    ),
                'GetStaticGateway'      =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Read system gateway'),
                    ),
                'GetHosts'      =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('List hosts'),
                    ),
                'GetNameServer' =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Read system nameserver'),
                    ),
                'GetConfig'=>   array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Get configuration'),
                    ),
                'SetMyName'     =>  array(
                    'argv'  =>  array(NAME),
                    'desc'  =>  _('Set system hostname'),
                    ),
                'SetRootEmail'  =>  array(
                    'argv'  =>  array(EMAIL),
                    'desc'  =>  _('Set e-mail address'),
                    ),
                'SystemMakeStaticGateway'       =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Make system gateway static'),
                    ),
                'SystemMakeDynamicGateway'      =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Make system gateway dynamic'),
                    ),
                'GetDynamicGateway' =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Get system gateway'),
                    ),
                'SetMyGate'     =>  array(
                    'argv'  =>  array(IPADR),
                    'desc'  =>  _('Set system gateway'),
                    ),
                'SetIf'     =>  array(
                    'argv'  =>  array(NAME, NAME, IPADR|NAME|EMPTYSTR, IPADR|NAME|EMPTYSTR, IPADR|NAME|EMPTYSTR, STR|EMPTYSTR, NAME|EMPTYSTR, NAME|EMPTYSTR, STR|EMPTYSTR, NAME|EMPTYSTR),
                    'desc'  =>  _('Configure an interface'),
                    ),
                'DeleteIf'  =>  array(
                    'argv'  =>  array(NAME),
                    'desc'  =>  _('Unconfigure an interface'),
                    ),
                'SetNameServer' =>  array(
                    'argv'  =>  array(IPADR),
                    'desc'  =>  _('Set system nameserver'),
                    ),
                'AddHost'       =>  array(
                    'argv'  =>  array(HOST),
                    'desc'  =>  _('Add host'),
                    ),
                'DelHost'       =>  array(
                    'argv'  =>  array(HOST),
                    'desc'  =>  _('Delete host'),
                    ),
                'SetDateTime'       =>  array(
                    'argv'  =>  array(DATETIME),
                    'desc'  =>  _('Set system clock'),
                    ),
                'UpdateMailAliases' =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Update mail aliases'),
                    ),
                'DisplayRemoteTime' =>  array(
                    'argv'  =>  array(URL|IPADR),
                    'desc'  =>  _('Display remote time'),
                    ),
                'SetRemoteTime' =>  array(
                    'argv'  =>  array(URL|IPADR),
                    'desc'  =>  _('Set remote time'),
                    ),
                'GetRemoteTime' =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Get remote time'),
                    ),
                'AutoConfig'    =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Automatic configuration'),
                    ),
                'InitGraphs'    =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Init graphs'),
                    ),
                'DeleteStats'   =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Erase statistics files'),
                    ),
                'Shutdown'  =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('System shutdown'),
                    ),
                'Restart'   =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('System restart'),
                    ),
                'NetStart'  =>  array(
                    'argv'  =>  array(NAME|NONE),
                    'desc'  =>  _('Restart network'),
                    ),
                'IfUpDown'  =>  array(
                    'argv'  =>  array(NAME, BOOL),
                    'desc'  =>  _('Interface up or down'),
                    ),
                'GetServiceStartStatus'=>   array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Get service start status'),
                    ),
                'DisableService'=>  array(
                    'argv'  =>  array(URL),
                    'desc'  =>  _('Turn off service'),
                    ),
                'EnableService'=>   array(
                    'argv'  =>  array(URL),
                    'desc'  =>  _('Turn on service'),
                    ),
                'GetPartitions' =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Get partition list'),
                    ),
                'GetSystemInfo' =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Get system information'),
                    ),
                'GetLogsConfig'=>   array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Get logs configuration'),
                    ),
                'SetLogsConfig'=>   array(
                    'argv'  =>  array(NAME, FILEPATH, NUM, NUM|ASTERISK, NUM|ASTERISK),
                    'desc'  =>  _('Set logs configuration'),
                    ),
                'RotateLogFile'=>   array(
                    'argv'  =>  array(FILEPATH),
                    'desc'  =>  _('Rotate log file'),
                    ),
                'RotateAllLogFiles'=>   array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Rotate all log files'),
                    ),
                'SetManCgiHome'=>   array(
                    'argv'  =>  array(IPADR),
                    'desc'  =>  _('Set man.cgi home'),
                    ),
                'IsNotifierEnabled'=>   array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Is notifier enabled'),
                    ),
                'EnableNotifier'=>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Enable notifier'),
                    ),
                'DisableNotifier'=> array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Disable notifier'),
                    ),
                'SetNotifyLevel'=>  array(
                    'argv'  =>  array(NAME),
                    'desc'  =>  _('Set notify level'),
                    ),
                'SetNotifierHost'   =>  array(
                    'argv'  =>  array(URL),
                    'desc'  =>  _('Set notifier host'),
                    ),
                'DisableNotifierSSLVerifyPeer'=>    array(
                    'argv'  =>  array(NAME),
                    'desc'  =>  _('Disable notifier SSL verify peer'),
                    ),
                'EnableNotifierSSLVerifyPeer'=> array(
                    'argv'  =>  array(NAME),
                    'desc'  =>  _('Enable notifier SSL verify peer'),
                    ),
                'SetNotifierAPIKey' =>  array(
                    // API key type is similar to URL
                    'argv'  =>  array(URL),
                    'desc'  =>  _('Set notifier API key'),
                    ),
                'AddNotifierUser'   =>  array(
                    'argv'  =>  array(JSON),
                    'desc'  =>  _('Add notifier user'),
                    ),
                'DelNotifierUser'   =>  array(
                    'argv'  =>  array(URL),
                    'desc'  =>  _('Delete notifier user'),
                    ),
                'AddFilter'     =>  array(
                    'argv'  =>  array(REGEXP),
                    'desc'  =>  _('Add filter'),
                    ),
                'DelFilter'     =>  array(
                    'argv'  =>  array(REGEXP),
                    'desc'  =>  _('Delete filter'),
                    ),
                'SetNotifierTimeout'=>  array(
                    'argv'  =>  array(NUM),
                    'desc'  =>  _('Set notifier timeout'),
                    ),
                'GenerateSSLKeyPair'=>  array(
                    'argv'  =>  array(NUM),
                    'desc'  =>  _('Generate SSL key pair'),
                    ),
                'EnableHostap'  =>  array(
                    'argv'  =>  array(NAME),
                    'desc'  =>  _('Enable hostap on an interface'),
                    ),
                'GetMFSConfig'  =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Get MFS config'),
                    ),
                'SetMFS'    =>  array(
                    'argv'  =>  array(NAME),
                    'desc'  =>  _('Set MFS'),
                    ),
                'SetMFSSize'    =>  array(
                    'argv'  =>  array(MFSSIZE),
                    'desc'  =>  _('Set MFS size'),
                    ),
                'SetSyncMFS'    =>  array(
                    'argv'  =>  array(NAME),
                    'desc'  =>  _('Set sync MFS'),
                    ),
                )
            );
    }
References ASTERISK, BOOL, DATETIME, EMAIL, EMPTYSTR, FILEPATH, HOST, IPADR, JSON, MFSSIZE, NAME, NONE, NUM, REGEXP, STR, and URL.
__construct() [2/2]
__construct ()
Reimplemented from Model.
Definition at line 115 of file include.php.
    {
        $this->Module= basename(dirname($_SERVER['PHP_SELF']));
        $this->Caption= _TITLE('System');
        $this->LogsHelpMsg= _HELPWINDOW('This page shows system-wide logs. Most services on PFFW write to their own log files, but a few processes may log messages to this system file. Pay special attention to error messages.');
    }
References _HELPWINDOW(), _TITLE(), and Caption.
Member Function Documentation
_delFilter()
_delFilter ($tokens, $token)
Attention
Fake slice to update the keys, otherwise json_encode() saves the numerical keys too, i.e. returns a json object not array.
Definition at line 1728 of file system.php.
    {
        $key= FALSE;
        try {
            $key= array_search($token, $tokens, TRUE);
        } catch (Exception $ignored) {}
        if ($key !== FALSE) {
            unset($tokens[$key]);
            $tokens= array_slice($tokens, 0);
        }
        return $tokens;
    }
Referenced by AddFilter(), and DelFilter().
_getDynamicGateway()
_getDynamicGateway ()
Definition at line 593 of file system.php.
    {
        global $Re_Ip;
        $cmd= "/sbin/route -n get default | /usr/bin/grep gateway 2>&1";
        exec($cmd, $output, $retval);
        if ($retval === 0) {
            if (count($output) > 0) {
                #    gateway: 10.0.0.2
                $re= "\s*gateway:\s*($Re_Ip)\s*";
                if (preg_match("/$re/m", $output[0], $match)) {
                    return $match[1];
                }
            }
        }
        else {
            $errout= implode("\n", $output);
            Error($errout);
            ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Get dynamic gateway failed: $errout");
        }
        return FALSE;
    }
References $Re_Ip, $retval, ctlr_syslog(), and Error().
Referenced by GetConfig(), GetDynamicGateway(), getSystemGateway(), and SystemMakeStaticGateway().
_getIfConfig()
_getIfConfig ($if)
Definition at line 468 of file system.php.
    {
        $file= $this->confDir."hostname.".$if;
        if (file_exists($file)) {
            if (($contents= $this->GetFile($file)) !== FALSE) {
                $contents= explode("\n", $contents);
                $inet= array('', '', '', '', '', '', '', '', '');
                $nwid= array('', '', '');
                $hostap= array('');
                $wifi= array('');
                $up= array('');
                foreach ($contents as $line) {
                    if (preg_match("/^(inet|dhcp|autoconf)\s*(\S*)\s*(\S*)\s*(\S*)\s*(\S*)$/", $line, $match)) {
                        $inet= $match;
                        // OpenBSD 6.6 onwards uses hex if mask in hostname.if file
                        // Convert if mask from hex to ip: 0xffffff00 -> 255.255.255.0
                        if ($inet[3] !== '') {
                            $inet[3]= long2ip(hexdec($inet[3]));
                        }
                        $output= $this->RunShellCommand("/sbin/ifconfig $if | /usr/bin/grep -E '(inet |lladdr )'");
                        // lladdr aa:bb:cc:dd:ee:ff
                        // inet 192.168.0.1 netmask 0xffffff00 broadcast 192.168.0.255
                        if (preg_match('/lladdr\s*(\S+)/m', $output, $match)) {
                            $inet[]= $match[1];
                        } else {
                            $inet[]= '';
                        }
                        if (preg_match('/inet\s*(\S+)/m', $output, $match)) {
                            $inet[]= $match[1];
                        } else {
                            $inet[]= '';
                        }
                        if (preg_match('/netmask\s*(\S+)/m', $output, $match)) {
                            $inet[]= long2ip(hexdec($match[1]));
                        } else {
                            $inet[]= '';
                        }
                        if (preg_match('/broadcast\s*(\S+)/m', $output, $match)) {
                            $inet[]= $match[1];
                        } else {
                            $inet[]= '';
                        }
                    }
                    // Search in hostname.$if contents
                    // inet 192.168.0.1 0xffffff00
                    // nwid mynwid wpakey mykey
                    // mediaopt hostap
                    else if (preg_match('/(nwid|join)\s+(\S+)\s*(\S*)\s*(\S*)/', $line, $match)) {
                        $nwid= array($match[2], $match[3], $match[4]);
                    }
                    else if (preg_match('/mediaopt (hostap)/', $line, $match)) {
                        $hostap= array($match[1]);
                    }
                }
                if ($this->isWifiIf($if)) {
                    $wifi= array('wifi');
                }
                if ($this->isIfUp($if)) {
                    $up= array('up');
                }
                return json_encode(array_merge(array_slice($inet, 1), $nwid, $hostap, $wifi, $up));
            }
        }
        return FALSE;
    }
References Model\GetFile(), isIfUp(), Model\isWifiIf(), and Model\RunShellCommand().
Referenced by GetConfig(), and GetIfConfig().
_getModuleInfo()
_getModuleInfo ($start)
Attention
Don't call $this->_getPartitions() instead, it needs an explode()
Reimplemented from Model.
Definition at line 660 of file system.php.
    {
        $info= array();
        $uptime= $this->RunShellCommand('/usr/bin/uptime');
        if (preg_match('/up (.*), (\d+) user.*/', $uptime, $match)) {
            $info['uptime']= $match[1];
            $info['users']= $match[2];
        } else {
            $info['uptime']= '';
            $info['users']= '';
        }
        exec('/bin/df -h', $parts);
        $partitions= array();
        foreach ($parts as $p) {
            if (preg_match('/^(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)$/', $p, $match)) {
                $partitions[$match[6]]= $match[5];
            }
        }
        $info['partitions']= $partitions;
        return $info;
    }
References Model\RunShellCommand().
_getMyName()
_getMyName ()
Definition at line 432 of file system.php.
    {
        return $this->GetFile($this->confDir.'myname');
    }
References Model\GetFile().
Referenced by GetConfig(), and GetMyName().
_getPartitions()
_getPartitions ()
Returns all partitions mounted.
Reimplemented from Model.
Definition at line 1221 of file system.php.
    {
        return $this->RunShellCommand('/bin/df -h | /usr/bin/egrep "^\/dev"');
    }
References Model\RunShellCommand().
Referenced by GetPartitions().
_getStaticGateway()
_getStaticGateway ()
Definition at line 588 of file system.php.
    {
        return $this->GetFile($this->confDir.'mygate');
    }
References Model\GetFile().
Referenced by GetConfig(), GetStaticGateway(), and getSystemGateway().
AddFilter()
AddFilter ($filter)
Definition at line 1700 of file system.php.
    {
        global $ROOT, $TEST_DIR_SRC, $NotifierFilters;
        $filters= json_decode($NotifierFilters, TRUE);
        if ($filters === NULL) {
            ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Cannot json_decode NotifierFilters, starting with an empty list: $NotifierFilters");
            $filters= array();
        }
        $filters= $this->_delFilter($filters, $filter);
        $filters[]= $filter;
        return $this->SetNVP($ROOT . $TEST_DIR_SRC . '/lib/setup.php', '\$NotifierFilters', "'".json_encode($filters)."';");
    }
References $NotifierFilters, $ROOT, $TEST_DIR_SRC, _delFilter(), ctlr_syslog(), and Model\SetNVP().
AddHost()
AddHost ($host)
Adds host line to hosts file.
Parameters
string $host Host definition line.
Returns
bool TRUE on success, FALSE on fail.
Definition at line 393 of file system.php.
    {
        $this->DelHost($host);
        return $this->AppendToFile($this->confDir.'hosts', $host);
    }
References Model\AppendToFile(), and DelHost().
AddNotifierUser()
AddNotifierUser ($userJson)
Definition at line 1668 of file system.php.
    {
        global $ROOT, $TEST_DIR_SRC, $NotifierUsers;
        $users= json_decode($NotifierUsers, TRUE);
        if ($users === NULL) {
            ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Cannot json_decode NotifierUsers, starting with an empty list: $NotifierUsers");
            $users= array();
        }
        $user= json_decode($userJson, TRUE);
        $token= key($user);
        $users[$token]= $user[$token];
        return $this->SetNVP($ROOT . $TEST_DIR_SRC . '/lib/setup.php', '\$NotifierUsers', "'".json_encode($users)."';");
    }
References $NotifierUsers, $ROOT, $TEST_DIR_SRC, ctlr_syslog(), and Model\SetNVP().
AutoConfig()
AutoConfig ()
Runs installer with the automatic configuration option.
Returns
bool TRUE on success, FALSE on fail.
Definition at line 868 of file system.php.
    {
        global $SRC_ROOT;
        exec("$SRC_ROOT/Installer/install.php -a 2>&1", $output, $retval);
        if ($retval === 0) {
            return TRUE;
        }
        $errout= implode("\n", $output);
        Error($errout);
        ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Auto configuration failed: $errout");
        return FALSE;
    }
References $retval, $SRC_ROOT, ctlr_syslog(), and Error().
DaemonizedRotateAllLogFiles()
DaemonizedRotateAllLogFiles ()
Rotate all log files via newsyslog.
Daemonized, because newsyslog kills httpd, hence parent, stopping rotation in the middle, e.g. before compressing files.
Definition at line 1510 of file system.php.
    {
        global $TmpFile;
        $cmd= "/usr/bin/newsyslog -vF -f $this->newSyslogConf > $TmpFile 2>&1 &";
        exec($cmd, $output, $retval);
        if ($retval === 0) {
            return TRUE;
        }
        $errout= implode("\n", $output);
        Error($errout);
        ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Log rotation failed: $errout");
        return FALSE;
    }
References $retval, $TmpFile, ctlr_syslog(), and Error().
DaemonizedRotateLogFile()
DaemonizedRotateLogFile ($file)
Rotate log file via newsyslog.
Daemonized, because newsyslog may kill httpd, hence parent.
Attention
Do not use & at the end to send the command to background Otherwise, gzip fails to compress the rotated file sometimes This daemonized child process should not exit before newsyslog exits
Definition at line 1465 of file system.php.
    {
        global $TmpFile;
        if (($contents= $this->GetFile($this->newSyslogConf)) !== FALSE) {
            $re_filepath= Escape($file, '/');
            $re_owner= '([\w:]+|)';
            $re_mode= '(\d+)';
            $re_count= '(\d+)';
            $re_size= '(\d+|\*)';
            $re_when= '(\d+|\*)';
            $re= "/^(\s*$re_filepath\s+$re_owner\s*$re_mode\s+$re_count\s+$re_size\s+$re_when\s+.*)$/m";
            if (preg_match($re, $contents, $match)) {
                $line= $match[1];
                $cmd= "/bin/echo '$line' | /usr/bin/newsyslog -vF -f -  > $TmpFile 2>&1";
                exec($cmd, $output, $retval);
                if ($retval === 0) {
                    return TRUE;
                }
                $errout= implode("\n", $output);
                Error($errout);
                ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Log rotation failed: $errout");
            }
        }
        return FALSE;
    }
References $retval, $TmpFile, ctlr_syslog(), Error(), Escape(), and Model\GetFile().
DaemonizeFunc()
DaemonizeFunc ($func, $param = '')
Daemonizes to run the given function.
Attention
Parent should exit, not return TRUE Otherwise the Controller returns twice confusing the View
Definition at line 1528 of file system.php.
    {
        $pid= pcntl_fork();
        if ($pid == -1) {
            ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, 'Cannot fork');
        }
        else if ($pid) {
            exit;
        }
        else {
            // Make the child process a session leader
            $sid= posix_setsid();
            if ($sid < 0) {
                ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, 'Cannot make the child a session leader');
                // Exit if cannot daemonize completely
                return FALSE;
            }
            // The child is daemonized now, hence survives even if its process group is killed.
            // This is necessary when rotating httpd logs.
            $argv= array();
            if ($param !== '') {
                $argv= array($param);
            }
            return call_user_func_array(array($this, $func), $argv);
        }
    }
References ctlr_syslog(), and exit.
Referenced by RotateAllLogFiles(), and RotateLogFile().
DeleteIf()
DeleteIf ($if)
Deconfigures an interface by deleting its hostname file.
Parameters
string $if Interface name.
Returns
bool TRUE on success, FALSE on fail.
Definition at line 801 of file system.php.
    {
        exec("/sbin/ifconfig $if down");
        exec("/sbin/ifconfig $if delete");
        return $this->DeleteFile($this->confDir.'hostname.'.$if);
    }
References Model\DeleteFile().
DeleteStats()
DeleteStats ()
Deletes temporary logs, statistics, and output files created by the WUI.
Returns
bool TRUE on success, FALSE on fail.
Definition at line 935 of file system.php.
    {
        // Do not remove the base folders, but the folders and/or files under them
        exec("/bin/rm -rf {$this->PFFWDIR}/logs/* {$this->PFFWDIR}/stats/* {$this->PFFWDIR}/out/* 2>&1", $output, $retval);
        if ($retval === 0) {
            return TRUE;
        }
        $errout= implode("\n", $output);
        Error($errout);
        ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Failed erasing statistics files: $errout");
        return FALSE;
    }
References $retval, ctlr_syslog(), and Error().
DelFilter()
DelFilter ($filter)
Definition at line 1715 of file system.php.
    {
        global $ROOT, $TEST_DIR_SRC, $NotifierFilters;
        $filters= json_decode($NotifierFilters, TRUE);
        if ($filters !== NULL) {
            $filters= $this->_delFilter($filters, $filter);
            return $this->SetNVP($ROOT . $TEST_DIR_SRC . '/lib/setup.php', '\$NotifierFilters', "'".json_encode($filters)."';");
        }
        ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Cannot json_decode NotifierFilters: $NotifierFilters");
        return FALSE;
    }
References $NotifierFilters, $ROOT, $TEST_DIR_SRC, _delFilter(), ctlr_syslog(), and Model\SetNVP().
DelHost()
DelHost ($host)
Deletes host line from hosts file.
Parameters
string $host Host definition line.
Returns
bool TRUE on success, FALSE on fail.
Definition at line 405 of file system.php.
    {
        return $this->ReplaceRegexp($this->confDir.'hosts', "/^(\h*$host(\s|))/m", '');
    }
References Model\ReplaceRegexp().
Referenced by AddHost().
DelNotifierUser()
DelNotifierUser ($token)
Definition at line 1684 of file system.php.
    {
        global $ROOT, $TEST_DIR_SRC, $NotifierUsers;
        $users= json_decode($NotifierUsers, TRUE);
        if ($users === NULL) {
            ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Cannot json_decode NotifierUsers, starting with an empty list: $NotifierUsers");
            $users= array();
        }
        if (array_key_exists($token, $users)) {
            unset($users[$token]);
        }
        return $this->SetNVP($ROOT . $TEST_DIR_SRC . '/lib/setup.php', '\$NotifierUsers', "'".json_encode($users)."';");
    }
References $NotifierUsers, $ROOT, $TEST_DIR_SRC, ctlr_syslog(), and Model\SetNVP().
DisableNotifier()
DisableNotifier ()
Todo:
Should we delete the tmp file too?
Definition at line 1564 of file system.php.
    {
        $tmp= $this->cronDir.'root';
        // Do not use PutFile(), it expects file to exist
        file_put_contents($tmp, $this->getRootCronTab(), LOCK_EX);
        $retval= $this->ReplaceRegexp($tmp, '?^(\h*\*/1\h+\*\h+\*\h+\*\h+\*\h+/usr/bin/env\h+PATH=\$PATH:/usr/local/bin\h+/usr/local/bin/php\h+/var/www/htdocs/pffw/Notifier/notify.php\h+.*)$?m', '#${1}');
        if (file_exists($tmp.'.bak')) {
            unlink($tmp.'.bak');
        }
        if ($retval) {
            exec("/usr/bin/crontab -u root $tmp");
            return !$this->IsNotifierEnabled();
        }
        ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Failed disabling notifier");
        return FALSE;
    }
References $retval, ctlr_syslog(), getRootCronTab(), IsNotifierEnabled(), and Model\ReplaceRegexp().
DisableNotifierSSLVerifyPeer()
DisableNotifierSSLVerifyPeer ($bool)
Definition at line 1643 of file system.php.
    {
        global $ROOT, $TEST_DIR_SRC;
        // Append semi-colon to new value, this setting is a PHP line
        return $this->SetNVP($ROOT . $TEST_DIR_SRC . '/lib/setup.php', '\$NotifierSSLVerifyPeer', $bool.';');
    }
References $ROOT, $TEST_DIR_SRC, and Model\SetNVP().
DisableService()
DisableService ($service)
Turn off (disable) service startup.
Parameters
string $service Service name.
Returns
bool TRUE on success, FALSE on fail.
Definition at line 1299 of file system.php.
    {
        if (in_array($service, $this->rcConfLocalServices)) {
            return $this->DisableServiceRcConfLocal($service);
        }
        else if (in_array($service, $this->rcLocalServices)) {
            return $this->DisableServiceRcLocal($service);
        }
        else {
            return FALSE;
        }
    }
References DisableServiceRcConfLocal(), and DisableServiceRcLocal().
DisableServiceRcConfLocal()
DisableServiceRcConfLocal ($service)
Turn off (disable) service startup in rc.conf.local.
Parameters
string $service Service name in rc.conf.local.
Returns
bool TRUE on success, FALSE on fail.
Definition at line 1337 of file system.php.
    {
        return $this->ReplaceRegexp($this->rcConfLocal, "/^(\h*$service\h*=.*)$/m", '#${1}');
    }
References Model\ReplaceRegexp().
Referenced by DisableService().
DisableServiceRcLocal()
DisableServiceRcLocal ($service)
Turn off (disable) service startup in rc.local.
Parameters
string $service Service name in rc.local.
Returns
bool TRUE on success, FALSE on fail.
Attention
snort and pmacct have multiple lines in rc.local, hence the while loop
$count should come first in the if condition to be decremented on each iteration of the loop
Definition at line 1348 of file system.php.
    {
        $service= Escape($service, '/');
        // Prevent infinite loop in case ReplaceRegexp() always returns TRUE
        // We don't expect more than 10 lines
        $count= 10;
        $retval= FALSE;
        while ($count-- && $this->ReplaceRegexp($this->confDir.'rc.local', "/^(\h*$service\b.*)$/m", '#${1}')) {
            $retval= TRUE;
        }
        return $retval;
    }
References $retval, Escape(), and Model\ReplaceRegexp().
Referenced by DisableService().
DisplayDashboardExtras()
static DisplayDashboardExtras () static
Definition at line 127 of file include.php.
    {
        global $ServiceInfo;
        ?>
        <tr>
            <td colspan="4">
                <a class="transparent" href="/system/graphs.php?submenu=cpus"><img src="/system/dashboard/cpu.png" name="cpu" alt="cpu" title="<?php echo _TITLE2('CPU load of the system') ?>"></a><br>
                <a class="transparent" href="/system/graphs.php?submenu=memory"><img src="/system/dashboard/memory.png" name="memory" alt="memory" title="<?php echo _TITLE2('Memory usage') ?>"></a><br>
                <a class="transparent" href="/system/graphs.php?submenu=disks"><img src="/system/dashboard/diskio.png" name="diskio" alt="diskio" title="<?php echo _TITLE2('Disk input and output') ?>"></a>
            </td>
        </tr>
        <tr id="dashboard">
            <td class="part" colspan="4" title="<?php echo _TITLE2('Disk partition usage') ?>">
                <a class="transparent" href="/system/graphs.php?submenu=partitions">
                <table class="part">
                    <tr>
                        <td>
                            <table class="part" style="width: 275px;">
                                <tr>
                                    <td class="partleft" style="background-color: brown; width: <?php echo $ServiceInfo['system']['partitions']['/'] != '0%' ? $ServiceInfo['system']['partitions']['/'] : '0.1%'; ?>"></td>
                                    <td class="partright" style="background-color: whitesmoke"><?php echo $ServiceInfo['system']['partitions']['/']; ?></td>
                                </tr>
                            </table>
                        </td>
                        <td class="part" style="width: 100px;">/</td>
                    </tr>
                </table>
                </a>
            </td>
        </tr>
        <tr id="dashboard">
            <td class="part" colspan="4" title="<?php echo _TITLE2('Disk partition usage') ?>">
                <a class="transparent" href="/system/graphs.php?submenu=partitions">
                <table class="part">
                    <tr>
                        <td>
                            <table class="part" style="width: 275px;">
                                <tr>
                                    <td class="partleft" style="background-color: green; width: <?php echo $ServiceInfo['system']['partitions']['/tmp'] != '0%' ? $ServiceInfo['system']['partitions']['/tmp'] : '0.1%'; ?>"></td>
                                    <td class="partright" style="background-color: whitesmoke"><?php echo $ServiceInfo['system']['partitions']['/tmp']; ?></td>
                                </tr>
                            </table>
                        </td>
                        <td class="part" style="width: 100px;">/tmp</td>
                    </tr>
                </table>
                </a>
            </td>
        </tr>
        <tr id="dashboard">
            <td class="part" colspan="4" title="<?php echo _TITLE2('Disk partition usage') ?>">
                <a class="transparent" href="/system/graphs.php?submenu=partitions">
                <table class="part">
                    <tr>
                        <td>
                            <table class="part" style="width: 275px;">
                                <tr>
                                    <td class="partleft" style="background-color: blue; width: <?php echo $ServiceInfo['system']['partitions']['/usr'] != '0%' ? $ServiceInfo['system']['partitions']['/usr'] : '0.1%'; ?>"></td>
                                    <td class="partright" style="background-color: whitesmoke"><?php echo $ServiceInfo['system']['partitions']['/usr']; ?></td>
                                </tr>
                            </table>
                        </td>
                        <td class="part" style="width: 100px;">/usr</td>
                    </tr>
                </table>
                </a>
            </td>
        </tr>
        <tr id="dashboard">
            <td class="part" colspan="4" title="<?php echo _TITLE2('Disk partition usage') ?>">
                <a class="transparent" href="/system/graphs.php?submenu=partitions">
                <table class="part">
                    <tr>
                        <td>
                            <table class="part" style="width: 275px;">
                                <tr>
                                    <td class="partleft" style="background-color: orange; width: <?php echo $ServiceInfo['system']['partitions']['/var'] != '0%' ? $ServiceInfo['system']['partitions']['/var'] : '0.1%'; ?>"></td>
                                    <td class="partright" style="background-color: whitesmoke"><?php echo $ServiceInfo['system']['partitions']['/var']; ?></td>
                                </tr>
                            </table>
                        </td>
                        <td class="part" style="width: 100px;">/var</td>
                    </tr>
                </table>
                </a>
            </td>
        </tr>
        <?php
        if (isset($ServiceInfo['system']['partitions']['/var/log'])) {
            ?>
            <tr id="dashboard">
                <td class="part" colspan="4" title="<?php echo _TITLE2('Disk partition usage') ?>">
                    <a class="transparent" href="/system/graphs.php?submenu=partitions">
                        <table class="part">
                        <tr>
                            <td>
                                <table class="part" style="width: 275px;">
                                    <tr>
                                        <td class="partleft" style="background-color: red; width: <?php echo $ServiceInfo['system']['partitions']['/var/log'] != '0%' ? $ServiceInfo['system']['partitions']['/var/log'] : '0.1%'; ?>"></td>
                                        <td class="partright" style="background-color: whitesmoke"><?php echo $ServiceInfo['system']['partitions']['/var/log']; ?></td>
                                    </tr>
                                </table>
                            </td>
                            <td class="part" style="width: 100px;">/var/log</td>
                        </tr>
                    </table>
                    </a>
                </td>
            </tr>
            <?php
        }
    }
DisplayRemoteTime()
DisplayRemoteTime ($timeserver)
Displays datetime from the given time server.
Writes its output to a temporary file.
Definition at line 975 of file system.php.
    {
        global $TmpFile;
        // First make sure there are no running rdate processes.
        $this->Pkill('rdate', '-KILL');
        $this->RunShellCommand("/usr/sbin/rdate -p $timeserver > $TmpFile 2>&1 &");
        return TRUE;
    }
References $TmpFile, Model\Pkill(), and Model\RunShellCommand().
EnableHostap()
EnableHostap ($if)
Enables hostap on the given interface.
Returns
bool TRUE on success, FALSE on fail.
Definition at line 1776 of file system.php.
    {
        $file= $this->confDir."hostname.".$if;
        if (($contents= $this->GetFile($file)) !== FALSE) {
            if (!preg_match("/mediaopt hostap/m", $contents, $match)) {
                exec("/bin/echo 'mediaopt hostap' >>$file 2>&1", $output, $retval);
                return TRUE;
            }
        }
        return FALSE;
    }
References $retval, and Model\GetFile().
EnableNotifier()
EnableNotifier ()
Definition at line 1584 of file system.php.
    {
        $tmp= $this->cronDir.'root';
        // Do not use PutFile(), it expects file to exist
        file_put_contents($tmp, $this->getRootCronTab(), LOCK_EX);
        $retval= $this->ReplaceRegexp($tmp, '?^\h*#(\h*\*/1\h+\*\h+\*\h+\*\h+\*\h+/usr/bin/env\h+PATH=\$PATH:/usr/local/bin\h+/usr/local/bin/php\h+/var/www/htdocs/pffw/Notifier/notify.php\h+.*$)?m', '${1}');
        if (file_exists($tmp.'.bak')) {
            unlink($tmp.'.bak');
        }
        if ($retval) {
            exec("/usr/bin/crontab -u root $tmp");
            return $this->IsNotifierEnabled();
        }
        ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Failed enabling notifier");
        return FALSE;
    }
References $retval, ctlr_syslog(), getRootCronTab(), IsNotifierEnabled(), and Model\ReplaceRegexp().
EnableNotifierSSLVerifyPeer()
EnableNotifierSSLVerifyPeer ($bool)
Definition at line 1651 of file system.php.
    {
        global $ROOT, $TEST_DIR_SRC;
        // Append semi-colon to new value, this setting is a PHP line
        return $this->SetNVP($ROOT . $TEST_DIR_SRC . '/lib/setup.php', '\$NotifierSSLVerifyPeer', $bool.';');
    }
References $ROOT, $TEST_DIR_SRC, and Model\SetNVP().
EnableService()
EnableService ($service)
Turn on (enable) service startup.
Parameters
string $service Service name.
Returns
bool TRUE on success, FALSE on fail.
Definition at line 1318 of file system.php.
    {
        if (in_array($service, $this->rcConfLocalServices)) {
            return $this->EnableServiceRcConfLocal($service);
        }
        else if (in_array($service, $this->rcLocalServices)) {
            return $this->EnableServiceRcLocal($service);
        }
        else {
            return FALSE;
        }
    }
References EnableServiceRcConfLocal(), and EnableServiceRcLocal().
EnableServiceRcConfLocal()
EnableServiceRcConfLocal ($service)
Turn on (enable) service startup in rc.conf.local.
Parameters
string $service Service name in rc.conf.local.
Returns
bool TRUE on success, FALSE on fail.
Definition at line 1372 of file system.php.
    {
        return $this->ReplaceRegexp($this->rcConfLocal, "/^\h*#(\h*$service\h*=.*)$/m", '${1}');
    }
References Model\ReplaceRegexp().
Referenced by EnableService().
EnableServiceRcLocal()
EnableServiceRcLocal ($service)
Turn on (enable) service startup in rc.local.
See the attention notes in DisableServiceRcLocal()
Parameters
string $service Service name in rc.local.
Returns
bool TRUE on success, FALSE on fail.
Definition at line 1385 of file system.php.
    {
        $service= Escape($service, '/');
        $count= 10;
        $retval= FALSE;
        while ($count-- && $this->ReplaceRegexp($this->confDir.'rc.local', "/^\h*#(\h*$service\b.*)$/m", '${1}')) {
            $retval= TRUE;
        }
        return $retval;
    }
References $retval, Escape(), and Model\ReplaceRegexp().
Referenced by EnableService().
FormatLogCols()
FormatLogCols (& $cols)
Post-processes log columns for display.
Parameters
array $cols Parsed log line in columns
Reimplemented from View.
Definition at line 122 of file include.php.
    {
        $cols['Log']= wordwrap($cols['Log'], 150, '<br />', TRUE);
    }
GenerateSSLKeyPair()
GenerateSSLKeyPair ($set_serial)
Generates SSL key pair for httpd.
Returns
bool TRUE on success, FALSE on fail.
Definition at line 1756 of file system.php.
    {
        global $MODEL_PATH;
        exec("cd $MODEL_PATH/ssl; SET_SERIAL=$set_serial /bin/sh gen_ssl.sh 2>&1", $output, $retval);
        if ($retval === 0) {
            return TRUE;
        }
        $errout= implode("\n", $output);
        Error($errout);
        ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Generate SSL key pair failed: $errout");
        return FALSE;
    }
References $MODEL_PATH, $retval, ctlr_syslog(), and Error().
GetConfig()
GetConfig ()
Reads hostname, gateway, and interface configuration.
Returns
array Configuration.
Definition at line 621 of file system.php.
    {
        $config= array();
        if (($myname= $this->_getMyName()) !== FALSE) {
            $config['Myname']= trim($myname);
        }
        $config['Mygate']= 'Unknown';
        $config['StaticGateway']= FALSE;
        if (($mygate= $this->_getStaticGateway()) !== FALSE) {
            $config['Mygate']= trim($mygate);
            $config['StaticGateway']= TRUE;
        }
        else if (($mygate= $this->_getDynamicGateway()) !== FALSE) {
            $config['Mygate']= trim($mygate);
        }
        if (($intif= $this->_getIntIf()) !== FALSE) {
            $config['IntIf']= trim($intif, '"');
        }
        if (($extif= $this->_getExtIf()) !== FALSE) {
            $config['ExtIf']= trim($extif, '"');
        }
        if (($ifs= $this->_getPhyIfs()) !== FALSE) {
            $ifs= explode("\n", $ifs);
            foreach ($ifs as $if) {
                $config['Ifs'][$if]= array();
                if (($output= $this->_getIfConfig($if)) !== FALSE) {
                    $config['Ifs'][$if]= json_decode($output, TRUE);
                }
            }
        }
        return Output(json_encode($config));
    }
References $ifs, _getDynamicGateway(), Model\_getExtIf(), _getIfConfig(), Model\_getIntIf(), _getMyName(), Model\_getPhyIfs(), _getStaticGateway(), and Output().
GetDynamicGateway()
GetDynamicGateway ()
Reads the default gateway on the routing table.
Returns
string IP address of the gateway.
Definition at line 563 of file system.php.
    {
        return Output($this->_getDynamicGateway());
    }
References _getDynamicGateway(), and Output().
GetHosts()
GetHosts ()
Reads hosts file contents.
Returns
string Uncommented lines of hosts file.
Definition at line 415 of file system.php.
    {
        global $Re_Ip;
        return Output($this->SearchFileAll($this->confDir.'hosts', "/^\h*(($Re_Ip|[:\d]+)\b.*)\h*$/m"));
    }
References $Re_Ip, Output(), and Model\SearchFileAll().
GetIfConfig()
GetIfConfig ($if)
Reads interface configuration.
Parameters
string $if Interface to get configuration of.
Returns
string Root e-mail address.
Definition at line 463 of file system.php.
    {
        return Output($this->_getIfConfig($if));
    }
References _getIfConfig(), and Output().
GetLogsConfig()
GetLogsConfig ()
Get logs configuration.
Definition at line 1402 of file system.php.
    {
        global $MODEL_PATH, $ModelFiles, $Models, $ModelsToLogConfig;
        $output= array();
        foreach ($ModelsToLogConfig as $m) {
            if (array_key_exists($m, $ModelFiles)) {
                require_once($MODEL_PATH.'/'.$ModelFiles[$m]);
                if (class_exists($Models[$m])) {
                    $model= new $Models[$m]();
                    if (($config= $model->GetNewsyslogConfig($m)) !== FALSE) {
                        $output= array_merge($output, $config);
                    }
                }
                else {
                    ctlr_syslog(LOG_NOTICE, __FILE__, __FUNCTION__, __LINE__, "Not in Models: $m");
                }
            }
            else {
                ctlr_syslog(LOG_NOTICE, __FILE__, __FUNCTION__, __LINE__, "Not in ModelFiles: $m");
            }
        }
        return Output(json_encode($output));
    }
References $MODEL_PATH, $ModelFiles, $Models, $ModelsToLogConfig, ctlr_syslog(), and Output().
GetMFSConfig()
GetMFSConfig ()
Definition at line 1788 of file system.php.
    {
        $retval= TRUE;
        $MFSConfig= array(
            'enable' => 'Unknown',
            'size' => 'Unknown',
            'sync' => 'Unknown',
            );
        $file= $this->confDir.'rc';
        if (($contents= $this->GetFile($file)) !== FALSE) {
            if (preg_match("/^USE_MFS=(yes|no)$/m", $contents, $match)) {
                $MFSConfig['enable']= $match[1];
            } else {
                ERROR(_('Cannot get mount MFS'));
                ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, 'Cannot get USE_MFS');
                $retval= FALSE;
            }
            if (preg_match("/^MFS_SIZE=(\d+[kKmMgG]*)$/m", $contents, $match)) {
                $MFSConfig['size']= $match[1];
            } else {
                ERROR(_('Cannot get MFS size'));
                ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, 'Cannot get MFS_SIZE');
                $retval= FALSE;
            }
        } else {
            ERROR(_('Cannot get contents of /etc/rc'));
            ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Cannot get contents of file: $file");
            $retval= FALSE;
        }
        $file= $this->confDir.'sync.var';
        if (($contents= $this->GetFile($file)) !== FALSE) {
            if (preg_match("/^SYNC_MFS=(yes|no)$/m", $contents, $match)) {
                $MFSConfig['sync']= $match[1];
            } else {
                ERROR(_('Cannot get persistent MFS'));
                ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, 'Cannot get SYNC_MFS');
                $retval= FALSE;
            }
        } else {
            ERROR(_('Cannot get contents of /etc/sync.var'));
            ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Cannot get contents of file: $file");
            $retval= FALSE;
        }
        return $retval ? Output(json_encode($MFSConfig)) : FALSE;
    }
References $MFSConfig, $retval, ctlr_syslog(), Model\GetFile(), and Output().
GetMyName()
GetMyName ()
Reads hostname.
Returns
string System name, output of hostname too.
Definition at line 427 of file system.php.
    {
        return Output($this->_getMyName());
    }
References _getMyName(), and Output().
GetNameServer()
GetNameServer ()
Reads nameserver setting.
Returns
string System-wide nameserver.
Definition at line 442 of file system.php.
    {
        return Output($this->SearchFile($this->confDir.'resolv.conf', "/^\h*nameserver\h*([^#]*)\h*/m"));
    }
References Output(), and Model\SearchFile().
GetPartitions()
GetPartitions ()
Gets partition list.
Definition at line 1216 of file system.php.
    {
        return Output($this->_getPartitions());
    }
References _getPartitions(), and Output().
GetRemoteTime()
GetRemoteTime ()
Reads datetime temporary output file.
DisplayRemoteTime() and SetRemoteTime() functions write their output to a tmp file. We wait for their output in a loop.
Attention
PHP sleep() function is affected by changes to the system clock, so we cannot use it in the while loop. Note that we change the system time by calling SetRemoteTime(). But, the shell sleep command seems not affected by changes, to the clock, so we use it instead.
Returns
string Datetime.
Definition at line 1014 of file system.php.
    {
        global $TmpFile;
        $count= 0;
        while ($count++ < self::PROC_STAT_TIMEOUT) {
            // Wait until rdate exits
            if (!$this->IsRunning('rdate')) {
                break;
            }
            // Shell sleep command seems not affected by changes to clock
            exec('/bin/sleep ' . self::PROC_STAT_SLEEP_TIME);
        }
        if ($count < self::PROC_STAT_TIMEOUT) {
            if (($output= $this->GetFile($TmpFile)) !== FALSE) {
                $retval= $output;
            }
        }
        else {
            $retval= _('The process is taking too long, thus will run in the background.');
        }
        return Output($retval);
    }
References $retval, $TmpFile, Model\GetFile(), Model\IsRunning(), and Output().
getRootCronTab()
getRootCronTab ()
Attention
Remove the comments cron adds at the beginning of table, otherwise they are multiplied
Definition at line 1603 of file system.php.
    {
        //# DO NOT EDIT THIS FILE - edit the master and reinstall.
        //# (/var/cron/root installed on Thu Aug  9 18:03:44 2018)
        //# (Cron version V5.0)
        $contents= explode("\n", $this->GetFile($this->rootCronTab));
        // Match cron comments, otherwise there are other lines at the beginning
        // Remove in reverse order
        if (preg_match('/^#\h*\‍(Cron\h*version\h*.*$/', $contents[2])) {
            unset($contents[2]);
        }
        if (preg_match('|^#\h*\‍(/var/cron/root\h*installed\h*on\h*.*$|', $contents[1])) {
            unset($contents[1]);
        }
        if (preg_match('/^#\h*DO\h*NOT\h*EDIT\h*THIS\h*FILE\h*.*$/', $contents[0])) {
            unset($contents[0]);
        }
        return implode("\n", $contents);
    }
References Model\GetFile().
Referenced by DisableNotifier(), and EnableNotifier().
GetRootEmail()
GetRootEmail ()
Reads root e-mail address.
Returns
string Root e-mail address.
Definition at line 452 of file system.php.
    {
        return Output($this->SearchFile($this->confDir.'mail/aliases', "/^\h*root:\h*([^#]*)\h*$/m"));
    }
References Output(), and Model\SearchFile().
GetServiceStartStatus()
GetServiceStartStatus ()
Gets service start stati.
Definition at line 1244 of file system.php.
    {
        $output= array();
        foreach ($this->rcConfLocalServices as $service) {
            $stat= $this->GetServiceStatRcConfLocal($this->rcConfLocal, $service);
            if ($stat === '') {
                $output[$service]= TRUE;
            }
            else if ($stat === '#') {
                $output[$service]= FALSE;
            }
        }
        foreach ($this->rcLocalServices as $service) {
            $stat= $this->GetServiceStatRcLocal($this->confDir.'rc.local', $service);
            if ($stat === '') {
                $output[$service]= TRUE;
            }
            else if ($stat === '#') {
                $output[$service]= FALSE;
            }
        }
        return Output(json_encode($output));
    }
References GetServiceStatRcConfLocal(), GetServiceStatRcLocal(), and Output().
GetServiceStatRcConfLocal()
GetServiceStatRcConfLocal ($file, $service)
Gets service startup status in rc.conf.local.
Parameters
string $file Config file.
string $service Service name in rc.conf.local.
Returns
string Empty if on, # if off.
Definition at line 1275 of file system.php.
    {
        return $this->SearchFile($file, "/^\h*(#|)\h*$service\h*=.*$/m");
    }
References Model\SearchFile().
Referenced by GetServiceStartStatus().
GetServiceStatRcLocal()
GetServiceStatRcLocal ($file, $service)
Gets service startup status in rc.local.
Parameters
string $file Config file.
string $service Service name in rc.local.
Returns
string Empty if on, # if off.
Definition at line 1287 of file system.php.
    {
        $service= Escape($service, '/');
        return $this->SearchFile($file, "/^\h*(#|)\h*$service\b.*$/m");
    }
References Escape(), and Model\SearchFile().
Referenced by GetServiceStartStatus().
GetStaticGateway()
GetStaticGateway ()
Reads static gateway address from mygate file.
Returns
string IP address of the gateway.
Definition at line 553 of file system.php.
    {
        return Output($this->_getStaticGateway());
    }
References _getStaticGateway(), and Output().
getSystemGateway()
getSystemGateway ()
Gets system gateway, static or dynamic.
Returns
string Gateway.
Definition at line 573 of file system.php.
    {
        $gateway= '';
        if (($mygate= $this->_getStaticGateway()) !== FALSE) {
            $gateway= trim($mygate);
        } else if (($mygate= $this->_getDynamicGateway()) !== FALSE) {
            $gateway= trim($mygate);
        }
        if ($gateway === '') {
            Error(_('System has no gateway'));
        }
        return $gateway;
    }
References _getDynamicGateway(), _getStaticGateway(), and Error().
Referenced by NetStart().
GetSystemInfo()
GetSystemInfo ()
Gets system information.
Definition at line 1229 of file system.php.
    {
        return Output($this->RunShellCommand('/usr/bin/uptime') . "\n" .
            $this->RunShellCommand('/bin/date') . "\n" .
            $this->RunShellCommand('/sbin/sysctl -n kern.securelevel') . "\n" .
            $this->RunShellCommand('/sbin/sysctl -n net.inet.ip.forwarding') . "\n" .
            $this->RunShellCommand('/sbin/sysctl -n net.inet6.ip6.forwarding || echo "n/a"') . "\n" .
            $this->RunShellCommand('/sbin/sysctl -n kern.hostname') . "\n" .
            $this->RunShellCommand('/usr/bin/uname -msr') . "\n" .
            $this->RunShellCommand('/usr/bin/uname -p'));
    }
References Output(), and Model\RunShellCommand().
IfUpDown()
IfUpDown ($if, $updown)
Definition at line 1153 of file system.php.
    {
        $updown= $updown ? 'up' : 'down';
        exec("/sbin/ifconfig $if $updown 2>&1", $output, $retval);
        $errout= implode("\n", $output);
        Error($errout);
        if ($retval === 0) {
            return TRUE;
        }
        ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "IfUpDown failed: $errout");
        return FALSE;
    }
References $retval, ctlr_syslog(), and Error().
InitGraphs()
InitGraphs ()
Deletes all graph files and recreates them as necessary.
Returns
bool TRUE on success, FALSE on fail.
Definition at line 887 of file system.php.
    {
        global $VIEW_PATH;
        $result= TRUE;
        // symon
        exec("/bin/rm -f {$this->PFFWDIR}/symon/cache/* 2>&1", $output, $retval);
        // Failing to clear the cache dir is not fatal
        exec("/bin/rm -f {$this->PFFWDIR}/symon/rrds/localhost/*.rrd 2>&1", $output, $retval);
        if ($retval === 0) {
            exec('/bin/sh /usr/local/share/examples/symon/c_smrrds.sh all 2>&1', $output, $retval);
            if ($retval !== 0) {
                $result= FALSE;
            }
        }
        else {
            $result= FALSE;
        }
        // collectd
        exec("/bin/rm -rf {$this->PFFWDIR}/collectd/rrd/localhost/* 2>&1", $output, $retval);
        if ($retval !== 0) {
            $result= FALSE;
        }
        exec("/bin/rm -f {$this->PFFWDIR}/dashboard/* 2>&1", $output, $retval);
        if ($retval !== 0) {
            $result= FALSE;
        }
        exec("/bin/rm -f {$this->PFFWDIR}/cache/* 2>&1", $output, $retval);
        if ($retval !== 0) {
            $result= FALSE;
        }
        if (!$result) {
            $errout= implode("\n", $output);
            Error($errout);
            ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Failed initializing graphs: $errout");
        }
        return $result;
    }
References $retval, $VIEW_PATH, ctlr_syslog(), and Error().
isIfUp()
isIfUp ($if)
Definition at line 539 of file system.php.
    {
        exec("/sbin/ifconfig $if | grep \"[[:space:]]*flags=\"", $output, $retval);
        if (preg_match('/(<UP,|\bUP\b)/', $output[0])) {
            return TRUE;
        }
        return FALSE;
    }
References $retval.
Referenced by _getIfConfig().
IsNotifierEnabled()
IsNotifierEnabled ()
Definition at line 1558 of file system.php.
    {
        $stat= $this->SearchFile($this->rootCronTab, '?^\h*(#|)\h*\*/1\h+\*\h+\*\h+\*\h+\*\h+/usr/bin/env\h+PATH=\$PATH:/usr/local/bin\h+/usr/local/bin/php\h+/var/www/htdocs/pffw/Notifier/notify.php\h+.*$?m');
        return ($stat === '');
    }
References Model\SearchFile().
Referenced by DisableNotifier(), and EnableNotifier().
NetStart()
NetStart ($if = '')
Restarts the network.
This method should be called after changing the network configuration of the system.
Attention
We have to reload pf rules too, otherwise all access to the system may be blocked. For example, if you change the IP address of int_if, you need to reload the rules; otherwise, pf would still be running with rules using the old IP address of int_if.
Parameters
string $if Interface name, or empty for both intif and extif.
Returns
bool TRUE on success, FALSE on fail.
Definition at line 1051 of file system.php.
    {
        $cmd= array();
        $intif= $this->_getIntIf();
        if ($intif !== FALSE) {
            $intif= trim($intif, '"');
            if ($if == '' || $if == $intif) {
                if ($this->isWifiIf($intif)) {
                    // Clear all wifi configuration, ifconfig down and /etc/netstart don't clear them
                    $cmd[]= "/sbin/ifconfig $intif -mediaopt hostap -nwid -wpakey -nwkey 2>&1";
                }
                $cmd[]= "/sbin/ifconfig $intif down 2>&1";
            }
        } else {
            Error('Cannot get intif');
        }
        // Down extif too, in case the gateway changes
        $extif= $this->_getExtIf();
        if ($extif !== FALSE) {
            $extif= trim($extif, '"');
            if ($if == '' || $if == $extif) {
                if ($this->isWifiIf($extif)) {
                    // Clear all wifi configuration, ifconfig down and /etc/netstart don't clear them
                    $cmd[]= "/sbin/ifconfig $extif -mediaopt hostap -nwid -wpakey -nwkey 2>&1";
                }
                $cmd[]= "/sbin/ifconfig $extif down 2>&1";
            }
        } else {
            Error('Cannot get extif');
        }
        if ($if == '' || $if == $extif) {
            // Delete the arp entry for the old gateway, in case the new gateway has the same IP address
            // Otherwise, the system cannot reach the new gateway, continues to use the old ethernet address,
            // ping, nslookup, or others don't work (extif becomes effectively down).
            $gateway= $this->getSystemGateway();
            if ($gateway !== '') {
                $cmd[]= "/usr/sbin/arp -nd $gateway 2>&1";
            }
            // Delete the current default route, so we are sure we load the pf rules after the new default route is set
            $cmd[]= "/sbin/route delete default 2>&1";
        }
        // Pass $if as arg, passing empty string is fine
        $cmd[]= "/bin/sh /etc/netstart $if 2>&1";
        // /etc/netstart does not up (autoconf?) ifs on OpenBSD 7.0 anymore
        if ($intif !== FALSE) {
            if ($if == '' || $if == $intif) {
                $cmd[]= "/sbin/ifconfig $intif up 2>&1";
            }
        }
        if ($extif !== FALSE) {
            if ($if == '' || $if == $extif) {
                $cmd[]= "/sbin/ifconfig $extif up 2>&1";
            }
        }
        // Implode with ';' not '&&', any of the commands can fail, but we should exec the others
        $cmdline= implode(' ; ', $cmd);
        exec($cmdline, $output, $retval);
        $errout= implode("\n", $output);
        Error($errout);
        // Refresh the pf rules too
        $retval&= $this->reloadPfRules();
        if ($retval === 0) {
            return TRUE;
        }
        ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Netstart failed: $errout");
        return FALSE;
    }
References $retval, Model\_getExtIf(), Model\_getIntIf(), ctlr_syslog(), Error(), getSystemGateway(), Model\isWifiIf(), and reloadPfRules().
reloadPfRules()
reloadPfRules ()
Definition at line 1129 of file system.php.
    {
        $cmd= "/sbin/route -n show | grep -q ^default";
        $count= 0;
        while ($count++ < 20) {
            exec($cmd, $output, $retval);
            if ($retval === 0) {
                break;
            }
            exec('/bin/sleep ' . self::PROC_STAT_SLEEP_TIME);
        }
        if ($retval !== 0) {
            Error(_('Cannot find default route'));
        }
        $cmd= "/sbin/pfctl -f $this->PfRulesFile 2>&1";
        exec($cmd, $output, $retval);
        $errout= implode("\n", $output);
        Error($errout);
        return $retval;
    }
References $retval, and Error().
Referenced by NetStart().
Restart()
Restart ()
Restarts the system.
Reimplemented from View.
Definition at line 962 of file system.php.
    {
        global $TmpFile;
        $this->RunShellCommand("/sbin/shutdown -r now > $TmpFile 2>&1 &");
        return TRUE;
    }
References $TmpFile, and Model\RunShellCommand().
RotateAllLogFiles()
RotateAllLogFiles ()
Calls forked full rotation function.
Definition at line 1499 of file system.php.
    {
        return $this->DaemonizeFunc('DaemonizedRotateAllLogFiles');
    }
References DaemonizeFunc().
RotateLogFile()
RotateLogFile ($file)
Calls forked rotation function.
Definition at line 1455 of file system.php.
    {
        return $this->DaemonizeFunc('DaemonizedRotateLogFile', $file);
    }
References DaemonizeFunc().
SelectProcesses()
SelectProcesses ($psout)
Reads all processes from ps output.
Used to list all processes.
Parameters
array $psout ps output obtained elsewhere.
Returns
array Parsed ps output.
Reimplemented from Model.
Definition at line 1175 of file system.php.
    {
        //   PID STARTED  %CPU      TIME %MEM   RSS   VSZ STAT  PRI  NI TTY      USER     GROUP    COMMAND
        //     1  5:10PM   0.0   0:00.03  0.0   388   412 Is     10   0 ??       root     wheel    /sbin/init
        $re= '/^\s*(\d+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\d+)\s+(\d+)\s+(\S+)\s+(\d+)\s+(\d+)\s+\S+\s+(\S+)\s+(\S+)\s+(.+)$/';
        $processes= array();
        foreach ($psout as $line) {
            if (preg_match($re, $line, $match)) {
                $processes[]= array(
                    $match[1],
                    $match[2],
                    $match[3],
                    $match[4],
                    $match[5],
                    $match[6],
                    $match[7],
                    $match[8],
                    $match[9],
                    $match[10],
                    $match[11],
                    $match[12],
                    $match[13],
                    );
            }
        }
        return $processes;
    }
SetDateTime()
SetDateTime ($datetime)
Sets system clock.
Parameters
string $datetime Datetime.
Returns
bool TRUE on success, FALSE on fail.
/bin/date returns 0 on success on OpenBSD 5.9 now.
Definition at line 838 of file system.php.
    {
        exec("/bin/date $datetime 2>&1", $output, $retval);
        if ($retval === 0) {
            return TRUE;
        }
        $errout= implode("\n", $output);
        Error($errout);
        ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Set date failed: $errout");
        return FALSE;
    }
References $retval, ctlr_syslog(), and Error().
SetIf()
SetIf ($if, $type, $ip, $mask, $bc, $opt, $nwid, $keytype, $key, $hostap)
Sets system interface configuration.
Parameters
string $if Interface name.
string $type inet or dhcp|autoconf only.
string $ip IP address.
string $mask Netmask.
string $bc Broadcast address.
string $opt Options.
string $nwid Network id for wifi.
string $keytype Type of key for wifi.
string $key Key for wifi.
string $hostap Whether to enable Host AP for wifi.
Returns
mixed Return value of file_put_contents() or FALSE on fail.
Attention
Need a new line char at the end of hostname.if, otherwise /etc/netstart fails Since file_put_contents() removes the last new line char, we append a PHP_EOL.
Definition at line 755 of file system.php.
    {
        global $Re_Ip;
        // OpenBSD 6.6 uses hex if mask in hostname.if file
        // Convert if mask from ip to hex: 255.255.255.0 -> 0xffffff00
        if ($mask !== '') {
            $mask= '0x'.dechex(ip2long($mask));
        }
        // PFFW supports only these configuration options
        // Trim whitespace caused by empty strings
        $ifconf= trim("$type $ip $mask $bc $opt");
        if ($nwid !== '') {
            $ifconf.= "\n".trim("nwid $nwid");
            if ($keytype !== '' && $key !== '') {
                $ifconf.= ' '.trim("$keytype $key");
            }
        }
        if ($hostap == 'on') {
            $ifconf.= "\nmediaopt hostap";
        }
        // @todo Args passed to this function are validated by the Controller, but we can implement some semantic validation too
        if (preg_match("/^inet\s*$Re_Ip\s*[x0-9a-f]+\s*($Re_Ip|).*$/m", $ifconf)
            || preg_match('/^(dhcp|autoconf)\s*NONE\s*NONE\s*NONE.*$/m', $ifconf)
            || preg_match('/^(dhcp|autoconf)$/m', $ifconf)
            || preg_match('/(dhcp|autoconf)/m', $ifconf) && ($hostap === '')) {
            return file_put_contents($this->confDir.'hostname.'.$if, $ifconf.PHP_EOL);
        }
        else {
            Error(_('Unsupported interface configuration').": $ifconf");
        }
        return FALSE;
    }
References $Re_Ip, and Error().
SetLogsConfig()
SetLogsConfig ($model, $file, $count, $size, $when)
Set logs configuration.
Definition at line 1431 of file system.php.
    {
        global $MODEL_PATH, $ModelFiles, $Models, $ModelsToLogConfig;
        if (array_key_exists($model, $ModelFiles)) {
            require_once($MODEL_PATH.'/'.$ModelFiles[$model]);
            if (class_exists($Models[$model])) {
                $model= new $Models[$model]();
                return $model->SetNewsyslogConfig($file, $count, $size, $when);
            }
            else {
                ctlr_syslog(LOG_NOTICE, __FILE__, __FUNCTION__, __LINE__, "Not in Models: $model");
            }
        }
        else {
            ctlr_syslog(LOG_NOTICE, __FILE__, __FUNCTION__, __LINE__, "Not in ModelFiles: $model");
        }
        return FALSE;
    }
References $MODEL_PATH, $ModelFiles, $Models, $ModelsToLogConfig, and ctlr_syslog().
SetManCgiHome()
SetManCgiHome ($ip)
Set int_net.
Definition at line 1207 of file system.php.
    {
        $re= '|^(\s*\$www\{\'home\'\}\h*=\h*\')(.*)(\'\h*;\h*)$|m';
        return $this->ReplaceRegexp('/var/www/htdocs/pffw/View/cgi-bin/man.cgi', $re, '${1}'."https://$ip".'${3}');
    }
References Model\ReplaceRegexp().
SetMFS()
SetMFS ($value)
Definition at line 1838 of file system.php.
    {
        return $this->SetNVP('/etc/rc', 'USE_MFS', $value);
    }
References Model\SetNVP().
SetMFSSize()
SetMFSSize ($value)
Definition at line 1843 of file system.php.
    {
        return $this->SetNVP('/etc/rc', 'MFS_SIZE', $value);
    }
References Model\SetNVP().
SetMyGate()
SetMyGate ($mygate)
Sets system static gateway.
Writes the given IP address to mygate file.
Parameters
string $mygate Gateway IP address.
Returns
int Return value of file_put_contents().
Definition at line 719 of file system.php.
    {
        // File is created, if does not exist. Otherwise, overwrites the existing file.
        return file_put_contents($this->confDir.'mygate', $mygate.PHP_EOL);
    }
Referenced by SystemMakeStaticGateway().
SetMyName()
SetMyName ($myname)
Sets system hostname.
Writes the given name to myname file.
Parameters
string $myname Hostname.
Returns
int Return value of file_put_contents().
Attention
Do not change the active hostname here by running /bin/hostname, otherwise UI login over SSH fails.
Definition at line 733 of file system.php.
    {
        // The user should run auto config and then reboot the system to activate the new hostname.
        return file_put_contents($this->confDir.'myname', $myname.PHP_EOL);
    }
SetNameServer()
SetNameServer ($nameserver)
Changes nameserver.
Parameters
string $nameserver System nameserver IP.
Returns
bool TRUE on success, FALSE on fail.
Definition at line 814 of file system.php.
    {
        global $Re_Ip;
        return $this->ReplaceRegexp($this->confDir.'resolv.conf', "/^(\h*nameserver\h*)($Re_Ip)(\b.*)$/m", '${1}'.$nameserver.'${3}');
    }
References $Re_Ip, and Model\ReplaceRegexp().
SetNotifierAPIKey()
SetNotifierAPIKey ($apikey)
Attention
$apikey string should be in quotes
Definition at line 1659 of file system.php.
    {
        global $ROOT, $TEST_DIR_SRC;
        // Append semi-colon to new value, this setting is a PHP line
        return $this->SetNVP($ROOT . $TEST_DIR_SRC . '/lib/setup.php', '\$NotifierAPIKey', "'$apikey';");
    }
References $ROOT, $TEST_DIR_SRC, and Model\SetNVP().
SetNotifierHost()
SetNotifierHost ($host)
Attention
$host string should be in quotes
Definition at line 1634 of file system.php.
    {
        global $ROOT, $TEST_DIR_SRC;
        // Append semi-colon to new value, this setting is a PHP line
        return $this->SetNVP($ROOT . $TEST_DIR_SRC . '/lib/setup.php', '\$NotifierHost', "'$host';");
    }
References $ROOT, $TEST_DIR_SRC, and Model\SetNVP().
SetNotifierTimeout()
SetNotifierTimeout ($timeout)
Definition at line 1743 of file system.php.
    {
        global $ROOT, $TEST_DIR_SRC;
        // Append semi-colon to new value, this setting is a PHP line
        return $this->SetNVP($ROOT . $TEST_DIR_SRC . '/lib/setup.php', '\$NotifierTimeout', $timeout.';');
    }
References $ROOT, $TEST_DIR_SRC, and Model\SetNVP().
SetNotifyLevel()
SetNotifyLevel ($level)
Definition at line 1626 of file system.php.
    {
        global $ROOT, $TEST_DIR_SRC;
        // Append semi-colon to new value, this setting is a PHP line
        return $this->SetNVP($ROOT . $TEST_DIR_SRC . '/lib/setup.php', '\$NotifyLevel', $level.';');
    }
References $ROOT, $TEST_DIR_SRC, and Model\SetNVP().
SetRemoteTime()
SetRemoteTime ($timeserver)
Sets datetime from the given time server.
Writes its output to a temporary file.
Todo:
All such networking calls should run on a separate thread, similar to pfctl tests.
Definition at line 990 of file system.php.
    {
        global $TmpFile;
        // First make sure there are no running rdate processes.
        $this->Pkill('rdate', '-KILL');
        // Note that this command runs on the background.
        $this->RunShellCommand("/usr/sbin/rdate $timeserver > $TmpFile 2>&1 &");
        return TRUE;
    }
References $TmpFile, Model\Pkill(), and Model\RunShellCommand().
SetRootEmail()
SetRootEmail ($emailaddr)
Changes root e-mail address.
Parameters
string $emailaddr E-mail address.
Returns
bool TRUE on success, FALSE on fail.
Definition at line 827 of file system.php.
    {
        return $this->ReplaceRegexp($this->confDir.'mail/aliases', "/^(\h*root:\h*)([^#\s]*)(.*)$/m", '${1}'.$emailaddr.'${3}');
    }
References Model\ReplaceRegexp().
SetSyncMFS()
SetSyncMFS ($value)
Definition at line 1848 of file system.php.
    {
        return $this->SetNVP('/etc/sync.var', 'SYNC_MFS', $value);
    }
References Model\SetNVP().
Shutdown()
Shutdown ()
Halts and powers the system down.
Definition at line 951 of file system.php.
    {
        global $TmpFile;
        $this->RunShellCommand("/sbin/shutdown -h -p now > $TmpFile 2>&1 &");
        return TRUE;
    }
References $TmpFile, and Model\RunShellCommand().
SystemMakeDynamicGateway()
SystemMakeDynamicGateway ()
Converts static gateway address to dynamic address.
Simply deletes mygate file.
Returns
bool TRUE on success, FALSE on fail.
Definition at line 706 of file system.php.
    {
        return $this->DeleteFile($this->confDir.'mygate');
    }
References Model\DeleteFile().
SystemMakeStaticGateway()
SystemMakeStaticGateway ()
Converts dynamic gateway address to static address.
Returns
bool TRUE on success, FALSE on fail.
Definition at line 691 of file system.php.
    {
        if (($gateway= $this->_getDynamicGateway()) !== FALSE) {
            return $this->SetMyGate($gateway);
        }
        return FALSE;
    }
References _getDynamicGateway(), and SetMyGate().
UpdateMailAliases()
UpdateMailAliases ()
Updates mail aliases.
This is necessary after modifying the aliases file.
Returns
string Output of newaliases.
Definition at line 858 of file system.php.
    {
        return Output($this->RunShellCommand('/usr/bin/newaliases'));
    }
References Output(), and Model\RunShellCommand().
Field Documentation
$confDir
$confDir = '/etc/'
Definition at line 32 of file system.php.
$Layout
$Layout = 'system'
Definition at line 113 of file include.php.
$LogFile
$LogFile = '/var/log/messages'
Definition at line 39 of file system.php.
$Model
$Model = 'system'
Definition at line 112 of file include.php.
$Name
$Name = 'system'
Definition at line 29 of file system.php.
$User
$User = '\S+'
Definition at line 34 of file system.php.
The documentation for this class was generated from the following files:
src/Model/system.php
src/View/system/include.php