PF Firewall: src/View/system/conf.basic.php File Reference
conf.basic.php File Reference
Basic system-wide configuration.
Functions
PrintDateTimeForm ($remotetime)
Displays a form to change system datetime.
Variables
$RemoteTime = FALSE
if (count($_POST))
Detailed Description
Basic system-wide configuration.
Definition in file conf.basic.php.
Function Documentation
PrintDateTimeForm()
PrintDateTimeForm ($remotetime)
Displays a form to change system datetime.
Attention
PHP date() function uses the timezone defined in php ini file, hence we use /bin/date here.
Todo:
Check how to get local date time using a PHP function.
Definition at line 28 of file conf.basic.php.
{
    global $TimeServer;
    if (isset($_SESSION['TimeServer'])) {
        $TimeServer= $_SESSION['TimeServer'];
    }
    $day= exec('/bin/date +%d');
    $month= exec('/bin/date +%m');
    $year= exec('/bin/date +%y');
    $hour= exec('/bin/date +%H');
    $min= exec('/bin/date +%M');
    $confirm= _NOTICE('Are you sure you want to set the date?');
    ?>
    <tr class="oddline">
        <td class="title">
            <?php echo _TITLE('Time server').':' ?>
        </td>
        <td>
            <form action="<?php echo $_SERVER['PHP_SELF'] ?>" method="post">
                <input type="text" name="TimeServer" style="width: 200px;" maxlength="50" value="<?php echo $TimeServer ?>" />
                <input type="submit" name="Display" value="<?php echo _CONTROL('Display') ?>"/>
                <input type="submit" name="Apply" value="<?php echo _CONTROL('Apply') ?>" onclick="return confirm('<?php echo $confirm ?>')"/>
                <?php
                if ($remotetime) {
                    echo '<br />'.$remotetime;
                }
                ?>
            </form>
        </td>
        <td class="none">
            <?php
            PrintHelpBox(_HELPBOX('Usually the network time daemon adjusts the system clock according to Internet time servers gradually. But if the clock is too out of sync with the time servers, you are advised to set the system clock to Internet time manually. You can use your own time server if you like.'));
            ?>
        </td>
    </tr>
    <tr class="evenline">
        <td class="title">
            <?php echo _TITLE('Date').':' ?>
        </td>
        <td>
            <form action="<?php echo $_SERVER['PHP_SELF'] ?>" method="post">
                <input type="text" name="Day" style="width: 20px;" maxlength="2" value="<?php echo $day ?>" />.
                <input type="text" name="Month" style="width: 20px;" maxlength="2" value="<?php echo $month ?>" />.
                <input type="text" name="Year" style="width: 20px;" maxlength="2" value="<?php echo $year ?>" /> -
                <input type="text" name="Hour" style="width: 20px;" maxlength="2" value="<?php echo $hour ?>" />:
                <input type="text" name="Minute" style="width: 20px;" maxlength="2" value="<?php echo $min ?>" />
                <input type="submit" name="Apply" value="<?php echo _CONTROL('Apply') ?>" onclick="return confirm('<?php echo $confirm ?>')"/>
            </form>
        </td>
        <td class="none">
            <?php
            PrintHelpBox(_HELPBOX('You can set the system clock here. Format is day.month.year-hour:minute.
<b>You must be very careful when setting the system clock, significant hops in system time may cause system malfunction.</b>'));
            ?>
        </td>
    </tr>
    <?php
}
$RemoteTime= FALSE;
if (count($_POST)) {
    if (filter_has_var(INPUT_POST, 'Year') && filter_has_var(INPUT_POST, 'Month') && filter_has_var(INPUT_POST, 'Day') && filter_has_var(INPUT_POST, 'Hour') && filter_has_var(INPUT_POST, 'Minute')) {
        $NewDateTime= filter_input(INPUT_POST, 'Year').filter_input(INPUT_POST, 'Month').filter_input(INPUT_POST, 'Day').filter_input(INPUT_POST, 'Hour').filter_input(INPUT_POST, 'Minute');
        if (!$View->Controller($Output, 'SetDateTime', $NewDateTime)) {
            wui_syslog(LOG_NOTICE, __FILE__, __FUNCTION__, __LINE__, "Time set failed: $NewDateTime");
        }
    }
    else if (filter_has_var(INPUT_POST, 'TimeServer')) {
        $_SESSION['TimeServer']= filter_input(INPUT_POST, 'TimeServer');
        $TimeServer= $_SESSION['TimeServer'];
        if (filter_has_var(INPUT_POST, 'Apply')) {
            $View->Controller($Output, 'SetRemoteTime', $TimeServer);
        }
        else if (filter_has_var(INPUT_POST, 'Display')) {
            $View->Controller($Output, 'DisplayRemoteTime', $TimeServer);
        }
        $View->Controller($Output, 'GetRemoteTime');
        $RemoteTime= implode("\n", $Output);
    }
    else if (filter_has_var(INPUT_POST, 'MyName')) {
        $View->Controller($Output, 'SetMyName', trim(filter_input(INPUT_POST, 'MyName')));
    }
    else if (filter_has_var(INPUT_POST, 'RootEmail')) {
        if ($View->Controller($Output, 'SetRootEmail', filter_input(INPUT_POST, 'RootEmail'))) {
            $View->Controller($Output, 'UpdateMailAliases');
        }
    }
}
References $_SESSION, $TimeServer, _HELPBOX(), _NOTICE(), _TITLE(), and PrintHelpBox().
Variable Documentation
$RemoteTime
$RemoteTime = FALSE
Definition at line 93 of file conf.basic.php.
if
if(count($_POST)) (count($_POST))
Definition at line 95 of file conf.basic.php.