PF Firewall: src/View/pf/conf.write.php File Reference
conf.write.php File Reference
Variables
$printNumbers = 1
if(count($_POST) &&!filter_has_var(INPUT_POST, 'numbers')) $testResult = $View->Controller($Output, 'TestRules', json_encode($View->RuleSet->rules))
if($testResult) else
$force = 0
if(filter_has_var(INPUT_POST, 'forcedisplay')) $StrRules = array()
$generated = FALSE
if ($testResult||$force)
border bottom
Variable Documentation
$force
$force = 0
Definition at line 41 of file conf.write.php.
Referenced by Model\IsInlineAnchor(), Rule\load(), RuleSet\load(), RuleSet\parse(), RuleSet\parseInlineRules(), RuleSet\validate(), Rule\validate(), Rule\validateArrayValues(), Rule\validateKeyDef(), and Rule\validateValue().
$generated
$generated = FALSE
Definition at line 47 of file conf.write.php.
$printNumbers
$printNumbers = 1
Definition at line 23 of file conf.write.php.
Referenced by RuleSet\generate().
$StrRules
if (filter_has_var(INPUT_POST, 'forcedisplay')) $StrRules = array()
Definition at line 46 of file conf.write.php.
$testResult
if (count($_POST) &&!filter_has_var(INPUT_POST, 'numbers')) $testResult = $View->Controller($Output, 'TestRules', json_encode($View->RuleSet->rules))
Definition at line 28 of file conf.write.php.
Referenced by AfTo\edit(), Anchor\edit(), Antispoof\edit(), Blank\edit(), Comment\edit(), DivertPacket\edit(), DivertTo\edit(), Filter\edit(), FilterBase\edit(), _Include\edit(), Limit\edit(), LoadAnchor\edit(), Macro\edit(), NatBase\edit(), NatTo\edit(), Option\edit(), Queue\edit(), Route\edit(), Scrub\edit(), State\edit(), Table\edit(), Timeout\edit(), Rule\editHead(), and RuleSet\save().
bottom
border bottom
Definition at line 71 of file conf.write.php.
else
if ($testResult) else
Initial value:
{
    PrintHelpWindow('<br>' . _NOTICE('Failed testing ruleset'), NULL, 'ERROR')
Definition at line 37 of file conf.write.php.
if
if($testResult|| $force) ($testResult||)
Definition at line 48 of file conf.write.php.