PF Firewall: src/View/system/conf.net.php File Reference
conf.net.php File Reference
Network configuration.
Functions
PrintHostsForm ()
Displays a list box with hosts file contents.
Variables
if (count($_POST))
$Row = 1
$Class = $Row++ % 2 == 0 ? 'evenline' : 'oddline'
ifs
Detailed Description
Network configuration.
Definition in file conf.net.php.
Function Documentation
PrintHostsForm()
PrintHostsForm ()
Displays a list box with hosts file contents.
Todo:
This form needs improvement, should not be one line entry.
Definition at line 30 of file conf.net.php.
{
    global $View, $Class;
    ?>
    <tr class="<?php echo $Class ?>">
        <td class="title">
            <?php echo _TITLE('Hosts').':' ?>
        </td>
        <td>
            <?php
            if ($View->Controller($hosts, 'GetHosts')) {
                ?>
                <form action="<?php echo $_SERVER['PHP_SELF'] ?>" method="post">
                    <input style="display:none;" type="submit" name="Add" value="<?php echo _CONTROL('Add') ?>"/>
                    <select name="HostsToDelete[]" multiple style="width: 300px; height: 100px;">
                        <?php
                        foreach ($hosts as $host) {
                        ?>
                        <option value="<?php echo $host ?>"><?php echo $host ?></option>
                        <?php
                        }
                        ?>
                    </select>
                    <input type="submit" name="Delete" value="<?php echo _CONTROL('Delete') ?>"/><br />
                    <input type="text" name="HostToAdd" style="width: 300px;" maxlength="250"/>
                    <input type="submit" name="Add" value="<?php echo _CONTROL('Add') ?>"/>
                </form>
                <?php
            }
            ?>
        </td>
        <td class="none" rowspan="2">
            <?php
            PrintHelpBox(_HELPBOX('You can modify the hosts file here. Format of a hosts entry is: IP hostname alias [alias [...]]'));
            ?>
        </td>
    </tr>
    <?php
}
if (count($_POST)) {
    if (filter_has_var(INPUT_POST, 'NetStart')) {
        $View->Controller($Output, 'NetStart');
    }
    // Other vars may be empty strings, do not check
    else if (filter_has_var(INPUT_POST, 'IfName')) {
        if (filter_has_var(INPUT_POST, 'Apply')) {
            $View->Controller($Output, 'SetIf', filter_input(INPUT_POST, 'IfName'), filter_input(INPUT_POST, 'IfType'), filter_input(INPUT_POST, 'InterfaceIP'),
                    filter_input(INPUT_POST, 'IfMask'), filter_input(INPUT_POST, 'IfBc'), filter_input(INPUT_POST, 'IfOpt'),
                    filter_has_var(INPUT_POST, 'IfNwId') ? filter_input(INPUT_POST, 'IfNwId') : '',
                    filter_has_var(INPUT_POST, 'IfKeyType') ? filter_input(INPUT_POST, 'IfKeyType') : '',
                    filter_has_var(INPUT_POST, 'IfKey') ? filter_input(INPUT_POST, 'IfKey') : '',
                    filter_has_var(INPUT_POST, 'IfHostap') ? filter_input(INPUT_POST, 'IfHostap') : '');
        }
        else if (filter_has_var(INPUT_POST, 'Restart')) {
            $View->Controller($Output, 'NetStart', filter_input(INPUT_POST, 'IfName'));
        }
        else if (filter_has_var(INPUT_POST, 'Up')) {
            $View->Controller($Output, 'IfUpDown', filter_input(INPUT_POST, 'IfName'), 1);
        }
        else if (filter_has_var(INPUT_POST, 'Down')) {
            $View->Controller($Output, 'IfUpDown', filter_input(INPUT_POST, 'IfName'), 0);
        }
        else if (filter_has_var(INPUT_POST, 'Delete')) {
            $View->Controller($Output, 'DeleteIf', filter_input(INPUT_POST, 'IfName'));
        }
    }
    else if (filter_has_var(INPUT_POST, 'MyGate')) {
        if (filter_has_var(INPUT_POST, 'Apply')) {
            $View->Controller($Output, 'SetMyGate', filter_input(INPUT_POST, 'MyGate'));
        }
        else if (filter_has_var(INPUT_POST, 'MakeDynamic')) {
            $View->Controller($Output, 'SystemMakeDynamicGateway');
        }
    }
    else if (filter_has_var(INPUT_POST, 'MakeStatic')) {
        $View->Controller($Output, 'SystemMakeStaticGateway');
    }
    else if (filter_has_var(INPUT_POST, 'NameServer')) {
        $View->Controller($Output, 'SetNameServer', filter_input(INPUT_POST, 'NameServer'));
    }
    else if (filter_has_var(INPUT_POST, 'Add') && filter_has_var(INPUT_POST, 'HostToAdd')) {
        $View->Controller($Output, 'AddHost', filter_input(INPUT_POST, 'HostToAdd'));
    }
    else if (filter_has_var(INPUT_POST, 'Delete')) {
        foreach ($_POST['HostsToDelete'] as $Host) {
            $View->Controller($Output, 'DelHost', $Host);
        }
    }
}
References $Class, $View, _HELPBOX(), _TITLE(), and PrintHelpBox().
Variable Documentation
$Class
$Class = $Row++ % 2 == 0 ? 'evenline' : 'oddline'
Definition at line 126 of file conf.net.php.
Referenced by PrintHostsForm(), and PrintReloadConfigForm().
$Row
$Row = 1
Definition at line 125 of file conf.net.php.
if
if(count($_POST)) (count($_POST))
Definition at line 70 of file conf.net.php.
ifs
ifs
Definition at line 193 of file conf.net.php.