PF Firewall: src/Controller/lib.php File Reference
lib.php File Reference
Defs and library functions for Controller.
Functions
IsName ($str)
IsNumber ($str)
IsSha1Str ($str)
IsBool ($str)
IsJson ($str)
IsEmpty ($str)
IsStr ($str)
IsSerializedArray ($str)
IsIPList ($iplist)
IsIPAddress ($ip)
IsIPRange ($iprange)
IsHost ($host)
IsUrl ($name)
IsEmailAddress ($addr)
IsAsterisk ($str)
IsDateTime ($datetime)
Checks the type of datetime string as supplied to date command.
IsTailNumber ($str)
IsMfsSize ($str)
ComputeArgCounts ($commands, $argv, $cmd, &$actual, &$expected, &$acceptable, &$check)
Computes and fills arg count variables.
ValidateArgs ($commands, $command, $argv, $check)
Checks types of the arguments passed.
ExpandArgs (&$ArgV, &$Locale, &$View, &$Command)
Expands command line args.
ValidateCommand ($ArgV, $Locale, $View, $Command, $validateargs, &$Model)
Validates command line.
Variables
$TmpFile = PFFWDIR.'/out/ctlr.out'
Output and error redirect file.
$RetvalFile = PFFWDIR.'/out/retval.out'
Return value redirect file.
$ModelFiles
Matches model names to files. View provides the name only.
$Models
Matches model names to Classes. Used to create the object.
$ArgTypes
Functions and info strings used in shell arg control.
$MonthDays
Detailed Description
Defs and library functions for Controller.
Definition in file lib.php.
Function Documentation
ComputeArgCounts()
ComputeArgCounts ($commands, $argv, $cmd, & $actual, & $expected, & $acceptable, & $check)
Computes and fills arg count variables.
Parameters
array $commands Available commands for the current model
array $argv Argument vector
string $cmd Method name, key to $commands
int $actual Given arg count [out]
int $expected Expected arg count [out]
int $acceptable Acceptable arg count [out]
int $check Arg count used while validating [out]
Attention
There may be extra or missing args, hence min() here
Definition at line 329 of file lib.php.
{
    $actual= count($argv);
    $expected= count($commands[$cmd]['argv']);
    $acceptable= $expected;
    for ($argpos= 0; $argpos < $expected; $argpos++) {
        $argtype= $commands[$cmd]['argv'][$argpos];
        if ($argtype & NONE) {
            $acceptable--;
        }
    }
    $check= min($actual, $expected);
}
References NONE.
Referenced by ValidateCommand().
ExpandArgs()
ExpandArgs (& $ArgV, & $Locale, & $View, & $Command)
Expands command line args.
Parameters
array $ArgV Argument vector, modified
string $Locale The Locale to set
string $View The View to find the Model
string $Command Model command to call
Returns
bool Validation result
Definition at line 429 of file lib.php.
{
    $valid= FALSE;
    // Arg 0 contains all of the args as a json encoded string
    if (count($ArgV) < 1) {
        ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, 'Not enough args: '.print_r($ArgV, TRUE));
        goto out;
    }
    if (count($ArgV) > 1) {
        ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, 'Too many args: '.print_r($ArgV, TRUE));
        goto out;
    }
    $decoded= json_decode($ArgV[0], TRUE);
    if ($decoded == NULL || !is_array($decoded)) {
        ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, 'Failed decoding args: '.print_r($ArgV, TRUE));
        goto out;
    }
    $ArgV= $decoded;
    if (count($ArgV) < 3) {
        ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, 'Not enough args: '.print_r($ArgV, TRUE));
        goto out;
    }
    // Controller runs using the session locale of View
    $Locale= $ArgV[0];
    $View= $ArgV[1];
    $Command= $ArgV[2];
    // Discard locale, view, and command before computing arg counts
    $ArgV= array_slice($ArgV, 3);
    $valid= TRUE;
out:
    return $valid;
}
References $ArgV, $View, and ctlr_syslog().
IsAsterisk()
IsAsterisk ($str)
Definition at line 268 of file lib.php.
{
    return $str === '*';
}
IsBool()
IsBool ($str)
Definition at line 196 of file lib.php.
{
    return preg_match('/' . RE_BOOL . '/', $str);
}
References RE_BOOL.
IsDateTime()
IsDateTime ($datetime)
Checks the type of datetime string as supplied to date command.
Parameters
string $datetime Arg.
Returns
bool Type check result
There should be 10 digits.
Year can be 00-99, so no need to check.
Definition at line 279 of file lib.php.
{
    global $MonthDays;
    if (preg_match('/^\d{10,}$/', $datetime)) {
        $datetime= str_split($datetime, 2);
        //$Year= $datetime[0] + 0;
        $month= $datetime[1] + 0;
        $day= $datetime[2] + 0;
        $hour= $datetime[3] + 0;
        $min= $datetime[4] + 0;
        if (($month <= 12)
            && ($day <= $MonthDays[$month])
            && ($hour <= 23)
            && ($min <= 59)) {
            return TRUE;
        }
    }
    return FALSE;
}
References $MonthDays.
IsEmailAddress()
IsEmailAddress ($addr)
Definition at line 262 of file lib.php.
{
    return preg_match('/^root(@localhost|)$/', $addr)
        || preg_match('/^[a-z]+[a-z0-9]*(\.|\-|_)?[a-z0-9]+@([a-z]+[a-z0-9]*(\.|\-)?[a-z]+[a-z0-9]*[a-z0-9]+){1,4}\.[a-z]{2,4}$/', $addr);
}
IsEmpty()
IsEmpty ($str)
Definition at line 206 of file lib.php.
{
    return empty($str);
}
IsHost()
IsHost ($host)
Definition at line 250 of file lib.php.
{
    global $preIP;
    return preg_match("/^($preIP|::1)\s[a-zA-Z][a-z0-9A-Z_.#\s]{0,100}$/", $host);
}
References $preIP.
IsIPAddress()
IsIPAddress ($ip)
Definition at line 236 of file lib.php.
{
    global $preIP;
    return preg_match("/^$preIP$/", $ip);
}
References $preIP.
Referenced by IsIPList().
IsIPList()
IsIPList ($iplist)
Definition at line 225 of file lib.php.
{
    $ips= explode(';', $iplist, 10);
    foreach ($ips as $ip) {
        if ($ip !== '' && !IsIPAddress(trim($ip))) {
            return FALSE;
        }
    }
    return TRUE;
}
References IsIPAddress().
IsIPRange()
IsIPRange ($iprange)
Definition at line 243 of file lib.php.
{
    global $preIP, $preIPRange;
    return preg_match("/^$preIP\/$preIPRange$/", $iprange);
}
References $preIP, and $preIPRange.
IsJson()
IsJson ($str)
Definition at line 201 of file lib.php.
{
    return json_decode($str) !== NULL;
}
IsMfsSize()
IsMfsSize ($str)
Definition at line 313 of file lib.php.
{
    return preg_match('/^\d+[kKmMgG]*$/', $str);
}
IsName()
IsName ($str)
Definition at line 181 of file lib.php.
{
    return preg_match('/' . RE_NAME . '/', $str);
}
References RE_NAME.
IsNumber()
IsNumber ($str)
Definition at line 186 of file lib.php.
{
    return preg_match('/' . RE_NUM . '/', $str);
}
References RE_NUM.
Referenced by IsTailNumber().
IsSerializedArray()
IsSerializedArray ($str)
Definition at line 217 of file lib.php.
{
    // Serialized arrays passed to the Model are small enough to warrant this json_decode() and array check
    // Otherwise, this is not true for the return values of the Model, especially logs and statistics
    // XXX: Was unserialize() before, redundant now.
    return is_array(json_decode($str, TRUE));
}
IsSha1Str()
IsSha1Str ($str)
Definition at line 191 of file lib.php.
{
    return preg_match('/' . RE_SHA1 . '/', $str);
}
References RE_SHA1.
IsStr()
IsStr ($str)
Todo:
This is still too general?
Definition at line 211 of file lib.php.
{
    return preg_match("/^[^\n]{0,500}$/", $str);
}
IsTailNumber()
IsTailNumber ($str)
Bug:
tail(1) on OpenBSD 5.9 amd64 gets stuck with: echo soner | /usr/bin/tail -99999999 &m=148586652218524&w=2
Attention
Never allow large numbers here, otherwise the system becomes unusuable. Fixed in 6.4
Definition at line 302 of file lib.php.
{
    if (IsNumber($str)) {
        return $str < 1000;
    }
}
References IsNumber().
IsUrl()
IsUrl ($name)
Definition at line 257 of file lib.php.
{
    return preg_match('|^[\w_.:\-/?=]{1,200}$|', $name);
}
ValidateArgs()
ValidateArgs ($commands, $command, $argv, $check)
Checks types of the arguments passed.
The arguments are checked against the types listed in $commands.
Parameters
array $commands Available commands for the current model
string $command Method name, key to $commands
array $argv Argument vector
int $check Arg count used while validating
Returns
bool Validation result
Todo:
There are 2 types of argument checks in this project, which one to choose?
Definition at line 359 of file lib.php.
{
    global $ArgTypes;
    $helpmsg= $commands[$command]['desc'];
    $logmsg= $commands[$command]['desc'];
    $valid= FALSE;
    // Check each argument in order
    for ($argpos= 0; $argpos < $check; $argpos++) {
        $arg= $argv[$argpos];
        $argtype= $commands[$command]['argv'][$argpos];
        // Multiple types may match for an arg, hence the foreach loop
        foreach ($ArgTypes as $type => $conf) {
            // Acceptable types are bitwise ORed, hence the AND here
            if ($argtype & $type) {
                $validatefunc= $conf['func'];
                if ($validatefunc($arg)) {
                    $valid= TRUE;
                    if ($type & FILEPATH) {
                        // Further check if file really exists
                        exec("[ -e $arg ]", $output, $retval);
                        if ($retval !== 0) {
                            $valid= FALSE;
                            $errormsg= "$command: $arg";
                            Error(_('No such file').": $errormsg");
                            ctlr_syslog(LOG_NOTICE, __FILE__, __FUNCTION__, __LINE__, "No such file: $errormsg");
                        }
                    }
                    if ($valid) {
                        // One type succeded, hence do not check for other possible types for this arg
                        break;
                    }
                }
                else {
                    $valid= FALSE;
                    $helpmsg.= "\n"._($conf['desc']).': '.$arg;
                    $logmsg.= "\n".$conf['desc'].': '.$arg;
                    // Will keep checking if further types are possible for this arg
                }
            }
        }
        if (!$valid) {
            // One arg failed to check, do not run the func
            break;
        }
    }
    if (!$valid) {
        Error(_('Arg type check failed').": $helpmsg");
        ctlr_syslog(LOG_NOTICE, __FILE__, __FUNCTION__, __LINE__, "Arg type check failed: $logmsg");
    }
    return $valid;
}
References $ArgTypes, $retval, ctlr_syslog(), Error(), and FILEPATH.
Referenced by ValidateCommand().
ValidateCommand()
ValidateCommand ($ArgV, $Locale, $View, $Command, $validateargs, & $Model)
Validates command line.
Parameters
array $ArgV Argument vector
string $Locale The Locale to set
string $View The View to find the Model
string $Command Model command to call
bool $validateargs Whether to validate command args
object $Model Model class created
Returns
bool Validation result
Attention
Do not set the locale until after the model file is included and the model is created, otherwise strings recorded into logs are also translated, such as the strings on the Commands array of models. Strings cannot be detranslated.
Definition at line 481 of file lib.php.
{
    global $Models, $LOCALES, $VIEW_PATH;
    $valid= FALSE;
    if (!class_exists($Models[$View])) {
        Error(_('View not in Models').": $View");
        ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "View not in Models: $View");
        goto out;
    }
    $Model= new $Models[$View]();
    if (!array_key_exists($Locale, $LOCALES)) {
        ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Locale not in LOCALES: $Locale");
        goto out;
    }
    putenv('LC_ALL='.$Locale);
    putenv('LANG='.$Locale);
    $Domain= 'pffw';
    bindtextdomain($Domain, $VIEW_PATH.'/locale');
    bind_textdomain_codeset($Domain, $LOCALES[$Locale]['Codeset']);
    textdomain($Domain);
    if (!method_exists($Model, $Command)) {
        $ErrorStr= "$Models[$View]->$Command()";
        Error(_('Method does not exist').": $ErrorStr");
        ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Method does not exist: $ErrorStr");
        goto out;
    }
    if (!array_key_exists($Command, $Model->Commands)) {
        Error(_('Unsupported command').": $Command");
        ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Unsupported command: $Command");
        goto out;
    }
    if (!$validateargs) {
        goto out2;
    }
    ComputeArgCounts($Model->Commands, $ArgV, $Command, $ActualArgC, $ExpectedArgC, $AcceptableArgC, $ArgCheckC);
    if ($ActualArgC < $AcceptableArgC) {
        $ErrorStr= "[$AcceptableArgC]: $ActualArgC";
        Error(_('Not enough args')." $ErrorStr");
        ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Not enough args $ErrorStr");
        goto out;
    }
    if ($ActualArgC > $ExpectedArgC) {
        $ErrorStr= "[$ExpectedArgC]: $ActualArgC: ".implode(', ', array_slice($ArgV, $ExpectedArgC));
        Error(_('Too many args')." $ErrorStr");
        ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Too many args $ErrorStr");
        goto out;
    }
    // Check only the relevant args
    if ($ArgCheckC > 0 && !ValidateArgs($Model->Commands, $Command, $ArgV, $ArgCheckC)) {
        Error(_('Not running command').": $Command");
        ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Not running command: $Command");
        goto out;
    }
out2:
    $valid= TRUE;
out:
    return $valid;
}
References $ArgV, $Domain, $LOCALES, $Models, $View, $VIEW_PATH, ComputeArgCounts(), ctlr_syslog(), Error(), and ValidateArgs().
Variable Documentation
$ArgTypes
$ArgTypes
Functions and info strings used in shell arg control.
Parameters
string func Function to check type
string desc Info string to use when check failed
Definition at line 75 of file lib.php.
Referenced by ValidateArgs().
$ModelFiles
$ModelFiles
Initial value:
= array(
    'system'            => 'system.php',
    'pf'                => 'pf.php',
    'dhcpd'             => 'dhcpd.php',
    'dnsmasq'           => 'dnsmasq.php',
    'httpd'             => 'httpd.php',
    'httpdlogs'         => 'httpdlogs.php',
    'wui_syslog'        => 'wuilogs.php',
    'ctlr_syslog'       => 'ctlrlogs.php',
    'openssh'           => 'openssh.php',
    'ftp-proxy'         => 'ftp-proxy.php',
    'symon'             => 'symon.php',
    'symux'             => 'symux.php',
    'collectd'          => 'collectd.php',
    'monitoring'        => 'monitoring.php',
    'docs'              => 'docs.php',
    )
Matches model names to files. View provides the name only.
Definition at line 32 of file lib.php.
Referenced by System\GetLogsConfig(), Model\GetServiceStatus(), and System\SetLogsConfig().
$Models
$Models
Initial value:
= array(
    'system'            => 'System',
    'pf'                => 'Pf',
    'dhcpd'             => 'Dhcpd',
    'dnsmasq'           => 'Dnsmasq',
    'httpd'             => 'Httpd',
    'httpdlogs'         => 'Httpdlogs',
    'wui_syslog'        => 'Wuilogs',
    'ctlr_syslog'       => 'Ctlrlogs',
    'openssh'           => 'Openssh',
    'ftp-proxy'         => 'Ftpproxy',
    'symon'             => 'Symon',
    'symux'             => 'Symux',
    'collectd'          => 'Collectd',
    'monitoring'        => 'Monitoring',
    'docs'              => 'Docs',
    )
Matches model names to Classes. Used to create the object.
Definition at line 51 of file lib.php.
Referenced by System\GetLogsConfig(), Model\GetServiceStatus(), System\SetLogsConfig(), and ValidateCommand().
$MonthDays
$MonthDays
Initial value:
= array(
    1   => 31,
    2   => 29,
    3   => 31,
    4   => 30,
    5   => 31,
    6   => 30,
    7   => 31,
    8   => 31,
    9   => 30,
    10  => 31,
    11  => 30,
    12  => 31,
    )
Definition at line 166 of file lib.php.
Referenced by IsDateTime().
$RetvalFile
$RetvalFile = PFFWDIR.'/out/retval.out'
Return value redirect file.
Definition at line 29 of file lib.php.
Referenced by Model\Start().
$TmpFile
$TmpFile = PFFWDIR.'/out/ctlr.out'
Output and error redirect file.
Definition at line 26 of file lib.php.
Referenced by System\DaemonizedRotateAllLogFiles(), System\DaemonizedRotateLogFile(), System\DisplayRemoteTime(), System\GetRemoteTime(), Model\Kill(), Model\KillPid(), Model\Pkill(), System\Restart(), System\SetRemoteTime(), System\Shutdown(), and Model\Start().