PF Firewall: src/Controller/ctlr.php File Reference
ctlr.php File Reference
Proxy to run all shell commands.
Variables
$ROOT = dirname(dirname(dirname(__FILE__)))
$SRC_ROOT = dirname(dirname(__FILE__))
if(filter_has_var(INPUT_SERVER, 'SERVER_ADDR')) $ArgV = array_slice($argv, 1)
This is a command line tool, should never be requested on the web interface.
$ValidateArgs = TRUE
if($ArgV[0]==='-n') if($ArgV[0]==='-t') $retval = 1
if(!ExpandArgs($ArgV, $Locale, $View, $Command)) if (!array_key_exists($View, $ModelFiles)) = 0
out __pad0__
out $Error
$encoded = json_encode($msg, JSON_UNESCAPED_SLASHES)
if($encoded !==NULL) else
Detailed Description
Proxy to run all shell commands.
This way we have only one entry in doas.conf.
Todo:
Continually check for security issues.
Definition in file ctlr.php.
Variable Documentation
$ArgV
if (filter_has_var(INPUT_SERVER, 'SERVER_ADDR')) $ArgV = array_slice($argv, 1)
This is a command line tool, should never be requested on the web interface.
Definition at line 53 of file ctlr.php.
Referenced by ExpandArgs(), and ValidateCommand().
$encoded
$encoded = json_encode($msg, JSON_UNESCAPED_SLASHES)
Attention
If json_encode() inserts slashes, it is hard to decode the base64 encoded graph string at the receiving end
Definition at line 107 of file ctlr.php.
Referenced by File_ASN1_Element\__construct(), File_ASN1\_decode_ber(), File_ASN1\decodeBER(), File_ASN1_Element\File_ASN1_Element(), and File_X509\sign().
$Error
out $Error
Definition at line 105 of file ctlr.php.
$retval
out $retval = 1
Definition at line 72 of file ctlr.php.
Referenced by System\_getDynamicGateway(), Model\_getLiveLogs(), Pf\_getPfInfo(), System\AutoConfig(), RuleSet\comment(), View\Controller(), Model\CopyLogFileToTmp(), Model\CreateUser(), System\DaemonizedRotateAllLogFiles(), System\DaemonizedRotateLogFile(), Model\DeleteFile(), System\DeleteStats(), System\DisableNotifier(), System\DisableServiceRcLocal(), System\EnableHostap(), EnableHostap(), System\EnableNotifier(), System\EnableServiceRcLocal(), System\GenerateSSLKeyPair(), Model\GetLastLogs(), Model\GetLogs(), System\GetMFSConfig(), Pf\GetPfIfsInfo(), Pf\GetPfQueueInfo(), Pf\GetPfRulesInfo(), Model\GetProcList(), System\GetRemoteTime(), Model\getRrdValue(), Model\GetServiceStatus(), Pf\GetStateList(), System\IfUpDown(), System\InitGraphs(), System\isIfUp(), Model\IsLogFileModified(), Model\IsRunning(), Model\isWifiIf(), Rule\load(), RuleSet\load(), System\NetStart(), RuleSet\parse(), Rule\parseParenthesized(), Model\PrepareFileForDownload(), System\reloadPfRules(), Pf\RunPfInfoCmd(), Model\SearchFile(), RuleSet\separate(), Symon\SetConf(), System\SetDateTime(), Dhcpd\SetDhcpdConf(), Pf\SetIfs(), Symon\SetIfs(), Dhcpd\SetOptions(), Symon\SetPartitions(), Model\SetPassword(), Model\Start(), Pf\Start(), Pf\Stop(), RuleSet\uncomment(), and ValidateArgs().
$ROOT
$ROOT = dirname(dirname(dirname(__FILE__)))
Todo:
Is there a better way?
Definition at line 31 of file ctlr.php.
Referenced by System\AddFilter(), System\AddNotifierUser(), System\DelFilter(), System\DelNotifierUser(), System\DisableNotifierSSLVerifyPeer(), System\EnableNotifierSSLVerifyPeer(), Ctlrlogs\FormatLogCols(), Wuilogs\FormatLogCols(), Model\SetDefaultLocale(), Model\SetForceHTTPs(), Model\SetHelpBox(), Model\SetLogLevel(), Model\SetMaxAnchorNesting(), Model\SetMaxFileSizeToProcess(), System\SetNotifierAPIKey(), System\SetNotifierHost(), System\SetNotifierTimeout(), System\SetNotifyLevel(), Model\SetPfctlTimeout(), Model\SetReloadRate(), Model\SetSessionTimeout(), Model\SetStatusCheckInterval(), and Model\SetUseSSH().
$SRC_ROOT
$SRC_ROOT = dirname(dirname(__FILE__))
Definition at line 32 of file ctlr.php.
Referenced by System\AutoConfig(), View\Controller(), and Symon\RenderLayout().
$ValidateArgs
$ValidateArgs = TRUE
Definition at line 55 of file ctlr.php.
__pad0__
out __pad0__
Definition at line 101 of file ctlr.php.
else
if ($encoded !==NULL) else
Initial value:
{
    ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, 'Failed encoding output, error, and retval: '.print_r($msg, TRUE))
Definition at line 111 of file ctlr.php.
if
if (! array_key_exists $View, $ModelFiles) = 0
Definition at line 79 of file ctlr.php.