PF Firewall: src/View/system/dashboard.php File Reference
dashboard.php File Reference
Functions
foreach($ServiceStatus as $Module=> $StatusArray) DisplayModuleStatus ($Module, $DisplayDashboardExtrasFunc=FALSE)
Variables
$SavedMenu = $Menu
$SavedLogConf = $LogConf
$View = new System()
$Menu = $SavedMenu
$LogConf = $SavedLogConf
$TopMenu = 'info'
$Submenu = 'dashboard'
$LastDashboardInterval = '10min'
if(filter_has_var(INPUT_GET, 'interval')) else if(isset($_SESSION['system']['DashboardInterval'])) $_SESSION ['system']['DashboardInterval'] = $LastDashboardInterval
$IntervalChanged = 0
if($StatusCheckInterval !==$DashboardIntervals2Seconds[$LastDashboardInterval]) $ServiceStatus = array()
if($View->Controller($Output, 'GetServiceStatus', 1, $LastDashboardInterval, $IntervalChanged)) $ModuleNames
$SubmenuNames
$ShowDataRangeSelector = TRUE
$Reload = TRUE
$Critical = 0
$Error = 0
$Warning = 0
vertical align
Function Documentation
DisplayModuleStatus()
foreach($ServiceStatus as $Module=> $StatusArray) DisplayModuleStatus ($Module, $DisplayDashboardExtrasFunc = FALSE)
Definition at line 88 of file dashboard.php.
{
    global $ModelsToStat, $ServiceStatus, $ModuleNames, $SubmenuNames, $Status2Images, $StatusTitles, $IMG_PATH;
    if (array_key_exists($Module, $ModuleNames)) {
        $ModuleName= $ModuleNames[$Module];
    } else {
        $ModuleName= $Module;
    }
    if (array_key_exists($Module, $SubmenuNames)) {
        $SubmenuName= $SubmenuNames[$Module];
    } else {
        $SubmenuName= 'info';
    }
    $Caption = $ModelsToStat[$Module];
    $RunStatus= $ServiceStatus[$Module]['Status'];
    $ErrorStatus= $ServiceStatus[$Module]['ErrorStatus'];
    $StatusImage= $Status2Images[$RunStatus];
    $ErrorStatusImage= $Status2Images[$ErrorStatus];
    $Critical= $ServiceStatus[$Module]['Critical'];
    $Error= $ServiceStatus[$Module]['Error'];
    $Warning= $ServiceStatus[$Module]['Warning'];
    $ErrorCounts= array();
    if ($Critical) {
        $ErrorCounts[]= _TITLE('Critical').': '.$Critical;
    }
    if ($Error) {
        $ErrorCounts[]= _TITLE('Error').': '.$Error;
    }
    if ($Warning) {
        $ErrorCounts[]= _TITLE('Warning').': '.$Warning;
    }
    $ErrorCountsStr= implode(', ', $ErrorCounts);
    ?>
    <tr>
        <td class="module">
            <a class="transparent" href="<?php echo "/$ModuleName/info.php?submenu=$SubmenuName" ?>">
            <div>
                <table>
                    <tr>
                        <td class="moduleimage">
                            <img src="<?php echo $IMG_PATH.$StatusImage ?>" name="<?php echo $RunStatus ?>" alt="<?php echo $RunStatus ?>" title="<?php echo $StatusTitles[$RunStatus] ?>" align="absmiddle">
                        </td>
                        <td class="moduleimage">
                            <img src="<?php echo $IMG_PATH.$ErrorStatusImage ?>" name="<?php echo $ErrorStatus ?>" alt="<?php echo $ErrorStatus ?>" title="<?php echo $StatusTitles[$ErrorStatus] ?>" align="absmiddle">
                        </td>
                        <td class="modulecaption">
                            <strong><?php echo _($Caption) ?></strong>
                        </td>
                        <td class="moduleerrorcounts">
                            <?php echo $ErrorCountsStr ?>
                        </td>
                    </tr>
                    <?php
                    if ($DisplayDashboardExtrasFunc) {
                        $DisplayDashboardExtrasFunc();
                    }
                    ?>
                </table>
            </div>
            </a>
        </td>
    </tr>
    <?php
}
References $Critical, $Error, $IMG_PATH, $ModelsToStat, $ModuleNames, $ServiceStatus, $Status2Images, $StatusTitles, $SubmenuNames, $Warning, _TITLE(), and align.
Variable Documentation
$_SESSION
if(filter_has_var(INPUT_GET, 'interval')) else if (isset($_SESSION[ 'system'][ 'DashboardInterval'])) $_SESSION[ 'system'][ 'DashboardInterval'] = $LastDashboardInterval
Definition at line 48 of file dashboard.php.
$Critical
$Critical = 0
Definition at line 79 of file dashboard.php.
Referenced by DisplayModuleStatus().
$Error
$Error = 0
Definition at line 80 of file dashboard.php.
Referenced by DisplayModuleStatus().
$IntervalChanged
$IntervalChanged = 0
Definition at line 50 of file dashboard.php.
$LastDashboardInterval
$LastDashboardInterval = '10min'
Definition at line 42 of file dashboard.php.
$LogConf
$LogConf = $SavedLogConf
Definition at line 37 of file dashboard.php.
$Menu
$Menu = $SavedMenu
Definition at line 36 of file dashboard.php.
$ModuleNames
if ($View->Controller($Output, 'GetServiceStatus', 1, $LastDashboardInterval, $IntervalChanged)) $ModuleNames
Initial value:
= array(
    'symon' => 'monitoring',
    'symux' => 'monitoring',
    'collectd' => 'monitoring',
    )
Definition at line 62 of file dashboard.php.
Referenced by DisplayModuleStatus().
$Reload
$Reload = TRUE
Definition at line 76 of file dashboard.php.
$SavedLogConf
$SavedLogConf = $LogConf
Definition at line 25 of file dashboard.php.
$SavedMenu
$SavedMenu = $Menu
Definition at line 24 of file dashboard.php.
$ServiceStatus
if ($StatusCheckInterval !==$DashboardIntervals2Seconds[ $LastDashboardInterval]) $ServiceStatus = array()
Definition at line 55 of file dashboard.php.
Referenced by BuildFields(), DisplayModuleStatus(), FilterKeywords(), FilterLogLevels(), and FilterPreviousLogs().
$ShowDataRangeSelector
$ShowDataRangeSelector = TRUE
Definition at line 74 of file dashboard.php.
$Submenu
$Submenu = 'dashboard'
Definition at line 40 of file dashboard.php.
$SubmenuNames
$SubmenuNames
Initial value:
= array(
    'system' => 'system',
    'pf' => 'pf',
    'dhcpd' => 'dhcpd',
    )
Definition at line 68 of file dashboard.php.
Referenced by DisplayModuleStatus().
$TopMenu
$TopMenu = 'info'
Definition at line 39 of file dashboard.php.
$View
$View = new System()
Definition at line 35 of file dashboard.php.
$Warning
$Warning = 0
Definition at line 81 of file dashboard.php.
Referenced by DisplayModuleStatus().
align
vertical align
Definition at line 246 of file dashboard.php.
Referenced by DisplayModuleStatus(), and PrintNVPs().