PF Firewall: src/lib/defs.php File Reference
defs.php File Reference
Common variables, arrays, and constants.
Functions
_STATS ($str)
For classifying gettext strings into files.
_TITLE ($str)
For classifying gettext strings into files.
Variables
const VERSION '7.3'
Project version.
$ROOT = dirname(dirname(dirname(__FILE__)))
$SRC_ROOT = dirname(dirname(__FILE__))
$VIEW_PATH = $SRC_ROOT . '/View'
$MODEL_PATH = $SRC_ROOT . '/Model'
const PFFWDIR '/var/log/pffw'
$LOG_PRIOS
Syslog priority strings.
$ADMIN = array('admin')
Superuser.
$USER = array('user')
Unprivileged user who can modify any configuration.
$ALL_USERS = array_merge($ADMIN, $USER)
All valid users.
$LOCALES
Locale definitions used by both View and Controller.
$MonthNames
Used in translating months from number to string.
$MonthNumbers
Used in translating months from string to number.
$Re_MonthNames = implode('|', array_values($MonthNames))
$MonthNumbersNoLeadingZeros = array_map(function ($str) { return $str + 0; }, array_keys($MonthNames))
$Re_MonthNumbersNoLeadingZeros = implode('|', $MonthNumbersNoLeadingZeros)
$DaysNoLeadingZeros
$Re_DaysNoLeadingZeros = implode('|', $DaysNoLeadingZeros)
$WeekDays = array('Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun')
$Re_WeekDays = implode('|', $WeekDays)
$TCPDUMP = 'exec 2>/dev/null; /usr/sbin/tcpdump -nettt -r'
General tcpdump command used everywhere.
const UINT_0_2 '[0-2]'
Type definitions for config settings as PREs.
const STR_on_off 'on|off'
const STR_On_Off 'On|Off'
const STR_SING_QUOTED '\'[^\']*\''
const STR_yes_no 'yes|no'
const UINT '[0-9]+'
const INT_M1_0_UP '-1|[0-9]+'
const UINT_0_1 '0|1'
const INT_M1_0_3 '-1|[0-3]'
const UINT_0_3 '[0-3]'
const UINT_1_4 '[0-4]'
const IP '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}'
const IPorNET '(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})|(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\/\d{1,2})'
const PORT '[0-9]+'
const FLOAT '[0-9]+|([0-9]+\.[0-9]+)'
const CHAR '.'
$Re_Ip = '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}'
Common regexps.
$Re_Net = "$Re_Ip\/\d{1,2}"
$Re_IpPort = '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}:\d{1,5}'
$preIPOctet = '(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])'
$preIPRange = '(\d|[1-2]\d|3[0-2])'
$preIP = "$preIPOctet\\.$preIPOctet\\.$preIPOctet\\.$preIPOctet"
$preNet = "$preIP\/$preIPRange"
$preMacByte = '[\da-f]{2}'
$preMac = "$preMacByte\:$preMacByte\:$preMacByte\:$preMacByte\:$preMacByte\:$preMacByte"
$preIfName = '\w+\d+'
$StatsConf
Master statistics configuration.
$ModelsToStat
Models to get statuses.
$DashboardIntervals2Seconds
$PF_CONFIG_PATH = '/etc/pfre'
$TMP_PATH = '/var/log/pffw/tmp'
$TEST_DIR_PATH = ''
$TEST_DIR_SRC = '/pffw'
$INSTALL_USER = 'root'
Detailed Description
Common variables, arrays, and constants.
Definition in file defs.php.
Function Documentation
_STATS()
_STATS ($str)
For classifying gettext strings into files.
Definition at line 163 of file defs.php.
{
    return _($str);
}
Referenced by View\PrintStats().
_TITLE()
_TITLE ($str)
For classifying gettext strings into files.
Attention
Moved here to satisfy $ModelsToStat below
Definition at line 402 of file defs.php.
{
    return _($str);
}
Referenced by Dhcpd\__construct(), Dnsmasq\__construct(), Ftpproxy\__construct(), Httpd\__construct(), Monitoring\__construct(), Openssh\__construct(), Pf\__construct(), System\__construct(), Rule\dispHead(), AfTo\display(), Anchor\display(), Antispoof\display(), DivertPacket\display(), DivertTo\display(), FilterBase\display(), NatBase\display(), Queue\display(), Route\display(), Scrub\display(), Table\display(), Dhcpd\DisplayDashboardExtras(), Openssh\DisplayDashboardExtras(), Pf\DisplayDashboardExtras(), DisplayModuleStatus(), Macro\dispMacro(), AfTo\edit(), Anchor\edit(), Antispoof\edit(), Blank\edit(), Comment\edit(), DivertPacket\edit(), DivertTo\edit(), Filter\edit(), LoadAnchor\edit(), Macro\edit(), NatBase\edit(), NatTo\edit(), Queue\edit(), Route\edit(), Scrub\edit(), Table\edit(), Filter\editAction(), Timeout\editAdaptiveTimeouts(), Rule\editAf(), Queue\editBandwidth(), Filter\editBlockOption(), Option\editBlockPolicy(), Rule\editComment(), Option\editDebug(), FilterBase\editDirection(), FilterBase\editFilterHead(), FilterBase\editFilterOpts(), Option\editFingerprints(), Table\editFlags(), Timeout\editFragment(), Rule\editHead(), Option\editHostid(), Timeout\editIcmpTimeouts(), State\editIfBinding(), _Include\editInclude(), Anchor\editInlineRules(), Filter\editInterface(), Timeout\editInterval(), Limit\editLimit(), Rule\editLog(), Option\editLogInterface(), NatBase\editNat(), Option\editOptimization(), Timeout\editOtherTimeouts(), State\editOverload(), Filter\editPoolType(), FilterBase\editQueue(), Option\editReassemble(), FilterBase\editReceivedOn(), AfTo\editRedirAf(), Route\editRouteType(), Option\editRulesetOptimization(), Scrub\editScrubOptions(), Option\editSelectOption(), Option\editSkip(), State\editSourceTrack(), Timeout\editSrcTrack(), State\editState(), FilterBase\editStateFilter(), Option\editStatePolicy(), Option\editSyncookies(), FilterBase\editTagged(), Timeout\editTcpTimeouts(), Timeout\editUdpTimeouts(), Table\editValues(), Model\GetStatus(), PrintDateTimeForm(), PrintHelpWindow(), PrintHGraph(), PrintHostsForm(), PrintLiveLogHeaderForm(), PrintLogFileChooser(), PrintLogHeaderForm(), PrintNVPsVGraph(), View\PrintProcessTable(), View\PrintStatusForm(), PrintVGraph(), Layout\render(), SetRefreshInterval(), SetSubmenu(), and UpdateLogsPageSessionVars().
Variable Documentation
$ADMIN
$ADMIN = array('admin')
Superuser.
Definition at line 49 of file defs.php.
Referenced by View\PrintStatusForm().
$ALL_USERS
$ALL_USERS = array_merge($ADMIN, $USER)
All valid users.
Definition at line 53 of file defs.php.
Referenced by Authentication().
$DashboardIntervals2Seconds
$DashboardIntervals2Seconds
Initial value:
= array(
    '1min' => 60,
    '5min' => 300,
    '10min' => 600,
    '30min' => 1800,
    '1hour' => 3600,
    '12hour' => 43200,
    '1day' => 86400,
    '1week' => 604800,
    '1month' => 2592000,
    '6month' => 15552000,
    )
Definition at line 422 of file defs.php.
Referenced by Model\GetServiceStatus().
$DaysNoLeadingZeros
$DaysNoLeadingZeros
Initial value:
= array(
    '1', '2', '3', '4', '5', '6', '7', '8', '9', '10',
    '11', '12', '13', '14', '15', '16', '17', '18', '19', '20',
    '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31'
    )
Definition at line 111 of file defs.php.
$INSTALL_USER
$INSTALL_USER = 'root'
Definition at line 441 of file defs.php.
$LOCALES
$LOCALES
Initial value:
= array(
    'en_EN' => array(
        'Name' => _('English'),
        'Codeset' => 'UTF-8'
        ),
    'tr_TR' => array(
        'Name' => _('Turkish'),
        'Codeset' => 'UTF-8'
        ),
    )
Locale definitions used by both View and Controller.
It is recommended that all translations use UTF-8 codeset.
Parameters
string Name Title string
string Codeset Locale codeset
Definition at line 63 of file defs.php.
Referenced by HTMLHeader(), and ValidateCommand().
$LOG_PRIOS
$LOG_PRIOS
Initial value:
= array(
    'LOG_EMERG',
    'LOG_ALERT',
    'LOG_CRIT',
    'LOG_ERR',
    'LOG_WARNING',
    'LOG_NOTICE',
    'LOG_INFO',
    'LOG_DEBUG',
    )
Syslog priority strings.
Definition at line 37 of file defs.php.
Referenced by ctlr_syslog(), and wui_syslog().
$MODEL_PATH
$MODEL_PATH = $SRC_ROOT . '/Model'
Definition at line 32 of file defs.php.
Referenced by System\GenerateSSLKeyPair(), System\GetLogsConfig(), Model\GetServiceStatus(), and System\SetLogsConfig().
$ModelsToStat
$ModelsToStat
Initial value:
= array(
    'system' => _TITLE('System'),
    'pf' => _TITLE('Packet Filter'),
    'dhcpd' => _TITLE('DHCP Server'),
    'dnsmasq' => _TITLE('DNS Forwarder'),
    'openssh' => _TITLE('OpenSSH'),
    'ftp-proxy' => _TITLE('FTP Proxy'),
    'httpd' => _TITLE('Web User Interface'),
    'symon' => _TITLE('Symon'),
    'symux' => _TITLE('Symux'),
    'collectd' => _TITLE('Collectd'),
    )
Models to get statuses.
Todo:
Code reuse issue: Titles are already available as class vars
Definition at line 409 of file defs.php.
Referenced by DisplayModuleStatus(), Model\GetServiceStatus(), and Model\GetStatus().
$MonthNames
$MonthNames
Initial value:
= array(
    '01' => 'Jan',
    '02' => 'Feb',
    '03' => 'Mar',
    '04' => 'Apr',
    '05' => 'May',
    '06' => 'Jun',
    '07' => 'Jul',
    '08' => 'Aug',
    '09' => 'Sep',
    '10' => 'Oct',
    '11' => 'Nov',
    '12' => 'Dec',
    )
Used in translating months from number to string.
Definition at line 75 of file defs.php.
Referenced by View\FormatDate(), Pf\FormatDate(), Model\formatDateHourRegexp(), Model\formatDateHourRegexpDayLeadingZero(), Model\formatDateHourRegexpWeekDays(), Model\GetDateRegexp(), and Pf\GetDateRegexp().
$MonthNumbers
$MonthNumbers
Initial value:
= array(
    'Jan' => '01',
    'Feb' => '02',
    'Mar' => '03',
    'Apr' => '04',
    'May' => '05',
    'Jun' => '06',
    'Jul' => '07',
    'Aug' => '08',
    'Sep' => '09',
    'Oct' => '10',
    'Nov' => '11',
    'Dec' => '12',
    )
Used in translating months from string to number.
Definition at line 91 of file defs.php.
Referenced by View\FormatDateArray().
$MonthNumbersNoLeadingZeros
$MonthNumbersNoLeadingZeros = array_map(function ($str) { return $str + 0; }, array_keys($MonthNames))
Definition at line 108 of file defs.php.
$PF_CONFIG_PATH
$PF_CONFIG_PATH = '/etc/pfre'
Definition at line 435 of file defs.php.
Referenced by _Include\editInclude(), and IsFilePath().
$preIfName
$preIfName = '\w+\d+'
Definition at line 160 of file defs.php.
Referenced by Dhcpd\_getArpTable().
$preIP
$preIP = "$preIPOctet\\.$preIPOctet\\.$preIPOctet\\.$preIPOctet"
Definition at line 154 of file defs.php.
Referenced by Dhcpd\_getArpTable(), IsHost(), IsIPAddress(), and IsIPRange().
$preIPOctet
$preIPOctet = '(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])'
Todo:
$num and $range need full testing. Define $port.
Definition at line 152 of file defs.php.
$preIPRange
$preIPRange = '(\d|[1-2]\d|3[0-2])'
Definition at line 153 of file defs.php.
Referenced by IsIPRange().
$preMac
$preMac = "$preMacByte\:$preMacByte\:$preMacByte\:$preMacByte\:$preMacByte\:$preMacByte"
Definition at line 158 of file defs.php.
Referenced by Dhcpd\_getArpTable().
$preMacByte
$preMacByte = '[\da-f]{2}'
Definition at line 157 of file defs.php.
$preNet
$preNet = "$preIP\/$preIPRange"
Definition at line 155 of file defs.php.
$Re_DaysNoLeadingZeros
$Re_DaysNoLeadingZeros = implode('|', $DaysNoLeadingZeros)
Definition at line 116 of file defs.php.
$Re_Ip
$Re_Ip = '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}'
Common regexps.
Todo:
Find a proper regexp for IPv4 addresses, this is too general.
Definition at line 148 of file defs.php.
Referenced by System\_getDynamicGateway(), Dhcpd\_getLeases(), ComputeIfDefs(), System\GetHosts(), Dhcpd\GetRange(), Ftpproxy\ParseLogLine(), Fwlogs\ParseLogLine(), Httpdlogs\ParseLogLine(), Openssh\ParseLogLine(), Pf\ParseLogLine(), Dhcpd\SetDhcpdConf(), System\SetIf(), System\SetNameServer(), Dhcpd\SetOption(), and Dhcpd\SetRange().
$Re_IpPort
$Re_IpPort = '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}:\d{1,5}'
Definition at line 150 of file defs.php.
$Re_MonthNames
$Re_MonthNames = implode('|', array_values($MonthNames))
Definition at line 106 of file defs.php.
Referenced by Model\formatDateHourRegexp(), Model\formatDateHourRegexpDayLeadingZero(), and Model\formatDateHourRegexpWeekDays().
$Re_MonthNumbersNoLeadingZeros
$Re_MonthNumbersNoLeadingZeros = implode('|', $MonthNumbersNoLeadingZeros)
Definition at line 109 of file defs.php.
$Re_Net
$Re_Net = "$Re_Ip\/\d{1,2}"
Definition at line 149 of file defs.php.
$Re_WeekDays
$Re_WeekDays = implode('|', $WeekDays)
Definition at line 119 of file defs.php.
Referenced by Model\formatDateHourRegexpWeekDays().
$ROOT
$ROOT = dirname(dirname(dirname(__FILE__)))
Definition at line 28 of file defs.php.
$SRC_ROOT
$SRC_ROOT = dirname(dirname(__FILE__))
Definition at line 29 of file defs.php.
$StatsConf
$StatsConf
Master statistics configuration.
This array provides stats configuration parameters needed for each module. Detailed behaviour of each module is defined by the settings in this array.
Parameters
Stats Parent field in configuration details used on statistics pages.
Stats>Total Mandatory sub-field for each Stats field. Configures the the general settings for the basic stats for the module.
Stats>Total>Title Title to display on top of the graph.
Stats>Total>Cmd Command line to get log lines. Usually to get all lines.
Stats>Total>Needle To get only those lines that contain the Needle text among the lines obtained by Stats>Total>Cmd.
Stats>Total>Color The color of the bars on the graph.
Stats>Total>NVPs Name-Value-Pairs to print at the bottom of the graph. Usually top 5 of some of the more important stats. Displayed in 2 columns.
Stats>Total>BriefStats Statistics (parsed field names) to collect as BriefStats. Top 100 of collected data are shown on the left of General statistics page.
Stats>Total>Counters Statistics to collect and show as a graph over total data. The difference between these counters and Stats><StatName> is that these are collected using the command line for the Total stats. So there is no separate Cmd field. Counters has one extra field, Divisor, which is used to divide the total count. Usually need to convert bytes to kilobytes.
Stats><StatName> Custom statistics to be collected. The data for these graphs are collected using the Cmd and Needle fields. Stats>Total>Counters could have been merged with this one perhaps. The sub-fields for these custom stats is the same as the Total field described above.
Definition at line 202 of file defs.php.
Referenced by Model\CountDiffLogLines(), Model\GetProcStatLines(), Model\GetStatsLogLines(), and Model\UpdateStats().
$TCPDUMP
$TCPDUMP = 'exec 2>/dev/null; /usr/sbin/tcpdump -nettt -r'
General tcpdump command used everywhere.
Todo:
All system binaries called should be defined like this.
Attention
Redirect stderr to /dev/null to hush tcpdump warning: "tcpdump: WARNING: snaplen raised from 116 to 160". Otherwise that warning goes in front of the data.
Definition at line 125 of file defs.php.
Referenced by Pf\__construct(), Pf\_getFileLineCount(), Pf\_getLiveLogs(), and Pf\GetLogs().
$TEST_DIR_PATH
$TEST_DIR_PATH = ''
Definition at line 438 of file defs.php.
Referenced by IsFilePath().
$TEST_DIR_SRC
$TEST_DIR_SRC = '/pffw'
Attention
Necessary to set to '/pffw' instead of '' to fix $ROOT . $TEST_DIR_SRC in model.php
Definition at line 440 of file defs.php.
Referenced by System\AddFilter(), System\AddNotifierUser(), System\DelFilter(), System\DelNotifierUser(), System\DisableNotifierSSLVerifyPeer(), System\EnableNotifierSSLVerifyPeer(), Model\SetDefaultLocale(), Model\SetForceHTTPs(), Model\SetHelpBox(), Model\SetLogLevel(), Model\SetMaxAnchorNesting(), Model\SetMaxFileSizeToProcess(), System\SetNotifierAPIKey(), System\SetNotifierHost(), System\SetNotifierTimeout(), System\SetNotifyLevel(), Model\SetPfctlTimeout(), Model\SetReloadRate(), Model\SetSessionTimeout(), Model\SetStatusCheckInterval(), and Model\SetUseSSH().
$TMP_PATH
$TMP_PATH = '/var/log/pffw/tmp'
Definition at line 436 of file defs.php.
Referenced by IsFilePath().
$USER
$USER = array('user')
Unprivileged user who can modify any configuration.
Definition at line 51 of file defs.php.
$VIEW_PATH
$VIEW_PATH = $SRC_ROOT . '/View'
Definition at line 31 of file defs.php.
$WeekDays
$WeekDays = array('Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun')
Definition at line 118 of file defs.php.
CHAR
const CHAR '.'
Definition at line 144 of file defs.php.
FLOAT
const FLOAT '[0-9]+|([0-9]+\.[0-9]+)'
Definition at line 143 of file defs.php.
INT_M1_0_3
const INT_M1_0_3 '-1|[0-3]'
Definition at line 137 of file defs.php.
INT_M1_0_UP
const INT_M1_0_UP '-1|[0-9]+'
Definition at line 135 of file defs.php.
IP
const IP '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}'
Definition at line 140 of file defs.php.
IPorNET
const IPorNET '(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})|(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\/\d{1,2})'
Definition at line 141 of file defs.php.
PFFWDIR
const PFFWDIR '/var/log/pffw'
Definition at line 34 of file defs.php.
Referenced by Model\__construct(), FilterPreviousLogs(), Model\GetServiceStatus(), Model\GetStatsFileName(), and Model\PrepareFileForDownload().
PORT
const PORT '[0-9]+'
Definition at line 142 of file defs.php.
STR_on_off
const STR_on_off 'on|off'
Definition at line 130 of file defs.php.
Referenced by Model\getValidValues(), and PrintNVPForm().
STR_On_Off
const STR_On_Off 'On|Off'
Definition at line 131 of file defs.php.
Referenced by Model\getValidValues(), and PrintNVPForm().
STR_SING_QUOTED
const STR_SING_QUOTED '\'[^\']*\''
Definition at line 132 of file defs.php.
STR_yes_no
const STR_yes_no 'yes|no'
Definition at line 133 of file defs.php.
Referenced by Model\getValidValues(), and PrintNVPForm().
UINT
const UINT '[0-9]+'
Definition at line 134 of file defs.php.
UINT_0_1
const UINT_0_1 '0|1'
Definition at line 136 of file defs.php.
UINT_0_2
const UINT_0_2 '[0-2]'
Type definitions for config settings as PREs.
Todo:
Fix leading 0's problem(s)
Definition at line 129 of file defs.php.
UINT_0_3
const UINT_0_3 '[0-3]'
Definition at line 138 of file defs.php.
UINT_1_4
const UINT_1_4 '[0-4]'
Definition at line 139 of file defs.php.
VERSION
const VERSION '7.3'
Project version.
Definition at line 26 of file defs.php.