PF Firewall: src/View/lib/phpseclib/Crypt/DES.php File Reference
DES.php File Reference
Data Structures
class Crypt_DES
Namespaces
namespace Crypt_DES
#-
Variables
const CRYPT_DES_ENCRYPT (!class_exists('Crypt_Base')) 0
Include Crypt_Base.
const CRYPT_DES_DECRYPT 1
Contains $keys[CRYPT_DES_DECRYPT].
const CRYPT_DES_MODE_CTR CRYPT_MODE_CTR
#-
const CRYPT_DES_MODE_ECB CRYPT_MODE_ECB
Encrypt / decrypt using the Electronic Code Book mode.
const CRYPT_DES_MODE_CBC CRYPT_MODE_CBC
Encrypt / decrypt using the Code Book Chaining mode.
const CRYPT_DES_MODE_CFB CRYPT_MODE_CFB
Encrypt / decrypt using the Cipher Feedback mode.
const CRYPT_DES_MODE_OFB CRYPT_MODE_OFB
Encrypt / decrypt using the Cipher Feedback mode.
Variable Documentation
CRYPT_DES_DECRYPT
const CRYPT_DES_DECRYPT 1
Contains $keys[CRYPT_DES_DECRYPT].
Definition at line 82 of file DES.php.
Referenced by Crypt_DES\_decryptBlock(), Crypt_DES\_setupInlineCrypt(), and Crypt_DES\_setupKey().
CRYPT_DES_ENCRYPT
const CRYPT_DES_ENCRYPT(!class_exists('Crypt_Base')) (! class_exists 'Crypt_Base') 0
Include Crypt_Base.
Base cipher class #+ @access private
See also
self::_setupKey()
self::_processBlock() Contains $keys[CRYPT_DES_ENCRYPT]
Definition at line 78 of file DES.php.
Referenced by Crypt_DES\_encryptBlock(), Crypt_DES\_setupInlineCrypt(), and Crypt_DES\_setupKey().
CRYPT_DES_MODE_CBC
const CRYPT_DES_MODE_CBC CRYPT_MODE_CBC
Encrypt / decrypt using the Code Book Chaining mode.
http://en.wikipedia.org/wiki/Block_cipher_modes_of_operation#Cipher-block_chaining_.28CBC.29
Definition at line 109 of file DES.php.
CRYPT_DES_MODE_CFB
const CRYPT_DES_MODE_CFB CRYPT_MODE_CFB
Encrypt / decrypt using the Cipher Feedback mode.
http://en.wikipedia.org/wiki/Block_cipher_modes_of_operation#Cipher_feedback_.28CFB.29
Definition at line 115 of file DES.php.
Referenced by Crypt_RSA\_parseKey().
CRYPT_DES_MODE_CTR
const CRYPT_DES_MODE_CTR CRYPT_MODE_CTR
#-
#+ @access public
See also
self::encrypt()
self::decrypt() Encrypt / decrypt using the Counter mode.
Set to -1 since that's what Crypt/Random.php uses to index the CTR mode.
http://en.wikipedia.org/wiki/Block_cipher_modes_of_operation#Counter_.28CTR.29
Definition at line 97 of file DES.php.
Referenced by Net_SSH2\_encryption_algorithm_to_crypt_instance().
CRYPT_DES_MODE_ECB
const CRYPT_DES_MODE_ECB CRYPT_MODE_ECB
Encrypt / decrypt using the Electronic Code Book mode.
http://en.wikipedia.org/wiki/Block_cipher_modes_of_operation#Electronic_codebook_.28ECB.29
Definition at line 103 of file DES.php.
CRYPT_DES_MODE_OFB
const CRYPT_DES_MODE_OFB CRYPT_MODE_OFB
Encrypt / decrypt using the Cipher Feedback mode.
http://en.wikipedia.org/wiki/Block_cipher_modes_of_operation#Output_feedback_.28OFB.29
Definition at line 121 of file DES.php.