PF Firewall: src/Installer/install.php File Reference
install.php File Reference
Configuration script used both during installation and by the web interface.
Variables
$ROOT = dirname(dirname(__FILE__))
$VIEW_PATH = $ROOT.'/View/'
$LOG_LEVEL = LOG_DEBUG
Log all during installation.
$Auto = FALSE
if (isset($_SERVER[ 'argv'][1]) &&$_SERVER[ 'argv'][1]=='-a')
$View = new View()
$View Model = 'system'
$UseSSH = FALSE
if($View->Controller($Output, 'GetConfig')) else
Detailed Description
Configuration script used both during installation and by the web interface.
Definition in file install.php.
Variable Documentation
$Auto
$Auto = FALSE
Definition at line 49 of file install.php.
$LOG_LEVEL
$LOG_LEVEL = LOG_DEBUG
Log all during installation.
Definition at line 43 of file install.php.
Referenced by ctlr_syslog(), Model\IsInlineAnchor(), and wui_syslog().
$ROOT
$ROOT = dirname(dirname(__FILE__))
Definition at line 38 of file install.php.
$UseSSH
$UseSSH = FALSE
Attention
This script is executed on the command line, so we don't have access to cookie and session vars here.
Definition at line 62 of file install.php.
Referenced by View\Controller().
$View
$View = new View()
Definition at line 57 of file install.php.
Referenced by ApplyConfig(), Authentication(), RuleSet\comment(), ConfigMFS(), CreateUsers(), _Include\editInclude(), FilterBase\editQueue(), EnableHostap(), ExpandArgs(), FillGraphDataRange(), FillNVPs(), GenerateSSLKeyPair(), Session\getform(), GetHwInfo(), GetLogFile(), RuleSet\load(), RuleSet\parse(), PrintDHCPInterfaceForm(), PrintDHCPOptionForm(), PrintDHCPRangeOptionForm(), PrintHGraph(), PrintHostsForm(), PrintLiveLogHeaderForm(), PrintLogCols(), PrintLogFileChooser(), PrintNVPForm(), PrintNVPs(), PrintNVPsVGraph(), PrintVGraph(), ProcessNavigationButtons(), ProcessStartLine(), RuleSet\separate(), SetGraphData(), SetRefreshInterval(), SetSubmenu(), RuleSet\setupEditSession(), RuleSet\test(), RuleSet\uncomment(), UpdateLogsPageSessionVars(), and ValidateCommand().
$VIEW_PATH
$VIEW_PATH = $ROOT.'/View/'
Definition at line 39 of file install.php.
Referenced by Net_SSH2\__construct(), Crypt_RSA\__construct(), File_ASN1\__construct(), File_X509\__construct(), Crypt_RSA\_convertPrivateKey(), Net_SSH2\_encryption_algorithm_to_crypt_instance(), Model\_getReloadRate(), Crypt_RSA\_parseKey(), Crypt_Hash\_sha512(), File_X509\_validateSignature(), File_X509\computeKeyIdentifier(), File_X509\getDN(), File_X509\getPublicKey(), Net_SSH2\getServerPublicHostKey(), System\InitGraphs(), File_X509\loadCSR(), File_X509\loadSPKAC(), System_SSH_Agent\requestIdentities(), Crypt_Base\setPassword(), File_X509\sign(), and ValidateCommand().
else
if ($View->Controller($Output, 'GetConfig')) else
Initial value:
{
    wui_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, 'Cannot get configuration')
Definition at line 87 of file install.php.
if
if(isset($_SERVER['argv'][1]) && $_SERVER['argv'][1]=='-a') (isset($_SERVER['argv'][1]) && $_SERVER[ 'argv'][1] = = '-a')
Definition at line 50 of file install.php.
Model
$View Model = 'system'
Definition at line 58 of file install.php.