PF Firewall: src/lib/lib.php File Reference
lib.php File Reference
Project-wide common functions.
Functions
IsFilePath ($filepath)
Validates the given file path.
FlattenArray (&$array)
Converts an array to a simple value.
Escape ($str, $chars, $no_double_escapes=TRUE)
Escapes chars.
AddValueCreateKey (&$data, $name, $value)
Detailed Description
Project-wide common functions.
Definition in file lib.php.
Function Documentation
AddValueCreateKey()
AddValueCreateKey (& $data, $name, $value)
Definition at line 96 of file lib.php.
{
    if (!isset($data[$name])) {
        $data[$name]= 0;
    }
    $data[$name]+= $value;
}
Referenced by Model\CollectMinuteStats(), Model\IncStats(), SumData(), and Model\UpdateStats().
Escape()
Escape ($str, $chars, $no_double_escapes = TRUE)
Escapes chars.
Prevents double escapes by default.
preg_quote() double escapes, thus is not suitable. It is not possible to make sure that strings contain no escapes, because this function is used over strings obtained from config files too, which we don't have any control over.
Example: $no_double_escapes as FALSE is used in the code to double escape the $ char.
Parameters
string $str String to process.
string $chars Chars to escape.
bool $no_double_escapes Whether to prevent double escapes.
Returns
string Escaped string.
First remove existing escapes
Definition at line 80 of file lib.php.
{
    if ($chars !== '') {
        $chars_array= str_split($chars);
        foreach ($chars_array as $char) {
            $esc_char= preg_quote($char, '/');
            if ($no_double_escapes) {
                $str= preg_replace("/\\\\$esc_char/", $char, $str);
            }
            $str= preg_replace("/$esc_char/", "\\\\$char", $str);
        }
    }
    return $str;
}
Referenced by Dhcpd\_getLeases(), System\DaemonizedRotateLogFile(), System\DisableServiceRcLocal(), System\EnableServiceRcLocal(), FilterKeywords(), View\getLogLineClass(), Model\GetNewsyslogConfig(), System\GetServiceStatRcLocal(), Model\SetNewsyslogConfig(), and Model\SetNVP().
FlattenArray()
FlattenArray (& $array)
Converts an array to a simple value.
Attention
Don't use 0 as key to fetch the last value; the last key index may not be 0.
Parameters
array $array Array to flatten.
Definition at line 57 of file lib.php.
{
    if (count($array) == 1) {
        $array= $array[key($array)];
    }
}
Referenced by Rule\inputDelValue(), and Rule\parseItem().
IsFilePath()
IsFilePath ($filepath)
Validates the given file path.
If we are not testing the controller, we should expect regular file paths. For example, _Include or LoadAnchor type of rules accept regular paths, not test ones.
Attention
? should never appear in regex patterns, this is better than using / or | chars.
Parameters
string $filepath File path to validate.
Returns
bool TRUE if valid.
Definition at line 36 of file lib.php.
{
    global $PF_CONFIG_PATH, $TMP_PATH, $TEST_DIR_PATH;
    return
        // pf configuration files
        preg_match("?^($TEST_DIR_PATH|)$PF_CONFIG_PATH/\w[\w.\-_]*$?", $filepath)
        || preg_match("?^($TEST_DIR_PATH|)/etc/\w[\w.\-_]*$?", $filepath)
        // Uploaded tmp files
        || preg_match("?^($TEST_DIR_PATH|)$TMP_PATH/\w[\w.\-_]*$?", $filepath)
        // Log files, statistics and uncompressed logs
        || preg_match('?^/var/log/\w[\w./\-_]*$?', $filepath);
}
References $PF_CONFIG_PATH, $TEST_DIR_PATH, and $TMP_PATH.