PF Firewall: src/View/lib/libauth.php File Reference
libauth.php File Reference
Authentication and related library functions.
Functions
wui_syslog ($prio, $file, $func, $line, $msg)
Wrapper for syslog().
LogUserOut ($reason='User logged out')
Logs user out by setting session USER var to loggedout.
Authentication ($passwd)
Authenticates session user with the password supplied.
HTMLHeader ($color='white', $reloadRate=0)
HTML Header.
SetSubmenu ($default)
Sets session submenu variable.
SetTopMenu ($view, $default='info')
Sets session topmenu variable.
Variables
$Domain = 'pffw'
Detailed Description
Authentication and related library functions.
Definition in file libauth.php.
Function Documentation
Authentication()
Authentication ($passwd)
Authenticates session user with the password supplied.
Passwords are never passed around plaintext, but are always encrypted.
In fact, passwords are double encrypted using:
sha1() right after the user types her password in
encrypt(1) while saving to the password file using chpass(1).
openssl_*() while saving as a cookie var.
Also, we always use SSH connections to execute all Controller commands.
Parameters
string $passwd SHA encrypted password.
Todo:
Should we reset everything else, other than USER and Timeout?
Definition at line 133 of file libauth.php.
{
    global $ALL_USERS, $SessionTimeout, $View;
    wui_syslog(LOG_DEBUG, __FILE__, __FUNCTION__, __LINE__, 'Login attempt');
    if (!in_array($_SESSION['USER'], $ALL_USERS)) {
        wui_syslog(LOG_NOTICE, __FILE__, __FUNCTION__, __LINE__, 'Not a valid user');
        // Throttle authentication failures
        exec('/bin/sleep 5');
        LogUserOut('Authentication failed');
    }
    if (!$View->CheckAuthentication($_SESSION['USER'], $passwd)) {
        wui_syslog(LOG_NOTICE, __FILE__, __FUNCTION__, __LINE__, 'Password mismatch');
        // Throttle authentication failures
        exec('/bin/sleep 5');
        LogUserOut('Authentication failed');
    }
    wui_syslog(LOG_DEBUG, __FILE__, __FUNCTION__, __LINE__, 'Authentication succeeded');
    // Encrypt the password to save as a cookie var.
    $random= exec('(dmesg; sysctl; route -n show; df; ifconfig -A; hostname) | cksum -q -a sha256 -');
    $cryptKey= pack('H*', $random);
    $iv_size= openssl_cipher_iv_length('AES-256-CBC');
    $iv= openssl_random_pseudo_bytes($iv_size);
    $ciphertext= openssl_encrypt($passwd, 'AES-256-CBC', $cryptKey, OPENSSL_RAW_DATA, $iv);
    if (!$ciphertext) {
        wui_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, 'openssl_encrypt failed: '.openssl_error_string());
        exit;
    }
    $ciphertext= $iv.$ciphertext;
    $ciphertext_base64= base64_encode($ciphertext);
    // Save password to the cookie
    setcookie('passwd', $ciphertext_base64);
    // Save key to the session, so we can decrypt the password from the cookie later on to log in to the SSH server
    $_SESSION['cryptKey']= $cryptKey;
    // Update session timeout now, otherwise in the worst case scenario, vars.php may log user out on very close session timeout
    $_SESSION['Timeout']= time() + $SessionTimeout;
    // Reset the pf session if the user changes
    if (isset($_SESSION['PREVIOUS_USER']) && $_SESSION['PREVIOUS_USER'] !== $_SESSION['USER']) {
        unset($_SESSION['pf']);
    }
    header('Location: /system/info.php?submenu=dashboard');
    exit;
}
References $_SESSION, $ALL_USERS, $SessionTimeout, $View, exit, LogUserOut(), and wui_syslog().
HTMLHeader()
HTMLHeader ($color = 'white', $reloadRate = 0)
HTML Header.
Parameters
string $color Page background, Login page uses gray.
int $reloadrate Page reload rate, defaults to 0 (no reload)
Definition at line 196 of file libauth.php.
{
    global $LOCALES;
?>
<!DOCTYPE html>
<html>
    <head>
        <title><?php echo _MENU('PF Firewall') ?></title>
        <meta http-equiv="content-type" content="text/html; charset=<?php echo $LOCALES[$_SESSION['Locale']]['Codeset'] ?>" />
        <meta name="description" content="PF Firewall" />
        <meta name="author" content="Soner Tari"/>
        <meta name="keywords" content="PF, Firewall, :)" />
        <link rel="stylesheet" href="../pffw.css" type="text/css" media="screen" />
        <?php
        if ($reloadRate !== 0) {
            ?>
            <meta http-equiv="refresh" content="<?php echo $reloadRate ?>" />
            <?php
        }
        ?>
    </head>
    <body style="background: <?php echo $color ?>">
<?php
}
References $LOCALES, and _MENU().
LogUserOut()
LogUserOut ($reason = 'User logged out')
Logs user out by setting session USER var to loggedout.
Redirects to the main index page, which asks for re-authentication.
Parameters
string $reason Reason for log message.
Warning
Relogin page should not time out
Definition at line 103 of file libauth.php.
{
    wui_syslog(LOG_INFO, __FILE__, __FUNCTION__, __LINE__, $reason);
    // Save USER to check if the user changes in the next session
    $_SESSION['PREVIOUS_USER']= $_SESSION['USER'];
    $_SESSION['USER']= 'loggedout';
    $_SESSION['Timeout']= -1;
    session_write_close();
    header('Location: /index.php');
    exit;
}
References $_SESSION, exit, and wui_syslog().
Referenced by Authentication().
SetSubmenu()
SetSubmenu ($default)
Sets session submenu variable.
Parameters
string $default Default submenu selected
Returns
string Selected submenu
Definition at line 227 of file libauth.php.
{
    global $View, $Menu, $TopMenu;
    if (filter_has_var(INPUT_GET, 'submenu')) {
        $submenu= filter_input(INPUT_GET, 'submenu');
        if (array_key_exists($submenu, $Menu[$TopMenu]['SubMenu'])) {
            $_SESSION[$View->Model][$TopMenu]['submenu']= $submenu;
        }
        else {
            wui_syslog(LOG_NOTICE, __FILE__, __FUNCTION__, __LINE__, "No such submenu for $View->Model>$TopMenu: " . $submenu);
            echo _TITLE('Resource not available').": $TopMenu.php?submenu=" . $submenu;
            exit(1);
        }
    }
    if (!isset($_SESSION[$View->Model][$TopMenu])) {
        $_SESSION[$View->Model][$TopMenu]= array();
    }
    if (isset($_SESSION[$View->Model][$TopMenu]['submenu'])) {
        $submenu= $_SESSION[$View->Model][$TopMenu]['submenu'];
    }
    else {
        $submenu= $default;
    }
    $_SESSION[$View->Model][$TopMenu]['submenu']= $submenu;
    return $submenu;
}
References $_SESSION, $Menu, $TopMenu, $View, _TITLE(), exit, and wui_syslog().
SetTopMenu()
SetTopMenu ($view, $default = 'info')
Sets session topmenu variable.
View object does not exist yet when this function is called in index.php files, hence the $view parameter.
Parameters
string $view Module name
string $default Default topmenu selected
Returns
string Selected topmenu
Definition at line 268 of file libauth.php.
{
    if (isset($_SESSION[$view]['topmenu'])) {
        $topmenu= $_SESSION[$view]['topmenu'];
    }
    else {
        $topmenu= $default;
    }
    $_SESSION[$view]['topmenu']= $topmenu;
    return $topmenu.'.php';
}
References $_SESSION.
wui_syslog()
wui_syslog ($prio, $file, $func, $line, $msg)
Wrapper for syslog().
Web interface related syslog messages. A global $LOG_LEVEL is set in setup.php.
Parameters
int $prio Log priority checked against $LOG_LEVEL.
string $file Source file the function is in.
string $func Function where the log is taken.
int $line Line number within the function.
string $msg Log message.
Definition at line 67 of file libauth.php.
{
    global $LOG_LEVEL, $LOG_PRIOS;
    $msg= trim($msg);
    try {
        openlog('wui', LOG_PID, LOG_LOCAL0);
        if ($prio <= $LOG_LEVEL) {
            $user= array_key_exists('USER', $_SESSION) ? $_SESSION['USER'] : 'NA';
            $useratip= $user.'@'.filter_input(INPUT_SERVER, 'REMOTE_ADDR');
            $func= $func == '' ? 'NA' : $func;
            $log= "$LOG_PRIOS[$prio] $useratip $file: $func ($line): $msg";
            if (!syslog($prio, $log)) {
                $log.= "\n";
                if (!fwrite(STDERR, $log)) {
                    echo $log;
                }
            }
        }
        closelog();
    }
    catch (Exception $e) {
        echo 'Caught exception: ',  $e->getMessage(), "\n";
        echo "wui_syslog() failed: $prio, $file, $func, $line, $msg\n";
        // No need to closelog(), it is optional
    }
}
References $_SESSION, $LOG_LEVEL, and $LOG_PRIOS.
Referenced by ApplyConfig(), Authentication(), View\CheckAuthentication(), ConfigMFS(), View\Controller(), CreateUsers(), EnableHostap(), GenerateSSLKeyPair(), InitIfs(), LogUserOut(), Notify(), PrintHelpBox(), and SetSubmenu().
Variable Documentation
$Domain
$Domain = 'pffw'
Definition at line 50 of file libauth.php.
Referenced by ValidateCommand().