PF Firewall: src/View/lib/libwui.php File Reference
libwui.php File Reference
WUI library functions.
Functions
PrintHelpBox ($msg='', $width=300)
Prints the message in a simple box, without an image.
PrintHelpWindow ($msg, $width='auto', $type='INFO')
Prints the message in a box with a title bar and an image.
GetLogFile ()
Gets the log file.
PrintLogFileChooser ($logfile)
Prints dropdown box and buttons for logs archives.
PrintNVPsVGraph ($data, $color='red', $title='')
Prints NVP graph vertically.
PrintVGraph ($data, $color='red', $title='', $page='general', $style='Daily', $needle='', $logFile='')
Prints vertical graph across the data range.
PrintHGraph ($data, $color='red', $title='', $page='general', $style='Daily', $needle='', $logFile='')
Prints horizontal graph across the data range.
PrintNVPs ($nvps, $title, $maxcount=100, $pie=TRUE, $needle='', $prefix='', $postfix='', $dateArray=array(), $logFile='')
Prints NVP statistics.
PrintGraphNVPSet ($stats, $date, $parent, $conf, $type, $style, $prefix, $postfix, $page)
Main function that prints both the graph and the NVPs below it.
PrintMinutesGraphNVPSet ($stats, $parent, $conf, $type, $prefix, $postfix, $dateArray, $logFile='')
Main function that prints minutes graph and the NVPs below it.
DivideArrayData (&$data, $divisor)
Divides array values by a divisor.
FillDatesGraphData (&$data, $stats, $dateArray, $name, $parent='')
Fills graph data struct based on dates.
SetGraphData (&$data, $stats, $dateArray, $name, $parent)
FillGraphDataRange (&$data, $stats, $dateArray, $range, $parent)
Fills graph data struct based on a given range according to date.
FillGraphData (&$data, $stats, $range, $parent, $name='', $dateArray=array())
Fills graph data struct based on a given range.
FillNVPs (&$data, $stats, $datearray, $parent, $name, $style)
Sums up count fields of data arrays.
MergeStats (&$data, $stats, $parent, $name, $style)
Sums up count fields of data arrays.
SumData (&$data, $stats)
Adds statistics values to the given data set.
SetRefreshInterval ()
Updates refresh interval for live pages.
ProcessStartLine (&$startline)
Processes posted start line on logs pages.
ProcessNavigationButtons ($linesperpage, $total, &$startline, &$headstart)
Processes posted navigation buttons on logs pages.
PrintLogHeaderForm ($start, $total, $count, $re, $hidden, $needle='', $showDateTimeSelect=FALSE, $dateArray=array())
Displays navigation buttons on logs pages.
PrintLiveLogHeaderForm ($count, $re)
Displays controls on live logs pages.
UpdateLogsPageSessionVars (&$count, &$re, &$needle)
Updates logs and live logs session variables.
PrintTableHeaders ($view)
Prints table headers for logs pages.
PrintLogCols ($linenum, $cols, $lastlinenum=-1, $class='', $module='')
Displays log fields in columns.
RemoveBackSlashes ($str)
GetHwInfo ($names, &$hw)
Reads sysctl hw values.
Variables
$FormIdCount = 0
Provides a unique form id for NVP and graph print functions.
Detailed Description
WUI library functions.
Definition in file libwui.php.
Function Documentation
DivideArrayData()
DivideArrayData (& $data, $divisor)
Divides array values by a divisor.
Used for KB statistics.
Parameters
array $data Name-Value-Pair.
int $divisor Divisor.
Definition at line 773 of file libwui.php.
{
    if ($divisor != 0) {
        foreach ($data as $name => $value) {
            if (is_array($value)) {
                $data[$name]['value']= ceil($data[$name]['value'] / $divisor);
            } else {
                $data[$name]= ceil($value / $divisor);
            }
        }
    }
}
Referenced by PrintGraphNVPSet(), and PrintMinutesGraphNVPSet().
FillDatesGraphData()
FillDatesGraphData (& $data, $stats, $dateArray, $name, $parent = '')
Fills graph data struct based on dates.
Collects the counts classified in dates already obtained in $stats.
If Month or Day field is empty the sub fields are assumed all inclusive, respectively.
Parameters
array $data Data used by graph functions.
array $stats Statistics collected elsewhere.
array $dateArray Datetime struct.
string $name Count field name in $stats array.
string $parent Parent field name in to get count field, if provided.
Definition at line 800 of file libwui.php.
{
    if ($dateArray['Month'] == '') {
        for ($m= 1; $m <= 12; $m++) {
            $m= sprintf('%02d', $m);
            for ($d= 1; $d <= 31; $d++) {
                $d= sprintf('%02d', $d);
                $dateArray['Month']= $m;
                $dateArray['Day']= $d;
                SetGraphData($data, $stats, $dateArray, $name, $parent);
            }
        }
    }
    else if ($dateArray['Day'] == '') {
        for ($d= 1; $d <= 31; $d++) {
            $d= sprintf('%02d', $d);
            $dateArray['Day']= $d;
            SetGraphData($data, $stats, $dateArray, $name, $parent);
        }
    }
    else {
        SetGraphData($data, $stats, $dateArray, $name, $parent);
    }
}
References SetGraphData().
Referenced by PrintGraphNVPSet().
FillGraphData()
FillGraphData (& $data, $stats, $range, $parent, $name = '', $dateArray = array())
Fills graph data struct based on a given range.
Analogous to FillDatesGraphData(), except dates are handled in FillGraphDataRange().
Range is either 24 (Hours in a day) or 60 (Minutes in an hour). Converts size number into 2 digit string to index data array.
Parameters
array $data Data used by graph functions.
array $stats Statistics collected elsewhere.
int $range Size of the range, 24 or 60.
string $parent Parent field name to get count field.
string $name Count field name in $stats array.
array $dateArray Datetime to restrict the searches.
Attention
All hours and minutes should be initialized with 0, even if there is no stats for them
Definition at line 898 of file libwui.php.
{
    for ($hm= 0; $hm < $range; $hm++) {
        $hm= sprintf('%02d', $hm);
        if (!isset($data[$hm])) {
            $data[$hm]= array();
        }
        // Such initialization is faster than any if condition
        if (!isset($data[$hm]['value'])) {
            $data[$hm]['value']= 0;
        }
        if (!isset($data[$hm]['date'])) {
            if ($range == 24) {
                $dateArray['Hour']= $hm;
            } else {
                $dateArray['Minute']= $hm;
            }
            $data[$hm]['date']= $dateArray;
        }
        if ($name != '') {
            if (isset($stats[$hm][$parent][$name])) {
                $data[$hm]['value']+= $stats[$hm][$parent][$name];
            }
        }
        else {
            if (isset($stats[$hm][$parent])) {
                $data[$hm]['value']+= $stats[$hm][$parent];
            }
        }
    }
}
Referenced by FillGraphDataRange(), and PrintMinutesGraphNVPSet().
FillGraphDataRange()
FillGraphDataRange (& $data, $stats, $dateArray, $range, $parent)
Fills graph data struct based on a given range according to date.
Range is either 24 (Hours in a day) or 60 (Minutes in an hour)
If Month or Day field is empty the sub fields are assumed all inclusive, respectively.
Parameters
array $data Data used by graph functions.
array $stats Statistics collected elsewhere.
array $dateArray Datetime struct.
string $range Size of the range, 24 or 60.
string $parent Parent field name in to get count field.
Definition at line 863 of file libwui.php.
{
    global $View;
    if ($dateArray['Month'] == '' || $dateArray['Day'] == '') {
        foreach ($stats as $date => $hourStats) {
            if (isset($hourStats['Hours'])) {
                FillGraphData($data, $hourStats['Hours'], $range, $parent, 'Sum', $dateArray);
            }
        }
    }
    else {
        $date= $View->FormatDate($dateArray);
        if (isset($stats[$date]['Hours'])) {
            FillGraphData($data, $stats[$date]['Hours'], $range, $parent, 'Sum', $dateArray);
        }
    }
}
References $View, and FillGraphData().
Referenced by PrintGraphNVPSet().
FillNVPs()
FillNVPs (& $data, $stats, $datearray, $parent, $name, $style)
Sums up count fields of data arrays.
Parameters
array $data Cumulative data summed up.
array $stats Original data.
array $datearray Datetime struct.
string $parent Parent field name to get count field.
string $name Count field name.
string $style Graph style, flag to sum days or hours.
Definition at line 946 of file libwui.php.
{
    global $View;
    if ($datearray['Month'] == '' || $datearray['Day'] == '') {
        foreach ($stats as $date => $dateStats) {
            MergeStats($data, $dateStats, $parent, $name, $style);
        }
    }
    else {
        $date= $View->FormatDate($datearray);
        if (isset($stats[$date])) {
            MergeStats($data, $stats[$date], $parent, $name, $style);
        }
    }
}
References $View, and MergeStats().
Referenced by PrintGraphNVPSet().
GetHwInfo()
GetHwInfo ($names, & $hw)
Reads sysctl hw values.
Parameters
array $names Names of hw values to read.
array $hw sysctl values in NVP form, output.
Definition at line 1369 of file libwui.php.
{
    global $View;
    $hw= array();
    if ($View->Controller($output, 'GetSysCtl', 'hw')) {
        // Create text from array first
        $lines= implode("\n", $output);
        foreach ($names as $name) {
            if (preg_match("/^hw\.$name=(.*)$/m", $lines, $match)) {
                $hw[$name]= $match[1];
            }
            else {
                $hw[$name]= _('Unknown');
            }
        }
    }
}
References $View.
GetLogFile()
GetLogFile ()
Gets the log file.
Definition at line 145 of file libwui.php.
{
    global $View;
    $logfile= '';
    if (filter_has_var(INPUT_POST, 'LogFile')) {
        $logfile= filter_input(INPUT_POST, 'LogFile');
    } else if (isset($_SESSION[$View->Model]['LogFile'])) {
        $logfile= $_SESSION[$View->Model]['LogFile'];
    }
    if ($View->Controller($output, 'SelectLogFile', $logfile)) {
        $logfile= $output[0];
    } else if ($View->Controller($output, 'SelectLogFile', '')) {
        $logfile= $output[0];
    } else {
        return FALSE;
    }
    $_SESSION[$View->Model]['LogFile']= $logfile;
    return $logfile;
}
References $_SESSION, and $View.
MergeStats()
MergeStats (& $data, $stats, $parent, $name, $style)
Sums up count fields of data arrays.
Sums the values of names. $style is used once to merge minutes of an hour.
Todo:
How to fix $style comparison with gettexted string?
Parameters
array $data Cumulative data merged
array $stats Original data array, passed down as NVPs in recursion
string $parent Parent field name to get count field
string $name Count field name
string $style Graph style, flag to sum days or hours
Definition at line 977 of file libwui.php.
{
    if ($style == _('Hourly')) {
        if (isset($stats['Hours'])) {
            foreach ($stats['Hours'] as $h => $hourStats) {
                if (isset($hourStats[$parent][$name])) {
                    SumData($data, $hourStats[$parent][$name]);
                }
            }
        }
    }
    else {
        if (isset($stats[$parent][$name])) {
            SumData($data, $stats[$parent][$name]);
        }
    }
}
References SumData().
Referenced by FillNVPs().
PrintGraphNVPSet()
PrintGraphNVPSet ($stats, $date, $parent, $conf, $type, $style, $prefix, $postfix, $page)
Main function that prints both the graph and the NVPs below it.
Parameters
array $stats Data set.
array $date Datetime struct.
string $parent Parent field name to get count field.
array $conf Attributes of graph, title and color.
string $type Graph direction, horizontal or vertical.
string $style Precision of graph.
string $prefix Regexp to insert before the search string.
string $postfix Regexp to insert after the search string.
Definition at line 628 of file libwui.php.
{
    global $NvpColCount;
    $data= array();
    // The default is Horizontal
    $printFunc= ($type == 'Vertical') ? 'PrintVGraph' : 'PrintHGraph';
    if ($style == 'Hourly') {
        FillGraphDataRange($data, $stats, $date, 24, $parent);
    }
    else {
        FillDatesGraphData($data, $stats, $date, 'Sum', $parent);
        $printFunc= 'PrintNVPsVGraph';
    }
    if (isset($conf['Divisor'])) {
        DivideArrayData($data, $conf['Divisor']);
    }
    if (!isset($conf['Needle'])) {
        $conf['Needle']= '';
    }
    ?>
    <table id="statset">
        <tr>
            <td>
                <?php
                $printFunc($data, $conf['Color'], _($conf['Title']), $page, $style, $conf['Needle']);
                if (array_key_exists('NVPs', $conf) && count($conf['NVPs']) > 0) {
                    ?>
                    <table>
                        <?php
                        $count= 0;
                        foreach ($conf['NVPs'] as $name => $title) {
                            if (($count % $NvpColCount) == 0) {
                                ?>
                                <tr>
                                <?php
                            }
                            ?>
                            <td class="nvps">
                                <?php
                                $nvps= array();
                                FillNVPs($nvps, $stats, $date, $parent, $name, $style);
                                if (isset($conf['Divisor'])) {
                                    DivideArrayData($nvps, $conf['Divisor']);
                                }
                                PrintNVPs($nvps, _($title), 10, TRUE, $conf['Needle'], $prefix, $postfix, $date);
                                ?>
                            </td>
                            <?php
                            if (($count++ % $NvpColCount) == ($NvpColCount - 1)) {
                                ?>
                                </tr>
                                <?php
                            }
                        }
                        ?>
                    </table>
                    <?php
                }
                ?>
            </td>
        </tr>
    </table>
    <?php
}
References $NvpColCount, DivideArrayData(), FillDatesGraphData(), FillGraphDataRange(), FillNVPs(), and PrintNVPs().
PrintHelpBox()
PrintHelpBox ($msg = '', $width = 300)
Prints the message in a simple box, without an image.
Used in simple info boxes on the right of components. New lines are replaced with html breaks before displaying.
Warning
Checks if $msg is empty, because some automatized functions may not pass a non-empty string (such as on configuration pages), thus the box should not be displayed. Just take debug logs.
Parameters
string $msg Message to display.
int $width Box width, defaults to 300px.
Definition at line 38 of file libwui.php.
{
    global $ShowHelpBox;
    if ($ShowHelpBox) {
        if ($msg !== '') {
            ?>
            <table id="helpbox" style="width: <?php echo $width ?>px;">
                <tr>
                    <td class="leftbar">
                    </td>
                    <td>
                        <?php
                        echo preg_replace("/\n/", '<br />', _($msg));
                        ?>
                    </td>
                </tr>
            </table>
            <?php
            return;
        }
        else {
            wui_syslog(LOG_DEBUG, __FILE__, __FUNCTION__, __LINE__, '$msg empty');
        }
    }
}
References $ShowHelpBox, and wui_syslog().
Referenced by _Include\editInclude(), PrintDateTimeForm(), PrintDHCPInterfaceForm(), PrintDHCPOptionForm(), PrintDHCPRangeOptionForm(), PrintHostsForm(), PrintNVPForm(), and PrintReloadConfigForm().
PrintHelpWindow()
PrintHelpWindow ($msg, $width = 'auto', $type = 'INFO')
Prints the message in a box with a title bar and an image.
Used as the main explanation box on a page. New lines are replaced with html breaks before displaying.
Warning
$Width type should be string, because some functions use 'auto'.
Parameters
string $msg Message to display.
mixed $width Box width, defaults to auto.
string $type Image type to display.
Types of help boxes.
Parameters
string name Title string.
string icon Image to display on the top-left corner of the box.
Definition at line 77 of file libwui.php.
{
    global $IMG_PATH, $InHelpRegion, $ErrorMsg, $WarnMsg, $InfoMsg, $ShowHelpBox;
    $HelpBoxTypes = array(
        'INFO' => array(
            'name' => _TITLE('INFORMATION'),
            'icon' => 'info.png'
            ),
        'ERROR' => array(
            'name' => _TITLE('ERROR'),
            'icon' => 'error.png'
            ),
        'WARN' => array(
            'name' => _TITLE('WARNING'),
            'icon' => 'warning.png'
            ),
    );
    $boxes= array(
        'ERROR' => 'ErrorMsg',
        'WARN' => 'WarnMsg',
        'INFO' => 'InfoMsg',
        );
    if (array_key_exists($type, $boxes)) {
        ${$boxes[$type]}.= ${$boxes[$type]} ? '<br />'.$msg : $msg;
    }
    if (isset($InHelpRegion) && $InHelpRegion) {
        foreach ($boxes as $type => $msgname) {
            if (($type !== 'INFO') || $ShowHelpBox) {
                if (isset(${$msgname}) && (${$msgname} !== '')) {
                    ${$msgname}= preg_replace("/\n/", '<br />', ${$msgname});
                    ?>
                    <table id="mainhelpbox" style="width: <?php echo $width ?>">
                        <tr>
                            <th colspan="2">
                                <?php echo _($HelpBoxTypes[$type]['name']) ?>
                            </th>
                        </tr>
                        <tr>
                            <td class="image">
                                <img src="<?php echo $IMG_PATH.$HelpBoxTypes[$type]['icon'] ?>" name="pffw" alt="pffw" border="0">
                            </td>
                            <td>
                                <?php echo ${$msgname} ?>
                            </td>
                        </tr>
                    </table>
                    <?php
                    // Messsage is printed now, reinitialize it
                    ${$msgname}= '';
                }
            }
        }
    }
}
References $IMG_PATH, $InHelpRegion, $ShowHelpBox, and _TITLE().
Referenced by ProcessStartLine(), SetRefreshInterval(), and UpdateLogsPageSessionVars().
PrintHGraph()
PrintHGraph ($data, $color = 'red', $title = '', $page = 'general', $style = 'Daily', $needle = '', $logFile = '')
Prints horizontal graph across the data range.
Parameters
array $data Data filled in elsewhere.
string $color Color of the bars.
string $title Graph title, if provided.
boolean $page TRUE if the caller is hourly stats page, used to jump to the correct page.
string $needle Search regexp to filter the logs, used by hourly stats.
string $logFile Current log file, used by live stats pages to set the log file to the active one.
Definition at line 418 of file libwui.php.
{
    global $FormIdCount, $View;
    $dataValues= array_map(function ($a) { return $a['value']; }, $data);
    $max= 0;
    if (count($dataValues) > 0) {
        $max= max($dataValues);
    }
    ?>
    <strong><?php echo $title ?></strong> <?php echo _TITLE('total').'= '.array_sum($dataValues) ?>
    <table id="statsgraph">
        <tr class="hgraph">
            <?php
            if ($page == 'hourly' || ($page == 'general' && $style= 'Hourly')) {
                $action= "$View->LogsPage?submenu=archives";
                $title= _TITLE('Click to search in the logs');
            } else {
                $action= "$View->StatsPage?submenu=hourly";
                $title= _TITLE('Click to search in the stats');
            }
            for ($i= 0; $i < count($data); $i++) {
                $i= sprintf('%02d', $i);
                $dateArray= $data[$i]['date'];
                if ($page == 'general' && $style= 'Hourly') {
                    $dateArray['Month']= '';
                    $dateArray['Day']= '';
                }
                $formId= 'form'.$FormIdCount++;
                ?>
                <form id="<?php echo $formId ?>" name="<?php echo $formId ?>" action="<?php echo $action ?>" method="post">
                    <input type="hidden" name="SearchRegExp" value="" />
                    <input type="hidden" name="SearchNeedle" value="<?php echo $needle ?>" />
                    <input type="hidden" name="Month" value="<?php echo isset($dateArray['Month']) ? $dateArray['Month'] : '' ?>" />
                    <input type="hidden" name="Day" value="<?php echo isset($dateArray['Day']) ? $dateArray['Day'] : '' ?>" />
                    <input type="hidden" name="Hour" value="<?php echo isset($dateArray['Hour']) ? $dateArray['Hour'] : '' ?>" />
                    <input type="hidden" name="Minute" value="<?php echo isset($dateArray['Minute']) ? $dateArray['Minute'] : '' ?>" />
                    <?php
                    if ($logFile != '') {
                        ?>
                        <input type="hidden" name="LogFile" value="<?php echo $logFile ?>" />
                        <?php
                    }
                    ?>
                    <input type="hidden" name="Apply" value="Apply" />
                    <input type="hidden" name="Sender" value="Stats" />
                </form>
                <td onclick="document.<?php echo $formId ?>.submit()" style="cursor: pointer;" title="<?php echo $title ?>">
                    <table>
                        <tr>
                            <td class="bartop">
                                <?php
                                $height= 0;
                                if (!isset($data[$i])) {
                                    $data[$i]['value']= 0;
                                }
                                if ($data[$i]['value'] > 0) {
                                    echo $data[$i]['value'];
                                    $height= round(100 * $data[$i]['value'] / $max);
                                }
                                ?>
                            </td>
                        </tr>
                        <tr id="bar">
                            <td id="bar" height="<?php echo $height ?>px" style="background-color: <?php echo $color ?>;">
                            </td>
                        </tr>
                        <tr>
                            <td class="legend">
                                <?php printf('%02d', $i) ?>
                            </td>
                        </tr>
                    </table>
                </td>
                <?php
            }
            ?>
        </tr>
    </table>
    <?php
}
References $FormIdCount, $View, and _TITLE().
PrintLiveLogHeaderForm()
PrintLiveLogHeaderForm ($count, $re)
Displays controls on live logs pages.
Uses session variables.
Definition at line 1204 of file libwui.php.
{
    global $View, $TopMenu;
    ?>
    <form action="<?php echo $_SERVER['PHP_SELF'] ?>" method="post">
        <table id="nvp">
            <tr class="oddline">
                <td>
                    <?php echo _TITLE('Refresh interval').':' ?><input type="text" name="RefreshInterval" style="width: 20px;" maxlength="2" value="<?php echo $_SESSION[$View->Model][$TopMenu]['ReloadRate'] ?>" />
                    <?php echo _TITLE('secs') ?>
                </td>
                <td>
                    <?php echo _TITLE('Lines per page').':' ?><input type="text" name="LinesPerPage" style="width: 20px;" maxlength="2" value="<?php echo $count ?>" />
                </td>
                <td>
                    <?php echo _TITLE('Regexp').':' ?><input type="text" name="SearchRegExp" style="width: 300px;" maxlength="200" value="<?php echo $re ?>" />
                    <input type="submit" name="Apply" value="<?php echo _CONTROL('Apply') ?>"/>
                </td>
            </tr>
        </table>
    </form>
    <?php
}
References $TopMenu, $View, and _TITLE().
PrintLogCols()
PrintLogCols ($linenum, $cols, $lastlinenum = -1, $class = '', $module = '')
Displays log fields in columns.
This cannot be a View member function, because used by non-Views too.
Parameters
int $linenum Line number of the log line
array $cols Parsed log line
array $lastlinenum Last line number, used to detect the last line
string $class Cell class, used for highlighting
string $module Module name if different from $View, $LogConf index
Module name may be different from the current View name
Definition at line 1319 of file libwui.php.
{
    global $LogConf, $View;
    if ($module == '') {
        $module= $View->Model;
    }
    $View->FormatLogCols($cols);
    $lastLine= $linenum == $lastlinenum;
    // Center the line number column
    ?>
    <tr>
        <td class="center<?php echo $lastLine ? ' lastLineFirstCell':'' ?><?php echo ($class == '') ? '':" $class" ?>">
            <?php echo $linenum ?>
        </td>
        <?php
        $totalCols= count($LogConf[$module]['Fields']);
        $count= 1;
        foreach ($LogConf[$module]['Fields'] as $field => $caption) {
            $cellClass= $class;
            if ($lastLine && $count++ == $totalCols) {
                $cellClass.= ' lastLineLastCell';
            }
            $nowrap = ($field == 'Date' || $field == 'DateTime') ? ' nowrap' : '';
            ?>
            <td<?php echo ($cellClass == '') ? '':' class="'.$cellClass.'"' ?><?php echo $nowrap ?>>
                <?php echo isset($cols[$field]) ? $cols[$field] : '' ?>
            </td>
            <?php
        }
        ?>
    </tr>
    <?php
}
References $LogConf, and $View.
Referenced by View\PrintLogLine().
PrintLogFileChooser()
PrintLogFileChooser ($logfile)
Prints dropdown box and buttons for logs archives.
Parameters
string $logfile Log file selected by user.
Definition at line 175 of file libwui.php.
{
    global $View;
    $selectedlogs= '';
    ?>
    <table style="width: auto;">
        <tr>
            <td>
                <form action="<?php echo $_SERVER['PHP_SELF'] ?>" method="post">
                    <?php echo _TITLE('Archives').': ' ?>
                    <select name="LogFile">
                        <?php
                        if ($View->Controller($output, 'GetLogFilesList')) {
                            $filelist= json_decode($output[0], TRUE);
                            foreach ($filelist as $filepath => $startdate) {
                                $file= basename($filepath);
                                $option= sprintf('%-19s - %s', $startdate, $file);
                                if (preg_match('/.*\.gz$/', $file)) {
                                    // $logfile does not have .gz extension, because it points to the file decompressed by the controller
                                    // Update this local copy for comparison and to print it below
                                    $logfile.= basename($logfile).'.gz' == $file ? '.gz' : '';
                                }
                                if (basename($logfile) == $file) {
                                    $selected= 'selected';
                                    $selectedlogs= $option;
                                }
                                else {
                                    $selected= '';
                                }
                                ?>
                                <option <?php echo $selected ?> value="<?php echo $filepath ?>"><?php echo $option ?></option>
                                <?php
                            }
                        }
                        ?>
                    </select>
                    <input type="submit" name="Apply" value="<?php echo _CONTROL('Apply') ?>"/>
                    <input type="submit" name="Download" value="<?php echo _CONTROL('Download') ?>"/>
                </form>
            </td>
            <td>
                <strong><?php echo _TITLE('Selected').': '.$selectedlogs ?></strong>
            </td>
        </tr>
    </table>
    <?php
}
References $View, and _TITLE().
PrintLogHeaderForm()
PrintLogHeaderForm ($start, $total, $count, $re, $hidden, $needle = '', $showDateTimeSelect = FALSE, $dateArray = array())
Displays navigation buttons on logs pages.
Todo:
$hidden seems like a hack, find a better way?
Parameters
int $start First line to start listing.
int $total Number of lines in the logs (obtained somewhere else).
int $count Number of lines to list.
string $re Regexp to use with grep over logs.
string $hidden Some modules may need extra hidden inputs added to form.
string $needle Optional regexp to use with a second grep over logs, used by Stats pages.
boolean $showDateTimeSelect TRUE if we are to show datetime selection.
array $dateArray Datetime to filter the logs.
Definition at line 1097 of file libwui.php.
{
    ?>
    <form action="<?php echo $_SERVER['PHP_SELF'] ?>" method="post">
        <table id="nvp">
            <tr class="oddline">
                <td>
                    <?php echo _TITLE('Line').':' ?>
                    <input type="text" name="StartLine" style="width: 50px;" maxlength="10" value="<?php echo $start + 1 ?>" />/<?php echo $total ?>
                </td>
                <td>
                    <?php echo _TITLE('Lines per page').':' ?>
                    <input type="text" name="LinesPerPage" style="width: 30px;" maxlength="3" value="<?php echo $count ?>" />
                </td>
                <td>
                    <?php echo _TITLE('Regexp').':' ?>
                    <input type="text" name="SearchRegExp" style="width: 300px;" maxlength="200" value="<?php echo $re ?>" />
                    <?php echo _TITLE('Needle').':' ?>
                    <input type="text" name="SearchNeedle" style="width: 100px;" maxlength="200" value="<?php echo $needle ?>" />
                    <input type="submit" name="Apply" value="<?php echo _CONTROL('Apply') ?>"/>
                </td>
            </tr>
            <tr class="evenline">
                <td class="center" colspan="<?php echo $showDateTimeSelect ? 2:3 ?>">
                    <input type="submit" name="First" value="<?php echo _CONTROL('<< First') ?>"/>
                    <input type="submit" name="Previous" value="<?php echo _CONTROL('< Previous') ?>"/>
                    <input type="submit" name="Next" value="<?php echo _CONTROL('Next >') ?>"/>
                    <input type="submit" name="Last" value="<?php echo _CONTROL('Last >>') ?>"/>
                </td>
                <?php
                if ($showDateTimeSelect) {
                    ?>
                    <td>
                        <?php echo _TITLE('Month').':' ?>
                        <select name="Month" style="width: 50px;">
                            <option value=""></option>
                            <?php
                            for ($m= 1; $m <= 12; $m++) {
                                $m= sprintf('%02d', $m);
                                $selected= ($dateArray['Month'] == $m) ? 'selected' : '';
                                ?>
                                <option <?php echo $selected ?> value="<?php echo $m ?>"><?php echo $m ?></option>
                                <?php
                            }
                            ?>
                        </select>
                        <?php echo _TITLE('Day').':' ?>
                        <select name="Day" style="width: 50px;">
                            <option value=""></option>
                            <?php
                            for ($d= 1; $d <= 31; $d++) {
                                $d= sprintf('%02d', $d);
                                $selected= ($dateArray['Day'] == $d) ? 'selected' : '';
                                ?>
                                <option <?php echo $selected ?> value="<?php echo $d ?>"><?php echo $d ?></option>
                                <?php
                            }
                            ?>
                        </select>
                        <?php echo _TITLE('Hour').':' ?>
                        <select name="Hour">
                            <option value=""></option>
                            <?php
                            for ($h= 0; $h < 24; $h++) {
                                $h= sprintf('%02d', $h);
                                $selected= ($dateArray['Hour'] == $h) ? 'selected' : '';
                                ?>
                                <option <?php echo $selected ?> value="<?php echo $h ?>"><?php echo $h ?></option>
                                <?php
                            }
                            ?>
                        </select>
                        <?php echo _TITLE('Minute').':' ?>
                        <select name="Minute">
                            <option value=""></option>
                            <?php
                            for ($m= 0; $m < 60; $m++) {
                                $m= sprintf('%02d', $m);
                                $selected= ($dateArray['Minute'] == $m) ? 'selected' : '';
                                ?>
                                <option <?php echo $selected ?> value="<?php echo $m ?>"><?php echo $m ?></option>
                                <?php
                            }
                            ?>
                        </select>
                        <input type="submit" name="Apply" value="<?php echo _CONTROL('Apply') ?>"/>
                        <input type="submit" name="Defaults" value="<?php echo _CONTROL('Defaults') ?>"/>
                    </td>
                    <?php
                }
                ?>
            </tr>
        </table>
        <?php
        if ($hidden) {
            echo $hidden;
        }
        ?>
    </form>
    <?php
}
References $hidden, and _TITLE().
Referenced by Pf\PrintStatesTable().
PrintMinutesGraphNVPSet()
PrintMinutesGraphNVPSet ($stats, $parent, $conf, $type, $prefix, $postfix, $dateArray, $logFile = '')
Main function that prints minutes graph and the NVPs below it.
Parameters
array $stats Data set.
string $parent Parent field name to get count field.
array $conf Attributes of graph, title and color.
string $type Graph direction, horizontal or vertical.
string $prefix Regexp to insert before the search string.
string $postfix Regexp to insert after the search string.
array $dateArray Datetime to restrict the searches.
string $logFile Current log file, used by live stats pages to set the log file to the active one.
Todo:
More than 2 or 3 NVPs under graph may be a problem
Definition at line 709 of file libwui.php.
{
    $data= array();
    // The default is Horizontal
    $printGraphFunc= ($type == 'Vertical') ? 'PrintVGraph' : 'PrintHGraph';
    if (isset($stats['Mins'])) {
        FillGraphData($data, $stats['Mins'], 60, $parent, '', $dateArray);
    }
    if (isset($conf['Divisor'])) {
        DivideArrayData($data, $conf['Divisor']);
    }
    if (!isset($conf['Needle'])) {
        $conf['Needle']= '';
    }
    ?>
    <table id="statset">
        <tr>
            <td>
                <?php
                $printGraphFunc($data, $conf['Color'], _($conf['Title']), 'hourly', 'Hourly', $conf['Needle'], $logFile);
                if (array_key_exists('NVPs', $conf) && count($conf['NVPs']) > 0) {
                    ?>
                    <table>
                        <tr>
                            <?php
                            foreach ($conf['NVPs'] as $name => $title) {
                                if (isset($stats[$parent]) && isset($stats[$parent][$name])) {
                                    ?>
                                    <td class="nvps">
                                        <?php
                                        $nvps= $stats[$parent][$name];
                                        if (isset($conf['Divisor'])) {
                                            DivideArrayData($nvps, $conf['Divisor']);
                                        }
                                        PrintNVPs($nvps, _($title), 10, TRUE, $conf['Needle'], $prefix, $postfix, $dateArray, $logFile);
                                        ?>
                                    </td>
                                    <?php
                                }
                            }
                            ?>
                        </tr>
                    </table>
                    <?php
                }
                ?>
            </td>
        </tr>
    </table>
    <?php
}
References DivideArrayData(), FillGraphData(), and PrintNVPs().
PrintNVPs()
PrintNVPs ($nvps, $title, $maxcount = 100, $pie = TRUE, $needle = '', $prefix = '', $postfix = '', $dateArray = array(), $logFile = '')
Prints NVP statistics.
Parameters
array $nvps Name-Value-Pairs to print.
string $title Title.
int $maxcount Number of NVPs to print.
boolean $pie TRUE if we are to print pie chart trigger image.
string $needle Search regexp to filter the logs.
string $prefix Regexp to insert before the search string.
string $postfix Regexp to insert after the search string.
array $dateArray Datetime to restrict the searches.
string $logFile Current log file, used by live stats pages to set the log file to the active one.
Attention
Do not use the needle in the regexp, use it separately, or grep takes too long,
Do not use href in anchor, otherwise href overrides the onclick action sometimes, hence the cursor style
Definition at line 517 of file libwui.php.
{
    global $IMG_PATH, $View, $FormIdCount;
    ?>
    <strong><?php echo $title ?></strong>
    <table id="stats">
        <?php
        arsort($nvps);
        $count= 0;
        foreach ($nvps as $n => $value) {
            ?>
            <tr>
                <td class="value">
                    <?php echo $value ?>
                </td>
                <td class="name">
                    <?php
                    // Empty strings print default gettext header lines otherwise
                    $name= $n !== '' ? _(htmlspecialchars($n)):'-';
                    // Needle can be used to disable log searches
                    if ($needle === FALSE) {
                        echo $name;
                    } else {
                        // Need unique ids for each form for submission to work
                        $formId = 'form'.$FormIdCount++;
                        // Need SearchRegExp and action URL supplied externally
                        // Regex should search for a case sensitive exact match, otherwise github matches live.github or GITHUB too
                        // Caveats of this regexp method:
                        // @todo P3scan Number of e-mails Clean Exit: Searches all, need a separate parser, e.g. for (Clean Exit). Mails: 1
                        // @todo P3scan pop3s: Cannot find pop3s, need to make POP3S lowercase
                        // @todo Smtp-gated Source IPs: Searches and finds all IPs, not just source (or destination), the same issue with other modules
                        // @todo Openssh briefstats password: Searches and finds all password words, not just failed attempts
                        // @todo syslog "last message repeated x times": Causes more date lines in brief stats than can be parsed, need -rr option in OpenBSD 6.x/syslog
                        // @todo Briefstats should use the Total Needle too, otherwise we cannot get general statistics for, say, spamassassin
                        // Use default pre/postfixes if not supplied by the caller
                        if ($prefix == '') {
                            // @attention Use [[:blank:]]+, [:blank:]+ does not work
                            $prefix= '([[:blank:]]+)';
                        }
                        if ($postfix == '') {
                            $postfix= '([^[:alnum:]]+)';
                        }
                        // ~30 secs if search name is long, as in SSLproxy error or warning messages. Two cascaded greps are very fast.
                        // Otherwise, the following would/could do the same job.
                        //$regexp= $needle == '' ?
                        //  "($prefix|^)${name}($postfix|$)" :
                        //  "(($prefix|^)${name}$postfix.*($needle)|($needle).*$prefix${name}($postfix|$))";
                        $regexp= "($prefix|^)".Escape($name, '()[]+?')."($postfix|$)";
                        ?>
                        <form id="<?php echo $formId ?>" name="<?php echo $formId ?>" action="<?php echo $View->LogsPage ?>?submenu=archives" method="post">
                            <input type="hidden" name="SearchRegExp" value="<?php echo $regexp ?>" />
                            <input type="hidden" name="SearchNeedle" value="<?php echo $needle ?>" />
                            <input type="hidden" name="Month" value="<?php echo isset($dateArray['Month']) ? $dateArray['Month'] : '' ?>" />
                            <input type="hidden" name="Day" value="<?php echo isset($dateArray['Day']) ? $dateArray['Day'] : '' ?>" />
                            <input type="hidden" name="Hour" value="<?php echo isset($dateArray['Hour']) ? $dateArray['Hour'] : '' ?>" />
                            <?php
                            if ($logFile != '') {
                                ?>
                                <input type="hidden" name="LogFile" value="<?php echo $logFile ?>" />
                                <?php
                            }
                            ?>
                            <input type="hidden" name="Sender" value="Stats" />
                        </form>
                        <a onclick="document.<?php echo $formId ?>.submit()" style="cursor: pointer;" title="<?php echo _TITLE('Click to search in the logs') ?>"><?php echo $name ?></a>
                        <?php
                    }
                    ?>
                </td>
                <?php
                if ($count == 0 && $pie) {
                    ?>
                    <img id="chart" class="chart-trigger" onclick="generateChart(<?php echo str_replace('"', "'", str_replace("'", "\'", json_encode($nvps))) ?>, <?php echo "'".str_replace("'", "\'", $title)."'" ?>);"
                        src="<?php echo $IMG_PATH.'chart.png' ?>" name="<?php echo $title ?>" alt="<?php echo $title ?>" align="absmiddle" >
                    <?php
                }
                ?>
            </tr>
            <?php
            if (++$count >= $maxcount) {
                break;
            }
        }
        ?>
    </table>
    <?php
}
References $FormIdCount, $IMG_PATH, $View, and align.
Referenced by PrintGraphNVPSet(), PrintMinutesGraphNVPSet(), and View\PrintStats().
PrintNVPsVGraph()
PrintNVPsVGraph ($data, $color = 'red', $title = '')
Prints NVP graph vertically.
Parameters
array $data Data filled in elsewhere.
string $color Color of the bars.
string $title Graph title, if provided.
Definition at line 236 of file libwui.php.
{
    global $FormIdCount, $View;
    $dataValues= array_map(function ($a) { return $a['value']; }, $data);
    $max= 0;
    if (count($dataValues) > 0) {
        $max= max($dataValues);
    }
    ?>
    <strong><?php echo $title ?></strong> <?php echo _TITLE('total').'= '.array_sum($dataValues) ?>
    <table id="statsgraph">
        <?php
        foreach ($data as $name => $valueArray) {
            $value= $valueArray['value'];
            $dateArray= $valueArray['date'];
            $formId= 'form'.$FormIdCount++;
            $width= 0;
            if ($value > 0) {
                $width= round(100 * $value / $max);
            }
            ?>
            <form id="<?php echo $formId ?>" name="<?php echo $formId ?>" action="<?php echo $View->StatsPage ?>?submenu=daily" method="post">
                <input type="hidden" name="Month" value="<?php echo isset($dateArray['Month']) ? $dateArray['Month'] : '' ?>" />
                <input type="hidden" name="Day" value="<?php echo isset($dateArray['Day']) ? $dateArray['Day'] : '' ?>" />
                <input type="hidden" name="Hour" value="<?php echo isset($dateArray['Hour']) ? $dateArray['Hour'] : '' ?>" />
                <input type="hidden" name="Apply" value="Apply" />
                <input type="hidden" name="Sender" value="Stats" />
            </form>
            <tr onclick="document.<?php echo $formId ?>.submit()" style="cursor: pointer;" title="<?php echo _TITLE('Click to search in the stats') ?>">
                <td class="hlegend">
                    <table>
                        <tr id="hbar">
                            <td class="legend">
                                <?php echo $name ?>
                            </td>
                        </tr>
                    </table>
                </td>
                <td>
                    <table>
                        <tr id="hbar">
                            <td style="width: <?php echo $width ?>%; background: <?php echo $color ?>;">
                            </td>
                            <?php
                            if ($value > 0) {
                                ?>
                                <td class="value"><?php echo $value ?></td>
                                <?php
                            }
                            else {
                                ?>
                                <td class="valuezero"> </td>
                                <?php
                            }
                            ?>
                        </tr>
                    </table>
                </td>
            </tr>
            <?php
        }
        ?>
    </table>
    <?php
}
References $FormIdCount, $View, and _TITLE().
PrintTableHeaders()
PrintTableHeaders ($view)
Prints table headers for logs pages.
$view may be different from View object name, hence passed as a param.
Parameters
string $view Module name, $LogConf index.
Definition at line 1291 of file libwui.php.
{
    global $LogConf;
    ?>
    <tr id="logline">
        <th><?php echo _('Line') ?></th>
        <?php
        foreach ($LogConf[$view]['Fields'] as $field => $caption) {
            ?>
            <th><?php echo $caption ?></th>
            <?php
        }
        ?>
    </tr>
    <?php
}
References $LogConf.
PrintVGraph()
PrintVGraph ($data, $color = 'red', $title = '', $page = 'general', $style = 'Daily', $needle = '', $logFile = '')
Prints vertical graph across the data range.
Todo:
Can combine with PrintNVPsVGraph()?
Parameters
array $data Data filled in elsewhere.
string $color Color of the bars.
string $title Graph title, if provided.
boolean $page TRUE if the caller is hourly stats page, used to jump to the correct page.
string $needle Search regexp to filter the logs, used by hourly stats.
string $logFile Current log file, used by live stats pages to set the log file to the active one.
Definition at line 318 of file libwui.php.
{
    global $FormIdCount, $View;
    $dataValues= array_map(function ($a) { return $a['value']; }, $data);
    $max= 0;
    if (count($dataValues) > 0) {
        $max= max($dataValues);
    }
    ?>
    <strong><?php echo $title ?></strong> <?php echo _TITLE('total').'= '.array_sum($dataValues) ?>
    <table id="statsgraph">
        <tr>
            <td>
                <?php
                if ($page == 'hourly' || ($page == 'general' && $style= 'Hourly')) {
                    $action= "$View->LogsPage?submenu=archives";
                    $title= _TITLE('Click to search in the logs');
                } else {
                    $action= "$View->StatsPage?submenu=hourly";
                    $title= _TITLE('Click to search in the stats');
                }
                for ($i= 0; $i < count($data); $i++) {
                    $i= sprintf('%02d', $i);
                    $width= 0;
                    if (!isset($data[$i])) {
                        $data[$i]['value']= 0;
                    }
                    if ($data[$i]['value'] > 0) {
                        $width= round(100 * $data[$i]['value'] / $max);
                    }
                    $dateArray= $data[$i]['date'];
                    if ($page == 'general' && $style= 'Hourly') {
                        $dateArray['Month']= '';
                        $dateArray['Day']= '';
                    }
                    $formId= 'form'.$FormIdCount++;
                    ?>
                    <form id="<?php echo $formId ?>" name="<?php echo $formId ?>" action="<?php echo $action ?>" method="post">
                        <input type="hidden" name="SearchRegExp" value="" />
                        <input type="hidden" name="SearchNeedle" value="<?php echo $needle ?>" />
                        <input type="hidden" name="Month" value="<?php echo isset($dateArray['Month']) ? $dateArray['Month'] : '' ?>" />
                        <input type="hidden" name="Day" value="<?php echo isset($dateArray['Day']) ? $dateArray['Day'] : '' ?>" />
                        <input type="hidden" name="Hour" value="<?php echo isset($dateArray['Hour']) ? $dateArray['Hour'] : '' ?>" />
                        <input type="hidden" name="Minute" value="<?php echo isset($dateArray['Minute']) ? $dateArray['Minute'] : '' ?>" />
                        <?php
                        if ($logFile != '') {
                            ?>
                            <input type="hidden" name="LogFile" value="<?php echo $logFile ?>" />
                            <?php
                        }
                        ?>
                        <input type="hidden" name="Apply" value="Apply" />
                        <input type="hidden" name="Sender" value="Stats" />
                    </form>
                    <table>
                        <tr id="hbar" onclick="document.<?php echo $formId ?>.submit()" style="cursor: pointer;" title="<?php echo $title ?>">
                            <td class="legend">
                                <?php printf('%02d', $i) ?>
                            </td>
                            <td style="width: <?php echo $width ?>%; background-color: <?php echo $color ?>;">
                            </td>
                            <?php
                            if ($data[$i]['value'] > 0) {
                                ?>
                                <td class="value"><?php echo $data[$i]['value'] ?></td>
                                <?php
                            }
                            else {
                                ?>
                                <td class="valuezero"> </td>
                                <?php
                            }
                            ?>
                        </tr>
                    </table>
                    <?php
                }
                ?>
            </td>
        </tr>
    </table>
    <?php
}
References $FormIdCount, $View, and _TITLE().
ProcessNavigationButtons()
ProcessNavigationButtons ($linesperpage, $total, & $startline, & $headstart)
Processes posted navigation buttons on logs pages.
Definition at line 1052 of file libwui.php.
{
    global $View, $TopMenu;
    if (count($_POST)) {
        if (filter_has_var(INPUT_POST, 'First')) {
            $startline= 0;
        }
        else if (filter_has_var(INPUT_POST, 'Previous')) {
            $startline-= $linesperpage;
        }
        else if (filter_has_var(INPUT_POST, 'Next')) {
            $startline+= $linesperpage;
        }
        else if (filter_has_var(INPUT_POST, 'Last')) {
            $startline= $total;
        }
    }
    $headstart= $startline + $linesperpage;
    if ($headstart > $total) {
        $headstart= $total;
        $startline= $headstart - $linesperpage;
    }
    if ($startline < 0) {
        $startline= 0;
        $headstart= $linesperpage;
    }
    $_SESSION[$View->Model][$TopMenu]['StartLine']= $startline;
}
References $_SESSION, $TopMenu, and $View.
ProcessStartLine()
ProcessStartLine (& $startline)
Processes posted start line on logs pages.
Definition at line 1025 of file libwui.php.
{
    global $View, $TopMenu;
    $pageSession= &$_SESSION[$View->Model][$TopMenu];
    if (filter_has_var(INPUT_POST, 'StartLine')) {
        if (preg_match('/^\d+$/', filter_input(INPUT_POST, 'StartLine'))) {
            $pageSession['StartLine']= filter_input(INPUT_POST, 'StartLine') - 1;
        }
        else {
            PrintHelpWindow(_NOTICE('FAILED').': '._NOTICE('Page start line').': '.filter_input(INPUT_POST, 'StartLine'), 'auto', 'ERROR');
        }
    }
    if (isset($pageSession['StartLine'])) {
        $startline= $pageSession['StartLine'];
    }
    else {
        $startline= 0;
        $pageSession['StartLine']= $startline;
    }
}
References $_SESSION, $TopMenu, $View, _NOTICE(), and PrintHelpWindow().
RemoveBackSlashes()
RemoveBackSlashes ($str)
Definition at line 1358 of file libwui.php.
{
    return preg_replace('/\\\\\\\\/', '\\', $str);
}
Referenced by UpdateLogsPageSessionVars().
SetGraphData()
SetGraphData (& $data, $stats, $dateArray, $name, $parent)
Definition at line 825 of file libwui.php.
{
    global $View;
    $date= $View->FormatDate($dateArray);
    if ($parent == '') {
        if (isset($stats[$date][$name])) {
            $data[$date]= array(
                'value' => $stats[$date][$name],
                'date' => $dateArray,
                );
        }
    }
    else {
        if (isset($stats[$date][$parent][$name])) {
            $data[$date]= array(
                'value' => $stats[$date][$parent][$name],
                'date' => $dateArray,
                );
        }
    }
}
References $View.
Referenced by FillDatesGraphData().
SetRefreshInterval()
SetRefreshInterval ()
Updates refresh interval for live pages.
Definition at line 1008 of file libwui.php.
{
    global $View, $TopMenu;
    if (filter_has_var(INPUT_POST, 'RefreshInterval')) {
        if (preg_match('/^\d+$/', filter_input(INPUT_POST, 'RefreshInterval'))) {
            $_SESSION[$View->Model][$TopMenu]['ReloadRate']= filter_input(INPUT_POST, 'RefreshInterval') >= 3 ? filter_input(INPUT_POST, 'RefreshInterval'):3;
        }
        else {
            PrintHelpWindow(_NOTICE('FAILED').': '._TITLE('Refresh interval').': '.filter_input(INPUT_POST, 'RefreshInterval'), 'auto', 'ERROR');
        }
    }
}
References $_SESSION, $TopMenu, $View, _NOTICE(), _TITLE(), and PrintHelpWindow().
SumData()
SumData (& $data, $stats)
Adds statistics values to the given data set.
Definition at line 998 of file libwui.php.
{
    foreach ($stats as $name => $value) {
        AddValueCreateKey($data, $name, $value);
    }
}
References AddValueCreateKey().
Referenced by MergeStats().
UpdateLogsPageSessionVars()
UpdateLogsPageSessionVars (& $count, & $re, & $needle)
Updates logs and live logs session variables.
Parameters
int $count Max line per log page.
string $re Regexp to use over logs file.
string $needle Optional regexp to use with a second grep over logs, used by Stats pages.
Definition at line 1235 of file libwui.php.
{
    global $View, $TopMenu;
    $pageSession= &$_SESSION[$View->Model][$TopMenu];
    if (filter_has_var(INPUT_POST, 'LinesPerPage')) {
        if (preg_match('/^\d+$/', filter_input(INPUT_POST, 'LinesPerPage'))) {
            $pageSession['LinesPerPage']= filter_input(INPUT_POST, 'LinesPerPage');
        }
        else {
            PrintHelpWindow(_NOTICE('FAILED').': '._TITLE('Lines per page').': '.filter_input(INPUT_POST, 'LinesPerPage'), 'auto', 'ERROR');
        }
    }
    if (isset($pageSession['LinesPerPage'])) {
        $count= $pageSession['LinesPerPage'];
    }
    else {
        $count= 25;
        $pageSession['LinesPerPage']= $count;
    }
    // Empty regexp posted is used to clear the session regexp
    if (filter_has_var(INPUT_POST, 'SearchRegExp')) {
        $pageSession['SearchRegExp']= filter_input(INPUT_POST, 'SearchRegExp');
    }
    if (isset($pageSession['SearchRegExp'])) {
        $re= RemoveBackSlashes($pageSession['SearchRegExp']);
        $pageSession['SearchRegExp']= $re;
    }
    else {
        $re= '';
    }
    if (filter_has_var(INPUT_POST, 'SearchNeedle')) {
        $pageSession['SearchNeedle']= filter_input(INPUT_POST, 'SearchNeedle');
    }
    if (isset($pageSession['SearchNeedle'])) {
        $needle= RemoveBackSlashes($pageSession['SearchNeedle']);
        $pageSession['SearchNeedle']= $needle;
    }
    else {
        $needle= '';
    }
}
References $_SESSION, $TopMenu, $View, _NOTICE(), _TITLE(), PrintHelpWindow(), and RemoveBackSlashes().
Variable Documentation
$FormIdCount
$FormIdCount = 0
Provides a unique form id for NVP and graph print functions.
Definition at line 227 of file libwui.php.
Referenced by PrintHGraph(), PrintNVPs(), PrintNVPsVGraph(), and PrintVGraph().