PF Firewall: src/View/lib/logs.archives.php File Reference
logs.archives.php File Reference
All log archive pages include this file.
Functions
PrintLogsHelp ($msg)
Prints archives log help box.
Variables
$LogFile = GetLogFile()
$ApplyDefaults = TRUE
$DateArray = array()
if(count($_POST)) else if(isset($_SESSION[ $View->Model][ $Submenu][ 'Month'], $_SESSION[ $View->Model][ $Submenu][ 'Day'], $_SESSION[ $View->Model][ $Submenu][ 'Hour'], $_SESSION[ $View->Model][ $Submenu][ 'Minute'])) if($ApplyDefaults) $_SESSION [$View->Model][$Submenu]['Month'] = $DateArray['Month']
$_SESSION [$View->Model][$Submenu]['Day'] = $DateArray['Day']
$_SESSION [$View->Model][$Submenu]['Hour'] = $DateArray['Hour']
$_SESSION [$View->Model][$Submenu]['Minute'] = $DateArray['Minute']
$LogSize = 0
$Logs = array()
if($LogFile !==FALSE && $View->Controller($Output, 'GetLogs', $LogFile, $HeadStart, $LinesPerPage, $SearchRegExp, $SearchNeedle, $DateArray['Month'], $DateArray['Day'], $DateArray['Hour'], $DateArray['Minute'])) $LineCount = $StartLine + 1
$LastLineNum = $StartLine + min(array(count($Logs), $LinesPerPage))
Detailed Description
All log archive pages include this file.
Log configuration is in $LogConf.
Definition in file logs.archives.php.
Function Documentation
PrintLogsHelp()
PrintLogsHelp ($msg)
Prints archives log help box.
Definition at line 31 of file logs.archives.php.
{
    $msg.= ($msg !== '' ? "\n\n" : '')._HELPWINDOW('Log keeping capacity of PFFW is limited only by the size of the disks on your system.
If you are not seeing as many number of lines as you were expecting, this may be because the log file has turned over and put in a compressed archive file. The default maximum number of archive files for most services is 100, and can be configured on the system configuration pages. Depending on how busy a service it is, this many log archives may mean months of logging in most cases. You can download the log files using the Download button.
You can search the logs by entering keywords or extended regular expressions in Regexp box. Regular expressions are de-facto standard for text searching.');
    PrintHelpWindow($msg);
}
$View->UploadLogFile();
$LogFile= GetLogFile();
ProcessStartLine($StartLine);
UpdateLogsPageSessionVars($LinesPerPage, $SearchRegExp, $SearchNeedle);
$ApplyDefaults= TRUE;
$DateArray= array();
if (count($_POST)) {
    if (!filter_has_var(INPUT_POST, 'Defaults')) {
        $DateArray['Month']= filter_input(INPUT_POST, 'Month');
        $DateArray['Day']= filter_input(INPUT_POST, 'Day');
        $DateArray['Hour']= filter_input(INPUT_POST, 'Hour');
        $DateArray['Minute']= filter_input(INPUT_POST, 'Minute');
        $ApplyDefaults = FALSE;
    }
}
// Use isset here, Month and Day may be empty string
else if (isset($_SESSION[$View->Model][$Submenu]['Month'],
    $_SESSION[$View->Model][$Submenu]['Day'],
    $_SESSION[$View->Model][$Submenu]['Hour'],
    $_SESSION[$View->Model][$Submenu]['Minute'])) {
    $DateArray['Month']= $_SESSION[$View->Model][$Submenu]['Month'];
    $DateArray['Day']= $_SESSION[$View->Model][$Submenu]['Day'];
    $DateArray['Hour']= $_SESSION[$View->Model][$Submenu]['Hour'];
    $DateArray['Minute']= $_SESSION[$View->Model][$Submenu]['Minute'];
    $ApplyDefaults= FALSE;
}
if ($ApplyDefaults) {
    $DateArray['Month']= '';
    $DateArray['Day']= '';
    $DateArray['Hour']= '';
    $DateArray['Minute']= '';
}
$_SESSION[$View->Model][$Submenu]['Month']= $DateArray['Month'];
$_SESSION[$View->Model][$Submenu]['Day']= $DateArray['Day'];
$_SESSION[$View->Model][$Submenu]['Hour']= $DateArray['Hour'];
$_SESSION[$View->Model][$Submenu]['Minute']= $DateArray['Minute'];
$LogSize= 0;
if ($LogFile !== FALSE && $View->Controller($Output, 'GetFileLineCount', $LogFile, $SearchRegExp, $SearchNeedle, $DateArray['Month'], $DateArray['Day'], $DateArray['Hour'], $DateArray['Minute'])) {
    $LogSize= $Output[0];
}
ProcessNavigationButtons($LinesPerPage, $LogSize, $StartLine, $HeadStart);
require_once($VIEW_PATH.'/header.php');
PrintLogFileChooser($LogFile);
PrintLogHeaderForm($StartLine, $LogSize, $LinesPerPage, $SearchRegExp, $CustomHiddenInputs, $SearchNeedle, TRUE, $DateArray);
?>
<table id="logline">
    <?php
    PrintTableHeaders($View->Model);
    $Logs= array();
    if ($LogFile !== FALSE && $View->Controller($Output, 'GetLogs', $LogFile, $HeadStart, $LinesPerPage, $SearchRegExp, $SearchNeedle, $DateArray['Month'], $DateArray['Day'], $DateArray['Hour'], $DateArray['Minute'])) {
        $Logs= json_decode($Output[0], TRUE);
    }
    $LineCount= $StartLine + 1;
    $LastLineNum= $StartLine + min(array(count($Logs), $LinesPerPage));
    foreach ($Logs as $Logline) {
        $View->PrintLogLine($Logline, $LineCount++, $LastLineNum);
    }
References _HELPWINDOW(), and PrintHelpWindow().
Variable Documentation
$_SESSION [1/4]
$_SESSION[ $View->Model][ $Submenu][ 'Day'] = $DateArray['Day']
Definition at line 82 of file logs.archives.php.
$_SESSION [2/4]
$_SESSION[ $View->Model][ $Submenu][ 'Hour'] = $DateArray['Hour']
Definition at line 83 of file logs.archives.php.
$_SESSION [3/4]
$_SESSION[ $View->Model][ $Submenu][ 'Minute'] = $DateArray['Minute']
Definition at line 84 of file logs.archives.php.
$_SESSION [4/4]
if(count($_POST)) else if(isset($_SESSION[$View->Model][$Submenu]['Month'], $_SESSION[$View->Model][$Submenu]['Day'], $_SESSION[$View->Model][$Submenu]['Hour'], $_SESSION[$View->Model][$Submenu]['Minute'])) if ($ApplyDefaults) $_SESSION[ $View->Model][ $Submenu][ 'Month'] = $DateArray['Month']
Definition at line 81 of file logs.archives.php.
Referenced by Pf\__construct(), Authentication(), RuleSet\cancel(), View\CheckAuthentication(), View\Controller(), Session\getform(), GetLogFile(), LogUserOut(), PrintDateTimeForm(), View\PrintStatusForm(), ProcessNavigationButtons(), ProcessStartLine(), RuleSet\save(), SetRefreshInterval(), SetSubmenu(), SetTopMenu(), RuleSet\setupEditSession(), UpdateLogsPageSessionVars(), and wui_syslog().
$ApplyDefaults
$ApplyDefaults = TRUE
Definition at line 49 of file logs.archives.php.
$DateArray
$DateArray = array()
Definition at line 51 of file logs.archives.php.
$LastLineNum
$LastLineNum = $StartLine + min(array(count($Logs), $LinesPerPage))
Definition at line 109 of file logs.archives.php.
$LineCount
if ($LogFile !==FALSE &&$View->Controller($Output, 'GetLogs', $LogFile, $HeadStart, $LinesPerPage, $SearchRegExp, $SearchNeedle, $DateArray[ 'Month'], $DateArray[ 'Day'], $DateArray[ 'Hour'], $DateArray[ 'Minute'])) $LineCount = $StartLine + 1
Definition at line 108 of file logs.archives.php.
$LogFile
$LogFile = GetLogFile()
Definition at line 44 of file logs.archives.php.
Referenced by Model\GetLogFilesList(), Model\GetProcStatLines(), and Model\SelectLogFile().
$Logs
$Logs = array()
Definition at line 103 of file logs.archives.php.
$LogSize
$LogSize = 0
Definition at line 86 of file logs.archives.php.