PF Firewall: src/Model/include.php File Reference
include.php File Reference
Includes, defines, and functions used in the Model.
Functions
Output ($msg)
Sets or updates $Output with the given message.
Error ($msg)
Sets or updates $Error with the given message.
convertBinary ($value)
convertDecimal ($value)
ctlr_syslog ($prio, $file, $func, $line, $msg)
Wrapper for controller error logging via syslog.
Variables
$ROOT = dirname(dirname(dirname(__FILE__)))
$SRC_ROOT = dirname(dirname(__FILE__))
const NONE 1
Shell command argument types.
const FILEPATH 2
const NAME 4
const NUM 8
const SHA1STR 16
const BOOL 32
const SAVEFILEPATH 64
const JSON 128
const EMPTYSTR 256
const REGEXP 512
const SERIALARRAY 1024
const IPADRLIST 2048
const STR 4096
const IPADR 8192
const HOST 16384
const URL 32768
const EMAIL 65536
const DATETIME 131072
const IPRANGE 262144
const TAIL 524288
const ASTERISK 1048576
const CONFNAME 2097152
const MFSSIZE 268435456
$Output = ''
$Error = ''
Detailed Description
Includes, defines, and functions used in the Model.
Definition in file include.php.
Function Documentation
convertBinary()
convertBinary ($value)
Definition at line 143 of file include.php.
{
    $g= round($value / 1073741824);
    if ($g) {
        return $g . 'G';
    }
    $m= round($value / 1048576);
    if ($m) {
        return $m . 'M';
    }
    $k= round($value / 1024);
    if ($k) {
        return $k . 'K';
    }
    return $value;
}
Referenced by Pf\parsePfIfsInfo(), Pf\parsePfQueueInfo(), and Pf\parsePfRulesInfo().
convertDecimal()
convertDecimal ($value)
Definition at line 163 of file include.php.
{
    $g= round($value / 1000000000);
    if ($g) {
        return $g . 'G';
    }
    $m= round($value / 1000000);
    if ($m) {
        return $m . 'M';
    }
    $k= round($value / 1000);
    if ($k) {
        return $k . 'K';
    }
    return $value;
}
Referenced by Pf\parsePfIfsInfo(), Pf\parsePfQueueInfo(), and Pf\parsePfRulesInfo().
ctlr_syslog()
ctlr_syslog ($prio, $file, $func, $line, $msg)
Wrapper for controller error logging via syslog.
A global $LOG_LEVEL is set in setup.php.
Parameters
int $prio Log priority checked against $LOG_LEVEL
string $file Source file the function is in
string $func Function where the log is taken
int $line Line number within the function
string $msg Log message
Definition at line 194 of file include.php.
{
    global $LOG_LEVEL, $LOG_PRIOS;
    $msg= trim($msg);
    try {
        openlog('ctlr', LOG_PID, LOG_LOCAL0);
        if ($prio <= $LOG_LEVEL) {
            $func= $func == '' ? 'NA' : $func;
            $log= "$LOG_PRIOS[$prio] $file: $func ($line): $msg";
            if (!syslog($prio, $log)) {
                $log.= "\n";
                if (!fwrite(STDERR, $log)) {
                    echo $log;
                }
            }
        }
        closelog();
    }
    catch (Exception $e) {
        echo 'Caught exception: ',  $e->getMessage(), "\n";
        echo "ctlr_syslog() failed: $prio, $file, $func, $line, $msg\n";
        // No need to closelog(), it is optional
    }
}
References $LOG_LEVEL, and $LOG_PRIOS.
Referenced by System\_getDynamicGateway(), System\AddFilter(), System\AddNotifierUser(), Model\AppendToFile(), System\AutoConfig(), Model\CollectDayStats(), Model\CopyLogFileToTmp(), Model\CountDiffLogLines(), Model\CreateUser(), System\DaemonizedRotateAllLogFiles(), System\DaemonizedRotateLogFile(), System\DaemonizeFunc(), Model\DeleteFile(), System\DeleteStats(), System\DelFilter(), System\DelNotifierUser(), System\DisableNotifier(), System\EnableNotifier(), ExpandArgs(), System\GenerateSSLKeyPair(), Model\getCachedContents(), Model\GetDisabledValue(), Pf\GetLogs(), System\GetLogsConfig(), System\GetMFSConfig(), Model\GetProcList(), Model\getRrdValue(), Model\GetSavedStats(), Model\GetServiceStatus(), Pf\GetStateList(), Model\GetStatsFileInfo(), Model\GetValue(), System\IfUpDown(), System\InitGraphs(), Model\IsInlineAnchor(), Model\IsLogFileModified(), Model\IsRunning(), Model\Kill(), Model\KillPid(), RuleSet\load(), System\NetStart(), Rule\parse(), RuleSet\parseInlineRules(), Pf\parsePfIfsInfo(), Pf\parsePfQueueInfo(), Pf\parsePfRulesInfo(), Model\Pkill(), Model\PrepareFileForDownload(), Model\ReplaceRegexp(), Pf\RunPfInfoCmd(), Model\SaveStats(), Model\SelectLogFile(), Model\SetConfValue(), System\SetDateTime(), System\SetLogsConfig(), Model\SetNewsyslogConfig(), Model\SetNVP(), Model\SetPassword(), Dhcpd\Start(), Model\Start(), Collectd\Stop(), Model\UpdateTmpLogFile(), RuleSet\validate(), Rule\validate(), ValidateArgs(), Rule\validateArrayValues(), ValidateCommand(), Rule\validateKeyDef(), and Rule\validateValue().
Error()
Error ($msg)
Sets or updates $Error with the given message.
Error strings are accumulated in global $Error var and returned to View.
Parameters
string $msg Error message.
Definition at line 131 of file include.php.
{
    global $Error;
    if ($Error === '') {
        $Error= $msg;
    }
    else if ($msg !== '') {
        $Error.= "\n".$msg;
    }
}
References $Error.
Referenced by System\_getDynamicGateway(), System\AutoConfig(), Model\CopyLogFileToTmp(), Model\CreateUser(), System\DaemonizedRotateAllLogFiles(), System\DaemonizedRotateLogFile(), Model\DeleteFile(), System\DeleteStats(), System\GenerateSSLKeyPair(), Model\GetProcList(), Model\getRrdValue(), Model\GetServiceStatus(), Pf\GetStateList(), Model\GetStatus(), System\getSystemGateway(), System\IfUpDown(), System\InitGraphs(), Model\IsInlineAnchor(), Model\IsRunning(), Model\Kill(), Model\KillPid(), RuleSet\load(), System\NetStart(), RuleSet\parseInlineRules(), Model\Pkill(), Model\PrepareFileForDownload(), System\reloadPfRules(), Pf\RunPfInfoCmd(), Model\SetConfValue(), System\SetDateTime(), System\SetIf(), Model\SetPassword(), Model\Start(), Pf\Start(), Pf\Stop(), RuleSet\validate(), Rule\validate(), ValidateArgs(), Rule\validateArrayValues(), ValidateCommand(), Model\ValidateFile(), Model\ValidateFileExists(), Rule\validateKeyDef(), and Rule\validateValue().
Output()
Output ($msg)
Sets or updates $Output with the given message.
Output strings are accumulated in global $Output var and returned to View.
$msg may be the output of another function call. So, we first check to see if it is FALSE, meaning the function had failed or not.
Attention
Note that we never send bool messages.
Parameters
string $msg Output message.
Returns
bool TRUE on success, FALSE on fail.
Definition at line 108 of file include.php.
{
    global $Output;
    if ($msg !== FALSE) {
        if ($Output === '') {
            $Output= $msg;
        }
        else if ($msg !== '') {
            $Output.= "\n".$msg;
        }
        return TRUE;
    }
    return FALSE;
}
References $Output.
Referenced by Model\GetAllStats(), Dhcpd\GetArpTable(), Dhcpd\GetArpTableLineCount(), System\GetConfig(), Model\GetConfigValues(), Model\GetDateTime(), Model\GetDefaultLogFile(), System\GetDynamicGateway(), Model\GetExtIf(), Model\GetFileLineCount(), Symon\GetGraph(), System\GetHosts(), System\GetIfConfig(), Dhcpd\GetIfs(), Model\GetIntIf(), Model\GetLastLogs(), Dhcpd\GetLeases(), Dhcpd\GetLeasesLineCount(), Dnsmasq\GetListenOn(), Model\GetLiveLogs(), Model\GetLogFilesList(), Model\GetLogs(), Openssh\GetLogs(), Pf\GetLogs(), System\GetLogsConfig(), Model\GetLogStartDate(), System\GetMFSConfig(), Model\GetModuleStatus(), System\GetMyName(), System\GetNameServer(), Dhcpd\GetOption(), System\GetPartitions(), Pf\GetPfIfsInfo(), Pf\GetPfInfo(), Pf\GetPfQueueInfo(), Pf\GetPfRulesInfo(), Model\GetPhyIfs(), Model\GetProcList(), Model\GetProcStatLines(), Dhcpd\GetRange(), Model\GetReloadRate(), System\GetRemoteTime(), System\GetRootEmail(), System\GetServiceStartStatus(), Model\GetServiceStatus(), Pf\GetStateCount(), Pf\GetStateList(), System\GetStaticGateway(), Model\GetStats(), Model\GetSysCtl(), System\GetSystemInfo(), Collectd\GetVersion(), Dnsmasq\GetVersion(), Httpd\GetVersion(), Model\GetVersion(), Model\PrepareFileForDownload(), Symon\RenderLayout(), Pf\RunPfInfoCmd(), Model\SelectLogFile(), and System\UpdateMailAliases().
Variable Documentation
$Error
$Error = ''
Definition at line 93 of file include.php.
Referenced by Error().
$Output
$Output = ''
Definition at line 92 of file include.php.
Referenced by ConfigMFS(), EnableHostap(), GenerateSSLKeyPair(), RuleSet\load(), Output(), View\ProcessStartStopRequests(), and RuleSet\test().
$ROOT
$ROOT = dirname(dirname(dirname(__FILE__)))
Definition at line 25 of file include.php.
$SRC_ROOT
$SRC_ROOT = dirname(dirname(__FILE__))
Definition at line 26 of file include.php.
ASTERISK
const ASTERISK 1048576
Definition at line 88 of file include.php.
Referenced by System\__construct().
BOOL
const BOOL 32
Definition at line 73 of file include.php.
Referenced by Model\__construct(), and System\__construct().
CONFNAME
const CONFNAME 2097152
Definition at line 89 of file include.php.
Referenced by Model\__construct().
DATETIME
const DATETIME 131072
Definition at line 85 of file include.php.
Referenced by System\__construct().
EMAIL
const EMAIL 65536
Definition at line 84 of file include.php.
Referenced by System\__construct().
EMPTYSTR
const EMPTYSTR 256
Definition at line 76 of file include.php.
Referenced by Model\__construct(), and System\__construct().
FILEPATH
const FILEPATH 2
Definition at line 69 of file include.php.
Referenced by Model\__construct(), System\__construct(), and ValidateArgs().
HOST
const HOST 16384
Definition at line 82 of file include.php.
Referenced by System\__construct().
IPADR
const IPADR 8192
Definition at line 81 of file include.php.
Referenced by Dhcpd\__construct(), and System\__construct().
IPADRLIST
const IPADRLIST 2048
Definition at line 79 of file include.php.
IPRANGE
const IPRANGE 262144
Definition at line 86 of file include.php.
Referenced by Pf\__construct().
JSON
const JSON 128
Definition at line 75 of file include.php.
Referenced by System\__construct().
MFSSIZE
const MFSSIZE 268435456
Definition at line 90 of file include.php.
Referenced by System\__construct().
NAME
const NAME 4
Definition at line 70 of file include.php.
Referenced by Dhcpd\__construct(), Dnsmasq\__construct(), Model\__construct(), Pf\__construct(), Symon\__construct(), and System\__construct().
NONE
const NONE 1
Shell command argument types.
Attention
PHP is not compiled, otherwise would use bindec().
Warning
Do not use bitwise shift operator either, would mean 100+ shifts for constant values!
Definition at line 68 of file include.php.
Referenced by Dhcpd\__construct(), Model\__construct(), Pf\__construct(), Symon\__construct(), System\__construct(), and ComputeArgCounts().
NUM
const NUM 8
Definition at line 71 of file include.php.
Referenced by Dhcpd\__construct(), Model\__construct(), Pf\__construct(), Symon\__construct(), and System\__construct().
REGEXP
const REGEXP 512
Definition at line 77 of file include.php.
Referenced by Dhcpd\__construct(), Model\__construct(), Pf\__construct(), and System\__construct().
SAVEFILEPATH
const SAVEFILEPATH 64
Definition at line 74 of file include.php.
SERIALARRAY
const SERIALARRAY 1024
Definition at line 78 of file include.php.
Referenced by Model\__construct().
SHA1STR
const SHA1STR 16
Definition at line 72 of file include.php.
Referenced by Model\__construct().
STR
const STR 4096
Definition at line 80 of file include.php.
Referenced by Model\__construct(), and System\__construct().
TAIL
const TAIL 524288
Definition at line 87 of file include.php.
Referenced by Dhcpd\__construct(), Model\__construct(), and Pf\__construct().
URL
const URL 32768
Definition at line 83 of file include.php.
Referenced by System\__construct().