PF Firewall: Model Namespace Reference
Model Namespace Reference
Model of MVC: Generally, the Model is responsible for executing commands from the View.
Data Structures
class _Include
class AfTo
Class for AF Translation rules.
class Anchor
Class for Anchor rules.
class Antispoof
class BinatTo
class Blank
class Comment
class DivertPacket
class DivertTo
class Filter
class FilterBase
class Limit
class LoadAnchor
class Macro
class NatBase
class NatTo
class Option
class Queue
class RdrTo
class Route
class Rule
Base class for all model rule types.
class RuleSet
Loads, validates, parses, and generates a list of rules.
class Scrub
class State
class Table
class Timeout
Functions
IsInlineAnchor ($str, $force=FALSE)
Checks and validates any inline rules.
Detailed Description
Model of MVC: Generally, the Model is responsible for executing commands from the View.
In PFRE, the Model:
Loads rules from strings given to it or from files in the file system
Generates rules or rulesets given by the View
Validates the values in rules: Untaints all externally supplied data
Tests rules using pfctl, and returns the test results
Installs, saves, or deletes rule files
Authenticates users
Configures PFRE settings
Function Documentation
IsInlineAnchor()
IsInlineAnchor ($str, $force = FALSE)
Checks and validates any inline rules.
Since we create a new RuleSet object for each nested anchor, we limit the number of nesting.
Parameters
string $str List of rule definitions in an array.
bool $force If set, continues checking and validating even if there are errors or $MaxAnchorNesting is reached.
Returns
bool TRUE if $str has inline anchor.
Definition at line 183 of file Anchor.php.
{
    global $LOG_LEVEL, $Nesting, $MaxAnchorNesting;
    $result= FALSE;
    // Do not allow more than $MaxAnchorNesting count of nested inline rules
    $max= $Nesting + 1 > $MaxAnchorNesting;
    if ($max) {
        Error(_('Validation Error') . ': ' . _('Reached max nesting for inline anchors') . ': <pre>' . htmlentities(print_r($str, TRUE)) . '</pre>');
        ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Validation Error: Reached max nesting for inline anchors: $str");
    }
    if (!$max || $force) {
        $Nesting++;
        $ruleSet= new RuleSet();
        $result= $ruleSet->parse($str, $force);
        if (!$result) {
            if (LOG_DEBUG <= $LOG_LEVEL) {
                Error(_('Validation Error') . ': ' . _('Invalid inline rules, parser output') . ': <pre>' . htmlentities(print_r(json_decode(json_encode($ruleSet), TRUE), TRUE)) . '</pre>');
            }
            ctlr_syslog(LOG_NOTICE, __FILE__, __FUNCTION__, __LINE__, 'Validation Error: Invalid inline rules: ' . print_r(json_decode(json_encode($ruleSet), TRUE), TRUE));
        }
        $Nesting--;
    }
    return $result;
}
References $force, $LOG_LEVEL, $MaxAnchorNesting, ctlr_syslog(), Error(), and IsInlineAnchor().
Referenced by IsInlineAnchor().