PF Firewall: src/Controller/sh.php File Reference
sh.php File Reference
Login shell for users.
Variables
$ROOT = dirname(dirname(dirname(__FILE__)))
$SRC_ROOT = dirname(dirname(__FILE__))
if(filter_has_var(INPUT_SERVER, 'SERVER_ADDR')) $ArgV = array_slice($argv, 1)
This is a command line tool, should never be requested on the web interface.
if($ArgV[0]==='-c') $retval = 1
$args = implode(' ', $ArgV)
if(!ExpandArgs($ArgV, $Locale, $View, $Command)) if (!array_key_exists($View, $ModelFiles))
if(!ValidateCommand($ArgV, $Locale, $View, $Command, TRUE, $Model)) $cwd = dirname(__FILE__)
$encoded = implode(' ', $encoded)
out __pad0__
out $Error
if($encoded !==NULL) else
Detailed Description
Login shell for users.
We set the login shells of admin and user users to sh.php.
Using a shell script to pass args to the Controller commands would expand those args, hence could cause security issues.
Now instead we make sure the args are never expanded and the users cannot drop to a command shell:
use sh.php as login shell
pass all args to it as an ssh command (the -c option of phpseclib channel exec), without any shell expansion
validate all args within sh.php
convert them to a string enclosed between single quotes, so no expansion again
exec ctlr.php passing the args string to it
Todo:
Continually check for security issues.
Definition in file sh.php.
Variable Documentation
$args
$args = implode(' ', $ArgV)
Definition at line 76 of file sh.php.
Referenced by Net_SSH2\_define_array(), Net_SSH2\_login(), RRDTool\graph(), hash2cmdline(), Cache\insert(), and Net_SSH2\login().
$ArgV
if (filter_has_var(INPUT_SERVER, 'SERVER_ADDR')) $ArgV = array_slice($argv, 1)
This is a command line tool, should never be requested on the web interface.
Definition at line 66 of file sh.php.
$cwd
if (!ValidateCommand($ArgV, $Locale, $View, $Command, TRUE, $Model)) $cwd = dirname(__FILE__)
Definition at line 98 of file sh.php.
$encoded
$encoded = implode(' ', $encoded)
Definition at line 103 of file sh.php.
$Error
out $Error
Definition at line 108 of file sh.php.
$retval
out $retval = 1
Definition at line 73 of file sh.php.
$ROOT
$ROOT = dirname(dirname(dirname(__FILE__)))
Todo:
Is there a better way?
Definition at line 44 of file sh.php.
$SRC_ROOT
$SRC_ROOT = dirname(dirname(__FILE__))
Definition at line 45 of file sh.php.
__pad0__
out __pad0__
Definition at line 107 of file sh.php.
else
if ($encoded !==NULL) else
Initial value:
{
    ctlr_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, 'Failed encoding output, error, and retval: '.print_r($msg, TRUE))
Definition at line 113 of file sh.php.
if
if(!ExpandArgs($ArgV, $Locale, $View, $Command)) if(!array_key_exists($View, $ModelFiles)) (! array_key_exists $View, $ModelFiles)
Definition at line 83 of file sh.php.