PF Firewall: src/View/symon/tools.inc File Reference
tools.inc File Reference
Functions
hash2cmdline (&$args)
get_extension ($filename)
normalise_filename ($filename)
save ($filename, &$data)
load ($filename)
config_error ($item, $problem)
runtime_error ($problem)
warning ($problem)
Function Documentation
config_error()
config_error ($item, $problem)
Definition at line 105 of file tools.inc.
{
    global $symon;
    print("\xa\xa".'<b>check setup.inc: $symon["'.$item.'"]="'.
    $symon[$item].'" '.$problem);
    exit(1);
}
References $symon, exit, and print.
Referenced by Layout\__construct(), Cache\__construct(), RRDTool\__construct(), Layout\_generate_default(), and Layout\_generate_host().
get_extension()
get_extension ($filename)
Definition at line 45 of file tools.inc.
{
    preg_match("/\.([^\.]+)$/", $filename, $match);
    if (isset($match[1])) {
    return $match[1];
    } else {
    return '';
    }
}
Referenced by Symon\RenderLayout().
hash2cmdline()
hash2cmdline (& $args)
Definition at line 34 of file tools.inc.
{
    reset($args);
    $cmdline = '';
    foreach($args as $key => $value) {
    $cmdline .= " ".escapeshellarg($value);
    }
    return $cmdline;
}
References $args.
Referenced by RRDTool\graph().
load()
load ($filename)
Definition at line 88 of file tools.inc.
{
    global $symon;
    $fh = fopen($filename, 'r');
    if (!$fh) {
    runtime_error('tools: cannot open file "'.$filename.'" for reading');
    return 0;
    }
    $data = fread($fh, $symon['loadbuffer']);
    fclose($fh);
    return $data;
}
References $symon, and runtime_error().
Referenced by Symon\RenderLayout(), and RuleSet\validate().
normalise_filename()
normalise_filename ($filename)
Definition at line 54 of file tools.inc.
{
    /* remove basename and trailing extension from filename */
    $filename = basename($filename);
    if (preg_match("/^([^\.]+)/", $filename, $match)) {
    $filename = $match[1];
    }
    /* remove all but lowercase and digits */
    $filename = preg_replace("/[^a-z0-9_]/", '', $filename);
    return $filename;
}
Referenced by Layout\__construct(), Layout\_load(), and Lexer\load().
runtime_error()
runtime_error ($problem)
Definition at line 112 of file tools.inc.
{
    print("\xa\xa<b>".$problem.'</b>');
    error_log($problem);
    exit(1);
}
References exit, and print.
Referenced by Layout\__construct(), Layout\_add_group(), Layout\_add_item(), Cache\_cache(), Layout\_generate_default(), Layout\_generate_host(), Lexer\_get_chr_and_nl(), Lexer\_get_next_line(), Layout\_load(), Cache\_load(), Lexer\_next_token(), RRDTool\_test(), Graph\_url(), Cache\expire_key(), Session\getformconstrained(), Session\getformdefault(), Cache\insert(), load(), Lexer\load(), output_picture(), Lexer\parse_error(), and save().
save()
save ($filename, & $data)
Definition at line 66 of file tools.inc.
{
    $fh = fopen($filename, 'w');
    if (!$fh) {
    runtime_error('tools: cannot open file "'.$filename.'" for writing');
    return 0;
    }
    if (is_array($data)) {
    $mydata = join("\xa", $data);
    } else {
    $mydata = $data;
    }
    $result = fwrite($fh, $mydata);
    fflush($fh);
    fclose($fh);
    return $result;
}
References runtime_error().
Referenced by Cache\insert().
warning()
warning ($problem)
Definition at line 118 of file tools.inc.
{
    print("\xa\xa<b>".$problem.'</b>');
    error_log($problem);
}
References print.
Referenced by Graph\_makevars(), Graph\_parse_filename(), Option\editDebug(), and get_template().