PF Firewall: src/View/lib/vars.php File Reference
vars.php File Reference
Required includes and vars.
Variables
$ROOT = dirname(dirname(dirname(dirname(__FILE__))))
$SRC_ROOT = dirname(dirname(dirname(__FILE__)))
$Menu = array()
$LogConf = array()
$PFFW_MODULES
Left menu items with captions and user permissions.
if(isset($_SESSION['Timeout'])) elseif(isset($_SESSION[ 'USER']) &&in_array($_SESSION[ 'USER'], $ALL_USERS)) if(!isset($_SESSION['USER'])|| $_SESSION['USER']=='loggedout') $IMG_PATH = '/images/'
Path to image files used in help boxes and links.
$Status2Images
$StatusTitles
$TopMenu = str_replace('.php', '', basename(filter_input(INPUT_SERVER, 'PHP_SELF')))
$Submenu = ''
const PRINT_COUNT TRUE
Used as arg to PrintProcessTable() to print the number of processes at the top.
$Reload = FALSE
$CustomHiddenInputs = ''
Detailed Description
Required includes and vars.
Attention
TAB size throughout this source code is 4 spaces.
Bug:
There is partial PHP support in Doxygen, thus there are many issues.
Definition in file vars.php.
Variable Documentation
$CustomHiddenInputs
$CustomHiddenInputs = ''
Definition at line 124 of file vars.php.
$IMG_PATH
if(isset($_SESSION[ 'Timeout'])) elseif(isset($_SESSION['USER']) &&in_array($_SESSION['USER'], $ALL_USERS)) if (!isset($_SESSION[ 'USER'])||$_SESSION[ 'USER']=='loggedout') $IMG_PATH = '/images/'
Path to image files used in help boxes and links.
Definition at line 92 of file vars.php.
Referenced by DisplayModuleStatus(), Rule\editHelp(), PrintHelpWindow(), PrintNVPs(), and View\PrintStatusForm().
$LogConf
$LogConf = array()
Definition at line 34 of file vars.php.
$Menu
$Menu = array()
Definition at line 33 of file vars.php.
$PFFW_MODULES
$PFFW_MODULES
Left menu items with captions and user permissions.
Todo:
Remove this line, but needed for rule editor for now
Definition at line 41 of file vars.php.
$Reload
$Reload = FALSE
Definition at line 123 of file vars.php.
$ROOT
$ROOT = dirname(dirname(dirname(dirname(__FILE__))))
Definition at line 28 of file vars.php.
$SRC_ROOT
$SRC_ROOT = dirname(dirname(dirname(__FILE__)))
Definition at line 29 of file vars.php.
$Status2Images
$Status2Images
Initial value:
= array(
    'C' => 'critical.png',
    'E' => 'error2.png',
    'W' => 'warning2.png',
    'R' => 'running.png',
    'S' => 'stop.png',
    'N' => 'noerror.png',
    'U' => 'warning2.png',
    )
Definition at line 95 of file vars.php.
Referenced by DisplayModuleStatus(), and View\PrintStatusForm().
$StatusTitles
$StatusTitles
Initial value:
= array(
    'C' => _TITLE('Critical Error'),
    'E' => _TITLE('Error'),
    'W' => _TITLE('Warning'),
    'R' => _TITLE('Running'),
    'S' => _TITLE('Stopped'),
    'N' => _TITLE('No Errors'),
    'U' => _TITLE('Unknown'),
    )
Definition at line 105 of file vars.php.
Referenced by DisplayModuleStatus(), and View\PrintStatusForm().
$Submenu
$Submenu = ''
Definition at line 118 of file vars.php.
$TopMenu
$TopMenu = str_replace('.php', '', basename(filter_input(INPUT_SERVER, 'PHP_SELF')))
Definition at line 117 of file vars.php.
Referenced by PrintLiveLogHeaderForm(), ProcessNavigationButtons(), ProcessStartLine(), SetRefreshInterval(), SetSubmenu(), and UpdateLogsPageSessionVars().
PRINT_COUNT
const PRINT_COUNT TRUE
Used as arg to PrintProcessTable() to print the number of processes at the top.
Definition at line 121 of file vars.php.