PF Firewall: src/View/lib/view.php File Reference
view.php File Reference
View base class.
Data Structures
class View
Functions
_MENU ($str)
For classifying gettext strings into files.
_CONTROL ($str)
For classifying gettext strings into files.
_NOTICE ($str)
For classifying gettext strings into files.
_HELPBOX ($str)
For classifying gettext strings into files.
_HELPWINDOW ($str)
For classifying gettext strings into files.
_TITLE2 ($str)
For classifying gettext strings into files.
_HELPBOX2 ($str)
For classifying gettext strings into files.
Detailed Description
View base class.
Definition in file view.php.
Function Documentation
_CONTROL()
_CONTROL ($str)
For classifying gettext strings into files.
Definition at line 650 of file view.php.
{
    return _($str);
}
Referenced by RuleSet\cancel(), Rule\dispEditLinks(), AfTo\edit(), Anchor\edit(), Antispoof\edit(), Blank\edit(), Comment\edit(), DivertPacket\edit(), DivertTo\edit(), LoadAnchor\edit(), Macro\edit(), Queue\edit(), Route\edit(), Scrub\edit(), Table\edit(), Rule\editDeleteValueLinks(), FilterBase\editFilterHead(), FilterBase\editFilterOpts(), Rule\editHead(), Filter\editInterface(), Rule\editInterface(), NatBase\editNat(), FilterBase\editQueue(), Option\editReassemble(), Option\editSkip(), State\editState(), Option\editSyncookies(), Table\editValues(), and RuleSet\save().
_HELPBOX()
_HELPBOX ($str)
For classifying gettext strings into files.
Definition at line 662 of file view.php.
{
    return _($str);
}
Referenced by _Include\editInclude(), PrintDateTimeForm(), and PrintHostsForm().
_HELPBOX2()
_HELPBOX2 ($str)
For classifying gettext strings into files.
Definition at line 680 of file view.php.
{
    return _($str);
}
Referenced by Httpd\__construct(), Openssh\__construct(), PrintDHCPInterfaceForm(), PrintDHCPOptionForm(), PrintDHCPRangeOptionForm(), and PrintReloadConfigForm().
_HELPWINDOW()
_HELPWINDOW ($str)
For classifying gettext strings into files.
Definition at line 668 of file view.php.
{
    return _($str);
}
Referenced by Dhcpd\__construct(), Dnsmasq\__construct(), Ftpproxy\__construct(), Ctlrlogs\__construct(), Httpd\__construct(), Httpdlogs\__construct(), Wuilogs\__construct(), Monitoring\__construct(), Openssh\__construct(), Pf\__construct(), System\__construct(), PrintLiveLogsHelp(), and PrintLogsHelp().
_MENU()
_MENU ($str)
For classifying gettext strings into files.
Definition at line 644 of file view.php.
{
    return _($str);
}
Referenced by HTMLHeader().
_NOTICE()
_NOTICE ($str)
For classifying gettext strings into files.
Definition at line 656 of file view.php.
{
    return _($str);
}
Referenced by View\CheckAuthentication(), RuleSet\comment(), RuleSet\move(), RuleSet\parse(), PrintDateTimeForm(), View\PrintStatusForm(), ProcessStartLine(), RuleSet\separate(), SetRefreshInterval(), RuleSet\uncomment(), and UpdateLogsPageSessionVars().
_TITLE2()
_TITLE2 ($str)
For classifying gettext strings into files.
Definition at line 674 of file view.php.
{
    return _($str);
}
Referenced by Httpd\__construct(), Openssh\__construct(), PrintDHCPInterfaceForm(), PrintDHCPOptionForm(), PrintDHCPRangeOptionForm(), View\PrintProcessTableHeader(), and PrintReloadConfigForm().